### ISSUE TITLE
latest alpha snapshot cannot be downloaded

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#10012]
### Steps to reproduce:
1. go to the help menu, and press check for updates,
2. press download and install,
3. skip donation and wait some seconds
### Actual behavior:
error is shown, and the following is displayed in the log:
ERROR - updateCheck.UpdateDownloader._bg (18:41:58.800):
Error downloading https://ci.appveyor.com/api/buildjobs/vg63itgyy5xrff9m/artifacts/output/nvda_snapshot_alpha-18266,1af87759.exe
Traceback (most recent call last):
  File "updateCheck.pyc", line 601, in _bg
  File "updateCheck.pyc", line 624, in _download
  File "urllib\request.pyc", line 222, in urlopen
  File "urllib\request.pyc", line 531, in open
  File "urllib\request.pyc", line 641, in http_response
  File "urllib\request.pyc", line 563, in error
  File "urllib\request.pyc", line 503, in _call_chain
  File "urllib\request.pyc", line 755, in http_error_302
  File "urllib\request.pyc", line 531, in open
  File "urllib\request.pyc", line 641, in http_response
  File "urllib\request.pyc", line 569, in error
  File "urllib\request.pyc", line 503, in _call_chain
  File "urllib\request.pyc", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: The specified blob does not exist.
# my south slavic thinking outloud says that it can be because of the latest flake8 included
### Expected behavior:
Update process should work normaly
#### NVDA installed/portable/running from source:
installed, the alpha which should be updated
#### NVDA version:
alpha-18245,4e634980
#### Windows version:
win 10 1903
#### Name and version of other software in use when reproducing the issue:
n/a
#### Other information about your system:
n/a
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a

**Comment by DrSooom** [comment]
HTTP Error 302: Moved temporarily
HTTP Error 404: File not found

Perhaps wrong URL or Redirect.

**Comment by gdata1** [comment]
I have that mistake, too.

**Comment by dingpengyu** [comment]
> I have that mistake, too.
The official build page doesn't download properly, I downloaded the update from the appveyor build page.
[nvda alpha-18266](https://ci.appveyor.com/project/NVAccess/nvda/builds/26404684/artifacts)

**Comment by DrSooom** [comment]
See: https://www.nvaccess.org/files/nvda/snapshots/

**Comment by feerrenrut** [comment]
This should now be fixed so I'll close this. Please comment/reopen if you still encounter problems.
