### ISSUE TITLE
StopItteration, might be from python3 transition

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#10038]
### Steps to reproduce:

1. go to google.com
2. press ctrl+end.
3. press shift+h.
4. press n.

### Actual behavior:

```
Speaking ['blank']
IO - inputCore.InputManager.executeGesture (05:24:28.097):
Input: kb(laptop):n
ERROR - scriptHandler.executeScript (05:24:28.137):
error executing script: <bound method BrowseModeTreeInterceptor.addQuickNav.<locals>.<lambda> of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x0B3DAE50>> with gesture 'n'
Traceback (most recent call last):
  File "browseMode.pyc", line 1733, in _iterNotLinkBlock
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 190, in executeScript
  File "browseMode.pyc", line 430, in <lambda>
  File "browseMode.pyc", line 402, in _quickNavScript
RuntimeError: generator raised StopIteration
IO - inputCore.InputManager.executeGesture (05:24:29.274):
Input: kb(laptop):NVDA+f1
```

### Expected behavior:

message about no more blocks of text.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:

alpha-18290,7b5cd2d0

probably caused by threshold.

**Comment by DrSooom** [comment]
@derekriemer: Please list all web browsers (incl. version), where this issue occurs. Thanks.
