### ISSUE TITLE
Error in alpha with built-in audacity appmod

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#10103]
### Steps to reproduce:

1. open audacity.
2. select audio. ctrl+a works.
3. press alt+c, and press c until "compresser" is found.
4. press enter.
5. press tab.

### Actual behavior:

```
ERROR - eventHandler.executeEvent (23:07:33.553):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x03318FF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 150, in executeEvent
  File "eventHandler.pyc", line 163, in doPreGainFocus
  File "api.pyc", line 109, in setFocusObject
  File "baseObject.pyc", line 46, in __get__
  File "baseObject.pyc", line 149, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1695, in _get_container
  File "IAccessibleHandler.pyc", line 950, in findGroupboxObject
  File "NVDAObjects\IAccessible\__init__.pyc", line 48, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 137, in __call__
  File "appModules\audacity.pyc", line 15, in event_NVDAObject_init
AttributeError: 'NoneType' object has no attribute 'replace'
```

### Expected behavior:

Items in the UI read.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
Version: alpha-18399,26485a09

#### Windows version:
^10

#### Name and version of other software in use when reproducing the issue:
Audacity: 2.3.1

**Comment by josephsl** [comment]
Hi, ah, another object model issue we need to handle. I bet there are more things of this nature we haven’t gotten to fixing once and for all. CC @LeonardDer, a P2. Thanks.
