### ISSUE TITLE
More accurate error text needed when opening add-ons with faulty manifests

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#10135]
### Is your feature request related to a problem? Please describe.

When attempting to install an add-on with errors in its manifest, the error text is misleading.

For example, if the minimum NVDA version is set to None instead of some actual version number, the error that is shown, captured from Speech History, is:

```
Error  dialog
Failed to open add-on package file at N:\test\test_add-on-0.1.nvda-addon - missing file or invalid file format
```

### Describe the solution you'd like

An error that says something closer to what actually happened.
Perhaps:

```
Failed to install add-on package file N:\test\test_add-on-0.1.nvda-addon - missing or invalid add-on manifest.
```

### Additional context

The error shown seems to indicate that the add-on package file is the missing file or [the one with the] invalid file format. But the zip package is actually fine. That impression is reinforced by the phrase "failed to open" followed by the add-on package file name. This can cause someone to spend time investigating the wrong thing, when trying to diagnose why an add-on isn't installing.
The actual problem is with the manifest, and the error should say as much.

If you are someone who looks at logs all the time, it is clear what happened, but most users aren't supposed to have to do that.

```
DEBUG - NVDAHelper.nvdaControllerInternal_installAddonPackageFromPath (21:12:44.217):
Requesting installation of add-on from N:\test\test_add-on-0.1.nvda-addon
WARNING - addonHandler._report_manifest_errors (21:12:44.280):
Error loading manifest:
{'docFileName': True, 'description': True, 'author': True, 'url': True, 'lastTestedNVDAVersion': True, 'summary': True, 'minimumNVDAVersion': ValidateError('"None" is not a valid API Version string: None',), 'version': True, 'name': True}
ERROR - gui.addonGui.installAddon (21:12:44.280):
Error opening addon bundle from N:\test\test_add-on-0.1.nvda-addon
Traceback (most recent call last):
  File "gui\addonGui.pyc", line 471, in installAddon
  File "addonHandler\__init__.pyc", line 568, in __init__
AddonError: Manifest file has errors.
```

**Comment by Brian1Gaff** [comment]
I agree here. Indeed failed to install is often all you get till you dig or 
maybe  incompatible. all a little vague. I rather liked the way windows used 
to do it, it would say something had failed, then present a details button 
that  expanded on the issue.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by CyrilleB79** [comment]
Hello
You write:
> ### Describe the solution you'd like
> An error that says something closer to what actually happened.
> Perhaps:
> 
> ```
> Failed to install add-on package file N:\test\test_add-on-0.1.nvda-addon - missing or invalid add-on manifest.
> ```
> 

abd

> The actual problem is with the manifest, and the error should say as much.

I agree the message is misleading for the developer.
But the user does not have to know the nature of the real issue (missing or badly formatted manifest file).
IMO the message should just be labelled such as:
"Could not install add-on ; invalid add-on file."
Then there are two ways:
* A user will look for a newer version of this add-on fixing the issue or report the issue to the developer if no new version is available
* The developer facing this issue wil not get a misleading message and will surely look t=at the log to investigate.





> 
> If you are someone who looks at logs all the time, it is clear what happened, but most users aren't supposed to have to do that.
> 
> ```
> DEBUG - NVDAHelper.nvdaControllerInternal_installAddonPackageFromPath (21:12:44.217):
> Requesting installation of add-on from N:\test\test_add-on-0.1.nvda-addon
> WARNING - addonHandler._report_manifest_errors (21:12:44.280):
> Error loading manifest:
> {'docFileName': True, 'description': True, 'author': True, 'url': True, 'lastTestedNVDAVersion': True, 'summary': True, 'minimumNVDAVersion': ValidateError('"None" is not a valid API Version string: None',), 'version': True, 'name': True}
> ERROR - gui.addonGui.installAddon (21:12:44.280):
> Error opening addon bundle from N:\test\test_add-on-0.1.nvda-addon
> Traceback (most recent call last):
>   File "gui\addonGui.pyc", line 471, in installAddon
>   File "addonHandler\__init__.pyc", line 568, in __init__
> AddonError: Manifest file has errors.
> ```

**Comment by Adriani90** [comment]
@CyrilleB79, @XLTechie is this still an issue in NVDA 2024.2 or last alpha?

**Comment by CyrilleB79** [comment]
@XLTechie would you agree with the following message instead?
"Could not install add-on. Invalid add-on file: N:\test\test_add-on-0.1.nvda-addon"

The user does not need to know of manifest issues or any other error description internal to the add-on or to NVDA. This message should be enough for the user to try to download the file again or to contact the add-on author to report the issue.

From the add-on developer's point of view, this message should be enough to encourage them to open the log and look for details on the cause of the issue;

**Comment by XLTechie** [comment]
@CyrilleB79 Now that users have little reason to be manually editing manifests because of easy incompatibility overrides, your proposed language is more acceptable than it would have been before the store (when this issue was opened).

I'm still not thrilled with vague error messages--even Windows usually provides a way to get more information, as @Brian1Gaff pointed out.
But what you propose is better than the overly generalized message used now.
