### ISSUE TITLE
New UIA support and Braille not working

### ISSUE THREAD

**Issue by vincent-lg** [nvaccess/nvda#10191]
The support for UIA in console leads to a lot of problems in Braille.

## Steps to reproduce

1. Activate the UIA support for the Windows console in NVDA preferences.
2. Start a console with a Braille display.
3. And browse in review. No need to go far to see the problems.

## Excerpt

Here is an excerpt for my own Windows console.  When I open it, the review cursor is able to read the following:

```
Microsoft Windows [Version 10.0.17763.678]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Admin>
```

My Braille display, when scrolling with the review cursor (with pavnum7 and pavnum9 on a computer keyboard) reads the following:

```
78]
 Corporation. All rights reserved.

CC:\Users\Admin>
```

(The CC on the last line doesn't appear the first time, it only appears when browsing back to it, which shows some problems.)

So I'd say there is a problem.  And when using the Braille keys to scroll, things get even more weird.  I don't think I need to supply a full transcript: comparing outputs in the previous transcripts should show lots of problems.

So I would highly advise: please don't merge it or do some proper testing in Braille.  Although the feature can be turned off, it's definitely on by default.

I'll be happy to do further testing if need be.

## Information:

- Windows 10 (see signature above if needed)
- NVDA snapshot: `alpha-18590,50619158`
- Braille display: HandyTech ActiveBraille

Thanks!

**Comment by Adriani90** [comment]
cc: @codeofdusk, @leonardder

**Comment by leonardder** [comment]
Thanks for your report. I can definitely reproduce this and will try to 
look into this sooner or later, but at least before 2019.3 comes out.

**Comment by leonardder** [comment]
Turns out that the collapse method is broken when invoked for a textInfo that's positioned at the start of a line.

**Comment by leonardder** [comment]
Quick investigation revealed that it looks pretty complicated to fix this. Whatever I do with moving endpoints of the range, when positioned at the first character in the text, it simply refuses to collapse.

**Comment by zstanecic** [comment]
Hi to all!

Now when testing NVDA latest alpha I get the following errors with the uia implementation:

ERROR - eventHandler.executeEvent (08:56:37.791) - MainThread (7448):

error executing event: gainFocus on <NVDAObjects.Dynamic_OutlookUIAWordDocumentWordDocumentEditableTextWithAutoSelectDetectionUIAWindowNVDAObject object at 0x067E5E30> with extra args of {}

Traceback (most recent call last):

  File "eventHandler.pyc", line 150, in executeEvent

  File "eventHandler.pyc", line 163, in doPreGainFocus

  File "api.pyc", line 147, in setFocusObject

  File "api.pyc", line 254, in setNavigatorObject

  File "documentBase.pyc", line 24, in makeTextInfo

  File "treeInterceptorHandler.pyc", line 170, in __init__

  File "NVDAObjects\UIA\__init__.pyc", line 297, in __init__

NotImplementedError: UIAutomationTextRangeArray is empty

This happened when I pressed ctrl+r to bring the reply message dialog. 

There is also an error in the microsof word when creating the new word document:

ERROR - RPC process 9136 (nvda_slave.exe) (08:52:03.358) - Dummy-1 (8512):

__main__.main:

slave error

Traceback (most recent call last):

  File "nvda_slave.pyw", line 91, in main

  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject

  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject

  File "comtypes\__init__.pyc", line 1245, in GetActiveObject

  File "_ctypes/callproc.c", line 933, in GetResult

OSError: [WinError -2147221021] Операция недоступна

ERROR - eventHandler.executeEvent (08:53:12.010) - MainThread (7448):

error executing event: typedCharacter on <NVDAObjects.UIA.ListItem object at 0x067E5E30> with extra args of {'ch': '\r'}

Traceback (most recent call last):

  File "eventHandler.pyc", line 155, in executeEvent

  File "eventHandler.pyc", line 92, in __init__

  File "eventHandler.pyc", line 100, in next

  File "C:\Users\ninos\AppData\Roaming\nvda\addons\SoundSymbols\globalPlugins\SoundSymbols\__init__.py", line 23, in event_typedCharacter

    nextHandler()

  File "eventHandler.pyc", line 100, in next

  File "NVDAObjects\__init__.pyc", line 1037, in event_typedCharacter

  File "speech\__init__.pyc", line 719, in speakTypedCharacters

  File "api.pyc", line 264, in isTypingProtected

  File "baseObject.pyc", line 42, in __get__

  File "baseObject.pyc", line 145, in _getPropertyViaCache

  File "NVDAObjects\__init__.pyc", line 911, in _get_isProtected

  File "baseObject.pyc", line 42, in __get__

  File "baseObject.pyc", line 145, in _getPropertyViaCache

  File "NVDAObjects\UIA\__init__.pyc", line 1148, in _get_states

  File "NVDAObjects\UIA\__init__.pyc", line 759, in _getUIACacheablePropertyValue

  File "comtypesMonkeyPatches.pyc", line 26, in __call__

_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))

**Comment by lukaszgo1** [comment]
@zstanecic If you are still experiencing these problems please open separate issue for them.
