### ISSUE TITLE
When getting a COM attribute using dynamic dispatch and the call is canceled, the original COMError is raised instead of watchdog.CallCancelled

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#10276]
### Steps to reproduce:
In word, run the following code snippet from the python console:

`for i in range(5000): review._rangeObj.Start == review._rangeObj.End`

### Actual behavior:
On python 3:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "comtypesMonkeyPatches.pyc", line 78, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 168, in __getattr__
  File "comtypes\automation.pyc", line 729, in _invoke
_ctypes.COMError: (-2147418110, 'Aanroep is door het berichtenfilter geannuleerd.', (None, None, None, 0, None))
```

### Expected behavior:
On python 2:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "watchdog.pyo", line 202, in _COMError_init
CallCancelled
```

#### NVDA installed/portable/running from source:
n/a

#### NVDA version:
2019.2 and Alpha

#### Windows version:
Windows 10 version 1093

#### Name and version of other software in use when reproducing the issue:
Word 2016 version 16.0.11929.20300

#### Other information about your system:
N/a

### Other questions
n/a

**Comment by michaelDCurran** [comment]
This should have been handled in merged pr #9795. Clearly there is a situation where this is not working.
