### ISSUE TITLE
Error during the building of nvda in scons

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [nvaccess/nvda#10297]
When i try build nvda with scons i get an error of py2exe in pyython three

**Comment by josephsl** [comment]
Hi, it looks like the sofa is here but the cushions are not i.e. what errors are you getting, which Visual Studio version you’ve got, and did you get all dependencies? Thanks.

**Comment by AlexandrKozlovskiy** [comment]
Traceback (most recent call last):
  File "setup.py", line 253, in <module>
    + getRecursiveDataFiles('documentation', '../user_docs', excludes=('*.t2t', '*.t2tconf', '*/developerGuide.*'))
  File "C:\Users\ksash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\ksash\AppData\Local\Programs\Python\Python37-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\ksash\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\ksash\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 104, in run
    super(py2exe, self).run()
  File "c:\nvda\include\py2exe\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "c:\nvda\include\py2exe\py2exe\distutils_buildexe.py", line 273, in _run
    builder.build()
  File "c:\nvda\include\py2exe\py2exe\runtime.py", line 264, in build
    self.copy_files(destdir)
  File "c:\nvda\include\py2exe\py2exe\runtime.py", line 505, in copy_files
    assert mod.__file__.endswith(EXTENSION_SUFFIXES[0])
AssertionError
scons: *** [dist] Error 1
scons: building terminated because of errors.

**Comment by josephsl** [comment]
CC @LeonardDer

**Comment by leonardder** [comment]
I'd need a full log of the py2exe part of the log, not just the traceback.

It looks like py2exe is collecting something to package on your system which doesn't exist or isn't required on other systems.

Could you also provide information on your version of Windows, and whether it is 32-bit or 64-bit?

**Comment by leonardder** [comment]
@AlexandrKozlovskiy Is this still reproducible?

**Comment by Adriani90** [comment]
@AlexandrKozlovskiy are you available to test if this is still occuring with the last alpha version of NVDA?

**Comment by Adriani90** [comment]
No further updates on this from the initial author. I have built NVDA successfully from source now with Python 3.7.6, so most probably there was a bug in the installation of Python of that specific machine. I am closing this as abandoned, but feel free to comment with updates and we can reopen. Thanks.
