### ISSUE TITLE
Notepad++: read by line does not work if text direction is right-to-left

### ISSUE THREAD

**Issue by mush42** [nvaccess/nvda#10356]
### Steps to reproduce:

* Open Notepad++
* Type some text
* Change the text-direction to be right-to-left. From the view menu, click the menu item that says "Text Direction RTL Ctrl-Alt-R".

### Actual behavior:
NVDA fails to speak anything when navigating the text by line using the up and down arrow keys. Word and character navigation seams to be working alright though.
A look at NVDA's log reveals that the following exception is being raised:

```python
ERROR - scriptHandler.executeScript (22:49:10.781) - MainThread (3076):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_ScintillaIAccessibleScintillaWindowNVDAObject object at 0x05E82AB0>> with gesture 'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "editableText.pyc", line 219, in script_caret_moveByLine
  File "editableText.pyc", line 164, in _caretMovementScriptHelper
  File "editableText.pyc", line 150, in _caretScriptPostMovedHelper
  File "speech\__init__.pyc", line 793, in speakTextInfo
  File "textInfos\offsets.pyc", line 527, in getTextWithFields
  File "baseObject.pyc", line 26, in __get__
  File "textInfos\offsets.pyc", line 545, in _get_text
  File "NVDAObjects\window\scintilla.pyc", line 180, in _getTextRange
  File "winKernel.pyc", line 212, in virtualAllocEx
OSError: [WinError 87] The parameter is incorrect.
```

### Expected behavior:

NVDA ]should read the text when navigating by line regardless of the text direction.

 
#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1 

#### Windows version:
Windows 10Ver1903 (64-bit) build 18362.356

#### Name and version of other software in use when reproducing the issue:
Notepad++ version  7.7.1 (64-bit)

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this issue is still present in the latest alpha builds. Specifically, I've tested with alpha-18874,6cdb7be0.

**Comment by zahra21** [comment]
hello.
i am Zahra from Iran and my language is right to left.
when i copied some text and peisted in notepad++, and used AltControlR to change direction of my text, it did not work and my text remained ltr again.
i tested with notepad++ 7.7 and 7.8 which is released october seven and impossibility of changing direction, i observed on both versions!
i use nvda 2017.2 on windows xp.
as i said, i only tested with 32bit versions of notepad++.

**Comment by mush42** [comment]
Hi @zahra21,

If you're using magnifier, please beware of the conflict between npp's text direction commands and magnifier's mode switching commands,

**Comment by bdorer** [comment]
that's right. If you use windows magnifier it doesn't work with CTRL+Alt+r.
But i'm not able to reproduce this. Could you attach a file to test with? May it is something different.

**Comment by zahra21** [comment]
hi mush42.
no, i never use magnifier or braille.
i use nvda with espeak ng.
i could not set my notepad to shows my files in rtl mode.

**Comment by Adriani90** [comment]
I cannot reproduce this issue with NVDA 2019.3.1 and Notepad++ 7.8.4 64Bit.
@mush42 are you able to test again with the last NVDA Alpha and see if this is still reproducible? Also which Notepad++ version are you using? 64bit or 32bit?

**Comment by mush42** [comment]
Hi @Adriani90,

I use NVDA 2019.3.1, Notepad++ v7.8.4 64-bit, and Windows 10Ver1903 (64-bit).

The problem is still reproducible in my machine with the above setup.

@nvaccess this issue is critical for those users who's language is RTL.

Regards,

**Comment by Adriani90** [comment]
@mush42 how is this now with NVDA 2023.2 and the last version of Notepad++? Can you still reproduce this issue?

**Comment by mush42** [comment]
> @mush42 how is this now with NVDA 2023.2 and the last version of Notepad++? Can you still reproduce this issue?

Yes it is still reproducible with NVDA v2023.2 final.

**Comment by seanbudd** [comment]
@mush42 is this still an issue in the latest version of notepad and NVDA?
