### ISSUE TITLE
Errors with latest Alpha during import of Screen curtain on Windows 7

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#10502]
### Steps to reproduce:
1. Start Latest Alpha on Windows 7. The same error can be reproduced when focusing vision category of settings.
### Actual behavior:
Error sound is played and The following is logged;
ERROR - vision.visionHandler._getProvidersFromFileSystem (22:09:34.114) - MainThread (1192):
Error while importing vision enhancement provider module screenCurtain
Traceback (most recent call last):
  File "vision\visionHandler.pyc", line 58, in _getProvidersFromFileSystem
  File "vision\visionHandler.pyc", line 36, in _getProviderClass
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\screenCurtain.pyc", line 39, in <module>
  File "visionEnhancementProviders\screenCurtain.pyc", line 82, in Magnification
AttributeError: function 'MagShowSystemCursor' not found

### Expected behavior:
No error sound.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
Latest Alpha
#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Alpha from a day ago before integration of Vision GUI. No such problems.

**Comment by DrSooom** [comment]
I thought that Windows 7 don't get the screen curtain feature due to OS limitations. Only Windows 8.1 and later should get it. Please correct me if I'm wrong.

**Comment by zstanecic** [comment]
Yesp, this function is available on win 8 and later

**Comment by Brian1Gaff** [comment]
Yes just ahead of this in this very list was a change to stop profiles 
saving lots of stuff  not intended from this functions point of view, I 
suspect that the code has broken the windows 7 opt out  part of the routine.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----
