### ISSUE TITLE
NVDA does not report objects in Malwarebytes 4.0.4

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#10616]
### Steps to reproduce:
1. INstall Malwarebytes 4.0.4
2. Open it
3. Tab around
4. Use object navigation and route the mouse to different objects

### Actual behavior:
When tabbing around, NVDA does not report anything.
When using object navigation, NVDA reports the objects. When routing the mouse to objects, sometimes I get errors. I could catch following:

```
ERROR - eventHandler.executeEvent (22:55:17.660) - MainThread (8888):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x07AFEA10> with extra args of {'x': 1597, 'y': 931}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1069, in event_mouseMove
  File "api.pyc", line 199, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 748, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 332, in __init__
ValueError: Unknown position None
IO - inputCore.InputManager.executeGesture (22:55:22.163) - winInputHook (9872):
Input: kb(laptop):NVDA+f1
WARNING - fileUtils.getFileVersionInfo (22:55:22.191) - MainThread (8888):
Invalid or unavailable version info attribute for 'C:\\Program Files\\Malwarebytes\\Anti-Malware\\mbam.exe': ProductVersion
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (22:55:24.175) - MainThread (8888):
Developer info for navigator object:
name: 'Auf diesem Computer Premium aktivieren,Auf diesem Computer Premium aktivieren,Lizenzschlüssel'
role: ROLE_EDITABLETEXT
roleText: None
states: STATE_FOCUSABLE
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x07E1B170>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=902, top=884, width=1391, height=95)
value: ''
appModule: <'appModuleHandler' (appName 'mbam', process ID 6808) at address 165c250>
appModule.productName: 'Malwarebytes'
appModule.productVersion: None
TextInfo: <class 'NVDAObjects.UIA.UIATextInfo'>
windowHandle: 1182170
windowClassName: 'Qt5QWindowOwnDCIcon'
windowControlID: 0
windowStyle: -1764818944
extendedWindowStyle: 256
windowThreadID: 14060
windowText: 'Malwarebytes Kostenlos  4.0.4'
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x6307ef8 at 4968440>
UIA automationID: popUpOnboardingWizard.pageActivation.textKeyField
UIA frameworkID: Qt
UIA runtimeID: (42, 1182170, 4, -2147483506)
UIA providerDescription: [pid:6808,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:qwindows.dll)]
UIA className: QQuickTextField_QML_390
UIA patterns available: ValuePattern, LegacyIAccessiblePattern, TextPattern, InvokePattern
```

### Expected behavior:
NVDA should report the objects when tabbing around as it was in the previous version of Malwarebytes.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.3 Beta 1

#### Windows version:
Windows 10 1909 update

#### Name and version of other software in use when reproducing the issue:
Malwarebytes 4.0.4

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, 2019.2.1 does not work either.

**Comment by Adriani90** [comment]
@josephsl, @leonardder could this might be related to new QT versions?
It also seems that NVDA generates an error saying that the version atribute is unknown or so. Is this maybe related to app host versioning?

**Comment by DrSooom** [comment]
@Adriani90: If Qt 5.12.x is used, then yes. Qt 5.9.8, which is used by MuseScore 3.3.x, works fine with NVDA 2019.2.1. See also: https://musescore.org/en/node/285464

**Comment by Adriani90** [comment]
This is fixed in a small update from Malwarebytes, thanks to the great support of @Malwarebytes.
Closing as works for me.
