### ISSUE TITLE
Navigating between messages in Outlook 365 causes NVDA to go silent.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10734]
### Steps to reproduce:

1. Open Outlook.
2. Move to any message (in a folder with multiple messages in it).
3. EITHER press control+tab to move to the preview window or press ENTER to open the message.
4. Press CONTROL+. (CONTROL+PERIOD) to move to the next message.

### Actual behavior:
At Step 4, the new message loads, the focus appears to be in the body of the message, but NVDA is silent.

Additionally, press NVDA+F1 at this point to open the log, and if UIA is enabled in NVDA, nothing happens (press alt twice or change focus somehow, even press down arrow to go to the next line in the message and NVDA comes back).

Log fragments below from the point of pressing control+. or in the case of UIA, to pressing ALT and the ribbon loading.  The main problem for end users is that the new message isn't being read, but the additional error trying to display the log might aid investigation.

NVDA 2019.3beta3 log without UIA enabled:

```
IO - inputCore.InputManager.executeGesture (21:29:46.455) - winInputHook (21284):
Input: kb(desktop):control+.
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (21:29:47.053) - MainThread (28196):
oleacc.AccessibleObjectFromEvent with window 135656, objectID 2297 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (21:29:47.054) - MainThread (28196):
oleacc.AccessibleObjectFromEvent with window 135656, objectID 2303 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (21:29:47.168) - MainThread (28196):
oleacc.AccessibleObjectFromEvent with window 135656, objectID 2307 and childID 0: [WinError -2147467259] Unspecified error
```

NVDA 2019.3 beta 3 log with UIA enabled:

```
IO - inputCore.InputManager.executeGesture (21:25:41.171) - winInputHook (28504):
Input: kb(desktop):control+.
IO - inputCore.InputManager.executeGesture (21:26:21.515) - winInputHook (28504):
Input: kb(desktop):NVDA+f1
DEBUGWARNING - NVDAObjects.UIA.UIATextInfo.__init__ (21:26:21.523) - MainThread (14468):
Could not clone range
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 284, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (21:26:21.523) - MainThread (14468):
error executing script: <bound method GlobalCommands.script_navigatorObject_devInfo of <globalCommands.GlobalCommands object at 0x083BD550>> with gesture 'NVDA+f1'
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 284, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "globalCommands.pyc", line 1577, in script_navigatorObject_devInfo
  File "api.pyc", line 226, in getNavigatorObject
  File "baseObject.pyc", line 26, in __get__
  File "treeInterceptorHandler.pyc", line 239, in _get_NVDAObjectAtStart
  File "baseObject.pyc", line 26, in __get__
  File "NVDAObjects\UIA\__init__.pyc", line 344, in _get_NVDAObjectAtStart
  File "baseObject.pyc", line 26, in __get__
  File "NVDAObjects\UIA\__init__.pyc", line 354, in _get_UIAElementAtStart
  File "NVDAObjects\UIA\__init__.pyc", line 747, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 288, in __init__
RuntimeError: Could not clone range
IO - speech.speak (21:26:25.563) - MainThread (14468):
Speaking [LangChangeCommand ('en'), 'Ribbon Tabs', 'tab control', 'expanded']
```

NVDA 2019.2.1 logs are similar:
Without UIA:

```
IO - inputCore.InputManager.executeGesture (21:35:24.009):
Input: kb(desktop):control+.
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:35:24.686):
oleacc.AccessibleObjectFromEvent with window 135656, objectID 3671 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:35:24.687):
oleacc.AccessibleObjectFromEvent with window 135656, objectID 3674 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:35:24.822):
oleacc.AccessibleObjectFromEvent with window 135656, objectID 3677 and childID 0: [Error -2147467259] Unspecified error
IO - inputCore.InputManager.executeGesture (21:35:29.697):
Input: kb(desktop):NVDA+f1
```

With UIA enabled:

```
IO - inputCore.InputManager.executeGesture (21:32:59.250):
Input: kb(desktop):control+.
IO - inputCore.InputManager.executeGesture (21:33:06.331):
Input: kb(desktop):NVDA+f1
DEBUGWARNING - NVDAObjects.UIA.UIATextInfo.__init__ (21:33:06.335):
Could not clone range
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyo", line 273, in __init__
COMError: (-2146233079, None, (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (21:33:06.335):
error executing script: <bound method GlobalCommands.script_navigatorObject_devInfo of <globalCommands.GlobalCommands object at 0x0552CB50>> with gesture 'NVDA+f1'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 192, in executeScript
  File "globalCommands.pyo", line 1542, in script_navigatorObject_devInfo
  File "api.pyo", line 210, in getNavigatorObject
  File "baseObject.pyo", line 31, in __get__
  File "treeInterceptorHandler.pyo", line 233, in _get_NVDAObjectAtStart
  File "baseObject.pyo", line 31, in __get__
  File "NVDAObjects\UIA\__init__.pyo", line 329, in _get_NVDAObjectAtStart
  File "baseObject.pyo", line 31, in __get__
  File "NVDAObjects\UIA\__init__.pyo", line 339, in _get_UIAElementAtStart
  File "NVDAObjects\UIA\__init__.pyo", line 689, in copy
  File "NVDAObjects\UIA\__init__.pyo", line 277, in __init__
RuntimeError: Could not clone range
IO - speech.speak (21:33:10.819):
Speaking [LangChangeCommand (u'en_US'), u'Ribbon Tabs  tab control  collapsed']

```
### Expected behavior:

NVDA should read the next message.

#### NVDA version:

Installed 2019.3beta 3
Portable 2019.2.1

#### Windows version:

Windows 10 Version: 
1903 build 18362.388 (I have a bug in Windows update and can't update past this for now - but that's a different issue (and unrelated to NVDA)

#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.12325.20280 
 
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.3beta3
2019.2.1

**Comment by CyrilleB79** [comment]
May it be an Outlook issue?
Here with outlook 2016 and without NVDA (Windows Magnifier only):
1. open a message
2. press control+, to go to next message
3. press control+, to go to next message
4. press Escape to close the message

After step 2, the next message is opened. After step 3, the next message is not opened. After step 4 the message window is not closed whereas it should. I need to press Alt+F4 to close this window.

**Comment by devinprater** [comment]
This issue is reproducible on Outlook 2016, the release version, not 365.

**Comment by Qchristensen** [comment]
In Outlook 365 (16.0.12325.20280) - without NVDA running (and with or without Magnifier running), I can press control+. at least 20 times to move between messages and it loads the next message.

I also tried with Windows 10 Narrator.  Narrator only reads the subject of each message as it loads, but it did that for each press of control+.

**Comment by Adriani90** [comment]
Here I expect NVDA to report at least the sender and the subject of the message. Ideally NVDA would then start to read the message body automatically, at least when you are in browse mode, similar to how it does when the coresponding setting is enabled for web pages.

**Comment by XLTechie** [comment]
Agreed with @Adriani90, that definitely seems like what it should be doing.

**Comment by Qchristensen** [comment]
This still happens for me using:

NVDA 2023.1.0.27913 
 
Windows 11 (64-bit) Version: 22H2, Build: 22621.1555 
 
Office 365 (64-bit) Version: 16.0.16227.20244 

I can start reading or read the title bar etc and it has updated, but nothing is spoken to even indicate the new message is loaded.  From the log when I try to move between messages:

IO - inputCore.InputManager.executeGesture (12:27:31.814) - winInputHook (8472):
Input: kb(desktop):control+.
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (12:27:32.343) - watchdog (15528):
Potential freeze, waiting up to 10 seconds.
DEBUG - UIAHandler.shouldUseUIAInMSWord (12:27:33.514) - MainThread (22720):
Using UIA due to suitable Office version: (16, 0, 16227)
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (12:27:33.869) - watchdog (15528):
Recovered from potential freeze after 2.026544300000001 seconds.

<nothing happens automatically after this, it just waits for my next input>
