### ISSUE TITLE
Error while navigating with object review

### ISSUE THREAD

**Issue by Nuno69** [nvaccess/nvda#10786]
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:03.519) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:03.824) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.192) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.335) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.434) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.525) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.635) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.743) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.825) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:04.915) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:05.006) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:05.116) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:05.244) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
ERROR - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (21:28:05.655) - MainThread (18236):
Traceback (most recent call last):
  File "locationHelper.pyc", line 259, in toLogical
  File "locationHelper.pyc", line 170, in toLogical
  File "windowUtils.pyc", line 93, in physicalToLogicalPoint
RuntimeError: Couldn't convert point(x=1662, y=975) from physical to logical coordinates for window 2034168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "displayModel.pyc", line 312, in _get__storyFieldsAndRects
  File "locationHelper.pyc", line 261, in toLogical
RuntimeError: Couldn't convert RectLTWH(left=259, top=54, width=1403, height=921) to logical coordinates
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (21:28:06.293) - MainThread (18236):
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by Adriani90** [comment]
Closing as this does not comply with the issue template. Please fill the issue template including exact steps to reproduce, actual and expected behavior as well as other information required.
