### ISSUE TITLE
Error with table grid sample in Chrome

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#10925]
While investigating another issue with Chrome I noticed NVDA errors when navigating a table with `role=grid`

### Steps to reproduce:
1. In Chrome open the following `role=grid` sample:
https://gist.github.com/feerrenrut/f6ed87b8758243c1d454d75b72179844
1. Navigate with tab to the table. 

### Actual behavior:
Error sound, log:

```
ERROR - eventHandler.executeEvent (12:27:00.058) - MainThread (20080):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x095D4A70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1534, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 485, in speakObject
  File "speech\__init__.pyc", line 318, in speakObjectProperties
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1147, in _get_columnNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

### Expected behavior:
No error sound. Not sure if speech should be different. 

#### NVDA version:
Installed Version: alpha-19834,2cdf280b

#### Windows version:
Windows 10 1903

#### Name and version of other software in use when reproducing the issue:
Chrome Version
- 80.0.3987.149 
- 81.0.4044.113

Canary Version
- 83.0.4100.0
- 84.0.4116.2

Not reproducible in Firefox 75.0

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
From launcher:
- 2019.3.1 also has error
- 2019.1 also has error.

**Comment by feerrenrut** [comment]
In NVDA 2019.1 there is also the following error when using Chrome:

```
ERROR - eventHandler.executeEvent (12:25:04.286):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x0575AA30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "browseMode.pyo", line 1477, in event_gainFocus
  File "speech.pyo", line 403, in speakObject
  File "speech.pyo", line 277, in speakObjectProperties
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 1148, in _get_columnNumber
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 1115, in _get_IA2PhysicalColumnNumber
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

```

**Comment by aleventhal** [comment]
The sample markup is illegal, because the `<th>` and `<td>` elements are naturally cells, but then have child spans that are also cells via role="gridcell". Chrome does try to support a wide variety of strange and illegal table markup, but we haven't seen this one before.

My suggestion would be to get rid of the span elements and make the td or th elements have the tabindex and role. Another option that may be easier, even if it seems weird to me, would be to put role="none" on the th and td elements.

**Comment by feerrenrut** [comment]
@aleventhal thanks for the update. This sample was distilled from https://github.com/nvaccess/nvda/issues/10880#issuecomment-606089517 where they also got the error. Looks like we can at least close this issue.
