### ISSUE TITLE
Excel Find and Replace dialog raises error when Japanese characters are typed

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#10936]
### Steps to reproduce:

- run NVDA and Microsoft Excel
- open blank book (Book1)
- type Ctrl+F to open Find and Replace dialog
- make sure focus is at the edit control
- enable Microsoft Japanese IME
- type ideogragaphic (Kanji) characters such as "日本語"

### Actual behavior:

- no error occured

### Expected behavior:

- error (with sound) occurs as follows

```
ERROR - eventHandler.executeEvent (19:39:55.151) - MainThread (27576):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x00BA58F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1155, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (19:39:55.719) - MainThread (27576):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x00BA58F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1155, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
ERROR - eventHandler.executeEvent (19:39:56.407) - MainThread (27576):
error executing event: caret on <NVDAObjects.Dynamic_DisplayModelEditableTextInputCompositionInputComposition object at 0x00BA58F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 189, in event_caret
  File "NVDAObjects\__init__.pyc", line 1155, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "displayModel.pyc", line 292, in __init__
  File "textInfos\offsets.pyc", line 453, in __init__
  File "displayModel.pyc", line 609, in _getCaretOffset
AttributeError: 'NoneType' object has no attribute 'toLTRB'
```

#### NVDA installed/portable/running from source:

- portable

#### NVDA version:

- 2020.1beta1

#### Windows version:

- Windows version 10.0.18363 (Japanese + English Language Pack)

#### Name and version of other software in use when reproducing the issue:

- Microsoft Office 365 (32bit) Excel Version 2003 (Build 12624.20382) (Japanese + English Language Pack)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

- NVDA 2019.3.1 works as expected

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No

**Comment by feerrenrut** [comment]
@nishimotz Does this causes any noticeable degradation in behavior or just the error sound?

**Comment by nishimotz** [comment]
While in the edit control, characters should be announced when the left/right arrow keys are pressed.
When this error occurs, the announcements of multi-byte characters can not be heard, so it is difficult to type or confirm such characters.

**Comment by nishimotz** [comment]
If error sound is suppressed in release build, can it be used normally?
I think the caret move announcements are missing when this error occurs.

**Comment by feerrenrut** [comment]
@nishimotz, yes it sounds like this will cause problems in the release. Depending on the complexity of a fix, it might be too late to do something about this, it may have to wait for the 2020.2 release.

**Comment by lukaszgo1** [comment]
@nishimotz Would you be able to bisect this perhaps?

**Comment by feerrenrut** [comment]
I would start by seeing how the behavior changes when checking if `objLocation` is None and raising a `RuntimeError` in `displayModel.EditableTextDisplayModelTextInfo._getCaretOffset`

It would be good to understand what the exact type is for `self.obj` and why it's call to `def _get_location fails`

**Comment by nishimotz** [comment]
I am checking again, but it doesn't seem to be a regression.
Now I can see the similar issue with 2019.2.1.
