### ISSUE TITLE
Edge: RuntimeError when address bar is empty

### ISSUE THREAD

**Issue by aaclause** [nvaccess/nvda#10980]
### Steps to reproduce:
1. Open Microsoft Edge.
2. Go to address bar (ALT+d or CTRL+l).
3. (if needed) remove the selection.

### Actual behavior:
The following error occurs and braille screen is not updated:

```
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 296, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1103, in event_gainFocus
  File "braille.pyc", line 1905, in handleGainFocus
  File "braille.pyc", line 1910, in _doNewObject
  File "braille.pyc", line 1575, in getFocusRegions
  File "braille.pyc", line 991, in update
  File "NVDAObjects\UIA\__init__.pyc", line 759, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 300, in __init__
RuntimeError: Could not clone range
```

Maybe related to #10734?

### Expected behavior:
No error, braille display refreshed.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-19938,e8cde2ca

#### Windows version:
Windows 10 Insider (64-bit) build 19603.1000

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge 80.0.361.111

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Adriani90** [comment]
@Andre9642 I cannot reproduce this with NVDA Version: alpha-20015,56a62097 on last stable Edge Cromium 81.

Can you confirm?

**Comment by Adriani90** [comment]
However, I have to metntion that I do not have a braille display connected. It might be related to braille only.

**Comment by Andre9642** [comment]
Yes, no problem if I don't have a braille display connected.

**Comment by aaclause** [comment]
I am no longer able to reproduce this issue (Microsoft Edge 91.0.864.54), closing.
