### ISSUE TITLE
In Google Sheets, navigator throws errors when examining the table structure

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#11113]
### Steps to reproduce:

1. In Firefox, open https://sheets.google.com, log in if necessary.
2. Create a new sheet, for example based off of the Invoice Template under the General tab.
3. Once the spreadsheet opens, go to the Help menu and search for braille support. Make sure it is checked.
4. Press Escape to return focus to the spreadsheet and arrow around a bit.
5. Now, use the Object Navigator Parent command to investigate the table structure.

### Actual behavior:

NVDA speaks the row number (1 of 26, for example), and some other information, but also plays an error sound. The entry in the NVDA log file looks like this:

```
ERROR - eventHandler.executeEvent (16:09:22.937) - MainThread (19740):
error executing event: becomeNavigatorObject on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionRowWithFakeNavigationEditorChunkMozillaIAccessible object at 0x0BB9CB50> with extra args of {'isFocus': False}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1127, in event_becomeNavigatorObject
  File "braille.pyc", line 2034, in handleReviewMove
  File "braille.pyc", line 1910, in _doNewObject
  File "braille.pyc", line 1572, in getFocusRegions
  File "braille.pyc", line 621, in update
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1172, in _get_cellCoordsText
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1162, in _get_columnNumber
NotImplementedError
```

### Expected behavior:

No error, and all information should be read.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA version alpha-20145,cdd37c72

#### Windows version:

Windows 10 19H2.

#### Name and version of other software in use when reproducing the issue:

Firefox 76 RC or 77 Beta, or 78 Nightly.

#### Other information about your system:

Braille display connected, Focus 40 Blue 5th generation.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2020.1RC, same result.

#### If addons are disabled, is your problem still occuring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes. No change.

@jcsteh Is this a bug in Firefox, are we not implementing something NVDA is expecting?

**Comment by feerrenrut** [comment]
From the stack, it looks like it's an issue in braille. If you are able to disable the braille display and the error goes away and table navigation etc all works correctly with speech, then it's likely a bug in NVDA's braille code.

**Comment by MarcoZehe** [comment]
Hi @feerrenrut , this is confirmed a braille issue.

**Comment by Adriani90** [comment]
cc:@bramd

**Comment by Adriani90** [comment]
@MarcoZehe are you still seeing this error in NVDA 2022.4?

**Comment by Adriani90** [comment]
@aaclause could you please test if you can reproduce this error with a braille display? I don't have one at hand. Otherwise I would say let's close this issue as abandoned since we didn't get any updates from Marco since many years unfortunately.
