### ISSUE TITLE
Make winKernel / winUser type safe wrappers

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11125]
# Is your feature request related to a problem? Please describe.
NVDA is using many windows API functions that are c function and therefore require certain types as input / output parameters. Most of them can be found in the winKernel and winUser modules.
However, the functions we're using are merely wrappers of these functions, without checking what types we're passing at them and getting from them.

By default, ctypes assumes a return type of ctypes.c_long for all library functions loaded with the WinDLL library loader. However, many of these functions return other types, such as DWORD (unsigned long) and HANDLE. Furthermore, when throwing parameters at these functions, ctypes by default only knows how many bytes the function expects as its input. This is all in depth explained in the [ctypes docs](https://docs.python.org/3/library/ctypes.html)

### Describe the solution you'd like
I propose two things:

1. Define a standard for new wrappers added to winKernel and winUser
2. Update the current wrappers according to this new standard.

As a standard, I'd propose to no longer wrap these functions with python `def` style functions, but using ctypes.WINFUNCTYPE. This allows us to:

* Provide expected types, names and default values for arguments
* Automatic Windows error handling/raising (GetLastError)
* Automatic input parameters for functions like user32.GetClientRect. You set RECT as an input parameters and ctypes automatically passes an empty structure to the function

A downside of this approach might be that we don't have type annotations.

**Comment by feerrenrut** [comment]
An example function:
https://github.com/nvaccess/nvda/blob/1cf36fbe2e0a7b40cccea707914fe575b92c54b6/source/winKernel.py#L77

> A downside of this approach might be that we don't have type annotations.

Doing something like the following could resolve that:
https://github.com/nvaccess/nvda/blob/45cb098b2f6238ae875b42ee2f2b32b4912f2366/nvdaHelper/eventHandler/EventHandlerDllWrapper.py#L27

Taking this approach also means that we can attach docs to these functions. Getting type info and docs at the call site is very helpful.

**Comment by leonardder** [comment]
> An example function:
> 
> https://github.com/nvaccess/nvda/blob/1cf36fbe2e0a7b40cccea707914fe575b92c54b6/source/winKernel.py#L77

How do you mean this reference? I wrote this function myself, but it still hasn't type checking at the ctypes level, so you're still allowed to throw things at that function that might break.

I will update the initial description with some additional examples and justifications.

**Comment by leonardder** [comment]
> Doing something like the following could resolve that:
> 
> https://github.com/nvaccess/nvda/blob/45cb098b2f6238ae875b42ee2f2b32b4912f2366/nvdaHelper/eventHandler/EventHandlerDllWrapper.py#L27

I'm not following how this example is supposed to work. getEventHandlerDll is supposed to return a EventHandlerDll instance, but it will return an instance of ctypes.CDLL. Probably better to discuss this in #10556, though.

I was more thinking about an approach like visionEnhancementProviders.screenCurtain.Magnification

**Comment by leonardder** [comment]
I actually found a serious bug that's caused by this inaccurateness.

the return type of WaitForSingleObject is DWORD. If its value is `WAIT_FAILED = 0xffffffff`, the function raises a Windows Error. However, this is never the case, as the return type is set to its default, ctypes.c_int, which is unsigned. Therefore the result of WaitForSingleObject will never be treated as WAIT_FAILED at all, as that's out of the range of c_int.

If you add `kernel32.WaitForSingleObject.restype = ctypes.wintypes.DWORD` to winKernel, you will notice that NVDA will not start at all. If you do it at runtime, you get bugs instantly.

I'm afraid there are more ugly bugs like this.

**Comment by feerrenrut** [comment]
> I'm not following how this example is supposed to work.

How you describe it is how it's supposed to work. The type information is provided for IDE's and automatic type checkers. The types of `EventHandlerDll` and the returned `ctypes.CDLL` match. We could probably create an annotation that added these types to the CDLL methods automatically.

**Comment by feerrenrut** [comment]
> an example function

> so you're still allowed to throw things at that function that might break.

I wanted to point to an example in the code base that does not have the types set. 

It would b

**Comment by leonardder** [comment]
> How you describe it is how it's supposed to work. The type information is provided for IDE's and automatic type checkers. The types of `EventHandlerDll` and the returned `ctypes.CDLL` match. We could probably create an annotation that added these types to the CDLL methods automatically.

I think that would be required for runtime inspection as well. Creating a class only for a type checker to be satisfied feels a bit tricky to me.

**Comment by feerrenrut** [comment]
It's just a way of specifying the type returned by the function. I'm not aware of another way to do it?

**Comment by leonardder** [comment]
How about the following approach I'd like to explore:

1. Define the functions as in [your example](https://github.com/nvaccess/nvda/blob/45cb098b2f6238ae875b42ee2f2b32b4912f2366/nvdaHelper/eventHandler/EventHandlerDllWrapper.py#L27)
2. Create a new ctypesHelper module
3. In that module, provide a decorator that does the following:

	* Discard the body of the decorated function, it will be empty
	* Inspect the function for type annotations
	* Construct the proper WINFUNCTYPE object using the annotated function, along with default values
	* We could subclass typing.Generic to create an annotation for out params

**Comment by feerrenrut** [comment]
Yep, that's what I had in mind, but not confident it is possible haha!

> We could subclass typing.Generic to create an annotation for out params

I'm not sure what you mean by this.

**Comment by leonardder** [comment]
I wrote a prototype:
https://github.com/leonardder/nvda/commit/3e8bfa03aaac563627afb796ddcf61c02565308a

It can be used as follows:

```
import ctypes, ctypesHelper, winKernel

@ctypesHelper.annotatedCFunction(winKernel.kernel32)
def CloseHandle(handle: ctypes.wintypes.HANDLE) -> ctypes.wintypes.BOOL:
	...

```

Runtime inspection of type hints is not possible.

```
>>> typing.get_type_hints(CloseHandle)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python37\lib\typing.py", line 1002, in get_type_hints
    'or function.'.format(obj))
TypeError: <WinFunctionType object at 0x0492B300> is not a module, class, method, or function.
```

> > We could subclass typing.Generic to create an annotation for out params
> 
> I'm not sure what you mean by this.

I thought you needed to use typing.Generic to construct your own type like typing.Optional, but turns out I was wrong. feel free to forget this.

**Comment by leonardder** [comment]
I expanded the prototype, so to see what it looks like, it's probably best to refer to the [ctypesHelper](https://github.com/leonardder/nvda/tree/ctypesHelper) branch I'm working on.
It also contains an example implementation in winKernel for createWaitableTimer.
Type hints should be available for type checkers as well as at runtime using typing.get_type_hints and inspect.signature. Thanks to the magic of functools.update_wrapper

**Comment by feerrenrut** [comment]
It looks like there is enough logic and conditions in there that it would be worth writing unit tests. As a bonus it will help to document how it works.

**Comment by feerrenrut** [comment]
Did you notice the note in the docs for `functools.wraps`?

> Without the use of this decorator factory, the name of the example function would have been 'wrapper', and the docstring of the original example() would have been lost.

Is this relevant to your prototype?

**Comment by leonardder** [comment]
> Did you notice the note in the docs for `functools.wraps`?
> 
> > Without the use of this decorator factory, the name of the example function would have been 'wrapper', and the docstring of the original example() would have been lost.
> 
> Is this relevant to your prototype?

Yes, probably, thanks for pointing me at this. I might have to do some additional magic under the hood to make docstrings work. The problem is that functools.update_wrapper actually expects a real FunctionType. Therefore, to make doc strings work, they need to be set on the class.

> 
> 
> It looks like there is enough logic and conditions in there that it would be worth writing unit tests. As a bonus it will help to document how it works.

If you believe this prototype is the right way to go, unit tests are certainly planned.

**Comment by feerrenrut** [comment]
> If you believe this prototype is the right way to go

This is hard to say without a few more examples of how it is used. I think tests will help with that. It would also be good to at least outline alternative approaches and compare the benefits of each.

**Comment by leonardder** [comment]
I think there are some alternative approaches:

1. Set argtypes and restype on a per _FuncPtr object basis, and leave the wrappers as they are. However, if we don't do this using a helper function like in this prototype, we don't have type annotations.
2. Instead of making the decorator return the WINFUNCTYPE object, return another wrapper function taking *args, **kwargs, and let that wrapper forward the arguments to the winfunctype. This way, we could easily preserve doc string and other attributes, like __name__, __qualname__ and the __repr__ method. Validation would still be performed by the winfunctype object. I think I"m going to explore this approach, as it might be a bit cleaner than patching the winfunctype.
3. Don't create a WINFUNCTYPE object, but wrap the _FuncPtr object directly. This requires patching the _FuncPtr objects, and therefore lets the winKernel module patch function pointers on winKernel.kernel32. I consider this a bit dirty, I really prefer the WINFUNCTYPE approach myself.

**Comment by leonardder** [comment]
@josephsl curious to know what you think about this.

I also found out that python 3.8 adds functions to the typing module to inspect types, typing.get_origin and typing.get_args. That would allow us to use Generics, like this

```
CType = TypeVar("CType")

class OutParam(Generic[CType]):
    ...

def GetClientRect(hwnd: ctypes.wintypes.HWND, rect: OutParam[ctypes.wintypes.LPRECT) -> ctypes.wintypes.BOOL:
    ...
```

All annotations for which typing.get_origin returns OutParam are output parameters. The type to use for the output parameter could be retrieved with typing.get_args

**Comment by josephsl** [comment]
Hi, was this tested under Python 3.8 with a test wrapper module? As for implications of that change, I don’t know as ctypes isn’t really my area. Thanks.

**Comment by leonardder** [comment]
> Hi, was this tested under Python 3.8 with a test wrapper module?

Not yet, this was based on python 3.8 docs.

**Comment by Adriani90** [comment]
What is now the current status on this, now that we are on Python 3.11?
cc: @gerald-hartig is there an official positoin of NV Access on this topic?

**Comment by Adriani90** [comment]
cc: @SaschaCowley for triaging, an updated  position from NV Access on this one is still open.

**Comment by gerald-hartig** [comment]
This might be a good candidate to include in the 64 bit migration project. @Adriani90 in your spelunking through the backlog, have you encountered other issues that this lack of type checking might have caused?

**Comment by seanbudd** [comment]
Based on reading the discussion it seems this stalled over discussing/debating implementation details. I think opening a PR would be fine, but the approach discussion needs to be resolved. I would suggest anyone opening a PR to:

1. Comment their planned approach here first
2. Open a draft PR with a small example change

**Comment by LeonarddeR** [comment]
In https://github.com/nvaccess/nvda/pull/18207, @SaschaCowley chose an approach for this that somewhat differs from what I propose here.

@seanbudd wrote:
>     2. Open a draft PR with a small example change

What I propose is something like the `Magnification` class in `visionEnhancementProviders.screenCurtain`. I think that example suffices.

A major advantage of the approach in #18207 is that the function pointers are directly annotated on the library objects. 
For example, `ctypes.windll.kernel32.CloseHandle.argtypes=(ctypes.wintypes.HANDLE,)` ensures that in every place `CloseHandle` is called, argument types are properly validated. An advantage of using the approach as in the `Magnification` class is that you can provide parameter names and direction (in or out parameter).

**Comment by LeonarddeR** [comment]
I just discovered that we can actually combine best of both worlds:
```python
import ctypes

_CloseHandle_funcType = ctypes.WINFUNCTYPE(ctypes.wintypes.BOOL, ctypes.wintypes.HANDLE)
_CloseHandle_params = ((0, "hObject"),)
_CloseHandle = _CloseHandle_funcType(("CloseHandle", ctypes.windll.kernel32), _CloseHandle_params)
ctypes.windll.Kernel32.CloseHandle=_CloseHandle
```

**Comment by gexgd0419** [comment]
Note that in the [ctypes documentation](https://docs.python.org/3/library/ctypes.html#ctypes-fundamental-data-types-2):

> Fundamental data types, when returned as foreign function call results, or, for example, by retrieving structure field members or array items, are transparently converted to native Python types. In other words, if a foreign function has a [restype](https://docs.python.org/3/library/ctypes.html#ctypes._CFuncPtr.restype) of [c_char_p](https://docs.python.org/3/library/ctypes.html#ctypes.c_char_p), you will always receive a Python bytes object, not a [c_char_p](https://docs.python.org/3/library/ctypes.html#ctypes.c_char_p) instance.

Here's a table:

| Original restype | Converted type |
| - | - |
| Any integer type, e.g. c_long, c_ubyte | int |
| Any floating point type, e.g. c_double | float |
| c_char, c_char_p | bytes |
| c_wchar, c_wchar_p | str |
| c_bool | bool |
| c_void_p | int |


This should be reflected on the type hints, as `c_int` and `int` are not quite the same.

This also applies to callback functions argument types. So if you define your callback function to take an `c_int`, you will actually get an `int`.

**Comment by LeonarddeR** [comment]
I'm currently working on a prototype that will look like this:

```
@ctypesUtils.wrapCFunc(windll.kernel32.CloseHandle)
def CloseHandle(hObject: ctypes.wintypes.HANDLE) -> ctypes.wintypes.BOOL:
    """A doc string"""
    ...
    
```

The `ctypesUtils.wrapCFunc` decorator will mutate this function so that it will eventually return a ctypes function type that is properly annotated with the proper argtypes/restype.

Something like this should also work:

```
@ctypesUtils.wrapCFunc(windll.kernel32.CloseHandle)
def CloseHandle(hObject: typing.Annotated[int, ctypes.wintypes.HANDLE]) -> typing.Annotated[int, ctypes.wintypes.BOOL]:
```

Annotations ensure that type checkers will expect int for the argument and return type, whereas the decorator will read the annotations and, as there is a ctypes type in the annotations, will use that type for argtypes/restype.

Going even further:

```
@ctypesUtils.wrapCFunc(windll.kernel32.CloseHandle, errCheck=ctypesUtils.zeroReturnIsErrorErrCheck)
def CloseHandle(hObject: typing.Annotated[int, ctypes.wintypes.HANDLE]) -> typing.Annotated[None, ctypes.wintypes.BOOL]:
```

Since the function here returns a BOOL, the return type is meant to communicate succes/failure. The `zeroReturnIsErrorErrCheck)` function will raise WinError when res is 0, otherwise returns None for this particular function.

**Comment by LeonarddeR** [comment]
@SaschaCowley do you think this can help with the `winBindings` package that will be introduced in #18207?

**Comment by SaschaCowley** [comment]
@LeonarddeR that sounds fantastic. One of the issues on my radar to investigate is type information for static type analysis when using ctypes functions, which it sounds like your proposal would solve. It looks like your proposal handles argtypes, restype and errcheck, but what about specifying directionality?

**Comment by gexgd0419** [comment]
The problem is that setting out parameters changes the argument list and the return type.

For example:

``` python
from ctypes import WINFUNCTYPE, POINTER, byref, windll
from ctypes.wintypes import BOOL, HWND, RECT

GetForegroundWindow = WINFUNCTYPE(HWND)(("GetForegroundWindow", windll.user32))
GetWindowRect_funcType = WINFUNCTYPE(BOOL, HWND, POINTER(RECT))
GetWindowRect_raw = GetWindowRect_funcType(("GetWindowRect", windll.user32))
GetWindowRect = GetWindowRect_funcType(("GetWindowRect", windll.user32), ((1, "hWnd"), (2, "lpRect")))

hWnd: int = GetForegroundWindow()

rc1 = RECT()
if GetWindowRect_raw(hWnd, byref(rc1)):
    print(rc1.left, rc1.top, rc1.right, rc1.bottom)

rc2: RECT = GetWindowRect(hWnd)
print(rc2.left, rc2.top, rc2.right, rc2.bottom)
```

We can invoke `GetWindowRect` in two ways, and when `lpRect` is specified as an out parameter, `GetWindowRect` changes from taking two arguments to taking one, and the second argument becomes the return value, unwrapping one layer of `POINTER`.

So maybe we can separate the static type checking part and the runtime part, by using `if TYPE_CHECKING:`. Or use a separate `.pyi` file.

Or maybe, write all the out parameters in the decorator line, something like:

```python
@ctypesUtils.wrapCFunc(
        windll.user32.GetWindowRect,
        errCheck=ctypesUtils.zeroReturnIsErrorErrCheck,
        outParams=((1, "lpRect")),  # 1 means inserting at index 1
        restype=ctypes.wintypes.BOOL,  # the actual restype
        )
def GetWindowRect(hWnd: typing.Annotated[int, ctypes.wintypes.HANDLE]) -> ctypes.wintypes.RECT:
```

Note that when there are two or more out parameters, the return type will become a tuple containing all the out parameters.

**Comment by LeonarddeR** [comment]
Good points there.
I will file a draft pr with te pototype in an hour or two. Please note that it still needs documentation and unit testing, but I want you to get the idea. It deals with out params using return type annotations, it only requires the restype on the decorator.

**Comment by LeonarddeR** [comment]
I just created #18534. This will probably look like black magic to you all. I will write unit tests and proper documentation later today or tomorrow.

**Comment by LeonarddeR** [comment]
I think this has been sufficiently covered by the winbindings migration.
