### ISSUE TITLE
NVDA 2019.3-2020.1 & iTunes: UIAutomationTextRangeArray is empty / NULL COM pointer access on some elements

### ISSUE THREAD

**Issue by AAClause** [nvaccess/nvda#11141]
### Steps to reproduce:
There are several ways to reproduce this issue, here's one:

1. Open iTunes.
2. In the library sidebar, select a playlist.
3. Press tab key two times.

### Actual behavior:
The following error occurs and no speech/braille feedback for the focused element:

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "speech\__init__.pyc", line 523, in getObjectSpeech
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 309, in __init__
NotImplementedError: UIAutomationTextRangeArray is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eventHandler.pyc", line 213, in executeEvent
  File "eventHandler.pyc", line 94, in __init__
  File "eventHandler.pyc", line 102, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 539, in getObjectSpeech
  File "speech\__init__.pyc", line 463, in _getPlaceholderSpeechIfTextEmpty
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1194, in _get__isTextEmpty
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 320, in __init__
  File "NVDAObjects\UIA\__init__.pyc", line 765, in collapse
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
ValueError: NULL COM pointer access
```

</details>

Same thing for some other items.

### Expected behavior:
No error and description of the focused item (here: `<playlist name> Edit`).

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20175,9967903a

#### Windows version:
10 Insider (64-bit) build 19624.1000

#### Name and version of other software in use when reproducing the issue:
iTunes 12.10.6.2

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same behavior with 2019.3. Works with 2019.2.1.

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Adriani90** [comment]
@aaclause are you still able to reproduce this with NVDA 2023.2 on last version of iTunes?

**Comment by Adriani90** [comment]
Given this article and that alternatives from Apple for iTunes are already published in the Windows store, I am closing as abandoned.
https://applescoop.org/story/from-icon-to-obsolete-what-happened-to-apple-itunes
If you want to hear your Apple podcasts on your Windows PC, there is also a new alternative from Apple:
https://www.groovypost.com/howto/listen-apple-podcasts-pc-web-app/
For audiobooks there is no solution yet, but it is a matter of short time until it will come. If you have audiobooks on iTunes and want to export them, there are plenty of converters that can convert them to mp3.
