### ISSUE TITLE
Libreoffice writer, focus tracking bug, not possible to edit foodnote

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11192]
### Steps to reproduce:
1. Open NVDA dn open Libreoffice Writer
2. Press alt and go to format submenu > foodnotes and endnotes
3. Press enter on foodnote
4. Type something or use arrow keys to navigate

### Actual behavior:
NVDA generates errors and does not report anything.
Following is written to the log:

```
IO - inputCore.InputManager.executeGesture (17:06:51.739) - winInputHook (812):
Input: kb(laptop):l
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:06:51.762) - MainThread (13060):
accRole failed: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (17:06:51.763) - MainThread (13060):
error executing event: caret on <NVDAObjects.Dynamic_SymphonyParagraphSymphonyTextEditableTextWithAutoSelectDetectionIAccessible object at 0x015FEEF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 213, in executeEvent
  File "eventHandler.pyc", line 94, in __init__
  File "eventHandler.pyc", line 102, in next
  File "compoundDocuments.pyc", line 469, in event_caret
  File "documentBase.pyc", line 24, in makeTextInfo
  File "compoundDocuments.pyc", line 216, in __init__
  File "documentBase.pyc", line 24, in makeTextInfo
  File "textInfos\offsets.pyc", line 453, in __init__
  File "textInfos\offsets.pyc", line 250, in _getCaretOffset
NotImplementedError
```

### Expected behavior:
NVDA should not generate errors and the edit field should be navigable without errors.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.1

#### Windows version:
Windows 10 1909 Update

#### Name and version of other software in use when reproducing the issue:
Libreoffice writer 6.4.4.2.

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, no effect

**Comment by DrSooom** [comment]
@Adriani90: You meant the menu "Insert" and not "Format", right? 😉

#### Workaround with NVDA 2019.2.1: Press ALT+TAB twice.

**Comment by Adriani90** [comment]
Oh yes, thanks, edited accordingly.

 

 

Von: Daniel Mayr <notifications@github.com> 
Gesendet: Sonntag, 24. Mai 2020 19:43
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Libreoffice writer, focus tracking bug, not possible to edit foodnote (#11192)

 

@Adriani90 <https://github.com/Adriani90> : You meant the menu "Insert" and not "Format", right? 😉


Workaround with NVDA 2019.2.1: Press ALT+TAB twice.

**Comment by Adriani90** [comment]
With NVDA 2024.4.1 and LO 25.2 it works as expected. Closing as works for me.
