### ISSUE TITLE
Alpha updates have stopped working

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#11225]
-->

### Steps to reproduce
Run an alpha version of NVDA recently downloaded. Check for updates. When update is detected follow the prompts to download
This download failes with a ding, and  an ok button, this of course cancells the update:

### Actual behavior:
The download does not even start to do anything from what I can tell.
### Expected behavior:
The download should proceed as it always does, resulting in the opertunity to install it.
### System configuration
Windows 7 up to date, the version of nvda is portable on the hard drive of the machine.
#### NVDA version:
Alpha prior to the latest one.
#### Windows version:
7
#### Name and version of other software in use when reproducing the issue:
None only desktop
#### Other information about your system:
Nothing of note
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I cannot as this is the only updatable snapshot at the moment
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No I thought this was always run in any case.

**Comment by Adriani90** [comment]
There might be something wrong with your internet connection, I have just updated NVDA with the alpha you mentioned and it's working. So this is definitely an isue on your machine.
Please re establish the internet connection and try to download the update one more time.

**Comment by Brian1Gaff** [comment]
Well, unless the certificate  being out of date  does not matter, my end 
says it does matter.

IO - speech.speak (21:43:34.086) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Help', 'subMenu', 'h']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:34.086) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Help  ', 'sub Menu  ', 'h 
', IndexCommand(6)]
IO - inputCore.InputManager.executeGesture (21:43:34.643) - winInputHook 
(2796):
Input: kb(desktop):enter
IO - speech.speak (21:43:34.664) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'User Guide', 'u', '1 of 10']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:34.664) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'User Guide  ', 'u  ', '1 of 
10  ', IndexCommand(7)]
IO - inputCore.InputManager.executeGesture (21:43:35.523) - winInputHook 
(2796):
Input: kb(desktop):upArrow
IO - speech.speak (21:43:35.532) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'About...', 'a', '10 of 10']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:35.532) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'About...  ', 'a  ', '10 of 
10  ', IndexCommand(8)]
IO - inputCore.InputManager.executeGesture (21:43:37.723) - winInputHook 
(2796):
Input: kb(desktop):upArrow
IO - speech.speak (21:43:37.735) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Check for update...', 'c', '9 of 
10']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:37.735) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Check fore update...  ', 'c 
', '9 of 10  ', IndexCommand(9)]
IO - inputCore.InputManager.executeGesture (21:43:38.635) - winInputHook 
(2796):
Input: kb(desktop):enter
IO - speech.speak (21:43:38.724) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Inbox - Outlook Express - Brians 
lists account BGlists']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:38.725) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Inbox  dash- Outlook 
Express  dash- Brians lists account B Glists  ', IndexCommand(10)]
IO - speech.speak (21:43:38.789) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Checking for Update', 'Checking for 
update']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:38.790) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Checking fore Update  ', 
'Checking fore update  ', IndexCommand(11)]
IO - tones.beep (21:43:39.646) - MainThread (5892):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speak (21:43:39.651) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Please wait']
IO - tones.beep (21:43:39.661) - MainThread (5892):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
DEBUG - windowUtils.getWindowScalingFactor (21:43:39.666) - MainThread 
(5892):
GetDpiForWindow failed, using GetDeviceCaps instead
IO - speech.speak (21:43:39.699) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'NVDA Update', 'NVDA version 
alpha-20256,f2cbfec8 is available.']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:39.700) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'NVDA Update  ', 'NVDA 
version alpha dash-20256,f 2cbfec 8 is available.  ', IndexCommand(13)]
IO - speech.speak (21:43:39.701) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Download update', 'Alt+d']
IO - inputCore.InputManager.executeGesture (21:43:44.004) - winInputHook 
(2796):
Input: kb(desktop):tab
IO - speech.speak (21:43:44.024) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Close', 'Alt+c']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:44.024) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Close  ', 'Alt plus c  ', 
IndexCommand(15)]
IO - inputCore.InputManager.executeGesture (21:43:45.196) - winInputHook 
(2796):
Input: kb(desktop):tab
IO - speech.speak (21:43:45.206) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Download update', 'Alt+d']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:45.206) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Download update  ', 'Alt 
plus d  ', IndexCommand(16)]
IO - inputCore.InputManager.executeGesture (21:43:46.388) - winInputHook 
(2796):
Input: kb(desktop):space
IO - speech.speak (21:43:46.406) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'space', EndUtteranceCommand()]
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:46.406) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'space  ', IndexCommand(17)]
IO - speech.speak (21:43:46.407) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'pressed']
IO - speech.speak (21:43:46.566) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Please Donate', 'We need your help 
in order to continue to improve NVDA.\nThis project relies primarily on 
donations and grants. By donating, you are helping to fund full time 
development.\nIf even $10 is donated for every download, we will be able to 
cover all of the ongoing costs of the project.\nAll donations are received 
by NV Access, the non-profit organisation which develops NVDA.\nThank you 
for your support.']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:46.571) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Please Donate  ', 'We need 
your help in order to continue to improve NVDA. This project relies 
primarily on donations and grants. By donating, you are helping to fund full 
time development. If even $10 is donated fore every download, we will be 
able to cover all of the ongoing costs of the project. All donations are 
received by NV Access, the non dash-profit organisation which develops NVDA. 
Thank you fore your support.  ', IndexCommand(20)]
IO - speech.speak (21:43:46.572) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Donate', 'Alt+d']
IO - inputCore.InputManager.executeGesture (21:43:47.924) - winInputHook 
(2796):
Input: kb(desktop):tab
IO - speech.speak (21:43:47.941) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Not now', 'Alt+n']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:47.942) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Not now  ', 'Alt plus n  ', 
IndexCommand(22)]
IO - inputCore.InputManager.executeGesture (21:43:48.692) - winInputHook 
(2796):
Input: kb(desktop):space
IO - speech.speak (21:43:48.700) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'space', EndUtteranceCommand()]
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:48.701) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'space  ', IndexCommand(23)]
IO - speech.speak (21:43:48.701) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'pressed']
IO - speech.speak (21:43:48.891) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Downloading Update', 'Connecting']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:48.891) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Downloading Update  ', 
'Connecting  ', IndexCommand(26)]
IO - speech.speak (21:43:48.895) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Cancel']
ERROR - updateCheck.UpdateDownloader._bg (21:43:49.297) - 
updateCheck.UpdateDownloader.start (4624):
Error downloading 
https://ci.appveyor.com/api/buildjobs/tuo479ro0yw2xyvi/artifacts/output/nvda_snapshot_alpha-20256,f2cbfec8.exe
Traceback (most recent call last):
  File "urllib\request.pyc", line 1319, in do_open
  File "http\client.pyc", line 1252, in request
  File "http\client.pyc", line 1298, in _send_request
  File "http\client.pyc", line 1247, in endheaders
  File "http\client.pyc", line 1026, in _send_output
  File "http\client.pyc", line 966, in send
  File "http\client.pyc", line 1422, in connect
  File "ssl.pyc", line 423, in wrap_socket
  File "ssl.pyc", line 870, in _create
  File "ssl.pyc", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate 
verify failed: certificate has expired (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "updateCheck.pyc", line 610, in _bg
  File "updateCheck.pyc", line 633, in _download
  File "urllib\request.pyc", line 222, in urlopen
  File "urllib\request.pyc", line 525, in open
  File "urllib\request.pyc", line 543, in _open
  File "urllib\request.pyc", line 503, in _call_chain
  File "urllib\request.pyc", line 1362, in https_open
  File "urllib\request.pyc", line 1321, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] 
certificate verify failed: certificate has expired (_ssl.c:1076)>
IO - speech.speak (21:43:49.429) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Error', 'Error downloading update.']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:49.430) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Error  ', 'Error 
downloading update.  ', IndexCommand(28)]
IO - speech.speak (21:43:49.434) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'OK']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:50.504) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'OK  ', IndexCommand(29)]
IO - inputCore.InputManager.executeGesture (21:43:52.835) - winInputHook 
(2796):
Input: kb(desktop):space
IO - speech.speak (21:43:52.848) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'space', EndUtteranceCommand()]
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:52.848) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'space  ', IndexCommand(30)]
IO - speech.speak (21:43:52.849) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'pressed']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(21:43:52.958) - MainThread (5892):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, 
None, 0, None))
IO - speech.speak (21:43:53.000) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Downloading Update', 'Connecting']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:53.001) - 
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Downloading Update  ', 
'Connecting  ', IndexCommand(33)]
IO - speech.speak (21:43:53.002) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Cancel']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole 
(21:43:53.097) - MainThread (5892):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, 
None, 0, None))
IO - speech.speak (21:43:53.108) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Inbox - Outlook Express - Brians 
lists account BGlists']


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Brian1Gaff** [comment]
Well, unless the certificate  being out of date  does not matter, my end
says it does matter.

IO - speech.speak (21:43:34.086) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Help', 'subMenu', 'h']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:34.086) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Help  ', 'sub Menu  ', 'h
', IndexCommand(6)]
IO - inputCore.InputManager.executeGesture (21:43:34.643) - winInputHook
(2796):
Input: kb(desktop):enter
IO - speech.speak (21:43:34.664) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'User Guide', 'u', '1 of 10']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:34.664) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'User Guide  ', 'u  ', '1 of
10  ', IndexCommand(7)]
IO - inputCore.InputManager.executeGesture (21:43:35.523) - winInputHook
(2796):
Input: kb(desktop):upArrow
IO - speech.speak (21:43:35.532) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'About...', 'a', '10 of 10']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:35.532) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'About...  ', 'a  ', '10 of
10  ', IndexCommand(8)]
IO - inputCore.InputManager.executeGesture (21:43:37.723) - winInputHook
(2796):
Input: kb(desktop):upArrow
IO - speech.speak (21:43:37.735) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Check for update...', 'c', '9 of
10']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:37.735) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Check fore update...  ', 'c
', '9 of 10  ', IndexCommand(9)]
IO - inputCore.InputManager.executeGesture (21:43:38.635) - winInputHook
(2796):
Input: kb(desktop):enter
IO - speech.speak (21:43:38.724) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Inbox - Outlook Express - Brians
lists account BGlists']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:38.725) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Inbox  dash- Outlook
Express  dash- Brians lists account B Glists  ', IndexCommand(10)]
IO - speech.speak (21:43:38.789) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Checking for Update', 'Checking for
update']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:38.790) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Checking fore Update  ',
'Checking fore update  ', IndexCommand(11)]
IO - tones.beep (21:43:39.646) - MainThread (5892):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speak (21:43:39.651) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Please wait']
IO - tones.beep (21:43:39.661) - MainThread (5892):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
DEBUG - windowUtils.getWindowScalingFactor (21:43:39.666) - MainThread
(5892):
GetDpiForWindow failed, using GetDeviceCaps instead
IO - speech.speak (21:43:39.699) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'NVDA Update', 'NVDA version
alpha-20256,f2cbfec8 is available.']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:39.700) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'NVDA Update  ', 'NVDA
version alpha dash-20256,f 2cbfec 8 is available.  ', IndexCommand(13)]
IO - speech.speak (21:43:39.701) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Download update', 'Alt+d']
IO - inputCore.InputManager.executeGesture (21:43:44.004) - winInputHook
(2796):
Input: kb(desktop):tab
IO - speech.speak (21:43:44.024) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Close', 'Alt+c']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:44.024) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Close  ', 'Alt plus c  ',
IndexCommand(15)]
IO - inputCore.InputManager.executeGesture (21:43:45.196) - winInputHook
(2796):
Input: kb(desktop):tab
IO - speech.speak (21:43:45.206) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Download update', 'Alt+d']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:45.206) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Download update  ', 'Alt
plus d  ', IndexCommand(16)]
IO - inputCore.InputManager.executeGesture (21:43:46.388) - winInputHook
(2796):
Input: kb(desktop):space
IO - speech.speak (21:43:46.406) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'space', EndUtteranceCommand()]
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:46.406) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'space  ', IndexCommand(17)]
IO - speech.speak (21:43:46.407) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'pressed']
IO - speech.speak (21:43:46.566) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Please Donate', 'We need your help
in order to continue to improve NVDA.\nThis project relies primarily on
donations and grants. By donating, you are helping to fund full time
development.\nIf even $10 is donated for every download, we will be able to
cover all of the ongoing costs of the project.\nAll donations are received
by NV Access, the non-profit organisation which develops NVDA.\nThank you
for your support.']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:46.571) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Please Donate  ', 'We need
your help in order to continue to improve NVDA. This project relies
primarily on donations and grants. By donating, you are helping to fund full
time development. If even $10 is donated fore every download, we will be
able to cover all of the ongoing costs of the project. All donations are
received by NV Access, the non dash-profit organisation which develops NVDA.
Thank you fore your support.  ', IndexCommand(20)]
IO - speech.speak (21:43:46.572) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Donate', 'Alt+d']
IO - inputCore.InputManager.executeGesture (21:43:47.924) - winInputHook
(2796):
Input: kb(desktop):tab
IO - speech.speak (21:43:47.941) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Not now', 'Alt+n']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:47.942) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Not now  ', 'Alt plus n  ',
IndexCommand(22)]
IO - inputCore.InputManager.executeGesture (21:43:48.692) - winInputHook
(2796):
Input: kb(desktop):space
IO - speech.speak (21:43:48.700) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'space', EndUtteranceCommand()]
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:48.701) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'space  ', IndexCommand(23)]
IO - speech.speak (21:43:48.701) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'pressed']
IO - speech.speak (21:43:48.891) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Downloading Update', 'Connecting']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:48.891) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Downloading Update  ',
'Connecting  ', IndexCommand(26)]
IO - speech.speak (21:43:48.895) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Cancel']
ERROR - updateCheck.UpdateDownloader._bg (21:43:49.297) -
updateCheck.UpdateDownloader.start (4624):
Error downloading
https://ci.appveyor.com/api/buildjobs/tuo479ro0yw2xyvi/artifacts/output/nvda_snapshot_alpha-20256,f2cbfec8.exe
Traceback (most recent call last):
  File "urllib\request.pyc", line 1319, in do_open
  File "http\client.pyc", line 1252, in request
  File "http\client.pyc", line 1298, in _send_request
  File "http\client.pyc", line 1247, in endheaders
  File "http\client.pyc", line 1026, in _send_output
  File "http\client.pyc", line 966, in send
  File "http\client.pyc", line 1422, in connect
  File "ssl.pyc", line 423, in wrap_socket
  File "ssl.pyc", line 870, in _create
  File "ssl.pyc", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed: certificate has expired (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "updateCheck.pyc", line 610, in _bg
  File "updateCheck.pyc", line 633, in _download
  File "urllib\request.pyc", line 222, in urlopen
  File "urllib\request.pyc", line 525, in open
  File "urllib\request.pyc", line 543, in _open
  File "urllib\request.pyc", line 503, in _call_chain
  File "urllib\request.pyc", line 1362, in https_open
  File "urllib\request.pyc", line 1321, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: certificate has expired (_ssl.c:1076)>
IO - speech.speak (21:43:49.429) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Error', 'Error downloading update.']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:49.430) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Error  ', 'Error
downloading update.  ', IndexCommand(28)]
IO - speech.speak (21:43:49.434) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'OK']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:50.504) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'OK  ', IndexCommand(29)]
IO - inputCore.InputManager.executeGesture (21:43:52.835) - winInputHook
(2796):
Input: kb(desktop):space
IO - speech.speak (21:43:52.848) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'space', EndUtteranceCommand()]
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:52.848) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'space  ', IndexCommand(30)]
IO - speech.speak (21:43:52.849) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'pressed']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(21:43:52.958) - MainThread (5892):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - speech.speak (21:43:53.000) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Downloading Update', 'Connecting']
IO - speech.manager.SpeechManager._pushNextSpeech (21:43:53.001) -
MainThread (5892):
Sending to synth: [LangChangeCommand ('en_GB'), 'Downloading Update  ',
'Connecting  ', IndexCommand(33)]
IO - speech.speak (21:43:53.002) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Cancel']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(21:43:53.097) - MainThread (5892):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - speech.speak (21:43:53.108) - MainThread (5892):
Speaking [LangChangeCommand ('en_GB'), 'Inbox - Outlook Express - Brians
lists account BGlists']


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by XLTechie** [comment]
The certificate is not expired. Neither of them are.

echo | openssl s_client -servername ci.appveyor.com -connect ci.appveyor.com:443 
2>/dev/null | openssl x509 -noout -dates

notBefore=Dec 20 00:00:00 2019 GMT
notAfter=Dec 19 23:59:59 2021 GMT

And, because that address is just a redirection, I checked the second 
certificate as well:

echo | openssl s_client -servername appveyorcidatav2.blob.core.windows.net 
-connect appveyorcidatav2.blob.core.windows.net:443 2>/dev/null | openssl x509 
-noout -dates

notBefore=May 26 22:33:12 2020 GMT
notAfter=May 26 22:33:12 2022 GMT

Maybe check your computer's time and date setting?

**Comment by Brian1Gaff** [comment]
That is weird. I just tried it downloading in a browser and that seems to 
have worked. That must mean, I presume that something in that installation 
of the portable version is corrupted does it? Would you think removing 
everything but  the .ini and the add ons might work. It certainly does not 
with just an update from a downloaded copy, as I just tried it. Nvda works 
fine, its just that one problem. Where is that data kept for nvda? It cannot 
be a global problem if I can download the files in browsers though A bit 
puzzled now. If it can happen once it can happen to others.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment]
OK, its weird then. Here is what I have tried.
 Firstly, I have the final beta, which prompts to download the release 
version, and this is a portable version too, this works.
 I have installed an alpha from 2nd of June manually to a fresh portable 
folllder, so its raw, no set up changes. It prompts for you to get the 
latest alpha, but that download from inside the program fails also.
 There has to be something different about the alpha downloads that does not 
work here on my windows 7 machine. After all if manual downloads of the same 
files and installation work via a browser, and another portable of the 
previous release candidate downloads the release version with no issues, 
there has to be something wrong with the alpha snapshot downloader, since 
the certificates should be the same in betas and release as they are in 
Alpha, and the look up is the same.

So unless there is a basic difference between how the downloader validates 
certificates in alphas against betas and release candidates/release 
versions, one would expect those to fail if it was my machine causing it, 
surely?
 That was my premise anyway, to create the ticket.
 Is anyone else using windows 7, and can see what occurs?
 Its mighty strange, but I can work around it, but if it hits the release 
version there will be a lot of issues.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by XLTechie** [comment]
Well, the certificates are not the same in betas as in alphas, as I believe 
betas are downloaded directly from NV Access servers.

I don't have any Windows 7 systems available to test. I think @lukaszgo1 might, 
if he is willing and I am remembering correctly.

**Comment by lukaszgo1** [comment]
Yes, I have a Win 7 system but this is not specific to Win 7. It seems to be a duplicate of #5871. @Brian1Gaff Could you please try to download  one of the snapshots with Internet Explorer and then once again try to update. If it is indeed a duplicate of #5871 this time the download should succeed.

**Comment by Brian1Gaff** [comment]
Yes I already said all browsers download the file and will then update the 
snapshot, but after that, say updating to the one before last, then the 
internal download will not work either, and indeed a complete new portable 
install on the same machine will not work either, yet, as I said downloads 
do work from rc to  the latest stable with no difficulty on the same 
machine. This is true on both portable and installed copies, but I am not 
willing to overwrite my installed stable to see if updates to alpha can work 
on an installed copy.
 It is as somebody once said, a mystery wrapped up in an enigma!
 I'll have to go look at that issue you mentioned, I could not find a ticket 
for fails to update when I looked.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment]
Hi yes exactly the issue. Does this mean that the fix which was put in all 
that time ago has now been removed somehow, ie a regression? If so could 
somebody please fix it in Alpha as I have changed nothing from when it did 
work here. Either that or is there a way to force windows to update its 
certificates, if that is what is required. I do feel though that to avoid a 
massive hiccup when this goes into beta and rc, this issue should be 
sidestepped.
 I s there any way to merge these two tickets together, as it is as has been 
said the same issue but of course operating several years ago.
 Thanks. Perhaps somebody could flag it to the most appropriate dev for this 
issue, as I'd not know ho to put in the list. Thanks.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment]
In the end, I  installed a very old alpha, which worked and downloaded me 
the new version, so lets see what occurs if the next one comes out.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by leonardder** [comment]
The error in #5871 seem to be different, yet I think the underlying cause might be the same.

**Comment by Brian1Gaff** [comment]
Well anyway, I have managed to get it to work. The truth will come when the 
next update does of course.
 When did downloading get so complicated!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by XLTechie** [comment]
My guess? When you decided to stay on Windows 7 for some reason.

**Comment by Brian1Gaff** [comment]
No its not that, as many still use 7 and they all worked.  As I say it was a 
change in nvda alpha as when I went back quite a way, the update worked from 
there to the newest version, so I'll wait for another new version, then if 
it works, problem solved, if not as somebody famous said, I'll be back!

Interestingly the latest Edge works well on windows 7. My reasons? Two 
really, should you be remotely interested. We use a piece of software which 
is abandonware to record a talking newspaper for the blind and several other 
similar bits for databases of users that are a pain to keep working on 
windows 10 when thy do a major update.
At the moment anti virus software still works and of course the email 
software I'm using here also works, so what is not to like. Yes I have tried 
10, and although it has good bits, its not really enough to make me want it 
badly enough to go out and try to find complex solutions to software issues, 
when my volunteers are not computer savvy and need something they are 
familiar with.
 Now I'll shut up.
 well on that subject  anyway. If you want to discuss that bit here is not 
the place for it, thanks.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
