### ISSUE TITLE
Excel - Listing the comments in the current sheet fails

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11366]
### Steps to reproduce:

* Open a new Excel document
* In cell A1, press shift+F2, enter a dummy comment and validate
* In cell A3, press shift+F2, enter a dummy comment and validate
* Press NVDA+F7 to open the element list dialog.
* shift+tab to turn back to radio buttons indicating the element type
* Press right or left arrow to land on the comment radio button
* press tab to go to the comments list

### Actual behavior:

The error beep is heard and nothing is found in the comment's list. The following error is found in the log:
```IO - inputCore.executeGesture (11:21:26.845) - winInputHook (17628):
Input: kb(desktop):rightArrow
ERROR - RPC process 6636 (EXCEL.EXE) (11:21:26.916) - Dummy-7635 (13692):
Thread 356, build\x86\remote\excel.cpp, nvdaInProcUtils_excel_getCellInfos::<lambda_252607b36749a934dcf7252ca0219d42>::operator (), 478:
application.range failed. Code -2146827284, rangeAddress [Classeur1]Feuil1!$A$2,$A$4

IO - speech.speak (11:21:26.936) - MainThread (11308):
Speaking ['Commentaires', 'bouton radio', 'coché', 'Alt+o']
```

Note: this error does not occur if the comments are on contiguous cells.

### Expected behavior:

No error and the both comments are listed.

#### NVDA installed/portable/running from source:
Installed and portable

#### NVDA version:
NVDA 2020.2beta2

#### Windows version:
Windows 10 1809
#### Name and version of other software in use when reproducing the issue:
Excel 2016

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes:
2019.1.1: the issue is still present.
2019.1: All is working well.

#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

### Additional notes:

I have not not been able to find which commit has caused this regression since my environment does not seem to allow me to runn NVDA from source from this time.
Anyway, it semms that the following commit is a good candidate for this regression:
commit e194b8986efc02a9d52f405307813fead21cd6f6
Author: Michael Curran <michaelDCurran@users.noreply.github.com>
Address crash in Excel 2007 (#9456)

If this first commit is not responsible for the regression, here is another commit that may interfer:
commit 0df2a494237d0364c1fa1fd51c95fdd3c93b4170
Author: Takuya Nishimoto <nishimotz@gmail.com>
Excel cell range text should be translated. #9470 (#9471)

@michaelDCurran may you have a look since you are the author of e194b8986efc02a9d52f405307813fead21cd6f6?
Thanks.

**Comment by CyrilleB79** [comment]
@michaelDCurran, as the author of e194b89, may you have a look? What do you think?
Anyway, the regression is between 2019.1 and 2019.1.1.


Also @feerrenrut may you at least label this issue adequately so that it is visible?

Thanks.

**Comment by Adriani90** [comment]
@CyrilleB79 I cannot reproduce this anymore in NVDA 2024.2 and Office 365, can you test in Office 2016? Is this still an issue?

**Comment by CyrilleB79** [comment]
Yes, it is still an issue (Microsoft® Excel® 2016 MSO (Version 2405 Build 16.0.17628.20006) 32 bits).
I am quite surprised that you do not get the same result with Excel 365. Could you double check?

Strangely, just after restart, I have had no error when going on the "Note" tab; but selecting another tab and turning on the "Notes" tab makes the error appear again.

**Comment by Adriani90** [comment]
Ok it seems now I can reproduce it in Excel 365 as well with NVDFA 2024.4.1. Here is a related error:

```
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:40:49.318) - MainThread (3364):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONADD, window 722656 (EXCEL7), objectID 138, childID 0, process 13340 (excel), thread 3972
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:40:49.318) - MainThread (3364):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONREMOVE, window 722656 (EXCEL7), objectID 139, childID 0, process 13340 (excel), thread 3972
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:40:49.318) - MainThread (3364):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONADD, window 722656 (EXCEL7), objectID 140, childID 0, process 13340 (excel), thread 3972
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:40:49.318) - MainThread (3364):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONADD, window 722656 (EXCEL7), objectID 141, childID 0, process 13340 (excel), thread 3972
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:40:49.318) - MainThread (3364):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 722656 (EXCEL7), objectID 142, childID 0, process 13340 (excel), thread 3972
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (00:40:49.318) - Dummy-2 (24440):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1337, in getNearestWindowHandle
_ctypes.COMError: (-2147417846, ''The message filter indicated that the application is busy.', (None, None, None, 0, None))
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:40:49.318) - MainThread (3364):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 722656 (EXCEL7), objectID 143, childID 0, process 13340 (excel), thread 3972
IO - speech.speech.speak (00:40:49.338) - MainThread (3364):
Speaking ['Anmerkungen', 'Auswahlschalter', 'aktiviert']
ERROR - RPC process 13340 (EXCEL.EXE) (00:40:49.334) - Dummy-9 (28536):
Thread 3972, build\x86_64\remote\excel.cpp, nvdaInProcUtils_excel_getCellInfos::<lambda_1>::operator (), 480:
application.range failed. Code -2146827284, rangeAddress [Mappe1]Tabelle1!$A$1,$A$3,$A$6

IO - inputCore.InputManager.executeGesture (00:40:50.478) - winInputHook (19152):
Input: kb(laptop):tab
IO - speech.speech.speak (00:40:50.498) - MainThread (3364):
Speaking ['Baumansicht']
IO - inputCore.InputManager.executeGesture (00:40:50.958) - winInputHook (19152):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (00:40:51.148) - winInputHook (19152):
Input: kb(laptop):downArrow

**Comment by seanbudd** [comment]
Hi @CyrilleB79,

We haven't been able to reproduce this issue.
Can you please provide a sample document and confirm the versions of software you're still reproducing this with?

**Comment by CyrilleB79** [comment]
@seanbudd, it's quite strange that you cannot reproduce: on my end, I can reproduce on 2 different computers, and today as well as five years ago.

To double check, I have reproduced the issue as follows:

STR:
* Download, unzip and open [SampleFormulasAndComments.zip](https://github.com/user-attachments/files/18972743/SampleFormulasAndComments.zip).
* Press NVDA+F7
* Shift+tab back on the tabs list and choose "Notes" tab.
* Tab in the list, actually a tree view, and look that it is empty whereas it should contain 2 notes.
* Shift+tab back on the tabs list and choose "Formulas" tab.
* Tab in the list, actually a tree view, and look that it is empty whereas it should contain 2 formulas.

Log: [nvda.log](https://github.com/user-attachments/files/18972789/nvda.log)

Versions:
* NVDA 2024.4.2rc1, started in English and without add-ons (`nvda --disable-addons --lang=en`)
* Excel 2016 (Microsoft® Excel® 2016 MSO (Version 2501 Build 16.0.18429.20132) 32-bit); with interface set in English (and restarted), just to be sure.
* Windows 10 22H2 (AMD64) build 19045.5371 (French localization)

In the past days, I have also reproduced on


I have also reproduced the issue with the following configuration:
* NVDA 2024.4.2rc1, without add-ons
* Excel 2021 LTSC (Microsoft® Excel® LTSC MSO (16.0.14332.20824) 64 bits), French GUI
* Windows 10 22H2

I hope this gives you more details, I've tried to provide as much as possible, and I am curious if we can understand why I can reproduce on my end but not you.

**Comment by michaelDCurran** [comment]
If I open the file in Excel,  enable editing (it was in protected view), 
press NVDA+f7, and choose notes, I see a3 and a7. Choosing formulas I 
see a1 and a5.

Perhaps this is an MS Office language difference?

Can you please open the sample file in Excel. Focus one of the cells. 
Open the NVDA Python console and execute:
nav.excelCellObject.worksheet.cells.specialCells(-4144).address(True, 
True, 1, True)

and paste here what you get.

This fetches the list of commented cell addresses.

I get:
'[SampleFormulasAndComments.xlsx]Sheet1!$A$3,$A$7'

If you get a different value to me. Can you please execute:
nav.excelCellObject.application.range(yourValue).count
Where `yourValue` is the value you got above.

I get 2. I'm assuming you get 0?

My hypothesis is that Your MS Office splits addresses using a different 
syntax, but specialCells.address and application.range(address) do not 
agree.

**Comment by CyrilleB79** [comment]
@michaelDCurran the file is not in protected view on my end; probably it is in protected view because you have downloaded it?

Anyway, in the console, I get:
```
>>> nav.excelCellObject.worksheet.cells.specialCells(-4144).address(True, True, 1, True)
'[SampleFormulasAndComments.xlsx]Sheet1!$A$3,$A$7'
```
At the same time as I execute the command, I get an error in the log, as shown in the following log fragment:

```
IO - inputCore.InputManager.executeGesture (00:01:36.997) - winInputHook (19948):
Input: kb(desktop):enter
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:01:37.023) - MainThread (6192):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 265334 (EXCEL7), objectID 1739, childID 0, process 9424 (excel), thread 19712
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:01:37.028) - MainThread (6192):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 265334 (EXCEL7), objectID 1740, childID 0, process 9424 (excel), thread 19712
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:01:37.028) - MainThread (6192):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONADD, window 265334 (EXCEL7), objectID 1741, childID 0, process 9424 (excel), thread 19712
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:01:37.028) - MainThread (6192):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 265334 (EXCEL7), objectID 1742, childID 0, process 9424 (excel), thread 19712
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:01:37.033) - MainThread (6192):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 265334 (EXCEL7), objectID 1743, childID 0, process 9424 (excel), thread 19712
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:01:37.033) - MainThread (6192):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 265334 (EXCEL7), objectID 1744, childID 0, process 9424 (excel), thread 19712
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (00:01:37.039) - MainThread (6192):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 265334 (EXCEL7), objectID 1745, childID 0, process 9424 (excel), thread 19712
ERROR - comtypes._comobject.call_without_this (00:01:37.033) - Dummy-5 (16576):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 154, in call_without_this
  File "UIAHandler\__init__.pyc", line 714, in IUIAutomationEventHandler_HandleAutomationEvent
  File "comtypes\__init__.pyc", line 278, in __getattr__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147417846, 'Le filtre de messages indiquait que l’application était occupée.', (None, None, None, 0, None))
IO - speech.speech.speak (00:01:37.100) - MainThread (6192):
Speaking ["'[SampleFormulasAndComments.xlsx]Sheet1!$A$3,$A$7'"]
```

Even if I get the same value as you, I have tried the following which is unexpected:
```
>>> nav.excelCellObject.application.range('[SampleFormulasAndComments.xlsx]Sheet1!$A$3,$A$7').count
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "comtypes\client\lazybind.pyc", line 60, in __call__
  File "comtypes\automation.pyc", line 746, in _invoke
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147352567, 'Une exception s’est produite.', (None, None, None, 0, None))
```

To summarize, I do not get 0 nor 2, but the error above.

**Comment by michaelDCurran** [comment]
application.range(address) needs to work, as it is executed in-process 
via nvdahelper.

That error is unexpected.

I'm wondering whether perhaps replacing the commas with semi colons in 
the address provided to application.range works?

I think although range.address() produces  a language-independent xla1 
notation, application.range expects a regional specific notation.

the other thing to try is instead of range.address(True, True, xlA1, 
True) try range.address(True, True, xlRC, True)

And passing that to application.range.

If this works, then in excel.py in the iterate method, change xlA1 to 
xlRC in the call to address = collectionObject.address(True, True, xlA1, 
True)

Failing all this, we can ask Excel what its international cell separator is.

I'd like to avoid walking the areas as this could add a lot more 
cross-process calls for very large sheets.
