### ISSUE TITLE
Error on Edge Chromium address bar with braille enabled.

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11370]
### Steps to reproduce:
1. Open Microsoft Edge (Chromium)
2. Open a new window (ctrl+n)
3. Focus the address bar with alt+d

### Actual behavior:
An error is raised:

```
ERROR - eventHandler.executeEvent (08:02:25.449) - MainThread (10544):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x06EB7730> with extra args of {}
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 296, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eventHandler.pyc", line 214, in executeEvent
  File "eventHandler.pyc", line 94, in __init__
  File "eventHandler.pyc", line 102, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\UIA\__init__.pyc", line 1053, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1106, in event_gainFocus
  File "braille.pyc", line 1908, in handleGainFocus
  File "braille.pyc", line 1913, in _doNewObject
  File "braille.pyc", line 1578, in getFocusRegions
  File "braille.pyc", line 994, in update
  File "NVDAObjects\UIA\__init__.pyc", line 759, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 300, in __init__
RuntimeError: Could not clone range
```

### Expected behavior:
No error, as without braille.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20514

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Edge Chromium 83.0.478.61'

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Andre9642** [comment]
Duplicate of #10980

**Comment by JulienCochuyt** [comment]
@leonardder, can you confirm that you only reproduce with an empty address bar, as in #10980?

This RuntimeError is raised by NVDA after catching a COMError when attempting to clone the range object.
This was introduced as of 59de1dcbcb by @michaelDCurran for #7997 with the following comment:
> IUIAutomationTextRange::clone can sometimes fail, such as in UWP account login screens

Could you please reproduce with debugwarning log level so that the original COMError gets logged? - In case it carries any relevant info.

**Comment by leonardder** [comment]
Closing as duplicate.

**Comment by leonardder** [comment]
@JulienCochuyt the original com error was part of the log, but just for completeness:

```
DEBUGWARNING - NVDAObjects.UIA.UIATextInfo.__init__ (11:26:49.748) - MainThread (13924):
Could not clone range
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 296, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

```

Let's continue the discussion in #10980. This is also one of the major issues #11079 suffers from, actually.

**Comment by JulienCochuyt** [comment]
@leonardder wrote:
> @JulienCochuyt the original com error was part of the log

Oops! You're right. Sorry for that. Seems I've read it too quickly.
