### ISSUE TITLE
NVDA not reading Excel 365 sheet name when renaming sheet

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11459]
### Steps to reproduce:

1. Open Excel
2. Press ALT+H, O, R to rename the current sheet.
3. Use the arrows to move through the name.

### Actual behavior:

At step 2, NVDA reports "Unknown".
At step 3, NVDA doesn't report anything (unless speak command keys is enabled, and then only the fact an arrow key is pressed is reported).

### Expected behavior:

Following step 2, NVDA should report the current sheet name, and that it is selected.  At step 3, NVDA should report the current position in the text, as in other text edit operations.

Two log fragments below, the first immediately upon pressing the 'R" in step 2 above:

```
IO - inputCore.InputManager.executeGesture (09:17:14.023) - winInputHook (32272):
Input: kb(laptop):r
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (09:17:14.209) - MainThread (31488):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
DEBUGWARNING - eventHandler.executeEvent (09:17:14.266) - MainThread (31488):
error executing event: typedCharacter on <NVDAObjects.UIA.MenuItem object at 0x06B1CCB0> with extra args of {'ch': 'r'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 214, in executeEvent
  File "eventHandler.pyc", line 94, in __init__
  File "eventHandler.pyc", line 102, in next
  File "NVDAObjects\__init__.pyc", line 1050, in event_typedCharacter
  File "speech\__init__.pyc", line 977, in speakTypedCharacters
  File "api.pyc", line 264, in isTypingProtected
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 924, in _get_isProtected
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1227, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 813, in _getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (09:17:14.279) - MainThread (31488):
oleacc.AccessibleObjectFromEvent with window 67634, objectID 1417 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (09:17:14.280) - MainThread (31488):
oleacc.AccessibleObjectFromEvent with window 67634, objectID 1405 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (09:17:14.282) - MainThread (31488):
oleacc.AccessibleObjectFromEvent with window 67634, objectID 1391 and childID 0: [WinError -2147467259] Unspecified error
IO - speech.speak (09:17:14.308) - MainThread (31488):
Speaking [LangChangeCommand ('en_GB'), 'unknown']
```

This second log fragment from subsequently pressing an arrow key in the sheet name edit with the name selected:

```
IO - inputCore.InputManager.executeGesture (09:17:15.712) - winInputHook (32272):
Input: kb(laptop):leftArrow
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (09:17:15.724) - MainThread (31488):
oleacc.AccessibleObjectFromEvent with window 67634, objectID 1465 and childID 0: [WinError -2147467259] Unspecified error
```

#### NVDA version:

2020.2 installed
I can also replicate on any version back to 2015.4 (earliest I tried) portable.

#### Windows version:
Windows 10 64-bit, 1903 build 18362

Also reported by user running Windows 10 version 2004.

#### Name and version of other software in use when reproducing the issue:

Office 365 (64-bit) Version: 
16.0.13001.20338 

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
As above
#### If addons are disabled, is your problem still occuring?
No add-ons installed.

**Comment by pranavlal** [comment]
Hi all,

I can duplicate this with the exact steps mentioned in the original entry.
Microsoft® Excel® for Microsoft 365 MSO (16.0.14228.20036) 
nvda version 2020.4.
Pranav

**Comment by ruifontes** [comment]
Tried with:
Windows 10 Version 21H1 (Build 19043.1055)
Microsoft® Excel® for Microsoft 365 MSO (16.0.14131.20278) 64 bits 
NVDA 2021.1RC1
and everything running as it should...

**Comment by Qchristensen** [comment]
@ruifontes are you using "Use UI Automation controls to access Microsoft Excel Spreadsheet controls when available"?

Just testing now with a slightly older build of Office: Office 365 (64-bit) Version: 16.0.14026.20306 - I found with that option enabled, it reads the sheet name when renaming, but with that disabled, it reads "unknown" and then silent as I arrow around.

**Comment by britechguy** [comment]
When using F6 to navigate through the various control regions, the Sheet name is not announced when one lands on it and it has focus during F6 traversal.  I believe it also does not announce when you left/right arrow through the worksheet tabs, but right now I have a problem with Excel where I cannot do this anyway if NVDA is active, but it works just fine when NVDA is not (which is a separate issue, and I believe one with Excel).

**Comment by comanna** [comment]
I have the same issue in Windows 11:
I am running excel within office 365
Microsoft Windows
Version 24H2 (OS Build 26100.3775)
NVDA Version: 2024.4.2 (2024.4.2.35031)

Steps to reproduce:
1.	Open an excel workbook;
2.	It opens on a worksheet called “Sheet1” by default;
3.	NVDA does not read the title of worksheet which is “Sheet1” by default;
4.	Press alt-h-o-r to rename the sheet;
5.	NVDA says “unknown” and will not echo the sheet name nor echo the edit box now lying open;
6.	Blindly thype in a new sheet name and press enter’
7.	NVDA echoes the new sheet name as the edit box closes;
8.	Pressing alt-h-o-r again: NVDA still says “unknown”;
9.	Only when a new worksheet is added will NVDA say the worksheet name after pressing alt -Page up or alt-page down to move from worksheet to worksheet.

All the best,

Cearbhall

M: +353 (0) 833323487; E: [cearbhall.omeadhra@blbc.ie](mailto:cearbhall.omeadhra@blbc.ie)

From: nvda@nvda.groups.io <nvda@nvda.groups.io> On Behalf Of Martin O'Sullivan via groups.io
Sent: Friday, April 18, 2025 5:52 PM
To: nvda@nvda.groups.io
Subject: [nvda] NVDA Will Not Read The Worksheet Name When I Am Editing It

NVDA will not read the worksheet name when I am editing it.
 
Steps to recreate 
 
Open excel 
 
Enter the following keyboard commands Alt > H > O > R 
 
Try typing a worksheet name in. 
 
I saw this issue on github, however it was from a few years back.  Is there a way to get this working?
 
https://github.com/nvaccess/nvda/issues/5154
_._,_._,_
________________________________________
Groups.io Links:
You receive all messages sent to this group. 
[View/Reply Online (#124370)](https://nvda.groups.io/g/nvda/message/124370) | [Reply to Group](mailto:nvda@nvda.groups.io?subject=Re:%20%5Bnvda%5D%20NVDA%20Will%20Not%20Read%20The%20Worksheet%20Name%20When%20I%20Am%20Editing%20It) | [Reply to Sender](mailto:osumartin@gmail.com?subject=Private:%20Re:%20%5Bnvda%5D%20NVDA%20Will%20Not%20Read%20The%20Worksheet%20Name%20When%20I%20Am%20Editing%20It) | [Mute This Topic](https://groups.io/mt/112334577/53070) | [New Topic](https://nvda.groups.io/g/nvda/post) 
________________________________________
NVDA Topics on Groups.io - https://nvda.groups.io/g/nvda/topics | NVDA Archive Search Page on Groups.io - https://nvda.groups.io/g/nvda/search 

NVDA is developed by NV Access in collaboration with the community. 
Get the Latest . . .
NVDA News from: https://www.nvaccess.org/news/
Version of NVDA from: https://www.nvaccess.org/download/
NVDA add-ons from the Add-Ons Store in the NVDA Tools Menu
Your continued donations help keep NVDA development going strong. Donate at: https://www.nvaccess.org/donate

Other links: 
NVAccess on Facebook: https://www.facebook.com/NVAccess/
________________________________________
[Your Subscription](https://nvda.groups.io/g/nvda/editsub/53070) | [Contact Group Owner](mailto:nvda+owner@nvda.groups.io) | [Unsubscribe](https://nvda.groups.io/g/nvda/leave/109045/53070/1067308947/xyzzy) [cearbhall.omeadhra@blbc.ie]
_._,_._,_
