### ISSUE TITLE
Internet Information Services (IIS) Manager: error when moving through listview

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11468]
### Steps to reproduce:
1. Open Internet Information Services (IIS) Manager
2. use the tree view to connect to a server and select a site.
3. Press tab until you reach the list view containing shortcuts to several feature pages.

### Actual behavior:
Traceback:

```
ERROR - eventHandler.executeEvent (11:02:12.320) - MainThread (3316):
error executing event: gainFocus on <NVDAObjects.IAccessible.sysListView32.ListItem object at 0x0555E6D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 214, in executeEvent
  File "eventHandler.pyc", line 94, in __init__
  File "eventHandler.pyc", line 102, in next
  File "\\install01\install$\000007 - sevenP\Leonard\nvda_portable\userConfig\addons\unicornNVDA\globalPlugins\unicorn\__init__.py", line 340, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 102, in next
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\behaviors.pyc", line 606, in reportFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 436, in _get_name
AttributeError: 'NoneType' object has no attribute 'width'
```

### Expected behavior:
NO error

#### NVDA installed/portable/running from source:
Portable

#### NVDA version:
2020.2

#### Windows version:
Windows Server 2012 R2

#### Name and version of other software in use when reproducing the issue:
Internet Information Services (IIS) Manager on said version of Windows server. However, it also applies to current versions of IIS manager.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NO

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by leonardder** [comment]
I'm pretty sure this is related to the fix in #2673, as LVM_GETVIEW returns 0 for this list. It is also a list with groupings in it.
