### ISSUE TITLE
Can't read address bar in Opera Browser

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11503]
### Steps to reproduce:

1. Open Opera Browser to any page.
2. Press ALT+D to move the focus to the address bar
3. Arrow through the letters.

### Actual behavior:

NVDA reads "Blank".  The following is recorded in the log:
```
IO - inputCore.InputManager.executeGesture (14:24:29.543) - winInputHook (8296):
Input: kb(laptop):leftArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (14:24:29.550) - MainThread (10348):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._callback (14:24:29.552) - Dummy-2 (15668):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:29.552) - Dummy-2 (15668):
Calling sync on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:29.552) - Dummy-2 (15668):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (14:24:29.553) - Dummy-2 (15668):
Queue empty, done processing
DEBUG - editableText.EditableText._hasCaretMoved (14:24:29.557) - MainThread (10348):
Caret move detected using bookmarks. Elapsed: 0 ms
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getFormatFieldAndOffsets (14:24:29.559) - MainThread (10348):
could not get attributes
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 233, in _getFormatFieldAndOffsets
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467263, 'Not implemented', (None, None, None, 0, None))
IO - speech.speak (14:24:29.560) - MainThread (10348):
Speaking [LangChangeCommand ('en_GB'), 'blank']


```
### Expected behavior:

NVDA should read the contents of the address bar as in other browsers.

#### NVDA version:

NVDA 2020.2 installed.

#### Windows version:

Windows 10 version 1903 (64-bit) Build: 18362 

#### Name and version of other software in use when reproducing the issue:

Opera version 69.0.3686.95

Reporting user (P.Otter in NVDA User email list) advised this worked in earlier versions of Opera.

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.2.1 and 2016.4 with same results
#### If addons are disabled, is your problem still occuring?
No add-ons
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No change

**Comment by Adriani90** [comment]
Testing with NVDA 2023.2 and Opera 102, NVDA kind of reads only a part of the address in the address bar. For example https://www.google.com, NVDA reads only until the first o.
* continue pressing right arrow NVDA just repeats the letter o.
* Pressing backspace cause NVDA to behave as expected.
* Arrowing left after pressing backspace, you will notice that the last letter of the address, which is "m", has been deleted as expected.

**Comment by seanbudd** [comment]
Is this still an issue?
