### ISSUE TITLE
Table navigation fails for this table with display: block in Firefox

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#11749]
### Steps to reproduce:

1. Go to [this page](https://newrustacean.com/show_notes/)
2. Press t to move to the sole table on the webpage and attempt to use table navigation commands (moving to next/previous row/column)

### Actual behavior:

Table navigation fails with the following traceback

```
ERROR - scriptHandler.executeScript (14:36:02.569) - MainThread (24764):
error executing script: <bound method DocumentWithTableNavigation.script_nextRow of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x06E70290>> with gesture 'alt+ctrl+down arrow'
Traceback (most recent call last):
  File "documentBase.pyc", line 157, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 433, in _getNearestTableCell
  File "documentBase.pyc", line 141, in _getNearestTableCell
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 421, in _getTableCellAt
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "documentBase.pyc", line 170, in script_nextRow
  File "documentBase.pyc", line 163, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 429, in _getTableCellAt
LookupError
```

### Expected behavior:

Table navigation succeeds

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21145,ac31a795

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Firefox 82.0 b9. IE11 doesn't recognize this as a table in browse mode. This error does not happen with Chrome

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by MarcoZehe** [comment]
@Neurrone Shot in the dark, but can you try this in Firefox Nightly? @jcsteh recently implemented a fix having to do with certain table constellations that might help here.

**Comment by Neurrone** [comment]
Tested with Firefox 85.0 B4 and I can no longer reproduce this problem, so it was fixed somewhere along the way.

Thanks @jcsteh.
