### ISSUE TITLE
Rich Text Area: 'NoneType' object has no attribute 'role'

### ISSUE THREAD

**Issue by aaclause** [nvaccess/nvda#11753]
### Steps to reproduce:
1. Open <https://www.tiny.cloud/> in Firefox.
2. Move by heading level 3 and stop on — A new mobile-first user experience for rich text editing —.
3. Press downarrow until you meet an Application container.
4. Press enter then escape to focus the Rich Text Area.
5. Press downarrow 6 times (after — A featherweight download, TinyMCE can handle any challenge you throw at it. —).

### Actual behavior:
The table is not properly shown and the following traceback is raised in the log:

```
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "editableText.pyc", line 218, in script_caret_moveByLine
  File "editableText.pyc", line 163, in _caretMovementScriptHelper
  File "NVDAObjects\behaviors.pyc", line 177, in _caretScriptPostMovedHelper
  File "editableText.pyc", line 149, in _caretScriptPostMovedHelper
  File "speech\__init__.pyc", line 1087, in speakTextInfo
  File "speech\types.pyc", line 42, in __iter__
  File "speech\__init__.pyc", line 1127, in getTextInfoSpeech
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 390, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 329, in _getText
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 261, in _iterRecursiveText
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 38, in _getRawTextInfo
AttributeError: 'NoneType' object has no attribute 'role'
```

### Expected behavior:
No error.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21170,e274931c

#### Windows version:
10 Insider (64-bit) build 20231.1000

#### Name and version of other software in use when reproducing the issue:
Firefox 81.0.1

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by aaclause** [comment]
Duplicate of #12542. I close this one as the website used for my “Steps to reproduce” has changed and the STR are better in #12542.
