### ISSUE TITLE
Unable to read Office installer window

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#11825]
### Steps to reproduce:
* Launch Office 2016 reparation with an admin account different from the currently logged user account
* Alt+Tab to the Office reparation window

### Actual behavior:

The window content is not read
Following error in log:

```
IO - inputCore.InputManager.executeGesture (10:50:21.806) - winInputHook (7492):
Input: kb(desktop):alt+tab
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (10:50:21.961) - MainThread (12940):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
IO - speech.speak (10:50:21.996) - MainThread (12940):
Speaking ['élément de liste']
ERROR - core.CorePump.run (10:50:22.001) - MainThread (12940):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 519, in run
  File "IAccessibleHandler\__init__.pyc", line 1085, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 759, in processFocusWinEvent
  File "IAccessibleHandler\__init__.pyc", line 619, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 715, in isUIAWindow
  File "_UIAHandler.pyc", line 684, in _isUIAWindowHelper
  File "baseObject.pyc", line 26, in __get__
  File "appModuleHandler.pyc", line 415, in _get_productName
  File "appModuleHandler.pyc", line 390, in _setProductInfo
RuntimeError: processHandle is 0
IO - inputCore.InputManager.executeGesture (10:50:23.479) - winInputHook (7492):
Input: kb(desktop):NVDA+tab
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (10:50:23.495) - MainThread (12940):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
IO - speech.speak (10:50:23.495) - MainThread (12940):
Speaking ['élément de liste']
```

The window content is not read either on request (NVDA+B).

### Expected behavior:
The window content is read when the window takes focus or on request.

### Notes

* I have just taken the error when it occurred. I will not have the possibility to reproduce it since the installer was not launched by me.
* Maybe this is just due to the fact that the installer was launched with a different account. Is NVDA supposed to read the content of applications launched with a different account?
If there is nothing to do in this case, feel free to close this issue.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.3
#### Windows version:
Version de Windows : Windows 10 1809 (64-bit) build 17763.1518
#### Name and version of other software in use when reproducing the issue:
MS Office 2016
#### Does the issue still occur after restarting your computer?
Do not know.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Not tested
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by leonardder** [comment]
The behavior of NVDA when using an application started on another user account is undetermined. I have the felling that sometimes it just works, in other cases it does not, also based on whether running as a portable copy or not, the used accessibility API, etc.

**Comment by CyrilleB79** [comment]
> @CyrilleB79 are you still able to reproduce this with NVDA 2023.1 RC1 and Office 2016 last build?

Not tested again. However, since I have currently update issues for my Windows (I still have Windows 10 2004) and since the issue seems related to UIA, I'd rather solve my update issue before performing tests again.

**Comment by Adriani90** [comment]
@CyrilleB79 any updates on this? Are you still on 2004? Or could you test this again?

**Comment by CyrilleB79** [comment]
Still on 2004.

**Comment by Adriani90** [comment]
@CyrilleB79 I cannot reproduce this issue with NVDA last alpha when installing / repairing Office 2016 or 365, but not sure I am doing something wrong here because I just have only one account on my PC and this is the admin account.
Are you still on 2004? Or could you solve the update issue you had before?

**Comment by Adriani90** [comment]
@CyrilleB79 any updates on this issue? ARe you still seeing it in newer versions of MS Office?
