### ISSUE TITLE
Say all throws an exception in a control that does not support setting the caret

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1201]
**Reported by jteh on 2010-11-16 06:31**
Say all does nothing in a control which does not support retrieving the caret, as expected. However, in a control which supports retrieval but not setting of the caret, an unhandled exception occurs. This is harmless but unclean.

Str:
1. Open a command prompt.
2. Press NVDA+downArrow.
3. Expected: No response.
4. Actual: Unhandled exception.

We can catch this and then either abort or ignore it. Ignoring might be confusing, as say all would appear to work but wouldn't move the caret. However, maybe this is desirable in some cases?

**Comment by ehollig** [comment]
@jcsteh is this still the case? I did not see anything alarming in the log when I performed the steps that you provided.

**Comment by derekriemer** [comment]
Can still reproduce.
1. open command prompt in win7.
2. press say all.

IO - speech.speak (18:36:19):
Speaking [IndexCommand(1), IndexCommand(2), IndexCommand(3), IndexCommand(4), IndexCommand(5), IndexCommand(6), IndexCommand(7), IndexCommand(8), IndexCommand(9), IndexCommand(10), IndexCommand(11)]
ERROR - queueHandler.pumpAll (18:36:19):
error in generator 497
Traceback (most recent call last):
  File "queueHandler.pyo", line 72, in pumpAll
  File "sayAllHandler.pyo", line 151, in readTextHelper_generator
  File "textInfos\offsets.pyo", line 493, in updateCaret
  File "textInfos\offsets.pyo", line 178, in _setCaretOffset
NotImplementedError
IO - inputCore.InputManager.executeGesture (18:36:21):
Input: kb(laptop):NVDA+f1

**Comment by jcsteh** [comment]
P3 because this is ugly and perhaps confusing, but it doesn't break any functionality that a user would expect to work.

**Comment by Adriani90** [comment]
This is still reproducible in Windows 10 1809 with NVDA 2019.1.1.

**Comment by Adriani90** [comment]
I cannot reproduce this with NVDA last alpha on Windows 11. @lukaszgo1 or @CyrilleB79 could you test if this exception still occurs under Windows 10? If not, then I vote for closing this issue since support for Windows 7 has ended.

**Comment by CyrilleB79** [comment]
Still reproducible on Windows 10 2004 (version 10.0.19041 Build 19041), which is out-of-date however. I will test on a more recent version later or next week.

**Comment by CyrilleB79** [comment]
And also reproducible in the console in Windows 10 22H2 (10.0.19045 Build 19045).

**Comment by Adriani90** [comment]
@CyrilleB79 are you meanwhile having the chance to test this on a newer Windows 10 build or even Windows 11? Is this still an issue in NVDA last alpha?

**Comment by CyrilleB79** [comment]
@Adriani90, I have no Windows 10 PC anymore.

On Windows 11 23H2 (AMD64) build 22631.5909, I have had difficulty opening `cmd.exe` instead of `WindowsTerminal.exe` since `cmd.exe` is redirected to WT. I have finally succeeded in opening a real `cmd.exe` with:
`C:\Windows\System32\conhost.exe C:\Windows\System32\cmd.exe`

With NVDA 2025.3rc1, the issue is not present anymore, neither in `cmd.exe`, nor in `WindowsTerminal.exe`.
