### ISSUE TITLE
Impossible to use any UIA control in latest Alpha

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#12227]
### Steps to reproduce:
1. Try to access any UIA application - list of files in Windows Explorer search box in menu start etc.

### Actual behavior:
Error sound plays and the following is in the log:
```
error executing event: gainFocus on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x05492D78> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "appModules\explorer.pyc", line 415, in event_gainFocus
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1142, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1137, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1005, in reportFocus
  File "speech\__init__.pyc", line 449, in speakObject
  File "speech\__init__.pyc", line 491, in getObjectSpeech
  File "speech\__init__.pyc", line 355, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1465, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 836, in _getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
_ctypes.COMError: (-2147024809, 'A parameter is incorrect.', (None, None, None, 0, None))

```

### Expected behavior:
No errors and controls should be readable.
#### NVDA installed/portable/running from source:
Tested with portable and from sources.

#### NVDA version:
NVDA version alpha-22132,d90b24e7
#### Windows version:
Windows 7 X64
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.4 works okay.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by lukaszgo1** [comment]
cc @michaelDCurran

**Comment by zstanecic** [comment]
I cannot reproduce this on windows 10 20h2.

 

 

From: Łukasz Golonka ***@***.***> 
Sent: Thursday, March 25, 2021 8:48 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] Impossible to use any UIA control in latest Alpha (#12227)

 


Steps to reproduce:


1.	Try to access any UIA application - list of files in Windows Explorer search box in menu start etc.


Actual behavior:


Error sound plays and the following is in the log:

error executing event: gainFocus on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x05492D78> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "appModules\explorer.pyc", line 415, in event_gainFocus
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1142, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1137, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1005, in reportFocus
  File "speech\__init__.pyc", line 449, in speakObject
  File "speech\__init__.pyc", line 491, in getObjectSpeech
  File "speech\__init__.pyc", line 355, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1465, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 836, in _getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
_ctypes.COMError: (-2147024809, 'A parameter is incorrect.', (None, None, None, 0, None))
 

Expected behavior:


No errors and controls should be readable.


System configuration


NVDA installed/portable/running from source:


Tested with portable and from sources.


NVDA version:


NVDA version alpha-22132,d90b24e7


Windows version:


Windows 7 X64


Name and version of other software in use when reproducing the issue:


None


Other information about your system:


Other questions


Does the issue still occur after restarting your computer?


Yes


Have you tried any other versions of NVDA? If so, please report their behaviors.


2020.4 works okay.


If add-ons are disabled, is your problem still occurring?


Yes


Did you try to run the COM registry fixing tool in NVDA menu / tools?


No

**Comment by XLTechie** [comment]
I can not repro either.  Can you perhaps give an exact STR, showing where it 
stops working?

Also, please run the com reg fixing tool.

**Comment by lukaszgo1** [comment]
This is a regression from #12210

**Comment by michaelDCurran** [comment]
We'll just need a try except catching COMError around the fetching of the annotationTypes property in _get_states. Looks like Windows 7 UIA core can't handle that property ID.
