### ISSUE TITLE
Hi, is there a problem or not when I press alt + f4 after the function fixes the problems in the com registry, NVDA closes

### ISSUE THREAD

**Issue by marcel-88** [nvaccess/nvda#12639]
I go to NVDA settings, to tools, and click on the function to fix registry problems. After the fix is ​​finished I press ok, and NVDA stops talking, if at that moment I press alt + f4 NVDA closes, but if I press Windows + d to go to the desktop NVDA starts talking again and doesn't close at pressing alt + f4.
 I want to know if this is a mistake or not, excuse me if it is a wrong place to report, I do not know another place to write. If there is another place, please show me. Thanks for understanding. And although he will apologize for my English, I use a translator.

**Comment by XLTechie** [comment]
I believe I know why this is happening. Expect a fix next week if testing 
confirms the fix I have in mind.

**Comment by Adriani90** [comment]
This is still occuring.
STR:
1. Open NVDA and e.g. a Firefox window
2. Run the COM reg fixing tool while you focus the firefox window
3. Press "contunue button"
4. After the tool performed fixes, press alt+f4.

Actual: NVDA speech is cancelled, but can be restored with alt+tab or e.g. opening NVDA menu with nvda+n.
After that, pressing up and down arrow key in Firefox window gives me following error:

```
IO - inputCore.InputManager.executeGesture (19:52:06.306) - winInputHook (14020):
Input: kb(laptop):downArrow
IO - inputCore.logTimeSinceInput (19:52:06.315) - MainThread (19988):
0.009 sec since input
IO - speech.speech.speak (19:52:06.315) - MainThread (19988):
Speaking ['Open ']
ERROR - scriptHandler.executeScript (19:52:06.330) - MainThread (19988):
error executing script: <bound method CursorManager.script_moveByLine_forward of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x00B967F0>> with gesture 'Pfeiltaste nach unten'
Traceback (most recent call last):
  File "IAccessibleHandler\__init__.pyc", line 328, in normalizeIAccessible
  File "comtypes\client\lazybind.pyc", line 127, in QueryInterface
  File "comtypes\_post_coinit\unknwn.pyc", line 520, in QueryInterface
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 33, in __call__
_ctypes.COMError: (-2147467262, 'Schnittstelle nicht unterstützt', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "cursorManager.pyc", line 323, in script_moveByLine_forward
  File "cursorManager.pyc", line 190, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1780, in _set_selection
  File "baseObject.pyc", line 39, in __get__
  File "textInfos\offsets.pyc", line 518, in _get_NVDAObjectAtStart
  File "virtualBuffers\__init__.pyc", line 233, in _getNVDAObjectFromOffset
  File "virtualBuffers\gecko_ia2.pyc", line 345, in getNVDAObjectFromIdentifier
  File "IAccessibleHandler\__init__.pyc", line 330, in normalizeIAccessible
RuntimeError: <comtypes.client.lazybind.Dispatch object at 0x0561D930> Not an IAccessible
```
Restarting NVDA at this point leads to the Firefox window not getting focus anymore. I have to kill the Firefox process and start Firefox again in order to navigate the window properly.

Expected behavior:
Pressing al+f4 on the registration fixing tool should either not be possible at all, or it should perform the same action as when pressing the ok button.



cc: @jcsteh since I could reproduce this directly with Firefox, but I guess it is a COM registration fixing tool problem in general.

**Comment by Adriani90** [comment]
Now NVDA does not close anymore and the speech is not interupted.
But when pressing alt+f4 on the welcome dialog of COM registry fixing tool, the fixing process is started.
Expected behavior: Welcome dialog should close without starting the COM registry fixing process when pressing alt+f4.
cc: @SaschaCowley, @seanbudd

**Comment by CyrilleB79** [comment]
@Adriani90 please open a specific issue for this: it's a regression of 2025.1 and should be handled separately.
Cc @seanbudd, @SaschaCowley

**Comment by Adriani90** [comment]
Closing in favor of #18090 and because this particular issue does not occur anymore.
