### ISSUE TITLE
Error in the Input gesture manager allowing to open many instances of them

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#12673]
### Steps to reproduce:

* Open the Input gesture manager
* Shift-tab back in the filter field
* Type a string with a typo leading to no result in the tree, e.g. "zzzz"
* Press Escape to close the dialog
* Open the input gesture manager dialog
* Open again the input gesture manager dialog, without closing the previous instance.

### Actual behavior:

* First errors in the log appear as soon as you type "zzzz"
* Two or more instances of the input gesture manager are opened

### Expected behavior:

* No error in the log
* There should not be a way to open two instances of the input gesture manager and the usual message should appear.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.1

#### Windows version:
Windows 10 2004 (64-bit) build 19041.388

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.4 does not have this issue.

#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

Maybe a regression with wxPython upgrade?
Cc @seanbudd

**Comment by feerrenrut** [comment]
@CyrilleB79 Could you attach a log snippet for the error please?

**Comment by CyrilleB79** [comment]
Yes. Sorry. I had prepared the log but have forgotten to attach it to this issue.
I'll attach it when I am back on my home's computer tonight.

**Comment by CyrilleB79** [comment]
Here is the log: 
[nvda.log](https://github.com/nvaccess/nvda/files/6869875/nvda.log)

The first error is line 403.

**Comment by feerrenrut** [comment]
Thanks @CyrilleB79
Here is the error / stack for convenience:
```
DEBUG - gui.inputGestures._GesturesTree.getData (23:10:05.261) - MainThread (18736):
Getting data for item indexes (0, None, None)
ERROR - gui.inputGestures._GesturesTree.getData (23:10:05.264) - MainThread (18736):
Exceeded expected categories bounds, trying to access category with index 0, but only 0 exist.
Stack trace:
  File "nvda.pyw", line 359, in <module>
  File "core.pyc", line 750, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "gui\inputGestures.pyc", line 626, in onFilterChange
  File "gui\inputGestures.pyc", line 634, in filter
  File "gui\inputGestures.pyc", line 541, in doRefresh
  File "wx\lib\mixins\treemixin.pyc", line 371, in RefreshItems
  File "wx\lib\mixins\treemixin.pyc", line 397, in RefreshChildrenRecursively
  File "gui\inputGestures.pyc", line 639, in onTreeSelect
  File "gui\inputGestures.pyc", line 642, in _refreshButtonState
  File "gui\inputGestures.pyc", line 489, in getSelectedItemData
  File "gui\inputGestures.pyc", line 505, in getData
ERROR - unhandled exception (23:10:05.265) - MainThread (18736):
Traceback (most recent call last):
  File "gui\inputGestures.pyc", line 639, in onTreeSelect
  File "gui\inputGestures.pyc", line 642, in _refreshButtonState
  File "gui\inputGestures.pyc", line 489, in getSelectedItemData
  File "gui\inputGestures.pyc", line 499, in getData
IndexError: list index out of range
```
