### ISSUE TITLE
Error sounds in input to main message window in Outlook Express

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1268]
**Reported by briang1 on 2010-12-10 13:10**
These errors occur seemingly at random, and I don't think they do any harm, but as they occur, I thought I'd record the fact in case they have any relevence.
(I could not find any ticket for this, but if you can close this one!)
Input: kb(desktop):n
IO - speech._speakSpellingGen (12:37:15):
Speaking character u'n'
ERROR - eventHandler.executeEvent (12:37:15):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionBodyMSHTMLIAccessibleWindowNVDAObject object at 0x02377DB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 135, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 90, in next
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 300, in event_caret
  File "NVDAObjects\IAccessible__init__.pyc", line 1165, in event_caret
  File "NVDAObjects__init__.pyc", line 804, in event_caret
  File "NVDAObjects__init__.pyc", line 839, in makeTextInfo
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 176, in **init**
  File "core.pyc", line 40, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 149, in **getattr**
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147023899, 'Overlapped I/O operation is in progress.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (12:37:15):
Input: kb(desktop):space
IO - speech.speakTypedCharacters (12:37:15):
typed word: in
IO - speech._speakSpellingGen (12:37:15):
Speaking character u'space'

Above is the log fragment from one of the errors i encountered in snap 3978.

These have been hanging around for a while, so not new.

Obviously a person using a release version would not see them.
 They are rare, and seem to happen in batches in a message, then nothing for  ages.

**Comment by leonardder** [comment]
Closing, OE abandoned.
