### ISSUE TITLE
I couldn't upgrade nvda alpha 23571 to alpha 23584 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12740]
### Steps to reproduce:
on my machine it was with nvda alpha 23571, so i used the new version check in nvda help menu, i found nvda alpha 23584.
I asked for nvda to update itself
nvda downloaded the update, pressed enter on install now, the copy of nvda closed and the installer opened.
the uac window was displayed, I confirmed with the yes button, and after a few seconds the error window appeared informing me that it was not possible to delete a file, I repeated the process and the error continued.
I restarted the computer and the nvda installation seemed to be corrupt as nvda did not start.
Using the narrator I downloaded the installer from the nv access page and managed to install nvda.
I reported this problem today but this same error has already occurred when trying to update from some alphas back, I believe that since the beginning of last week, I update nvda alpha every day when I turn on the computer. 
### Actual behavior:
impossible to update. 
### Expected behavior:
error-free upgrade 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
alfa 23584
#### Windows version:
10.0.19044.1165
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[instalation.txt](https://github.com/nvaccess/nvda/files/6994182/instalation.txt)

**Comment by seanbudd** [comment]
Judging by the logs, this looks like it could be caused by add-ons. Try disabling the ones which appear in the following stacktraces:


```python
Trying to recover from freeze. Listing stacks for Python threads:
Python stack for thread 9496 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 452, in _run
  File "winUser.pyc", line 425, in getMessage

Python stack for thread 436 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 126, in _watcher
  File "watchdog.pyc", line 62, in getFormattedStacksForAllThreads

Python stack for thread 4052 (Thread-9):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\audiothemes\globalPlugins\audiothemes\unspoken\mixer.py", line 40, in feeder_func
    self.queue.put(block_string, block=True)
  File "queue.pyc", line 139, in put
  File "threading.pyc", line 296, in wait

Python stack for thread 11692 (Thread-10):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\audiothemes\globalPlugins\audiothemes\unspoken\mixer.py", line 57, in player_func
    self.player.feed(send_string)
  File "nvwave.pyc", line 332, in feed
  File "nvwave.pyc", line 347, in _feedUnbuffered_handleErrors
  File "nvwave.pyc", line 378, in _feedUnbuffered
  File "nvwave.pyc", line 404, in sync
  File "winKernel.pyc", line 261, in waitForSingleObject

Python stack for thread 6648 (Bluetooth Audio background beeper thread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\bluetoothaudio\globalPlugins\bluetoothAudio.py", line 52, in run
    playerLocal.feed(buf.raw)
  File "nvwave.pyc", line 332, in feed
  File "nvwave.pyc", line 347, in _feedUnbuffered_handleErrors
  File "nvwave.pyc", line 378, in _feedUnbuffered
  File "nvwave.pyc", line 404, in sync
  File "winKernel.pyc", line 261, in waitForSingleObject

Python stack for thread 336 (Thread-5):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 1175, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 300, in wait

Python stack for thread 7692 (Thread-4):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\tonysEnhancements\globalPlugins\tonysEnhancements.py", line 683, in run
    tones.beep(150, 10, left=25, right=25)
  File "tones.pyc", line 60, in beep
  File "nvwave.pyc", line 332, in feed
  File "nvwave.pyc", line 347, in _feedUnbuffered_handleErrors
  File "nvwave.pyc", line 371, in _feedUnbuffered
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\tonysEnhancements\globalPlugins\tonysEnhancements.py", line 576, in preWaveOpen
    winmm.waveOutSetVolume(selfself._waveout, volume2)

Python stack for thread 10392 (MPVEventHandlerThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\zPod\globalPlugins\zPod\lib\mpv.py", line 857, in _loop
    for event in _event_generator(self._event_handle):
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\zPod\globalPlugins\zPod\lib\mpv.py", line 636, in _event_generator
    event = _mpv_wait_event(handle, -1).contents

Python stack for thread 9312 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 14268 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 340, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 12824 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2229, in func

Python stack for thread 13828 (Thread-1):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 467, in run
    task()
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 450, in __call__
    self.__lib.RHVoice_speak(msg)
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 346, in __call__
    self.__player.play(string_at(samples,count*sizeof(c_short)))
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 288, in play
    self.do_play(self.__prev_data)
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 278, in do_play
    player.feed(data)
  File "nvwave.pyc", line 332, in feed
  File "nvwave.pyc", line 347, in _feedUnbuffered_handleErrors
  File "nvwave.pyc", line 378, in _feedUnbuffered
  File "nvwave.pyc", line 404, in sync
  File "winKernel.pyc", line 261, in waitForSingleObject

Python stack for thread 9836 (MainThread):
  File "nvda.pyw", line 362, in <module>
  File "core.pyc", line 746, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "gui\installerGui.pyc", line 266, in onInstall
  File "gui\installerGui.pyc", line 91, in doInstall
  File "gui\installerGui.pyc", line 60, in doInstall
  File "gui\__init__.pyc", line 752, in __init__
  File "gui\__init__.pyc", line 830, in Notify
  File "core.pyc", line 707, in run
  File "IAccessibleHandler\__init__.pyc", line 960, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 545, in processGenericWinEvent
  File "IAccessibleHandler\__init__.pyc", line 490, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 45, in getNVDAObjectFromEvent
  File "IAccessibleHandler\__init__.pyc", line 263, in accessibleObjectFromEvent
  File "oleacc.pyc", line 265, in AccessibleObjectFromEvent
```



```python
ERROR - globalPluginHandler.listPlugins (12:48:03.984) - MainThread (9836):
Error importing global plugin winguido
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
AttributeError: module 'globalPlugins.winguido' has no attribute 'GlobalPlugin'
ERROR - globalPluginHandler.listPlugins (12:48:04.000) - MainThread (9836):
Error importing global plugin winword
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
AttributeError: module 'globalPlugins.winword' has no attribute 'GlobalPlugin'
DEBUGWARNING - Python warning (12:48:04.487) - MainThread (9836):
C:\Users\ferna\AppData\Roaming\nvda\addons\zPodCast\globalPlugins\zPodCast\vlc.py:1802: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  if not any(getargspec(callback)[:2]):  # list(...)
DEBUGWARNING - Python warning (12:48:04.601) - MainThread (9836):
C:\Users\ferna\AppData\Roaming\nvda\addons\wordReview\globalPlugins\wordReview\libs\bs4\element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'
```

**Comment by fernando-jose-silva** [comment]
I uninstalled some addons, I hope you have uninstalled the mail, waiting for a new alpha to try to update.

**Comment by fernando-jose-silva** [comment]
unfortunately upgrading to the most resentful alpha again was not possible.
Does anyone have any more ideas, or which addon should I uninstall?
The log follows again. 
[instalation2.txt](https://github.com/nvaccess/nvda/files/7000187/instalation2.txt)

**Comment by Brian1Gaff** [comment]
It looks like you have some complex interaction going on between add ons to 
me. The last time this occured I disabled all then did the install and 
proved it worked, Once there I had to painstakingly re enable the add ons 
one at a time  and see what happened on the reboot.
 I wonder, did you just tweak the manifests of some of the add ons and now 
they are saying they are compatible but in fact have some syntax which may 
need so adjusting?

Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by lukaszgo1** [comment]
It would be nice to establish if this is cuased by add-ons in the first place. The easiest way to do seems to be:
1. Wait for the next Alpha to show up but don't accept to install it.
2. Shutdown NVDA and with another screen reader /  portable copy of NVDA rename NVDA's config in appdata` to `nvda-old`
3. Start NVDA let it create a new config and attempt to update to the next Alpha.

**Comment by fernando-jose-silva** [comment]
thank you very much to everyone it seems I managed to solve the problem around here.
I'm not a programmer so I can't say for sure that this was the cause of the problem, but the error stopped happening when I updated the addon
TiendaNVDA-0.5.nvda-addon
I will close the call, any question I am available.
