### ISSUE TITLE
NVDA never speak after restart Windows

### ISSUE THREAD

**Issue by moyanming** [nvaccess/nvda#12754]
### Steps to reproduce:
Every restart of Windows 10 21H1 Home/Pro.
BTW, the turn-off and then turn on of Windows 10 OS have no issue.

### Actual behavior:
NVDA will not speak anymore.

### Expected behavior:
NVDA should speak after restart OS.

#### NVDA installed/portable/running from source:
There is only a USB audio device on the computer.
I found that the USB audio device will be recognized by Windows after a restart will take about 5 seconds, but NVDA starts fast and it seems that the NVDA never found the audio device and NVDA will never speak then. If I restart NVDA, the speaker works fine.
Are there key functions that can "refresh" the NVDA to find the audio device?

#### NVDA version:
test with NVDA 2020.4 and 2021.1 are both have this issue.

#### Windows version:
21H1 home/pro

**Comment by feerrenrut** [comment]
Thanks for reporting @moyanming, NVDA should detect the preferred device and swap to it when it becomes available. This is also true if you use the Microsoft sound mapper.

First let's confirm what is happening:
- Please set your logging level to debug
- One the advanced settings page, enable "nvwave" debug logging category.
- Save your config
- Restart your computer to reproduce the issue
- Once NVDA starts, open the log viewer and save the log
- Attach it to this issue.

**Comment by moyanming** [comment]
> Thanks for reporting @moyanming, NVDA should detect the preferred device and swap to it when it becomes available. This is also true if you use the Microsoft sound mapper.
> 
> First let's confirm what is happening:
> 
> * Please set your logging level to debug
> * One the advanced settings page, enable "nvwave" debug logging category.
> * Save your config
> * Restart your computer to reproduce the issue
> * Once NVDA starts, open the log viewer and save the log
> * Attach it to this issue.

Hi, @feerrenrut 
Sorry for the late reply.
Please find the "first boot OS without speech.log" and "restart NVDA works fine.log" in the attachments.
1. Test on the Windows 21H1 with NVDA 2021.1.
2. First boot OS there is no speech, but restart NVDA the speech works fine.
3. There is only one audio device on this computer: a USB audio device.
This USB audio device was recognized by OS about 5~10 seconds later after restarting OS, but it is recognized without delay when shut down and then boot the OS.
4.The following log comes from the "first boot OS without speech.log" and seems that the nvware can't open and find the audio device and it does not retry to do so.
The "使用的设备标识号已超出本地系统范围" may be means "The device is not find on the system.".

Any ideas?

DEBUG - core.main (09:22:52.054) - MainThread (5400):
Initializing tones
DEBUG - nvwave.WavePlayer.open (09:22:52.054) - MainThread (5400):
Calling winmm.waveOutOpen. outputDeviceName: WAVE_MAPPER outputDeviceID: -1
DEBUG - nvwave.WavePlayer._handleWinmmError (09:22:52.054) - MainThread (5400):
Winmm Error: Error opening outputDeviceName: WAVE_MAPPER with id: -1
Stack trace:
  File "nvda.pyw", line 359, in <module>
  File "core.pyc", line 454, in main
  File "tones.pyc", line 28, in initialize
  File "nvwave.pyc", line 212, in __init__
  File "nvwave.pyc", line 302, in open
  File "nvwave.pyc", line 529, in _handleWinmmError
DEBUG - nvwave.WavePlayer._close (09:22:52.054) - MainThread (5400):
Calling winmm.waveOutClose
WARNING - nvwave.WavePlayer.open (09:22:52.054) - MainThread (5400):
Unable to open WAVE_MAPPER device, there may be no audio devices.
WARNING - tones.initialize (09:22:52.054) - MainThread (5400):
Failed to initialize audio for tones
Traceback (most recent call last):
  File "tones.pyc", line 28, in initialize
  File "nvwave.pyc", line 212, in __init__
  File "nvwave.pyc", line 298, in open
  File "nvwave.pyc", line 111, in _winmm_errcheck
FileNotFoundError: [Errno 2] 使用的设备标识号已超出本地系统范围。


[first boot OS without speech.log](https://github.com/nvaccess/nvda/files/7044817/first.boot.OS.without.speech.log)
[restart NVDA works fine.log](https://github.com/nvaccess/nvda/files/7044819/restart.NVDA.works.fine.log)

**Comment by moyanming** [comment]
Hi, @feerrenrut 
Another scenario should be concerned:
There is only one audio device on the computer: a USB audio device, this USB audio device may be disconnect during the NVDA running, and the NVDA should reopen this USB audio device when it is reconnecting to the computer.

**Comment by moyanming** [comment]
NVDA should always use the current default Windows audio device when output audio, but not open and use the one when NVDA first start.

**Comment by feerrenrut** [comment]
We are too late in the 2021.3 dev cycle to be able to include this. We'll need to investigate more closely to be able to confidently suggest an approach. Pushing this back to 2022.1

**Comment by lukaszgo1** [comment]
Are you really planning to skip 2021.4 making two backwards compatibility breaking releases in less than a year?

**Comment by ABuffEr** [comment]
> > There is a similar issue for braille devices as well. As reported as follows:
> > > I've got a user with a problem with a Braille display (Focus 40) - where when NVDA starts with the computer, it doesn't work, but if she then restarts NVDA, it works.
> 
> I don't thing these are related in any way - NVDA uses completelly different mechanism for automatic braille display detection and for setting up audio devices. Also for what its worth I do have Focus 40 connected to my machine for about a month and haven't experienced this problem even a single time so there is probably something particular to their system here.

Confirm, at least until 2021.2. It could be related to Windows Braille support via BRLTTY: if you tried Braille via Narrator in the past, even disabling Narrator, when Windows 10 updates itself to a major version the display could be switched again to BRLTTY/libusb support instead of Freedom drivers.

**Comment by lukaszgo1** [comment]
> Confirm, at least until 2021.2. It could be related to Windows Braille support via BRLTTY: if you tried Braille via Narrator in the past, even disabling Narrator, when Windows 10 updates itself to a major version the display could be switched again to BRLTTY/libusb support instead of Freedom drivers.



This cannot be the issue here. If LibUSB got  enabled Focus displays becomes non functional with NVDA and the reported issue states:
> but if she then restarts NVDA, it works.

which clearly suggests that proper drivers are installed and the issue lies with the auto detection.

**Comment by seanbudd** [comment]
> Are you really planning to skip 2021.4 making two backwards compatibility breaking releases in less than a year?

2021.4 is going to be skipped as it won't be able to be released before the year of 2021 ends, and releasing it in 2022 leads to confusion and the assumption that the release is late.
2022.1 is expected to be a compatibility breaking release, and won't be made until 2022.
In order to release at least four releases next year, we aim to release 2022.1 much earlier in the year than 2021.1 was released. 
2022.1 has to be a compatibility breaking release to include fixes such as #12710.
To further discuss API compatibility breaking releases, please create a new issue or contact info@nvaccess.org, as it is not related to this issue.

**Comment by Adriani90** [comment]
@moyanming are you still having this issue in NVDA 2024.4.1?
