### ISSUE TITLE
NVDA always reports "section multi line editable" in MS 365 Online

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12762]
### Steps to reproduce:
1. Open this link: https://eurekavi-my.sharepoint.com/:w:/g/personal/rowen_enabc_net/EXjpxqF2GZ9Oi_o6abFnbikBVcF7TAxmBbe_YS_jVMmxzw?e=QnCrXN
2. Try to use the up and down arrow keys to navigate in the document editing area;

### Actual behavior:
- NVDA will read "section multi line editable" in advance before reporting the content of each line.
- NVDA will announce "section multi line editable blank" in the blank line.
### Expected behavior:
Be consistent with the behavior in other editors:
- NVDA directly announces the content of each line.
- NVDA reports "blank" in a blank line.

#### NVDA installed/portable/running from source:
installed and portable.

#### NVDA version:
2020.4; 2021.1;
#### Windows version:
Windows 10 21H1 (x64) build 19043.1165
#### Name and version of other software in use when reproducing the issue:
Chrome 92.0.4515.159

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Many early versions of NVDA behave the same.

#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cary-rowen** [comment]
Hi, @seanbudd 

The issue cannot be reproduced using FireFox, should I report it to the chromium team?

Thanks

**Comment by seanbudd** [comment]
@cary-rowen - Potentially. Without a minimal code sample and a technical investigation, we can't confirm that this isn't an issue with NVDA

**Comment by cary-rowen** [comment]
I also reported this issue to chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1393237

**Comment by Adriani90** [comment]
Following error is written to the log when pressing up and down arrow while navigating the text:
```
IO - inputCore.InputManager.executeGesture (10:46:21.628) - winInputHook (1872):
Input: kb(laptop):upArrow
ERROR - scriptHandler.executeScript (10:46:21.658) - MainThread (20072):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x0829F110>> with gesture 'Pfeiltaste nach oben'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "editableText.pyc", line 235, in script_caret_moveByLine
  File "editableText.pyc", line 171, in _caretMovementScriptHelper
  File "editableText.pyc", line 90, in _hasCaretMoved
  File "documentBase.pyc", line 74, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 120, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 232, in _findContentDescendant
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
```

**Comment by Adriani90** [comment]
cc: @aleventhal there is a bug on Chromium for this but no activity so far. This is important for users especially working in Online Office 365 environments.
Not sure if this has to do with how Chromium renders contentEditable="true" atributes on edit fields. At least on read only fields NVDA character navigation does not work at all.

**Comment by Adriani90** [comment]
I tested in a word document opening it in the MS Word web app.
This seems to be fixed in Chrome and Edge 124, Firefox 125. Tested with NVDA last alpha. Closing as works for me. If you are still having this issue, please comment with a new test case and we can reopen.
