### ISSUE TITLE
scons source error

### ISSUE THREAD

**Issue by rhythm1827** [nvaccess/nvda#12909]
After installing all the dependencies to run NVDA I faced this error. 
Python version: 3.7.9 (32 bit)
`
Error: Command '['C:\\Users\\eGeneration Ltd\\Desktop\\pywinautoexamples\\nvda\\.venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 101.
Traceback (most recent call last):
  File "C:\Users\eGeneration Ltd\Desktop\pywinautoexamples\nvda\venvUtils\\ensureVenv.py", line 148, in <module>
    ensureVenvAndRequirements()
  File "C:\Users\eGeneration Ltd\Desktop\pywinautoexamples\nvda\venvUtils\\ensureVenv.py", line 112, in ensureVenvAndRequirements
    return createVenvAndPopulate()
  File "C:\Users\eGeneration Ltd\Desktop\pywinautoexamples\nvda\venvUtils\\ensureVenv.py", line 68, in createVenvAndPopulate
    check=True
  File "C:\Users\eGeneration Ltd\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\eGeneration Ltd\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe', '-m', 'venv', '--clear', 'C:\\Users\\eGeneration Ltd\\Desktop\\pywinautoexamples\\nvda\\venvUtils\\..\\.venv']' returned non-zero exit status 1.
`

**Comment by rhythm1827** [comment]
@CyrilleB79 Sorry, I don't add the solution. 
Just I had just moved the nvda directory to C drive. That's solved this problem. 
Thank you.
