### ISSUE TITLE
With latest Master, documents are nomore accessible under LibreOffice Writer

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#12919]
### Steps to reproduce:
Open LibreOffice Writer and try to write some text.
### Actual behavior:
NVDA does not see nor the texte neither the cursor position.
### Expected behavior:
We should be able to review the document.
#### NVDA installed/portable/running from source:
NVDA installed
#### NVDA version:
alpha-23903,fb4466ee
#### Windows version:
Windows 10 21H2 64 bits
#### Name and version of other software in use when reproducing the issue:
LibreOffice 7.2.1 64 bits

**Comment by lukaszgo1** [comment]
Confirmed with latest Alpha.
When moving with up and down arrows 'blank' is reported. With left and right error sound plays, and the following is in the log:
```
error executing script: <bound method EditableText.script_caret_moveByCharacter of <compoundDocuments.CompoundDocument object at 0x073B3630>> with gesture 'left arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "editableText.pyc", line 228, in script_caret_moveByCharacter
  File "editableText.pyc", line 163, in _caretMovementScriptHelper
  File "editableText.pyc", line 149, in _caretScriptPostMovedHelper
  File "speech\speech.pyc", line 1138, in speakTextInfo
  File "speech\types.pyc", line 42, in __iter__
  File "speech\speech.pyc", line 1335, in getTextInfoSpeech
AttributeError: 'NoneType' object has no attribute 'isspace'

```

This does not occur with 2021.2.

**Comment by MichelSuch** [comment]
Is there a chance this could be repaired for 2021.3?

**Comment by feerrenrut** [comment]
@MichelSuch we are looking into it. The list of issues that are blocking the release can be found by looking at [the 2021.3 milestone](https://github.com/nvaccess/nvda/milestone/57), currently it is just this issue.
