### ISSUE TITLE
error when opening a new file in VSCode

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#13003]
### Steps to reproduce:

1. Open VSCode, then press ctrl--k-o to open a folder. Or, open a project. The goal is that ctrl-p will have files to choose from.
2. Open a file.
3. Press ctrl-p, choose a file, and press enter to open it.

### Actual behavior:
When the new file opens, NVDA plays an error sound. The log contains the following:

```
ERROR - eventHandler.executeEvent (11:13:20.026) - MainThread (36216):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x04BA5790> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\behaviors.pyc", line 188, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1173, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1028, in reportFocus
  File "speech\speech.pyc", line 555, in speakObject
  File "speech\speech.pyc", line 604, in getObjectSpeech
  File "documentBase.pyc", line 22, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 129, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 158, in _getSelectionBase
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 228, in _findContentDescendant
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 30, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

### Expected behavior:
No error should be produced.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.3 beta 1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
VSCode 1.60.1
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
To my knowledge, 2021.2 and earlier didn't do this, though as error sounds never play outside of betas, I may have just not noticed. This error doesn't impact usability, as far as I can tell, so I'd have had no reason to check the NVDA log when opening files.
#### If NVDA add-ons are disabled, is your problem still occurring?
not yet tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
@mehgcap are you still having this issue with NVDA 2024.4.1?
