### ISSUE TITLE
Errors in Input Gestures Dialog when a category has too many elements

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#13017]
### Steps to reproduce:
1. Install a plugin with many scripts (for example, 4035).
2. Open the corresponding category in Input Gestures dialog.
3. Use the "Filter by:"field to search an element without closing the category.
### Actual behavior:
Error sounds are played and the log contain unhandled exceptions.
### Expected behavior:
No errors, exceptions should be properly handled, or add a note in the developer guide about the maximum number of commands allowed in a category.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3beta1
#### Windows version:
Versión 20H2 (compilación de SO 19042.1288) (copied in Spanish).
#### Name and version of other software in use when reproducing the issue:
Development version of Emoticons add-on
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I haven't tried other versions of NVDA
#### If NVDA add-ons are disabled, is your problem still occurring?
No (this requires add-ons to be enabled)
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[insertSymbol.zip](https://github.com/nvaccess/nvda/files/7463133/insertSymbol.zip)
Attached is a relevant plugin and NVDA's log

**Comment by feerrenrut** [comment]
Could you please test this with NVDA 2021.2. I'd like to know if this is a regression.

**Comment by nvdaes** [comment]
Testing this in NVDA 2021.2 I don't get errors. I've tested it from scratchpad.

**Comment by nvdaes** [comment]
Hi again, seems that the error is not a regression. What happened is that I didn't listen the error sound since NVDA 2021.2 is stable.
But I have set the log in debug level and I get the same error:

< ERROR - unhandled exception (15:40:29.608) - MainThread (7268):
Traceback (most recent call last):
  File "gui\inputGestures.pyc", line 650, in onTreeSelect
  File "gui\inputGestures.pyc", line 653, in _refreshButtonState
  File "gui\inputGestures.pyc", line 497, in getSelectedItemData
  File "gui\inputGestures.pyc", line 510, in getData
IndexError: list index out of range
DEBUG - gui.inputGestures._GesturesTree.getData (15:40:29.609) - MainThread (7268):
Getting data for item indexes (1, None, None)
ERROR - gui.inputGestures._GesturesTree.getData (15:40:29.610) - MainThread (7268):
Exceeded expected categories bounds, trying to access category with index 1, but only 1 exist.
Stack trace:
  File "nvda.pyw", line 362, in <module>
  File "core.pyc", line 746, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "gui\inputGestures.pyc", line 637, in onFilterChange
  File "gui\inputGestures.pyc", line 645, in filter
  File "gui\inputGestures.pyc", line 552, in doRefresh
  File "wx\lib\mixins\treemixin.pyc", line 371, in RefreshItems
  File "wx\lib\mixins\treemixin.pyc", line 397, in RefreshChildrenRecursively
  File "gui\inputGestures.pyc", line 650, in onTreeSelect
  File "gui\inputGestures.pyc", line 653, in _refreshButtonState
  File "gui\inputGestures.pyc", line 497, in getSelectedItemData
  File "gui\inputGestures.pyc", line 516, in getData
ERROR - unhandled exception (15:40:29.611) - MainThread (7268):
Traceback (most recent call last):
  File "gui\inputGestures.pyc", line 650, in onTreeSelect
  File "gui\inputGestures.pyc", line 653, in _refreshButtonState
  File "gui\inputGestures.pyc", line 497, in getSelectedItemData
  File "gui\inputGestures.pyc", line 510, in getData
IndexError: list index out of range
DEBUG - gui.inputGestures._GesturesTree.getData (15:40:29.612) - MainThread (7268):
Getting data for item indexes (1, None, None)
ERROR - gui.inputGestures._GesturesTree.getData (15:40:29.613) - MainThread (7268):
Exceeded exp

...
