### ISSUE TITLE
NVDA makes an error sound when alt tabbing to Windows Terminal

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#13194]
/CC @codeofdusk 

### Steps to reproduce:

This does not happen all the time. This was observed while I SSHed into another system, and the command I executed was writing progress info to the screen, similar to apt when it installs software

Press alt-tab to bring focus to Terminal

### Actual behavior:

The following error is logged upon focusing on Terminal. I'm unable to switch to object navigation to review text, as that also leads to this same error being logged.

```
error executing event: gainFocus on <NVDAObjects.Dynamic_WinTerminalUIAEditableTextWithAutoSelectDetectionUIA object at 0x055A4590> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\behaviors.pyc", line 358, in event_gainFocus
  File "NVDAObjects\behaviors.pyc", line 188, in event_gainFocus
  File "NVDAObjects\UIA\__init__.pyc", line 1265, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1176, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1031, in reportFocus
  File "speech\speech.pyc", line 555, in speakObject
  File "speech\speech.pyc", line 607, in getObjectSpeech
  File "baseObject.pyc", line 26, in __get__
  File "textInfos\__init__.pyc", line 448, in _get_isCollapsed
  File "NVDAObjects\UIA\__init__.pyc", line 907, in compareEndPoints
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

### Expected behavior:

Using Terminal works as per usual

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-24399,b5f82f87

#### Windows version:
Windows 10 21h2

#### Name and version of other software in use when reproducing the issue:

Windows Terminal 1.11.3471.0

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Brian1Gaff** [comment]
So you have switched on error sounds?
 I have to say, there are a lot of errors that make sounds in that mode, but 
many of them are benign. Are you saying this one actually affects the 
outcome?
 Most of this type tend to be due to timing issues between what was there 
but is not there now!

 Still see what others think.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Dickson Tan" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Monday, December 27, 2021 7:41 AM
Subject: [nvaccess/nvda] NVDA makes an error sound when alt tabbing to 
Windows Terminal (Issue #13194)

**Comment by Neurrone** [comment]
Yes. This prevented me from reading anything. It only resolved itself once the command finished running.

**Comment by ehollig** [comment]
Hello @Neurrone. Is this error still occurring with NVDA 2023.1?

**Comment by Neurrone** [comment]
This doesn't seem to be a problem anymore, closing.
