### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#13401]
This is an issue that primarily affects developers, the standard issue template doesn't apply well.
Unfortunately there are not reliable steps to reproduce the issue, however here is an example of the test **[Robot.chromeTests.pr11606](https://ci.appveyor.com/project/NVAccess/nvda/builds/42706260/tests)** failing.
This is build: `pr13391-24822,2c54fafa` of [master](https://github.com/nvaccess/nvda/tree/master) [2c54fafa](https://github.com/nvaccess/nvda/commit/2c54fafa69e5e02fd0439979cc6e5b48acec4154) merged with [gestureForDetails](https://github.com/nvaccess/nvda/tree/gestureForDetails) [b8f79d0c](https://github.com/nvaccess/nvda/commit/b8f79d0c1f6d878cab2434387f1628e339dcaacf)

Fails with error (note the newline):
```
speech Actual != Expected: out of link != out of link
space
```

NVDA log for this test, note the timestamps for `out of link` and `space` are both at `11:17:05.336`
```
IO - inputCore.InputManager.executeGesture (11:17:05.086) - RF Test Spy Thread (4272):
Input: kb(desktop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:17:05.321) - MainThread (5616):
Caret move detected using bookmarks. Elapsed: 10 ms
IO - speech.speech.speak (11:17:05.336) - MainThread (5616):
Speaking [LangChangeCommand ('en'), 'out of link']
IO - speech.speech.speak (11:17:05.336) - MainThread (5616):
Speaking [LangChangeCommand ('en'), 'space', EndUtteranceCommand()]
IO - braille.BrailleBuffer.update (11:17:06.273) - MainThread (5616):
Braille regions text: ['NVDA Browser Test Case (783285141) doc ', 'mln editable sect ', 'lst •  lnk A  lnk B ']
DEBUG - external:globalPlugins.speechSpyGlobalPlugin.NVDASpyLib.dump_speech_to_log (11:17:06.429) - RF Test Spy Thread (4272):
dump_speech_to_log.
```
Further down: all NVDA speech collected by the system test spy is dumped to the log. It does not contain the `space` speech:
```
All speech:
[
[''],
[LangChangeCommand ('en'), 'Taskbar  ', IndexCommand(1)],
[LangChangeCommand ('en'), 'NVDA Browser Test Case (783285141)   Google Chrome  ', IndexCommand(2)],
[LangChangeCommand ('en'), 'NVDA Browser Test Case (783285141)  ', 'document  ', IndexCommand(3)],
[LangChangeCommand ('en'), 'Before Test Case Marker  ', IndexCommand(4)],
[LangChangeCommand ('en'), 'Test page load complete  ', IndexCommand(5)],
[LangChangeCommand ('en'), 'Test page load complete  ', IndexCommand(6)],
[LangChangeCommand ('en'), 'Focus mode  ', IndexCommand(7)],
[LangChangeCommand ('en'), 'section  ', 'multi line  ', 'editable  ', 'list  ', 'bullet  ', 'link  ', 'A  ', '  ', 'link  ', 'B  ', IndexCommand(8)],
[LangChangeCommand ('en'), 'out of link  ', IndexCommand(9)]
]
```
The robot framework test log timestamps show that both the `out of link` and `space` speech were received between `emulateKeyPress` and `wait_for_speech_to_finish`:

| Timestamp   | Action |
| ---                | ---      | 
|11:17:05.086 |  emulateKeyPress ('rightArrow',) |
|11:17:06.289  |  wait_for_speech_to_finish {'speechStartedIndex': 9}	|
|11:17:06.289  |	get_speech_at_index_until_now (9,)	
|11:17:06.289  | assert speech string matches (ignore case: False):  'out of link <br>space'	|
|11:17:06.289  | Argument types are:<br><type 'unicode'><br><type 'unicode'>	|
|11:17:06.289|repr of (speech) actual vs expected (ignore_case=False):<br>'out of link'<br>vs<br>'out of link\nspace'	|
|11:17:06.305 | speech Actual != Expected: out of link != out of link<br>space |
|11:17:06.305|Traceback (most recent call last):<br>  File "C:\projects\nvda\tests\system\robot\chromeTests.py", line 594, in test_pr11606<br>    "space"<br>  File "C:\projects\nvda\tests\system\libraries\AssertsLib.py", line 28, in strings_match<br>    ignore_case=ignore_case<br>  File "C:\projects\nvda\.venv\lib\site-packages\robot\libraries\BuiltIn.py", line 823, in should_be_equal_as_strings<br>    self._should_be_equal(first, second, msg, values, formatter)<br>  File "C:\projects\nvda\.venv\lib\site-packages\robot\libraries\BuiltIn.py", line 642, in _should_be_equal<br>    assert_equal(first, second, msg, include_values, formatter)<br>  File "C:\projects\nvda\.venv\lib\site-packages\robot\utils\asserts.py", line 182, in assert_equal<br>    _report_inequality(first, second, '!=', msg, values, formatter)<br>  File "C:\projects\nvda\.venv\lib\site-packages\robot\utils\asserts.py", line 231, in _report_inequality<br>    raise AssertionError(msg) |

The screenshot does not highlight any potential cause.

**Comment by feerrenrut** [comment]
To preserve the system test result artifact from the failed build: [pr13391-24822,2c54fafa-systemTestResult.zip](https://github.com/nvaccess/nvda/files/8160317/pr13391-24822.2c54fafa-systemTestResult.zip)

**Comment by Adriani90** [comment]
cc: @gerald-hartig, @SaschaCowley for triaging.

**Comment by seanbudd** [comment]
Given our change in test environments, closing in favour of individual issues for GitHub actions failures.
