### ISSUE TITLE
Intermittent error sounds in Firefox after introduction of PR #13399

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#13433]
### Steps to reproduce:
There is no clear STR for this issue as the error is intermittent. The problem occurs most often when clicking on a link which opens a new page in Firefox.
### Actual behavior:
Error sound plays and the following is in the log:
```
ERROR - eventHandler.executeEvent (15:38:45.771) - MainThread (5616):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x077E5590> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "D:\nvda_py3.8\userConfig\addons\remote\globalPlugins\remoteClient\__init__.py", line 458, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 107, in next
  File "D:\nvda_py3.8\userConfig\addons\unicornNVDA\globalPlugins\unicorn\__init__.py", line 345, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\behaviors.pyc", line 241, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1152, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1052, in reportFocus
  File "speech\speech.pyc", line 558, in speakObject
  File "speech\speech.pyc", line 601, in getObjectSpeech
  File "speech\speech.pyc", line 433, in getObjectPropertiesSpeech
  File "NVDAObjects\IAccessible\mozilla.pyc", line 82, in hasDetails
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1554, in _get_detailsRelations
  File "NVDAObjects\IAccessible\__init__.pyc", line 1497, in _getIA2TargetsForRelationsOfType
  File "comtypes\__init__.pyc", line 1152, in QueryInterface
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147417836, 'Requested object does not exist.', (None, None, None, 0, None))

```

### Expected behavior:
No error
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
alpha-24876,2325be89
#### Windows version:
Windows 7 X64
#### Name and version of other software in use when reproducing the issue:
Firefox Nightly 99 X64
#### Does the issue still occur after restarting your computer?
Yes, it does
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No problem with versions of NVDA before #13399 
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried.

**Comment by lukaszgo1** [comment]
cc @feerrenrut Given that this occurs for objects which just disappeared the simplest way to fix this seems to be to just ignore this particular error as there is nothing we can do.

**Comment by paulber19** [comment]
Hi.
This always happens with thunderbird 31.6 since 
nvda_snapshot_alpha-24852c267db9f .
No error with thunderbird 91.0
Best regards.
Paul.

**Comment by feerrenrut** [comment]
@lukaszgo1 and @paulber19 Could you please test with this [try-build](https://ci.appveyor.com/api/buildjobs/qxi2p6nuywxc6gav/artifacts/output%2Fnvda_snapshot_try-fixFirefoxDetails-24931%2C43598547.exe ) of #13456

**Comment by paulber19** [comment]
Hi.
Test result:
There is no longer an error with thunderbird 31.6, but there is a new 
one that always occurs when launching Firefox, while there is none with 
nvda version alpha-24937.4df1ded2.
Here is the error:
ERROR - eventHandler.executeEvent (10:29:17.103) - MainThread (2616):
error executing event: gainFocus on 
<NVDAObjects.IAccessible.mozilla.Mozilla object at 0x076A01D0> with 
extra args of {}
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 1477, in 
_get__IA2Relations
   File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220995, 'L’objet n’est pas connecté au serveur', 
(None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "eventHandler.pyc", line 284, in executeEvent
   File "eventHandler.pyc", line 98, in __init__
   File "eventHandler.pyc", line 107, in next
   File "NVDAObjects\__init__.pyc", line 1152, in event_gainFocus
   File "NVDAObjects\__init__.pyc", line 1052, in reportFocus
   File "speech\speech.pyc", line 558, in speakObject
   File "speech\speech.pyc", line 601, in getObjectSpeech
   File "speech\speech.pyc", line 433, in getObjectPropertiesSpeech
   File "NVDAObjects\IAccessible\mozilla.pyc", line 81, in hasDetails
   File "baseObject.pyc", line 42, in __get__
   File "baseObject.pyc", line 146, in _getPropertyViaCache
   File "NVDAObjects\IAccessible\__init__.pyc", line 1568, in 
_get_detailsRelations
   File "NVDAObjects\IAccessible\__init__.pyc", line 1550, in 
_getIA2RelationFirstTarget
   File "baseObject.pyc", line 42, in __get__
   File "baseObject.pyc", line 146, in _getPropertyViaCache
   File "NVDAObjects\IAccessible\__init__.pyc", line 1479, in 
_get__IA2Relations
NotImplementedError

Best regards.

**Comment by feerrenrut** [comment]
Thanks for testing, I'll look at this again on Monday.

**Comment by feerrenrut** [comment]
Please could you test with the following [try build](https://ci.appveyor.com/api/buildjobs/o382y7t5bcxuc62m/artifacts/output%2Fnvda_snapshot_try-fixFirefoxDetails-24947%2C74ab929d.exe)

**Comment by paulber19** [comment]
Hi.
I no longer see any errors.
Best regards.
Paul.
