### ISSUE TITLE
Errors when hovering mouse over image in Word

### ISSUE THREAD

**Issue by FalkoBabbage** [nvaccess/nvda#13528]
### Steps to reproduce:
Open a word document with an image in the document.
Hover over that image with the mouse.
### Actual behavior:
NVDA tries to expand an expand an textInfo Object every time the mouse event is fired, each time resulting in the following error in the NVDA Log:
```
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\__init__.pyc", line 1120, in event_mouseMove
  File "NVDAObjects\window\winword.pyc", line 917, in expand
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 89, in new__getattr__
  File "comtypes\client\dynamic.pyc", line 110, in __getattr__
  File "comtypes\automation.pyc", line 708, in GetIDsOfNames
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147352570, 'Unknown name.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (14:54:23.385) - MainThread (3288):
error executing event: mouseMove on <NVDAObjects.Dynamic_WinwordWordDocumentWordDocumentIAccessibleWindowNVDAObject object at 0x06DEA050> with extra args of {'x': 878, 'y': 488}
Traceback (most recent call last):
  File "comtypes\client\lazybind.pyc", line 123, in __bind
KeyError: ('Expand', 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 87, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 161, in __getattr__
  File "comtypes\client\lazybind.pyc", line 126, in __bind
  File "comtypes\typeinfo.pyc", line 366, in Bind
NameError: Name Expand not found
```
### Expected behavior:
NVDA should not try to do this on an image, or at least to try and catch this error before it runs into these COM errors, especially in frequently called events as mouseMove events.
#### NVDA installed/portable/running from source:
NVDA Portable
#### NVDA version:
NVDA 2022.1 Beta2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Microsoft® Word for Microsoft 365 MSO (version 2202 Build 16.0.14931.20128) 64 bits 
#### Other information about your system:
-
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2021.3.4 does not do this. I have checked it with and without "Use UI Automation to access Microsoft Word Document controls when available" option in Advanced tab.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

In event_mouseMove of the NVDAObject class there is the line "info.expand(info.unit_mouseChunk)". The code of the WordDocumentTextInfo in winword.py then tries "self._rangeObj.Expand(NVDAUnitsToWordUnits[unit])", which it fails to do.

**Comment by seanbudd** [comment]
I reproduced this with NVDA version 2021.3.5. This isn't a regression, just that error sounds only happen in betas and alphas by default.
Does this have any user impact? Otherwise, we can fix this in a future release.

**Comment by Adriani90** [comment]
I cannot reproduce with NVDA alpha-36438,ced96e51 (2025.2.0.36438)
on Windows 11 24 H2 and Microsoft 365 MSO (Version 2504 Build 16.0.18730.20122) 64 Bit


Probably this has been fixed either by Microsoft or by any updates of external dependencies of NVDA. Closing as works for me. If you are still having this issue, please comment and we can reopen.
