### ISSUE TITLE
Problem with the dialog new profile in Microsoft Outlook (without existing profiles)

### ISSUE THREAD

**Issue by Carlos-EstebanM** [nvaccess/nvda#13525]
### Steps to reproduce:
1. Is necessary have one profile (or more) in Outlook and delete all. So, with an email account put in Outlook, go to the file menu, tab information and press account setingss for open a menu.
2. In this menu, select manage profiles and after, show profiles.
3. Select and delete all the profiles and close Outlook.
4. Open Outlook Again.

### Actual behavior:
NVDA can't detect the focus changes presing tab in the dialog new profile.
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x057648B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1621, in event_caret
  File "NVDAObjects\window\edit.pyc", line 825, in event_caret
  File "NVDAObjects\window\edit.pyc", line 855, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 667, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'
### Expected behavior:
NVDA read the dialog, that have an edit box for the name and the button cancel.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.1 beta2
#### Windows version:
Windows 11 build 22000.556
#### Name and version of other software in use when reproducing the issue:
Microsoft Office 365 build 16.0.14931.20128
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. NVDA 2021.3.4 has the same problem.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2025.3.1 and MS Outlook 365 version 2509.
cc: @michaelDCurran, @SaschaCowley
