### ISSUE TITLE
No braille when opening a message in Thunderbird

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#13599]
### Steps to reproduce:
Try to read a mail with Thunderbird
### Actual behavior:
When reading the mail line by line, speech correctly announces what is on the line, but braille only displays "Unknown".
### Expected behavior:
Braille should the content of the current line.
#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA version alpha-25209,21367c8e
#### Windows version:
Windows 11 21H2 (x64) build 22000.593
#### Name and version of other software in use when reproducing the issue:
Thunderburd x64 91.8.0

**Comment by feerrenrut** [comment]
1. Which braille display are you using?
2. Please provide a [debug level log](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) (with add-ons disabled).

**Comment by MichelSuch** [comment]
Let me add that it works fine with previous Master version 25159,c4466885


Le 12/04/2022 à 08:18, Michel Such a écrit :

**Comment by feerrenrut** [comment]
Error in the log:
```
rror in func VirtualBuffer._loadBufferDone
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "virtualBuffers\__init__.pyc", line 492, in _loadBufferDone
  File "browseMode.pyc", line 1306, in event_treeInterceptor_gainFocus
  File "virtualBuffers\gecko_ia2.pyc", line 532, in _getInitialCaretPos
  File "browseMode.pyc", line 1850, in _getInitialCaretPos
UnboundLocalError: local variable 'caretPos' referenced before assignment
```

Will be fixed with #13601

**Comment by feerrenrut** [comment]
This is a duplicate of #13600
