### ISSUE TITLE
Getting review cursor position info fails with missing hint when word document is in protected mode

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13602]
### Steps to reproduce:
1. Download [test.docx](https://github.com/nvaccess/nvda/files/8469518/test.docx);
2. Open it in ms Word;
3. The files downloaded from the internet will be in protected mode, you can confirm this by pressing F6;
4. Press NVDA+numpDelete.
### Actual behavior:
NVDA plays an error tone and logs the following error:

```
_ctypes.COMError: (-2146823683, None, ('此方法或属性无效，因为 该文档被锁定，无法编辑。', 'Microsoft Word', 'wdmain11.chm', 37373, None))
WARNING - RPC process 7976 (WINWORD.EXE) (10:09:45.059) - Dummy-33 (9280):
```

### Expected behavior:
The ideal is to have no errors and be able to report location information.
If it is indeed impossible to report status information, a user-friendly prompt should be given.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.1Beta3
#### Windows version:
Windows 10 21H2 (x64) build 19044.1586
#### Name and version of other software in use when reproducing the issue:
ms word365
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
@cary-rowen I cannot reproduce this issue with NVDA 2025.3.1 and MS Office 365 version 2509. Can you please update MS Office 365 and see whether it is reproducible on your machine?

**Comment by cary-rowen** [comment]
cc @Adriani90 
Are you sure?

Could you provide the steps to reproduce the problem and the following information?
It would be even better if you could provide screen recording and audio output.

* **Microsoft 365MSO (版本 2510 Build 16.0.19328.20144) 64 Bit**
* **Windows 10 22H2 (AMD64) build 19045.6456**
* **NVDA2025.3.1 (2025.3.1.53219)**

```log
IO - speech.speech.speak (23:30:01.728) - MainThread (472):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - inputCore.executeGesture (23:30:02.520) - winInputHook (16656):
Input: kb(laptop):NVDA+delete
ERROR - scriptHandler.executeScript (23:30:02.548) - MainThread (472):
error executing script: <bound method GlobalCommands.script_caretPos_currentDimensions of <globalCommands.GlobalCommands object at 0x069CAA90>> with gesture 'NVDA+删除'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "globalCommands.pyc", line 1514, in script_caretPos_currentDimensions
  File "globalCommands.pyc", line 1468, in script_reportCaretLocation
  File "globalCommands.pyc", line 1427, in _reportLocationText
  File "baseObject.pyc", line 39, in __get__
  File "NVDAObjects\UIA\wordDocument.pyc", line 211, in _get_locationText
  File "baseObject.pyc", line 39, in __get__
  File "NVDAObjects\window\winword.pyc", line 825, in _get_locationText
  File "NVDAObjects\window\winword.pyc", line 1990, in getLocalizedMeasurementTextForPointSize
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 94, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 146, in __getattr__
  File "comtypes\automation.pyc", line 851, in _invoke
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 33, in __call__
_ctypes.COMError: (-2146823683, None, ('此方法或属性无效，因为 该文档被锁定，无法编辑。', 'Microsoft Word', 'wdmain11.chm', 37373, None))
IO - inputCore.executeGesture (23:30:03.457) - winInputHook (16656):
Input: kb(laptop):control+shift+NVDA+f1
```

**Comment by Adriani90** [comment]
STR:
1. Open document
2. Pressed nvda+delete
3. Pressed f6
4. Pressed nvda+delete
5. Pressed tab
6. Pressed nvda+delete
7. Pressed f6
8. Pressed nvda+delet

Actual: in all tese cases NVDA reported the location properly (see the log file attached).

Tested in:
Windows 11 24 H2
Nvda 2025.3.1
Microsoft 365 MSO (Version 2510 Build 16.0.19328.20144) 64 Bit

[nvda+del.txt](https://github.com/user-attachments/files/23293106/nvda%2Bdel.txt)

**Comment by Adriani90** [comment]
It might be specific to Windows 10 22 H2, but then it is out of support, Windows 10 support officially ended in Oktober 2025.
