### ISSUE TITLE
Microsoft Edge: intermittent short freezes when moving with Tab

### ISSUE THREAD

**Issue by Futyn-Maker** [nvaccess/nvda#14229]
### Steps to reproduce:

1. Open any site in Microsoft Edge;
2. Fastly Move with 'Tab' and 'Shift+Tab' by links, forward and back

### Actual behavior:

Sometimes, the NVDA speech response is delayed by about a second after pressing Tab. After few seconds it starts response fastly again, but these freezes happen periodicaly (and often).

### Expected behavior:

Microsoft Edge with NVDA works without any freezes

### NVDA logs, crash dumps and other attachments:

There are two errors that I've found when freezes happen:

```
ERROR - core.CorePump.run (10:39:34.582) - MainThread (11772):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 785, in run
  File "braille.pyc", line 2408, in pumpAll
  File "braille.pyc", line 2131, in handlePendingCaretUpdate
  File "braille.pyc", line 2137, in _doCursorMove
  File "braille.pyc", line 1176, in update
  File "textInfos\offsets.pyc", line 534, in compareEndPoints
AttributeError: 'ITextDocumentTextInfo' object has no attribute '_startOffset'
ERROR - eventHandler.executeEvent (10:39:35.885) - MainThread (11772):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x0A431A10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 301, in executeEvent
  File "eventHandler.pyc", line 102, in __init__
  File "eventHandler.pyc", line 111, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1649, in event_caret
  File "NVDAObjects\window\edit.pyc", line 836, in event_caret
  File "NVDAObjects\window\edit.pyc", line 862, in makeTextInfo
  File "documentBase.pyc", line 61, in makeTextInfo
  File "textInfos\offsets.pyc", line 476, in __init__
  File "NVDAObjects\window\edit.pyc", line 298, in _getSelectionOffsets
  File "winKernel.pyc", line 278, in virtualAllocEx
OSError: [WinError 6] Неверный дескриптор.
ERROR - eventHandler.executeEvent (10:39:35.892) - MainThread (11772):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x0A431A10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 301, in executeEvent
  File "eventHandler.pyc", line 102, in __init__
  File "eventHandler.pyc", line 111, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1649, in event_caret
  File "NVDAObjects\window\edit.pyc", line 836, in event_caret
  File "NVDAObjects\window\edit.pyc", line 862, in makeTextInfo
  File "documentBase.pyc", line 61, in makeTextInfo
  File "textInfos\offsets.pyc", line 476, in __init__
  File "NVDAObjects\window\edit.pyc", line 298, in _getSelectionOffsets
  File "winKernel.pyc", line 278, in virtualAllocEx
OSError: [WinError 6] Неверный дескриптор.
```

or

```
ERROR - core.CorePump.run (10:45:51.973) - MainThread (5584):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 785, in run
  File "braille.pyc", line 2408, in pumpAll
  File "braille.pyc", line 2131, in handlePendingCaretUpdate
  File "braille.pyc", line 2137, in _doCursorMove
  File "braille.pyc", line 1106, in update
  File "braille.pyc", line 1286, in _getSelection
  File "documentBase.pyc", line 66, in _get_selection
  File "documentBase.pyc", line 61, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 208, in __init__
  File "textInfos\offsets.pyc", line 476, in __init__
  File "virtualBuffers\__init__.pyc", line 213, in _getSelectionOffsets
OSError: [WinError 1775] При удаленном вызове процедуры главному компьютеру от клиента был передан пустой дескриптор контекста
```

#### NVDA installed/portable/running from source:

Installed
#### NVDA version:

2022.3

#### Windows version:

Windows 11 21H2 (x64) build 22000.376

#### Name and version of other software in use when reproducing the issue:

MS Edge 106

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No (don't think it's relevant)

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by feerrenrut** [comment]
We can't reproduce this as it stands, a complete debug level log would give us more context around the issue.

Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

**Comment by michaelDCurran** [comment]
Technical:
The first few tracebacks seem unrelated as they refer to richEdit support, which is not related to Edge's Chromium IAccessible2 implementation.

**Comment by Adriani90** [comment]
@Futyn-Maker I cannot reproduce this with NVDA 2022.4 and Microsoft Edge 110. Could you please test with these versions iuf the problem is occuring? Make sure that the Microsoft Edge Window is maximized.

**Comment by Adriani90** [comment]
are you using the setting automatically  switch to focus mode when the system focus or system carret is moving? This settings can be turned on and off in browse mode category of NVDA
s settings dialog.

**Comment by Futyn-Maker** [comment]
I'm sorry, it looked like the problem was out of NVDA's scope, but in my PC configuration. I just forgot to close it.
