### ISSUE TITLE
NVDA goes silent while selecting cells in excel with UIA enabled.

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#14230]
### Steps to reproduce:
Make sure that the UIA with excel is enabled.
- Open the excel(blank workbook is also fine).
- when your focus is on Cell "A1", keep pressing shift+down arrow key to select the 
cells.

### Actual behavior:

NVDA goes silent once 20 cells are selected.
Afterwards, The cells are get selected, but NVDA does not announce anything.
### Expected behavior:

NVDA should announce entire selected range regardless of the range length.

Note: Similar issue can be observed when shift+right arrow key is used for the cell selection
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2022.3
#### Windows version:
Windows 11
#### Name and version of other software in use when reproducing the issue:
Latest MS Excel with office 365
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same with previous versions
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by msviolafangirl** [comment]
I can confirm this is an issue. In my case, once I select more than 3 rows or columns, NVDA quits announcing the selected range and just says "quick analysis available".

**Comment by Adriani90** [comment]
I get following error when UIA in Excel is enabled and selecting a higher number of cells in a blank excel with NVDA, no add-ons in use.

```
IO - speech.speech.speak (14:26:37.570) - MainThread (9736):
Speaking ['A1', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (14:26:40.170) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:26:40.193) - MainThread (9736):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 459800 (EXCEL7), objectID 437, childID 0, process 9764 (excel), thread 6504
IO - speech.speech.speak (14:26:40.270) - MainThread (9736):
Speaking ['ausgewählt', 'A1  bis B1 ', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (14:26:40.601) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:26:40.611) - MainThread (9736):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 459800 (EXCEL7), objectID 438, childID 0, process 9764 (excel), thread 6504
IO - speech.speech.speak (14:26:40.690) - MainThread (9736):
Speaking ['ausgewählt', 'A1  bis C1 ', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (14:26:40.780) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:26:40.815) - MainThread (9736):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 459800 (EXCEL7), objectID 439, childID 0, process 9764 (excel), thread 6504
IO - speech.speech.speak (14:26:40.894) - MainThread (9736):
Speaking ['ausgewählt', 'A1  bis D1 ', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (14:26:40.950) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:26:40.960) - MainThread (9736):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 459800 (EXCEL7), objectID 440, childID 0, process 9764 (excel), thread 6504
IO - speech.speech.speak (14:26:41.031) - MainThread (9736):
Speaking ['ausgewählt', 'A1  bis E1 ', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (14:26:41.461) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:26:41.470) - MainThread (9736):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 459800 (EXCEL7), objectID 441, childID 0, process 9764 (excel), thread 6504
IO - inputCore.InputManager.executeGesture (14:26:41.502) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:26:41.513) - MainThread (9736):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 459800 (EXCEL7), objectID 442, childID 0, process 9764 (excel), thread 6504
IO - inputCore.InputManager.executeGesture (14:26:41.530) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.560) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.600) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.630) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.660) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.695) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - speech.speech.speak (14:26:41.695) - MainThread (9736):
Speaking ['ausgewählt', 'A1  bis K1 ', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (14:26:41.730) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.765) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.795) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.830) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.860) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.896) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.930) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.960) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:41.996) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
IO - inputCore.InputManager.executeGesture (14:26:42.020) - winInputHook (1392):
Input: kb(laptop):shift+rightArrow
ERROR - eventHandler.executeEvent (14:26:42.071) - MainThread (9736):
error executing event: gainFocus on <NVDAObjects.UIA.excel.ExcelCell object at 0x04E6D3B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1382, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1147, in reportFocus
  File "speech\speech.pyc", line 687, in speakObject
  File "speech\speech.pyc", line 726, in getObjectSpeech
  File "speech\speech.pyc", line 582, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\excel.pyc", line 431, in _get_cellCoordsText
AttributeError: 'NoneType' object has no attribute 'QueryInterface'
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (14:26:42.120) - MainThread (9736):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
DEBUGWARNING - eventHandler.executeEvent (14:26:42.150) - MainThread (9736):
error executing event: gainFocus on <NVDAObjects.UIA.excel.ExcelCell object at 0x051F9610> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1382, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1147, in reportFocus
  File "speech\speech.pyc", line 687, in speakObject
  File "speech\speech.pyc", line 726, in getObjectSpeech
  File "speech\speech.pyc", line 582, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\excel.pyc", line 364, in _get_states
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1692, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 987, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
```

**Comment by Adriani90** [comment]
Adding some advanced logging for UIA, events and synth driver, I get following in the log, it seems an exception occurs on the cell and is displayed in the developer info.

```
IO - inputCore.InputManager.executeGesture (16:21:11.451) - winInputHook (34388):
Input: kb(laptop):shift+downArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (16:21:11.451) - MainThread (21548):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 1051002 (EXCEL7), objectID 85, childID 0, process 32604 (excel), thread 9064
DEBUG - UIAHandler.UIAHandler.IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent (16:21:11.451) - Dummy-2 (2196):
handleFocusChangedEvent called with element A1 Element with automationID A1, className XLSpreadsheetCell and frameworkID [None]
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.451) - Dummy-2 (2196):
checking if is native UIA  element: A1 Element with automationID A1, className XLSpreadsheetCell and frameworkID [None]
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.451) - Dummy-2 (2196):
Locating nearest ancestor windowHandle for element A1 Element with automationID A1, className XLSpreadsheetCell and frameworkID [None]
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.458) - Dummy-2 (2196):
Found ancestor element with valid windowHandle hwnd 0X10097A of class EXCEL7
DEBUG - UIAHandler.UIAHandler.isUIAWindow (16:21:11.458) - Dummy-2 (2196):
Found cached is UIA window True for hwnd hwnd 0X10097A of class EXCEL7
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.458) - Dummy-2 (2196):
treating element as native due to windowHandle hwnd 0X10097A of class EXCEL7. 
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.458) - Dummy-2 (2196):
Got previously cached nearest windowHandle of hwnd 0X10097A of class EXCEL7 for element A1 Element with automationID A1, className XLSpreadsheetCell and frameworkID [None]
DEBUG - UIAHandler.UIAHandler.IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent (16:21:11.460) - Dummy-2 (2196):
Created object <NVDAObjects.UIA.excel.ExcelCell object at 0x05DA7B70> for element A1 Element with automationID A1, className XLSpreadsheetCell and frameworkID [None]
DEBUG - UIAHandler.UIAHandler.IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent (16:21:11.460) - Dummy-2 (2196):
handleFocusChangedEvent: Queuing NVDA gainFocus event for obj <NVDAObjects.UIA.excel.ExcelCell object at 0x05DA7B70> 
DEBUG - NVDAObjects.UIA.UIA.__init__ (16:21:11.464) - MainThread (21548):
No windowHandle for UIA NvDAObject. Searching UIA element ancestry for nearest windowHandle
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.465) - MainThread (21548):
Locating nearest ancestor windowHandle for element Blatt "Tabelle1" Bereich with automationID Tabelle1, className [None] and frameworkID [None]
DEBUGWARNING - UIAHandler.func (16:21:11.465) - UIAHandler.UIAHandler.MTAThread (1768):
Not registering for textChange events from UIA element with class name 'XLSpreadsheetCell' and automation ID 'A1'
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.467) - MainThread (21548):
Found ancestor element with valid windowHandle hwnd 0X10097A of class EXCEL7
DEBUG - NVDAObjects.UIA.UIA.__init__ (16:21:11.473) - MainThread (21548):
No windowHandle for UIA NvDAObject. Searching UIA element ancestry for nearest windowHandle
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.473) - MainThread (21548):
Locating nearest ancestor windowHandle for element Datenblatt Datenraster with automationID Grid, className XLSpreadsheetGrid and frameworkID [None]
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.474) - MainThread (21548):
Found ancestor element with valid windowHandle hwnd 0X10097A of class EXCEL7
IO - speech.speech.speak (16:21:11.474) - MainThread (21548):
Speaking ['ausgewählt', 'A1  bis A27 ', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (16:21:11.490) - winInputHook (34388):
Input: kb(laptop):shift+downArrow
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.500) - Dummy-2 (2196):
handlePropertyChangeEvent called with property RangeValuePattern.Value, value 24.0 for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.500) - Dummy-2 (2196):
checking if is native UIA  element: [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.500) - Dummy-2 (2196):
Locating nearest ancestor windowHandle for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.506) - Dummy-2 (2196):
Found ancestor element with valid windowHandle hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.isUIAWindow (16:21:11.506) - Dummy-2 (2196):
Found cached is UIA window True for hwnd hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.506) - Dummy-2 (2196):
treating element as native due to windowHandle hwnd 0X100450 of class NetUIHWND. 
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.507) - Dummy-2 (2196):
Got previously cached nearest windowHandle of hwnd 0X100450 of class NetUIHWND for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.507) - Dummy-2 (2196):
Checking if should accept NVDA event valueChange with window hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.510) - Dummy-2 (2196):
handlePropertyChangeEvent: created object <NVDAObjects.UIA.UIA object at 0x05EA5D30> 
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.510) - Dummy-2 (2196):
handlePropertyChangeEvent: queuing NVDA valueChange event for NVDAObject <NVDAObjects.UIA.UIA object at 0x05EA5D30> 
IO - inputCore.InputManager.executeGesture (16:21:11.529) - winInputHook (34388):
Input: kb(laptop):shift+downArrow
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.539) - Dummy-2 (2196):
handlePropertyChangeEvent called with property RangeValuePattern.Value, value 48.0 for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.539) - Dummy-2 (2196):
checking if is native UIA  element: [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.539) - Dummy-2 (2196):
Locating nearest ancestor windowHandle for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.540) - Dummy-2 (2196):
Found ancestor element with valid windowHandle hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.isUIAWindow (16:21:11.541) - Dummy-2 (2196):
Found cached is UIA window True for hwnd hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.541) - Dummy-2 (2196):
treating element as native due to windowHandle hwnd 0X100450 of class NetUIHWND. 
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.541) - Dummy-2 (2196):
Got previously cached nearest windowHandle of hwnd 0X100450 of class NetUIHWND for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.541) - Dummy-2 (2196):
Checking if should accept NVDA event valueChange with window hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.544) - Dummy-2 (2196):
handlePropertyChangeEvent: created object <NVDAObjects.UIA.UIA object at 0x05ECE6F0> 
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.544) - Dummy-2 (2196):
handlePropertyChangeEvent: queuing NVDA valueChange event for NVDAObject <NVDAObjects.UIA.UIA object at 0x05ECE6F0> 
IO - inputCore.InputManager.executeGesture (16:21:11.549) - winInputHook (34388):
Input: kb(laptop):shift+downArrow
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.556) - Dummy-2 (2196):
handlePropertyChangeEvent called with property RangeValuePattern.Value, value 72.0 for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.556) - Dummy-2 (2196):
checking if is native UIA  element: [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.556) - Dummy-2 (2196):
Locating nearest ancestor windowHandle for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.559) - Dummy-2 (2196):
Found ancestor element with valid windowHandle hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.isUIAWindow (16:21:11.559) - Dummy-2 (2196):
Found cached is UIA window True for hwnd hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.isNativeUIAElement (16:21:11.559) - Dummy-2 (2196):
treating element as native due to windowHandle hwnd 0X100450 of class NetUIHWND. 
DEBUG - UIAHandler.UIAHandler.getNearestWindowHandle (16:21:11.560) - Dummy-2 (2196):
Got previously cached nearest windowHandle of hwnd 0X100450 of class NetUIHWND for element [None] Scrollleiste with automationID [None], className NetUIScrollBar and frameworkID Win32
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.560) - Dummy-2 (2196):
Checking if should accept NVDA event valueChange with window hwnd 0X100450 of class NetUIHWND
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.562) - Dummy-2 (2196):
handlePropertyChangeEvent: created object <NVDAObjects.UIA.UIA object at 0x06F8B970> 
DEBUG - UIAHandler.UIAHandler.IUIAutomationPropertyChangedEventHandler_HandlePropertyChangedEvent (16:21:11.562) - Dummy-2 (2196):
handlePropertyChangeEvent: queuing NVDA valueChange event for NVDAObject <NVDAObjects.UIA.UIA object at 0x06F8B970> 
IO - inputCore.InputManager.executeGesture (16:21:11.589) - winInputHook (34388):
Input: kb(laptop):shift+downArrow
```

And this is the developer info:

```
INFO - globalCommands.script_navigatorObject_devInfo (16:22:16.711) - MainThread (21548):
Developer info for navigator object:
name: ''
role: TABLECELL
processID: 32604
roleText: None
states: exception: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
isFocusable: exception: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
hasFocus: False
Python object: <NVDAObjects.UIA.excel.ExcelCell object at 0x05DA7B70>
Python class mro: (<class 'NVDAObjects.UIA.excel.ExcelCell'>, <class 'NVDAObjects.UIA.excel.ExcelObject'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: exception: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
location: None
value: None
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
appModule: AppModule(excel, appName='excel', processID=32604)
appModule.productName: 'Microsoft Office'
appModule.productVersion: '16.0.18129.20158'
appModule.helperLocalBindingHandle: c_long(128939128)
appModule.appArchitecture: 'AMD64'
windowHandle: 1051002
windowClassName: 'EXCEL7'
windowControlID: 0
windowStyle: 1460338688
extendedWindowStyle: 0
windowThreadID: 9064
windowText: 'Mappe1'
displayText: exception: cannot unpack non-iterable NoneType object
UIAElement: <POINTER(IUIAutomationElement) ptr=0x76fd9e0 at 691f350>
UIA automationID: Exception: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
UIA frameworkID: 
UIA runtimeID: (42, 1051002, 4, 1005)
UIA providerDescription: [pid:32604,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:mso.dll)]
UIA className: Exception: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
UIA patterns available: 
```

**Comment by Adriani90** [comment]
Narator works as expected in this case. @michaelDCurran, @gerald-hartig is this then an NVDA issue? Or should we contact Microsoft?

**Comment by seanbudd** [comment]
@Adriani90 - this needs to be reported to Microsoft

**Comment by Adriani90** [comment]
I need some technical details Sean, otherwise it‘s hard to argue against Microsoft when Narator works as expected.

**Comment by seanbudd** [comment]
@Adriani90 - you don't need to argue with them about technical details, please leave it up to their team to investigate. Microsoft should be able to handle reports from users, not developers

**Comment by Adriani90** [comment]
It‘s so easy to say this, but unfortunately the reality is different. If Narator works as expected, I always get the answer „NVDA devs should investigate first“. It‘s annoying really, but that‘s what we have to accept I guess. Issues are down prioritized alot, if NVDA is the only screen reader having this problem. So at least with some technical details, I can try to argue on another eye level.Von meinem iPhone gesendetAm 20.11.2025 um 06:45 schrieb Sean Budd ***@***.***>:﻿seanbudd left a comment (nvaccess/nvda#14230)
@Adriani90 - you don't need to argue with them about technical details, please leave it up to their team to investigate. Microsoft should be able to handle reports from users, not developers
