### ISSUE TITLE
Can't move to or activate buttons in Excel

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14255]
### Steps to reproduce:

1) Open Excel to a sheet with a button on it which launches a macro.  Note that with the developer ribbon enabled, you can press alt, L, i, b to insert a button but it relies on the mouse to size it (similar to the previous problem with shapes), so I'm not including the full steps to create such a button here.  I have reported that to Microsoft.

2) Press NVDA+F7 to open the elements list.
3) Press alt+f to select form fields
4) Select the button
5) Try to activate the button
6) Press alt+m to move to the button.

### Actual behavior:

At step 5, the "Activate" button is disabled so the button cannot be activated.

At step 6, moving to the button, does not move the focus to the button itself, but to the cell nearest the top-left of the button.

### Expected behavior:

At step 5, you should be able to "Activate" the button.

At step 6, moving to the button should move the focus to the button itself.

#### NVDA version:

NVDA 2022.4 Beta 1

#### Windows version:

Windows 11 (64-bit) Version: 22H2, Build: 22621.674 

#### Name and version of other software in use when reproducing the issue:

Office 365 (64-bit) Version: 16.0.15629.20204 

#### Does the issue still occur after restarting your computer?

I tried with UIA enabled for Excel in NVDA's advanced settings, however the elements list does not work (issue #14083) and neither does trying to change between focus and browse modes (issue #12881).

#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons

**Comment by Adriani90** [comment]
@Qchristensen I guess the issue is still occuring even in NVDA last alpha with last Office 365 update right?
Could you please attach a test sample to this issue?

**Comment by Qchristensen** [comment]
I just tested here - initially with NVDA 2026.2 Beta 10 - which is where I got the log below - but I also tested with the latest alpha - nvda_snapshot_alpha-57376,e2c58a1b.exe - with the same observable results, so my guess is the log would likely be the same.

When going to the button in the elements list, the "Activate" button is visible, but greyed out.  Moving to the button also only moves focus to a cell near the button (the cell the top-left of the button is over?) but I can't activate the button, and trying to activate the context menu gives an error.  Log of pressing alt+m in the elements list to move to the button and then opening the context menu below.  I've also attached the same spreadsheet I created with one button, which activates the URL in cell A1.

[button test.xlsm](https://github.com/user-attachments/files/30967873/button.test.xlsm)

IO - inputCore.InputManager.executeGesture (15:11:21.340) - winInputHook (32128):
Input: kb(desktop):alt+m
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (15:11:21.458) - MainThread (33160):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 658242 (EXCEL7), objectID 7554, childID 0, process 24912 (excel), thread 12572
IO - speech.speech.speak (15:11:21.479) - MainThread (33160):
Speaking [LangChangeCommand ('en_GB'), 'Book2 - Excel', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (15:11:21.527) - MainThread (33160):
Could not locate dropdown list in previous objects
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (15:11:21.612) - MainThread (33160):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_VALUECHANGE, window 658242 (EXCEL7), objectID 7555, childID 0, process 24912 (excel), thread 12572
IO - speech.speech.speak (15:11:21.669) - MainThread (33160):
Speaking [LangChangeCommand ('en_GB'), 'Sheet1', 'table', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:11:21.776) - MainThread (33160):
Speaking [LangChangeCommand ('en_GB'), 'H7', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:11:21.917) - MainThread (33160):
Speaking [LangChangeCommand ('en_GB'), 'Button 1 H7-I8', 'button', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (15:11:22.877) - winInputHook (32128):
Input: kb(desktop):applications
ERROR - scriptHandler.executeScript (15:11:22.880) - MainThread (33160):
error executing script: <bound method BrowseModeTreeInterceptor.script_passThrough of <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x00000190815E9550>> with gesture 'applications'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "browseMode.pyc", line 758, in script_passThrough
  File "browseMode.pyc", line 744, in _focusLastFocusableObject
  File "baseObject.pyc", line 39, in __get__
  File "browseMode.pyc", line 317, in _get_currentFocusableNVDAObject
AttributeError: 'ExcelBrowseModeTreeInterceptor' object has no attribute 'makeTextInfo'
IO - inputCore.InputManager.executeGesture (15:11:24.941) - winInputHook (32128):
Input: kb(desktop):NVDA+f1
DEBUG - gui.contextHelp.bindHelpEvent (15:11:24.989) - MainThread (33160):
Did context help binding for LogViewer
INFO - globalCommands.script_navigatorObject_devInfo (15:11:25.198) - MainThread (33160):
Developer info for navigator object:
name: 'Button 1 H7-I8'
role: BUTTON
processID: 24912
roleText: None
states: FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.window.excel.ExcelFormControl object at 0x00000190815CBE10>
Python class mro: (<class 'NVDAObjects.window.excel.ExcelFormControl'>, <class 'NVDAObjects.window.excel.ExcelBase'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=0, top=484, width=2560, height=799)
value: ''
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
appModule: AppModule(excel, appName='excel', processID=24912)
appModule.productName: 'Microsoft Office'
appModule.productVersion: '16.0.20228.20158'
appModule.helperLocalBindingHandle: c_void_p(1720904045600)
appModule.appArchitecture: 'AMD64'
windowHandle: 658242
windowClassName: 'EXCEL7'
windowControlID: 0
windowStyle: 1460338688
extendedWindowStyle: 0
windowThreadID: 12572
windowText: 'Book2'
displayText: ''

**Comment by Qchristensen** [comment]
In testing that, I also looked at the elements list on the web.  On this page, for instance, there are a few buttons like comment and unsubscribe - if I look at the form fields list in the elements list, I can see those buttons, and the dialog HAS an "Activate" button, but it is greyed out, even with one of those buttons selected.  If I go to the "buttons" list with alt+b, the activate button is available (there is no list of "buttons" in the elements list in Excel though).  Am I missing something, or is the issue perhaps that the "Activate" button doesn't actually work with form fields in the elements list?  (As well as moving to buttons not working in Excel)
