### ISSUE TITLE
Will NVDA 2023.1 have to reset the user's default configuration?

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14412]
When I upgraded from nvda2022.4Beta3 to alpha-27213, I encountered a warning about a bad configuration file.
### Steps to reproduce:
Upgrade NVDA from older version to alpha-27213,

### Actual behavior:
I got a warning that my configuration is wrong and my configuration has been reset.
The specific error configuration is 'reportLineIndentation'.

### Expected behavior:
We should have a solution that has the least impact on users.
Also, even if the configuration file is wrong, please help the user to keep the log containing the error instead of directly resetting to the default value.
### NVDA logs, crash dumps and other attachments:
ERROR - config.ConfigManager._initBaseConf (12:19:28.720) - MainThread (3500):
Error loading base configuration
Traceback (most recent call last):
  File "config\__init__.pyc", line 565, in _initBaseConf
  File "config\__init__.pyc", line 599, in _loadConfig
  File "config\__init__.pyc", line 595, in _loadConfig
  File "config\profileUpgrader.pyc", line 25, in upgrade
  File "config\profileUpgrader.pyc", line 66, in _doValidation
ValueError: Unable to validate config file after upgrade: Key reportLineIndentation : the value "False" is of the wrong type.
Full result: (value of false means the key was not present)
[(['documentFormatting'], 'reportLineIndentation', VdtTypeError('the value "False" is of the wrong type.'))]

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-27213 
#### Windows version:
Windows 10 22H2 (x64) build 19045.2251
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
n/a
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a
#### If NVDA add-ons are disabled, is your problem still occurring?
n/a
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

**Comment by CyrilleB79** [comment]
@cary-rowen, this is clearly not intended.

At the very worst, the configuration of a profile may be modified by the upgrade only for the items affected by this update. But in any case, the config should not have been globally reinitialized.

* By chance, would you be able to provide the full log at DEBUG level?
  Note: when reporting issues, it's always better to provide the full log if possible rather than an extract.
* Are you using profiles
* Is the config being reinitialized the default config or the config of a profile?
* If you can reproduce the issue, would you be able to provide the previous config (nvda.ini + .ini in the profile folder) used with NVDA 2022.4beta3
* You do not specify if you have done the upgrade with add-ons disabled; more generally, some fields of the report are filled with "N/A" whereas they are applicable to this issue. Can you update it please?

I will try to have a look at this issue. But if you can provide the requested information, this would help. Thanks.

**Comment by cary-rowen** [comment]
@CyrilleB79 
I updated the original comment.
But I don't think the error has anything to do with the add-on.
The configuration key where the error occurred was "reportLineIndentation"
Accepted values ​​are False or True in 2022.4 and 0 or 1 in 2023.1

**Comment by CyrilleB79** [comment]
@cary-rowen, I think that I have identified the reason why the issue occurred.

The config file you were using before the upgrade was actually already an upgraded configuration (schemaVersion = 9). Probably, you have switched NVDA version back and forth between 2022.4beta3 and alpha with the same configuration folder, e.g. using the -c command line option with a portable NVDA or downgrading NVDA.

Downgrading NVDA is not supported and it is strongly recommended not to do so. However, that true that there are two use cases where this recommendation is not shown to the user:
* using an older NVDA with a config generated with a newer NVDA due to the usage of the -c parameter
* Completely uninstalling NVDA and then reinstalling an older NVDA, e.g. uninstall last alpha and then install 2022.4beta3

Could you confirm that you have executed one of these scenarios?

**Comment by cary-rowen** [comment]
< Unfortunately, the log is not at debug level. Would you be able to take another log at DEBUG level.
I can keep providing that log if you still want it.

< Are you using profiles
I am not using profile

< • Is the config being reinitialized the default config or the config of a profile?
This is the default config.
< Probably, you have switched NVDA version back and forth between 2022.4beta3 and alpha with the same configuration folder.
Yes, I can confirm this, in order to test the functionality of Alpha and 2022.4, I switched between the two versions.

**Comment by cary-rowen** [comment]
BTW, Even if downgrades are not supported, even in the worst case, the original configuration should be preserved for the user.

**Comment by CyrilleB79** [comment]
> BTW, Even if downgrades are not supported, even in the worst case, the original configuration should be preserved for the user.

I agree that reinitializing the config without the approval of the user and without any advise should not be an acceptable UX.

**Comment by CyrilleB79** [comment]
PS: No need to provide the log at level DEBUG anymore since the issue is identified.

**Comment by Brian1Gaff** [comment]
What I would do is have a new instance in a different folder myself,
 You can downdate as long as you make sure of the fact that the configs are 
removed of course.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by seanbudd** [comment]
>BTW, Even if downgrades are not supported, even in the worst case, the original configuration should be preserved for the user.

Agreed, downgrading will still not be supported. But we can improve this to reduce friction when downgrading.

>I agree that reinitializing the config without the approval of the user and without any advise should not be an acceptable UX.

A separate issue, a feature request, should be written up for this problem.
Where possible, invalid keys should be reset to the default, rather than resetting the whole config.
When upgrading the config, backups should be should kept for each schema version (e.g. just before upgrading, and just after upgrading).
This will allow for better downgrading and upgrading.

**Comment by cary-rowen** [comment]
If someone opens a new Feture Request as a clearer statement of this problem, I agree to close this.
Moreover, this issue may become more urgent as 2023.1 approaches.
It's probably not uncommon for this problem, as I've encountered.
