### ISSUE TITLE
NVDA crash with PowerPoint when an obscured form is focused

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#14445]
### Actual behavior:

A user informed me that my add-on was causing NVDA 2022.3.2 to crash when using PowerPoint (office 2021).
The provided NVDA log says:
  File "appModules\powerpnt.pyc", line 742, in _get_ppShapeType
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 87, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 161, in __getattr__
  File "comtypes\client\lazybind.pyc", line 123, in __bind
RecursionError: maximum recursion depth exceeded in comparison
After analysis, I found that it was the use of the obj.states statement placed in the "chooseNVDAObjectOverlayClasses" method that caused this infinite loop when the focus arrived on an obscured shape.
To reproduce the problem:
- use a portable copy of NVDA and enable loading custom code from developer Scratchpad directory.
- copy powerpnt.py file of NVDA source appModules directory to Scratchpad appModules directory.
- modify this file by adding just after the definition of the "chooseNVDAObjectOverlayClasses" method, the instruction:
state = obj. states
- restart NVDA and launch powerpoint
- start a new presentation
- in the slide view slide pane, select the single slide of the presentation and insert a text frame.
- type "tab" to focus on an obscured shape.
- the error occurs and NVDA freezes.

Test with MS Office 2019
### Expected behavior:

No NVDA crash when an add-on use obj.states instruction in chooseNVDAObjectOverlayClass method
#### NVDA installed/portable/running from source:
Installed and portable
#### NVDA version:
2022.3.2 and above
#### Windows version:
Windows 10 21h2 
#### Name and version of other software in use when reproducing the issue:
MS Office 2019 and 2021
#### Does the issue still occur after restarting your computer?
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by seanbudd** [comment]
Have you seen this issue without an add-on being involved? Can you provide a sample add-on and full nvda.log?

**Comment by paulber19** [comment]
The problem can only occur if some globalPlugin needs to test the state 
of an object in the "chooseNVDAObjectsOverlayClass" method using 
obj.states and the focus lands on an obscured shape of a slide in a 
presentation from PowrPoint..
A safe way to produce the problem is:
1- Enable loading custom code from Developer Scratchpad directory
2- create a "myTest.py" file with these lines:
from globalPluginHandler import GlobalPlugin

class GlobalPlugin (GlobalPlugin):
def chooseNVDAObjectOverlayClasses(self, obj, clsList):
super(GlobalPlugin, self).chooseNVDAObjectOverlayClasses(obj, clsList)
states = obj. states

3 Save this file to the scratchpad\globalPlugins folder.
4 restart NVDA
5- in PowerPoint, bring focus to an obscured shape.
- NVDA stops talking and freezes.

Here is the resulting log:
INFO - __main__ (09:41:03.065) - MainThread (2088):
Starting NVDA version alpha-27352,d36588ad
INFO - core.main (09:41:03.159) - MainThread (2088):
Config dir: F:\documents\Paulo\temp\nvda alpha sans add-on\userConfig
INFO - config.ConfigManager._loadConfig (09:41:03.174) - MainThread (2088):
Loading config: F:\documents\Paulo\temp\nvda alpha sans 
add-on\userConfig\nvda.ini
INFO - core.main (09:41:03.221) - MainThread (2088):
Developer Scratchpad mode enabled
INFO - core.main (09:41:03.311) - MainThread (2088):
Windows version: Windows 10 22H2 (10.0.19045) workstation AMD64
INFO - core.main (09:41:03.311) - MainThread (2088):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 
18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (09:41:03.311) - MainThread (2088):
Using comtypes version 1.1.11
INFO - core.main (09:41:03.311) - MainThread (2088):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - NVDAHelperLocal (09:41:03.831) - MainThread (2088):
Thread 2088, build\x86\localWin10\oneCoreSpeech.cpp, 
ocSpeech_initialize, 215:
ocSpeech_initialize

INFO - NVDAHelperLocal (09:41:03.836) - MainThread (2088):
Thread 2088, build\x86\localWin10\oneCoreSpeech.cpp, 
OcSpeechState::activate, 89:
Activating

INFO - NVDAHelperLocal (09:41:03.967) - MainThread (2088):
Thread 2088, build\x86\localWin10\oneCoreSpeech.cpp, 
preventEndUtteranceSilence_, 443:
AppendedSilence supported

INFO - synthDriverHandler.setSynth (09:41:04.011) - MainThread (2088):
Loaded synthDriver oneCore
WARNING - mathPres.initialize (09:41:04.041) - MainThread (2088):
MathPlayer 4 not available
INFO - core.main (09:41:04.041) - MainThread (2088):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (09:41:04.046) - MainThread (2088):
Braille input initialized
INFO - braille.initialize (09:41:04.046) - MainThread (2088):
Using liblouis version 3.23.0
INFO - braille.initialize (09:41:04.047) - MainThread (2088):
Using pySerial version 3.5
INFO - braille.BrailleHandler.setDisplayByName (09:41:04.061) - 
MainThread (2088):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (09:41:04.546) - MainThread (2088):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (09:41:04.749) - 
UIAHandler.UIAHandler.MTAThread (5968):
UIAutomation: IUIAutomation6
INFO - core.main (09:41:04.949) - MainThread (2088):
NVDA initialized
ERROR - NVDAObjects.__call__ (09:41:13.046) - MainThread (2088):
Exception in chooseNVDAObjectOverlayClasses for <globalPlugins.myTest - 
Copie.GlobalPlugin object at 0x08D21D90>
Traceback (most recent call last):
   File "NVDAObjects\__init__.pyc", line 111, in __call__
   File "F:\documents\Paulo\temp\nvda alpha sans 
add-on\userConfig\scratchpad\globalPlugins\myTest - Copie.py", line 8, 
in chooseNVDAObjectOverlayClasses
     states = obj.states
   File "baseObject.pyc", line 62, in __get__
   File "baseObject.pyc", line 168, in _getPropertyViaCache
   File "appModules\powerpnt.pyc", line 807, in _get_states
   File "baseObject.pyc", line 62, in __get__
   File "baseObject.pyc", line 168, in _getPropertyViaCache
   File "appModules\powerpnt.pyc", line 557, in _get__overlapInfo
   File "NVDAObjects\__init__.pyc", line 86, in __call__
   File "appModules\powerpnt.pyc", line 527, in __init__
   File "baseObject.pyc", line 62, in __get__
   File "baseObject.pyc", line 168, in _getPropertyViaCache
   File "appModules\powerpnt.pyc", line 781, in _get_role
   File "baseObject.pyc", line 62, in __get__
   File "baseObject.pyc", line 168, in _getPropertyViaCache
   File "appModules\powerpnt.pyc", line 742, in _get_ppShapeType
   File "monkeyPatches\comtypesMonkeyPatches.pyc", line 87, in 
new__getattr__
   File "comtypes\client\lazybind.pyc", line 168, in __getattr__
   File "comtypes\automation.pyc", line 746, in _invoke
   File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
ctypes.ArgumentError: argument 6: <class 'RecursionError'>: maximum 
recursion depth exceeded in __instancecheck__

**Comment by CyrilleB79** [comment]
@seanbudd, the information you've requested have been provided. Could you remove the blocked/needs-sample label or ask for further details if needed?

**Comment by paulber19** [comment]
Hi,
Still no response and yet it is a P1 qualified priority
Best regards.
Paul.

**Comment by ABuffEr** [comment]
Hi,
while a response would be welcome, I had a similar issue in the past, but forgot who explained me (someone of NVAccess, I think), and I'm afraid it's apply here. The problem is generally caused by the fact the object (read: NVDA object) is not - and cannot be - completely built at this stage, and trying to access to some properties brings to one or more calls on other objects (parent/children), that call chooseNVDAObjectOverlayClasses at their time... and so on, resulting in a recursion error.
The common solution is to move the states check into the new class inserted in clsList, or (a little more complex) make the check on IAccessible/UIA object behind NVDA obj.

**Comment by seanbudd** [comment]
Considering this is a bug with add-on code, rather than core NVDA, I've lowered the priority.

**Comment by Adriani90** [comment]
@paulber19, @ABuffEr is this still an issue in NVDA 2025.1 Beta?
Can this be solved at all? or is the workaround explained in https://github.com/nvaccess/nvda/issues/14445#issuecomment-1416804145
enough to consider closing this issue?

**Comment by paulber19** [comment]
Yes, it is always reproducible with NVDA 2025.1 Beta5.
I did not test the bypass proposals. No time.
And even if it is possible to contain it, I still think that it should 
be corrected Because it can waste a lot of time with an Add-on developer 
who does not know the problem.

**Comment by seanbudd** [comment]
Can you test the latest alpha builds and see if this is fixed with 64bit NVDA? Note you must fully uninstall 64bit NVDA first if switching back to 32bit.
