### ISSUE TITLE
Restarting NVDA in the VS Code editor gives an error

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14492]
### Steps to reproduce:
1. Open any file in VS Code.
2. Keep the focus in the editable Text Area.
3. nvda+q Select "Restart" in the pop-up dialog.
### Actual behavior:
nvda logs error after restart.
### Expected behavior:
no error.
### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/10322978/log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
* Latest Alpha version
* Build of #14484
#### Windows version:
Windows 10 22H2 (x64) build 19045.2364
#### Name and version of other software in use when reproducing the issue:
VS Code 1.74.2
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Relevant error snippet
```py
ERROR - eventHandler.executeEvent (11:14:04.509) - MainThread (22300):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x067CBA90> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\behaviors.pyc", line 296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1244, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1095, in reportFocus
  File "speech\speech.pyc", line 627, in speakObject
  File "speech\speech.pyc", line 681, in getObjectSpeech
  File "documentBase.pyc", line 74, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 110, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 235, in _findContentDescendant
LookupError: Object has no text descendants
```

**Comment by Adriani90** [comment]
@cary-rowen are you still having this issue in NVDA 2024.4.1?

**Comment by cary-rowen** [comment]
Yes, this can still be reproduced

**Comment by Adriani90** [comment]
@cary-rowen is this still an issue with NVDA 64 bit alpha?

**Comment by cary-rowen** [comment]
cc @Adriani90   

1. Everyone is welcome to test before asking for an update. If you have done so and cannot reproduce the issue, please attach your test results and then ask if others can reproduce it.
2. NVDA 2026.1 is currently in the development stage, and there is no indication that it is stable enough. While your suggestion to seek a new version is not wrong, I believe the current timing is not appropriate. I've noticed you've posted the same comment across multiple issues, and it's starting to sound like noise.
3. If you believe a specific commit or Pull Request (PR) could potentially help resolve a Bug, please mention them together. This would allow for more targeted testing.
4. Finally, I urge you not to arbitrarily close issues. NV Access does not appear to have any current policy regarding closing backlog issues, and your repeated requests for updates have made me feel pressured, compelling me to respond immediately.

## test result:

**It can still be reproduced.**

* Windows 10 22H2 (AMD64) build 19045.6456
* NVDA alpha-53327,2274e980 (2026.1.0.53327)

Visual Studio Code:

Version: 1.105.1 (user setup)
Commit: 7d842fb85a0275a4a8e4d7e040d2625abbf7f084
Date: 2025-10-14T22:33:36.618Z
Electron: 37.6.0
ElectronBuildId: 12502201
Chromium: 138.0.7204.251
Node.js: 22.19.0
V8: 13.8.258.32-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by seanbudd** [comment]
Hi @cary-rowen,

I appreciate your testing here and agree that it is more helpful to test issues first where possible before asking other community members to test.
Please don't feel obliged to respond to issues under a certain timeframe.
While we do close bugs that can't be reproduced, we can always reopen them if they get closed incorrectly.
I agree that we should not be closing issues unless we need information from the reporter still, and it appears we will never get that information. Triaged issues are usually reproducible confirmed issues, and so testing can usually be done by the community. There are exceptions to this of course, like issues with closed source software.
