### ISSUE TITLE
NVDA automagically changes Espeak variant in some situations

### ISSUE THREAD

**Issue by PeterLecky** [nvaccess/nvda#14670]
I sometimes experience automagical changes of espeak variant when rapidly typing or moving with the keyboard. The following bizzare steps to reproduce causes it on my and other friends notebooks so let's hope that it will help you to track it and fix. It is necessary to try on the web page, it does not occur in standard edits or in word.

### Steps to reproduce:
Set espeak as tts in nvda and use variant other than default (i usually use michael)
Configure nvda to use pitch change when announcing capital letters (set settings>speech>Capital pitch change percentage e.g. to 100%)
Open this page (tested in brave and firefox): http://jelenovipivonelej.info/a.html and position cursor to first letter (capital D)
Press left and right arrow simultaneously

### Actual behavior:
Espeak variant changes to default and returns back to michael after some arrowing or what ever.

### Expected behavior:
Nothing interesting happens :)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2022.4
#### Windows version:
windows 10
#### Name and version of other software in use when reproducing the issue:
Latest nightly of firefox and also tested in latest stable brave browser.
#### Does the issue still occur after restarting your computer?
Yeah

**Comment by XLTechie** [comment]
In Speech settings, try turning off the following settings:

Automatic language switching (when supported)

and:

Automatic dialect switching (when supported)

I suspect that one of those things is happening here, and eSpeak doesn't support 
the language/dialect using the voice you've chosen.

**Comment by PeterLecky** [comment]
I allready played with both these settings and problem appears also when 
are both disabled.
Thanks

**Comment by Adriani90** [comment]
@PeterLecky are you still having this issue in NVDA 2024.4.1?

**Comment by PeterLecky** [comment]
I actually have 2024.4.1rc1 (which is the same as stable as usual) and 
yes, it unfortunately still crashes.

**Comment by PeterLecky** [comment]
Sorry for prev message, it was not about crashes.
No, i canot reproduce it in same way as when i reported it but it 
happens in other situations.
E.g. i am using  shortcut shift+d to open list of drives in total 
commander, so i press shift+d and then immediately lovercase d to go to 
drive d. And it usually happens.
On the other side, it newer happens when i rapidly type D and than d in 
notepad so it somehow occurs when some window opens after press of 
capital letter immediately followed by lover case letter.

**Comment by PeterLecky** [comment]
Sure, it does not look like there is some usefull:
Speaking ['$Recycle.Bin; Size: <DIR>; Date: 01.02.2023 17:20; 
Attributes: --hs  1 of 17']
IO - inputCore.executeGesture (06:55:48.269) - winInputHook (12864):
Input: kb(laptop):shift+d
IO - inputCore.executeGesture (06:55:48.410) - winInputHook (12864):
Input: kb(laptop):d
IO - speech.speech.speak (06:55:48.574) - MainThread (10692):
Speaking [PitchCommand(offset=30), CharacterModeCommand(True), 'D', 
PitchCommand(), EndUtteranceCommand()]
IO - speech.speech.speak (06:55:48.594) - MainThread (10692):
Speaking ['combo box', '[-d-]', 'collapsed', CancellableSpeech (still 
valid)]
IO - speech.speech.speak (06:55:48.594) - MainThread (10692):
Speaking [CharacterModeCommand(True), 'd', EndUtteranceCommand()]
IO - speech.speech.speak (06:55:48.618) - MainThread (10692):
Speaking ['LEFT ', 'list', CancellableSpeech (still valid)]
IO - speech.speech.speak (06:55:48.626) - MainThread (10692):
Speaking ['..; Size: <DIR>; Date: 27.02.2025 13:54; Attributes: ----  0 
of 11']
DEBUGWARNING - 
NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget 
(06:55:48.626) - MainThread (10692):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations 
(06:55:48.627) - MainThread (10692):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget 
(06:55:48.627) - MainThread (10692):
Unable to fetch _IA2Relations
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 1863, in 
_getIA2RelationFirstTarget
   File "baseObject.pyc", line 59, in __get__
   File "baseObject.pyc", line 167, in _getPropertyViaCache
   File "NVDAObjects\IAccessible\__init__.pyc", line 1780, in 
_get__IA2Relations
NotImplementedError

**Comment by seanbudd** [comment]
Could you please upload a full log file as a file, rather than posting a snippet

**Comment by SaschaCowley** [comment]
Possible duplicate of #10214

**Comment by PeterLecky** [comment]
[nvda-old.log](https://github.com/user-attachments/files/19023139/nvda-old.log)

**Comment by Adriani90** [comment]
cc: @alex19EP could you also look into this? I think it might be related to the one with pitch change as well.
