### ISSUE TITLE
Many "couldn't find lock screen" errors.

### ISSUE THREAD

**Issue by ajirving** [nvaccess/nvda#14695]
### Steps to reproduce:
View log after computer has been locked.  The bad behavior only occurs sometimes and I'm not sure what the precise trigger is.
### Actual behavior:
Increased CPU usage while computer is locked (although I can't be sure this is due to NVDA).  After unlocking the NVDA log has many lines of errors like 
```
ERROR - utils.security._isObjectBelowLockScreenCheckZOrder (10:09:17.663) - MainThread (13796):
Couldn't find lock screen
Traceback (most recent call last):
  File "utils\security.pyc", line 255, in _isObjectBelowLockScreenCheckZOrder
  File "utils\security.pyc", line 315, in _isWindowBelowWindowMatchesCond
utils.security._UnexpectedWindowCountError: Windows found
 - window 1 indexes: [0] (expects len 1)
 - window 2 index: None

ERROR - utils.security._isObjectBelowLockScreenCheckZOrder (10:09:17.667) - MainThread (13796):
Couldn't find lock screen
Traceback (most recent call last):
  File "utils\security.pyc", line 255, in _isObjectBelowLockScreenCheckZOrder
  File "utils\security.pyc", line 315, in _isWindowBelowWindowMatchesCond
utils.security._UnexpectedWindowCountError: Windows found
 - window 1 indexes: [] (expects len 1)
 - window 2 index: None
```

### Expected behavior:
No errors reported.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.4
#### Windows version:
Windows 11
#### Does the issue still occur after restarting your computer?
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Na/

**Comment by seanbudd** [comment]
Could you explain what the bad behaviour is? Is the issue just errors in the log?

**Comment by ajirving** [comment]
The only bad behaviour I'm certain of is the errors in the log, the extract I quoted is repeated many times with only a small difference between each timestamp (suggesting some sort of loop).   Surely this isn't desirable?

If I leave the computer locked for some time I notice a significant increase in CPU activity (the fan starts running continuously).  This goes back to normal when I unlock.  I'm not setup to record running process statistics while the computer is locked so I can't say that NVDA is definitely the culprit.  However the evidence that some sort of loop is running and spamming the log is surely suspicious.

**Comment by seanbudd** [comment]
We can't diagnose the problem without a full log. Feel free to email this to info@nvaccess.org if you have privacy concerns.

It may be worth lowering the log level of this log, but we need more information about why this is being logged.

**Comment by ajirving** [comment]
I can no longer reproduce this so happy to assume it's been fixed.
