### ISSUE TITLE
Touchscreen support: recursion error when moving around the screen in Windows 11 22H2

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#14753]
### Steps to reproduce:
Prerequisites: a touch capable computer running Windows 11 2022 Update, alpha build 27879 or later:

1. With alpha build 27868 installed, move around the screen using touch (just move one finger arond the screen).
2. Instal alpha build 27879 or later.
3. Move around the screen with one finger.

### Actual behavior:
NVDA does nothing or plays error tones when moving arond the scren with one finger.

### Expected behavior:
NVDA announces object under the finger.

### NVDA logs, crash dumps and other attachments:
ERROR - scriptHandler.executeScript (19:44:03.844) - MainThread (9136):
error executing script: <bound method GlobalCommands.script_touch_explore of <globalCommands.GlobalCommands object at 0x0788A030>> with gesture 'hover'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "globalCommands.pyc", line 3806, in script_touch_explore
  File "screenExplorer.pyc", line 36, in moveTo
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1736, in _get_presentationType
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 877, in _get_presentationType
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1699, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 984, in _getUIACacheablePropertyValue
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
  File "comtypes\automation.pyc", line 516, in __ctypes_from_outparam__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 146, in newVARIANT_value_fget
  File "comtypes\automation.pyc", line 468, in _get_value
  File "comtypes\safearray.pyc", line 247, in unpack
  File "comtypes\safearray.pyc", line 233, in _get_size
  File "comtypes\_safearray.pyc", line 105, in SafeArrayGetUBound
ctypes.ArgumentError: argument 1: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-27914,5182cd98

#### Windows version:
Windows 11 22H2 (build 22621.1413)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
Fresh Windows installation

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No issue in alpha build 27868 and earlier, introduced in 27879

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

Thanks.

**Comment by josephsl** [comment]
Hi,

Note that the traceback was recorded with alpha build 27879. Thanks.

**Comment by joey-commits** [comment]
This is still reproducible in build 28166. I found a way to reliably reproduce this.
Find the "Show Hidden Icons" item on the tray with your finger and move your finger slowly left. NVDA will crash at this point. I think this likely is caused by conflicts between nVDA and the new System Tray features recently introduced to Windows.

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by michaelDCurran** [comment]
Logging a full stack we get:
```
ERROR - scriptHandler.executeScript (20:37:51.892) - MainThread (1032):
error executing script: <bound method GlobalCommands.script_touch_explore of <globalCommands.GlobalCommands object at 0x07873CF0>> with gesture 'hover'
Stack trace:
  File "nvda.pyw", line 406, in <module>
  File "core.pyc", line 794, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "core.pyc", line 761, in Notify
  File "core.pyc", line 731, in request
  File "core.pyc", line 761, in Notify
... another 100 times or so of request / notify calls... 
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "inputCore.pyc", line 221, in executeScript
  File "scriptHandler.pyc", line 297, in executeScript
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "globalCommands.pyc", line 3849, in script_touch_explore
  File "screenExplorer.pyc", line 31, in moveTo
  File "NVDAObjects\__init__.pyc", line 322, in objectFromPoint
  File "NVDAObjects\__init__.pyc", line 99, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 482, in findOverlayClasses
  File "baseObject.pyc", line 41, in __get__
  File "NVDAObjects\IAccessible\__init__.pyc", line 908, in _get_role
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 920, in _get_IAccessibleStates
  File "comtypes\__init__.pyc", line 856, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
ctypes.ArgumentError: argument 1: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object
```
