### ISSUE TITLE
Mouse Tracking Not Reading QT Controls And Contents of Text Boxes

### ISSUE THREAD

**Issue by ironcross32** [nvaccess/nvda#14814]
### Steps to reproduce:
1. Turn on mouse tracking
2. Attempt to read the contents of edit boxes and buttons in QT apps, using OCR when necessary to jump the mouse directly to a control or piece of text
### Actual behavior:

Nothing is read.
### Expected behavior:

Contents of QT text boxes, as well as controls should be read when mouse tracking is on by moving the mouse to them, or routing it directly using OCR.
### NVDA logs, crash dumps and other attachments:
Not relevant, no error.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.1
#### Windows version:
Version	10.0.22621 Build 22621

#### Name and version of other software in use when reproducing the issue:
Mudlet 4.17
#### Other information about your system:
QT 5.14
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by michaelDCurran** [comment]
Related traceback when using mouse tracking in Teamtalk 5:
```
ERROR - eventHandler.executeEvent (11:44:11.618) - MainThread (5236):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x081027D0> with extra args of {'x': 1174, 'y': 631}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\__init__.pyc", line 1212, in event_mouseMove
  File "NVDAObjects\UIA\__init__.pyc", line 903, in expand
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
ValueError: NULL COM pointer access
```

**Comment by seanbudd** [comment]
This looks like an issue with QT but more investigation is needed

**Comment by Adriani90** [comment]
@ironcross32 is this also an issue in QT 6? Did you also try with QT 6.8?

**Comment by Adriani90** [comment]
No updates upon request since more than 2 years, and QT 5 reaches end of life next week:
https://endoflife.date/qt

I am closing as abandoned. If you are still having this issue in QT 6, please comment and we can reopen.
