### ISSUE TITLE
Add-on Store: Ctrl+Tab should either maintain original focus, or focus the add-ons list

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#14987]
### Steps to reproduce:

1. Open the add-on store.
2. Press `Ctrl+tab`.

### Actual behavior:

* At this point, the focus moves to "`panel  unknown  focused`".
* Pressing `leftArrow` or `upArrow`, acts as if focus was in the tab selector all along.
* Pressing `rightArrow` or `downArrow`, acts as if focus was in the channel selector all along.

### Expected behavior:

1. Ideally, focus would be returned to the add-ons list, as it is when the dialog is first opened, and the name of the list would be announced. This behavior would incidentally solve #14986.
2. Alternatively, focus could stay wherever it was when `Ctrl+Tab` was pressed.
3. Lastly, focus could instead move firmly into the tab selector. While I don't think that's what a user would anticipate happening, it would be better than this.

### NVDA logs, crash dumps and other attachments:

```
IO - inputCore.executeGesture (20:28:18.998) - winInputHook (15284):
Input: kb(desktop):control+tab
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM.setSelection (20:28:19.019) - MainThread (19020):
selected Item: None
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM.resetListItems (20:28:19.020) - getAddonData (15264):
resetting list items
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM._tryPersistSelection (20:28:19.021) - getAddonData (15264):
No entries in new order
DEBUG - gui._addonStoreGui.viewModels.store.AddonStoreVM._getAvailableAddonsInBG (20:28:19.021) - getAddonData (15264):
getting available addons in the background
DEBUG - gui._addonStoreGui.viewModels.store.AddonStoreVM._getAvailableAddonsInBG (20:28:19.021) - getAddonData (15264):
completed getting addons in the background
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM.resetListItems (20:28:19.029) - getAddonData (15264):
resetting list items
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM._tryPersistSelection (20:28:19.029) - getAddonData (15264):
No entries in new order
DEBUG - gui._addonStoreGui.viewModels.store.AddonStoreVM._getAvailableAddonsInBG (20:28:19.029) - getAddonData (15264):
completed refresh
IO - speech.speech.speak (20:28:19.063) - MainThread (19020):
Speaking ['tab control', CancellableSpeech (still valid)]
IO - speech.speech.speak (20:28:19.063) - MainThread (19020):
Speaking ['panel', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (20:28:19.063) - MainThread (19020):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (20:28:19.063) - MainThread (19020):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (20:28:19.063) - MainThread (19020):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1600, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1515, in _get__IA2Relations
NotImplementedError
```

### System configuration

NVDA portable, version alpha-28372,94715243
Microsoft® Windows® Operating System version 10.0.19041.2311

**Comment by seanbudd** [comment]
Closing in favour of discussion in https://github.com/nvaccess/nvda/issues/14986#issuecomment-1581747491
