### ISSUE TITLE
Regression: #15097 breaks playback of start-up sound

### ISSUE THREAD

**Issue by ultrasound1372** [nvaccess/nvda#15143]
### Steps to reproduce:
When running NVDA alpha-28675 (384a7428), which includes the WASAPI stop if idle checks by @jcsteh, restart NVDA by any means. This includes updates, restart from exit dialog, or exit and launch again.
### Actual behavior:
No start-up sound is heard. Occasionally instead a tiny snippet of the beginning of the start-up sound is heard and then abruptly cut off.
### Expected behavior:
The start-up sound is heard in full as in previous versions.
### NVDA logs, crash dumps and other attachments:
Mostly complete dump of the initialization routine, contains possibly relevant error. Note the position in this chain the error occurs is variable due to threading.
```
DEBUG - __main__ (11:17:16.808) - MainThread (17512):
Provided arguments: ['--disable-addons', '--debug-logging']
INFO - __main__ (11:17:16.808) - MainThread (17512):
Starting NVDA version alpha-28675,384a7428
DEBUG - __main__ (11:17:16.808) - MainThread (17512):
Debug level logging enabled
DEBUG - core.main (11:17:17.226) - MainThread (17512):
Core starting
DEBUG - NVDAState._configInLocalAppDataEnabled (11:17:17.226) - MainThread (17512):
Installed user config is not in local app data
INFO - core.main (11:17:17.228) - MainThread (17512):
Config dir: C:\Users\Colton\AppData\Roaming\nvda
DEBUG - core.main (11:17:17.228) - MainThread (17512):
loading config
INFO - config.ConfigManager._loadConfig (11:17:17.232) - MainThread (17512):
Loading config: C:\Users\Colton\AppData\Roaming\nvda\nvda.ini
...
INFO - config.ConfigManager._loadConfig (11:17:17.295) - MainThread (17512):
Config loaded (after upgrade, and in the state it will be used by NVDA):
...
DEBUG - core.main (11:17:17.297) - MainThread (17512):
setting language to Windows
DEBUGWARNING - languageHandler._createGettextTranslation (11:17:17.297) - MainThread (17512):
couldn't set the translation service locale to en_US
DEBUG - languageHandler.setLocale (11:17:17.297) - MainThread (17512):
Win32 locale string from locale code is English_United States.1252
DEBUG - languageHandler._setPythonLocale (11:17:17.301) - MainThread (17512):
set python locale to English_United States.1252
DEBUG - core.main (11:17:17.562) - MainThread (17512):
Initializing NVDAHelper
DEBUG - NVDAHelper._RemoteLoader.__init__ (11:17:17.574) - MainThread (17512):
Starting C:\Program Files (x86)\NVDA\lib64\alpha-28675,384a7428\nvdaHelperRemoteLoader.exe
DEBUG - core.main (11:17:17.578) - MainThread (17512):
initializing nvwave
INFO - core.main (11:17:17.711) - MainThread (17512):
Windows version: Windows 10 22H2 (10.0.19045) workstation AMD64
INFO - core.main (11:17:17.711) - MainThread (17512):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (11:17:17.711) - MainThread (17512):
Using comtypes version 1.1.11
INFO - core.main (11:17:17.711) - MainThread (17512):
Using configobj version 5.1.0 with validate version 1.0.1
DEBUG - core.main (11:17:17.712) - MainThread (17512):
Initializing add-ons system
ERROR - stderr (11:17:17.715) - nvwave.playWaveFile(start.wav) (1708):
Exception in thread nvwave.playWaveFile(start.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
  File "nvwave.pyc", line 895, in feed
  File "nvwave.pyc", line 975, in _scheduleIdleCheck
  File "core.pyc", line 928, in callLater
core.NVDANotInitializedError: Cannot schedule callable, wx.App is not initialized
DEBUG - _addonStore.dataManager.initialize (11:17:17.785) - MainThread (17512):
initializing addonStore data manager
...
INFO - core.main (11:17:17.924) - MainThread (17512):
Add-ons are disabled. Restart NVDA to enable them.
DEBUG - core.main (11:17:17.924) - MainThread (17512):
Initializing appModule Handler
DEBUG - core.main (11:17:17.924) - MainThread (17512):
initializing background i/o
DEBUG - core.main (11:17:17.924) - MainThread (17512):
Initializing background braille display detection
DEBUG - core.main (11:17:17.926) - MainThread (17512):
Initializing tones
DEBUG - core.main (11:17:17.934) - MainThread (17512):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (11:17:17.934) - MainThread (17512):
Loading speech dictionary 'C:\Users\Colton\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (11:17:17.937) - MainThread (17512):
23 loaded records.
DEBUG - speechDictHandler.SpeechDict.load (11:17:17.937) - MainThread (17512):
Loading speech dictionary 'C:\Program Files (x86)\NVDA\builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (11:17:17.938) - MainThread (17512):
3 loaded records.
DEBUG - core.main (11:17:17.938) - MainThread (17512):
Initializing speech
INFO - synthDrivers.espeak.SynthDriver.__init__ (11:17:17.968) - MainThread (17512):
Using eSpeak NG version 1.52-dev
DEBUG - speechDictHandler.SpeechDict.load (11:17:18.065) - MainThread (17512):
Loading speech dictionary 'C:\Users\Colton\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-English (Great Britain).dic'...
DEBUG - speechDictHandler.SpeechDict.load (11:17:18.066) - MainThread (17512):
file 'C:\Users\Colton\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-English (Great Britain).dic' not found.
DEBUG - synthDriverHandler.SynthDriver.loadSettings (11:17:18.067) - MainThread (17512):
Loaded settings for SynthDriver espeak
INFO - synthDriverHandler.setSynth (11:17:18.067) - MainThread (17512):
Loaded synthDriver espeak
DEBUG - speech.sayAll.initialize (11:17:18.067) - MainThread (17512):
Initializing sayAllHandler
DEBUG - core.main (11:17:18.086) - MainThread (17512):
Initializing MathPlayer
INFO - core.main (11:17:18.379) - MainThread (17512):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
DEBUG - core.main (11:17:18.380) - MainThread (17512):
Initializing braille input
INFO - brailleInput.initialize (11:17:18.380) - MainThread (17512):
Braille input initialized
DEBUG - core.main (11:17:18.381) - MainThread (17512):
Initializing braille
INFO - braille.initialize (11:17:18.381) - MainThread (17512):
Using liblouis version 3.25.0
INFO - braille.initialize (11:17:18.381) - MainThread (17512):
Using pySerial version 3.5
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (11:17:18.382) - MainThread (17512):
registering pre_configSave action: <class 'brailleDisplayDrivers.noBraille.BrailleDisplayDriver'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (11:17:18.385) - MainThread (17512):
loading braille noBraille
INFO - braille.BrailleHandler._setDisplay (11:17:18.385) - MainThread (17512):
Loaded braille display driver 'noBraille', current display has 0 cells.
DEBUG - core.main (11:17:18.385) - MainThread (17512):
Initializing vision
DEBUG - core.main (11:17:18.385) - MainThread (17512):
Initializing displayModel
DEBUG - core.main (11:17:18.385) - MainThread (17512):
Initializing GUI
DEBUG - windowUtils._rawWindowProc (11:17:18.405) - MainThread (17512):
CustomWindow rawWindowProc called for unknown window 655400
DEBUG - windowUtils._rawWindowProc (11:17:18.406) - MainThread (17512):
CustomWindow rawWindowProc called for unknown window 655400
DEBUG - windowUtils._rawWindowProc (11:17:18.406) - MainThread (17512):
CustomWindow rawWindowProc called for unknown window 655400
DEBUG - windowUtils._rawWindowProc (11:17:18.406) - MainThread (17512):
CustomWindow rawWindowProc called for unknown window 655400
DEBUG - languageHandler.setLocale (11:17:18.407) - MainThread (17512):
Win32 locale string from locale code is English_United States.1252
DEBUG - languageHandler._setPythonLocale (11:17:18.407) - MainThread (17512):
set python locale to English_United States.1252
DEBUG - core.main (11:17:18.407) - MainThread (17512):
Initializing garbageHandler
DEBUG - core.main (11:17:18.417) - MainThread (17512):
initializing Java Access Bridge support
INFO - core.main (11:17:18.536) - MainThread (17512):
Java Access Bridge support initialized
DEBUG - core.main (11:17:18.537) - MainThread (17512):
Initializing legacy winConsole support
DEBUG - core.main (11:17:18.594) - MainThread (17512):
Initializing UIA support
INFO - UIAHandler.UIAHandler.MTAThreadFunc (11:17:18.604) - UIAHandler.UIAHandler.MTAThread (2676):
UIAutomation: IUIAutomation6
DEBUG - core.main (11:17:18.683) - MainThread (17512):
Initializing IAccessible support
DEBUG - core.main (11:17:18.683) - MainThread (17512):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (11:17:18.685) - MainThread (17512):
No locale gesture map for language en
DEBUG - core.main (11:17:18.693) - MainThread (17512):
Initializing keyboard handler
DEBUG - core.main (11:17:18.694) - MainThread (17512):
initializing mouse handler
DEBUG - core.main (11:17:18.719) - MainThread (17512):
Initializing touchHandler
DEBUGWARNING - touchHandler.touchSupported (11:17:18.720) - MainThread (17512):
No touch devices found
DEBUG - core.main (11:17:18.720) - MainThread (17512):
Initializing global plugin handler
DEBUG - core.main (11:17:18.720) - MainThread (17512):
Initializing core pump
DEBUG - core.main (11:17:18.721) - MainThread (17512):
Initializing watchdog
DEBUG - core.main (11:17:18.722) - MainThread (17512):
initializing updateCheck
INFO - core.main (11:17:18.723) - MainThread (17512):
NVDA initialized
```
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.2.0.28675
#### Windows version:
Windows 10 22H2 (19045.3208)
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
Used sound card is kept open via silenzio and is USB, so the truncation is not due to NVDA being the first sound to play on it.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not since this issue, but I've been on the alpha branch for a while now and this alpha was the first to introduce this behavior. I was previously only two commits behind it and that version did not exhibit this behavior.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes, given log is from such a state
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by brunoprietog** [comment]
Related issues: #15141, #15142

**Comment by ultrasound1372** [comment]
They are not related actually, as the change that is causing those errors is related to the settings panel API changing, whereas this is related to the WASAPI changes made in #15097

**Comment by jcsteh** [comment]
I guess I can see why this might happen, though it doesn't happen on my system. There's probably a race condition involved here, since sounds are played in a background thread. The issue is also being obscured by #15142, since that causes an error sound.

**Comment by brunoprietog** [comment]
I feel it's that, the error sound interrupts the NVDA initialization sound

**Comment by jcsteh** [comment]
No, it isn't, but that does make debugging this annoying.

**Comment by Brian1Gaff** [comment]
Are you sure? To me its the noise of the error, but that is also internal as 
its the initialisation of the vision gui that triggers it.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment]
Yes, I'm sure. Both of these problems are real, but there are both separate, albeit annoyingly easy to conflate. The key point here is this exception in the log that was originally provided:

```
Exception in thread nvwave.playWaveFile(start.wav):
...
  File "nvwave.pyc", line 895, in feed
  File "nvwave.pyc", line 975, in _scheduleIdleCheck
  File "core.pyc", line 928, in callLater
core.NVDANotInitializedError: Cannot schedule callable, wx.App is not initialized
```

That has nothing to do with vision providers.
