### ISSUE TITLE
after making new api public function, vision providers are not opening

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#15142]
### Steps to reproduce:
1. upgrade to latest alpha,
2. try to start it. You will hear few error sounds
3. try to open settings, and navigate to vision section
### Actual behavior:

we hear error sound, and we have the following log:
ERROR - vision.visionHandler._getProvidersFromFileSystem (13:08:30.611) - MainThread (4400):
Error while importing vision enhancement provider module NVDAHighlighter
Traceback (most recent call last):
  File "vision\visionHandler.pyc", line 58, in _getProvidersFromFileSystem
  File "vision\visionHandler.pyc", line 36, in _getProviderClass
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 242, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
ERROR - vision.visionHandler._getProvidersFromFileSystem (13:08:30.639) - MainThread (4400):
Error while importing vision enhancement provider module screenCurtain
Traceback (most recent call last):
  File "vision\visionHandler.pyc", line 58, in _getProvidersFromFileSystem
  File "vision\visionHandler.pyc", line 36, in _getProviderClass
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\screenCurtain.pyc", line 218, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
ERROR - queueHandler.flushQueue (13:08:30.664) - MainThread (4400):
Error in func VisionHandler.postGuiInit
Traceback (most recent call last):
  File "queueHandler.pyc", line 64, in flushQueue
  File "vision\visionHandler.pyc", line 96, in postGuiInit
  File "vision\visionHandler.pyc", line 119, in _updateAllProvidersList
  File "vision\visionHandler.pyc", line 103, in _getBuiltInProviderIds
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 242, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
ERROR - unhandled exception (13:13:42.289) - MainThread (4400):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 4312, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 693, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 675, in _doCategoryChange
  File "gui\settingsDialogs.pyc", line 603, in _getCategoryPanel
  File "gui\settingsDialogs.pyc", line 361, in __init__
  File "gui\settingsDialogs.pyc", line 371, in _buildGui
  File "gui\settingsDialogs.pyc", line 4025, in makeSettings
  File "vision\visionHandler.pyc", line 138, in getProviderList
  File "vision\visionHandler.pyc", line 119, in _updateAllProvidersList
  File "vision\visionHandler.pyc", line 103, in _getBuiltInProviderIds
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 242, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'

### Expected behavior:

vision providers should work and they shold be displayed.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-28685,a8b79c76

#### Windows version:
windows 11, 22H2, Windows 11 22H2 (10.0.23493) workstation AMD64

#### Name and version of other software in use when reproducing the issue:
n/a
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, older alpha before new api breakage.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by cary-rowen** [comment]
This seems to be the same issue as #15141.

**Comment by amirsol81** [comment]
I can duplicate this. So Braille-related items show up under my Vision pane of the Settings window with the latest Alpha.

**Comment by Brian1Gaff** [comment]
Yes it seems that random bits of the settings show up instead of the correct 
one, but on add ons they just fail to appear altogether making them not 
work, due to exit at initianalisation
Add to the list, the ocr program, unmute sound, and read feeds. and I think 
sound schemes.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
