### ISSUE TITLE
NVDA addons store becomes unusable if NVDA's language is set to Serbian

### ISSUE THREAD

**Issue by nidza07** [nvaccess/nvda#15231]
### Steps to reproduce:
1. Make sure NVDA's language is set to Serbian (possibly affects other languages as well).
2. Open the addons store, and install any available addon. In this case, I chose NVDA remote.

### Actual behavior:
In the middle of the installation, the following error is logged:
> ERROR - unhandled exception (21:25:01.901) - MainThread (11864):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\storeDialog.pyc", line 238, in onClose
  File "gui\_addonStoreGui\viewModels\store.pyc", line 333, in installPending
  File "gui\_addonStoreGui\viewModels\store.pyc", line 350, in _doInstall
  File "_addonStore\dataManager.pyc", line 274, in _cacheInstalledAddon
  File "json\__init__.pyc", line 180, in dump
  File "encodings\cp1252.pyc", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u010d' in position 50: character maps to <undefined>

After this, the installation dialog is completely stuck. If I manually  restart NVDA however, the addon seems to be installed completely fine. However, now, the addons store is completely broken. If I try to open it again, the following error is logged and the store does not open:
> ERROR - unhandled exception (21:27:36.875) - MainThread (2120):
Traceback (most recent call last):
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "gui\__init__.pyc", line 394, in onAddonStoreCommand
  File "gui\_addonStoreGui\viewModels\store.pyc", line 65, in __init__
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "_addonStore\dataManager.pyc", line 305, in _get_installedAddonGUICollection
  File "addonHandler\__init__.pyc", line 392, in _addonStoreData
  File "_addonStore\dataManager.pyc", line 281, in _getCachedInstalledAddonData
  File "json\__init__.pyc", line 296, in load
  File "json\__init__.pyc", line 348, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 71 (char 70)

The store is now completely unusable, unless you manually delete the "remote.json" file that was generated in the addons folder.
### Expected behavior:
The store should install the addon and work normally
### NVDA logs, crash dumps and other attachments:
I've pasted the errors, but if a full log is necessary, I can attach it.
#### NVDA installed/portable/running from source:
Portable, but happens with installed too
#### NVDA version:
alpha-28809,2c337e53 (2023.3.0.28809)
#### Windows version:
Windows 10 22H2
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I  believe that this issue did not occur before the addons store started supporting translated addons into other languages.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
NA

**Comment by CyrilleB79** [comment]
I am able to reproduce:
* with NVDA 2023.2beta1, both on installed or portable version
* Setting NVDA in Serbian with the flag "--lang=sr", but not in French (flag --lang=fr)
* Installing NVDA remote or Instant Translate, but not installing urlShortener, maybe because NVDA remote or Instant Translate have an "sr" translation but URL shortener has not.

**Comment by mzanm** [comment]
@nidza07 Can you try this build and see if it fixes the issue?
https://ci.appveyor.com/api/buildjobs/yuuxkqs1f4c2j2cg/artifacts/output%2Fnvda_snapshot_pr15241-28825%2C0e1455cc.exe

**Comment by nidza07** [comment]
Thank you @mzanm, the issue is definitely fixed with this build.
