### ISSUE TITLE
NVDA freezes when disconnecting a usb connected brailliant BI40x braille display

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15303]
### Steps to reproduce:
1. Connect a brailliant BI40x braille display via USB
2. Open NVDA and notice the braille display is connected and shows what is on the screen
3. Press the power button of the braille display together with the volume key to send the braille display in the recovery mode, the braille display will turn off and will be disconnected for a while

### Actual behavior:
NVDA gives and error sound and freezes completely. Following is written to the log:
```
IO - braille.BrailleBuffer.update (14:20:44.644) - MainThread (19432):
Braille regions text: ['Desktop lst ', 'Papierkorb 1 von 7']
IO - braille.BrailleHandler.update (14:20:44.644) - MainThread (19432):
Braille window dots: 12347 1 1234 24 15 1235 13 135 1235 12 - 16 - 1236 135 1345 - 12456
ERROR - braille.BrailleHandler._bgThreadExecutor (14:20:44.643) - hwIo.ioThread.IoThread (1928):
Error displaying cells. Disabling display
Traceback (most recent call last):
  File "braille.pyc", line 2663, in _bgThreadExecutor
  File "brailleDisplayDrivers\brailliantB.pyc", line 240, in display
  File "hwIo\hid.pyc", line 318, in setOutputReport
OSError: [WinError 1167] Das Gerät ist nicht angeschlossen.
ERROR - braille.BrailleHandler.handleDisplayUnavailable (14:20:44.661) - hwIo.ioThread.IoThread (1928):
Braille display unavailable. Disabling
Traceback (most recent call last):
  File "braille.pyc", line 2663, in _bgThreadExecutor
  File "brailleDisplayDrivers\brailliantB.pyc", line 240, in display
  File "hwIo\hid.pyc", line 318, in setOutputReport
OSError: [WinError 1167] Das Gerät ist nicht angeschlossen.
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (14:20:44.678) - hwIo.ioThread.IoThread (1928):
registering pre_configSave action: <class 'brailleDisplayDrivers.noBraille.BrailleDisplayDriver'>
DEBUG - braille.BrailleHandler._switchDisplay (14:20:44.678) - hwIo.ioThread.IoThread (1928):
Switching braille display from 'brailliantB' to 'noBraille'
ERROR - braille.BrailleDisplayDriver.terminate (14:20:44.678) - hwIo.ioThread.IoThread (1928):
Display driver BrailleDisplayDriver('brailliantB', numCells=40) failed to display while terminating.
Traceback (most recent call last):
  File "braille.pyc", line 2663, in _bgThreadExecutor
  File "brailleDisplayDrivers\brailliantB.pyc", line 240, in display
  File "hwIo\hid.pyc", line 318, in setOutputReport
OSError: [WinError 1167] Das Gerät ist nicht angeschlossen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "braille.pyc", line 2819, in terminate
  File "brailleDisplayDrivers\brailliantB.pyc", line 240, in display
  File "hwIo\hid.pyc", line 318, in setOutputReport
OSError: [WinError 1167] Das Gerät ist nicht angeschlossen.
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (14:20:44.697) - hwIo.ioThread.IoThread (1928):
loading braille noBraille
INFO - braille.BrailleHandler._setDisplay (14:20:44.698) - hwIo.ioThread.IoThread (1928):
Loaded braille display driver 'noBraille', current display has 0 cells.
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (14:20:45.473) - watchdog (22456):
Potential freeze, waiting up to 10 seconds.
```

### Expected behavior:
NVDA should not freeze

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-28861,705687b3 (2023.3.0.28861)

#### Windows version:
Windows 11 22 H2

#### Name and version of other software in use when reproducing the issue:
n/a

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
After further attempts unfortunately I cannot reproduce this issue reliably acctually, I think i will close it and will reopen in case I have more detailed information.
