### ISSUE TITLE
Unable to access some list of Windows components

### ISSUE THREAD

**Issue by CoBC** [nvaccess/nvda#15333]
### Steps to reproduce:
- Try to access for example to services list (services.msc)

### Actual behavior:

- NVDA don't read list item and error shown in the log

### Expected behavior:

- NVDA should read list correctly

### NVDA logs, crash dumps and other attachments:
- Log attach to the comment

#### NVDA installed/portable/running from source:
- Installed

#### NVDA version:
- alpha-28949,1e30951e

#### Windows version:
- Windows 11 22H2 (AMD64) build 22621.2134

#### Name and version of other software in use when reproducing the issue:
- services.msc, gpedit.msc

#### Does the issue still occur after restarting your computer?
- Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
- Works fine with stable NVDA version

#### If NVDA add-ons are disabled, is your problem still occurring?
- Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
- Yes
[nvda.log](https://github.com/nvaccess/nvda/files/12446825/nvda.log)

**Comment by CoBC** [comment]
First comment edited, sorry

**Comment by Brian1Gaff** [comment]
Unless my email client is confused, neither message contains the answers to the template. I assume you have turned on the ability to access system files etc, or you are not able to access them, strange to relate! For a new user, its far better to leave these at default, since it is very easy to accidentally screw them up.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment]
Brian, I'd encourage you to use the web interface of GitHub. Issues and comments are regularly edited after submission like in this case.

**Comment by seanbudd** [comment]
Can you create a log with add-ons disabled?

The issue is with this part in the stack trace.
It's either an issue with add-ons, or with #15295 or both

cc @leonardder 

```py
ERROR - eventHandler.executeEvent (00:29:55.918) - MainThread (6620):
error executing event: gainFocus on <NVDAObjects.UIA.sysListView32.SysListViewItem object at 0x0A8E1D10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 325, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "C:\Users\coren\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 171, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 124, in next
  File "C:\Users\coren\AppData\Roaming\nvda\addons\TeleNVDA\globalPlugins\remoteClient\__init__.py", line 585, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 124, in next
  File "C:\Users\coren\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator\__init__.py", line 97, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1343, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1293, in event_gainFocus
  File "NVDAObjects\behaviors.pyc", line 698, in reportFocus
  File "NVDAObjects\__init__.pyc", line 1144, in reportFocus
  File "speech\speech.pyc", line 628, in speakObject
  File "speech\speech.pyc", line 668, in getObjectSpeech
  File "speech\speech.pyc", line 520, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\sysListView32.pyc", line 65, in _get_name
  File "comtypes\__init__.pyc", line 1198, in QueryInterface
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467262, 'Cette interface n’est pas prise en charge', (None, None, None, 0, None))
```

**Comment by CoBC** [comment]
Here is a log with addons disabled.
[nvda.log](https://github.com/nvaccess/nvda/files/12460807/nvda.log)

**Comment by seanbudd** [comment]
thanks - I can see that the issue is still the same, just without the add-on in the stacktrace

**Comment by leonardder** [comment]
Looks like we should revert removing syslistview32 from badUIAClassNames. Windows advertises these syslistview32 controls as supporting UIA natively, but that doesn't seem to be the case 🙃

**Comment by leonardder** [comment]
I'm not sure how to fix this. Classifying syslistview32 as a bad UIA class name globally will reintroduce #15283. #15283 is caused by the fact that the MSAA implementation in Win Forms doesn't use non-0 iiaccessible ids for the list items, probably because that implementation is simply proxied by UIA. So basically we are stuck between two clashing situations.
I guess we need to move the syslistview32 classes out of the IAccessible package into the Window package, then fallback to the classes in Window when the UIA implementation is incomplete.

**Comment by leonardder** [comment]
After more investigation, I think we should fix this in mmc appmodule for now. We should also change the UIA syslistview32 code in such a way that can deal with lacking table and grid patterns.

**Comment by leonardder** [comment]
There is actually a workaround now by disabling column header reporting.

**Comment by CyrilleB79** [comment]
I understand that #15348 will fix this issue (thanks @leonardder) by a workaround.

But has the issue been reported to Microsoft? Is it also present with Narrator?

**Comment by CoBC** [comment]
No, no problem with Narrator.
