### ISSUE TITLE
Config migration seems to fail for excluded displays when trying to update from a previous alpha build

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15370]
The config migration seems to fail. When trying to update from a previous alpha build, I get:

```
Traceback (most recent call last):
  File "config\__init__.pyc", line 571, in _initBaseConf
  File "config\__init__.pyc", line 605, in _loadConfig
  File "config\__init__.pyc", line 601, in _loadConfig
  File "config\profileUpgrader.pyc", line 24, in upgrade
  File "config\profileUpgrader.pyc", line 41, in _doConfigUpgrade
  File "config\profileUpgradeSteps.pyc", line 368, in upgradeConfigFrom_10_to_11
  File "configobj\__init__.pyc", line 508, in __getitem__
KeyError: 'excludedDisplays'
```

_Originally posted by @bramd in https://github.com/nvaccess/nvda/issues/15200#issuecomment-1705609083_

**Comment by leonardder** [comment]
This can actually lead to a pretty severe crash:

```
core failure
Traceback (most recent call last):
  File "config\__init__.pyc", line 571, in _initBaseConf
  File "config\__init__.pyc", line 605, in _loadConfig
  File "config\__init__.pyc", line 601, in _loadConfig
  File "config\profileUpgrader.pyc", line 24, in upgrade
  File "config\profileUpgrader.pyc", line 41, in _doConfigUpgrade
  File "config\profileUpgradeSteps.pyc", line 368, in upgradeConfigFrom_10_to_11
  File "configobj\__init__.pyc", line 508, in __getitem__
KeyError: 'auto'
```

Now this is strange, because the key is really part of the config spec. It looks like the config spec isn't applied to the profile at migration time.
