### ISSUE TITLE
Error when activating secure desktop

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15395]
### Steps to reproduce:
Activate the secure desktop

### Actual behavior:
Following is in the log:

```
ERROR - unhandled exception (17:57:20.263) - winInputHook (16960):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "winInputHook.pyc", line 56, in keyboardHook
  File "keyboardHandler.pyc", line 257, in internal_keyDownEvent
  File "keyboardHandler.pyc", line 150, in shouldUseToUnicodeEx
AttributeError: '_SecureDesktopNVDAObject' object has no attribute 'windowClassName'
```

### Expected behavior:
No error.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29111,b341bf97

#### Windows version:
Windows 11 23H2 insider

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

**Comment by leonardder** [comment]
From the doc string of the new SecureDesktopNVDAObject:

> For security purposes, it is ideal we use a fake NVDAObject, that is not tied to any real window.

Looks like that code in the keyboard hook expects an object to hhave a window class. This is more likely to be a bug in that code than an issue in the chosen approach for #14488) 
Cc @seanbudd
