### ISSUE TITLE
Error logged when browsing to new page in Firefox

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15391]
### Steps to reproduce:
1. Open Firefox
2. Press CTRL+L
3. Enter a website address, e.g. nvaccess.org and press enter

### Actual behavior:
Error in log:
```
ERROR - core.CorePump.Notify (09:05:27.183) - MainThread (10848):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 764, in Notify
  File "braille.pyc", line 2749, in pumpAll
  File "braille.pyc", line 2502, in _handlePendingUpdate
  File "braille.pyc", line 1243, in update
  File "braille.pyc", line 1427, in _getSelection
  File "documentBase.pyc", line 79, in _get_selection
  File "documentBase.pyc", line 74, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 210, in __init__
  File "textInfos\offsets.pyc", line 479, in __init__
  File "virtualBuffers\__init__.pyc", line 215, in _getSelectionOffsets
OSError: [WinError 1775] A null context handle was passed from the client to the host during a remote procedure call
```

### Expected behavior:
No errors.

#### NVDA version:
2023.3 Beta branch

#### Name and version of other software in use when reproducing the issue:
Firefox 117

### Technical details
This is probably a regression from #15163. As braille updates are now performed at the end of each core cycle, the virtual buffer probably died at update time. This should be a trivial fix, when working with a tree interceptor, the isAlive property should be checked, probably in handlePendingUpdate.

**Comment by leonardder** [comment]
I will fix this later this week.
