### ISSUE TITLE
With NVDA 2023.2 and 2023.3 beta2, it is no longer possible to read the registry

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15495]
- type "windows+r",
- type the "regedit" command,
- - the registry editor opens
- use the up and down arrows to move the cursor,

NVDA does not speak and an error is written in the log:

Traceback (most recent call last):
  File "eventHandler.pyc", line 320, in executeEvent
  File "eventHandler.pyc", line 355, in doPreGainFocus
  File "api.pyc", line 139, in setFocusObject
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 655, in _get_container
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\sysTreeView32.pyc", line 244, in _get_parent
AttributeError: 'IAccessible' object has no attribute 'UIAElement'

Everything is normal with NVDA 2023.1

### Expected behavior:

No error and registry editor must be accessible
#### NVDA installed/portable/running from source:
NVDA portable
#### NVDA version:
2023.2 and 2023.3beta2
#### Windows version:
Windows 10 22H2 (10.0.19045) workstation x86
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. No problem with nvda 2023.1
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Kc9jjj** [comment]
It must be something new I had no problem doing this on beta 2
73,
Darren Tomblin KC9JJJ

On Sep 21, 2023, at 1:36 PM, paulber19 ***@***.***> wrote:

﻿

  *   type "windows+r",
  *   type the "regedit" command,
  *
     *   the registry editor opens
  *   use the up and down arrows to move the cursor,

NVDA does not speak and an error is written in the log:

Traceback (most recent call last):
File "eventHandler.pyc", line 320, in executeEvent
File "eventHandler.pyc", line 355, in doPreGainFocus
File "api.pyc", line 139, in setFocusObject
File "baseObject.pyc", line 62, in get
File "baseObject.pyc", line 168, in getPropertyViaCache
File "NVDAObjects_init.pyc", line 655, in _get_container
File "baseObject.pyc", line 62, in get
File "baseObject.pyc", line 168, in _getPropertyViaCache
File "NVDAObjects\IAccessible\sysTreeView32.pyc", line 244, in _get_parent
AttributeError: 'IAccessible' object has no attribute 'UIAElement'

Everything is normal with NVDA 2023.1

Steps to reproduce:
Actual behavior:
Expected behavior:

No error and registry editor must be accessible

NVDA logs, crash dumps and other attachments:
System configuration
NVDA installed/portable/running from source:

NVDA portable

NVDA version:

2023.2 and 2023.3beta2

Windows version:

Windows 10 22H2 (10.0.19045) workstation x86

Name and version of other software in use when reproducing the issue:

None

Other information about your system:
Other questions
Does the issue still occur after restarting your computer?

Yes

Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes. No problem with nvda 2023.1

If NVDA add-ons are disabled, is your problem still occurring?

Yes.

Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by Adriani90** [comment]
I cannot reproduce in the last alpha on Windows 11 at least.

cc: @lukaszgo1 can you reproduce on Windows 10 or so?

**Comment by seanbudd** [comment]
This is a limitation with using NVDA portable, NVDA cannot run with software running as an administrator

**Comment by paulber19** [comment]
You are right. I had forgotten to run NVDA portable as administrator.
I'm really sorry for making this mistake and asking this issue.
Best regards.
