### ISSUE TITLE
nvda 2023.3rc1: errors when changing tabs in the add-on store

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15670]
### Actual behavior:

Open the add-on store and quickly type "control+tab" or "control+shift+tab" several times.
After a while, errors are written to the log:

Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in _getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - unhandled exception (07:12:34.599) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 251, in _getAddonFieldText
AttributeError: 'AddonStoreModel' object has no attribute 'author'
ERROR - unhandled exception (07:12:34.649) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in _getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - unhandled exception (07:12:34.704) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 251, in _getAddonFieldText
AttributeError: 'AddonStoreModel' object has no attribute 'author'
ERROR - unhandled exception (07:12:34.759) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in _getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - unhandled exception (07:12:34.809) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 251, in _getAddonFieldText
AttributeError: 'AddonStoreModel' object has no attribute 'author'
ERROR - unhandled exception (07:12:34.864) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in _getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - unhandled exception (07:12:34.909) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 251, in _getAddonFieldText
AttributeError: 'AddonStoreModel' object has no attribute 'author'
ERROR - unhandled exception (07:12:34.969) - MainThread (4460):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in OnGetItemText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in getAddonFieldText
  File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in _getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - extensionPoints.Action.notify (07:12:35.409) - MainThread (4460):
Error running handler <bound method AddonDetails._updatedListItem of <gui._addonStoreGui.controls.details.AddonDetails object at 0x08219AD0>> for <extensionPoints.Action object at 0x0819C770>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 55, in notify
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "gui\_addonStoreGui\controls\details.pyc", line 193, in _updatedListItem
  File "gui\_addonStoreGui\controls\details.pyc", line 247, in _refresh
AttributeError: 'NoneType' object has no attribute 'version'

Other error:
ERROR - extensionPoints.Action.notify (07:18:17.553) - MainThread (4460):
Error running handler <bound method AddonDetails._updatedListItem of <gui._addonStoreGui.controls.details.AddonDetails object at 0x08219AD0>> for <extensionPoints.Action object at 0x0819C770>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 55, in notify
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "gui\_addonStoreGui\controls\details.pyc", line 193, in _updatedListItem
  File "gui\_addonStoreGui\controls\details.pyc", line 247, in _refresh
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - extensionPoints.Action.notify (07:18:17.723) - MainThread (4460):
Error running handler <bound method AddonDetails._updatedListItem of <gui._addonStoreGui.controls.details.AddonDetails object at 0x08219AD0>> for <extensionPoints.Action object at 0x0819C770>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 55, in notify
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "gui\_addonStoreGui\controls\details.pyc", line 193, in _updatedListItem
  File "gui\_addonStoreGui\controls\details.pyc", line 247, in _refresh
AttributeError: 'NoneType' object has no attribute 'version'

### Expected behavior:

No error
#### NVDA installed/portable/running from source:
nvda portable
#### NVDA version:
nvda 2023.3rc1
#### Windows version:
Windows 10 22H2 (10.0.19045) workstation AMD64

#### Name and version of other software in use when reproducing the issue:
None
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
No
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
No tested

**Comment by seanbudd** [comment]
I am unable to reproduce this - do you have a large number of add-ons installed and/or available for update?

**Comment by paulber19** [comment]
There are 27 add-ons installed, 3 activated  and only one update available.
The errors don't happen right away but after a lot of going back and 
forth between the tabs.

**Comment by ruifontes** [comment]
Can't reproduce.
The only errors logged are:
ERROR - _addonStore.dataManager._DataManager._getCachedInstalledAddonData (12:38:01.501) - MainThread (15724):
Invalid cached installed add-on data: C:\Users\Utilizador\AppData\Roaming\nvda\addons\clipspeak.json
Traceback (most recent call last):
  File "_addonStore\dataManager.pyc", line 284, in _getCachedInstalledAddonData
  File "json\__init__.pyc", line 293, in load
  File "codecs.pyc", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 93: invalid continuation byte
ERROR - _addonStore.dataManager._DataManager._getCachedInstalledAddonData (12:38:01.502) - MainThread (15724):
Invalid cached installed add-on data: C:\Users\Utilizador\AppData\Roaming\nvda\addons\clock.json
Traceback (most recent call last):
  File "_addonStore\dataManager.pyc", line 284, in _getCachedInstalledAddonData
  File "json\__init__.pyc", line 293, in load
  File "codecs.pyc", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 40: invalid continuation byte

**Comment by seanbudd** [comment]
Is there any affect on the user or just errors in the log?

**Comment by ruifontes** [comment]
No, it does not cause any problem...
By instance, clipSpeak.json and clock.json are formated in ANSI (CP-1252) instead of UTF-8...

**Comment by seanbudd** [comment]
Ah - it seems you have add-on data from an alpha or beta release. You may need to delete those files

**Comment by paulber19** [comment]
No, I haven't noticed anything like that.
But the error only occurs when selecting the "Installed incompatible 
add-ons" tab after multiple "control+tab".
For information, there are 27 add-ons installed and no incompatible 
add-ons installed.
I was unable to reproduce the error when all add-ons are disabled.

Here is the error:
ERROR - unhandled exception (09:38:52.372) - MainThread (7232):
Traceback (most recent call last):
   File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in 
OnGetItemText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in 
getAddonFieldText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in 
_getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - unhandled exception (09:38:52.437) - MainThread (7232):
Traceback (most recent call last):
   File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in 
OnGetItemText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in 
getAddonFieldText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 251, in 
_getAddonFieldText
AttributeError: 'AddonStoreModel' object has no attribute 'author'
ERROR - unhandled exception (09:38:52.487) - MainThread (7232):
Traceback (most recent call last):
   File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in 
OnGetItemText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in 
getAddonFieldText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in 
_getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - unhandled exception (09:38:52.542) - MainThread (7232):
Traceback (most recent call last):
   File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in 
OnGetItemText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in 
getAddonFieldText
       File "gui\_addonStoreGui\viewModels\addonList.pyc", line 251, in 
_getAddonFieldText
AttributeError: 'AddonStoreModel' object has no attribute 'author'
ERROR - unhandled exception (09:38:52.597) - MainThread (7232):
Traceback (most recent call last):
   File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in 
OnGetItemText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in 
getAddonFieldText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in 
_getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - unhandled exception (09:38:52.647) - MainThread (7232):
Traceback (most recent call last):
   File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in 
OnGetItemText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in 
getAddonFieldText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 251, in 
_getAddonFieldText
AttributeError: 'AddonStoreModel' object has no attribute 'author'
ERROR - unhandled exception (09:38:52.762) - MainThread (7232):
Traceback (most recent call last):
   File "gui\_addonStoreGui\controls\addonList.pyc", line 113, in 
OnGetItemText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 239, in 
getAddonFieldText
   File "gui\_addonStoreGui\viewModels\addonList.pyc", line 244, in 
_getAddonFieldText
AttributeError: 'NoneType' object has no attribute 'version'
ERROR - extensionPoints.Action.notify (09:38:53.078) - MainThread (7232):
Error running handler <bound method AddonDetails._updatedListItem of 
<gui._addonStoreGui.controls.details.AddonDetails object at 0x09DE7C60>> 
for <extensionPoints.Action object at 0x09DDF930>
Traceback (most recent call last):
   File "extensionPoints\__init__.pyc", line 55, in notify
   File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
   File "gui\_addonStoreGui\controls\details.pyc", line 193, in 
_updatedListItem
   File "gui\_addonStoreGui\controls\details.pyc", line 247, in _refresh
AttributeError: 'NoneType' object has no attribute 'version'

**Comment by Brian1Gaff** [comment]
If you look on the devel or add ons group, I posted another add on store error that only comes up at first run, where it seems to be unable to find the add on store urls, probably due to the windows system taking time to be able to go online.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
@paulber19 are you still having this issue in NVDA last alpha?
You say you have 3 addons enabled out of 27 and you cannot reproduce this error with addons disabled. Which 3 addons are activated? Could you reproduce this issue while disabling the addons one by one? If you have the addon columns review installed, this might have an impact.
cc: @ABuffEr

**Comment by seanbudd** [comment]
@paulber19 - any updates here? Can you answer @Adriani90's question? Note uploading a full log file would be helpful here, rather than pasting snippets

**Comment by paulber19** [comment]
[nvda.log](https://github.com/nvaccess/nvda/files/13946773/nvda.log)
I managed to reproduce the error with NVDA 2024.1beta4 and modules disabled. See the log.

**Comment by CyrilleB79** [comment]
Oh, there are many issues with this log:
1. @paulber19: a full log is nice, but it would help much more with the log level set to `DEBUG`. Here we are even not able to know your configuration unfortunately. If you have the opportunity provide a log at `DEBUG` level (and still add-ons disabled) while you reproduce the issue, it would be nice.
2. Some error messages are sent line by line to standard error output. @michaelDCurran, I think that you had fixed this in the past, but I have seen it again various times recently; may there be a regression?
3. There are also many errors in `nvwave` with `fileWavePlayer` being `None`. @paulber19, are you using WASAPI? I have also had such series of errors myself occasionnally recently, but I have not succeeded to reproduce with add-ons disabled. Cc @jcsteh, any opinion or something to dig?

**Comment by paulber19** [comment]
[nvda 2023.3.1 without add-on.log](https://github.com/nvaccess/nvda/files/13962092/nvda.2023.3.1.without.add-on.log)

[nvda 2023.3.1 with add-ons .log](https://github.com/nvaccess/nvda/files/13962073/nvda.2023.3.1.with.add-ons.log)
Although I manage to reproduce the errors that I reported with nvda 2023.3.1 with or without add-on (see logs), I close the question because the errors that I manage to produce with nvda 2024beta4 are not of same nature.

**Comment by paulber19** [comment]
not reproducible with 2024beta4

**Comment by CyrilleB79** [comment]
OK @paulber19. If the issue turns back with NVDA 2024.1 in the future, you can reopen this issue or open a new one.

Just a question that may explain the difference (otherwise than the version change).
Regarding the 2024.1beta4 on which you did the test, is it an upgrade of the 2023.3rc1 where you had the error, i.e. is it the same config folder that has been used before and after the  upgrade? Or has the 2024.1beta4 had its config folder been created independently (e.g. portable NVDA)?
Knowing this would help exclude or not something related to your specific config folder (fonfig files, json, add-ons, manual modifications, etc.)

**Comment by Adriani90** [comment]
This is still reproducible in NVDA 2024.2 Beta 1.
