### ISSUE TITLE
Error in the save file dialog in Powerpoint 365, NVDA does not report element when tabbing

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15675]
### Steps to reproduce:
1. Open NVDA and open an empty Powerpoint file
2. Press tab on a slide to land on its title place holder
3. Press enter to open the place holder and type something
4. Press escape to close the place holder
5. Press alt+f4 to display the save dialog
6. Press tab and shift+tab to navigate the dialog

### Actual behavior:
Following error is written to the log and on the element after the cancel button with this error, NVDA does not report it at all:
```
IO - inputCore.InputManager.executeGesture (22:52:13.549) - winInputHook (18236):
Input: kb(laptop):shift+tab
ERROR - eventHandler.executeEvent (22:52:13.594) - MainThread (18008):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x0555AA70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\behaviors.pyc", line 296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1147, in reportFocus
  File "speech\speech.pyc", line 626, in speakObject
  File "speech\speech.pyc", line 675, in getObjectSpeech
  File "NVDAObjects\window\edit.pyc", line 920, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 718, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'
ERROR - eventHandler.executeEvent (22:52:13.607) - MainThread (18008):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x0555AA70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1741, in event_caret
  File "NVDAObjects\window\edit.pyc", line 895, in event_caret
  File "NVDAObjects\window\edit.pyc", line 920, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 718, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'
IO - inputCore.InputManager.executeGesture (22:52:14.017) - winInputHook (18236):
Input: kb(laptop):shift+tab
IO - speech.speech.speak (22:52:14.046) - MainThread (18008):
Speaking ['Ihre Änderungen an dieser Datei speichern?', 'Fenster', CancellableSpeech (still valid)]
IO - speech.speech.speak (22:52:14.050) - MainThread (18008):
Speaking ['Abbrechen', 'Schalter', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (22:52:15.032) - winInputHook (18236):
Input: kb(laptop):tab
ERROR - eventHandler.executeEvent (22:52:15.082) - MainThread (18008):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x010ADD70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\behaviors.pyc", line 296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1147, in reportFocus
  File "speech\speech.pyc", line 626, in speakObject
  File "speech\speech.pyc", line 675, in getObjectSpeech
  File "NVDAObjects\window\edit.pyc", line 920, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 718, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'
ERROR - eventHandler.executeEvent (22:52:15.093) - MainThread (18008):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x010ADD70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1741, in event_caret
  File "NVDAObjects\window\edit.pyc", line 895, in event_caret
  File "NVDAObjects\window\edit.pyc", line 920, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 718, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'
ERROR - eventHandler.executeEvent (22:52:15.106) - MainThread (18008):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x010ADD70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1741, in event_caret
  File "NVDAObjects\window\edit.pyc", line 895, in event_caret
  File "NVDAObjects\window\edit.pyc", line 920, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 718, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'
```

### Expected behavior:
No error and NVDA reports all the elements in the dialog as it did before.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29726,a207ad54 (2024.1.0.29726)

#### Windows version:
Windows 11 22 H2

#### Name and version of other software in use when reproducing the issue:
MS Powerpoint Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64 Bit

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
@msftedad can you please report this to the development team? it needs an external fix by Microsoft, it seems the edit field for the file name is not passed properly to the screen reader, probably no atribute added, so Microsoft should fix it.

**Comment by msftedad** [comment]
Hi @Adriani90, We have verified this issue on our end and found that it is reproducible only with NVDA. The functionality is working as expected with other screen readers such as JAWS and Narrator.
