### ISSUE TITLE
Automation cathastrophic error sometimes when closing applications such as powerpoint

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15676]
[nvda.txt](https://github.com/nvaccess/nvda/files/13127699/nvda.txt)
### Steps to reproduce:
I reproduced this when closing powerpoint by pressing alt+f4 without saving.

### Actual behavior:
Following errors are written to the log, the impact looks like a short freeze of NVDA until the application is closed:
```
IO - speech.speech.speak (23:04:55.571) - MainThread (13400):
Speaking ['Nicht speichern', 'Schalter', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (23:04:56.094) - winInputHook (17116):
Input: kb(laptop):space
INFO - watchdog.waitForFreezeRecovery (23:04:56.705) - watchdog (12448):
Starting freeze recovery after 0.5000541000044905 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (23:04:56.707) - watchdog (12448):
Listing stacks for Python threads:
Python stack for thread 10472 (Dummy-1):
  File "comtypes\_comobject.pyc", line 154, in call_without_this
  File "UIAHandler\__init__.pyc", line 808, in IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent
  File "UIAHandler\__init__.pyc", line 1325, in isNativeUIAElement
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle

Python stack for thread 1244 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x089D73F0>)):
  File "threading.pyc", line 995, in _bootstrap
  File "threading.pyc", line 1038, in _bootstrap_inner
  File "watchdog.pyc", line 379, in run
  File "threading.pyc", line 622, in wait
  File "threading.pyc", line 320, in wait

Python stack for thread 12448 (watchdog):
  File "threading.pyc", line 995, in _bootstrap
  File "threading.pyc", line 1038, in _bootstrap_inner
  File "threading.pyc", line 975, in run
  File "watchdog.pyc", line 159, in _watcher
  File "watchdog.pyc", line 166, in waitForFreezeRecovery
  File "logHandler.pyc", line 55, in getFormattedStacksForAllThreads

Python stack for thread 17116 (winInputHook):
  File "threading.pyc", line 995, in _bootstrap
  File "threading.pyc", line 1038, in _bootstrap_inner
  File "threading.pyc", line 975, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 12716 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 995, in _bootstrap
  File "threading.pyc", line 1038, in _bootstrap_inner
  File "threading.pyc", line 975, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 320, in wait

Python stack for thread 17468 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 995, in _bootstrap
  File "threading.pyc", line 1038, in _bootstrap_inner
  File "threading.pyc", line 975, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 23852 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 995, in _bootstrap
  File "threading.pyc", line 1038, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 320, in wait

Python stack for thread 17956 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 995, in _bootstrap
  File "threading.pyc", line 1038, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 258, in run

Python stack for thread 13400 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 813, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 746, in processRequest
  File "core.pyc", line 761, in Notify
  File "IAccessibleHandler\__init__.pyc", line 1045, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 725, in processFocusWinEvent
  File "IAccessibleHandler\__init__.pyc", line 577, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 75, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 109, in __call__
  File "appModules\powerpnt.pyc", line 1347, in chooseNVDAObjectOverlayClasses
  File "appModules\powerpnt.pyc", line 1333, in fetchPpObjectModel
  File "appModules\powerpnt.pyc", line 1327, in _fetchPpObjectModelHelper
  File "appModules\powerpnt.pyc", line 1297, in _getPpObjectModelFromROT
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 86, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 168, in __getattr__
  File "comtypes\automation.pyc", line 809, in _invoke
  File "comtypes\automation.pyc", line 462, in _get_value
  File "comtypes\client\dynamic.pyc", line 32, in Dispatch
  File "comtypes\client\lazybind.pyc", line 112, in __init__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 31, in __call__

DEBUGWARNING - NVDAObjects.__call__ (23:04:56.758) - MainThread (13400):
Exception in chooseNVDAObjectOverlayClasses for AppModule(powerpnt, appName='powerpnt', processID=22524)
Traceback (most recent call last):
  File "NVDAObjects\__init__.pyc", line 109, in __call__
  File "appModules\powerpnt.pyc", line 1347, in chooseNVDAObjectOverlayClasses
  File "appModules\powerpnt.pyc", line 1333, in fetchPpObjectModel
  File "appModules\powerpnt.pyc", line 1327, in _fetchPpObjectModelHelper
  File "appModules\powerpnt.pyc", line 1297, in _getPpObjectModelFromROT
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 86, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 168, in __getattr__
  File "comtypes\automation.pyc", line 809, in _invoke
  File "comtypes\automation.pyc", line 462, in _get_value
  File "comtypes\client\dynamic.pyc", line 32, in Dispatch
  File "comtypes\client\lazybind.pyc", line 112, in __init__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 38, in __call__
exceptions.CallCancelled: COM call cancelled
IO - speech.speech.speak (23:04:56.861) - MainThread (13400):
Speaking ['Fenster', CancellableSpeech (still valid)]
DEBUGWARNING - eventHandler.executeEvent (23:04:56.872) - MainThread (13400):
error executing event: gainFocus on <NVDAObjects.IAccessible.ContentGenericClient object at 0x089CC450> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\__init__.pyc", line 1296, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1147, in reportFocus
  File "speech\speech.pyc", line 626, in speakObject
  File "speech\speech.pyc", line 665, in getObjectSpeech
  File "speech\speech.pyc", line 521, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1941, in _get_value
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\window\__init__.pyc", line 205, in _get_displayText
  File "displayModel.pyc", line 298, in __init__
  File "textInfos\offsets.pyc", line 482, in __init__
  File "displayModel.pyc", line 420, in _getStoryLength
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "displayModel.pyc", line 325, in _get__storyFieldsAndRects
  File "displayModel.pyc", line 202, in getWindowTextInRect
  File "watchdog.pyc", line 413, in cancellableExecute
  File "watchdog.pyc", line 346, in execute
exceptions.CallCancelled
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (23:04:56.903) - MainThread (13400):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (23:04:56.903) - MainThread (13400):
description IA2Attribute is: 
IO - speech.speech.speak (23:04:56.903) - MainThread (13400):
Speaking ['Python 3.11 regression: Garbage handler errors occur much more frequently · Issue #15634 · nvaccess/nvda – Mozilla Firefox', CancellableSpeech (still valid)]
INFO - watchdog.waitForFreezeRecovery (23:04:56.915) - watchdog (12448):
Recovered from freeze after 0.7093876000144519 seconds.
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (23:04:57.024) - MainThread (13400):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (23:04:57.024) - MainThread (13400):
description IA2Attribute is: 
IO - speech.speech.speak (23:04:57.026) - MainThread (13400):
Speaking ['Python 3.11 regression: Garbage handler errors occur much more frequently · Issue #15634 · nvaccess/nvda', 'Dokument', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (23:04:57.028) - MainThread (13400):
Getting mozilla descriptionFrom
DEBUG - NVDAObjects.IAccessible.mozilla.Mozilla._get_descriptionFrom (23:04:57.028) - MainThread (13400):
description IA2Attribute is: 
IO - speech.speech.speak (23:04:57.030) - MainThread (13400):
Speaking ['Comment body', 'Eingabefeld', 'erforderlich', 'ungültiger Eintrag', 'mehrzeilig', CancellableSpeech (still valid), 'Leave a comment', CancellableSpeech (still valid), 'Leer']
IO - inputCore.InputManager.executeGesture (23:04:59.006) - winInputHook (17116):
Input: kb(laptop):escape
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:04:59.065) - Dummy-1 (10472):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
_ctypes.COMError: (-2147418113, 'Schwerwiegender Fehler', (None, None, None, 0, None))
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:04:59.081) - Dummy-1 (10472):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
_ctypes.COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:04:59.081) - Dummy-1 (10472):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
_ctypes.COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:04:59.082) - Dummy-1 (10472):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
_ctypes.COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:04:59.082) - Dummy-1 (10472):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
_ctypes.COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
DEBUG - appModuleHandler.cleanup (23:04:59.087) - MainThread (13400):
application powerpnt closed
```

### Expected behavior:
No CTypes Com errors when closing powerpoint and no freeze.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29726,a207ad54 (2024.1.0.29726)

#### Windows version:
Windows 11 22H2

#### Name and version of other software in use when reproducing the issue:
Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64 Bit

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
I also get a lot of debug warnings related to the poweropint app module saying that NVDA cannot get the slideshow window. I guess the appmodule needs a revisit as well.

**Comment by seanbudd** [comment]
Is this a recent regression?

**Comment by Adriani90** [comment]
I couldn't reproduce this reliably for a while, closing for now.
