### ISSUE TITLE
NVDA crashes when a Visiobraille/Baum 440 display is disconnected

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#15705]
NVDA crashes when the Visiobraille display is disconnected. This display uses a HID protocol via the Baum driver. NVDA crashes and watchdog does not kick in to restart it. From the log it is unlcear why this crash is happening.

### Steps to reproduce:
1. Unplug the braille display

### Actual behavior:

* NVDA crashes

### Expected behavior:

* NVDA switches to no braille and keeps running normally

### NVDA logs, crash dumps and other attachments:
Log:
```
IO - speech.speech.speak (11:34:27.512) - MainThread (23584):
Speaking ['Bureaublad', 'lijst', CancellableSpeech (still valid)]
IO - speech.speech.speak (11:34:27.515) - MainThread (23584):
Speaking ['Prullenbak', 'niet geselecteerd', '1 van 17', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.NVDAObject._get_placeholder (11:34:27.515) - MainThread (23584):
Potential unimplemented child class: <NVDAObjects.IAccessible.sysListView32.List object at 0x0466F030>
DEBUG - NVDAObjects.NVDAObject._get_placeholder (11:34:27.516) - MainThread (23584):
Potential unimplemented child class: <NVDAObjects.Dynamic_SysListView32EmittingDuplicateFocusEventsListItemIAccessible object at 0x0466FA10>
IO - braille.BrailleBuffer.update (11:34:27.516) - MainThread (23584):
Braille regions text: ['Bureaublad lst ', 'Prullenbak nsel 1 van 17']
IO - braille.BrailleHandler.update (11:34:27.516) - MainThread (23584):
Braille window dots: 127 136 1235 15 1 136 12 123 1 145 - 123 234 2345 - 12347 1235 136 123 123 15 1345 12 1 13 - 1345 234 15 123 - 2 - 1236 1 1345 - 2 2356
DEBUG - hwIo.base.IoBase.write (11:34:27.517) - hwIo.ioThread.IoThread (8):
Write: b"\x01C%\x17\x11\x01%\x03\x07\x01\x19\x00\x07\x0e\x1e\x00O\x17%\x07\x07\x11\x1d\x03\x01\x05\x00\x1d\x0e\x11\x07\x00\x02\x00'\x01\x1d\x00\x026\x00"
ERROR - hwIo.ioThread._internalCompletionRoutine (11:34:30.280) - hwIo.ioThread.IoThread (8):
Error in overlapped completion routine <bound method IoBase._ioDone of <hwIo.hid.Hid object at 0x06575C50>>
Traceback (most recent call last):
  File "hwIo\ioThread.pyc", line 142, in _internalCompletionRoutine
  File "hwIo\base.pyc", line 194, in _ioDone
OSError: [WinError 1167] Het apparaat is niet aangesloten.
IO - inputCore.InputManager.executeGesture (11:34:33.393) - winInputHook (15108):
Input: kb(laptop):downArrow
IO - speech.speech.speak (11:34:33.414) - MainThread (23584):
Speaking ['ABBYY FineReader 14', '2 van 17', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.NVDAObject._get_placeholder (11:34:33.414) - MainThread (23584):
Potential unimplemented child class: <NVDAObjects.Dynamic_SysListView32EmittingDuplicateFocusEventsListItemIAccessible object at 0x083E5510>
IO - braille.BrailleBuffer.update (11:34:33.414) - MainThread (23584):
Braille regions text: ['Bureaublad lst ', 'ABBYY FineReader 14 2 van 17']
IO - braille.BrailleHandler.update (11:34:33.414) - MainThread (23584):
Braille window dots: 17 127 127 134567 134567 - 1247 24 1345 15 12357 15 1 145 15 1235 - 2 256 - 23 - 1236 1 1345 - 2 2356
DEBUG - hwIo.base.IoBase.write (11:34:33.414) - hwIo.ioThread.IoThread (8):
Write: b"\x01ACC}}\x00K\n\x1d\x11W\x11\x01\x19\x11\x17\x00\x022\x00\x06\x00'\x01\x1d\x00\x026\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
DEBUG - hwIo.base.IoBase.write (11:34:33.414) - hwIo.ioThread.IoThread (8):
Write failed: [WinError 1167] Het apparaat is niet aangesloten.
ERROR - braille.BrailleHandler._bgThreadExecutor (11:34:33.420) - hwIo.ioThread.IoThread (8):
Error displaying cells. Disabling display
Traceback (most recent call last):
  File "braille.pyc", line 2663, in _bgThreadExecutor
  File "brailleDisplayDrivers\baum.pyc", line 231, in display
  File "brailleDisplayDrivers\baum.pyc", line 154, in _sendRequest
  File "hwIo\base.pyc", line 144, in write
OSError: [WinError 1167] Het apparaat is niet aangesloten.
ERROR - braille.BrailleHandler.handleDisplayUnavailable (11:34:33.420) - hwIo.ioThread.IoThread (8):
Braille display unavailable. Disabling
Traceback (most recent call last):
  File "braille.pyc", line 2663, in _bgThreadExecutor
  File "brailleDisplayDrivers\baum.pyc", line 231, in display
  File "brailleDisplayDrivers\baum.pyc", line 154, in _sendRequest
  File "hwIo\base.pyc", line 144, in write
OSError: [WinError 1167] Het apparaat is niet aangesloten.
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (11:34:33.420) - hwIo.ioThread.IoThread (8):
registering pre_configSave action: <class 'brailleDisplayDrivers.noBraille.BrailleDisplayDriver'>
DEBUG - braille.BrailleHandler._switchDisplay (11:34:33.420) - hwIo.ioThread.IoThread (8):
Switching braille display from 'baum' to 'noBraille'
DEBUG - hwIo.base.IoBase.write (11:34:33.420) - hwIo.ioThread.IoThread (8):
Write: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG - hwIo.base.IoBase.write (11:34:33.420) - hwIo.ioThread.IoThread (8):
Write failed: [WinError 1167] Het apparaat is niet aangesloten.
ERROR - braille.BrailleDisplayDriver.terminate (11:34:33.420) - hwIo.ioThread.IoThread (8):
Display driver BrailleDisplayDriver('baum', numCells=40) failed to display while terminating.
Traceback (most recent call last):
  File "braille.pyc", line 2663, in _bgThreadExecutor
  File "brailleDisplayDrivers\baum.pyc", line 231, in display
  File "brailleDisplayDrivers\baum.pyc", line 154, in _sendRequest
  File "hwIo\base.pyc", line 144, in write
OSError: [WinError 1167] Het apparaat is niet aangesloten.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "braille.pyc", line 2819, in terminate
  File "brailleDisplayDrivers\baum.pyc", line 231, in display
  File "brailleDisplayDrivers\baum.pyc", line 154, in _sendRequest
  File "hwIo\base.pyc", line 144, in write
OSError: [WinError 1167] Het apparaat is niet aangesloten.
DEBUG - hwIo.base.IoBase.write (11:34:33.420) - hwIo.ioThread.IoThread (8):
Write: b'\x15\x00'
DEBUG - hwIo.base.IoBase.write (11:34:33.420) - hwIo.ioThread.IoThread (8):
Write failed: [WinError 1167] Het apparaat is niet aangesloten.
DEBUG - hwIo.base.IoBase.close (11:34:33.420) - hwIo.ioThread.IoThread (8):
Closing
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (11:34:33.425) - hwIo.ioThread.IoThread (8):
loading braille noBraille
INFO - braille.BrailleHandler._setDisplay (11:34:33.425) - hwIo.ioThread.IoThread (8):
Loaded braille display driver 'noBraille', current display has 0 cells.
DEBUG - hwIo.base.IoBase.close (11:34:33.425) - hwIo.ioThread.IoThread (8):
Closing
DEBUG - hwPortUtils.listUsbDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
'VID_04F2&PID_B6BF'
DEBUG - hwPortUtils.listUsbDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
'VID_0BDA&PID_B00C'
DEBUG - hwPortUtils.listUsbDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
'VID_06CB&PID_00F0'
DEBUG - hwPortUtils.listUsbDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
Finished listing USB devices
DEBUG - hwPortUtils.listComPorts (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
Finished listing com ports
DEBUG - hwPortUtils.listHidDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
{'hardwareID': 'HID\\VEN_SYNA&DEV_30D5&Col01', 'devicePath': '\\\\?\\hid#syna30d5&col01#4&76c4de1&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'provider': None}
DEBUG - hwPortUtils.listHidDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
{'hardwareID': 'HID\\VEN_SYNA&DEV_30D5&Col02', 'devicePath': '\\\\?\\hid#syna30d5&col02#4&76c4de1&1&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'provider': None}
DEBUG - hwPortUtils.listHidDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
{'hardwareID': 'HID\\VEN_HPQ&DEV_6001', 'devicePath': '\\\\?\\hid#hpq6001#3&9489f59&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'provider': None}
DEBUG - hwPortUtils.listHidDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
{'hardwareID': 'HID\\VEN_SYNA&DEV_30D5&Col03', 'devicePath': '\\\\?\\hid#syna30d5&col03#4&76c4de1&1&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'provider': None}
DEBUG - hwPortUtils.listHidDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
{'hardwareID': 'HID\\VEN_SYNA&DEV_30D5&Col04', 'devicePath': '\\\\?\\hid#syna30d5&col04#4&76c4de1&1&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'provider': None}
DEBUG - hwPortUtils.listHidDevices (11:34:33.425) - ThreadPoolExecutor-1_0 (12504):
Finished listing HID devices
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (11:34:33.437) - MainThread (23584):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (11:34:33.437) - MainThread (23584):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (11:34:33.437) - MainThread (23584):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1600, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1515, in _get__IA2Relations
NotImplementedError

```

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.2
#### Windows version:
Windows 11 22H2 build 22621
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this works correctly in 2023.1 and alpha-29670,d0614df6 (2024.1.0.29670), but fails in 2023.3RC2.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
cc @leonardder

**Comment by leonardder** [comment]
I'm pretty sure this works again properly because 2024.1 alpha changes strong to weak references for APC functions.

**Comment by seanbudd** [comment]
@bramd - can you confirm this is fixed in alpha?

**Comment by seanbudd** [comment]
Ah I see in the issue description that this works in alpha. Closing as fixed.
