### ISSUE TITLE
In some cases, downloading add-ons from the add-on store and performing installation will not install successfully.

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15796]
### Steps to reproduce:
1. In the Available Add-ons tab, select an add-on to install
2. Wait for the add-on download to complete
3. Press ESC.
4. NVDA asks if you want to install it, click Y.
### Actual behavior:
Show "Installing", No matter how long you wait, nothing will change.
### Expected behavior:
Execute the add-on installation process and restart.
### NVDA logs, crash dumps and other attachments:
```log
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListItemVM.status (11:31:44.751) - MainThread (10780):
addon status change: NVDACNMirror-stable: status: AvailableAddonStatus.INSTALLING
DEBUG - gui._addonStoreGui.viewModels.store.AddonStoreVM._doInstall (11:31:44.751) - MainThread (10780):
NVDACNMirror-stable status: AvailableAddonStatus.INSTALLING
ERROR - unhandled exception (11:31:44.751) - MainThread (10780):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\storeDialog.pyc", line 246, in onClose
  File "gui\_addonStoreGui\viewModels\store.pyc", line 356, in installPending
  File "gui\_addonStoreGui\viewModels\store.pyc", line 366, in _doInstall
  File "_addonStore\install.pyc", line 84, in installAddon
  File "_addonStore\install.pyc", line 39, in _getAddonBundleToInstallIfValid
  File "addonHandler\__init__.pyc", line 793, in __init__
  File "zipfile.pyc", line 1240, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cary\\AppData\\Roaming\\nvda\\addonStore\\_dl\\NVDACNMirror-0.5.2.nvda-addon'
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM._itemDataUpdated (11:31:44.761) - MainThread (10780):
Item updated: AddonListItemVM: NVDACNMirror-stable, AvailableAddonStatus.INSTALLING
DEBUG - gui._addonStoreGui.viewModels.addonList.AddonListVM._itemDataUpdated (11:31:44.761) - MainThread (10780):
Notifying of update
DEBUG - gui._addonStoreGui.controls.addonList.AddonVirtualList._itemDataUpdated (11:31:44.797) - MainThread (10780):
index: 55
IO - inputCore.InputManager.executeGesture (11:31:45.090) - winInputHook (10580):
Input: kb(laptop):tab
IO - tones.beep (11:31:45.744) - MainThread (10780):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speech.speak (11:31:45.745) - MainThread (10780):
Speaking ['请等待']
IO - tones.beep (11:31:45.858) - MainThread (10780):
Beep at pitch 110.0, for 40 ms, left volume 50, right volume 50
IO - speech.speech.speak (11:31:45.859) - MainThread (10780):
Speaking ['百分之 0']
```
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.3
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3448
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

**Comment by Brian1Gaff** [comment]
Would this be certain specific add ons? If it is then going to the authors page might help resolve it. I'm pretty certain oddities like this are  due to a corrupted file somewhere used to store the status of an add on. 

Does the same thing happen with the same add ons with a clean portable copy?
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message -----
