### ISSUE TITLE
Congelamento do NVDA no whatsapp desktop

### ISSUE THREAD

**Issue by patrick-barboza** [nvaccess/nvda#15813]
Ao utilizarmos o NVDA no whatsapp Desktop, e um áudio de uma conversa qualquer for reproduzido, por breves segundos o NVDA congela. Caso seja pressionado uma tecla ou mais de uma, o NVDA fica totalmente preso, tendo que reiniciá-lo. O seguinte registro foi gerado em meu log:
error executing event: UIA_controllerFor on <NVDAObjects.Dynamic_StartMenuSearchFieldSearchFieldEditableTextWithAutoSelectDetectionUIA object at 0x086C51F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 325, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\UIA\__init__.pyc", line 2094, in event_UIA_controllerFor
  File "NVDAObjects\behaviors.pyc", line 195, in event_controllerForChange
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 2088, in _get_controllerFor
  File "NVDAObjects\__init__.pyc", line 100, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 1081, in findOverlayClasses
AttributeError: module 'NVDAObjects.UIA.spartanEdge' has no attribute 'EdgeHTMLRootContainer'
ERROR - unhandled exception (09:34:49.405) - MainThread (5844):
Traceback (most recent call last):
  File "core.pyc", line 770, in Notify
  File "baseObject.pyc", line 181, in invalidateCaches
  File "weakref.pyc", line 451, in keys
RuntimeError: dictionary changed size during iteration
INFO - watchdog.waitForFreezeRecovery (09:34:59.568) - watchdog (7648):
Starting freeze recovery after 10.15528440000071 seconds.
ERROR - watchdog.waitForFreezeRecovery (09:35:14.612) - watchdog (7648):
Core frozen in stack! (25.19843200000014 seconds)
INFO - watchdog.waitForFreezeRecovery (09:35:14.617) - watchdog (7648):
Listing stacks for Python threads:
Python stack for thread 6660 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x0871DBE8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 7648 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 186, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 7264 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6736 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6060 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6188 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 5844 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 814, in main
  File "wx\core.pyc", line 2237, in MainLoop

ERROR - watchdog.waitForFreezeRecovery (09:35:29.613) - watchdog (7648):
Core frozen in stack! (40.19975140000042 seconds)
INFO - watchdog.waitForFreezeRecovery (09:35:29.618) - watchdog (7648):
Listing stacks for Python threads:
Python stack for thread 6660 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x0871DBE8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 7648 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 186, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 7264 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6736 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6060 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6188 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 5844 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 814, in main
  File "wx\core.pyc", line 2237, in MainLoop

ERROR - watchdog.waitForFreezeRecovery (09:35:44.650) - watchdog (7648):
Core frozen in stack! (55.23675810000077 seconds)
INFO - watchdog.waitForFreezeRecovery (09:35:44.655) - watchdog (7648):
Listing stacks for Python threads:
Python stack for thread 6660 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x0871DBE8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 7648 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 186, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 7264 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6736 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6060 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6188 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 5844 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 814, in main
  File "wx\core.pyc", line 2237, in MainLoop

ERROR - watchdog.waitForFreezeRecovery (09:35:59.686) - watchdog (7648):
Core frozen in stack! (70.27304920000006 seconds)
INFO - watchdog.waitForFreezeRecovery (09:35:59.691) - watchdog (7648):
Listing stacks for Python threads:
Python stack for thread 6660 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x0871DBE8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 7648 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 186, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 7264 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6736 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6060 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6188 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 5844 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 814, in main
  File "wx\core.pyc", line 2237, in MainLoop

ERROR - watchdog.waitForFreezeRecovery (09:36:14.699) - watchdog (7648):
Core frozen in stack! (85.28553830000055 seconds)
INFO - watchdog.waitForFreezeRecovery (09:36:14.704) - watchdog (7648):
Listing stacks for Python threads:
Python stack for thread 6660 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x0871DBE8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 7648 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 186, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 7264 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6736 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6060 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6188 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 5844 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 814, in main
  File "wx\core.pyc", line 2237, in MainLoop

ERROR - watchdog.waitForFreezeRecovery (09:36:29.723) - watchdog (7648):
Core frozen in stack! (100.30985690000034 seconds)
INFO - watchdog.waitForFreezeRecovery (09:36:29.723) - watchdog (7648):
Listing stacks for Python threads:
Python stack for thread 6660 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x0871DBE8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 7648 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 186, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 7264 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6736 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 522, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6060 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 6188 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 5844 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 814, in main
  File "wx\core.pyc", line 2237, in MainLoop

INFO - core.main (09:36:35.354) - MainThread (5844):
Exiting
INFO - watchdog.waitForFreezeRecovery (09:36:35.379) - watchdog (7648):
Recovered from freeze after 105.96595370000068 seconds.
INFO - config.ConfigManager.save (09:36:35.744) - MainThread (5844):
Base configuration saved
INFO - __main__ (09:36:37.155) - MainThread (5844):
NVDA exit

Como é possível ver, tentava de tudo para destravar o NVDA de forma amigável, mas não obtive sucesso.
Fui obrigado a fechá-lo completamente.

**Comment by CyrilleB79** [comment]
This issue has already been reported in #15169.
Closing as duplicate.
