### ISSUE TITLE
Fail to use autocompletion in python console

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#15872]
### Background:
between python version 3.7 and 3.11, change was made by python developers in rlcompleter module, which removed exception handling from attr_match method which was previously suppressing some type of exceptions.

### Steps to reproduce:
Open python console;
Write nav.;
Press Tab key

### Actual behavior:
Different types of exceptions are thrown

### Expected behavior:
Autocompletion should work as expected without throwing exceptions

### NVDA logs, crash dumps and other attachments:
ERROR - unhandled exception (00:57:28.295) - MainThread (11340):
Traceback (most recent call last):
  File "pythonConsole.pyc", line 410, in onInputChar
  File "pythonConsole.pyc", line 335, in complete
  File "pythonConsole.pyc", line 358, in _getCompletions
  File "rlcompleter.pyc", line 92, in complete
  File "rlcompleter.pyc", line 189, in attr_matches
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1052, in _get_labeledBy
TypeError: cannot unpack non-iterable NoneType object

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-30120,8052b68f
#### Windows version:
Windows 11 23H2 (AMD64) build 22631.2715
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Not applicable
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Only applicable to python 3.11 version of nvda
#### If NVDA add-ons are disabled, is your problem still occurring?
Not applicable
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

**Comment by LeonarddeR** [comment]
I had a quick look into this issue and it doesn't seem to be very trivial to fix. The only thing I could think of is copying the logic from `attr_match`, expanding it for our use case.
Actually the change in `attr_match` is pretty smart. When it encounters a `property` type, it just returns the match, i.e. it doesn't evaluate it. However, we're often using baseObject.Getter instead of property, which is in Pythonic terms a non-data descriptor. See [this](https://www.pythontutorial.net/python-oop/python-data-descriptors/) for more info about the difference.
In short, `baseObject.Getter` uses the principle of non-data descriptors to ensure that a getter only property can be overridden. When we'd use `property` instead of `baseObject.Getter`, properties would be read-only. There is now way to make subclasses of `property` a non-data descriptor.
So expanding `attr_match` would mean expanding the isinstance check that checks for instances of `property` with a check for `baseObject.Getter`. This would introduce a change in behavior though, properties that were previously excluded because they raised NotImplementedError will be part of the suggested auto completes. This might or might not be desirable.

**Comment by beqabeqa473** [comment]
Another way could be to just include rlcompleter from python3.7. I
don't think it is good, but at least very easy to do.

On 12/6/23, Leonard de Ruijter ***@***.***> wrote:
> I had a quick look into this issue and it doesn't seem to be very trivial to
> fix. The only thing I could think of is copying the logic from `attr_match`,
> expanding it for our use case.
> Actually the change in `attr_match` is pretty smart. When it encounters a
> `property` type, it just returns the match, i.e. it doesn't evaluate it.
> However, we're often using baseObject.Getter instead of property, which is
> in Pythonic terms a non-data descriptor. See
> [this](https://www.pythontutorial.net/python-oop/python-data-descriptors/)
> for more info about the difference.
> In short, `baseObject.Getter` uses the principle of non-data descriptors to
> ensure that a getter only property can be overridden. When we'd use
> `property` instead of `baseObject.Getter`, properties would be read-only.
> There is now way to make subclasses of `property` a non-data descriptor.
> So expanding `attr_match` would mean expanding the isinstance check that
> checks for instances of `property` with a check for `baseObject.Getter`.
> This would introduce a change in behavior though, properties that were
> previously excluded because they raised NotImplementedError will be part of
> the suggested auto completes. This might or might not be desirable.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15872#issuecomment-1842180746
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by LeonarddeR** [comment]
Related python issue: https://github.com/python/cpython/issues/88915
