### ISSUE TITLE
After exiting NVDA, some DLLs under lib64 are still being used by other processes

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15884]
This problem seems to have been around for a long time. For users who use portable versions on USB drives, it is very frustrating to be told that files are in use whenever they want to safely eject the USB drive

### Steps to reproduce:

1. `scons dist`
2. Do something to make SCons trigger a rebuild of dist, for example `scons -c`.
3. `scons dist`

Or

Create a portable version, then run it and exit, then delete the directory where the portable version is located

### Actual behavior:

py2exe cannot replace files when rebuilding the dist target

```
Add resource PYTHONSCRIPT/1(11153 bytes) to ../dist\nvda_slave.exe
Traceback (most recent call last):
  File "D:\NVDA\nvda\source\setup.py", line 151, in <module>
    freeze(
  File "D:\NVDA\nvda\.venv\Lib\site-packages\py2exe\__init__.py", line 197, in freeze
    builder.build()
  File "D:\NVDA\nvda\.venv\Lib\site-packages\py2exe\runtime.py", line 250, in build
    self.build_exe(target, exe_path, options.libname)
  File "D:\NVDA\nvda\.venv\Lib\site-packages\py2exe\runtime.py", line 380, in build_exe
    with UpdateResources(exe_path, delete_existing=False) as res_writer:
  File "C:\Program Files (x86)\Python311-32\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "D:\NVDA\nvda\.venv\Lib\site-packages\py2exe\resources.py", line 23, in UpdateResources
    _wapi.EndUpdateResourceW(hrscr, False)
  File "D:\NVDA\nvda\.venv\Lib\site-packages\py2exe\_wapi.py", line 10, in BOOL_errcheck
    raise WinError()
OSError: [WinError 110] 系统无法打开指定的设备或文件。
```

Unable to delete the directory where the portable version is located. Possible use case is unable to safely eject the USB drive.

### Expected behavior:

Can complete the operation on the NVDA directory in a timely manner

#### Does the issue still occur after restarting your computer?

Yes, but it is meaningless for this issue

**Comment by lukaszgo1** [comment]
As you mentioned this issue is not new. It occurs because NVDA injects these dll's to another processes, and freeing libraries injected like this is non trivial. I'd suggest to keep this issue open, but label with a P4 or even P5, since it affects only few users, and implementation cost is pretty high.

**Comment by hwf1324** [comment]
Yes, is it possible to copy these dlls to a temporary directory at runtime to alleviate this problem?

**Comment by lukaszgo1** [comment]
Note that injecting DLL's for multiple copies of NVDA to the same process often causes instabilities, or even a crash in case of browsers, so ideally the underlying problem should be addressed.

**Comment by OzancanKaratas** [comment]
This can be fixed by rejecting DLL files when exiting NVDA, but how?

**Comment by hwf1324** [comment]
> I'm curious how other contributors are handling this? Currently I have to restart my computer each time, which frees the files up. Thanks.

You can use some tools to find out what programs these DLLs are being used by, and then manually close them. Of course this isn't safe, so what I usually do is log off and log back into my Windows account, which is much faster than restarting the computer.

**Comment by SaschaCowley** [comment]
I tend to just kill the offending processes (typically Windows Explorer and Firefox) with [File Locksmith](https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith)

**Comment by tspivey** [comment]
I was trying to figure out why `nvdaHelperRemote.dll ` was not being unloaded from Windows Explorer after exiting NVDA.

Looking at `nvdaHelper/remote/injection.cpp` in `inprocMgrThreadFunc`, I noticed that `tempHandle` is being created but not freed.

From the [documentation for GetModuleHandleEx](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandleexw):
> If the module's reference count is incremented, the caller must use the FreeLibrary function to decrement the reference count when the module handle is no longer needed.

Could this be what's keeping it loaded?

**Comment by ABuffEr** [comment]
> I was trying to figure out why `nvdaHelperRemote.dll ` was not being unloaded from Windows Explorer after exiting NVDA.
> Looking at `nvdaHelper/remote/injection.cpp` in `inprocMgrThreadFunc`, I noticed that `tempHandle` is being created but not freed.

Could this be the reason of progressive explorer.exe slowdown?

**Comment by OzancanKaratas** [comment]
@tspivey can you implement this in a new pull request? I can do the tests before it is merged.

**Comment by OzancanKaratas** [comment]
It can also be used [FreeLibraryAndExitThread](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-freelibraryandexitthread) for this problem but I'm not sure which one should be used. If this issue is fixed, some update problems disappears. @michaelDCurran, can you implement one of these functions?

**Comment by Adriani90** [comment]
Can anyone confirm whether this is also an issue with the last 64bit alpha?

**Comment by SaschaCowley** [comment]
Yes, this is still the case

**Comment by amirmahdifard** [comment]
cc @jcsteh lastly i'm also fasing this issue, and because I don't want to restart my computer, i create portable versions in diffrent folders as long as my computer is not restarted until the end of the day. I know you are dealling with cpp code of nvda, so may be take a look

**Comment by jcsteh** [comment]
> Looking at nvdaHelper/remote/injection.cpp in inprocMgrThreadFunc, I noticed that tempHandle is being created but not freed.

The code does call `FreeLibraryAndExitThread(dllHandle,0)` and dllHandle == tempHandle. It'd be clearer to free tempHandle instead, but that's purely cosmetic, since they're equal. So I don't think that's the source of the problem.

This doesn't always happen. My best guess is that something in the process is still holding a reference to one of the COM proxies we register. Even though we unregister those and do our best to ensure they are unloaded, we can't force callers to release them, and we can't simply force unload the dll while references are being held without crashing the process. That said, there's a bunch of COM proxy cleanup being done in #20301 and a few extra bits and pieces to be submitted once we're sure that's stable, so it's possible something there might help here.

**Comment by amirmahdifard** [comment]
i'm wundering if @michaelDCurran 's merged pr regarding the com registration cleanup also fixed this issue or not, because this issue becomes annoying when I want to test several patches without restarting the computer. Nvda portable started in a folder and exited, makes that folder completely useless until the computer is restarted. Even once I tryed to delete the folder and only the inuse file remaned, but my computer was acting strangely until i restarted my computer, even with my main installed nvda. For example, anywhere of my file explorer when I deleted/moved/copyed/pasted/created a file or folder, my file explorer didn't refresh and it was shoing the look as i didn't move anything, i had to refresh my file explorer or close and reopen it. So i think that, may be, there is something that all running copys of nvda are sharing with each other. It looks very hard to search very deap in the codebase and find what's causing this, but if found, it would be the best of both worlds.

**Comment by amirmahdifard** [comment]
I just tryed to reproduce this issue with laytist master after @michaelDCurran 's pr has been merged, And sadly it doesn't solv this problem. it stil says file inuse for these 2 files. IAccessible2proxy.dll and ISimpleDOM.dll. It doesn't releace them.

**Comment by jcsteh** [comment]
Unfortunately, I'm not really surprised this isn't fixed. As I noted above:

> Even though we unregister those and do our best to ensure they are unloaded, we can't force callers to release them, and we can't simply force unload the dll while references are being held without crashing the process.

We're somewhat at the behest of the Windows COM marshaler here, unfortunately.

**Comment by jcsteh** [comment]
What does surprise me a little is that I don't understand why anything in Explorer would be using IA2 or ISimpleDOM interfaces. So either the COM marshaler holds onto proxies eagerly for a while or something is indeed holding references to those interfaces, which would be weird.

If we knew for certain that nothing would ever use IA2 in Explorer, we could consider never registering those interfaces at all in Explorer. I'm fairly certain Microsoft themselves never use IA2 in Explorer, but the question is whether there are any shell extensions that do. I'm not aware of any, but that doesn't mean they don't exist.

**Comment by amirmahdifard** [comment]
@jcsteh can't you keep track of what is holding this file? but the question is why it becomes in use when nvda is started but it doesn't releaced when nvda is exited? A full look would be in these 2 paths, and we only need to understand what holdes these dlls that they do holde, but they don't releace. May be asking an ai scan to scan the hole project would be a good idea. I don't know, i'm just mentioning every solootion reaches to my minde to may be help to fixing this issue.

**Comment by jcsteh** [comment]
I'd be interested to know whether the dll eventually gets released after, say, 10 minutes. No suggesting it as a solution, just a data point. I know that the Windows COM marshaler has some inbuilt timeouts of several minutes before it releases certain things.

**Comment by SaschaCowley** [comment]
@amirmahdifard 
> can't you keep track of what is holding this file?

That is not the problem. You can fairly easily check which applications are holding the DLLs with something like File Locksmith.

> but the question is why it becomes in use when nvda is started but it doesn't releaced when nvda is exited?

As already explained in https://github.com/nvaccess/nvda/issues/15884#issuecomment-4751980551

> Even though we unregister those and do our best to ensure they are unloaded, we can't force callers to release them, and we can't simply force unload the dll while references are being held without crashing the process.

It might help to think of it this way: When we inject these DLLs into a process, we are giving it a toolbox and tools to do work for us. When NVDA is exiting, we ask it to pack up the tools and put the tool box back (free the DLL), but we can't force it to do anything. If we were to force it to free the DLL, we would essentially be yanking all of the tools away from it, and if it's using any of them at the time, this could leave it in a broken state (whatever it's doing might be half complete, and it's got no way of completing it, and no way of cleaning up). So the only way to force free the DLL is to terminate the process.

**Comment by jcsteh** [comment]
To continue the analogy, the worst part is that Windows doesn't give us any mechanism to ask "who is using the tools in my toolbox?" Windows might just be holding onto the tools because it thinks someone might need them soon... or someone might legitimately be using the tools. We can't tell the difference; there just isn't a mechanism for that. It might be possible to figure it out with some very deep debugging (e.g. somehow instrumenting the COM proxy dlls to debug break or log a stack trace for every single AddRef call), but it would likely involve disassembling a bunch of Windows code even once we worked out who the caller was in order to figure out why it's calling.

In any case, the best thing we can probably do here is continue to gather data points that might allow someone to correlate the culprit.

**Comment by amirmahdifard** [comment]
@jcsteh you wundered if it's been releaced after some time?
sadly no. My computer is on until the end of the day, so when I try to reproduce this several hours after that nvda process is exited and the dll's are stil inuse.
