### ISSUE TITLE
Python console: Auto complete stalls for NotImplementedError

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#15883]
### Steps to reproduce:
1. Focus a desktop icon
2. Open a python console with nvda+ctrl+z
3. type: " `nav.tr`

### Actual behavior:
```log
ERROR - unhandled exception (19:05:32.472) - MainThread (4356):
Traceback (most recent call last):
  File "pythonConsole.pyc", line 410, in onInputChar
  File "pythonConsole.pyc", line 335, in complete
  File "pythonConsole.pyc", line 358, in _getCompletions
  File "rlcompleter.pyc", line 92, in complete
  File "rlcompleter.pyc", line 189, in attr_matches
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 400, in _get_treeInterceptorClass
NotImplementedError
```

### Expected behavior:
Auto complete expands to nav.treeInterceptor

#### NVDA installed/portable/running from source:
Installed/source

#### NVDA version:
alpha-30192,9cf92519

#### Windows version:
Windows 11 23H2

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this problem doesn't occur in version 2023.3

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by LeonarddeR** [comment]
Duplicate of #15872
