### ISSUE TITLE
Native selection mode: image links are not copied

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15909]
### Steps to reproduce:
1. With NVDA running, use this piece of html and open it in Firefox:
```
<!DOCTYPE html>
<html>
<body>
<h2>Image as a Link</h2>
<p>The image below is a link. Try to click on it.</p>
<a href="default.asp"><img src="smiley.gif" alt="HTML tutorial" style="width:42px;height:42px;"></a>
</body>
</html>
```
2. Use the native selection mode to copy the image link to the clipboard and paste it into a MS Word document for example
3. Alternatively copy the image link on this Github page displayed for every user, press i.e. shift+g to land on the image link with my user name

### Actual behavior:
NVDA does not copy the link. Sometimes it copies only the image, if there is one, or just the label of the link.
In step 2, NVDA does not copy anything
In step 3 NVDA copies only the label of the link as plain text
If the image link contains n image such as a logo, sometimes NVDA copies only the grafic with the label of the link, but not the link itself.

### Expected behavior:
NVDA should copy label, image and link role on an image link.

### NVDA logs, crash dumps and other attachments:
n/a
#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-30299,4519b893 (2024.1.0.30299)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
Firefox 120

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by XLTechie** [comment]
> NVDA should copy label, image and link role on an image link.

To be clear, what, exactly, should be copied given your example?

My understanding is that you should get the same as you would with NVDA turned 
off.

**Comment by Adriani90** [comment]
With NVDA turned off, pasting the image link from my example code in MS Word you get an image with a link behind it, unfortunately NVDA reports this as "slash" sign and you are not aware that this contains an image and a link. However I think this is a different issue.

With NVDA turned on, I get following error when using arrow keys or shift+arrow key after loading my code in the browser with native selection enabled:
```
IO - inputCore.InputManager.executeGesture (23:13:00.215) - winInputHook (16220):
Input: kb(laptop):NVDA+shift+f10
IO - speech.speech.speak (23:13:00.215) - MainThread (3884):
Speaking ['Native app selection mode enabled.']
IO - inputCore.InputManager.executeGesture (23:13:01.212) - winInputHook (16220):
Input: kb(laptop):downArrow
IO - speech.speech.speak (23:13:01.212) - MainThread (3884):
Speaking ['The image below is a link. Try to click on it.']
ERROR - scriptHandler.executeScript (23:13:01.212) - MainThread (3884):
error executing script: <bound method CursorManager.script_moveByLine_forward of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x0885A230>> with gesture 'down arrow'
Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 722, in clearAppSelection
  File "comtypes\__init__.pyc", line 831, in QueryInterface
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 31, in __call__
_ctypes.COMError: (-2147467262, 'Schnittstelle nicht unterstützt', (None, None, None, 0, None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 275, in script_moveByLine_forward
  File "cursorManager.pyc", line 175, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1404, in _set_selection
  File "cursorManager.pyc", line 133, in _set_selection
  File "textInfos\offsets.pyc", line 678, in updateSelection
  File "virtualBuffers\gecko_ia2.pyc", line 56, in _setSelectionOffsets
  File "virtualBuffers\gecko_ia2.pyc", line 726, in clearAppSelection
NotImplementedError
```


It seems on this Github page though I can copy the image links, and they are displayed in MS Word as graficc but the link behind it is not reported by NVDA due to lack of support for this feature. I did this for the participants image links.

I attached a word file with both scenarios, (I) Github page which seems to work, and (II) example code from the description with the expected behavior for the image link copied when NVDA was turned off.
[image links.docx](https://github.com/nvaccess/nvda/files/13653843/image.links.docx)

**Comment by Adriani90** [comment]
cc: @michaelDCurran

**Comment by seanbudd** [comment]
Cc @jcsteh - this is a firefox issue

**Comment by jcsteh** [comment]
1. I can't reproduce your COMError issue. Can you still reproduce that?
2. Your HTML code is invalid because both the link URL and the image URL are invalid. I'd try testing with something like this:
    `data:text/html,before <a href="https://example.com/"><img alt="placeholder" src="https://via.placeholder.com/10x10"></a> after`
3. I think there is a Firefox bug here where copying just an image seems to fail. I need to look into this. However, if your selection includes something before and after the image, it should work.

**Comment by Adriani90** [comment]
Re 1. the error is not reproducible anymore after running the COM registration fixing tool...

Re 2. It seems putting an "after" after my testing code made it work as well. The image shown as slash sign in MS Word is copied indeed, it seems image links with invalid URLs are being displayed as a kind of empty place holder in MS Word visibly but NVDA reads it as slash.
Your valid code is indeed displayed as propper grafic in word. So it seems both cases work if there is something before and after the image link.

Re 3. I think we can narrow the bug to this behavior. So we can close this as soon as there is a solution in Firefox for it. Are you planning to open a bug on the Bugzilla for it?

**Comment by jcsteh** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1869971

**Comment by jcsteh** [comment]
This is fixed for Firefox 140 (currently nightly).
