### ISSUE TITLE
Add ability to search for objects in the window where the focus or navigator object is located

### ISSUE THREAD

**Issue by Emil-18** [nvaccess/nvda#16048]
### Is your feature request related to a problem? Please describe.
It can be extremely time consuming to locate an object in an unfamiliar application, specialy if you have to use object navigation.
### Describe the solution you'd like
Add ability to list up in a dialog all objects in the window with focus/ where the navigator object is located. The user should be able to select the type of object they want to find, e.g button, list, all objects, etc. I think that the list always should display all objects when it is opened. Add a search field to filter the list, and move the navigator object to the object the user chooses from the list. I think the user should have the possibility to move the navigator object to the selected object without closing the dialog, so they can explore the areas around the object to find out if it is actualy the object they want.
I think it is best to use recursiveDescendants to go through all the objects, but sometimes, when there are too many IAccessible objects in a window, I get the following error
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "NVDAObjects\__init__.pyc", line 870, in _get_recursiveDescendants
  File "NVDAObjects\__init__.pyc", line 870, in _get_recursiveDescendants
  File "NVDAObjects\__init__.pyc", line 870, in _get_recursiveDescendants
  [Previous line repeated 13 more times]
  File "NVDAObjects\__init__.pyc", line 868, in _get_recursiveDescendants
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1157, in _get_children
  File "NVDAObjects\__init__.pyc", line 100, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 617, in findOverlayClasses
  File "comtypes\__init__.pyc", line 1231, in QueryService
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 39, in __call__
exceptions.CallCancelled: COM call cancelled
I also think that there should be an option in the advanced settings panel that makes NVDA use UIAutomation to list the objects via the FindAll method, as it is significantly faster then recursiveDescendants, and don't raise the previous error. The disadvantages by using UIAutomation is that it don't work with java applications, and it can result in errors when creating an NVDAObject from a none native UIAElement. A workaround could be to translate the UIAElement to an IAccessibleObject when it is none native.
### Additional context
recursiveDescendants is able to find IAccessibleObjects in areas where NVDA normally don't work with object navigation do to bad accNavigate implementation. Screen readers that use UIAutomation to object navigate, also works in these areas. If this is implemented, NVDAUsers will be able to use applications/areas of applications that was previously completely inaccessible/very dificult to use with NVDA.

**Comment by josephsl** [comment]
Hi, isn’t there an add-on that can do this? Thanks.

**Comment by Emil-18** [comment]
@josephsl There are 2 that I know of, obj inspector and NVDA global commands extension. Obj inspector is seamingly designed more for developers, plus that you can't move the navigator object to the selected item. The list item names start with the role name, so you can't use first letter navigation to quickly locate an item. NVDA global commands extension lacks a search field, and it is very slow to list up a lot of objects at once.
If it is added into NVDA core, it will be available to a lot more users, and I think that a large amount of people will find this feature useful.

**Comment by josephsl** [comment]
Hi, that’s what I thought (on add-ons). As for UIA strategy, keep in mind that not all UIA server-side implementations are good, and NVDA itself guards against instantiating certain objects based on class names (UIA handler lists some of them). Thanks.

**Comment by lukaszgo1** [comment]
While this feature sonuds pretty nice it would also be helpful to:
- Open a separate issue about `recursiveDescendants` failing with a specific example, as this should be fixed regardless
- Provide some examples of applications where `recursiveDescendants` allows to navigate whereas object navigation does not, as these should ideally be fixed

**Comment by Emil-18** [comment]
@lukaszgo1 some examples include:
* Situations where an IAccessible object includes other windows, as well as it's own sub items, such as the open button in combo boxes that includes an edit box, and the column headers in SysListview32 controls.
* an old version of Teams.
* zoom.
* In some windows forms tool bars, such as those found in MySql. When moving past the end, it wraps around to the beginning and vise versa. When moving to a seperator, it don't actualy moves to the seperator, but instead to a window contained inside the toolbar, havent tested with a toolbar that don't contain a window inside it yet.
* Some buttons inside treeview items in MySql.

**Comment by Emil-18** [comment]
I am planning to create a pr that fixes this issue soon. Should I create a new module underneath gui that contains the item list dialog? If not, where should the dialog be located?

**Comment by Adriani90** [comment]
cc: @michaelDCurran, @seanbudd, @gerald-hartig maybe they can respond to the last comment.

**Comment by seanbudd** [comment]
Yes the gui module is the correct place for any dialogs
