### ISSUE TITLE
IAccessible._get_children/_get_recursiveDescendants throws an error when it takes over 10 seconds to complete

### ISSUE THREAD

**Issue by Emil-18** [nvaccess/nvda#16055]
### Steps to reproduce:
* Open a window containing a lot of IAccessible objects, ideally a web page.
* open the python console with ctrl + z and run the following
l = [*fg.recursiveDescendants]
### Actual behavior:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "NVDAObjects\__init__.pyc", line 870, in _get_recursiveDescendants
  File "NVDAObjects\__init__.pyc", line 870, in _get_recursiveDescendants
  File "NVDAObjects\__init__.pyc", line 870, in _get_recursiveDescendants
  [Previous line repeated 7 more times]
  File "NVDAObjects\__init__.pyc", line 868, in _get_recursiveDescendants
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1145, in _get_children
  File "IAccessibleHandler\__init__.pyc", line 1137, in getIAccIdentity
  File "comtypes\__init__.pyc", line 1198, in QueryInterface
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 39, in __call__
exceptions.CallCancelled: COM call cancelled
This happens because watchdog thinks NVDA is frozen, and cancels calls
### Expected behavior:

The function should return normaly and l should be a list containing all the recursiveDescendants of fg
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The behavior is identical in the newest alpha
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
I think the real issue here is a performance issue causing the call to take too long

**Comment by Emil-18** [comment]
@seanbudd I found a workaround, by using wx.CallAfter

**Comment by ABuffEr** [comment]
Hi @Emil-18,
can you explain a bit more?

**Comment by Adriani90** [comment]
cc: @Emil-18 are you still seeing this issue in NVDA 2025.1 Beta? Could you explain more your workaround as requested by @ABuffEr?

**Comment by Emil-18** [comment]
@Adriani90, @ABuffEr Suppose you have a function called getRecursiveDescendence, that takes the object you are going to get all the recursive descendence from as an argument, and returns a list of all the objects found. Then you would use wx.CallLater (not CallAfter) like this.
res = wx.CallLater(0, getRecursiveDecendence, obj)
descendenceObjects = res.GetResult().
Hope this makes sence

**Comment by Emil-18** [comment]
@ABuffEr I found a solution, with no need for a workaround. Use watchdog.Suspender like this
with watchdog.Suspender(): # Disables watchdog while the block is being executed
    fetch the objects
I don't think we can use threads while deeling with IAccessible objects, because it is impossible to get the name inside of a thread that isn't the main thread. At least this was true in NVDA 2023. I have no idea if this is fixed now

**Comment by ABuffEr** [comment]
> watchdog.Suspender(): # Disables watchdog while the block is being executed
> fetch the objects

Thanks for tip.

> I don't think we can use threads while deeling with IAccessible objects, because it is impossible to get the name inside of a thread that isn't the main thread.

Just to document it, usually the trick is to re-acquire the object in current thread (main or not) in some way, like this (list item case):

```
# index is received from the other thread
objForCurThread = getNVDAObjectFromEvent(obj.windowHandle, winUser.OBJID_CLIENT, index)
# then fetch what you want
```

I use this approach with success from years in ColumnsReview.
Hth.
