### ISSUE TITLE
Another log error message is split in many messages

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#16320]
### Steps to reproduce:
Open the Python Console and execute the following line:
`import core;core.callLater(1000, lambda:log.debug('\udc15'))B	E�`

### Actual behavior:
The following error messages are logged:

```
ERROR - stderr (13:35:11.104) - MainThread (11716):
--- Logging error ---
ERROR - stderr (13:35:11.123) - MainThread (11716):
Traceback (most recent call last):
ERROR - stderr (13:35:11.133) - MainThread (11716):
  File "logging\__init__.pyc", line 1113, in emit
ERROR - stderr (13:35:11.140) - MainThread (11716):
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc15' in position 56: surrogates not allowed
ERROR - stderr (13:35:11.148) - MainThread (11716):
Call stack:
ERROR - stderr (13:35:11.155) - MainThread (11716):
  File "nvda.pyw", line 415, in <module>
ERROR - stderr (13:35:11.161) - MainThread (11716):
  File "core.pyc", line 881, in main
ERROR - stderr (13:35:11.168) - MainThread (11716):
  File "wx\core.pyc", line 2262, in MainLoop
ERROR - stderr (13:35:11.175) - MainThread (11716):
  File "core.pyc", line 827, in Notify
ERROR - stderr (13:35:11.183) - MainThread (11716):
  File "queueHandler.pyc", line 97, in pumpAll
ERROR - stderr (13:35:11.189) - MainThread (11716):
  File "queueHandler.pyc", line 64, in flushQueue
ERROR - stderr (13:35:11.196) - MainThread (11716):
  File "<console>", line 1, in <lambda>
ERROR - stderr (13:35:11.202) - MainThread (11716):
  File "logging\__init__.pyc", line 1477, in debug
ERROR - stderr (13:35:11.232) - MainThread (11716):
  File "logHandler.pyc", line 245, in _log
ERROR - stderr (13:35:11.242) - MainThread (11716):
  File "logging\__init__.pyc", line 1634, in _log
ERROR - stderr (13:35:11.249) - MainThread (11716):
  File "logging\__init__.pyc", line 1644, in handle
ERROR - stderr (13:35:11.257) - MainThread (11716):
  File "logging\__init__.pyc", line 1706, in callHandlers
ERROR - stderr (13:35:11.263) - MainThread (11716):
  File "logHandler.pyc", line 378, in handle
ERROR - stderr (13:35:11.269) - MainThread (11716):
  File "logging\__init__.pyc", line 978, in handle
ERROR - stderr (13:35:11.276) - MainThread (11716):
  File "logging\__init__.pyc", line 1230, in emit
ERROR - stderr (13:35:11.283) - MainThread (11716):
  File "logging\__init__.pyc", line 1118, in emit
ERROR - stderr (13:35:11.289) - MainThread (11716):
Message: '\udc15'
Arguments: ()

```

### Expected behavior:
There should be only one multi-line error message logged containing the whole traceback, not one error message logged for each line.

### NVDA logs, crash dumps and other attachments:

See Actual result
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.1beta13
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.4046
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tested
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

Cc @lukaszgo1 since you have worked on similar issues, in case you want to tackle it.

**Comment by lukaszgo1** [comment]
Note that this is not a regression - logger errors always were logged in this ridiculously verbose way. I have confirmed this is also occurring on a random Alpha of 2022.4 I'm running here.
@CyrilleB79  What is the real life situation in which you have encountered this issue? The reason I ask is that, in addition to making the error here less verbose it may also be worth trying to log this character if it may occur in real life situations.
