### ISSUE TITLE
NVDA freezes for a very long time when using table navigation commands on a nested table in groups.io

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16322]
### Steps to reproduce:
1. Open this groups.io website:
https://nvda.groups.io/g/nvda/search?q=vocalizer
2. Press t in browse mode to jump to the first table
3. Use ctrl+alt+arrow keys to navigate between the results of the subjects of the conversations found
4. Press down arrow key to navigate to the body text of the conversation which is put in a nested table cell below the link with the subject
5. Press ctrl+alt+arrow keys in this nested cell.

### Actual behavior:
Here is the log, NVDA freezes for about 66 seconds on my end, but not directly after table navigation. I happened actually after I pressed nvda+f1 to open the log file right after I heared the error sound.

```
IO - inputCore.InputManager.executeGesture (23:53:55.517) - winInputHook (23464):
Input: kb(laptop):control+downArrow
DEBUG - speech.manager.SpeechManager.cancel (23:53:55.517) - MainThread (2228):
SpeechManager- Cancel
IO - speech.speech.speak (23:53:55.526) - MainThread (2228):
Speaking ['the blindhelp website have legal stuff too wwhy this stupid thing: this site are ilegal bla bla bla bla stop this crap now! ']
DEBUG - speech.manager.SpeechManager.speak (23:53:55.530) - MainThread (2228):
SpeechManager- speak (priority <SpeechPriority.NORMAL: 0>): ['the blindhelp website have legal stuff too wwhy this stupid thing: this site are ilegal bla bla bla bla stop this crap now!  ']
DEBUG - speech.manager.SpeechManager._queueSpeechSequence (23:53:55.530) - MainThread (2228):
SpeechManager- Out Seq: [['the blindhelp website have legal stuff too wwhy this stupid thing: this site are ilegal bla bla bla bla stop this crap now!  ', IndexCommand(2484)], [EndUtteranceCommand()]]
DEBUG - speech.manager.SpeechManager._queueSpeechSequence (23:53:55.530) - MainThread (2228):
SpeechManager- Current priority: 0, queLen: 0
DEBUG - speech.manager.SpeechManager._getMostRecentlyCancelledUtterance (23:53:55.530) - MainThread (2228):
SpeechManager- Length of _cancelCommandsForUtteranceBeingSpokenBySynth: 0 Length of _indexesSpeaking: 0 
DEBUG - speech.manager.SpeechManager._doRemoveCancelledSpeechCommands (23:53:55.530) - MainThread (2228):
SpeechManager- Last index: None
DEBUG - speech.manager.SpeechManager.speak (23:53:55.530) - MainThread (2228):
SpeechManager- Will interrupt: False Will push: True | _indexesSpeaking: [] | _curPriQueue valid: False | _shouldPushWhenDoneSpeaking: False | _cancelledLastSpeechWithSynth False
DEBUG - speech.manager.SpeechManager.speak (23:53:55.530) - MainThread (2228):
SpeechManager- Pushing next speech
DEBUG - speech.manager.SpeechManager._pushNextSpeech (23:53:55.530) - MainThread (2228):
SpeechManager- pushNextSpeech - doneSpeaking: True
DEBUG - speech.manager.SpeechManager._pushNextSpeech (23:53:55.530) - MainThread (2228):
SpeechManager- Synth Gets: ['the blindhelp website have legal stuff too wwhy this stupid thing: this site are ilegal bla bla bla bla stop this crap now!  ', IndexCommand(2484)]
DEBUG - speech.manager.SpeechManager.cancel (23:53:56.127) - MainThread (2228):
SpeechManager- Cancel
IO - inputCore.InputManager.executeGesture (23:53:56.196) - winInputHook (23464):
Input: kb(laptop):alt+control+rightArrow
IO - speech.speech.speak (23:53:56.228) - MainThread (2228):
Speaking ['Tabellenrand']
DEBUG - speech.manager.SpeechManager.speak (23:53:56.228) - MainThread (2228):
SpeechManager- speak (priority <SpeechPriority.NORMAL: 0>): ['Tabellenrand  ']
DEBUG - speech.manager.SpeechManager._queueSpeechSequence (23:53:56.228) - MainThread (2228):
SpeechManager- Out Seq: [['Tabellenrand  ', IndexCommand(2485)], [EndUtteranceCommand()]]
DEBUG - speech.manager.SpeechManager._queueSpeechSequence (23:53:56.228) - MainThread (2228):
SpeechManager- Current priority: 0, queLen: 0
DEBUG - speech.manager.SpeechManager._getMostRecentlyCancelledUtterance (23:53:56.228) - MainThread (2228):
SpeechManager- Length of _cancelCommandsForUtteranceBeingSpokenBySynth: 0 Length of _indexesSpeaking: 0 
DEBUG - speech.manager.SpeechManager._doRemoveCancelledSpeechCommands (23:53:56.228) - MainThread (2228):
SpeechManager- Last index: None
DEBUG - speech.manager.SpeechManager.speak (23:53:56.228) - MainThread (2228):
SpeechManager- Will interrupt: False Will push: True | _indexesSpeaking: [] | _curPriQueue valid: False | _shouldPushWhenDoneSpeaking: False | _cancelledLastSpeechWithSynth False
DEBUG - speech.manager.SpeechManager.speak (23:53:56.228) - MainThread (2228):
SpeechManager- Pushing next speech
DEBUG - speech.manager.SpeechManager._pushNextSpeech (23:53:56.228) - MainThread (2228):
SpeechManager- pushNextSpeech - doneSpeaking: True
DEBUG - speech.manager.SpeechManager._pushNextSpeech (23:53:56.228) - MainThread (2228):
SpeechManager- Synth Gets: ['Tabellenrand  ', IndexCommand(2485)]
ERROR - scriptHandler.executeScript (23:53:56.232) - MainThread (2228):
error executing script: <bound method DocumentWithTableNavigation.script_nextColumn of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x04945DB0>> with gesture 'Alt+Strg+Pfeiltaste nach rechts'
Traceback (most recent call last):
  File "documentBase.pyc", line 358, in _tableFindNewCell
  File "virtualBuffers\gecko_ia2.pyc", line 613, in _getNearestTableCell
  File "documentBase.pyc", line 285, in _getNearestTableCell
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 595, in _getTableCellAt
  File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "documentBase.pyc", line 384, in _tableFindNewCell
  File "virtualBuffers\gecko_ia2.pyc", line 603, in _getTableCellAt
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "documentBase.pyc", line 480, in script_nextColumn
  File "documentBase.pyc", line 415, in _tableMovementScriptHelper
  File "documentBase.pyc", line 386, in _tableFindNewCell
RuntimeError: ('Unable to find current cell.', LookupError())
DEBUG - speech.manager.SpeechManager._onSynthIndexReached (23:53:56.446) - synthDrivers._espeak.BgThread (404):
SpeechManager- synthReachedIndex: 2485, synth: SynthDriver('espeak')
DEBUG - speech.manager.SpeechManager._onSynthDoneSpeaking (23:53:56.446) - synthDrivers._espeak.BgThread (404):
SpeechManager- synthDoneSpeaking synth:SynthDriver('espeak')
DEBUG - speech.manager.SpeechManager._handleIndex (23:53:56.473) - MainThread (2228):
SpeechManager- Handle index: 2485
DEBUG - speech.manager.SpeechManager._removeCompletedFromQueue (23:53:56.474) - MainThread (2228):
SpeechManager- Removing: ['Tabellenrand  ', IndexCommand(2485)]
DEBUG - speech.manager.SpeechManager._getMostRecentlyCancelledUtterance (23:53:56.474) - MainThread (2228):
SpeechManager- Length of _cancelCommandsForUtteranceBeingSpokenBySynth: 0 Length of _indexesSpeaking: 0 
DEBUG - speech.manager.SpeechManager._doRemoveCancelledSpeechCommands (23:53:56.474) - MainThread (2228):
SpeechManager- Last index: None
DEBUG - speech.manager.SpeechManager._pushNextSpeech (23:53:56.474) - MainThread (2228):
SpeechManager- pushNextSpeech - doneSpeaking: False
DEBUG - speech.manager.SpeechManager._pushNextSpeech (23:53:56.475) - MainThread (2228):
SpeechManager- No more speech
DEBUG - speech.manager.SpeechManager._handleDoneSpeaking (23:53:56.475) - MainThread (2228):
SpeechManager- Synth done speaking, should push: False
DEBUG - speech.manager.SpeechManager.cancel (23:53:57.888) - MainThread (2228):
SpeechManager- Cancel
IO - inputCore.InputManager.executeGesture (23:53:58.409) - winInputHook (23464):
Input: kb(laptop):NVDA+f1
DEBUG - gui.contextHelp.bindHelpEvent (23:53:58.421) - MainThread (2228):
Did context help binding for LogViewer
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (23:53:58.916) - watchdog (12492):
Potential freeze, waiting up to 10 seconds.
IO - inputCore.InputManager.executeGesture (23:54:07.864) - winInputHook (23464):
Input: kb(laptop):upArrow
INFO - watchdog.waitForFreezeRecovery (23:54:08.427) - watchdog (12492):
Starting freeze recovery after 10.010771200002637 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (23:54:08.427) - watchdog (12492):
Listing stacks for Python threads:
Python stack for thread 404 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 14260 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x05D51AF8>)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "watchdog.pyc", line 382, in run
  File "threading.pyc", line 629, in wait
  File "threading.pyc", line 327, in wait

Python stack for thread 21152 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 452, in _run
  File "winUser.pyc", line 460, in getMessage

Python stack for thread 12492 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 159, in _watcher
  File "watchdog.pyc", line 166, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 23464 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 16388 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 544, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 18224 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 3336 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 258, in run

Python stack for thread 2228 (MainThread):
  File "nvda.pyw", line 415, in <module>
  File "core.pyc", line 911, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 841, in processRequest
  File "core.pyc", line 857, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "keyboardHandler.pyc", line 571, in executeScript
  File "inputCore.pyc", line 222, in executeScript
  File "scriptHandler.pyc", line 295, in executeScript
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "globalCommands.pyc", line 2881, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1489, in info
  File "logHandler.pyc", line 233, in _log
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "gui\logViewer.pyc", line 116, in activate
  File "gui\logViewer.pyc", line 58, in __init__
  File "gui\logViewer.pyc", line 70, in refresh

ERROR - watchdog.waitForFreezeRecovery (23:54:23.430) - watchdog (12492):
Core frozen in stack! (25.013451399994665 seconds)
INFO - watchdog.waitForFreezeRecovery (23:54:23.436) - watchdog (12492):
Listing stacks for Python threads:
Python stack for thread 20600 (nvwave.playWaveFile(error.wav)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "nvwave.pyc", line 711, in play
  File "nvwave.pyc", line 912, in feed
  File "nvwave.pyc", line 888, in open
  File "nvwave.pyc", line 1009, in _setVolumeFromConfig
  File "nvwave.pyc", line 997, in setVolume

Python stack for thread 404 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 14260 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x05D51AF8>)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "watchdog.pyc", line 382, in run
  File "threading.pyc", line 629, in wait
  File "threading.pyc", line 327, in wait

Python stack for thread 21152 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 452, in _run
  File "winUser.pyc", line 460, in getMessage

Python stack for thread 12492 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 159, in _watcher
  File "watchdog.pyc", line 187, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 23464 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 16388 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 544, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 18224 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 3336 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 258, in run

Python stack for thread 2228 (MainThread):
  File "nvda.pyw", line 415, in <module>
  File "core.pyc", line 911, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 841, in processRequest
  File "core.pyc", line 857, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "keyboardHandler.pyc", line 571, in executeScript
  File "inputCore.pyc", line 222, in executeScript
  File "scriptHandler.pyc", line 295, in executeScript
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "globalCommands.pyc", line 2881, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1489, in info
  File "logHandler.pyc", line 233, in _log
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "gui\logViewer.pyc", line 116, in activate
  File "gui\logViewer.pyc", line 58, in __init__
  File "gui\logViewer.pyc", line 70, in refresh

DEBUGWARNING - RPC process 23708 (NarratorQuickStart.exe) (23:54:35.236) - Dummy-26 (9284):
Thread 7868, build\x86_64\remote\ia2Support.cpp, IA2Support_inProcess_initialize, 177:
Not installing IA2 support as  process is suspendable

ERROR - watchdog.waitForFreezeRecovery (23:54:38.453) - watchdog (12492):
Core frozen in stack! (40.03685229999246 seconds)
INFO - watchdog.waitForFreezeRecovery (23:54:38.467) - watchdog (12492):
Listing stacks for Python threads:
Python stack for thread 4924 (nvwave.playWaveFile(error.wav)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "nvwave.pyc", line 711, in play
  File "wave.pyc", line 362, in readframes
  File "wave.pyc", line 178, in read
  File "wave.pyc", line 178, in read

Python stack for thread 404 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 14260 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x05D51AF8>)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "watchdog.pyc", line 382, in run
  File "threading.pyc", line 629, in wait
  File "threading.pyc", line 327, in wait

Python stack for thread 21152 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 452, in _run
  File "winUser.pyc", line 460, in getMessage

Python stack for thread 12492 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 159, in _watcher
  File "watchdog.pyc", line 187, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 23464 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 16388 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 544, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 18224 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 3336 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 258, in run

Python stack for thread 2228 (MainThread):
  File "nvda.pyw", line 415, in <module>
  File "core.pyc", line 911, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 841, in processRequest
  File "core.pyc", line 857, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "keyboardHandler.pyc", line 571, in executeScript
  File "inputCore.pyc", line 222, in executeScript
  File "scriptHandler.pyc", line 295, in executeScript
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "globalCommands.pyc", line 2881, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1489, in info
  File "logHandler.pyc", line 233, in _log
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "gui\logViewer.pyc", line 116, in activate
  File "gui\logViewer.pyc", line 58, in __init__
  File "gui\logViewer.pyc", line 70, in refresh

ERROR - watchdog.waitForFreezeRecovery (23:54:53.501) - watchdog (12492):
Core frozen in stack! (55.08548009999504 seconds)
INFO - watchdog.waitForFreezeRecovery (23:54:53.525) - watchdog (12492):
Listing stacks for Python threads:
Python stack for thread 14276 (nvwave.playWaveFile(error.wav)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "nvwave.pyc", line 711, in play
  File "nvwave.pyc", line 912, in feed
  File "nvwave.pyc", line 888, in open
  File "nvwave.pyc", line 1009, in _setVolumeFromConfig
  File "nvwave.pyc", line 997, in setVolume

Python stack for thread 404 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 14260 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x05D51AF8>)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "watchdog.pyc", line 382, in run
  File "threading.pyc", line 629, in wait
  File "threading.pyc", line 327, in wait

Python stack for thread 21152 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 452, in _run
  File "winUser.pyc", line 460, in getMessage

Python stack for thread 12492 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 159, in _watcher
  File "watchdog.pyc", line 187, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 23464 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 16388 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 544, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 18224 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 3336 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 258, in run

Python stack for thread 2228 (MainThread):
  File "nvda.pyw", line 415, in <module>
  File "core.pyc", line 911, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 841, in processRequest
  File "core.pyc", line 857, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "keyboardHandler.pyc", line 571, in executeScript
  File "inputCore.pyc", line 222, in executeScript
  File "scriptHandler.pyc", line 295, in executeScript
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "globalCommands.pyc", line 2881, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1489, in info
  File "logHandler.pyc", line 237, in _log

INFO - globalCommands.script_navigatorObject_devInfo (23:55:04.776) - MainThread (2228):
Developer info for navigator object:
name: None
role: TABLECELL
processID: 18692
roleText: None
states: SELECTABLE
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x0992DF10>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=359, top=581, width=1521, height=30)
value: None
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
appModule: AppModule(appModuleHandler, appName='firefox', processID=18692)
appModule.productName: 'Firefox'
appModule.productVersion: '123.0.1'
appModule.helperLocalBindingHandle: c_long(100753544)
windowHandle: 984612
windowClassName: 'MozillaWindowClass'
windowControlID: 0
windowStyle: 382664704
extendedWindowStyle: 256
windowThreadID: 4660
windowText: 'nvda@nvda.groups.io | Search – Mozilla Firefox'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x615b244 at 492a260>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=984612, objectID=-4, childID=-13794
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_CELL
IAccessible accState: STATE_SYSTEM_SELECTABLE, STATE_SYSTEM_VALID (2097152)
IAccessible accDescription: ''
IAccessible accValue: None
IAccessible2 windowHandle: 984612
IAccessible2 uniqueID: -13794
IAccessible2 role: ROLE_SYSTEM_CELL
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_SELECTABLE_TEXT (5120)
IAccessible2 attributes: 'table-cell-index:0;tag:td;display:table-cell;'
IAccessible2 relations: containingTabPane * 1
INFO - watchdog.waitForFreezeRecovery (23:55:04.827) - watchdog (12492):
Recovered from freeze after 66.41087339998921 seconds.
```

### Expected behavior:
No freeze.

### NVDA logs, crash dumps and other attachments:
n/a, it is not always reproducible.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2024.1 Beta 13

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
Firefox 123
Chrome and Edge 122.

#### Other information about your system:
Asus ROG strix with intel I12900HK, 32gb Ram and 8 gb dedicated storage on the grafic card, NVIDIA gtx 3070TI

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I remember having reproduced this on versions of NVDA before but I was never able isolate this issue.

#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons in use.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
I could reproduce this also in other scenarios, so it is definitely related to the nvda+f1 command and the log viewer. I edited the issue title and description.

**Comment by seanbudd** [comment]
It seems like this freeze occurs when appending text to the end of the control.
wxWidgets perhaps could make a more time efficient implementation of `AppendText`.
Given the current limitation from wx, the best solution we see is limiting the size of the buffer of log viewer to only the last 1000 lines.

**Comment by Adriani90** [comment]
@seanbudd thanks for following up on this. So if I understood your proposal correctly, with that solution the user gets only the last 1000 lines displayed in the log when pressing nvda+f1. Right?
This is a good solution in the short term I think.
If possible, we should push WX to improve this on their end though.
Maybe it is a rare case, but limiting the log viewer would make issues like #16451 heavier to interpret since we would then miss important parts of the log.

**Comment by seanbudd** [comment]
That's correct, just a buffer of the last 1000 lines from the log file which contains all of the log.
I think #16451 wouldn't really be affected as we generally refer to the whole log file rather than log viewer snippets. Log viewer is generally most useful IMO for catching the most recent log lines rather than reading the full log file so I don't really see this as being an issue. You can always workaround this by opening the log file in a document reader.

**Comment by XLTechie** [comment]
@seanbudd I question the technical conclusion here.

I have just caused NVDA's log to expand to 906,600 plus lines (well over nine hundred thousand lines) for my current session, using `for i in range(1, 400000): log.debug(f"This is bogus log entry {i}.")` (and similar), in the Python console.
This is far longer than I think is likely for the average NVDA session (@Adriani90 can you comment?).

The Log Viewer takes 15 seconds to open on this 6-core, 32 GB RAM Intel I7 laptop.

Initially there is a watchdog timeout when opening the log, but if I terminate watchdog, this is not a problem.

In fact, the log viewer performance when open, is far snappier than the same log opened in Notepad, which has repeated delays and overall sluggishness, even though Win 11 Notepad gets the file open much faster.

I think @CyrilleB79's suggestion about what is going on, might be closer to the truth.
In any case, I also agree with @CyrilleB79 that there are other uses for the log viewer; and I would prefer to see truncating as a last resort rather than a first one.

**Comment by seanbudd** [comment]
Can anyone test and confirm if debouncing the refresh of the panel improves anything?
Launcher build from #19967 to test with: https://github.com/nvaccess/nvda/actions/runs/24547736924/artifacts/6488964289

**Comment by CyrilleB79** [comment]
I have just had this issue, about 30 second freeze when opening the log. I am running NVDA with add-ons so they may interfer. 
But here is my experience, in case it may provide hints to solve this issue:
* The log contains 22178 line, 5789997 characters
* NVDA is running for less than 2 hours with log level set to debug
* During this less-than-2-hour period, I have been away about 1 hour, with the computer locked and in stand by. I do not know exactly which type of standby, that's the standard Windows 11 one. Also I do not know if standby matters here; I'll try to check next time if the issue appears with no a previous standby.
* If I open the log viewer when it is not already open, the freeze occurs
* If I open it while it is already open as a background window, the logviewer window is raised to foreground with no delay/freeze
* If I open the log with `NVDA+F1` or with NVDA menu -> Tools -> Log viewer makes no difference. Thus the issues does not come from object dev info retrieval.
* Pressing `F5` in the log viewer immediately refreshes its content with no delay / freeze, so probably no link with the refresh function itself.

Only few add-ons are running: Eloquence (not used) and IBMTTS (currently used).
