### ISSUE TITLE
Vertical navigation: NVDA throws error and is silent when using it with Excel browse mode

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16387]
### Steps to reproduce:
1. Open MS Excel
2. While running NVDA, set two input gestures for vertical navigation (i.e. nvda+alt+up and down arrow)
3. In MS Excel switch to browse mode with nvda+space bar
4. Try to navigate vertically

### Actual behavior:
Following error appears and NVDA is silent:
```
IO - inputCore.InputManager.executeGesture (11:30:15.967) - winInputHook (1720):
Input: kb(laptop):NVDA+alt+downArrow
ERROR - scriptHandler.executeScript (11:30:15.987) - MainThread (13636):
error executing script: <bound method BrowseModeTreeInterceptor.addQuickNav.<locals>.<lambda> of <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x0505E3F0>> with gesture 'NVDA+Alt+Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "browseMode.pyc", line 564, in <lambda>
  File "browseMode.pyc", line 522, in _quickNavScript
  File "browseMode.pyc", line 465, in _iterSimilarParagraph
AttributeError: 'ExcelCell' object has no attribute 'copy'
```

### Expected behavior:
1. If vertical navigation is expected in Excel by design, NVDA should report "no previous vertically aligned paragraph" or "no next vertically aligned paragraph", same as it works in browsers or with other browse mode quick nav keys. However, note that excel provides its own vertical navigation natively when using ctrl+up and down arrow keys.
2. If vertical navigation should not be supporte din Excel, NVDA should report "not supported in this document", same as it does with other not supported quick nav gestures in Excel browse mode.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-31580,20342a38 (2024.2.0.31580)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
MS Office 365 MSO (Version 2403 Build 16.0.17425.20124) 64 Bit

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @mltony
