### ISSUE TITLE
Vertical navigation: runtime error in empty documents. report "no next aligned paragraph " or "no previous aligned paragraph" instead

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16386]
### Steps to reproduce:
1. Open an empty word document or an empty email in Outlook
2. While running NVDA, set two input gestures for vertical navigation (i.e. nvda+alt+up and down arrow)
3. In MS Word or Outlook, switch to browse mode with nvda+space bar
4. Try to navigate vertically

### Actual behavior:
Following error is raised and NVDA is silent:
```
IO - inputCore.InputManager.executeGesture (11:08:04.757) - winInputHook (1720):
Input: kb(laptop):NVDA+alt+downArrow
ERROR - scriptHandler.executeScript (11:08:04.769) - MainThread (13636):
error executing script: <bound method BrowseModeTreeInterceptor.addQuickNav.<locals>.<lambda> of <NVDAObjects.window.winword.WordDocumentTreeInterceptor object at 0x084EFC30>> with gesture 'NVDA+Alt+Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "browseMode.pyc", line 564, in <lambda>
  File "browseMode.pyc", line 522, in _quickNavScript
  File "browseMode.pyc", line 472, in _iterSimilarParagraph
  File "treeInterceptorHandler.pyc", line 234, in collapse
  File "NVDAObjects\window\winword.pyc", line 1052, in collapse
RuntimeError
```

### Expected behavior:
NVDA should report "no previous vertically aligned paragraph" or "no next vertically aligned paragraph", same as it works in browsers or with other browse mode quick nav keys.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
alpha-31580,20342a38 (2024.2.0.31580)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
MS Office 365 MSO (Version 2403 Build 16.0.17425.20124) 64 Bit

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @mltony

**Comment by Adriani90** [comment]
This works as expected when using UIA in MS Word or Outlook. But since most users still use the object model due to several UIA problems, this issue should be fixed for object model.
