### ISSUE TITLE
Error when closing tabs via ctrl+w while using UIA in Edge Chromium

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#16435]
### Steps to reproduce:
1. Open NVDA
2. Open Edge Chromium browser
3. In NVDA advanced settings, set UIA for chromium browsers to "yes"
4. Navigate to a website and open multiple tabs
5. Press ctrl+w to close a tab

### Actual behavior:
Following error appears. User impact might be that any tab closing notification, if any, will probably not be announced by NVDA.
```
IO - inputCore.InputManager.executeGesture (22:05:36.830) - winInputHook (15192):
Input: kb(laptop):control+w
DEBUGWARNING - eventHandler.executeEvent (22:05:36.860) - MainThread (5368):
error executing event: typedCharacter on <NVDAObjects.Dynamic_ChromiumUIADocumentEditableTextWithAutoSelectDetectionUIA object at 0x051C7810> with extra args of {'ch': '\x17'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\behaviors.pyc", line 271, in event_typedCharacter
  File "NVDAObjects\__init__.pyc", line 1199, in event_typedCharacter
  File "speech\speech.pyc", line 1228, in speakTypedCharacters
  File "api.pyc", line 349, in isTypingProtected
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1074, in _get_isProtected
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\web.pyc", line 372, in _get_states
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1692, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 984, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:05:36.874) - MainThread (5368):
error executing event: UIA_notification on <NVDAObjects.UIA.chromium.ChromiumUIA object at 0x062459B0> with extra args of {'notificationKind': 2, 'notificationProcessing': 1, 'displayString': 'Tab wird geschlossen', 'activityId': 'ClosingTab'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 122, in next
  File "eventHandler.pyc", line 150, in gen
  File "NVDAObjects\__init__.pyc", line 430, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 42, in getTreeInterceptor
  File "UIAHandler\browseMode.pyc", line 534, in __contains__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (22:05:36.889) - MainThread (5368):
error executing event: UIA_elementSelected on <NVDAObjects.UIA.chromium.ChromiumUIA object at 0x061D2130> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 122, in next
  File "eventHandler.pyc", line 150, in gen
  File "NVDAObjects\__init__.pyc", line 430, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 42, in getTreeInterceptor
  File "UIAHandler\browseMode.pyc", line 534, in __contains__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (22:05:36.911) - MainThread (5368):
Killed treeInterceptor: <NVDAObjects.UIA.chromium.ChromiumUIATreeInterceptor object at 0x055CD450>
```

### Expected behavior:
No error.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-31645,bf96860d (2024.2.0.31645)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
Edge 124

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons in use

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by seanbudd** [comment]
>User impact might be that any tab closing notification, if any, will probably not be announced by NVDA.

Is there a notification without UIA enabled?

**Comment by Adriani90** [comment]
NoVon meinem iPhone gesendetAm 23.04.2024 um 01:53 schrieb Sean Budd ***@***.***>:﻿

User impact might be that any tab closing notification, if any, will probably not be announced by NVDA.

Is there a notification without UIA enabled?

**Comment by beqabeqa473** [comment]
Yes, there is a notification default setup.
Use UIA with Microsoft Edge and other 
Chromium based browsers when available: Default (Only when necessary)

@Adriani90 are you certain in your answer?

**Comment by Adriani90** [comment]
I thought we talk about notification when closing a tab thrown by MS Edge. I don‘t think there is one thrown when closing tabs and UIA is set to only when necessary. Where did you find evidence for the notification? Maybe I missed something.Von meinem iPhone gesendetAm 23.04.2024 um 16:04 schrieb Beqa Gozalishvili ***@***.***>:﻿
Yes, there is a notification default setup.
Use UIA with Microsoft Edge and other
Chromium based browsers when available: Default (Only when necessary)
@Adriani90 are you certain in your answer?

**Comment by beqabeqa473** [comment]
Try it yourself and get back with answer.

It is there for several years.

**Comment by Adriani90** [comment]
Ah thanks for insisting on this, it seems indeed it works on my working machine, not sure why I didn't get that notification on my private machine.
So yes there is a notification when UIA is set to only when necessary.

**Comment by beqabeqa473** [comment]
In case you didn't try it with all addons disabled, You may have my addon installed which suppresses those notifications.
