### ISSUE TITLE
NVDA does not pronounce completely the last word or character name after a while moving in a text editor or text aria 

### ISSUE THREAD

**Issue by shadyar** [nvaccess/nvda#16457]
### Steps to reproduce:
After a while moving in a text editor software like Word or text aria character by character and word by word, this issue happens, Specially in code editors of IntelliJ Idea IDE or Eclipse.
I even disabled all add-on but it was not effective.
I have attached two logs related installed and running from source and after running the COM Registration Fixing Tool.
### Actual behavior:

NVDA does not pronounce the last part of the last syllable of the last word or character name 
### NVDA logs, crash dumps and other attachments:
yes
#### NVDA installed/portable/running from source:
Both NVDA installed and running from source.
#### NVDA version:
Installed Version: 2024.1 (2024.1.0.31547)
Running Version: nvda_snapshot_alpha-31645,bf96860d
#### Windows version:
Windows 11 latest version 64-bit
#### Name and version of other software in use when reproducing the issue:
code editor of IntelliJ, code editor of Eclipse, Microsoft Word and etc.
#### Other information about your system:
Laptop Asus Zen-Book 16 GB ram, 64-bit CPU
#### Does the issue still occur after restarting your computer?
Not immediately, but after a few minutes yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, those had the same behavior.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[after-running-COM-Registration-Fixing-Tool .log](https://github.com/nvaccess/nvda/files/15142269/after-running-COM-Registration-Fixing-Tool.log)
[nvda v2024.1.0.31547.log](https://github.com/nvaccess/nvda/files/15142273/nvda.v2024.1.0.31547.log)

**Comment by Adriani90** [comment]
This might be a duplicate of #16374.
@shadyar can you please describe exactly step by step what you are doing to reproduce this issue?

**Comment by Adriani90** [comment]
Your logs are unfortunately not really useful, you have to enable the debug log level in NVDA general settings.
Also is this reproducible when you use eSpeak?
Or which synthesizer are you using?

**Comment by shadyar** [comment]
@Adriani90 
No this is not a duplicate of #16374.
Thanks for your attention, I attached three new logs. The file names show, which one is better. it means the problem happened in a shorter time so that studying it would be easier.
[nvda-best.log](https://github.com/nvaccess/nvda/files/15155287/nvda-best.log)
[nvda-better.log](https://github.com/nvaccess/nvda/files/15155289/nvda-better.log)
[nvda-not-bad.log](https://github.com/nvaccess/nvda/files/15155290/nvda-not-bad.log)

**Comment by seanbudd** [comment]
As requested by @Adriani90 we need step by step instructions to reproduce the issue

**Comment by shadyar** [comment]
@seanbudd 
@Adriani90 
I can not reproduce this bug any time I would, I could not find a certain pattern for it just when I am programming in a code editor every once in a while this bug arises. A complex situation that makes this bug is most likely multi factors. You should study the log I have sent.

**Comment by Adriani90** [comment]
So here are the relevant part of the log I think might help:
You typed "package" and there was a suggestion appearing from the application, after typing letter c. at that point the speech has been canceled from the main thread. However, there is no interuption visible in the log, the word "package" has been spoken according to the log.

```
DEBUG - speech.manager.SpeechManager._handleIndex (00:56:41.547) - MainThread (14484):
Unknown index 60, speech probably cancelled from main thread.
```

```
IO - inputCore.InputManager.executeGesture (00:56:40.785) - winInputHook (13464):
Input: kb(desktop):shift+p
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:40.869) - MainThread (14484):
states: enabled,focusable,visible,showing,focused,opaque,editable,multiple line
IO - speech.speech.speak (00:56:40.869) - MainThread (14484):
Speaking [PitchCommand(offset=30), CharacterModeCommand(True), LangChangeCommand ('en_US'), 'P', PitchCommand(), EndUtteranceCommand()]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.012) - MainThread (14484):
states: enabled,focusable,visible,showing,focused,opaque
IO - speech.speech.speak (00:56:41.014) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'list', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.046) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.047) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService com.shadyar.leitnerbox.service', '1 of 97', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:41.163) - winInputHook (13464):
Input: kb(desktop):a
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.333) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.336) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'a', EndUtteranceCommand()]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.339) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.341) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService com.shadyar.leitnerbox.service', '1 of 293', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:41.407) - winInputHook (13464):
Input: kb(desktop):c
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.542) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.543) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService com.shadyar.leitnerbox.service', '1 of 39', CancellableSpeech (still valid)]
IO - speech.speech.speak (00:56:41.546) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'c', EndUtteranceCommand()]
DEBUG - speech.manager.SpeechManager._handleIndex (00:56:41.547) - MainThread (14484):
Unknown index 60, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (00:56:41.598) - winInputHook (13464):
Input: kb(desktop):k
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.692) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.694) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'k', EndUtteranceCommand()]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.698) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.700) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'Pack org.bouncycastle.util', '1 of 17', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:41.702) - winInputHook (13464):
Input: kb(desktop):a
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.781) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.782) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'a', EndUtteranceCommand()]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:41.785) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:41.787) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService com.shadyar.leitnerbox.service', '1 of 11', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:41.970) - winInputHook (13464):
Input: kb(desktop):g
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:42.096) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:42.096) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'g', EndUtteranceCommand()]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:42.100) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:42.102) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService com.shadyar.leitnerbox.service', '1 of 11', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:42.245) - winInputHook (13464):
Input: kb(desktop):e
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:42.529) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:42.531) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'e', EndUtteranceCommand()]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:42.538) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,active,selected,showing,transient
IO - speech.speech.speak (00:56:42.539) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'Package java.lang', '1 of 10', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:42.553) - winInputHook (13464):
Input: kb(desktop):space
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:42.691) - MainThread (14484):
states: enabled,focusable,visible,opaque,selectable,selected,transient
IO - speech.speech.speak (00:56:42.694) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'space', EndUtteranceCommand()]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.151) - MainThread (14484):
states: enabled,focusable,visible,showing,active,resizable
IO - speech.speech.speak (00:56:43.152) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'leitner-box - IntelliJ IDEA', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.153) - MainThread (14484):
states: enabled,focusable,visible,showing
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.153) - MainThread (14484):
states: enabled,focusable,visible,showing
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.154) - MainThread (14484):
states: enabled,focusable,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.154) - MainThread (14484):
states: enabled,focusable,visible,showing
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.154) - MainThread (14484):
states: enabled,focusable,visible,showing
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.154) - MainThread (14484):
states: enabled,focusable,visible,showing
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.154) - MainThread (14484):
states: enabled,focusable,visible,showing
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.155) - MainThread (14484):
states: enabled,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.155) - MainThread (14484):
states: enabled,visible,showing,opaque
IO - speech.speech.speak (00:56:43.166) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService.java', 'tab control', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.166) - MainThread (14484):
states: enabled,visible,showing,opaque,selectable,selected
IO - speech.speech.speak (00:56:43.167) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService.java', 'tab', 'selected', "F:\\Shadyar's projects\\leitner-box\\src\\main\\java\\com\\shadyar\\leitnerbox\\service\\PackageService.java", '2 of 12', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.169) - MainThread (14484):
states: enabled,focusable,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.170) - MainThread (14484):
states: enabled,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.170) - MainThread (14484):
states: enabled,focusable,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.170) - MainThread (14484):
states: enabled,focusable,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.170) - MainThread (14484):
states: enabled,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.170) - MainThread (14484):
states: enabled,focusable,visible,showing
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.170) - MainThread (14484):
states: enabled,focusable,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.171) - MainThread (14484):
states: enabled,focusable,visible,showing,opaque
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:43.171) - MainThread (14484):
states: enabled,focusable,visible,showing,focused,opaque,editable,multiple line
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.173) - MainThread (14484):
lineBounds: index 22296
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.174) - MainThread (14484):
line bounds: start 22272, end 22296
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.175) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22296
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.175) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22296
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.176) - MainThread (14484):
line bounds: returning 22272, 22296
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.176) - MainThread (14484):
lineBounds: index 0
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.177) - MainThread (14484):
line bounds: start 0, end 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.178) - MainThread (14484):
line bounds: tempStart 0, tempEnd 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.179) - MainThread (14484):
line bounds: tempStart 0, tempEnd 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:43.179) - MainThread (14484):
line bounds: returning 0, 39
IO - speech.speech.speak (00:56:43.182) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'Editor for PackageService.java', 'edit', 'multi line', CancellableSpeech (still valid), 'public void get Package \n']

**Comment by Adriani90** [comment]
IN another case, you typed "Public" and here also suggestions appeared after typing some letters. You seem to have denied the suggestions and continued typing. In this case, only the word "c" from public seem to have been reported by the synthesizer when speak typed word is enabled, but still the word was pronounced after you denied the suggestions:

```
IO - inputCore.InputManager.executeGesture (00:56:33.938) - winInputHook (13464):
Input: kb(desktop):p
IO - speech.speech.speak (00:56:33.992) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'p', EndUtteranceCommand()]
IO - speech.speech.speak (00:56:34.155) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'list', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:34.173) - winInputHook (13464):
Input: kb(desktop):u
IO - speech.speech.speak (00:56:34.227) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'packages -  ArrayList<CardPackage>', '1 of 24', CancellableSpeech (still valid)]
IO - speech.speech.speak (00:56:34.239) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'u', EndUtteranceCommand()]
IO - speech.speech.speak (00:56:34.360) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'computeStatistics(CardPackage cardPackage) -  void', '1 of 1', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:34.522) - winInputHook (13464):
Input: kb(desktop):b
IO - speech.speech.speak (00:56:34.568) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'b', EndUtteranceCommand()]
IO - speech.speech.speak (00:56:34.671) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'leitner-box - IntelliJ IDEA', CancellableSpeech (still valid)]
IO - speech.speech.speak (00:56:34.675) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService.java', 'tab control', CancellableSpeech (still valid)]
IO - speech.speech.speak (00:56:34.676) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService.java', 'tab', 'selected', "F:\\Shadyar's projects\\leitner-box\\src\\main\\java\\com\\shadyar\\leitnerbox\\service\\PackageService.java", '2 of 12', CancellableSpeech (still valid)]
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.684) - MainThread (14484):
lineBounds: index 22275
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.685) - MainThread (14484):
line bounds: start 22272, end 22275
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.685) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22275
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.686) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22275
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.686) - MainThread (14484):
line bounds: returning 22272, 22275
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.688) - MainThread (14484):
lineBounds: index 0
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.688) - MainThread (14484):
line bounds: start 0, end 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.689) - MainThread (14484):
line bounds: tempStart 0, tempEnd 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.689) - MainThread (14484):
line bounds: tempStart 0, tempEnd 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:34.689) - MainThread (14484):
line bounds: returning 0, 39
IO - speech.speech.speak (00:56:34.690) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'Editor for PackageService.java', 'edit', 'multi line', CancellableSpeech (still valid), 'pub\n']
IO - inputCore.InputManager.executeGesture (00:56:34.824) - winInputHook (13464):
Input: kb(desktop):l
IO - speech.speech.speak (00:56:34.936) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'l', EndUtteranceCommand()]
IO - speech.speech.speak (00:56:34.981) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'list', CancellableSpeech (still valid)]
IO - speech.speech.speak (00:56:35.000) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'decimalMaxValidatorForDouble -   DecimalMaxValidatorForDouble', '1 of 10', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:56:35.094) - winInputHook (13464):
Input: kb(desktop):i
IO - speech.speech.speak (00:56:35.146) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'i', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (00:56:35.218) - winInputHook (13464):
Input: kb(desktop):c
IO - speech.speech.speak (00:56:35.261) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'leitner-box - IntelliJ IDEA', CancellableSpeech (still valid)]
IO - speech.speech.speak (00:56:35.266) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService.java', 'tab control', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:35.266) - MainThread (14484):
states: enabled,visible,showing,opaque,selectable,selected
IO - speech.speech.speak (00:56:35.267) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'PackageService.java', 'tab', 'selected', "F:\\Shadyar's projects\\leitner-box\\src\\main\\java\\com\\shadyar\\leitnerbox\\service\\PackageService.java", '2 of 12', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:35.269) - MainThread (14484):
states: enabled,focusable,visible,showing,opaque
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.271) - MainThread (14484):
lineBounds: index 22278
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.273) - MainThread (14484):
line bounds: start 22272, end 22278
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.273) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22278
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.274) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22278
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.274) - MainThread (14484):
line bounds: returning 22272, 22278
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.274) - MainThread (14484):
lineBounds: index 0
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.276) - MainThread (14484):
line bounds: start 0, end 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.276) - MainThread (14484):
line bounds: tempStart 0, tempEnd 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.276) - MainThread (14484):
line bounds: tempStart 0, tempEnd 39
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.276) - MainThread (14484):
line bounds: returning 0, 39
IO - speech.speech.speak (00:56:35.277) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'Editor for PackageService.java', 'edit', 'multi line', CancellableSpeech (still valid), 'public\n']
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:35.281) - MainThread (14484):
states: enabled,focusable,visible,showing,focused,opaque,editable,multiple line
IO - speech.speech.speak (00:56:35.282) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'c', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (00:56:35.422) - winInputHook (13464):
Input: kb(desktop):space
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.453) - MainThread (14484):
lineBounds: index 22278
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.454) - MainThread (14484):
line bounds: start 22272, end 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.454) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.455) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.455) - MainThread (14484):
line bounds: returning 22272, 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.455) - MainThread (14484):
lineBounds: index 22277
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.457) - MainThread (14484):
line bounds: start 22272, end 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.457) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.458) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.458) - MainThread (14484):
line bounds: returning 22272, 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.459) - MainThread (14484):
lineBounds: index 22277
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.459) - MainThread (14484):
line bounds: start 22272, end 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.459) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.461) - MainThread (14484):
line bounds: tempStart 22272, tempEnd 22279
DEBUG - JABHandler.JABContext.getAccessibleTextLineBounds (00:56:35.461) - MainThread (14484):
line bounds: returning 22272, 22279
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:35.462) - MainThread (14484):
states: enabled,focusable,visible,showing,focused,opaque,editable,multiple line
IO - speech.speech.speakTypedCharacters (00:56:35.462) - MainThread (14484):
typed word: c
IO - speech.speech.speak (00:56:35.462) - MainThread (14484):
Speaking [LangChangeCommand ('en_US'), 'c']
```

**Comment by Adriani90** [comment]
So in summary:
There are only two potential word interuption visible when you type words with speak typed words enabled, but not when navigating word by word or character by character.

The log is not useful in this case.
Please provide a audio recording of this issue so people can understand better what it sounds like.

Did you try to disable cancellable speech on expired focus events?
You can disable this setting in NVDA advanced settings.
Can you still reproduce this issue with that setting disabled?

I guess maybe the application shows suggestions while you navigate words and that might interupt the word pronounciation when the focus is taken by the suggestions.

cc: @mwhapples can you reproduce?

**Comment by Adriani90** [comment]
There is also a warning that NVDA cannot fetch the formatting of the last charachter of previous word in the log but not sure if it is related. It happens after you type "void" and interact with the suggestions:
```
DEBUGWARNING - NVDAObjects.behaviors._delayedDetection (00:56:37.294) - MainThread (14484):
Error fetching formatting for last character of previous word
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyc", line 243, in _delayedDetection
  File "textInfos\offsets.pyc", line 574, in getTextWithFields
  File "NVDAObjects\JAB\__init__.pyc", line 187, in _getFormatFieldAndOffsets
AttributeError: 'NoneType' object has no attribute 'jabContext'
IO - inputCore.InputManager.executeGesture (00:56:39.514) - winInputHook (13464):
Input: kb(desktop):g
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:39.612) - MainThread (14484):
states: enabled,focusable,visible,showing,focused,opaque,editable,multiple line
IO - speech.speech.speak (00:56:39.613) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'g', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (00:56:39.728) - winInputHook (13464):
Input: kb(desktop):e
DEBUG - NVDAObjects.JAB.JAB._get_states (00:56:39.774) - MainThread (14484):
states: enabled,focusable,visible,showing,focused,opaque,editable,multiple line
IO - speech.speech.speak (00:56:39.774) - MainThread (14484):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_US'), 'e', EndUtteranceCommand()]
```

Without a recording it is really heavy to investigate further.

**Comment by shadyar** [comment]
@Adriani90 
Thanks so much for your consideration of the log. Yes I agree with your guess about showing suggestions while typing, that can potentially be cause of this bug. OK I will disable that feature in NVDA Advance Settings then I try to reproduce this bug and notify you. If it could not help, I will attempt to capture a audio record of this bug but it is not easy because you do not sure when this bug exactly occurs to capture the audio.

**Comment by Adriani90** [comment]
@shadyar any updates on this with cancellable speech disabled in advanced settings of NVDA? Are you still having this issue when you disable that setting?

**Comment by shadyar** [comment]
@Adriani90 
          I tested it.  First able I disabled all add-ons then I chosen No for feature "Attempt to cancel speech for expired focus events" in Preferences > Settings > Advance.
          It did not effect on the problem. The issue occurred.
          If there is a solution else I should try, let me know.

**Comment by Adriani90** [comment]
@shadyar are you still having this issue in NVDA 2025.1.2 with MS Office 365 version 2505, IntelliJ 2025.1.3 and Eclipse IdE 2025-06?

**Comment by Adriani90** [comment]
No updates upon request since more than 1 year, closing as abandoned. If you are still having this issue, please comment and we can reopen.
