### ISSUE TITLE
Running NVDA 2023.3.4 or 2024.1 with --help or -h flags throws an error

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#16522]
### Steps to reproduce:

Run either the launcher or an installed copy of NVDA 2023.3.4 or NVDA 2024.1 and including the latest alpha currently: alpha-31858,2d865027, with the --help command line argument, eg:

nvda_2024.1.exe --help

### Actual behavior:

The following error message is displayed:

---------------------------
Errors in 'nvda.exe'
---------------------------
See the logfile 'C:\Users\quent\AppData\Roaming\nvda.log' for details
---------------------------
OK   
---------------------------

(See log below)

### Expected behavior:

NVDA should display the help screen of command line arguments etc, as earlier versions of NVDA display when using the --help argument.

### NVDA logs, crash dumps and other attachments:

The logfile referenced contains:

Traceback (most recent call last):
  File "nvda.pyw", line 217, in <module>
  File "argparse.pyc", line 1902, in parse_known_args
  File "argparse.pyc", line 2114, in _parse_known_args
  File "argparse.pyc", line 2054, in consume_optional
  File "argparse.pyc", line 1978, in take_action
  File "argparse.pyc", line 1119, in __call__
  File "nvda.pyw", line 86, in print_help
  File "argparse.pyc", line 2585, in format_help
  File "argparse.pyc", line 286, in format_help
  File "argparse.pyc", line 217, in format_help
  File "argparse.pyc", line 217, in <listcomp>
  File "argparse.pyc", line 217, in format_help
  File "argparse.pyc", line 217, in <listcomp>
  File "argparse.pyc", line 543, in _format_action
  File "argparse.pyc", line 640, in _expand_help
ValueError: unsupported format character 'T' (0x54) at index 74
Traceback (most recent call last):
  File "nvda.pyw", line 217, in <module>
  File "argparse.pyc", line 1902, in parse_known_args
  File "argparse.pyc", line 2114, in _parse_known_args
  File "argparse.pyc", line 2054, in consume_optional
  File "argparse.pyc", line 1978, in take_action
  File "argparse.pyc", line 1119, in __call__
  File "nvda.pyw", line 86, in print_help
  File "argparse.pyc", line 2585, in format_help
  File "argparse.pyc", line 286, in format_help
  File "argparse.pyc", line 217, in format_help
  File "argparse.pyc", line 217, in <listcomp>
  File "argparse.pyc", line 217, in format_help
  File "argparse.pyc", line 217, in <listcomp>
  File "argparse.pyc", line 543, in _format_action
  File "argparse.pyc", line 640, in _expand_help
ValueError: unsupported format character 'T' (0x54) at index 74
Traceback (most recent call last):
  File "nvda.pyw", line 217, in <module>
  File "argparse.pyc", line 1902, in parse_known_args
  File "argparse.pyc", line 2114, in _parse_known_args
  File "argparse.pyc", line 2054, in consume_optional
  File "argparse.pyc", line 1978, in take_action
  File "argparse.pyc", line 1119, in __call__
  File "nvda.pyw", line 86, in print_help
  File "argparse.pyc", line 2585, in format_help
  File "argparse.pyc", line 286, in format_help
  File "argparse.pyc", line 217, in format_help
  File "argparse.pyc", line 217, in <listcomp>
  File "argparse.pyc", line 217, in format_help
  File "argparse.pyc", line 217, in <listcomp>
  File "argparse.pyc", line 543, in _format_action
  File "argparse.pyc", line 640, in _expand_help
ValueError: unsupported format character 'T' (0x54) at index 74

#### NVDA version:

NVDA 2023.3.4
NVDA 2024.1
alpha-31823,1791eb96
alpha-31858,2d865027

Alphas were installed, other versions were running from the launcher.

#### Windows version:

Windows 11 (64-bit) Version: 23H2, Build: 22631.3447

**Comment by XLTechie** [comment]
Testing a fix.
