### ISSUE TITLE
Regression: when rebuilding `scons source`, the `source` target was obscured and could not be run from source.

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#16535]
Related: #16208

The `Alias` function is used in `nvdaHelper\liblouis\sconscript` to set the alias of `testTable` to the `source` target.
This caused the `source' target to be masked and the build system did not build it correctly.

### Steps to reproduce:

1. `git clone --recursive https://github.com/YOUR-USERNAME/nvda.git`
2. `cd nvda`
3. `scons source`
4. `runnvda`

### Actual behavior:

NVDA is not running.

### Expected behavior:

NVDA running from source

### NVDA logs, crash dumps and other attachments:

```log
INFO - __main__ (06:38:38.434) - MainThread (6664):
Starting NVDA version source-2fb42d5-2fb42d5
INFO - core.main (06:38:38.666) - MainThread (6664):
Config dir: D:\NVDA\hwf1324\nvda\source\userConfig
INFO - config.ConfigManager._loadConfig (06:38:38.669) - MainThread (6664):
Loading config: D:\NVDA\hwf1324\nvda\source\userConfig\nvda.ini
CRITICAL - __main__ (06:38:38.747) - MainThread (6664):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 415, in <module>
    core.main()
  File "core.py", line 649, in main
    import NVDAHelper
  File "NVDAHelper.py", line 32, in <module>
    import eventHandler
  File "eventHandler.py", line 13, in <module>
    import api
  File "api.py", line 15, in <module>
    import review
  File "review.py", line 15, in <module>
    from NVDAObjects import NVDAObject, NVDAObjectTextInfo
  File "NVDAObjects\__init__.py", line 25, in <module>
    from displayModel import DisplayModelTextInfo
  File "displayModel.py", line 17, in <module>
    import mouseHandler
  File "mouseHandler.py", line 10, in <module>
    import gui
  File "gui\__init__.py", line 15, in <module>
    import ui
  File "ui.py", line 29, in <module>
    import braille
  File "braille.py", line 35, in <module>
    import louisHelper
  File "louisHelper.py", line 23, in <module>
    import louis
ModuleNotFoundError: No module named 'louis'
```

#### NVDA installed/portable/running from source:
source
#### NVDA version:
master
#### Does the issue still occur after restarting your computer?
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by hwf1324** [comment]
Cc: @LeonarddeR , @seanbudd 
I'm not sure how to set up in the build script how a build target depends on build targets in other files, maybe using Exporting Variables?
Maybe we should move `testTable` to the test build script.
