### ISSUE TITLE
bug in the windows 11 mail app with nvda

### ISSUE THREAD

**Issue by mjonsson1986** [nvaccess/nvda#16639]
in the windows 11 mail app
you can browse around the emails
but when you try to read one it are inpossible with the latest nvda dev snapshot
the folloing error come in the log

ERROR - eventHandler.executeEvent (17:35:22.541) - MainThread (16180):
error executing event: gainFocus on <NVDAObjects.Dynamic_MailWordDocumentWordDocumentEditableTextWithAutoSelectDetectionUIA object at 0x088BC290> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 340, in executeEvent
  File "eventHandler.pyc", line 415, in doPreGainFocus
  File "browseMode.pyc", line 1533, in event_treeInterceptor_gainFocus
  File "speech\sayAll.pyc", line 122, in readText
  File "speech\sayAll.pyc", line 297, in nextLine
  File "speech\types.pyc", line 49, in _flattenNestedSequences
  File "speech\types.pyc", line 49, in <genexpr>
  File "speech\speech.pyc", line 1376, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 315, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 438, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException
ERROR - scriptHandler.executeScript (17:35:22.948) - MainThread (16180):
error executing script: <bound method CursorManager.script_moveByLine_back of <appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x01232AB0>> with gesture 'uppåtpil'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 271, in script_moveByLine_back
  File "cursorManager.pyc", line 172, in _caretMovementScriptHelper
  File "speech\speech.pyc", line 1334, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1376, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 315, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 438, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException

i run windows 11 latest insider

**Comment by josephsl** [comment]
Hi, I assume NVDA alpha builds? Next time, fill out the template please.

**Comment by Adriani90** [comment]
@michaelDCurran I think this might be related to #16214?

**Comment by seanbudd** [comment]
Welcome @mjonsson1986 ,

We are unable to process this issue as it stands.
Please fill out the issue template fully. We need information like exact steps to reproduce, and versions of the software involved.
When this is done, let us know and we can reopen the issue. Alternatively, open a new issue.
 
Kind Regards,
NV Access Software Developers
