### ISSUE TITLE
NVDA fails to access the message area in Windows Mail.

### ISSUE THREAD

**Issue by Aleskis** [nvaccess/nvda#16689]
When entering a message in Windows Mail, the arrows trigger the error sound and nothing is read. The problem persists in the editing area when you try to reply to the message.

### Steps to reproduce:
1. Open Windows Mail and focus a message subject.
2. Press enter.

### NVDA logs, crash dumps and other attachments:
Input: kb(laptop):upArrow
IO - speech.speech.speak (14:54:50.851) - MainThread (10640):
Speaking [' Non lu GitHub [GitHub] A third-party OAuth application has been added to your account   mer. 12/06        Hey Aleskis! A third-party OAuth application (Eleven Labs) with user:email scopes was recently authorized to access your account. Visit https://github.com/settings/connections/applications/815219b44740212c1a75 for more information. To see this and other se', '4 sur 233', 'niveau 1', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (14:54:51.944) - winInputHook (13524):
Input: kb(laptop):enter
IO - speech.speech.speak (14:54:52.012) - MainThread (10640):
Speaking ['Navigation', 'groupe', CancellableSpeech (still valid)]
IO - speech.speech.speak (14:54:52.055) - MainThread (10640):
Speaking ['Navigation', 'bouton', 'réduit', CancellableSpeech (still valid)]
DEBUG - treeInterceptorHandler.update (14:54:52.064) - MainThread (10640):
Adding new treeInterceptor to runningTable: <appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x012C0910>
IO - speech.speech.speak (14:54:52.069) - MainThread (10640):
Speaking ['Volet de lecture', 'groupe', CancellableSpeech (still valid)]
IO - speech.speech.speak (14:54:52.073) - MainThread (10640):
Speaking ['Volet de lecture', 'groupe', CancellableSpeech (still valid)]
IO - speech.speech.speak (14:54:52.346) - MainThread (10640):
Speaking ['document', CancellableSpeech (still valid)]
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (14:54:52.565) - watchdog (14300):
Potential freeze, waiting up to 10 seconds.
ERROR - eventHandler.executeEvent (14:54:52.354) - MainThread (10640):
error executing event: gainFocus on <NVDAObjects.Dynamic_MailWordDocumentWordDocumentEditableTextWithAutoSelectDetectionUIA object at 0x0998A8F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 340, in executeEvent
  File "eventHandler.pyc", line 415, in doPreGainFocus
  File "browseMode.pyc", line 1555, in event_treeInterceptor_gainFocus
  File "speech\speech.pyc", line 1416, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1458, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 317, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 438, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (14:54:53.066) - watchdog (14300):
Recovered from potential freeze after 1.000426300000072 seconds.
IO - inputCore.InputManager.executeGesture (14:54:54.320) - winInputHook (13524):
Input: kb(laptop):upArrow
ERROR - scriptHandler.executeScript (14:54:54.331) - MainThread (10640):
error executing script: <bound method CursorManager.script_moveByLine_back of <appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x012C0910>> with gesture 'flèche haut'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 271, in script_moveByLine_back
  File "cursorManager.pyc", line 172, in _caretMovementScriptHelper
  File "speech\speech.pyc", line 1416, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1458, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 317, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 438, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException
IO - inputCore.InputManager.executeGesture (14:54:55.956) - winInputHook (13524):
Input: kb(laptop):downArrow
ERROR - scriptHandler.executeScript (14:54:55.967) - MainThread (10640):
error executing script: <bound method CursorManager.script_moveByLine_forward of <appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x012C0910>> with gesture 'flèche bas'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 275, in script_moveByLine_forward
  File "cursorManager.pyc", line 172, in _caretMovementScriptHelper
  File "speech\speech.pyc", line 1416, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1458, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 317, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 438, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException
IO - inputCore.InputManager.executeGesture (14:55:00.235) - winInputHook (13524):
Input: kb(laptop):NVDA+f1
DEBUG - gui.contextHelp.bindHelpEvent (14:55:00.241) - MainThread (10640):
Did context help binding for LogViewer
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (14:55:00.739) - watchdog (14300):
Potential freeze, waiting up to 10 seconds.
INFO - watchdog.waitForFreezeRecovery (14:55:01.739) - watchdog (14300):
Starting freeze recovery after 1.5006918999997652 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (14:55:01.740) - watchdog (14300):
Listing stacks for Python threads:
Python stack for thread 3124 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x07684378>)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "watchdog.pyc", line 382, in run
  File "threading.pyc", line 629, in wait
  File "threading.pyc", line 327, in wait

Python stack for thread 14300 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 159, in _watcher
  File "watchdog.pyc", line 166, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 6488 (Thread-7):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "C:\Users\alexi\AppData\Roaming\nvda\addons\translate\globalPlugins\translate\updater.py", line 22, in run
    time.sleep(1)

Python stack for thread 13524 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 3348 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 544, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 11252 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 12420 (Thread-4):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "C:\Users\alexi\AppData\Roaming\nvda\addons\IBMTTS\synthDrivers\_ibmeci.py", line 382, in run
    func, args, kwargs = callbackQueue.get()
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 11508 (Thread-3):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "C:\Users\alexi\AppData\Roaming\nvda\addons\IBMTTS\synthDrivers\_ibmeci.py", line 180, in run
    user32.GetMessageA(byref(msg), 0, 0, 0)

Python stack for thread 8868 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 258, in run

Python stack for thread 14332 (ScheduleThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "utils\schedule.pyc", line 83, in run

Python stack for thread 10640 (MainThread):
  File "nvda.pyw", line 415, in <module>
  File "core.pyc", line 923, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 853, in processRequest
  File "core.pyc", line 869, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "keyboardHandler.pyc", line 571, in executeScript
  File "inputCore.pyc", line 224, in executeScript
  File "scriptHandler.pyc", line 295, in executeScript
  File "gui\blockAction.pyc", line 78, in funcWrapper
  File "globalCommands.pyc", line 2923, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1489, in info
  File "logHandler.pyc", line 233, in _log
  File "gui\blockAction.pyc", line 78, in funcWrapper
  File "gui\logViewer.pyc", line 138, in activate

INFO - globalCommands.script_navigatorObject_devInfo (14:55:02.303) - MainThread (10640):
Developer info for navigator object:
name: ''
role: DOCUMENT
processID: 11320
roleText: None
states: FOCUSABLE, FOCUSED, READONLY
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_MailWordDocumentWordDocumentEditableTextWithAutoSelectDetectionUIA object at 0x0998A8F0>
Python class mro: (<class 'NVDAObjects.Dynamic_MailWordDocumentWordDocumentEditableTextWithAutoSelectDetectionUIA'>, <class 'appModules.hxmail.MailWordDocument'>, <class 'NVDAObjects.UIA.wordDocument.WordDocument'>, <class 'UIAHandler.browseMode.UIADocumentWithTableNavigation'>, <class 'documentBase.DocumentWithTableNavigation'>, <class 'NVDAObjects.UIA.wordDocument.WordDocumentNode'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.winword.WordDocument'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'NVDAObjects.behaviors.EditableTextWithSuggestions'>, <class 'NVDAObjects.behaviors.InputFieldWithSuggestions'>, <class 'NVDAObjects.behaviors.EditableTextBase'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=217, top=186, width=751, height=478)
value: None
TextInfo: <class 'NVDAObjects.UIA.wordDocument.WordDocumentTextInfo'>
appModule: AppModule(hxmail, appName='hxoutlook', processID=11320)
appModule.productName: 'microsoft.windowscommunicationsapps'
appModule.productVersion: '16005.14326.21944.0'
appModule.helperLocalBindingHandle: c_long(131238440)
windowHandle: 263810
windowClassName: 'Windows.UI.Core.CoreWindow'
windowControlID: 0
windowStyle: 1409286144
extendedWindowStyle: 2621440
windowThreadID: 10428
windowText: 'Courrier'
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x34e5e88 at b442c10>
UIA automationID: RootFocusControl
UIA frameworkID: 
UIA runtimeID: (42, 263810, 4, 262503116, 0)
UIA providerDescription: [pid:11320,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:MSOIMM.dll)]
UIA className: _WwG
UIA patterns available: TextPattern, ScrollPattern, LegacyIAccessiblePattern

#### NVDA version:
Version : alpha-32397,ad9ed733 (2024.3.0.32397)

#### Windows version:
Édition	Windows 11 Professionnel
Version	23H2
System Build 	22631.3737
Windows Feature Experience Pack 1000.22700.1009.0

#### Name and version of other software in use when reproducing the issue:
Windows Mail Version 16005.14326.21944.0

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Works great with NVDA 2024.1

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
@Aleskis , please provide all the sections of the template with the corresponding answers; or are the remaining sections commented by mistake by chance? More specifically, the log with the corresponding error would be useful in a first place.

**Comment by seanbudd** [comment]
Please open a new issue and fill out the bug report template fully

**Comment by seanbudd** [comment]
Nevermind, this was a formatting issue

**Comment by seanbudd** [comment]
Note that support for Windows Mail is ending this year: https://support.microsoft.com/en-gb/office/windows-mail-calendar-and-people-are-becomin[…]96e1-bc9afdc08e31?OCID=WinMail_2024Outlook_BizbarLearnMore

**Comment by seanbudd** [comment]
Note that support for Windows Mail is ending this year: https://support.microsoft.com/en-gb/office/windows-mail-calendar-and-people-are-becoming-outlook-773ecb94-5b16-4155-96e1-bc9afdc08e31?OCID=WinMail_2024Outlook_BizbarLearnMore

**Comment by Aleskis** [comment]
Does this mean that no fix will be offered? If so, it's a bad new, as many people choose to stay with mail rather than switch to Outlook, as the latter's ergonomics require much more tabbing to navigate. For example, entering the subject of a message does not open it. But that's another subject.

**Comment by seanbudd** [comment]
We will investigate it, but it less likely a fix will be occur, particularly if the fix is complex or work is needed on Microsofts time.

**Comment by gauravahir28** [comment]
Can this please be investigated as soon as possible? 
This is very frustrating as nothing is being read out with NVDA. 
It does work well with NVDA 2024.2! 
Even though Microsoft is ending support, many of us are choosing to stay with Windows Mail because the new Outlook isn't good with screen readers (at least for me).

**Comment by josephsl** [comment]
Hi,

Two things:

1. New Outlook: it uses Edge WebView2 interface, so we may need to come up with an app module for it (the new Outlook is one of the scenarios I had in mind when working on it).
2. This may have to do with Mail not responding to UIA remote operations request.

@MichaelDCurran, is this something worth documenting or might be fixed somehow, perhaps creating an exception for certain app/control combinations?

Thanks.
