### ISSUE TITLE
2024.4 Alphas are spamming logs with symbol files not found

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#16981]
### Steps to reproduce:

Run a recent alpha. Try to find an error or anything else in the log (debug level).

### Actual behavior:

Notice that it's difficult to find anything, because the log is full and filling, of tracebacks related to files not found.

```
IO - speech.speech.speak (04:38:17.638) - MainThread (25064):
Speaking ['alpha', '12 of 69', CancellableSpeech (still valid)]
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (04:38:17.638) - MainThread (25064):
Error loading 'cldr' symbols for locale 'en_GB'
Traceback (most recent call last):
  File "characterProcessing.pyc", line 414, in _getSpeechSymbolsForLocale
  File "characterProcessing.pyc", line 818, in getSymbols
  File "characterProcessing.pyc", line 64, in fetchLocaleData
  File "characterProcessing.pyc", line 826, in _initSymbols
FileNotFoundError: No 'cldr' data for locale 'en_GB'
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (04:38:17.644) - MainThread (25064):
Error loading 'builtin' symbols for locale 'en_GB'
Traceback (most recent call last):
  File "characterProcessing.pyc", line 414, in _getSpeechSymbolsForLocale
  File "characterProcessing.pyc", line 818, in getSymbols
  File "characterProcessing.pyc", line 64, in fetchLocaleData
  File "characterProcessing.pyc", line 826, in _initSymbols
FileNotFoundError: No 'builtin' data for locale 'en_GB'
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (04:38:17.644) - MainThread (25064):
Error loading 'cldr' symbols for locale 'en_GB'
Traceback (most recent call last):
  File "characterProcessing.pyc", line 414, in _getSpeechSymbolsForLocale
  File "characterProcessing.pyc", line 818, in getSymbols
  File "characterProcessing.pyc", line 64, in fetchLocaleData
  File "characterProcessing.pyc", line 826, in _initSymbols
FileNotFoundError: No 'cldr' data for locale 'en_GB'
```
(And again, and again, and again...)

### Expected behavior:

Maybe one notice about files not found the first time the locale is used, and then no more.
I'm also concerned it's having an effect of performance, to be polling for these files two or three times every utterance, if indeed that's what's happening.

### NVDA logs, crash dumps and other attachments:

[nvda-logSpam.txt](https://github.com/user-attachments/files/16540439/nvda-logSpam.txt)

#### NVDA installed/portable/running from source:

Portable

#### NVDA version:

alpha-33301,b8de34e9

#### Windows version:

11 Home 23H3

#### Name and version of other software in use when reproducing the issue:

N/A

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes. 2024.3beta6 (installed), is not doing this.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by XLTechie** [comment]
@LeonarddeR, sorry to bomb you with this one, but I thought I remembered you doing something with symbols recently.

I'll bisect if I have to, but haven't had time yet.

**Comment by LeonarddeR** [comment]
This is most likely my fault indeed. I'll have a look
