### ISSUE TITLE
Speech gets stuck on one item when arrowing too fast in add-on store

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#17351]
### Steps to reproduce:

Reported by andfal13 via email:

1. Open the add-on store.
2. Hold down the down arrow key to move through many items (about 5 seconds).
3. Press the up arrow a few times one second after the other

### Actual behavior:

NVDA stops on one item and reads the full information, ignoring any keystrokes.

In some cases, holding down (not just pressing) is enough to "clear" the issue without waiting until it finishes.

### Expected behavior:

NVDA should respond to key presses even after moving a long distance through the list.

### NVDA logs, crash dumps and other attachments:

Log fragment (with several notes in parentheses):

DEBUG - gui.addonStoreGui.controls.details.AddonDetails._updatedListItem (09:13:40.258) - MainThread (10480):
Setting listItem: AddonListItemVM: tesseractOCR-Channel.STABLE, AvailableAddonStatus.AVAILABLE
IO - inputCore.InputManager.executeGesture (09:13:40.273) - winInputHook (18596):
Input: kb(desktop):upArrow
DEBUG - gui.addonStoreGui.controls.details.AddonDetails._updatedListItem (09:13:40.358) - MainThread (10480):
Setting listItem: AddonListItemVM: tesseractOCR-Channel.STABLE, AvailableAddonStatus.AVAILABLE
(repeated many times - note: note specific to these particular add-ons at all, it was just where I was in the list)

DEBUG - gui.addonStoreGui.viewModels.store.AddonStoreVM._onSelectedItemChanged (09:13:47.558) - MainThread (10480):
Setting selection: AddonListItemVM: switchSynth-Channel.STABLE, AvailableAddonStatus.AVAILABLE

(Repeated a few times)

DEBUG - speech.manager.SpeechManager._handleIndex (09:13:47.558) - MainThread (10480):
Unknown index 82, speech probably cancelled from main thread.
DEBUG - gui.addonStoreGui.controls.addonList.AddonVirtualList.OnItemDeselected (09:13:47.593) - MainThread (10480):
item deselected
DEBUG - gui.addonStoreGui.viewModels.addonList.AddonListVM.setSelection (09:13:47.593) - MainThread (10480):
selected Item: None
DEBUG - gui.addonStoreGui.controls.addonList.AddonVirtualList.OnItemSelected (09:13:47.593) - MainThread (10480):
item selected: 138
DEBUG - gui.addonStoreGui.viewModels.addonList.AddonListVM.setSelection (09:13:47.593) - MainThread (10480):
selected Item: AddonListItemVM: subtitle_reader-Channel.STABLE, AvailableAddonStatus.AVAILABLE
DEBUG - gui.addonStoreGui.controls.addonList.AddonVirtualList.OnItemDeselected (09:13:47.653) - MainThread (10480):
item deselected
DEBUG - gui.addonStoreGui.viewModels.addonList.AddonListVM.setSelection (09:13:47.653) - MainThread (10480):
selected Item: None
DEBUG - gui.addonStoreGui.controls.addonList.AddonVirtualList.OnItemSelected (09:13:47.658) - MainThread (10480):
item selected: 137
DEBUG - gui.addonStoreGui.viewModels.addonList.AddonListVM.setSelection (09:13:47.658) - MainThread (10480):
selected Item: AddonListItemVM: stationPlaylist-Channel.STABLE, AvailableAddonStatus.AVAILABLE
IO - speech.speech.speak (09:13:47.723) - MainThread (10480):
Speaking [LangChangeCommand ('en_US'), 'StationPlaylist; Status: Available; Available version: 24.03; Channel: Stable; Publisher: ChrisDuffley', '138 of 176', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (09:13:47.723) - MainThread (10480):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (09:13:47.723) - MainThread (10480):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (09:13:47.723) - MainThread (10480):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1863, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1780, in _get__IA2Relations
NotImplementedError
IO - speech.speech.speak (09:13:47.738) - MainThread (10480):
Speaking [LangChangeCommand ('en_US'), 'StationPlaylist; Status: Available; Available version: 24.03; Channel: Stable; Publisher: ChrisDuffley', '138 of 176', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (09:13:47.743) - MainThread (10480):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (09:13:47.743) - MainThread (10480):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (09:13:47.743) - MainThread (10480):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1863, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1780, in _get__IA2Relations
NotImplementedError
DEBUG - gui.addonStoreGui.controls.details.AddonDetails._updatedListItem (09:13:47.758) - MainThread (10480):
Setting listItem: AddonListItemVM: switchSynth-Channel.STABLE, AvailableAddonStatus.AVAILABLE

#### NVDA version:

NVDA 2024.4 installed

#### Windows version:

Windows 11 (64-bit) Version: 23H2, Build: 22631.4391

**Comment by seanbudd** [comment]
We can address this by adding a delay to re-drawing controls when navigating between list items

**Comment by Adriani90** [comment]
@seanbudd this issue is quite severe, I managed to make my computer unusable while wrrowing through the list of add-ons in the add-on store.
Can you please have a look?
Especially due to the fact that navigation shortcuts such asn ctrl+home and end, pg up or pg down do not work in this window, users are limited to holding up and down arrow key to navigate faster through the list.

Str:
1. Open add-on store
2. In the available add-ons tab, tab to channels and choose "all"
3. Enable the checkbox to also include incompatible add-ons
4. Tab to the list of add-ons
5. Press and hold down arrow key for 10 seconds
6. press and hold up arrow key for some seconds
7. Repeat steps 5 and 6 for a while

Actual: NVDA gets unusable and freezes completely, the keyboard doesn't respond anymore and the CPU runs high
Expected: NVDA should not freeze

System info: Asus ROG strix 15, Intel I12900HK, 32 gb ram, NVIDIA gtx 3070TI 8gb DDR.
Windows 11 25 H2
NVDA alpha-53423,57f2e9dc (2026.1.0.53423)

cc: @CyrilleB79, @SaschaCowley

**Comment by Adriani90** [comment]
This is one log file that I could catch so far, it seems after a while the speech gets stuck, but when switching windows NVDA freezes and watchdog tries to recover multiple times, causing the computer to become unusable after a while unless I restart NVDA by double clicking the desktop shortcut.

[nvda-old.txt](https://github.com/user-attachments/files/23593255/nvda-old.txt)

**Comment by seanbudd** [comment]
I've changed this to a P2 as the freeze is more severe than we initially thought. Unfortunately, we do not have time to investigate this in the near future.

@Adriani90 - please consider the number of tickets you ask us to work on each day, it's not feasible for us to pick up work on several tickets each day. We would be constantly dropping work and never finishing it.

**Comment by Adriani90** [comment]
@seanbudd it's not that I would like you to work on such issues, but to try making clear the severity and that this is on your radar. The triaging should in my opinion reflect the current situation properly. Whether you want to work on it or not, this is solely your decision at NV Access. I am sure you have an internal roadmap where you can put such issues on.
