### ISSUE TITLE
Text cannot be read in PowerPoint edit fields

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#17390]
### Steps to reproduce:
* Open a PowerPoint presentation
* Focus a text area (or create it), e.g. on the title
* Press F2 to edit it
* Press `control+k` to insert a link
* In the edit field of the dialog that opens, try to write something and to re-read it with arrows or `NVDA+upArrow`

### Actual behavior:
Text is not read
### Expected behavior:
Text should be read
### NVDA logs, crash dumps and other attachments:
```
ERROR - scriptHandler.executeScript (09:59:47.161) - MainThread (30944):
error executing script: <bound method GlobalCommands.script_reportCurrentLine of <globalCommands.GlobalCommands object at 0x06744C90>> with gesture 'NVDA+flèche haut'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "globalCommands.pyc", line 211, in script_reportCurrentLine
  File "NVDAObjects\window\edit.pyc", line 1107, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 895, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'

```
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.4rc1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
PowerPoint Microsoft® PowerPoint® 2016 MSO (Version 2410 Build 16.0.18129.20100) 32 bits 
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
* NVDA 2020.4 is OK
* The issue appears in NVDA 2021.1

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment]
@CyrilleB79 does this also happen in Powerpoint 365?
If yes, this might be a quite critical regression.

**Comment by CyrilleB79** [comment]
I am not subscribed to 365. Could you test yourself please?

**Comment by SaschaCowley** [comment]
Reproducible with NVDA alpha-36748,f6287baa (2025.2.0.36748) and Microsoft® PowerPoint® for Microsoft 365 MSO (Version 2505 Build 16.0.18827.20102) 64-bit.
