### ISSUE TITLE
Nvda crashes when selecting whole text in specific source files in Android studio

### ISSUE THREAD

**Issue by PeterLecky** [nvaccess/nvda#17418]
Actually do not know what causes this. It happens in larger files but not in all large files. I prepared file which is not compillable (see zipped attachment, it defines few constants a lot of times), but this happens also in syntactically correct files.

### Steps to reproduce:
1. Open Android studio and attached java file in code editor
2. Press ctrl+a to select whole file
3. Nvda now completely crashes

It is also possible to reproduce this crash from python console
1. Open Android studio and attached java file in code editor
2. invoke python console (nvda+ctrl+z)
3. invoke import textInfos;len(focus.makeTextInfo(textInfos.POSITION_ALL).text)

### Actual behavior:
Nvda completely crashes and there are no any relevant information in %tmp%\nvda-old.log

### NVDA logs, crash dumps and other attachments:
[BadConstants.zip](https://github.com/user-attachments/files/17816136/BadConstants.zip)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
 Nvda 2024.4

#### Windows version:
Windows 10 22H2,

#### Name and version of other software in use when reproducing the issue:
Android Studio Koala | 2024.1.1 Patch 1
Build #AI-241.18034.62.2411.12071903, built on July 10, 2024
Runtime version: 17.0.11+0--11852314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
  io.wisetime.plugins.window.branch (1.1.0)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Reproducible on older versions of NVDA

**Comment by Adriani90** [comment]
@PeterLecky Please test with Android studio 2024.2.1 since INtelliJ is updated there as well. are you still having this issue with that version?
Can you also test with IntelliJ 2024.3 which has been released shortly? Most of the times Android studio lags behind IntelliJ, so IntelliJ current version should always be tested as well when encountering issues with Android Studio in general.

**Comment by PeterLecky** [comment]
Hello,
Upgraded Android studio:
Android Studio Ladybug | 2024.2.1 Patch 2
Build #AI-242.23339.11.2421.12550806, built on October 24, 2024
Runtime version: 21.0.3+-12282718-b509.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
   ide.experimental.ui=true
   i18n.locale=
Non-Bundled Plugins:
   io.wisetime.plugins.window.branch (1.1.0)

And it still crashes. I remember that i saw something also in nvda log 
in the past, latest nvda version crashes silently without any data in 
the log. I have old records (I talked about it with Tony Malykh in the 
past because i saw it first time with indent nav) so here it is:
IO - inputCore.InputManager.executeGesture (14:22:23.728) - winInputHook 
(5680):
Input: kb(laptop):alt+NVDA+downArrow
ERROR - scriptHandler.executeScript (14:22:23.739) - MainThread (7196):
error executing script: <bound method 
EditableIndentNav.script_moveToNextSibling of 
<NVDAObjects.Dynamic_MyCodeEditorEditableTextWithoutAutoSelectDetectionJABEditableIndentNav 
object at 0x07EC1D90>> with gesture 'alt+NVDA+down arrow'
Traceback (most recent call last):
   File "scriptHandler.pyc", line 295, in executeScript
   File 
"C:\Users\Peter\AppData\Roaming\nvda\addons\IndentNav\globalPlugins\indent_nav.py", 
line 439, in script_moveToNextSibling
     self.move(1, [msgEditable])
   File 
"C:\Users\Peter\AppData\Roaming\nvda\addons\IndentNav\globalPlugins\indent_nav.py", 
line 496, in move
     self.moveInEditable(increment, errorMessages[0], unbounded, op, 
speakOnly=speakOnly, moveCount=moveCount)
   File 
"C:\Users\Peter\AppData\Roaming\nvda\addons\IndentNav\globalPlugins\indent_nav.py", 
line 499, in moveInEditable
     with self.getLineManager() as lm:
   File 
"C:\Users\Peter\AppData\Roaming\nvda\addons\IndentNav\globalPlugins\indent_nav.py", 
line 304, in __enter__
     documentText = document.text
   File "baseObject.pyc", line 41, in __get__
   File "textInfos\offsets.pyc", line 593, in _get_text
   File "NVDAObjects\JAB\__init__.pyc", line 164, in _getTextRange
   File "JABHandler.pyc", line 479, in getAccessibleTextRange
OSError: exception: access violation writing 0x07F35000

**Comment by Adriani90** [comment]
What happens if indentnav is disabled? Is still crashing?
Is there any possibility to test with narator? 
and I see you enabled experimental UI, at least it‘s set to true. Where does that setting come from? And does it have any effect when you set it to false?

**Comment by PeterLecky** [comment]
> What happens if indentnav is disabled? Is still crashing?
Yes, tested also with all plugins disabled
> Is there any possibility to test with narator?
It seems that Narator does not support java applications. Didn't crash 
after ctrl+a but there is no feedback at all in code editor.
> and I see you enabled experimental UI, at least it‘s set to true. Where 
> does that setting come from? And does it have any effect when you set it 
> to false?
It's a new thing in latest version of Android studio, they enabled it 
for all users by default, it was disabled in older versions and NVDA 
crashed also in that case.
Thanks for your time.

**Comment by PeterLecky** [comment]
I have few more info. I have installed Jaws (full installer has 1.2GB, unbeliewable) and i can select and copy whole code in code editor without any crashes of jaws.
Peter

**Comment by PeterLecky** [comment]
Ah... Sorry for closing and thanks for reopening, it was my mistake.

**Comment by seanbudd** [comment]
It seems likely this is a bug in Java Access Bridge. Unfortunately we are stuck on an out of date version until we upgrade NVDA to 64bit see https://github.com/nvaccess/nvda/discussions/16304

**Comment by mltony** [comment]
cc: @dmitrii-drobotov -in case you can come up with some kind of workaround for this.

**Comment by dmitrii-drobotov** [comment]
Thanks for the heads-up @mltony. Here are my observations after quickly looking into this:
* I can reproduce it with a basic Java Swing app using the default JTextArea component if I paste the same text there. So it's not specific to Android Studio/IntelliJ.
* The size of the text doesn't seem to be the cause, I tried much larger files with 50000+ lines of code, and with them NVDA works slower or might freeze for a bit, but at least it doesn't crash.
* I also don't get anything related in NVDA logs even with the most verbose level, and the debugger doesn't stop on any uncaught exception before crashing. Does anybody have any tips on how I could debug this? 
If I remember correctly, there was a way to enable more logs in the Java Access Bridge, so I could try looking into this.

**Comment by PeterLecky** [comment]
Please, is there at least some way to stop nvda from crashing when 
requesting whole text? I see that it is actually not possible to 
properly return whole text in some situations, because of bug in JAB, 
but is it possible to try&catch some exception or something similar in 
python to keep NVDA running?
I am using IndentNav addon and it works perfectly in all files where 
nvda does not crash. I believe that it is better to have feature which 
sometimes does not work than have crashes in screen reader.
With best
Peter

**Comment by thgcode** [comment]
Maybe this can help the investigation (tested with NVDA version source-master-1edb075):
I enabled faulthandler (Python console command example):

```
import faulthandler
faulthandler.enable(open("path.to.some.file, "w"))
```

On my machine I got the error below (removed some lines for brevity). Looking at the AccessBridgePackages.h file from the JDK, I found the following definition:

```
#define MAX_BUFFER_SIZE   10240

    typedef struct GetAccessibleTextRangePackageTag {
        long vmID;
        JOBJECT64 AccessibleContext;
        jint start;
        jint end;
        wchar_t rText[MAX_BUFFER_SIZE];
    } GetAccessibleTextRangePackage;
```

It seems this MAX_BUFFER_SIZE is the buffer size Java Access Bridge can transfer on a single NVDA call, if NVDA requests a selection with a bigger length than this buffer limit, it can read or write past the buffer end. In some situations it can cause crashes, however in others it seems NVDA runs normaly if the buffer size is near 10240 characters. It seems maybe we would need to make multiple calls to get all the text, or limit to 10240 characters if we want to keep a single call.

Error output from faulthandler:
```
Windows fatal exception: access violation

Current thread 0x000025d0 (most recent call first):
  File "D:\nvda\source\JABHandler.py", line 656 in getAccessibleTextRange
  File "D:\nvda\source\NVDAObjects\JAB\__init__.py", line 176 in _getTextRange
  File "D:\nvda\source\textInfos\offsets.py", line 637 in _get_text
  File "D:\nvda\source\baseObject.py", line 39 in __get__
  File "D:\nvda\source\speech\speech.py", line 855 in getObjectSpeech
  File "D:\nvda\source\speech\speech.py", line 800 in speakObject
  File "D:\nvda\source\NVDAObjects\__init__.py", line 1205 in reportFocus
  File "D:\nvda\source\NVDAObjects\JAB\__init__.py", line 594 in reportFocus
  File "D:\nvda\source\NVDAObjects\__init__.py", line 1369 in event_gainFocus
  File "D:\nvda\source\NVDAObjects\JAB\__init__.py", line 649 in event_gainFocus
  File "D:\nvda\source\eventHandler.py", line 128 in next
  File "D:\nvda\source\eventHandler.py", line 119 in __init__
  File "D:\nvda\source\eventHandler.py", line 353 in executeEvent
  File "D:\nvda\source\eventHandler.py", line 87 in _queueEventCallback
  File "D:\nvda\source\queueHandler.py", line 67 in flushQueue
  File "D:\nvda\source\queueHandler.py", line 102 in pumpAll
  File "D:\nvda\source\core.py", line 984 in Notify
  File "D:\nvda\source\core.py", line 968 in processRequest
  File "D:\nvda\.venv\Lib\site-packages\wx\core.py", line 3427 in <lambda>
  File "D:\nvda\.venv\Lib\site-packages\wx\core.py", line 2262 in MainLoop
  File "D:\nvda\source\core.py", line 1041 in main
  File "D:\nvda\source\nvda.pyw", line 314 in <module>
```

**Comment by mltony** [comment]
@thgcode that's a great find! If this is confirmed - that would be an egregious bug in Java accessibility bridge. Would you consider reporting this to Java maintainers?
In theory we can work around this in NVDA by making multiple calls to get the text of the entire document, but I suspect that would be too slow in many cases - I routinely work with 1MB documents for example; it would take 100 IPC calls to get the text of the entire document - and that's on each key stroke, I suspect that would be unbearably sluggish.

**Comment by thgcode** [comment]
@mltony Yes, I thought of reporting it to the OpenJDK developers, but I don't know how to test it outside NVDA, to create a reproducible example to isolate and test only the Java Access Bridge component, to be sure the bug is in the component.

**Comment by thgcode** [comment]
@PeterLecky I created a draft Pull Request #17604 , in this pull request NVDA will get the text in parts, to not overload the buffer limit, can you please test with this pull request to see if it stops crashing on your machine as well?

**Comment by PeterLecky** [comment]
Hello,
Seems to work as expected, without crashes. Thank You.
