### ISSUE TITLE
Error with console window on NVDA R4619

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1742]
**Reported by PZajda on 2011-09-01 19:44**
When I run NVDA using python nvda.pyw and go to a console window, I have the following error:
ERROR - NVDAObjects.behaviors.Dynamic_IAccessibleWinConsoleWindowNVDAObject._monitor (21:15:03):
Error getting initial lines
Traceback (most recent call last):
  File "C:\nvda\main\source\NVDAObjects\behaviors.py", line 217, in _monitor
    oldLines = self._getTextLines()
  File "C:\nvda\main\source\NVDAObjects\window\winConsole.py", line 48, in _getTextLines
    return winConsoleHandler.getConsoleVisibleLines()
  File "C:\nvda\main\source\winConsoleHandler.py", line 96, in getConsoleVisibleLines
    consoleScreenBufferInfo=wincon.GetConsoleScreenBufferInfo(consoleOutputHandle)
  File "C:\nvda\main\source\wincon.py", line 56, in GetConsoleScreenBufferInfo
    raise WinError()
WindowsError: [6](Error) Descripteur non valide

It is the same case if I try to read the console which execute NVDA.pyw or another console.

**Comment by bhavyashah** [comment]
@michaelDCurran @jcsteh In conclusion, does https://github.com/nvaccess/nvda/issues/1742#issuecomment-155292168 imply that this issue can be potentially fixed, or should we close this ticket as a cantfix?

**Comment by michaelDCurran** [comment]
Closing as cantfix
