### ISSUE TITLE
NVDA freezes and speech is interupted when selecting text in MS Outlook

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#17479]
### Steps to reproduce:
1. Open NVDA
2. Open a new message in Outlook
3. Write some lines of text with blank lines in between (blank lines are not really required, but at least some different paragraphs)
4. Select text with shift+arrow keys or with ctrl+shift+arrow keys both in focus or browse mode.

### Actual behavior:
I also saw this behavior sometimes in edit fields in Chrome or Firefox, but not as obvious as in Outlook.
At some point NVDA is totally silent, epsecially when using focus mode. In browse mode, it seems at least speech is not cancelled, but the performance while selecting is really bad.
Following shows that there is at least a one seccond freeze regularly while selecting content:
```
IO - inputCore.InputManager.executeGesture (08:25:29.084) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (08:25:29.235) - watchdog (26736):
Recovered from potential freeze after 1.000731399981305 seconds.
IO - speech.speech.speak (08:25:29.272) - MainThread (19008):
Speaking ['There is an add-on which can speak the characters of a password when you type it, instead of “star star star” or what ever. This add-on might be useful in certain situations, but it can make NVDA vulnerable to security problems.\r ausgewählt']
IO - inputCore.InputManager.executeGesture (08:25:29.587) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:29.737) - MainThread (19008):
User does not want UIA in MS Word unless necessary
IO - inputCore.InputManager.executeGesture (08:25:29.976) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
IO - inputCore.InputManager.executeGesture (08:25:30.279) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
IO - speech.speech.speak (08:25:30.302) - MainThread (19008):
Speaking ['In following discussion\r ausgewählt']
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (08:25:30.311) - watchdog (26736):
Potential freeze, waiting up to 10 seconds.
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:30.662) - MainThread (19008):
User does not want UIA in MS Word unless necessary
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (08:25:30.812) - watchdog (26736):
Recovered from potential freeze after 1.0015155000146478 seconds.
IO - inputCore.InputManager.executeGesture (08:25:30.868) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
IO - inputCore.InputManager.executeGesture (08:25:31.322) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (08:25:31.332) - watchdog (26736):
Potential freeze, waiting up to 10 seconds.
IO - speech.speech.speak (08:25:31.332) - MainThread (19008):
Speaking ['Neue Zeile ausgewählt']
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:31.707) - MainThread (19008):
User does not want UIA in MS Word unless necessary
IO - inputCore.InputManager.executeGesture (08:25:31.827) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (08:25:31.833) - watchdog (26736):
Recovered from potential freeze after 1.000941300066188 seconds.
DEBUG - speech.manager.SpeechManager._handleIndex (08:25:31.912) - MainThread (19008):
Unknown index 1326, speech probably cancelled from main thread.
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:32.692) - MainThread (19008):
User does not want UIA in MS Word unless necessary
IO - inputCore.InputManager.executeGesture (08:25:32.762) - winInputHook (18892):
Input: kb(laptop):shift+downArrow
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:33.222) - MainThread (19008):
User does not want UIA in MS Word unless necessary
IO - inputCore.InputManager.executeGesture (08:25:33.653) - winInputHook (18892):
Input: kb(laptop):shift+downArrow
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:34.052) - MainThread (19008):
User does not want UIA in MS Word unless necessary
IO - inputCore.InputManager.executeGesture (08:25:34.285) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:34.755) - MainThread (19008):
User does not want UIA in MS Word unless necessary
IO - inputCore.InputManager.executeGesture (08:25:34.847) - winInputHook (18892):
Input: kb(laptop):control+shift+downArrow
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:25:35.427) - MainThread (19008):
User does not want UIA in MS Word unless necessary
```

This occurs both with UIA for MS Word in Outlook on or off.

I added advanced logging for events, speech manager, synth driver, UIA and speech, and following is written to the log:

```
IO - inputCore.InputManager.executeGesture (08:39:49.501) - winInputHook (27188):
Input: kb(laptop):control+shift+upArrow
IO - inputCore.InputManager.executeGesture (08:39:49.752) - winInputHook (27188):
Input: kb(laptop):control+shift+upArrow
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (08:39:49.752) - MainThread (13636):
Emitting winEvent IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3961, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.processGenericWinEvent (08:39:49.752) - MainThread (13636):
Processing generic winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3961, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:49.752) - MainThread (13636):
Creating NVDA event from winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3961, childID 0, process 20304 (outlook), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:49.752) - MainThread (13636):
winEvent mapped to NVDA event: caret
DEBUG - UIAHandler.UIAHandler.isUIAWindow (08:39:49.752) - MainThread (13636):
Found cached is UIA window False for hwnd hwnd 0X10AD6 of class _WwG
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:39:49.768) - MainThread (13636):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 68310 (_WwG), objectID 3961, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:49.768) - MainThread (13636):
Could not instantiate an NVDAObject for winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3961, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:49.806) - MainThread (13636):
Hook received winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3962, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:49.806) - MainThread (13636):
Adding winEvent to limiter: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3962, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (08:39:49.816) - MainThread (13636):
Emitting winEvent IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3962, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.processGenericWinEvent (08:39:49.816) - MainThread (13636):
Processing generic winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3962, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:49.816) - MainThread (13636):
Creating NVDA event from winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3962, childID 0, process 20304 (outlook), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:49.816) - MainThread (13636):
winEvent mapped to NVDA event: caret
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:49.816) - MainThread (13636):
checking window hwnd 0X10AD6 of class _WwG
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:49.831) - MainThread (13636):
window has UIA server side provider
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:39:49.831) - MainThread (13636):
User does not want UIA in MS Word unless necessary
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:49.831) - MainThread (13636):
MS word document treated as non-UIA
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:39:49.846) - MainThread (13636):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 68310 (_WwG), objectID 3962, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:49.846) - MainThread (13636):
Could not instantiate an NVDAObject for winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3962, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:50.016) - MainThread (13636):
Hook received winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3963, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:50.016) - MainThread (13636):
Adding winEvent to limiter: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3963, childID 0, process 20304 (outlook), thread 4836
IO - inputCore.InputManager.executeGesture (08:39:50.016) - winInputHook (27188):
Input: kb(laptop):control+shift+upArrow
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (08:39:50.324) - watchdog (19080):
Potential freeze, waiting up to 10 seconds.
IO - speech.speech.speak (08:39:50.346) - MainThread (13636):
Speaking ['Happy to exchange thoughts, feel free to also comment on the issue on Github.\r nicht ausgewählt']
DEBUG - speech.manager.SpeechManager.speak (08:39:50.346) - MainThread (13636):
SpeechManager- speak (priority <SpeechPriority.NORMAL: 0>): ['Happy to exchange thoughts, feel free to also comment on the issue on Github.  nicht ausgewählt  ']
DEBUG - speech.manager.SpeechManager._queueSpeechSequence (08:39:50.346) - MainThread (13636):
SpeechManager- Out Seq: [['Happy to exchange thoughts, feel free to also comment on the issue on Github.  nicht ausgewählt  ', IndexCommand(648)], [EndUtteranceCommand()]]
DEBUG - speech.manager.SpeechManager._queueSpeechSequence (08:39:50.346) - MainThread (13636):
SpeechManager- Current priority: 0, queLen: 0
DEBUG - speech.manager.SpeechManager._getMostRecentlyCancelledUtterance (08:39:50.346) - MainThread (13636):
SpeechManager- Length of _cancelCommandsForUtteranceBeingSpokenBySynth: 0 Length of _indexesSpeaking: 0 
DEBUG - speech.manager.SpeechManager._doRemoveCancelledSpeechCommands (08:39:50.346) - MainThread (13636):
SpeechManager- Last index: None
DEBUG - speech.manager.SpeechManager.speak (08:39:50.346) - MainThread (13636):
SpeechManager- Will interrupt: False Will push: True | _indexesSpeaking: [] | _curPriQueue valid: False | _shouldPushWhenDoneSpeaking: False | _cancelledLastSpeechWithSynth False
DEBUG - speech.manager.SpeechManager.speak (08:39:50.346) - MainThread (13636):
SpeechManager- Pushing next speech
DEBUG - speech.manager.SpeechManager._pushNextSpeech (08:39:50.346) - MainThread (13636):
SpeechManager- pushNextSpeech - doneSpeaking: True
DEBUG - speech.manager.SpeechManager._pushNextSpeech (08:39:50.346) - MainThread (13636):
SpeechManager- Synth Gets: ['Happy to exchange thoughts, feel free to also comment on the issue on Github.  nicht ausgewählt  ', IndexCommand(648)]
DEBUG - speech.manager.SpeechManager.cancel (08:39:50.396) - MainThread (13636):
SpeechManager- Cancel
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (08:39:50.396) - MainThread (13636):
Emitting winEvent IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3963, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.processGenericWinEvent (08:39:50.396) - MainThread (13636):
Processing generic winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3963, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:50.396) - MainThread (13636):
Creating NVDA event from winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3963, childID 0, process 20304 (outlook), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:50.396) - MainThread (13636):
winEvent mapped to NVDA event: caret
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:50.396) - MainThread (13636):
checking window hwnd 0X10AD6 of class _WwG
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:50.456) - MainThread (13636):
window has UIA server side provider
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:39:50.456) - MainThread (13636):
User does not want UIA in MS Word unless necessary
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:50.456) - MainThread (13636):
MS word document treated as non-UIA
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:39:50.476) - MainThread (13636):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 68310 (_WwG), objectID 3963, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:50.476) - MainThread (13636):
Could not instantiate an NVDAObject for winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3963, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:50.506) - MainThread (13636):
Hook received winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3964, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:50.506) - MainThread (13636):
Adding winEvent to limiter: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3964, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (08:39:50.815) - MainThread (13636):
Emitting winEvent IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3964, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.processGenericWinEvent (08:39:50.815) - MainThread (13636):
Processing generic winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3964, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:50.815) - MainThread (13636):
Creating NVDA event from winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3964, childID 0, process 20304 (outlook), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:50.815) - MainThread (13636):
winEvent mapped to NVDA event: caret
DEBUG - UIAHandler.UIAHandler.isUIAWindow (08:39:50.815) - MainThread (13636):
Found cached is UIA window False for hwnd hwnd 0X10AD6 of class _WwG
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (08:39:50.825) - watchdog (19080):
Recovered from potential freeze after 1.000686899991706 seconds.
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:39:50.846) - MainThread (13636):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 68310 (_WwG), objectID 3964, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:50.846) - MainThread (13636):
Could not instantiate an NVDAObject for winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3964, childID 0, process 20304 (outlook)
IO - inputCore.InputManager.executeGesture (08:39:53.501) - winInputHook (27188):
Input: kb(laptop):control+shift+leftArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:53.536) - MainThread (13636):
Hook received winEvent: EVENT_OBJECT_LOCATIONCHANGE, window 68310 (_WwG), objectID OBJID_CARET, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:53.536) - MainThread (13636):
Adding winEvent to limiter: EVENT_OBJECT_LOCATIONCHANGE, window 68310 (_WwG), objectID OBJID_CARET, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:53.538) - MainThread (13636):
Hook received winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3965, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (08:39:53.538) - MainThread (13636):
Adding winEvent to limiter: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3965, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (08:39:53.920) - MainThread (13636):
Emitting winEvent EVENT_OBJECT_LOCATIONCHANGE, window 68310 (_WwG), objectID OBJID_CARET, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (08:39:53.920) - MainThread (13636):
Emitting winEvent IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3965, childID 0, process 20304 (outlook), thread 4836
DEBUG - IAccessibleHandler.processGenericWinEvent (08:39:53.920) - MainThread (13636):
Processing generic winEvent: EVENT_OBJECT_LOCATIONCHANGE, window 68310 (_WwG), objectID OBJID_CARET, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.processGenericWinEvent (08:39:53.920) - MainThread (13636):
handling winEvent as caret event on focus. winEvent window 68310 (_WwG), objectID OBJID_CARET, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.processGenericWinEvent (08:39:53.920) - MainThread (13636):
Processing generic winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3965, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:53.920) - MainThread (13636):
Creating NVDA event from winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3965, childID 0, process 20304 (outlook), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:53.920) - MainThread (13636):
winEvent mapped to NVDA event: caret
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:53.920) - MainThread (13636):
checking window hwnd 0X10AD6 of class _WwG
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:53.976) - MainThread (13636):
window has UIA server side provider
DEBUG - UIAHandler.shouldUseUIAInMSWord (08:39:53.976) - MainThread (13636):
User does not want UIA in MS Word unless necessary
DEBUG - UIAHandler.UIAHandler._isUIAWindowHelper (08:39:53.976) - MainThread (13636):
MS word document treated as non-UIA
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:39:54.006) - MainThread (13636):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 68310 (_WwG), objectID 3965, childID 0, process 20304 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (08:39:54.006) - MainThread (13636):
Could not instantiate an NVDAObject for winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68310 (_WwG), objectID 3965, childID 0, process 20304 (outlook)
IO - inputCore.InputManager.executeGesture (08:39:55.778) - winInputHook (27188):
Input: kb(laptop):control+shift+upArrow
```

So it seems NVDA is not able to establish an NVDA Object on IA2 caret movement when selecting text.

### Expected behavior:
NVDA should speak selection while selecting text, and no freeze should occur.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-34670,def6a444 (2025.1.0.34670)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
MS Outlook Microsoft 365 MSO (Version 2410 Build 16.0.18129.20158) 64 Bit
Chrome canary 133 and firefox 133 only sometimes.

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All 2024 versions of NVDA show this behavior, I recall though that it worked properly some longer time ago.

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment]
cc: @jcsteh, @mltony, @michaelDCurran

**Comment by Adriani90** [comment]
This seems fixed now in MS Outlook 365 (Version 2505 Build 16.0.18827.20102) 64 Bit.
However, following error still occurs when selecting the last paragraph, last line or last character in an Outlook message while using browse mode.
It occurs only when using objectModel, UIA is set to "only when necessary".
Impact: NVDA does not speak last paragraph, last line or last character when trying to select.

```
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (02:11:52.005) - MainThread (21984):
Emitting winEvent EVENT_OBJECT_LOCATIONCHANGE, window 68274 (_WwG), objectID OBJID_CARET, childID 0, process 21836 (outlook), thread 22196
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (02:11:52.005) - MainThread (21984):
Emitting winEvent IA2_EVENT_TEXT_CARET_MOVED, window 68274 (_WwG), objectID 339, childID 0, process 21836 (outlook), thread 22196
DEBUG - IAccessibleHandler.processGenericWinEvent (02:11:52.005) - MainThread (21984):
Processing generic winEvent: EVENT_OBJECT_LOCATIONCHANGE, window 68274 (_WwG), objectID OBJID_CARET, childID 0, process 21836 (outlook)
DEBUG - IAccessibleHandler.processGenericWinEvent (02:11:52.005) - MainThread (21984):
handling winEvent as caret event on focus. winEvent window 68274 (_WwG), objectID OBJID_CARET, childID 0, process 21836 (outlook)
DEBUG - IAccessibleHandler.processGenericWinEvent (02:11:52.005) - MainThread (21984):
Processing generic winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68274 (_WwG), objectID 339, childID 0, process 21836 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (02:11:52.005) - MainThread (21984):
Creating NVDA event from winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68274 (_WwG), objectID 339, childID 0, process 21836 (outlook), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (02:11:52.005) - MainThread (21984):
winEvent mapped to NVDA event: caret
DEBUG - UIAHandler.UIAHandler.isUIAWindow (02:11:52.005) - MainThread (21984):
Found cached is UIA window False for hwnd hwnd 0X10AB2 of class _WwG
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (02:11:52.005) - MainThread (21984):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 68274 (_WwG), objectID 339, childID 0, process 21836 (outlook)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (02:11:52.005) - MainThread (21984):
Could not instantiate an NVDAObject for winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 68274 (_WwG), objectID 339, childID 0, process 21836 (outlook)
IO - inputCore.InputManager.executeGesture (02:11:52.113) - winInputHook (7384):
Input: kb(laptop):control+shift+downArrow
DEBUG - speech.manager.SpeechManager.cancel (02:11:52.113) - MainThread (21984):
SpeechManager- Cancel
ERROR - scriptHandler.executeScript (02:11:52.119) - MainThread (21984):
error executing script: <bound method CursorManager.script_selectParagraph_forward of <appModules.outlook.MailViewerTreeInterceptor object at 0x07765950>> with gesture 'Strg+Umschalt+Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "cursorManager.pyc", line 494, in script_selectParagraph_forward
  File "cursorManager.pyc", line 425, in _selectionMovementScriptHelper
  File "treeInterceptorHandler.pyc", line 245, in collapse
  File "NVDAObjects\window\winword.pyc", line 1292, in collapse
RuntimeError
IO - inputCore.InputManager.executeGesture (02:11:52.321) - winInputHook (7384):
Input: kb(laptop):control+shift+downArrow
ERROR - scriptHandler.executeScript (02:11:52.329) - MainThread (21984):
error executing script: <bound method CursorManager.script_selectParagraph_forward of <appModules.outlook.MailViewerTreeInterceptor object at 0x07765950>> with gesture 'Strg+Umschalt+Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "cursorManager.pyc", line 494, in script_selectParagraph_forward
  File "cursorManager.pyc", line 425, in _selectionMovementScriptHelper
  File "treeInterceptorHandler.pyc", line 245, in collapse
  File "NVDAObjects\window\winword.pyc", line 1292, in collapse
RuntimeError
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (02:11:55.521) - MainThread (21984):
Hook received winEvent: EVENT_OBJECT_DESTROY, window 656684 (OleMainThreadWndClass), objectID OBJID_WINDOW, childID 0, process 7872 (dllhost), thread 3024
DEBUG - IAccessibleHandler.processDestroyWinEvent (02:11:55.521) - MainThread (21984):
Processing destroy winEvent: window 656684 (unknown), objectID OBJID_WINDOW, childID 0, process 0 (unknown application)
```

**Comment by seanbudd** [comment]
Depriortized as the impact has been reduced considerably. We don't actively support UIA set to "only when necessary"

**Comment by seanbudd** [comment]
Actually, can you please open a separate issue for the other issue you describe?
