### ISSUE TITLE
Thunderbird: After attaching a file to a message the message's content often becomes inaccessible

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#17480]
### Steps to reproduce:
1. Create a new mail and enter some text in the message body.
2. Attach a file using the File menu.
### Actual behavior:

Getting back the the message body you'll sometime notice that it seems to be empty, the only way to get it back is to restart NVDA.
However this toes not systematically occurs.

### Expected behavior:

The content of the message body should be accessed without having to restart NVDA
#### NVDA installed/portable/running from source:
Installed NVDA
#### NVDA version:
NVDA alpha-34678,1fd469a2
#### Windows version:
Windows 11 24h2
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same behaviour with all previous 2024 versions
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by ruifontes** [comment]
Yes, it happens.
But only happens if you press Enter on the file to attach.
If you Tab to the Open button and press Enter, it do not happens.

**Comment by ruifontes** [comment]
Here is a log fragment:
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (15:46:10.369) - MainThread (6728):
accRole failed: (-2147417848, 'O objeto invocado foi desligado dos respetivos clientes.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (15:46:10.393) - MainThread (6728):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
ERROR - eventHandler.executeEvent (15:46:10.408) - MainThread (6728):
error executing event: typedCharacter on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0B47FA30> with extra args of {'ch': '\r'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1253, in event_typedCharacter
  File "speech\speech.pyc", line 1358, in speakTypedCharacters
  File "api.pyc", line 362, in isTypingProtected
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1123, in _get_isProtected
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1912, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 1157, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2147418094, 'The recipient of the call (server [not server application]) is not available and has disappeared; all calls are invalid. The call was not executed.', (None, None, None, 0, None))

**Comment by paulber19** [comment]
This happens with Thunderbird version 128 ESR with which the problem 
occurs very easily.
I failed to produce the issue with version 115.
After choosing the file to attach and pressing "enter", the error that 
Ruiz traced is produced.
then back with "shift+f6" (only when adding a first attachment), moving 
with a down or up arrow gives the following trace:
IO - inputCore.InputManager.executeGesture (18:42:47.079) - winInputHook 
(9848):
Input: kb(desktop):upArrow
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:47.103) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:47.188) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUG - editableText.EditableText._hasCaretMoved (18:42:47.188) - 
MainThread (8256):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets 
(18:42:47.193) - MainThread (8256):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 381, in _getLineOffsets
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getStoryLength 
(18:42:47.198) - MainThread (8256):
IAccessibleText::nCharacters failed
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 311, in _getStoryLength
   File "comtypes\__init__.pyc", line 349, in __getattr__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._getText 
(18:42:47.248) - MainThread (8256):
_getEmbedding returned None while getting initial fields. Object 
probably dead.
IO - speech.speech.speak (18:42:47.248) - MainThread (8256):
Speaking ['vide']
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:47.298) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
IO - inputCore.InputManager.executeGesture (18:42:47.779) - winInputHook 
(9848):
Input: kb(desktop):upArrow
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:47.789) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:47.869) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUG - editableText.EditableText._hasCaretMoved (18:42:47.869) - 
MainThread (8256):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets 
(18:42:47.869) - MainThread (8256):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 381, in _getLineOffsets
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getStoryLength 
(18:42:47.869) - MainThread (8256):
IAccessibleText::nCharacters failed
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 311, in _getStoryLength
   File "comtypes\__init__.pyc", line 349, in __getattr__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._getText 
(18:42:47.908) - MainThread (8256):
_getEmbedding returned None while getting initial fields. Object 
probably dead.
IO - speech.speech.speak (18:42:47.908) - MainThread (8256):
Speaking ['vide']
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:47.939) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
IO - inputCore.InputManager.executeGesture (18:42:48.264) - winInputHook 
(9848):
Input: kb(desktop):downArrow
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:48.289) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:48.359) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUG - editableText.EditableText._hasCaretMoved (18:42:48.359) - 
MainThread (8256):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets 
(18:42:48.359) - MainThread (8256):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 381, in _getLineOffsets
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getStoryLength 
(18:42:48.369) - MainThread (8256):
IAccessibleText::nCharacters failed
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\__init__.pyc", line 311, in _getStoryLength
   File "comtypes\__init__.pyc", line 349, in __getattr__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._getText 
(18:42:48.389) - MainThread (8256):
_getEmbedding returned None while getting initial fields. Object 
probably dead.
IO - speech.speech.speak (18:42:48.389) - MainThread (8256):
Speaking ['vide']
DEBUGWARNING - 
NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo._isCaretAtEndOfLine 
(18:42:48.423) - MainThread (8256):
Couldn't determine if caret is at end of line insertion point
Traceback (most recent call last):
   File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 106, in 
_isCaretAtEndOfLine
   File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, 'Interface inconnue.', (None, None, 
None, 0, None))

**Comment by ahicks92** [comment]
I also see this 99% of the time when doing attachments for what that is worth.  I haven't checked the logs to see if the error is happening.  Restarting Thunderbird itself is not always enough, it really does have to be a full NVDA restart sometimes.

**Comment by ahicks92** [comment]
Looks like this is also when saving attachments.  Saw that at least once as of today.  I don't know how frequent it is yet.

Is it possibly related to #17603?  Seems unlikely because the final behavior is different, but the repro is seeming pretty similar.

**Comment by Adriani90** [comment]
Is this reproducible with NVDA 2025.3 in Thunderbird 144, or 140 ESR?

**Comment by PeterLecky** [comment]
This seems to be fixed in Thunderbird, it disappeared in TB 140.
