### ISSUE TITLE
Braille doesn't work on last snapshot

### ISSUE THREAD

**Issue by dreinn** [nvaccess/nvda#17502]
### Steps to reproduce:
Start NVDA, select MDV Lilli display driver. 

### NVDA logs, crash dumps and other attachments:
This is what NVDA logs when I press a navigation key from the display braille:
ERROR - scriptHandler.executeScript (09:48:48.268) - MainThread (16984):
error executing script: <bound method GlobalCommands.script_braille_scrollForward of <globalCommands.GlobalCommands object at 0x07C918F0>> with gesture 'RG'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "globalCommands.pyc", line 4034, in script_braille_scrollForward
  File "braille.pyc", line 2834, in scrollForward
  File "braille.pyc", line 1995, in scrollForward
  File "braille.pyc", line 1988, in _nextWindow
  File "braille.pyc", line 1890, in _get_windowStartPos
  File "braille.pyc", line 1880, in windowPosToBufferPos
ZeroDivisionError: integer division or modulo by zero

**Comment by nvdaes** [comment]
Hello. I cannot reproduce this with the Focus braille display. But I saw this behavior in a previous portable alpha version with an EcoBraille display. I fixed it with a workaround, that was to enable the braille viewer.
Unfortunately I don't have an Ecobraille anymore to test, but you may try to enable the braille viewer to see if this affects this behavior with some braille displays.
As you may know, braille viewer is available from NVDA's menu, tools submenu. I mention how to enable it just in case.
Hope this helps.

**Comment by Adriani90** [comment]
I am on last alpha with a Brailliant BI40x and I cannot reproduce this issue.
@burmancomp what Braille display do you have? Can you reproduce?

**Comment by seanbudd** [comment]
@Emil-18 - see also #17092

**Comment by dreinn** [comment]
I confirm that if I activate the braille viewer, then I can use the display braille correctly.
For the moment, a great thanks to @nvdaes for the work around.
If you need more information for the issue, let me know!

**Comment by Adriani90** [comment]
Cc: @bramd , @dkager , @LeonarddeR

**Comment by josephsl** [comment]
Hi,

Is this happening if NVDA is told to show speech output in braille? If yes, I think we need to combine this issue with #17092 as the cause might be the same.

Thanks.

**Comment by SaschaCowley** [comment]
@dreinn are you still having this problem? Could we please get a full debug log?

**Comment by SaschaCowley** [comment]
@dreinn are you sure alpha-34735,bdd31537 is the first snapshot to exhibit this behaviour?

**Comment by dreinn** [comment]
@SaschaCowley I attach here a log file with add-on disabled and debug activated.
The problem is that I can't find any errors about braille.
To clarify, I never hear any error signals, the display apparently loads correctly, but no characters are shown on the display until I activate the braille viewer.
Ah, when I say that the display loads correctly, I mean no errors, but display braille remains died, until I activate the braille viewer.

[log no braille.txt](https://github.com/user-attachments/files/18488117/log.no.braille.txt)

**Comment by dreinn** [comment]
@SaschaCowley here it is.

[log no braille2.log](https://github.com/user-attachments/files/18488446/log.no.braille2.log)

**Comment by LeonarddeR** [comment]
@dreinn Have you tried this with add-ons disabled?

**Comment by dreinn** [comment]
@LeonarddeR @SaschaCowley Hello, I don't run NVDA from source, so I can't test your fix until it will be included in a snapshot.
Unfortunately I will return at work next tuesday, so, or someone can create a snapshot within the next 7 hours and then I can test, otherwise wait until Tuesday.

**Comment by LeonarddeR** [comment]
See https://ci.appveyor.com/api/buildjobs/0ejc0ra7xrg9sg8s/artifacts/output%2Fnvda_snapshot_pr17635-35065%2C35b44e5a.exe

**Comment by dreinn** [comment]
I'm sorry @LeonarddeR  First of all thank you for having made a snapshot so soon!
Unfortunately I can't try it because the stupid and unuseful antivirus Apex One prevents me to execute it.
Company policies keep this software installed.
There must be some difference between a manually created snapshot and an alpha snapshot, because I can run alphas without problems. Maybe it's a question of certificates, I don't know, but unfortunately I can't use this kind of snapshot.

**Comment by dreinn** [comment]
@LeonarddeR  I have an idea, i will replace the driver manually and each file which has to do with braille.
Stay tuned

**Comment by LeonarddeR** [comment]
Replacing the drivers won't work here.

**Comment by dreinn** [comment]
nope. Overwriting only the lilli.dll driver doesn't have any effect. So, in order I can test it, please commit your solution to the alpha snapshot system.

**Comment by michaelDCurran** [comment]
I've started a try build which will be fully signed. I'll provide the 
link when it is done.

**Comment by LeonarddeR** [comment]
https://ci.appveyor.com/api/buildjobs/ouyxqfa24ukjh01f/artifacts/output%2Fnvda_snapshot_try-i17635-35091%2Cc877ab3b.exe

**Comment by dreinn** [comment]
yes! it works properly!
Thank you very much to all people that contributed to this issue.

**Comment by LeonarddeR** [comment]
Please do'nt close an issue that is under investigation/that has a pr attached that is not yet merged. Merging the pr will automatically close the issue.
