### ISSUE TITLE
When removing items in Windows Explorer, errors occur

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1793]
**Reported by elliott94 on 2011-09-15 16:53**
This issue is very odd; I don't always hear the error sound when I see this in the log.

Steps to reproduce:
1. Open a new window in Explorer, and navigate to a file or folder that you wish to delete.
2. Open the Delete dialog, and when asked if you're sure that you want to remove the item, hit Escape.

Expected: NVDA should simply regane focus on the previous window.

Actual: the following error can be seen in the log. I've included two examples. The first gave me the error sound, the second didn't.

DEBUGWARNING - core.Notify (17:46:47):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 286, in Notify
  File "IAccessibleHandler.pyc", line 845, in pumpAll
  File "IAccessibleHandler.pyc", line 611, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 533, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 78, in **call**
  File "appModules\explorer.pyc", line 91, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 871, in _get_parent
  File "NVDAObjects__init__.pyc", line 78, in **call**
  File "appModules\explorer.pyc", line 91, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 874, in _get_parent
  File "NVDAObjects__init__.pyc", line 78, in **call**
  File "appModules\explorer.pyc", line 98, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 1308, in _get_parent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\window__init__.pyc", line 259, in _get_parent
  File "NVDAObjects__init__.pyc", line 72, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 372, in findOverlayClasses
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "watchdog.pyc", line 141, in _COMError_init
CallCancelled
DEBUGWARNING - eventHandler.executeEvent (17:48:22):
error executing event: gainFocus on <NVDAObjects.Dynamic_DialogIAccessibleWindowNVDAObject object at 0x05A2B310> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "appModules\explorer.pyc", line 144, in event_gainFocus
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects__init__.pyc", line 773, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 717, in reportFocus
  File "speech.pyc", line 282, in speakObject
  File "speech.pyc", line 214, in speakObjectProperties
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\behaviors.pyc", line 110, in _get_description
  File "NVDAObjects\behaviors.pyc", line 78, in getDialogText
  File "NVDAObjects\behaviors.pyc", line 66, in getDialogText
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects__init__.pyc", line 468, in _get_children
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA__init__.pyc", line 406, in _get_next
  File "NVDAObjects__init__.pyc", line 65, in **call**
  File "NVDAObjects\UIA__init__.pyc", line 224, in **init**
  File "comtypes__init__.pyc", line 266, in **getattr**
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

**Comment by dkager** [comment]
While this sounds familiar I can't seem to reproduce on Windows 10. According to https://github.com/nvaccess/nvda/issues/1793#issuecomment-155293065 there is no log info for this either.

**Comment by jcsteh** [comment]
Closing as duplicate of #2144, as that one contains more info.
