### ISSUE TITLE
VMware installer causes NVDA to become extremely sluggish

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1802]
**Reported by elliott94 on 2011-09-17 10:32**
When the VMware installer for either Workstation or Player is launched (these are the only two that I've tried), NVDA becomes very sluggish to the point that it takes around 5 seconds from the press of a key for any speech to be heard.

The installers are laid out like a web page; they both include HTML elements such as buttons, which have quick access keys. Due to the sluggishness, when a button is reached, NVDA's focus will sometimes move to another button, which makes it difficult to click them unless the quick access keys are used. I've tested the installers on both XP and 7, so it's not OS-spacific.

I've pasted a section of my log where the installer caused NVDA to crash. I'm not sure whether this is a bug to do with NVDA, but I thought it wouldn't do any harm to bring it to attention.

error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLButtonIAccessible object at 0x05F22B70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in **init**
  File "eventHandler.pyc", line 91, in next
  File "virtualBuffers__init__.pyc", line 1051, in event_gainFocus
  File "speech.pyc", line 282, in speakObject
  File "speech.pyc", line 214, in speakObjectProperties
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 450, in _get_name
  File "watchdog.pyc", line 141, in _COMError_init
CallCancelled
DEBUGWARNING - eventHandler.executeEvent (11:04:10):
error executing event: gainFocus on <NVDAObjects.Dynamic_DialogIAccessibleWindowNVDAObject object at 0x0259E470> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects__init__.pyc", line 773, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 717, in reportFocus
  File "speech.pyc", line 282, in speakObject
  File "speech.pyc", line 214, in speakObjectProperties
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\behaviors.pyc", line 110, in _get_description
  File "NVDAObjects\behaviors.pyc", line 78, in getDialogText
  File "NVDAObjects\behaviors.pyc", line 78, in getDialogText
  File "NVDAObjects\behaviors.pyc", line 66, in getDialogText
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 968, in _get_children
  File "NVDAObjects__init__.pyc", line 72, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 372, in findOverlayClasses
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "watchdog.pyc", line 141, in _COMError_init
CallCancelled
DEBUGWARNING - eventHandler.executeEvent (11:04:10):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLButtonIAccessible object at 0x05FAC110> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 131, in executeEvent
  File "eventHandler.pyc", line 144, in doPreGainFocus
  File "api.pyc", line 101, in setFocusObject
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects__init__.pyc", line 430, in _get_container
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 594, in _get_parent
  File "NVDAObjects__init__.pyc", line 65, in **call**
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 391, in **init**
  File "core.pyc", line 40, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 149, in **getattr**
  File "comtypes\automation.pyc", line 665, in _invoke
  File "comtypes\automation.pyc", line 367, in _get_value
  File "watchdog.pyc", line 141, in _COMError_init
CallCancelled

**Comment by dkager** [comment]
Didn't have this problem when installing VMware Player 12.1.0 last year on Windows 10.

**Comment by leonardder** [comment]
Installed VMware player 12.5 yesterday and didn't have problems either.
