### ISSUE TITLE
Intermittent error in Outlook Express

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1883]
**Reported by briang1 on 2011-11-03 19:06**
This error seems to occur  intermittently after hitting enter to send a message in Outlook Express. It does not seem to be destructive, but as its been happening for a while I thought I'd record it in a ticket in case its going to cause issues elsewhere at some point.

IO - inputCore.InputManager.executeGesture (18:45:57):
Input: kb(desktop):enter
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (18:45:57):
oleacc.AccessibleObjectFromEvent with window 6489048, objectID -4 and childID 0: [-2147467259](Error) Unspecified error
IO - speech.speak (18:45:57):
Speaking [('en_UK'), u'CC:  edit  multi line'](LangChangeCommand)
ERROR - eventHandler.executeEvent (18:45:57):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x03D57250> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in **init**
  File "eventHandler.pyc", line 91, in next
  File "appModules\msimn.pyc", line 57, in event_gainFocus
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects\behaviors.pyc", line 130, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 773, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 717, in reportFocus
  File "speech.pyc", line 311, in speakObject
  File "NVDAObjects__init__.pyc", line 843, in makeTextInfo
  File "textInfos\offsets.pyc", line 278, in **init**
  File "NVDAObjects\window\edit.pyc", line 323, in _getStoryLength
  File "winKernel.pyc", line 95, in virtualAllocEx
WindowsError: [6](Error) The handle is invalid.
ERROR - eventHandler.executeEvent (18:45:57):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x03D57250> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects\IAccessible__init__.pyc", line 1197, in event_caret
  File "NVDAObjects\window\edit.pyc", line 788, in event_caret
  File "NVDAObjects__init__.pyc", line 843, in makeTextInfo
  File "textInfos\offsets.pyc", line 275, in **init**
  File "NVDAObjects\window\edit.pyc", line 273, in _getSelectionOffsets
  File "winKernel.pyc", line 95, in virtualAllocEx
WindowsError: [6](Error) The handle is invalid.
IO - speech.speak (18:45:57):
Speaking [('en_UK'), u'Inbox - Outlook Express - Ktnews'](LangChangeCommand)
IO - speech.speak (18:45:57):
Speaking [('en_UK'), u'Outlook Express Message List  list'](LangChangeCommand)
IO - speech.speak (18:45:57):
Speaking [('en_UK'), u'Liam Judge  Subject: FW: TfL Launches live bus information, Received: 03/11/2011 14:24  297 of 298'](LangChangeCommand)

This is normally triggered after the enter is pressed to send the email or after the last key is pressed if a spellcheck is done first. In either case i suspect something is flashed on screen that confuses nvda if the timing is just right. The above was  using snapshot 4773.

**Comment by leonardder** [comment]
@Brian1gaff, closing this as no OE specific work will be done. Could you tell whether this is still a bug, or whether it now works properly for you?
