### ISSUE TITLE
Improuving NVDA's navegation with ABBYY FineReader 11 Corporate Edition

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1977]
**Reported by ManuelRamos on 2011-11-30 22:32**
Our NVDA is compatible with Fine Reader 11.

However, when sellecting option "open in Fine Reader", image file opens. In that situation, before converting document to other format (saving as( it is verry difficult to manage file via alt key or f10. In fact, options like "save", "save as" are not fluentlly spoken.

So it would be wonderfull that our NVDA could perform a little better with saving or managing documents in Finereader.

**Comment by bhavyashah** [comment]
Since the original author of this ticket cannot be contacted and he/she did not respond to @jcsteh's https://github.com/nvaccess/nvda/issues/1977#issuecomment-155294676 requesting specifics and detailed information, I suggest closing. @ehollig

**Comment by ehollig** [comment]
Closing because insufficient information provided to questions asked in https://github.com/nvaccess/nvda/issues/1977#issuecomment-155294676. Also, we do not have a way to contact the original author.

**Comment by fernando-jose-silva** [comment]
I would ask please do not yet close the problem.
I believe I can reproduce the problem.
I have the abby fine reader 12.
Open the fine reader.
Use the Open File option.
Choose a pdf file as an example.
Now that the problem can be found.
Press alt and then an arrow below to navigate through the menu.
Expected the nvda should read the item with focus.
The thing is that the nvda is mute.
Follows a log when the problem occurs.
The nvda in use is the next 14290 and windows 10 64bits.
In this machine there is also available jaws 18 that do not suffer from this problem.
Thank you very much: I would like to ask please do not close the problem.

IO - inputCore.InputManager.executeGesture (12:41:15.552):
Input: kb(laptop):downArrow
DEBUGWARNING - watchdog._watcher (12:41:16.075):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 366, in Notify
  File "IAccessibleHandler.pyc", line 892, in pumpAll
  File "IAccessibleHandler.pyc", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 684, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 635, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 809, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 799, in _get_IAccessibleStates
  File "comtypes\__init__.pyc", line 795, in __call__

DEBUGWARNING - core.CorePump.Notify (12:41:16.075):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 366, in Notify
  File "IAccessibleHandler.pyc", line 892, in pumpAll
  File "IAccessibleHandler.pyc", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 684, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 635, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 809, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
IO - inputCore.InputManager.executeGesture (12:41:23.221):
Input: kb(laptop):upArrow
DEBUGWARNING - watchdog._watcher (12:41:23.743):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 366, in Notify
  File "IAccessibleHandler.pyc", line 892, in pumpAll
  File "IAccessibleHandler.pyc", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 684, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 635, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 809, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 799, in _get_IAccessibleStates
  File "comtypes\__init__.pyc", line 795, in __call__

DEBUGWARNING - core.CorePump.Notify (12:41:23.744):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 366, in Notify
  File "IAccessibleHandler.pyc", line 892, in pumpAll
  File "IAccessibleHandler.pyc", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 684, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 635, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 809, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
IO - inputCore.InputManager.executeGesture (12:41:33.444):
Input: kb(laptop):NVDA+f1
DEBUGWARNING - watchdog._watcher (12:41:33.960):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 367, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 1420, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1167, in info
  File "logHandler.pyc", line 128, in _log
  File "gui\logViewer.pyc", line 100, in activate
  File "gui\logViewer.pyc", line 45, in __init__
  File "gui\logViewer.pyc", line 54, in refresh
  File "wx\_core.pyc", line 13101, in AppendText

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (12:41:34.381):
Developer info for navigator object:
name: u'ARQUIVO'
role: ROLE_POPUPMENU
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x0A83AA70>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'appModuleHandler' (appName u'finereader', process ID 16524) at address a936590>
appModule.productName: u'ABBYY FineReader'
appModule.productVersion: u'12.0.101.483'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 460738
windowClassName: u'AWL:2EE50000:8b:10003:0:0:0'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 7636
windowText: u'MenuWindow'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible) ptr=0xf902ab8 at 5356da0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=460738, objectID=-4, childID=0
IAccessible accName: u'ARQUIVO'
IAccessible accRole: ROLE_SYSTEM_MENUPOPUP
IAccessible accState:  (0)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by jcsteh** [comment]
Closing as a duplicate of #5693, since that issue contains more detail.
