### ISSUE TITLE
Error sound when pressing NVDA+control+r twice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2547]
**Reported by PZajda on 2012-07-21 16:53**
Hi,

If I press NVDA+control+r twice, I have the following error:
ERROR - keyboardHandler.internal_keyDownEvent (18:48:07):
internal_keyDownEvent
Traceback (most recent call last):
  File "keyboardHandler.pyc", line 146, in internal_keyDownEvent
  File "inputCore.pyc", line 282, in executeGesture
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "inputCore.pyc", line 100, in _get_script
  File "scriptHandler.pyc", line 66, in findScript
AttributeError: 'NoneType' object has no attribute 'display'

**Comment by ehollig** [comment]
There is no longer an error, but there is also no speech if this command is pressed twice. This is due to not checking for scriptCount==1. @leonardder would there be performance issues if when this command was pressed twice, it would perform the same action as it would have if it was pressed once? I.E. gui.mainFrame.onRevertToSavedConfigurationCommand(None)

**Comment by Adriani90** [comment]
I get an error in NVDA 2019.1.1:
```
ERROR - keyboardHandler.internal_keyDownEvent (21:02:56.707):
internal_keyDownEvent
Traceback (most recent call last):
  File "keyboardHandler.pyc", line 178, in internal_keyDownEvent
  File "inputCore.pyc", line 421, in executeGesture
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "inputCore.pyc", line 145, in _get_script
  File "scriptHandler.pyc", line 72, in findScript
AttributeError: 'NoneType' object has no attribute 'display'
```

NVDA says "configuration applied". However, the feature seems buggy, because I don't know which configuration NVDA applies in that moment. Suddenly the synth gets louder and some document formating settings are enabled although they were disabled before. Pressing an alt+tab brings my configuration back as it was before pressing nvda+ctrl+r twice.

**Comment by Adriani90** [comment]
a notification would be really helpful which says which configuration has been applied (i.e. standard configuration applied) or something like that.

**Comment by seanbudd** [comment]
Is this still an issue?

**Comment by seanbudd** [comment]
Potentially related: #14872
