### ISSUE TITLE
loseFocus event fired twice when sleep mode is turned on and then off

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2577]
**Reported by jteh on 2012-08-02 07:16**
loseFocus is fired when sleep mode is turned on. However, when sleep mode is turned back on and gainFocus is fired, because the focus object stays the same and loseFocus is always fired on the previous focus before gainFocus, we end up with a second loseFocus.

Str:
1. Focus in Tera Term or another app which uses !DisplayModelLiveText.
2. Turn on sleep mode.
3. Turn off sleep mode.
- Actual: Exception.
- Expected: No exception. :)

**Comment by leonardder** [comment]
Can still be reproduced. cc @jcsteh

**Comment by Adriani90** [comment]
@jcsteh I guess this can still be reproduced. Right?
@michaelDCurran do you have any suggestions to this issue?

**Comment by Adriani90** [comment]
I can reproduce this with Tera Term 5.2 and NVDA 2024.1 RC1. Following error is written to the log:
```
IO - speech.speech.speak (00:19:17.445) - MainThread (14620):
Speaking ['Tera Term - [disconnected] VT', 'Eingabeaufforderung', CancellableSpeech (still valid), 'Leer']
IO - inputCore.InputManager.executeGesture (00:19:18.811) - winInputHook (14284):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (00:19:19.344) - winInputHook (14284):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (00:19:20.451) - winInputHook (14284):
Input: kb(laptop):NVDA+shift+z
IO - speech.speech.speak (00:19:20.451) - MainThread (14620):
Speaking ['Schlafmodus eingeschaltet']
IO - inputCore.InputManager.executeGesture (00:19:21.321) - winInputHook (14284):
Input: kb(laptop):NVDA+shift+z
IO - speech.speech.speak (00:19:21.321) - MainThread (14620):
Speaking ['Schlafmodus ausgeschaltet']
ERROR - eventHandler.executeEvent (00:19:21.331) - MainThread (14620):
error executing event: loseFocus on <NVDAObjects.Dynamic_TerminalDisplayModelLiveTextIAccessibleWindowNVDAObject object at 0x04CA5C30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\behaviors.pyc", line 471, in event_loseFocus
  File "NVDAObjects\window\__init__.pyc", line 415, in stopMonitoring
  File "displayModel.pyc", line 241, in requestTextChangeNotifications
ValueError: list.remove(x): x not in list
```

**Comment by Adriani90** [comment]
cc: @Emil-18 since you investigated abit displayModel handling recently, maybe you are interested in this one?
