### ISSUE TITLE
Error heard when switching input languages in Windows 8

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2707]
**Reported by nvdakor on 2012-10-11 22:57**
Using Win8 with both English U.S. and Korean IME layout. An error is heard when switching languages in Windows 8 by pressing Windows key+SPACE. Here's the log when the error occurs:

IO - inputCore.InputManager.executeGesture (15:49:32):
Input: kb(laptop):windows+space
ERROR - eventHandler.executeEvent (15:49:32):
error executing event: gainFocus on <NVDAObjects.UIA.UIA object at 0x03EA9B30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in **init**
  File "eventHandler.pyc", line 91, in next
  File "appModules\explorer.pyc", line 152, in event_gainFocus
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects__init__.pyc", line 823, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 767, in reportFocus
  File "speech.pyc", line 317, in speakObject
  File "speech.pyc", line 235, in speakObjectProperties
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA__init__.pyc", line 548, in _get_columnNumber
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

Thanks.

**Comment by dkager** [comment]
CC @josephsl

**Comment by josephsl** [comment]
Hi, does not happen on Windows 10, so limiting the scope to Windows 8.1 for now.

**Comment by bhavyashah** [comment]
Confirmed. Using NVDA master-14274,18073792 (temporary copy) on a Windows 8.1 system, I was alarmed when I was able to successfully and consistently replicate these errors consecutively because the error sounds were quite frightening. :) Assuming you have more than one keyboard layout to toggle between (I have three; Hindi Traditional, English India and English US), follow the below steps to replicate the described error.
STR
* Wherever in Windows your focus is, press Windows+Spacebar.
* If NVDA does not play the error sound at this first go itself, press Windows+Space again until you do hear the error sound being played. In my limited testing, NVDA never takes more than three presses of Windows+Space to play the error sound.
* Once you hear the error sound once, press the read current line command (NVDA+L in my laptop) again and again to be greeted by a constant series of error sounds.
I am unsure if the error produced by Windows+Space is different from that produced by a subsequent NVDA+L, so I'll post each of them below respectively:

Windows+Space Error
Input: kb(laptop):windows+space
ERROR - eventHandler.executeEvent (15:44:45.739):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x048C7EF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 929, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 808, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1056, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 624, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 996, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 684, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (15:44:45.770):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x048C7830> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 929, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 808, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1056, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 624, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 996, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 684, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (15:44:45.802):
error executing event: gainFocus on <NVDAObjects.UIA.UIA object at 0x045E9130> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\DELL-PC\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 341, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "appModules\explorer.pyc", line 280, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 936, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 831, in reportFocus
  File "speech.pyc", line 376, in speakObject
  File "speech.pyc", line 270, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1233, in _get_value
  File "NVDAObjects\UIA\__init__.pyc", line 667, in _getUIACacheablePropertyValue
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

NVDA+L Error
Input: kb(laptop):NVDA+l
ERROR - scriptHandler.executeScript (15:53:13.573):
error executing script: <bound method GlobalCommands.script_reportCurrentLine of <globalCommands.GlobalCommands object at 0x046A1230>> with gesture u'NVDA+l'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 142, in script_reportCurrentLine
  File "textInfos\offsets.pyc", line 348, in expand
  File "textInfos\offsets.pyc", line 330, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 249, in _getLineOffsets
  File "NVDAObjects\__init__.pyc", line 41, in _getStoryText
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 996, in _get_basicText
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1233, in _get_value
  File "NVDAObjects\UIA\__init__.pyc", line 667, in _getUIACacheablePropertyValue
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

Please let me know if any further diagnostic information is required for troubleshooting purposes.

**Comment by Adriani90** [comment]
@bhavyashah is this still reproducible on Windows 8.1?

**Comment by Adriani90** [comment]
No updates since almost three years, I cannot reproduce this with las alpha of NVDA. Closing as abandoned and works for me. Please comment on this if you are still seeing this issue and we can reopen it. Thanks.
