### ISSUE TITLE
Error on progress bar updates

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2732]
**Reported by elliott94 on 2012-10-20 13:16**
I've received the following error in the log several times. It doesn't seem to cause any bad effects, but it's not just limited to one app so I figured their'd be no harm in filing a ticket. This particular entry is from the NVDA updater progress bar.

ERROR - eventHandler.executeEvent (14:08:17):
error executing event: valueChange on <NVDAObjects.Dynamic_ProgressBarIAccessibleWindowNVDAObject object at 0x05404250> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in **init**
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects\behaviors.pyc", line 50, in event_valueChange
  File "tones.pyc", line 42, in beep
  File "nvwave.pyc", line 164, in feed
  File "nvwave.pyc", line 146, in open
  File "nvwave.pyc", line 84, in _winmm_errcheck
WindowsError: [4](Error) The specified device is already in use.  Wait until it is free, and then try again.

**Comment by dkager** [comment]
@elliott94 Is this still a problem?

**Comment by elliott94** [comment]
I haven't seen this for a while now - happy for it to be closed.
