### ISSUE TITLE
Errors durring update

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2747]
**Reported by PZajda on 2012-10-26 10:27**
When updating NVDA and when the update is downloaded, I have the following errors:
WARNING - RPC process 3324 (nvda_slave.exe) (12:22:52):
installer._deleteKeyAndSubkeys:
Error deleting registry key
Traceback (most recent call last):
  File "installer.pyc", line 260, in _deleteKeyAndSubkeys
WindowsError: [6](Error) Descripteur non valide
WARNING - RPC process 3324 (nvda_slave.exe) (12:22:52):
installer._deleteKeyAndSubkeys:
Error deleting registry key
Traceback (most recent call last):
  File "installer.pyc", line 260, in _deleteKeyAndSubkeys
WindowsError: [6](Error) Descripteur non valide
WARNING - RPC process 3324 (nvda_slave.exe) (12:22:52):
installer._deleteKeyAndSubkeys:
Error deleting registry key
Traceback (most recent call last):
  File "installer.pyc", line 260, in _deleteKeyAndSubkeys
WindowsError: [6](Error) Descripteur non valide
WARNING - RPC process 3324 (nvda_slave.exe) (12:22:52):
installer._deleteKeyAndSubkeys:
Error deleting registry key
Traceback (most recent call last):
  File "installer.pyc", line 260, in _deleteKeyAndSubkeys
WindowsError: [6](Error) Descripteur non valide

**Comment by dkager** [comment]
Closing for lack of information.
