### ISSUE TITLE
Freezing and slowing  when exiting applications or switching areas in desktop

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2796]
**Reported by briang1 on 2012-11-14 11:26**
For some time now a strange and intermittent problem has been happening. In Windows XP at any rate. It can be at boot up, or it may well happen when you exit Outlook Express or IE8. It takes a fair amount of time to actually exit, though while in use the  apps work fine. Thereafter all switching between desktop, start button or system area etc, takes longer than it should to speak.
 Sometimes whn you reboot nvda, it can crash nvda, so you only hear the  ascending tones of the new session. Rebooting always restores the system again, thus it seems to be nvda which is slugging the  responses, not the computer or Windows.

Hear is the log from the most recent occurence. This is a recent main snap, and it from being in Outlook Express to the reboot of nvda, showing where the log terminated.

IO - speech.speak (11:01:56):
Speaking [('en_UK'), u'From: TfL Press Office; Subject: TfL Press Release - Mayor sets out major plan for transport investment while keeping fares as low as possible with rise at one per cent above inflation for 2013; Received: 07/11/2012 10:33  49 of 54'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (11:07:50):
Input: kb(desktop):downArrow
IO - speech.speak (11:07:50):
Speaking [('en_UK'), u"unread From: TfL Press Office; Subject: TfL Press Release - Transport for London celebrates 'STAR' schools dedication to active and safer travel ; Received: 08/11/2012 13:59  50 of 54"](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (11:07:52):
Input: kb(desktop):escape
IO - inputCore.InputManager.executeGesture (11:07:53):
Input: kb(desktop):alt+f4
DEBUGWARNING - watchdog._watcher (11:07:54):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 164, in <module>
  File "core.pyc", line 345, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "core.pyc", line 322, in Notify
  File "IAccessibleHandler.pyc", line 840, in pumpAll
  File "IAccessibleHandler.pyc", line 625, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 502, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 39, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 333, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:07:54):
oleacc.AccessibleObjectFromEvent with window 65672, objectID -4 and childID 0: 
IO - inputCore.InputManager.executeGesture (11:07:55):
Input: kb(desktop):alt+tab
IO - inputCore.InputManager.executeGesture (11:07:55):
Input: kb(desktop):downArrow
IO - inputCore.InputManager.executeGesture (11:07:56):
Input: kb(desktop):upArrow
IO - inputCore.InputManager.executeGesture (11:07:56):
Input: kb(desktop):downArrow
IO - inputCore.InputManager.executeGesture (11:07:58):
Input: kb(desktop):windows+m
IO - inputCore.InputManager.executeGesture (11:07:59):
Input: kb(desktop):downArrow
IO - inputCore.InputManager.executeGesture (11:08:00):
Input: kb(desktop):tab
DEBUG - appModuleHandler.update (11:08:00):
application msimn closed
DEBUGWARNING - watchdog._watcher (11:08:04):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 164, in <module>
  File "core.pyc", line 345, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "core.pyc", line 322, in Notify
  File "IAccessibleHandler.pyc", line 825, in pumpAll
  File "IAccessibleHandler.pyc", line 625, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 502, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 39, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 333, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:05):
oleacc.AccessibleObjectFromEvent with window 65684, objectID -4 and childID 48: 
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:06):
oleacc.AccessibleObjectFromEvent with window 65684, objectID -4 and childID 0: 
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:07):
oleacc.AccessibleObjectFromEvent with window 65682, objectID -4 and childID 0: 
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:09):
oleacc.AccessibleObjectFromEvent with window 65684, objectID -4 and childID 48: 
DEBUGWARNING - watchdog._watcher (11:08:09):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 164, in <module>
  File "core.pyc", line 345, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "core.pyc", line 322, in Notify
  File "IAccessibleHandler.pyc", line 840, in pumpAll
  File "IAccessibleHandler.pyc", line 625, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 502, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 39, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 333, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:10):
oleacc.AccessibleObjectFromEvent with window 65684, objectID -4 and childID 49: 
DEBUGWARNING - watchdog._watcher (11:08:14):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 164, in <module>
  File "core.pyc", line 345, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "core.pyc", line 322, in Notify
  File "IAccessibleHandler.pyc", line 837, in pumpAll
  File "IAccessibleHandler.pyc", line 583, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 502, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 45, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 72, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 375, in findOverlayClasses
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 753, in _get_IAccessibleRole
  File "comtypes__init__.pyc", line 795, in **call**

DEBUGWARNING - core.Notify (11:08:15):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 322, in Notify
  File "IAccessibleHandler.pyc", line 837, in pumpAll
  File "IAccessibleHandler.pyc", line 583, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 502, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 45, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 72, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 375, in findOverlayClasses
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 753, in _get_IAccessibleRole
  File "comtypes__init__.pyc", line 795, in **call**
  File "watchdog.pyc", line 140, in sendMessageCallCanceller
CallCancelled
DEBUGWARNING - watchdog._watcher (11:08:15):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 164, in <module>
  File "core.pyc", line 345, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "core.pyc", line 322, in Notify
  File "IAccessibleHandler.pyc", line 837, in pumpAll
  File "IAccessibleHandler.pyc", line 583, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 502, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 39, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 333, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:16):
oleacc.AccessibleObjectFromEvent with window 65684, objectID -4 and childID 49: 
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:17):
oleacc.AccessibleObjectFromEvent with window 65684, objectID -4 and childID 48: 
IO - speech.speak (11:08:23):
Speaking [('en_UK'), u'Desktop  list'](LangChangeCommand)
IO - speech.speak (11:08:23):
Speaking [('en_UK'), u'RegCleanr.exe  50 of 61'](LangChangeCommand)
IO - speech.speak (11:08:23):
Speaking [('en_UK'), u'RegCleanr.exe  50 of 61'](LangChangeCommand)
INFO - core.main (11:08:24):
Exiting
DEBUG - core.main (11:08:24):
Terminating updateCheck
DEBUG - core.main (11:08:24):
Terminating watchdog
DEBUG - core.main (11:08:24):
Terminating global plugin handler
DEBUG - core.main (11:08:24):
Terminating GUI

**Comment by leonardder** [comment]
XP specific issue, closing as won't fix.
