### ISSUE TITLE
extraneous message is given on reaching the address book control in envelopes and labels dialog in MS Word.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3053]
**Reported by sumandogra on 2013-03-06 12:05**
MS Word 2010

Extraneous message is given on reaching the address book control in envelopes and label’s dialog.
Steps to reproduce:
1.  In MS Word, go to mailings tab>create envelops tab.
2.  Press ENTER to open envelopes and labels dialog.
3.  Press SHIFT+TAB once to go back to the address book.
4.  NVDA gives an extraneous speech twice before announcing the name of the control.

**Comment by bhavyashah** [comment]
Triagers and MS Office experts: Could you please address @josephsl's proposal of merging this ticket into another as noted in https://github.com/nvaccess/nvda/issues/3053#issuecomment-155305553?

**Comment by Adriani90** [comment]
In Word 2010 NVDA reports from time to time "MSO Generic Control" and I get following error while tabbing through the envelope dialog. The errors occur especially near to the address book object:

```
ERROR - baseObject.ScriptableObject.bindGestures (23:13:05.126) - MainThread (9344):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x01759B70>
ERROR - baseObject.ScriptableObject.bindGestures (23:13:05.148) - MainThread (9344):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x01759B70>
DEBUG - config.ConfigManager._triggerProfileEnter (23:13:05.196) - MainThread (9344):
Activating triggered profile Word
DEBUG - synthDriverHandler.SynthDriver.loadSettings (23:13:05.196) - MainThread (9344):
Loaded changed settings for SynthDriver ibmeci
ERROR - baseObject.ScriptableObject.bindGestures (23:13:05.284) - MainThread (9344):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x0175F3F0>
ERROR - baseObject.ScriptableObject.bindGestures (23:13:05.307) - MainThread (9344):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x0175F3F0>
ERROR - baseObject.ScriptableObject.bindGestures (23:13:05.356) - MainThread (9344):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x07D98250>
ERROR - baseObject.ScriptableObject.bindGestures (23:13:05.378) - MainThread (9344):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x07D98250>
```

In Word 365, with or without UIA for Word enabled in NVDA settings, I get following error:
```
IO - inputCore.InputManager.executeGesture (23:18:25.509) - winInputHook (10572):
Input: kb(laptop):tab
DEBUGWARNING - NVDAObjects.window.winword.WordDocument._get_WinwordWindowObject (23:18:25.570) - MainThread (9344):
Could not get MS Word object model from window 395080 with class _WwN
Traceback (most recent call last):
  File "NVDAObjects\window\winword.pyc", line 1195, in _get_WinwordWindowObject
  File "oleacc.pyc", line 237, in AccessibleObjectFromWindow
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147467259] Unbekannter Fehler
ERROR - scriptHandler.executeScript (23:18:25.578) - MainThread (9344):
error executing script: <bound method WordDocument.script_tab of <NVDAObjects.Dynamic_WordDocumentEditableTextWithAutoSelectDetectionUIAWindowNVDAObject object at 0x04EEC690>> with gesture 'Tab'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "NVDAObjects\window\winword.pyc", line 1411, in script_tab
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 297, in __init__
NotImplementedError: UIAutomationTextRangeArray is empty
```

@michaelDCurran does this need an external fix from Microsoft? Or is it something that can be done from NVDA's side?

**Comment by Adriani90** [comment]
Errors are still reproducible with NVDA 2024.3 Beta in MS Office 365.

**Comment by seanbudd** [comment]
It seems like the double speaking bug is no longer an issue and the errors in the log are expected
