### ISSUE TITLE
NVDA makes error sound in save as/exiting power point dialogues

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3139]
**Reported by fatma.mehanna on 2013-04-07 23:05**
hi all,
i use powerpoint 2010 with windows xp, NVDA version main 5983.
NVDA makes an error sound when i press ctrl+s or when i press alt+f4 to save a presentation.
steps to reproduce:
1 open a new powerpoint presentation file or a presentation to modify.
2 modify the prepared presentation or start to prepare the new one.
3 after finishing, press alt+f4 to save/quiet the program.
results: nvda will announce the save file message, but with error sound.

**Comment by ehollig** [comment]
Not able to reproduce using Powerpoint 2016. Does anyone have Powerpoint 2010 installed to see if the problem still occurs?

**Comment by derekriemer** [comment]
Can we get the log? unless this is different on xp from 7, I never used to see this on 7 when using NVDA back in 2013.

**Comment by feerrenrut** [comment]
I updated the previous comment with the log file: https://github.com/nvaccess/nvda/issues/3139#issuecomment-155306113

This seems to be the relevant section:
```
Input: kb(desktop):alt+f4
ERROR - eventHandler.executeEvent (00:40:12):
error executing event: focusEntered on <NVDAObjects.Dynamic_NUIDialogClientIAccessibleWindowNVDAObject object at 0x03A91CB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in __init__
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects\__init__.pyc", line 827, in event_focusEntered
  File "speech.pyc", line 317, in speakObject
  File "speech.pyc", line 235, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\behaviors.pyc", line 131, in _get_description
  File "NVDAObjects\behaviors.pyc", line 72, in getDialogText
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 991, in _get_children
  File "IAccessibleHandler.pyc", line 354, in accessibleChildren
  File "oleacc.pyc", line 285, in AccessibleChildren
  File "_ctypes/callproc.c", line 936, in GetResult
WindowsError: [Error -2147418111] Call was rejected by callee
```

**Comment by bhavyashah** [comment]
Using NVDA 2017.3 RC 1 and Powerpoint 2010 on Windows 8.1, I was able to replicate the reported error via the following STR:
* Open a new blank PowerPoint presentation (Run>powerpnt).
* Type something (I Love NVDA) in the title and something (Yo Buddy) in the subtitle fields of the first blank title slide of the presentation.
* Press Ctrl+S and observe that NVDA reports it properly without generating any error. Escape out of the Save As dialog.
* Now, press Alt+F4 without having saved the presentation earlier.
Expected Result: NVDA should report the dialog normally without throwing any error.
Actual Result: NVDA's dialog reading functionality is perfect in this case as always, but following is a log snippet from the NVDA Log Viewer set at Debug.
Input: kb(laptop):alt+f4
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (16:29:04.163):
oleacc.AccessibleObjectFromEvent with window 3212364, objectID 89 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleChildren (16:29:04.227):
AccessibleChildren failed
Traceback (most recent call last):
  File "IAccessibleHandler.pyo", line 363, in accessibleChildren
  File "oleacc.pyo", line 285, in AccessibleChildren
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147418111] Call was rejected by callee
I would be happy to perform further testing to track down this issue if required.

**Comment by Adriani90** [comment]
When pressing ctrl+s I am getting following in the log file:

´´´
IO - inputCore.InputManager.executeGesture (11:04:33.174):
Input: kb(laptop):control+s
DEBUGWARNING - watchdog._watcher (11:04:33.831):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 203, in <module>
  File "core.pyo", line 473, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 443, in Notify
  File "IAccessibleHandler.pyo", line 894, in pumpAll
  File "IAccessibleHandler.pyo", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyo", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyo", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyo", line 71, in __call__
  File "NVDAObjects\IAccessible\__init__.pyo", line 558, in __init__
  File "IAccessibleHandler.pyo", line 914, in getIAccIdentity
  File "comtypes\__init__.pyo", line 1078, in QueryInterface

DEBUGWARNING - core.CorePump.Notify (11:04:34.019):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 443, in Notify
  File "IAccessibleHandler.pyo", line 894, in pumpAll
  File "IAccessibleHandler.pyo", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyo", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyo", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyo", line 78, in __call__
  File "NVDAObjects\IAccessible\__init__.pyo", line 385, in findOverlayClasses
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "watchdog.pyo", line 202, in _COMError_init
CallCancelled
´´´

**Comment by Adriani90** [comment]
When pressing alt+f4 and then escape, I am getting following:
´´´

IO - inputCore.InputManager.executeGesture (11:08:05.869):
Input: kb(laptop):alt+f4
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:05.947):
oleacc.AccessibleObjectFromEvent with window 1179826, objectID 163 and childID 0: [Error -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleChildren (11:08:05.994):
AccessibleChildren failed
Traceback (most recent call last):
  File "IAccessibleHandler.pyo", line 361, in accessibleChildren
  File "oleacc.pyo", line 285, in AccessibleChildren
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147418111] Aufruf wurde durch Aufgerufenen abgelehnt
IO - speech.speak (11:08:05.994):
Speaking [LangChangeCommand (u'de'), u'Microsoft PowerPoint  Dialogfeld']
IO - speech.speak (11:08:06.056):
Speaking [LangChangeCommand (u'de'), u'Microsoft PowerPoint  Dialogfeld  M\xf6chten Sie die \xc4nderungen in "Pr\xe4sentation1" speichern?']
IO - speech.speak (11:08:06.056):
Speaking [LangChangeCommand (u'de'), u'Speichern  Schalter']
IO - inputCore.InputManager.executeGesture (11:08:09.447):
Input: kb(laptop):tab
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (11:08:09.463):
oleacc.AccessibleObjectFromEvent with window 1179826, objectID 164 and childID 0: [Error -2147467259] Unbekannter Fehler
IO - speech.speak (11:08:09.494):
Speaking [LangChangeCommand (u'de'), u'Nicht speichern  Schalter']
IO - inputCore.InputManager.executeGesture (11:08:10.604):
Input: kb(laptop):escape
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (11:08:10.665):
accRole failed: (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
IO - speech.speak (11:08:10.697):
Speaking [LangChangeCommand (u'de'), u'Pr\xe4sentation1 - Microsoft PowerPoint']
IO - speech.speak (11:08:10.713):
Speaking [LangChangeCommand (u'de'), u'Folie 1 - Folienansicht']
INFO - updateCheck.AutoUpdateChecker._started (11:08:15.494):
Performing automatic update check
DEBUGWARNING - updateCheck.UpdateChecker._bg (11:08:15.494):
Error checking for update
Traceback (most recent call last):
  File "updateCheck.pyo", line 116, in _bg
  File "updateCheck.pyo", line 74, in checkForUpdate
  File "urllib.pyo", line 87, in urlopen
  File "urllib.pyo", line 213, in open
  File "urllib.pyo", line 443, in open_https
  File "httplib.pyo", line 1038, in endheaders
  File "httplib.pyo", line 882, in _send_output
  File "httplib.pyo", line 844, in send
  File "httplib.pyo", line 1263, in connect
  File "ssl.pyo", line 363, in wrap_socket
  File "ssl.pyo", line 611, in __init__
  File "ssl.pyo", line 840, in do_handshake
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:661)
´´´

**Comment by Adriani90** [comment]
I don't know if this Impacts security aspects. Maybe @ferrenrut can share ist thoughts with us. Regarind user experience this is not an issue.

**Comment by Adriani90** [comment]
In Powerpoint 2010 on Windows 10 and NVDA alpha-17134,363af94b I do not get any errors anymore.

@k-kolev1985 do you have by chance Office 2010 on your machine and could test if you can reproduce this errors on Windows 8.1? Thanks very much!

**Comment by Adriani90** [comment]
No updates on this issue from initial author since many years. I am closing as works for me because I cannot reproduce it in NVDA 2019.3.1.
