### ISSUE TITLE
Constant errors when moving around files in Studio recorder

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3199]
**Reported by pitermach on 2013-05-04 16:00**
Version master-9172,1b62fc7
STR:
-Download studio recorder from aph.org/tech, install it and then open any file. Then either use the arrow keys to move around it, or press space to play the file. 
When ever the file position changes there is a edit box on the screen that gets updated, and when it does this comes up:
ERROR - eventHandler.executeEvent (17:45:33):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleDisplayModelEditableTextWindowNVDAObject object at 0x04B045F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 136, in executeEvent
  File "eventHandler.pyc", line 84, in **init**
  File "eventHandler.pyc", line 91, in next
  File "NVDAObjects\IAccessible__init__.pyc", line 1285, in event_caret
  File "NVDAObjects__init__.pyc", line 868, in event_caret
  File "NVDAObjects__init__.pyc", line 903, in makeTextInfo
  File "displayModel.pyc", line 159, in **init**
  File "textInfos\offsets.pyc", line 280, in **init**
  File "displayModel.pyc", line 403, in _getCaretOffset
  File "displayModel.pyc", line 375, in _findCaretOffsetFromLocation
LookupError

**Comment by bhavyashah** [comment]
Since the original author of this ticket is unfortunately now out-of-reach, he/she failed to respond to @jcsteh's request for a status update in https://github.com/nvaccess/nvda/issues/3199#issuecomment-155306629, and it is possible that both NVDA as well as Studio Recorder updates may have resolved this issue overtime, unless we receive any feedback confirming the reported errors, I suggest closing. @ehollig

**Comment by leonardder** [comment]
Agreed. Closing as invalid as per above comment.
