### ISSUE TITLE
MS Outlook 2007 crashes when NVDA is loaded

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3308]
**Reported by ondrosik on 2013-06-28 16:17**
This is the user report from Czech community. He is on Win 7 32 bit. This happens on 2013.1.1 and newer master snapshots.
Steps to reproduce:
- move from inbox to another folder, for example folder with filterred e-mails from mailinglists.
  Open here some message.
  Outlook will crash. After restart it seems to be OK, but in some circumstances it happens again. User tested this with other screenreader but 

Outlook 2007 crashes with NVDA only.

I extracted the relevant part from the log:
Input: kb(desktop):numpadEnter
DEBUGWARNING - RPC process 5828 (DWWIN.EXE) (15:53:17):
Thread 3608, nvdaHelper\build\x86\remote\ia2Support.cpp, installIA2Support, 

81:
Error registering class object, code -2147221008

DEBUGWARNING - watchdog._watcher (15:53:18):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 157, in <module>
  File "core.pyo", line 307, in main
  File "wx_core.pyo", line 8010, in MainLoop
  File "wx_core.pyo", line 7306, in MainLoop
  File "core.pyo", line 283, in Notify
  File "IAccessibleHandler.pyo", line 848, in pumpAll
  File "IAccessibleHandler.pyo", line 593, in processGenericWinEvent
  File "IAccessibleHandler.pyo", line 504, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 231, in isUIAWindow

DEBUGWARNING - core.Notify (15:53:18):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 283, in Notify
  File "IAccessibleHandler.pyo", line 848, in pumpAll
  File "IAccessibleHandler.pyo", line 593, in processGenericWinEvent
  File "IAccessibleHandler.pyo", line 504, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 233, in isUIAWindow
  File "watchdog.pyo", line 140, in sendMessageCallCanceller
CallCancelled
DEBUGWARNING - watchdog._watcher (15:53:18):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 157, in <module>
  File "core.pyo", line 307, in main
  File "wx_core.pyo", line 8010, in MainLoop
  File "wx_core.pyo", line 7306, in MainLoop
  File "core.pyo", line 283, in Notify
  File "IAccessibleHandler.pyo", line 848, in pumpAll
  File "IAccessibleHandler.pyo", line 593, in processGenericWinEvent
  File "IAccessibleHandler.pyo", line 504, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 231, in isUIAWindow

IO - inputCore.InputManager.executeGesture (15:53:22):
Input: kb(desktop):tab
IO - inputCore.InputManager.executeGesture (15:53:23):
Input: kb(desktop):alt+tab
DEBUGWARNING - watchdog._watcher (15:53:23):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 157, in <module>
  File "core.pyo", line 307, in main
  File "wx_core.pyo", line 8010, in MainLoop
  File "wx_core.pyo", line 7306, in MainLoop
  File "core.pyo", line 284, in Notify
  File "queueHandler.pyo", line 76, in pumpAll
  File "queueHandler.pyo", line 47, in flushQueue
  File "eventHandler.pyo", line 54, in _queueEventCallback
  File "eventHandler.pyo", line 131, in executeEvent
  File "comtypesMonkeyPatches.pyo", line 51, in newCpbDel
  File "comtypes__init__.pyo", line 841, in **del**
  File "comtypes__init__.pyo", line 1092, in Release

DEBUGWARNING - eventHandler.executeEvent (15:53:23):
error executing event: gainFocus on 

<NVDAObjects.IAccessible.ContentGenericClient object at 0x059CFCF0> with 

extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 833, in event_gainFocus
  File "NVDAObjects__init__.pyo", line 777, in reportFocus
  File "speech.pyo", line 317, in speakObject
  File "speech.pyo", line 235, in speakObjectProperties
  File "baseObject.pyo", line 34, in **get**
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyo", line 1431, in _get_value
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\window__init__.pyo", line 196, in _get_displayText
  File "displayModel.pyo", line 26, in getWindowTextInRect
  File "watchdog.pyo", line 274, in cancellableExecute
  File "watchdog.pyo", line 208, in execute
CallCancelled
IO - speech.speak (15:53:23):
Speaking [('cs'), u'Microsoft Office Outlook  dialog  

Program Microsoft Office Outlook p\u0159estal pracovat.\nProbl\xe9m 

zp\u016fsobil, \u017ee program p\u0159estal spr\xe1vn\u011b fungovat. 

Ukon\u010dete program.'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (15:53:36):
Input: kb(desktop):windows+d
DEBUGWARNING - RPC process 2056 (dwm.exe) (15:53:36):
Thread 9776, nvdaHelper\build\x86\remote\injection.cpp, 

inproc_winEventCallback, 67:
SetWindowsHookEx with WH_GETMESSAGE failed, GetLastError returned 5

DEBUGWARNING - RPC process 2056 (dwm.exe) (15:53:36):
Thread 9776, nvdaHelper\build\x86\remote\injection.cpp, 

inproc_winEventCallback, 70:
SetWindowsHookEx with WH_CALLWNDPROC failed, GetLastError returned 5

DEBUGWARNING - RPC process 2056 (dwm.exe) (15:53:36):
Thread 9776, nvdaHelper\build\x86\remote\ia2Support.cpp, installIA2Support, 

81:
Error registering class object, code -2147221008

**Comment by ehollig** [comment]
@Qchristensen, this appears to be another Office 2007 specific issue. Could you  please test this issue, or @ondrosik, is this still an issue?

**Comment by Qchristensen** [comment]
I can reproduce this, although my log looks slightly different:

ERROR - eventHandler.executeEvent (13:16:03.690):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x054CE470> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 909, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 796, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1041, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 612, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 981, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 682, in _prefetchUIACacheForPropertyIDs
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
ERROR - RPC process 2432 (nvda_slave.exe) (13:16:20.180):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Operation unavailable

Using Windows 7, 64 bit with SP1 and I just realised it's a few weeks old snapshot build of NVDA on this system.

**Comment by Brian1Gaff** [comment]
Deja vue all over again?
 This looks suspiciously like the uia errors we got in some office software 
in XP with their first attempt at uia as an update. This resulted in the xp 
version of nvda having uia disabled to stop lock ups and crashes.
 I thought uia was only supported by Office from 2013 onwards in any case?
 As I've mentioned before I have a friend with a crashing version of Outlook 
2003 which may or may not be due to nvda/windows updates recently. hard to 
say as she is non technical.




bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment]
Is this still reproducible with NVDA 2018.2.1?

**Comment by Adriani90** [comment]
@ondrosik

**Comment by Qchristensen** [comment]
I can't reproduce it anymore.  I agree with closing it.  As always, if anyone can still reproduce this with current versions of NVDA, please report it.
