### ISSUE TITLE
WindowsError while trying to display a page

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3516]
**Reported by kredh on 2013-09-11 07:14**
Sometimes with the new NVDA next, when trying to enter a web-page (by clicking on a link, for instance), an error appears in the NVDA log.

Error in func _handleUpdate from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 47, in flushQueue
  File "virtualBuffers__init__.pyc", line 1489, in _handleUpdate
  File "braille.pyc", line 1444, in handleUpdate
  File "braille.pyc", line 743, in update
  File "textInfos\offsets.pyc", line 328, in expand
  File "virtualBuffers__init__.pyc", line 224, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 310, in _getUnitOffsets
  File "virtualBuffers__init__.pyc", line 170, in _getLineOffsets
WindowsError: [1775](Error) A null context descriptor was passed from the client to the host while calling a foreign procedure (RPC)

Note that, on my computer, the Windows messages are not in English (I translated this one but it may not be the exact way it's displayed in English).

**Comment by ehollig** [comment]
Closing, as the original poster did not reply to @jcsteh's question in https://github.com/nvaccess/nvda/issues/3516#issuecomment-155309504. Also, we are unable to contact the original poster.
