### ISSUE TITLE
MSHTML: Exception in isFocusable property

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3771]
**Reported by jteh on 2014-01-13 00:40**
This occurred when trying to move through the text of the update radio buttons in browse mode in the normal Adobe Flash installer:

```
error executing script: <bound method MSHTML.script_moveByLine_back of <virtualBuffers.MSHTML.MSHTML object at 0x03F647B0>> with gesture u'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 174, in executeScript
  File "cursorManager.pyo", line 154, in script_moveByLine_back
  File "cursorManager.pyo", line 79, in _caretMovementScriptHelper
  File "virtualBuffers\__init__.pyo", line 812, in _set_selection
  File "virtualBuffers\__init__.pyo", line 827, in _shouldSetFocusToObj
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyo", line 794, in _get_isFocusable
  File "comtypesMonkeyPatches.pyo", line 34, in new__getattr__
  File "comtypes\client\dynamic.pyo", line 93, in __getattr__
  File "comtypes\automation.pyo", line 643, in GetIDsOfNames
COMError: (-2147352570, 'Unknown name.', (None, None, None, 0, None))
```

This is on a pretty clean install of Windows XP sp3 with no further updates applied.

**Comment by ehollig** [comment]
Closing, as the original post discusses the flash installer, which development will be discontinued in 2020, Windows XP, and Internet Explorer 8, which is outdated now.
