### ISSUE TITLE
Next branch crashing windows update in IE8

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3884]
**Reported by briang1 on 2014-02-13 19:24**
I'm getting crashing of Internet Explorer 8 a bit more than is healthy 
today, but cannot pin it down.
 The only way I have managed to get a dump is via Windows update, which 
seems to crash every time I select choose from all updates for your 
computer. when it goes to show me the choices after the scan, it standa a 
very good chance of IE just vanishing.
 No errors in nvda no sign of windows crash reports, but there is a dump, 
which I'll attempt to attach to this message

NVDA version next-10355,a55d3d1

The machine is an Intel Pent 4 running at 2.6 gig, single core, so nothing 
too bad really.
IO - speech.speak (18:42:24):
Speaking [('en_GB'), u'Checking for the latest updates for 
your computer...', u'\n'](LangChangeCommand)
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (18:43:25):
oleacc.AccessibleObjectFromEvent with window 852574, objectID 3 and childID 
0: [-2147467259](Error) Unspecified error
DEBUGWARNING - watchdog._watcher (18:43:26):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 181, in <module>
  File "core.pyc", line 341, in main
  File "wx_core.pyc", line 8010, in MainLoop
  File "wx_core.pyc", line 7306, in MainLoop
  File "core.pyc", line 312, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 56, in _queueEventCallback
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 86, in __init__
  File "eventHandler.pyc", line 92, in next
  File "eventHandler.pyc", line 112, in gen
  File "NVDAObjects__init__.pyc", line 338, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 18, in getTreeInterceptor
  File "virtualBuffers\MSHTML.pyc", line 189, in __contains__
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 890, in _get_parent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 918, in _get_parent
  File "NVDAObjects__init__.pyc", line 73, in **call**
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 397, in findOverlayClasses
  File "NVDAObjects\IAccessible__init__.pyc", line 373, in 
findOverlayClasses
  File "baseObject.pyc", line 21, in **get**
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 587, in _get_role
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 43, in __getitem__
  File "comtypes\client\lazybind.pyc", line 163, in caller
  File "comtypes\automation.pyc", line 664, in _invoke

DEBUGWARNING - eventHandler.executeEvent (18:43:26):
error executing event: stateChange on <NVDAObjects.IAccessible.MSHTML.MSHTML 
object at 0x03B45BD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 86, in **init**
  File "eventHandler.pyc", line 92, in next
  File "eventHandler.pyc", line 112, in gen
  File "NVDAObjects__init__.pyc", line 338, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 18, in getTreeInterceptor
  File "virtualBuffers\MSHTML.pyc", line 189, in __contains__
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 890, in _get_parent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 918, in _get_parent
  File "NVDAObjects__init__.pyc", line 73, in **call**
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 397, in findOverlayClasses
  File "NVDAObjects\IAccessible__init__.pyc", line 373, in 
findOverlayClasses
  File "baseObject.pyc", line 21, in **get**
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 587, in _get_role
  File "watchdog.pyc", line 192, in _COMError_init
CallCancelled
DEBUG - appModuleHandler.cleanup (18:43:26):
application iexplore closed
DEBUG - treeInterceptorHandler.killTreeInterceptor (18:43:27):
Killed treeInterceptor: <virtualBuffers.MSHTML.MSHTML object at 0x03B37F50>
IO - speech.speak (18:43:27):
Speaking [('en_GB'), u'Desktop  list'](LangChangeCommand)
IO - speech.speak (18:43:27):
Speaking [('en_GB'), u'My Documents  not selected  1 of 
76'](LangChangeCommand)

Where did it go? weird.

**Comment by ehollig** [comment]
@Brian1Gaff, is this still the case for you? Also, is there anything relevant in the log provided in https://github.com/nvaccess/nvda/issues/3884#issuecomment-155317470? CC @michaelDCurran

**Comment by leonardder** [comment]
Note that this mentions legacy stuff like IE8 and Outlook Express, so this is going to be a won't fix most likely. I'd rather close as works for me though :)

**Comment by Brian1Gaff** [comment]
This is very old and from memory I think this problem stopped after some 
other bug was fixed. I guess this ticket was missed then

The only issue with Outlook Express I know of is that if a plain text 
display is selected and also if a preview pane is allowed. Nvda can seem to 
make Outlook express think its out of memory and it cannot open the message 
editor or indeed some other windows. a restart of OE fixes it.

The actual suggestion is to avoid those usage cases and all seems to be 
well.

I'm using it now anyway. IE 8 is pointless, as its not allowed on many sites 
now.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment]
Thanks for the clarification!
