### ISSUE TITLE
an error occurs while reading the first line of a webpage!

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3915]
**Reported by aslani.ali on 2014-02-22 09:09**
by NVDA and latest Espeak, while reading the first line of [this webpage,](http://windows.microsoft.com/en-us/internet-explorer/download-ie) the sound specified for error event is played by NVDA.

**Comment by dkager** [comment]
Also getting this with IE11 on codepen.io. The attachment contains an isolated case. The error is as follows:

```
ERROR - scriptHandler.executeScript (13:49:06):
error executing script: <bound method MSHTML.script_topOfDocument of <virtualBuffers.MSHTML.MSHTML object at 0x04D8CA50>> with gesture u'ctrl+home'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "cursorManager.pyc", line 219, in script_topOfDocument
  File "cursorManager.pyc", line 124, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1044, in _set_selection
  File "browseMode.pyc", line 1059, in _shouldSetFocusToObj
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 911, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 207, in __call__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))
```

[svg-in-anchor.html.txt](https://github.com/nvaccess/nvda/files/210080/svg-in-anchor.html.txt)

**Comment by Brian1Gaff** [comment]
I've seen this for some time, but its only sometimes. My guess is that there 
is some kind of situation where the start of the buffer is seen as say, one 
character in from the start and hence its unable to go to -1.

I don't think I'veever seen it have any lasting  problem though.
 I've noticed a similay weirdness in Word from time to time as well.


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by bhavyashah** [comment]
The provided URl seems to be dead. Any updates to share about the current standing of this issue? @jcsteh @dkager @Brian1Gaff

**Comment by dkager** [comment]
Closing because of a lack of feedback.
