### ISSUE TITLE
Strange Error when reading with sayAll Command in Libre Office Editable Text Based Documents.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#3942]
**Reported by ateu on 2014-03-01 13:35**
When reading with sayAll command in Apache Openoffice 4.1, LibreOffice 4.2 and 4.3 and Ibm Lothus Symphony, specially when is encountered a short line (line containing a few characters) followed by a normal line, NVDA plays its error sound and an error message is logged. Although the reading is not stopped, this error may incommode a lot the user who is reading.

Follows the log message.

ERROR - eventHandler.executeEvent (10:18:09):
error executing event: caret on <NVDAObjects.Dynamic_SymphonyParagraphSymphonyTextEditableTextWithAutoSelectDetectionIAccessible object at 0x056BF3F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 86, in **init**
  File "eventHandler.pyc", line 93, in next
  File "compoundDocuments.pyc", line 411, in event_caret
  File "compoundDocuments.pyc", line 388, in makeTextInfo
  File "compoundDocuments.pyc", line 217, in **init**
  File "NVDAObjects__init__.pyc", line 909, in makeTextInfo
  File "textInfos\offsets.pyc", line 280, in **init**
  File "NVDAObjects\IAccessible__init__.pyc", line 156, in _getCaretOffset
RuntimeError: no active caret in this object

**Comment by Adriani90** [comment]
, @ateu @Qchristensen could you try to see if this is still reproducible? Thanks.

**Comment by Qchristensen** [comment]
It's working for me with NVDA 2018.4 and LibreOffice 6.1.3.2 or Open Office 4.1.4 on Windows 10.

Since even the original poster advised that it didn't cause any actual problems, just the error in the log, I'm going to close this issue.
