### ISSUE TITLE
Firefox textfield typeing and erasing causing lag.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4032]
**Reported by Aerikkala85 on 2014-03-27 19:25**
I dont know how to fix this or is it just bug. when using backspace to erase text from any textfield on firefox or chrome, it starts to lag very badly, making typeing difficult. any one has a solution  on this. i'll paste the logfile below
thank you.

INFO - **main** (21:21:25):
Starting NVDA
INFO - core.main (21:21:26):
Config dir: C:\Users\Nina\AppData\Roaming\nvda
INFO - core.main (21:21:26):
NVDA version 2014.1
INFO - core.main (21:21:26):
Using Windows version sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1')
INFO - core.main (21:21:26):
Using Python version 2.7.6 (default, Nov 10 2013, 19:24:18) [v.1500 32 bit (Intel)](MSC)
INFO - core.main (21:21:26):
Using comtypes version 0.6.2
INFO - synthDriverHandler.setSynth (21:21:26):
Loaded synthDriver sapi4
INFO - core.main (21:21:26):
Using wx version 2.8.12.1 (msw-unicode)
INFO - braille.initialize (21:21:26):
Using liblouis version 2.5.3
INFO - braille.BrailleHandler.setDisplayByName (21:21:26):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (21:21:26):
Braille input initialized
ERROR - globalPluginHandler.initialize (21:21:26):
Error initializing global plugin <class 'globalPlugins.systrayList_docHandler.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyo", line 32, in initialize
  File "C:\Users\Nina\AppData\Roaming\nvda\addons\systrayList\globalPlugins\systrayList_docHandler.py", line 58, in **init**
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 15: ordinal not in range(128)
INFO - core.main (21:21:27):
NVDA initialized
ERROR - eventHandler.executeEvent (21:21:31):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x05501790> with extra args of {'y': 324, 'x': 661}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:31):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F22F0> with extra args of {'y': 271, 'x': 651}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:31):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F22F0> with extra args of {'y': 253, 'x': 647}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:31):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F22F0> with extra args of {'y': 243, 'x': 644}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:31):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F22F0> with extra args of {'y': 229, 'x': 639}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:31):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F22F0> with extra args of {'y': 222, 'x': 637}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:31):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F22F0> with extra args of {'y': 212, 'x': 633}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 214, 'x': 826}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 229, 'x': 831}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 237, 'x': 833}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 237, 'x': 831}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 236, 'x': 826}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 233, 'x': 826}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 230, 'x': 826}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 226, 'x': 828}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 225, 'x': 830}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 220, 'x': 836}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 217, 'x': 843}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 213, 'x': 853}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 212, 'x': 856}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 211, 'x': 859}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 210, 'x': 860}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 209, 'x': 861}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:32):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x056F2D10> with extra args of {'y': 209, 'x': 861}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'
ERROR - eventHandler.executeEvent (21:21:33):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x02C1ED50> with extra args of {'y': 193, 'x': 899}
Traceback (most recent call last):
  File "eventHandler.pyo", line 136, in executeEvent
  File "eventHandler.pyo", line 84, in **init**
  File "eventHandler.pyo", line 91, in next
  File "NVDAObjects__init__.pyo", line 812, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyo", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'

**Comment by ehollig** [comment]
I can not reproduce this and can not say I have seen it either. Has anyone else seen this? CC @jcsteh

**Comment by leonardder** [comment]
I'm afraid this is another case of an author which we can't contact any more. Also, @JCSTeh asked for more information, which hasn't been provided on his request. Closing as invalid.
