### ISSUE TITLE
Outlook 2010: COM/RPC error is thrown when starting Outlook and when switching between various portions of Outlook

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4131]
**Reported by nvdakor on 2014-05-07 23:55**
Hi,
Ever since implementation of COM for retrieving message headers and Calendar information, NvDA throws COM/RPC erro when Outlook starts or when switching to various components of Outlook. For now, user needs to restart nvDA to use Outlook (such as reading message headers).
The traceback is as follows:

```
DEBUGWARNING - RPC process 5240 (OUTLOOK.EXE) (16:49:45):
Thread 8764, build\x86_64\remote\ia2Support.cpp, installIA2Support, 81:
Error registering class object, code -2147221008

IO - speech.speak (16:49:45):
Speaking [- Microsoft Outlook'](u'Opening)
IO - speech.speak (16:49:46):
Speaking [- Outlook Data File - Microsoft Outlook'](u'Inbox)
IO - speech.speak (16:49:46):
Speaking [Task Row  Type a new Task'](u'New)
DEBUGWARNING - RPC process 4288 (nvda_slave.exe) (16:49:46):
Python warning:
C:\Program Files (x86)\NVDA\library.zip\configobj.py:28: DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
ERROR - RPC process 4288 (nvda_slave.exe) (16:49:46):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 945, in GetResult
WindowsError: [-2147221021](Error) Operation unavailable
ERROR - eventHandler.executeEvent (16:49:46):
error executing event: gainFocus on <appModules.outlook.CalendarView object at 0x043614D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 845, in event_gainFocus
  File "appModules\outlook.pyc", line 332, in reportFocus
  File "baseObject.pyc", line 21, in __get__
  File "appModules\outlook.pyc", line 75, in _get_outlookVersion
  File "baseObject.pyc", line 21, in __get__
  File "appModules\outlook.pyc", line 68, in _get_nativeOm
  File "comHelper.pyc", line 58, in getActiveObject
RuntimeError: Helper process unable to get object; see log for details
```

This was observed in Outlook 2010 64-bit running on Windows 8.1 64-bit.
Thanks.

**Comment by leonardder** [comment]
CC @JosephSL

**Comment by zstanecic** [comment]
Yes, the com error is reproducible by just starting outlook.

Using outlook version 2016/office365

ERROR - eventHandler.executeEvent (09:30:37.823):

error executing event: gainFocus on <appModules.outlook.UIAGridRow object at 0x04D54030> with extra args of {}

Traceback (most recent call last):

  File "eventHandler.pyc", line 150, in executeEvent

  File "eventHandler.pyc", line 165, in doPreGainFocus

  File "NVDAObjects\__init__.pyc", line 295, in objectInForeground

  File "NVDAObjects\__init__.pyc", line 207, in findBestAPIClass

  File "NVDAObjects\__init__.pyc", line 206, in findBestAPIClass

  File "NVDAObjects\UIA\__init__.pyc", line 871, in kwargsFromSuper

COMError: (-2146233083, None, (None, None, None, 0, None))

**Comment by josephsl** [comment]
Hi,

I'm the original person behind this ticket...

The error from the last traceback (from another person) is quite different from the one I've seen, although it is true that COM error is still thrown. As that error deals with Outlook startup, I'll close this one for now.

Thanks.
