### ISSUE TITLE
Audible error  or errors in  Outlook Express under certain conditions in next branch

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4379]
**Reported by briang1 on 2014-08-11 11:54**
Basically, recently the error below has become quite common, usually when forwarding an email and there is spellcheck activity, just before the actual send occurs.
IO - speech.speak (09:12:51):
Speaking [('en_GB'), u'Suggestions:  list'](LangChangeCommand)
IO - speech.speak (09:12:51):
Speaking [('en_GB'), u'a  1 of 6'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (09:12:52):
Input: kb(desktop):tab
IO - speech.speak (09:12:52):
Speaking [('en_GB'), u'Ignore  button  Alt+i'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (09:12:54):
Input: kb(desktop):enter
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (09:12:54):
oleacc.AccessibleObjectFromEvent with window 262974, objectID -4 and childID 0: [-2147467259](Error) Unspecified error
IO - speech.speak (09:12:54):
Speaking [('en_GB'), u'pane'](LangChangeCommand)
IO - speech.speak (09:12:54):
Speaking [('en_GB'), u'To:  edit  multi line'](LangChangeCommand)
ERROR - eventHandler.executeEvent (09:12:54):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x03FD0590> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in **init**
  File "eventHandler.pyc", line 98, in next
  File "appModules\msimn.pyc", line 80, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\behaviors.pyc", line 166, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 862, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 806, in reportFocus
  File "speech.pyc", line 332, in speakObject
  File "NVDAObjects\window\edit.pyc", line 834, in makeTextInfo
  File "NVDAObjects__init__.pyc", line 928, in makeTextInfo
  File "textInfos\offsets.pyc", line 301, in **init**
  File "NVDAObjects\window\edit.pyc", line 324, in _getStoryLength
  File "winKernel.pyc", line 117, in virtualAllocEx
WindowsError: [6](Error) The handle is invalid.
ERROR - eventHandler.executeEvent (09:12:54):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x03FD0590> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\IAccessible__init__.pyc", line 1285, in event_caret
  File "NVDAObjects\window\edit.pyc", line 807, in event_caret
  File "NVDAObjects\window\edit.pyc", line 834, in makeTextInfo
  File "NVDAObjects__init__.pyc", line 928, in makeTextInfo
  File "textInfos\offsets.pyc", line 298, in **init**
  File "NVDAObjects\window\edit.pyc", line 274, in _getSelectionOffsets
  File "winKernel.pyc", line 117, in virtualAllocEx
WindowsError: [6](Error) The handle is invalid.
ERROR - eventHandler.executeEvent (09:12:54):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x03FD0590> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\IAccessible__init__.pyc", line 1285, in event_caret
  File "NVDAObjects\window\edit.pyc", line 807, in event_caret
  File "NVDAObjects\window\edit.pyc", line 834, in makeTextInfo
  File "NVDAObjects__init__.pyc", line 928, in makeTextInfo
  File "textInfos\offsets.pyc", line 298, in **init**
  File "NVDAObjects\window\edit.pyc", line 274, in _getSelectionOffsets
  File "winKernel.pyc", line 117, in virtualAllocEx
WindowsError: [6](Error) The handle is invalid.
IO - speech.speak (09:12:54):
Speaking [('en_GB'), u'Inbox - Outlook Express - Brian Gaff sofa'](LangChangeCommand)
IO - speech.speak (09:12:54):
Speaking [('en_GB'), u'Outlook Express Message List  list'](LangChangeCommand)
IO - speech.speak (09:12:54):
Speaking [('en_GB'), u'has attachment; From: Della at KAB; Subject: Next Exec Meeting; Received: 05/08/2014 13:03  1378 of 1389'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (09:12:59):
Input: kb(desktop):escape
IO - inputCore.InputManager.executeGesture (09:13:00):
Input: kb(desktop):escape
IO - inputCore.InputManager.executeGesture (09:13:04):
Input: kb(desktop):control+alt+r
INFO - core.main (09:13:04):
Exiting

It seems to be mostly harmless, but thought it worth reporting so it does not get lost.

**Comment by leonardder** [comment]
Al though this is an OE error, the error reported is not specific to OE as @JCSTeh pointed out, so leaving this open for now, unless a core dev thinks that this should be closed anyway.

**Comment by Adriani90** [comment]
@jcsteh, @michaelDCurran do you have any suggestions? @brian1gaff is this still a big issue for you?

**Comment by josephsl** [comment]
Hi,

Next branch -> master/alpha snapshots. If this happens while using a "repackaged" Outlook Express that's floating around, then we might as well leave it open, otherwise let's say goodbye (as this is Windows XP/Outlook Express specific).

Thanks.

**Comment by Brian1Gaff** [comment]
Floating around? No just the odd thing. I do not want to see outlook Express 
broken though, as I know a lot of folk still use the patched version in 
Windows 7. Its more of an issue with Windows 10 as Microsoft insist in 
uninstalling it every update, despite it being a far more user friendly and 
capable newsreader and email program than their rubbish mail software and 
arguably Thunderbird with its tree structure to cope with.
 For those of us who like to keep email in little boxes separate in 
different accounts that would leave the sledgehammer Outlook as a 
possibility, but I have to say its reliability has been awful for everyone 
I've spoken to.
 So lets not ship it out of hand because its xp, it has a place or folk 
would not use it.

 However at the moment in the current alpha its behaving most of the time 
with the odd weird error that seems not to be destructive.



Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
Honnestly, I don't think there is a feature for outlook express and I doubt that there is someone working on the app module. But we can still let this issue open for a while, maybe something happens about it.
cc: @lukaszgo1

**Comment by Adriani90** [comment]
Since Outlook express is discontinued since years, I am closing this issue as abandoned.
