### ISSUE TITLE
Liblouis or nvda bug randomly created a traceback.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4457]
**Reported by driemer.riemer@... on 2014-09-14 10:52**
The other day while doing math homework I was activating my braille configuration profile, which caused nvda to gain focus on my editor after activating the profile. Nvda randomly made the error tone, causing me to look at the log. I found a snippet, and think this could be a bug in liblouis. I asked in the chat room, and mesar also had suspission it could be liblouis as well. I provided the whole log so that tthere is useful edge cases to know when it happened, but I will paste the traceback elow.

```
Input: kb(laptop):downArrow
IO - speech.speak (19:57:03):
Speaking [('en_US'), u'autobraille'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (19:57:03):
Input: kb(laptop):enter
DEBUG - brailleDisplayDrivers.freedomScientific.BrailleDisplayDriver._configureDisplay (19:57:03):
Activating extended keys on freedom Scientific display. Display name: Focus, firmware version: 4.89.
INFO - braille.BrailleHandler.setDisplayByName (19:57:03):
Loaded braille display driver freedomScientific, current display has 40 cells.
IO - speech.speak (19:57:03):
Speaking [('en_US'), u'EdSharp - [hw4.txt](LangChangeCommand)']
ERROR - eventHandler.executeEvent (19:57:03):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x056142F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\Derek Riemer\AppData\Roaming\nvda\addons\AudioThemes3D\globalPlugins\AudioThemes\__init__.py", line 88, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 863, in event_gainFocus
  File "braille.pyc", line 1406, in handleGainFocus
  File "braille.pyc", line 1410, in _doNewObject
  File "braille.pyc", line 1200, in getFocusRegions
  File "braille.pyc", line 556, in update
  File "braille.pyc", line 386, in update
  File "louis\__init__.pyc", line 136, in translate
WindowsError: exception: access violation reading 0x3585C052
IO - speech.speak (19:57:03):
Speaking [('en_US'), u'hw4.txt'](LangChangeCommand)
```

**Comment by jcsteh** [comment]
Probable duplicates: #4914, #4960, #5039.

**Comment by jcsteh** [comment]
While there was no crash in this particular case, I suspect it's the same root cause as the probable duplicates I mentioned. It's pretty hard to reproduce, but we believe we've found a way.

**Comment by nvaccessAuto** [comment]
Incubated in 877c44e770cfb7aae9d4ae88c58ea3096d0e6652.

**Comment by nvaccessAuto** [comment]
Incubated in 4e6735307d52514f3b80c3a04b65d20e9682dadf.
