### ISSUE TITLE
error with using firefox.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4544]
**Reported by vgjh2005 on 2014-10-12 09:17**
Hi:
FireFox version:32.0.3
Follow is the error log:
ERROR - virtualBuffers.Gecko_ia2._loadBuffer (11:16:57):
Traceback (most recent call last):
  File "virtualBuffers__init__.pyc", line 692, in _loadBuffer
WindowsError: [1702](Error) 
ERROR - scriptHandler.executeScript (11:19:42):
error executing script: <bound method Gecko_ia2.script_moveByLine_back of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05E75530>> with gesture u'\u4e0a\u5149\u6807'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 174, in executeScript
  File "cursorManager.pyc", line 156, in script_moveByLine_back
  File "cursorManager.pyc", line 67, in _caretMovementScriptHelper
  File "virtualBuffers__init__.pyc", line 728, in makeTextInfo
  File "virtualBuffers__init__.pyc", line 150, in **init**
  File "textInfos\offsets.pyc", line 298, in **init**
  File "virtualBuffers__init__.pyc", line 155, in _getSelectionOffsets
WindowsError: [1775](Error) 
When I use the mouse to move to the browse cursor, error is occured:
ERROR - eventHandler.executeEvent (11:20:26):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x05626250> with extra args of {'y': 0, 'x': 83}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects__init__.pyc", line 831, in event_mouseMove
  File "NVDAObjects\IAccessible__init__.pyc", line 141, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'

**Comment by ehollig** [comment]
As @jcsteh said in https://github.com/nvaccess/nvda/issues/4544#issuecomment-155329040, those two errors are pretty harmless. Also, it is unclear on what steps were performed to get these errors. Mouse tracking issue will be covered in #3654, therefore this is a duplicate.
The URL provided in https://github.com/nvaccessAuto does not exist anymore, therefore I am unable to replicate the example provided. @jcsteh, does the log provided in this comment provide anything useful?
