### ISSUE TITLE
candidateList error.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4545]
**Reported by vgjh2005 on 2014-10-12 09:21**
Hi:
windows version: windows 7 64bit
When I press tab to through the show desktop button,this error is occured:
ERROR - queueHandler.flushQueue (17:07:20):
Error in func handleInputCandidateListUpdate from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "NVDAHelper.pyc", line 207, in handleInputCandidateListUpdate
  File "NVDAObjects__init__.pyc", line 128, in **call**
  File "appModules\explorer.pyc", line 181, in event_NVDAObject_init
  File "baseObject.pyc", line 21, in **get**
  File "NVDAObjects\IAccessible__init__.pyc", line 777, in _get_role
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 761, in _get_IAccessibleRole
AttributeError: 'Dynamic_NotificationAreaCandidateItem' object has no attribute 'IAccessibleObject'

**Comment by bhavyashah** [comment]
@vgjh2005  Do you still experience the originally reported errors?

**Comment by vgjh2005** [comment]
Please close it.

**Comment by ehollig** [comment]
Closing as requested in https://github.com/nvaccess/nvda/issues/4545#issuecomment-328396645
