### ISSUE TITLE
Constant errors with Scintilla based editors in some cases

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4555]
**Reported by a11cf0.vk on 2014-10-17 11:45**
Steps to reproduce:
1. Open a relatively large text file in any Scintilla based editor such as Notepad++. userGuide.html that comes with NVDA is a good file to test.
2. Go to the bottom of the file.
3. Press and hold the up arrow key.

While the up arrow key is held, NVDA will constantly produce the following error until the top of the document is reached.

error executing event: caret on <NVDAObjects.Dynamic_ScintillaIAccessibleScintillaWindowNVDAObject object at 0x058E3290> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in **init**
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\IAccessible__init__.pyc", line 1286, in event_caret
  File "NVDAObjects\behaviors.pyc", line 171, in event_caret
  File "editableText.pyc", line 234, in detectPossibleSelectionChange
  File "speech.pyc", line 482, in speakSelectionChange
  File "baseObject.pyc", line 21, in **get**
  File "textInfos\offsets.pyc", line 407, in _get_text
  File "NVDAObjects\window\scintilla.pyc", line 156, in _getTextRange
  File "winKernel.pyc", line 117, in virtualAllocEx
WindowsError: [8](Error) Недостаточно памяти для обработки команды.

Thanks!

**Comment by leonardder** [comment]
I can't reproduce this with NVDA Next and a recent version of Notepad++. As I'm afraid we can't track down the original author of this issue, I will close this as works for me. Please get in touch if this is still a problem.
