### ISSUE TITLE
Activating the routing key above the current position in a LibreOffice document generates a stacktrace

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4694]
**Reported by bramd on 2014-12-15 00:24**
Activating the braille routing key above the current cursor position in a LibreOffice document generates the following stacktrace:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 176, in executeScript
  File "globalCommands.pyc", line 1266, in script_braille_routeTo
  File "braille.pyc", line 1362, in routeTo
  File "braille.pyc", line 1108, in routeTo
  File "braille.pyc", line 835, in routeTo
  File "textInfos__init__.pyc", line 444, in activate
AttributeError: 'CompoundDocument' object has no attribute 'isInForeground'

Using the routing keys to move the cursor works fine. Tested with LibreOffice 4.3.4.1.

**Comment by leonardder** [comment]
cc "bramd

**Comment by bramd** [comment]
Still reproducible here on latest next. It seems we need to implement the isInForeground property for CompoundDocuments. However, I don't know how to determine if such an object is in the foreground.

**Comment by Adriani90** [comment]
No updates from initial author since many years and also no updates from other users upon request. Closing as abandoned.

If you are still having this issue, please comment and we can reopen.
