### ISSUE TITLE
QT5 TextEdit Results in Crash in NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4826]
**Reported by trumpton on 2015-01-18 19:54**
Windows XP or Windows 8.1, with Latest NVDA.
Simple Application build with QT5.4.1.
Tab into a plaintext edit, and hold down enter.
Application (and NVDA) lock up.
Once application killed, NVDA Log reads as shown below.
Note that the program does not crash if WindowsEyes is used instead of NVDA.

---

NVDA Log File

NVDA initialized
IO - speech.speak (19:36:48):
Speaking [('en_GB'), u'Visual Studio Command Prompt (2010)  terminal'](LangChangeCommand)
IO - speech.speak (19:36:48):
Speaking [('en_GB'), u'E:\Release>                                                                     '](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (19:36:53):
Input: kb(desktop):upArrow
IO - speech.speak (19:36:53):
Speaking [('en_GB'), u'E:\Release>texteditcrash                                                        '](LangChangeCommand)
IO - speech.speak (19:36:53):
Speaking [('en_GB'), u'texteditcrash'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (19:36:53):
Input: kb(desktop):enter
IO - speech.speak (19:36:53):
Speaking [('en_GB'), u'E:\Release>                                                                     '](LangChangeCommand)
IO - speech.speak (19:36:59):
Speaking [('en_GB'), u'MainWindow  window'](LangChangeCommand)
IO - speech.speak (19:36:59):
Speaking [('en_GB'), u'edit  multi line'](LangChangeCommand)
IO - speech.speak (19:36:59):
Speaking [('en_GB'), u'blank'](LangChangeCommand)
IO - inputCore.InputManager.executeGesture (19:37:01):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:01):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:02):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:03):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:03):
Input: kb(desktop):enter
IO - inputCore.InputManager.executeGesture (19:37:03):
Input: kb(desktop):enter
DEBUGWARNING - watchdog._watcher (19:37:08):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 166, in <module>
  File "core.pyo", line 357, in main
  File "wx_core.pyo", line 8010, in MainLoop
  File "wx_core.pyo", line 7306, in MainLoop
  File "core.pyo", line 328, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "scriptHandler.pyo", line 136, in _queueScriptCallback
  File "scriptHandler.pyo", line 174, in executeScript
  File "editableText.pyo", line 128, in script_caret_newLine
  File "speech.pyo", line 611, in speakTextInfo
  File "textInfos\offsets.pyo", line 394, in getTextWithFields
  File "NVDAObjects\IAccessible__init__.pyo", line 197, in _getFormatFieldAndOffsets
  File "comtypes__init__.pyo", line 795, in **call**

DEBUGWARNING - scriptHandler.executeScript (19:37:08):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionIAccessible.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionIAccessible object at 0x03D02AB0>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 174, in executeScript
  File "editableText.pyo", line 128, in script_caret_newLine
  File "speech.pyo", line 611, in speakTextInfo
  File "textInfos\offsets.pyo", line 394, in getTextWithFields
  File "watchdog.pyo", line 191, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (19:37:09):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 166, in <module>
  File "core.pyo", line 357, in main
  File "wx_core.pyo", line 8010, in MainLoop
  File "wx_core.pyo", line 7306, in MainLoop
  File "core.pyo", line 328, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "eventHandler.pyo", line 59, in _queueEventCallback
  File "eventHandler.pyo", line 141, in executeEvent
  File "eventHandler.pyo", line 89, in __init__
  File "eventHandler.pyo", line 96, in next
  File "NVDAObjects__init__.pyo", line 807, in event_typedCharacter
  File "speech.pyo", line 539, in speakTypedCharacters
  File "api.pyo", line 235, in isTypingProtected
  File "baseObject.pyo", line 34, in **get**
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyo", line 802, in _get_states
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyo", line 792, in _get_IAccessibleStates
  File "comtypes__init__.pyo", line 795, in **call**

DEBUGWARNING - eventHandler.executeEvent (19:37:09):
error executing event: typedCharacter on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionIAccessible object at 0x03D02AB0> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
  File "eventHandler.pyo", line 141, in executeEvent
  File "eventHandler.pyo", line 89, in **init**
  File "eventHandler.pyo", line 96, in next
  File "NVDAObjects__init__.pyo", line 807, in event_typedCharacter
  File "speech.pyo", line 539, in speakTypedCharacters
  File "api.pyo", line 235, in isTypingProtected
  File "baseObject.pyo", line 34, in **get**
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyo", line 802, in _get_states
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "watchdog.pyo", line 191, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (19:37:09):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 166, in <module>
  File "core.pyo", line 357, in main
  File "wx_core.pyo", line 8010, in MainLoop
  File "wx_core.pyo", line 7306, in MainLoop
  File "core.pyo", line 327, in Notify
  File "IAccessibleHandler.pyo", line 858, in pumpAll
  File "IAccessibleHandler.pyo", line 605, in processGenericWinEvent
  File "IAccessibleHandler.pyo", line 523, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyo", line 37, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyo", line 338, in accessibleObjectFromEvent
  File "oleacc.pyo", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:37:10):
oleacc.AccessibleObjectFromEvent with window 262450, objectID -4 and childID 0: 
DEBUGWARNING - watchdog._watcher (19:37:12):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 166, in <module>
  File "core.pyo", line 357, in main
  File "wx_core.pyo", line 8010, in MainLoop
  File "wx_core.pyo", line 7306, in MainLoop
  File "core.pyo", line 328, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "scriptHandler.pyo", line 136, in _queueScriptCallback
  File "scriptHandler.pyo", line 174, in executeScript
  File "editableText.pyo", line 107, in script_caret_newLine
  File "NVDAObjects__init__.pyo", line 926, in makeTextInfo
  File "textInfos\offsets.pyo", line 296, in **init**
  File "NVDAObjects\IAccessible__init__.pyo", line 151, in _getCaretOffset

**Comment by bhavyashah** [comment]
The QT bug cited in one comment present at https://bugreports.qt.io/browse/QTBUG-39522 appears to be closed as invalid. Thoughts?

**Comment by leonardder** [comment]
As QT now has an entirely new accessibility implementation based on UIA, I"m closing this for now. If the issue still persists in QT 5.11 and above, please file a new issue.
