### ISSUE TITLE
Very frequent error in Firefox when navigating from one page to another

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4859]
**Reported by msuch on 2015-01-29 15:16**
This does not seem to really affect navigation, but the NVDA's error sound is heard and users wonder why.
It does not seem to happen when no braille display is connected.
It systematically produice the following error lines.
ERROR - queueHandler.flushQueue (16:02:45):
Error in func _handleUpdate from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers__init__.pyc", line 1262, in _handleUpdate
  File "braille.pyc", line 1475, in handleUpdate
  File "braille.pyc", line 774, in update
  File "textInfos\offsets.pyc", line 344, in expand
  File "virtualBuffers__init__.pyc", line 322, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 326, in _getUnitOffsets
  File "virtualBuffers__init__.pyc", line 258, in _getLineOffsets
WindowsError: [1775](Error) A null context descriptor has been passed from client to host during a remote procedure call (RPC)
ERROR - queueHandler.flushQueue (16:02:45):
Error in func _handleUpdate from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers__init__.pyc", line 1262, in _handleUpdate
  File "braille.pyc", line 1475, in handleUpdate
  File "braille.pyc", line 774, in update
  File "textInfos\offsets.pyc", line 344, in expand
  File "virtualBuffers__init__.pyc", line 322, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 326, in _getUnitOffsets
  File "virtualBuffers__init__.pyc", line 258, in _getLineOffsets
WindowsError: [1775](Error) A null context descriptor has been passed from client to host during a remote procedure call (RPC)

**Comment by dkager** [comment]
This is still true in Firefox 52.0.2:

```
ERROR - queueHandler.flushQueue (14:55:04):
Error in func _handleUpdate from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 608, in _handleUpdate
  File "braille.pyc", line 1718, in handleUpdate
  File "braille.pyc", line 953, in update
  File "textInfos\offsets.pyc", line 348, in expand
  File "virtualBuffers\__init__.pyc", line 320, in _getUnitOffsets
  File "textInfos\offsets.pyc", line 330, in _getUnitOffsets
  File "virtualBuffers\__init__.pyc", line 250, in _getLineOffsets
WindowsError: [Error 1775] A null context handle was passed from the client to the host during a remote procedure call
```

An almost sure way to get this error is to type a search query into Google and press Enter. After pressing Enter the error occurs but the results page loads just fine.

**Comment by feerrenrut** [comment]
I am unable to reproduce this. Steps taken:
- Open Firefox
- Go to https://www.google.com
- Type in something to search and press enter

I tried with and without "Google Instant"

- No Braille display
- Firefox version `52.0.2 (32-bit)`
- NVDA Version: `next-13950,c31e74f7`
- Windows 10 Version 1607 Build 14393.953

**Comment by dkager** [comment]
Same setup here, except on NVDA master. The key is probably to have a braille display connected. I can only reproduce this with braille (HumanWare Brailliant BI in my case).

**Comment by jcsteh** [comment]
CC @MichelSuch.

P3 because this is a harmless exception. That said, I think I already have a trivial fix. Can those experiencing this please try [this try build](https://ci.appveyor.com/api/buildjobs/ik97393w9llth64o/artifacts/output%2Fnvda_snapshot_try-i4859VbufUpdateNull-13973%2Cb76c12f6.exe) and report whether it fixes the problem? Thanks.

**Comment by dkager** [comment]
This looks like it fixes the issue for me.
