### ISSUE TITLE
Sometimes an error occurs when starting NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4914]
**Reported by PZajda on 2015-02-12 10:35**
When starting NVDA, sometimes I have the following error:
``` INFO - __main__ (11:27:01):
Starting NVDA
INFO - core.main (11:27:02):
Config dir: C:\Users\pzajda\AppData\Roaming\nvda
INFO - core.main (11:27:02):
NVDA version next-11658,29fdc71
INFO - core.main (11:27:02):
Using Windows version sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1')
INFO - core.main (11:27:02):
Using Python version 2.7.9 (default, Dec 10 2014, 12:24:55) [v.1500 32 bit (Intel)](MSC)
INFO - core.main (11:27:02):
Using comtypes version 0.6.2
INFO - synthDriverHandler.setSynth (11:27:03):
Loaded synthDriver sapi5
INFO - core.main (11:27:03):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (11:27:03):
Using liblouis version 2.6.0
INFO - braille.BrailleHandler.setDisplayByName (11:27:03):
Loaded braille display driver brltty, current display has 40 cells.
INFO - brailleInput.initialize (11:27:03):
Braille input initialized
ERROR - core.main (11:27:03):
Traceback (most recent call last):
  File "core.pyc", line 312, in main
  File "braille.pyc", line 1419, in message
  File "braille.pyc", line 433, in update
  File "louis\__init__.pyc", line 136, in translate
WindowsError: exception: access violation reading 0x47E95972
INFO - core.main (11:27:03):
NVDA initialized
ERROR - eventHandler.executeEvent (11:27:05):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x058FF410> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "appModules\nvda.pyc", line 42, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 863, in event_gainFocus
  File "braille.pyc", line 1453, in handleGainFocus
  File "braille.pyc", line 1467, in _doNewObject
  File "braille.pyc", line 1444, in _dismissMessage
AttributeError: 'NoneType' object has no attribute 'Stop' ```
It occurs randomly, when restarting NVDA sometimes I have it again, sometimes not.

**Comment by jcsteh** [comment]
We believe this to be the same underlying cause as #4457. A fix is now available for testing in the latest "next" branch snapshots.
