### ISSUE TITLE
NVDA crashes at Startup with BRLTTY enabled

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5039]
**Reported by laughingthunder on 2015-04-16 06:24**
There is a message posted to the NVDA user mailing list regarding NVDA crashing at Startup with BRLTTY enabled.  I am posting it here for tracking purposes.

--Begin Message--

NVDA crashes when it starts up and the selected braille display is Brltty.  It crashes so hard that you either have to hit the power switch, or change to a different user account, kill nvda.exe and then switch back. I managed to capture a log file of the crash. I don't know how much use it'll be, but below are the relevant sections.
INFO - __main__ (13:00:06):
Starting NVDA
INFO - core.main (13:00:06):
Config dir: C:\Users\asterisk\AppData\Roaming\nvda
INFO - core.main (13:00:06):
NVDA version 2015.1
INFO - core.main (13:00:06):
Using Windows version sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1')
INFO - core.main (13:00:06):
Using Python version 2.7.9 (default, Dec 10 2014, 12:24:55) [v.1500 32 bit (Intel)](MSC)
INFO - core.main (13:00:06):
Using comtypes version 0.6.2
NFO - braille.initialize (13:00:06):
Using liblouis version 2.6.0
INFO - braille.BrailleHandler.setDisplayByName (13:00:06):
Loaded braille display driver brltty, current display has 80 cells.
INFO - brailleInput.initialize (13:00:06):
Braille input initialized
ERROR - eventHandler.executeEvent (13:00:06):
error executing event: becomeNavigatorObject on <NVDAObjects.window.Desktop object at 0x05728FB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 141, in executeEvent
  File "eventHandler.pyo", line 89, in __init__
  File "eventHandler.pyo", line 96, in next
  File "NVDAObjects\__init__.pyo", line 875, in event_becomeNavigatorObject
  File "braille.pyo", line 1478, in handleReviewMove
  File "braille.pyo", line 1402, in _doNewObject
  File "braille.pyo", line 1192, in getFocusRegions
  File "braille.pyo", line 549, in update
  File "braille.pyo", line 394, in update
  File "louis\__init__.pyo", line 136, in translate
WindowsError: exception: access violation reading 0x67205645
ERROR - eventHandler.executeEvent (13:00:06):
error executing event: becomeNavigatorObject on <NVDAObjects.window.Desktop object at 0x05728FB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 141, in executeEvent
  File "eventHandler.pyo", line 89, in __init__
  File "eventHandler.pyo", line 96, in next
  File "NVDAObjects\__init__.pyo", line 875, in event_becomeNavigatorObject
  File "braille.pyo", line 1478, in handleReviewMove
  File "braille.pyo", line 1402, in _doNewObject
  File "braille.pyo", line 1192, in getFocusRegions
  File "braille.pyo", line 549, in update
  File "braille.pyo", line 394, in update
  File "louis\__init__.pyo", line 136, in translate
WindowsError: exception: access violation reading 0x6745DA0D
If you start Brltty while NVDA is loaded, there is no crash. This crash only happens when NVDA is started while Brltty is enabled. I do not know if a similar crash happens if another braille display is loaded.
I hope something can be done about this, because Brltty is the only service which supports my current desktop display.

--End Message--

**Comment by jcsteh** [comment]
We believe this to be the same underlying cause as #4457. A fix is now available for testing in the latest "next" branch snapshots.
