### ISSUE TITLE
Something wrong with NVDA's use of the Microsoft  Visual C++ Runtime Library

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5346]
**Reported by twynn92 on 2015-09-09 16:32**
Using NVDA 2015.3 as well as Master snapshots, NVDA seems to have a problem with the Microsoft Visual C++ Runtime Library. It might be that I am on a faulty Windows 8.1 (X86( configuration, but I uninstalled Microsoft C++ Redistributables 2005, 2010, and 2013 to see if it would resolve the issue. It didn't.

Upon loading the Java control panel (JRE 8 Update 60;) with the Access Bridge enabled, I get the following log output:

```
  ERROR - unhandled exception (10:01:17):
   ValueError: invalid string pointer 0x00DC9558
   ERROR - unhandled exception (10:01:18):
   ValueError: invalid string pointer 0x00DC8FF4
   DEBUGWARNING - watchdog._watcher (10:01:18):
   Trying to recover from freeze, core stack:
     File "nvda.pyw", line 167, in <module>
     File "core.pyo", line 371, in main
     File "wx\_core.pyo", line 8657, in MainLoop
     File "wx\_core.pyo", line 7952, in MainLoop
     File "core.pyo", line 340, in Notify
     File "JABHandler.pyo", line 681, in pumpAll
     File "queueHandler.pyo", line 50, in flushQueue
     File "JABHandler.pyo", line 649, in enterJavaWindow_helper
     File "JABHandler.pyo", line 532, in event_gainFocus
     File "NVDAObjects\__init__.pyo", line 69, in __call__
     File "NVDAObjects\JAB\__init__.pyo", line 219, in __init__
     File "baseObject.pyo", line 34, in __get__
     File "baseObject.pyo", line 110, in _getPropertyViaCache
     File "NVDAObjects\JAB\__init__.pyo", line 224, in _get__JABAccContextInfo
     File "JABHandler.pyo", line 344, in getAccessibleContextInfo
```

I saw a Microsoft Visual C++ Runtime Library error pop up once in the above scenario.

 A related issue probably occurs with reading an untagged document in Adobe Acrobat:

```
   DEBUGWARNING - watchdog._watcher (10:32:46):
   Trying to recover from freeze, core stack:
     File "nvda.pyw", line 167, in <module>
     File "core.pyo", line 371, in main
     File "wx\_core.pyo", line 8657, in MainLoop
     File "wx\_core.pyo", line 7952, in MainLoop
     File "core.pyo", line 342, in Notify
     File "queueHandler.pyo", line 83, in pumpAll
     File "queueHandler.pyo", line 50, in flushQueue
     File "eventHandler.pyo", line 61, in _queueEventCallback
     File "eventHandler.pyo", line 143, in executeEvent
     File "eventHandler.pyo", line 91, in __init__
     File "eventHandler.pyo", line 98, in next
     File "C:\Users\Timothy Wynn\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 341, in event_gainFocus
     File "eventHandler.pyo", line 98, in next
     File "C:\Users\Timothy Wynn\AppData\Roaming\nvda\addons\enhancedTouchGestures\globalPlugins\enhancedTouchGestures.py", line 43, in event_gainFocus
     File "eventHandler.pyo", line 98, in next
     File "C:\Users\Timothy Wynn\AppData\Roaming\nvda\addons\objsounds\globalPlugins\objsounds\__init__.py", line 48, in event_gainFocus
     File "eventHandler.pyo", line 98, in next
     File "NVDAObjects\__init__.pyo", line 867, in event_gainFocus
     File "NVDAObjects\__init__.pyo", line 811, in reportFocus
     File "speech.pyo", line 352, in speakObject
     File "speech.pyo", line 269, in speakObjectProperties
     File "baseObject.pyo", line 34, in __get__
     File "baseObject.pyo", line 110, in _getPropertyViaCache
     File "NVDAObjects\IAccessible\__init__.pyo", line 704, in _get_value
     File "comtypes\__init__.pyo", line 795, in __call__

   DEBUGWARNING - eventHandler.executeEvent (10:32:46):
   error executing event: gainFocus on <NVDAObjects.IAccessible.adobeAcrobat.RootTextNode object at 0x044420D0> with extra args of {}
   Traceback (most recent call last):
     File "eventHandler.pyo", line 143, in executeEvent
     File "eventHandler.pyo", line 91, in __init__
     File "eventHandler.pyo", line 98, in next
     File "C:\Users\Timothy Wynn\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 341, in event_gainFocus
     File "eventHandler.pyo", line 98, in next
     File "C:\Users\Timothy Wynn\AppData\Roaming\nvda\addons\enhancedTouchGestures\globalPlugins\enhancedTouchGestures.py", line 43, in event_gainFocus
     File "eventHandler.pyo", line 98, in next
     File "C:\Users\Timothy Wynn\AppData\Roaming\nvda\addons\objsounds\globalPlugins\objsounds\__init__.py", line 48, in event_gainFocus
     File "eventHandler.pyo", line 98, in next
     File "NVDAObjects\__init__.pyo", line 867, in event_gainFocus
     File "NVDAObjects\__init__.pyo", line 811, in reportFocus
     File "speech.pyo", line 352, in speakObject
     File "speech.pyo", line 269, in speakObjectProperties
     File "baseObject.pyo", line 34, in __get__
     File "baseObject.pyo", line 110, in _getPropertyViaCache
     File "watchdog.pyo", line 197, in _COMError_init
   CallCancelled
```

 I don't think this is under the purview of a NVDA-specific issue, but as I do not get said errors when NVDA is not running, I figure I'd file a bug report just in case.

**Comment by leonardder** [comment]
I'm afraid it's not possible to track down the original author any more. The issue sounds more like a JAVA bug than a Visual C++ runtime.

**Comment by jcsteh** [comment]
It could also be a misconfigured Java Access Bridge. Completely reinstalling Java and the Java Access Bridge might help. Closing, since we can't contact the reporter.
