### ISSUE TITLE
Strange happenings in XP on Firefox launch with next snapshots

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#5554]
Log fragment from windows XP running latest next snap zas firefox starts from a desktop shortcut. All the versions of nvda will have the watchdog issues at the start, but only next has the inability to go into the page set as home and it requires you to open the file menu then close it to trigger entry, at which point it throws the errors shown.
 The next snap is set to not do a say all on entry in order to stop verbosity when it starts to go into the page for clarity. I have play sound on  entry to an edit field on, so no indication in the log, but I think the same occurs if you set it to say focus mode. 
 It seems to  happen almost every time on the  start page search engine and sometimes on other pages as well randomly when  changing and attempting to  say things the first time. Is there anything else I can try?
 As I say its on XP and the latest stable of Firefox.

I notice its also looking at adobe flash for some odd reason too.

IO - speech.speak (10:26:23):
Speaking [LangChangeCommand ('en_GB'), u'Mozilla Firefox  13 of 66']
DEBUG - queueHandler.pumpAll (10:26:23):
generator 9262 finished
IO - inputCore.InputManager.executeGesture (10:26:24):
Input: kb(desktop):enter
DEBUGWARNING - watchdog._watcher (10:26:34):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 381, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 887, in pumpAll
  File "IAccessibleHandler.pyc", line 754, in processForegroundWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 37, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 344, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - core.Notify (10:26:34):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 887, in pumpAll
  File "IAccessibleHandler.pyc", line 754, in processForegroundWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 59, in **call**
  File "NVDAObjects__init__.pyc", line 188, in findBestAPIClass
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 430, in kwargsFromSuper
  File "watchdog.pyc", line 198, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (10:26:35):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 381, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 872, in pumpAll
  File "IAccessibleHandler.pyc", line 654, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 76, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 449, in findOverlayClasses
  File "NVDAObjects\IAccessible\mozilla.pyc", line 229, in findExtraOverlayClasses
  File "NVDAObjects\IAccessible\mozilla.pyc", line 120, in getGeckoVersion
  File "comtypes__init__.pyc", line 1111, in QueryService

DEBUGWARNING - core.Notify (10:26:35):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 872, in pumpAll
  File "IAccessibleHandler.pyc", line 654, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 76, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 449, in findOverlayClasses
  File "NVDAObjects\IAccessible\mozilla.pyc", line 229, in findExtraOverlayClasses
  File "watchdog.pyc", line 198, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (10:26:43):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 381, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 884, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 37, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 344, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - core.Notify (10:26:44):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 884, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 69, in **call**
  File "watchdog.pyc", line 198, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (10:26:45):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 381, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 884, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 59, in **call**
  File "NVDAObjects__init__.pyc", line 188, in findBestAPIClass
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 430, in kwargsFromSuper
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 155, in HTMLNodeFromIAccessible
  File "comtypes__init__.pyc", line 1111, in QueryService

DEBUGWARNING - watchdog._watcher (10:26:48):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 381, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 884, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 37, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 344, in accessibleObjectFromEvent
  File "oleacc.pyc", line 240, in AccessibleObjectFromEvent

DEBUGWARNING - core.Notify (10:26:48):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 884, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 76, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 446, in findOverlayClasses
  File "watchdog.pyc", line 198, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (10:26:49):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 381, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 351, in Notify
  File "IAccessibleHandler.pyc", line 884, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects__init__.pyc", line 76, in **call**
  File "NVDAObjects\IAccessible__init__.pyc", line 446, in findOverlayClasses
  File "NVDAObjects\IAccessible\adobeFlash.pyc", line 98, in findExtraOverlayClasses
  File "comtypes__init__.pyc", line 1111, in QueryService

IO - speech.speak (10:26:49):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Search Engine - Mozilla Firefox']
IO - speech.speak (10:26:49):
Speaking [LangChangeCommand ('en_GB'), u'unknown']
IO - speech.speak (10:26:49):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Search Engine - Mozilla Firefox  edit']
IO - speech.speak (10:26:49):
Speaking [LangChangeCommand ('en_GB'), u'unknown']
IO - inputCore.InputManager.executeGesture (10:53:21):
Input: kb(desktop):downArrow
IO - inputCore.InputManager.executeGesture (10:53:22):
Input: kb(desktop):upArrow
IO - speech.speak (10:53:24):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Search Engine - Mozilla Firefox']
IO - speech.speak (10:53:24):
Speaking [LangChangeCommand ('en_GB'), u'Menu Bar  tool bar']
IO - speech.speak (10:53:24):
Speaking [LangChangeCommand ('en_GB'), u'File  subMenu  Alt+F  1 of 7']
IO - inputCore.InputManager.executeGesture (10:53:27):
Input: kb(desktop):escape
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2WindowHandle (10:53:27):
IAccessible2::windowHandle failed: (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (10:53:27):
Resorting to WindowFromPoint on accLocation
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.**init** (10:53:27):
accLocation failed: (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.DynamicNVDAObjectType.**call** (10:53:27):
Invalid NVDAObject: Can't get a window handle from IAccessible
Stack trace:
  File "nvda.pyw", line 191, in <module>
  File "core.pyc", line 381, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 352, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 61, in _queueEventCallback
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 151, in doPreGainFocus
  File "api.pyc", line 107, in setFocusObject
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects__init__.pyc", line 475, in _get_container
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\mozilla.pyc", line 40, in _get_parent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 913, in _get_parent
  File "NVDAObjects__init__.pyc", line 71, in **call**
DEBUGWARNING - NVDAObjects.IAccessible.Mozilla._get_IA2Attributes (10:53:27):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.BrokenFocusedState._get_IA2Attributes (10:53:27):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
IO - speech.speak (10:53:27):
Speaking [LangChangeCommand ('en_GB'), u'table']
DEBUGWARNING - NVDAObjects.IAccessible.Dynamic_RowWithFakeNavigationMozillaIAccessible._get_IA2Attributes (10:53:27):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.Mozilla._get_IA2Attributes (10:53:27):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
IO - speech.speak (10:53:27):
Speaking [LangChangeCommand ('en_GB'), u'cell']
DEBUGWARNING - NVDAObjects.IAccessible.Mozilla._get_IA2Attributes (10:53:27):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
IO - speech.speak (10:53:27):
Speaking [LangChangeCommand ('en_GB'), u'edit']
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getCaretOffset (10:53:27):
IAccessibleText::caretOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible__init__.pyc", line 151, in _getCaretOffset
COMError: (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (10:53:27):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x03364FD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "appModules\firefox.pyc", line 24, in event_stateChange
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\behaviors.pyc", line 166, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 860, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 804, in reportFocus
  File "speech.pyc", line 371, in speakObject
  File "speech.pyc", line 673, in speakTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 291, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 240, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'
DEBUG - treeInterceptorHandler.update (10:53:28):
Adding new treeInterceptor to runningTable: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x032AD710>
IO - speech.speak (10:53:28):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Search Engine - Mozilla Firefox']
IO - speech.speak (10:53:28):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Search Engine  document']
IO - speech.speak (10:53:28):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Search Engine - Mozilla Firefox']
IO - speech.speak (10:53:28):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Search Engine  document']
IO - speech.speak (10:53:28):
Speaking [LangChangeCommand ('en_GB'), u'edit']
IO - speech.speak (10:53:28):
Speaking [LangChangeCommand ('en_GB'), u'align default', u'blank']
IO - inputCore.InputManager.executeGesture (10:53:35):
Input: kb(desktop):control+alt+r
INFO - core.main (10:53:35):
Exiting
DEBUG - core._terminate (10:53:35):

**Comment by jcsteh** [comment]
What effect does this have from a user perspective? The problem is more 
of interest to me than the error sounds and log messages. Thanks.

**Comment by Brian1Gaff** [comment]
Mainly a delay or non appearance of the page content without use intervention I'd say. 
As I said in a post on the devel list, it is strange but other than making the result a bit jumpy and slow to react, it  still works most times. Of course I don't know if anything is in fact missing from the page if I cannot tell its there!
 
Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
  ----- Original Message -----

**Comment by jcsteh** [comment]
@Brian1Gaff, can you reproduce this on a system running a later version of Windows? While we're not explicitly dropping support for Windows XP, it's not feasible for us to fix issues related only to XP.

**Comment by Brian1Gaff** [comment]
Hi in the more recent snap this seems to have gone away.
 It seemed to be more to do with single processor machines of an older 
vintage than XP though. On the support for xp front, obviously it is getting 
old now but I feel if this had been a problem at boot up or update, it might 
have been worth fixing it, as mostly the rest is still running well.
 I'll keep an eye out though, if you get my drift.

I think the crunch will come when you move to Python 3. At that point I 
think it would be helpful to use detection of the platform to let users know 
they are running the last version of nvda that will run on their machines.


I think more worrying that this is the decreasing usefulness of a portable 
version in Windows10 due to the problems with access to key parts of the 
system for uninstalled programs.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
