### ISSUE TITLE
Clicking caps lock in an input of type password in Internet Explorer causes javascript error

### ISSUE THREAD

**Issue by jonnymoo** [nvaccess/nvda#5720]
Hopefully this is the right place to raise a bug?

Given I am on a windows 8.1 machine
and I have NVDA desktop version 2015.4  
and I have a html page with an input of type password on it
When I click into the input field
and enter some text
and then press caps lock 
I receive the following error:

"Script Error.  An error has occurred in the script on this page.  Line: 1, Char: 1, Error Invalid calling oject.  Code: 0, URL:"

This is the html to test it with

```
<!DOCTYPE html5>
<html>
<head></head>
<body>
    <input type="password" />
</body>
</html>
```

![nvda password](https://cloud.githubusercontent.com/assets/2386725/12681299/d612e6dc-c6a5-11e5-9b92-590887c28360.jpg)

Thanks,

Jonny

**Comment by jonnymoo** [comment]
I should have added that I am using Internet Explorer 11

**Comment by Adriani90** [comment]
@jonnymoo it seems this issue got lost in the issue cosmos here. Could you please test with NVDA 2018.4.1 or with last Alpha if this issue still occurs? Thanks.

**Comment by Adriani90** [comment]
This issue is still reproducible in IE11 with NVDA 2019.1.1. I get following errors in the log:

```
IO - inputCore.InputManager.executeGesture (21:14:29.927):
Input: kb(laptop):leftArrow
DEBUGWARNING - RPC process 4888 (iexplore.exe) (21:14:29.947):
Thread 2268, build\x86\vbufBase\storage.cpp, VBufStorage_buffer_t::getTextInRange, 948:
Bad offsets of 11 and 14, returning NULL

IO - inputCore.logTimeSinceInput (21:14:29.987):
0.060 sec since input
IO - speech._speakSpellingGen (21:14:29.987):
Speaking character u'Stern'
DEBUG - queueHandler.registerGeneratorObject (21:14:29.987):
Adding generator 22
DEBUG - queueHandler.pumpAll (21:14:30.007):
generator 22 finished
IO - inputCore.InputManager.executeGesture (21:14:30.247):
Input: kb(laptop):tab
DEBUGWARNING - Python warning (21:14:30.278):
C:\Program Files (x86)\NVDA\library.zip\keyboardHandler.py:524: DeprecationWarning: Yield() is deprecated
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:14:30.378):
oleacc.AccessibleObjectFromEvent with window 787596, objectID 100728857 and childID 0: [Error -2147467259] Unbekannter Fehler
IO - inputCore.logTimeSinceInput (21:14:30.417):
0.170 sec since input
IO - speech.speak (21:14:30.417):
Speaking [u'Eingabefeld']
IO - inputCore.logTimeSinceInput (21:14:30.417):
0.170 sec since input
IO - speech.speak (21:14:30.420):
Speaking [u'C:\\Users\\adria\\Downloads\\new 1.html ausgew\xe4hlt']
DEBUGWARNING - Python warning (21:14:30.427):
C:\Program Files (x86)\NVDA\library.zip\api.py:274: DeprecationWarning: Yield() is deprecated
IO - inputCore.InputManager.executeGesture (21:14:30.759):
Input: kb(laptop):shift+tab
IO - inputCore.InputManager.executeGesture (21:14:31.628):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (21:14:32.068):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (21:14:32.453):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:14:32.928):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (21:14:36.322):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:14:37.437):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:14:37.717):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (21:14:38.457):
Input: kb(laptop):alt+tab
DEBUGWARNING - watchdog._watcher (21:14:41.188):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyc", line 519, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1003, in Notify
  File "core.pyc", line 490, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1465, in event_caret
  File "NVDAObjects\window\edit.pyc", line 797, in event_caret
  File "api.pyc", line 276, in processPendingEvents
  File "IAccessibleHandler.pyc", line 883, in pumpAll
  File "IAccessibleHandler.pyc", line 657, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 532, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 47, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 85, in __call__
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 498, in findOverlayClasses
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 406, in _get__UIAControl
  File "baseObject.pyc", line 31, in __get__
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 722, in _get_role
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 83, in __getitem__
  File "comtypes\client\lazybind.pyc", line 226, in __call__
  File "comtypes\automation.pyc", line 729, in _invoke

DEBUGWARNING - eventHandler.executeEvent (21:14:41.188):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleEditWindowNVDAObject object at 0x04DA2630> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1465, in event_caret
  File "NVDAObjects\window\edit.pyc", line 797, in event_caret
  File "api.pyc", line 276, in processPendingEvents
  File "IAccessibleHandler.pyc", line 883, in pumpAll
  File "IAccessibleHandler.pyc", line 657, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 532, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 47, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 85, in __call__
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 498, in findOverlayClasses
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 406, in _get__UIAControl
  File "baseObject.pyc", line 31, in __get__
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 722, in _get_role
  File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
IO - inputCore.logTimeSinceInput (21:14:41.247):
2.790 sec since input
IO - speech.speak (21:14:41.257):
Speaking [u'Dokument']
IO - inputCore.logTimeSinceInput (21:14:41.257):
2.800 sec since input
IO - speech.speak (21:14:41.257):
Speaking [u'Eingabefeld  gesch\xfctzt', u'*************']
DEBUG - treeInterceptorHandler.update (21:14:41.497):
Adding new treeInterceptor to runningTable: <virtualBuffers.MSHTML.MSHTML object at 0x04F1A9D0>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (21:14:41.513):
Buffer load took 0.015 sec, 227 chars
IO - inputCore.logTimeSinceInput (21:14:41.528):
3.070 sec since input
IO - speech.speak (21:14:41.528):
Speaking [u'Skriptfehler']
```

**Comment by Adriani90** [comment]
cc: @leonardder maybe this is related to this warning:

DEBUGWARNING - RPC process 4888 (iexplore.exe) (21:14:29.947):
Thread 2268, build\x86\vbufBase\storage.cpp, VBufStorage_buffer_t::getTextInRange, 948:
Bad offsets of 11 and 14, returning NULL

**Comment by Qchristensen** [comment]
Confirming this issue is still present in Windows 10, version 1903, build 18362.175.

Workaround for now is to use SHIFT+letters to type capital letters.

**Comment by Adriani90** [comment]
Support for Internet explorer has completely ended in 2022 and the browser is removed automatically from machines that still have it after an Edge update in February 2023. I am closing this issue as stale since I don' expect any further accessibility updates to Internet Explorer, nor to the IE Mode in Microsoft Edge.
