### ISSUE TITLE
NVDA freezing when navigating among the message summaries of outlook 2016 mail boxes

### ISSUE THREAD

**Issue by pranavlal** [nvaccess/nvda#5745]
Hi,

I have several mail boxes in outlook 2016. When I navigate through the message summaries in any of these mail boxes, NVDA freezes at random intervals. What happens is that NVDA stops speaking when I hit the up or down arrow keys. I then hit ctrl+y to navigate to another mailbox. I then return to the original mail box and can resume navigating. 

NVDA version 2015.4
os=windows 10 professional

**Comment by jcsteh** [comment]
When this "freeze" occurs, is response just slow or is there no response at all? What happens if you press, say, NVDA+f12 to report the time while this unresponsiveness is occurring?

I think a log file would be helpful with log level set to input/output. See [this article](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) for instructions.

**Comment by pranavlal** [comment]
When the freeze occurs, other functions of NVDA work without a problem so I can see the time and invoke the systray list add-on. The arrow keys stop responding in the message summary. I’ll send you a log in my next update.

**Comment by pranavlal** [comment]
[nvdaOutlookFreezeLog.txt](https://github.com/nvaccess/nvda/files/128321/nvdaOutlookFreezeLog.txt)
I have attached a large log file. The freeze occurs towards the end. It is hard to duplicate so I set the log level to info and tried my best to get NVDA to freeze.

**Comment by fernando-jose-silva** [comment]
Good afternoon dear, I just want to inform you that I have this same problem in Outlook 2016 windows 10 and NVDA master 13227.
 As this error occurs intermittently, I will strive to get a log and shipping as well to try to help.

**Comment by jcsteh** [comment]
If reporting the time, etc. still works, this isn't actually a freeze, as this indicates that NVDA is still running normally. I'm rather concerned that Outlook stops firing events for some reason. What do you get when you press NVDA+tab when this occurs?

**Comment by pranavlal** [comment]
Hi,

 

When I press nvda + tab, I am told

List item readonly not selected

 

I also checked the log just after NVDA got stuck in the message summaries. There is an error whose text I am pasting below. I cannot tell if it is relevant.

INFO - __main__ (17:17:27):

Starting NVDA

INFO - core.main (17:17:27):

Config dir: C:\Users\user\AppData\Roaming\nvda

INFO - core.main (17:17:28):

NVDA version 2015.4

INFO - core.main (17:17:28):

Using Windows version 10.0.10586 workstation

INFO - core.main (17:17:28):

Using Python version 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]

INFO - core.main (17:17:28):

Using comtypes version 0.6.2

INFO - external:synthDrivers.eloquence.SynthDriver.__init__ (17:17:30):

Using Eloquence version 6.1.0.0

INFO - synthDriverHandler.setSynth (17:17:30):

Loaded synthDriver eloquence

INFO - core.main (17:17:30):

Using wx version 3.0.2.0 msw (classic)

INFO - braille.initialize (17:17:30):

Using liblouis version 2.6.4

INFO - external:brailleDisplayDrivers.SeikaMini (17:17:30):

LoadLibrary SeikaDevice.dll CWD: C:\Program Files (x86)\NVDA

INFO - external:brailleDisplayDrivers.SeikaMini.BrailleDisplayDriver.__init__ (17:17:30):

SeikaMini an USB-HID, Cells 16 Buttons 22

INFO - braille.BrailleHandler.setDisplayByName (17:17:30):

Loaded braille display driver SeikaMini, current display has 16 cells.

INFO - brailleInput.initialize (17:17:30):

Braille input initialized

INFO - core.main (17:17:32):

NVDA initialized

ERROR - RPC process 6452 (nvda_slave.exe) (17:17:51):

__main__.main:

slave error

Traceback (most recent call last):

  File "nvda_slave.pyw", line 90, in main

  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject

  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject

  File "comtypes\__init__.pyo", line 1165, in GetActiveObject

  File "_ctypes/callproc.c", line 945, in GetResult

WindowsError: [Error -2147221021] Operation unavailable

ERROR - scriptHandler.executeScript (17:25:18):

error executing script: <bound method Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject.script_toggleAlignment of <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x053F4610>> with gesture u'ctrl+r'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "NVDAObjects\window\winword.pyo", line 1176, in script_toggleAlignment

  File "NVDAObjects\window\winword.pyo", line 1144, in _WaitForValueChangeForAction

  File "NVDAObjects\window\winword.pyo", line 1176, in <lambda>

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

ERROR - eventHandler.executeEvent (17:32:47):

error executing event: caret on <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x053F21B0> with extra args of {}

Traceback (most recent call last):

  File "eventHandler.pyo", line 143, in executeEvent

  File "eventHandler.pyo", line 91, in __init__

  File "eventHandler.pyo", line 98, in next

  File "NVDAObjects\IAccessible\__init__.pyo", line 1280, in event_caret

  File "NVDAObjects\window\winword.pyo", line 907, in event_caret

  File "NVDAObjects\__init__.pyo", line 926, in makeTextInfo

  File "NVDAObjects\window\winword.pyo", line 457, in __init__

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

ERROR - scriptHandler.executeScript (17:34:39):

error executing script: <bound method Gecko_ia2.script_activatePosition of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x055333D0>> with gesture u'enter'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "browseMode.pyo", line 303, in script_activatePosition

  File "browseMode.pyo", line 1011, in _activatePosition

  File "treeInterceptorHandler.pyo", line 118, in _set_passThrough

  File "review.pyo", line 117, in setCurrentMode

  File "review.pyo", line 25, in getObjectPosition

  File "NVDAObjects\__init__.pyo", line 926, in makeTextInfo

  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 81, in __init__

  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 155, in _findContentDescendant

COMError: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))

ERROR - scriptHandler.executeScript (17:41:38):

error executing script: <bound method Gecko_ia2.script_activatePosition of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05533A10>> with gesture u'enter'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "browseMode.pyo", line 303, in script_activatePosition

  File "browseMode.pyo", line 1011, in _activatePosition

  File "treeInterceptorHandler.pyo", line 118, in _set_passThrough

  File "review.pyo", line 117, in setCurrentMode

  File "review.pyo", line 25, in getObjectPosition

  File "NVDAObjects\__init__.pyo", line 926, in makeTextInfo

  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 81, in __init__

  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 155, in _findContentDescendant

COMError: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))

ERROR - scriptHandler.executeScript (18:00:28):

error executing script: <bound method Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject.script_toggleAlignment of <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x054B3B30>> with gesture u'ctrl+r'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "NVDAObjects\window\winword.pyo", line 1176, in script_toggleAlignment

  File "NVDAObjects\window\winword.pyo", line 1141, in _WaitForValueChangeForAction

  File "NVDAObjects\window\winword.pyo", line 1176, in <lambda>

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

ERROR - scriptHandler.executeScript (18:02:08):

error executing script: <bound method Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject.script_toggleAlignment of <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x054B3570>> with gesture u'ctrl+r'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "NVDAObjects\window\winword.pyo", line 1176, in script_toggleAlignment

  File "NVDAObjects\window\winword.pyo", line 1141, in _WaitForValueChangeForAction

  File "NVDAObjects\window\winword.pyo", line 1176, in <lambda>

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

INFO - updateCheck.AutoUpdateChecker._started (19:35:56):

Performing automatic update check

ERROR - RPC process 14960 (nvda_slave.exe) (19:40:23):

__main__.main:

slave error

Traceback (most recent call last):

  File "nvda_slave.pyw", line 90, in main

  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject

  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject

  File "comtypes\__init__.pyo", line 1165, in GetActiveObject

  File "_ctypes/callproc.c", line 945, in GetResult

WindowsError: [Error -2147221021] Operation unavailable

ERROR - scriptHandler.executeScript (19:41:00):

error executing script: <bound method Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject.script_toggleAlignment of <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x056AD390>> with gesture u'ctrl+r'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "NVDAObjects\window\winword.pyo", line 1176, in script_toggleAlignment

  File "NVDAObjects\window\winword.pyo", line 1141, in _WaitForValueChangeForAction

  File "NVDAObjects\window\winword.pyo", line 1176, in <lambda>

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

ERROR - scriptHandler.executeScript (04:29:45):

error executing script: <bound method Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject.script_toggleAlignment of <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x0559FE10>> with gesture u'ctrl+r'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "NVDAObjects\window\winword.pyo", line 1176, in script_toggleAlignment

  File "NVDAObjects\window\winword.pyo", line 1141, in _WaitForValueChangeForAction

  File "NVDAObjects\window\winword.pyo", line 1176, in <lambda>

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

ERROR - scriptHandler.executeScript (04:36:50):

error executing script: <bound method Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject.script_toggleAlignment of <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x054AB650>> with gesture u'ctrl+r'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "NVDAObjects\window\winword.pyo", line 1176, in script_toggleAlignment

  File "NVDAObjects\window\winword.pyo", line 1141, in _WaitForValueChangeForAction

  File "NVDAObjects\window\winword.pyo", line 1176, in <lambda>

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

ERROR - scriptHandler.executeScript (04:50:46):

error executing script: <bound method Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject.script_toggleAlignment of <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x0549D0B0>> with gesture u'ctrl+r'

Traceback (most recent call last):

  File "scriptHandler.pyo", line 186, in executeScript

  File "NVDAObjects\window\winword.pyo", line 1176, in script_toggleAlignment

  File "NVDAObjects\window\winword.pyo", line 1141, in _WaitForValueChangeForAction

  File "NVDAObjects\window\winword.pyo", line 1176, in <lambda>

  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__

  File "comtypes\client\lazybind.pyo", line 149, in __getattr__

  File "comtypes\automation.pyo", line 664, in _invoke

COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (04:58:05):

Developer info for navigator object:

name: ''

role: ROLE_LISTITEM

states: STATE_FOCUSABLE, STATE_SELECTABLE, STATE_READONLY

isFocusable: True

hasFocus: 0

Python object: <appModules.outlook.UIAGridRow object at 0x053A0E10>

Python class mro: (<class 'appModules.outlook.UIAGridRow'>, <class 'NVDAObjects.behaviors.RowWithFakeNavigation'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)

description: u''

location: (0, 0, 0, 0)

value: None

appModule: <'outlook' (appName u'outlook', process ID 25440) at address 538f5f0>

appModule.productName: u'Microsoft Outlook'

appModule.productVersion: u'16.0.6366.2062'

TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>

windowHandle: 656700

windowClassName: u'OutlookGrid'

windowControlID: 4704

windowStyle: 1442840576

windowThreadID: 25112

windowText: u'Table View'

displayText: u''

UIAElement: <POINTER(IUIAutomationElement) ptr=0x65c0f98 at 53a3b20>

UIA automationID: 

UIA frameworkID: 

UIA runtimeID: (42, 656700, 2, -714)

UIA providerDescription: [pid:25440,hwnd:0x0 Main(parent link):Unidentified Provider (unmanaged:OUTLOOK.EXE)]

UIA className: LeafRow

**Comment by fernando-jose-silva** [comment]
Good afternoon dears.
 I do not know if it helps the log attached because it is in Portuguese, I separated the log excerpt where NVDA froze to read the messages in the inbox.
 Thank you.
[outlook.txt](https://github.com/nvaccess/nvda/files/131490/outlook.txt)

**Comment by pranavlal** [comment]
The problem persists in the 2016 rc1 version.

**Comment by jcsteh** [comment]
I took a look at this log. NVDA definitely isn't freezing when it makes requests. That suggests Outlook either stops firing events, fires invalid events for some reason or fires events in such a way that NVDA filters them out.

Are you able to check whether this happens with Narrator? I normally don't recommend running NVDA and Narrator together, but it should be okay briefly. When NVDA stops reporting messages, see if Narrator does as well. That will give us some idea of whether there is some utlook UIA brokenness at play here.

**Comment by fernando-jose-silva** [comment]
good day, in my case the narrator also went unanswered, being necessary to return to alt + Tabn for the e-mail list is read again.

**Comment by pranavlal** [comment]
I did some tests and the arrow keys are being executed but NVDA is not speaking when I press them.

**Comment by pranavlal** [comment]
I tested this with narrator. I launched narrator when the problem occurred. I reached the message summaries and tried using the up and down arrow keys. Narrator did not give me any feedback. NVDA is not freezing. I can tab through the outlook interface. NVDA does not respond in the  section of the window that contains the message summaries. By does not respond, I mean that hitting the up or down arrow doews not do anything and does not yield any speech output. I have a feeling that the arrow keys do get executed but I do not get any speech feedback.

**Comment by jcsteh** [comment]
If Narrator isn't giving feedback either, Outlook is simply not 
bothering to notify us about the focus moving. That probably means we'll 
need to get Microsoft to fix this.

**Comment by pranavlal** [comment]
ok. Where do we go from here? Is there any more data I can send?

**Comment by ehollig** [comment]
@jcsteh, from https://github.com/nvaccess/nvda/issues/5745#issuecomment-185493089 it sounds like this needs an external fix and is not an NVDA issue. @pranavlal, is this still occurring for you?

**Comment by Qchristensen** [comment]
Is anyone still having this issue?  I've had correspondence from someone with similar sounding symptoms moving around the options in Outlook's settings, and similar looking error in the log:

NVDA version 2018.3.2

INFO - core.main (09:31:58.457):

Using Windows version 10.0.17134 workstation

... (Snipped for brevity, standard NVDA startup at log level info) ...

NVDA initialized

ERROR - RPC process 5572 (nvda_slave.exe) (09:32:25.773):

__main__.main:

slave error

Traceback (most recent call last):

  File "nvda_slave.pyw", line 94, in main

  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject

  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject

  File "comtypes\__init__.pyo", line 1247, in GetActiveObject

  File "_ctypes/callproc.c", line 950, in GetResult

WindowsError: [Error -2147221021] Operation unavailable

**Comment by pranavlal** [comment]
I am no longer having this problem.

-----Original Message-----

**Comment by ehollig** [comment]
Thank you @pranavlal. Closing as worksforme
