### ISSUE TITLE
Odd page headers and footers announced as "primary" page header / footer in Word

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#5990]
In Word (2016 at least), setting up headers and footers and checking the "different odd and even pages" checkbox, the even page header and footers are announced as "Even page header" and "even page footer" however the odd pages are announced as "Primary page header" and "Primary page footer".  This is the same whether or not "Different first page" is set (with that set, the first page is identified as "first page header" and "first page footer" when editing.

I've attached a dummy document with different first page, odd and even headers to demonstrate.

[headers and footers.docx](https://github.com/nvaccess/nvda/files/278611/headers.and.footers.docx)

**Comment by leonardder** [comment]
@Qchristensen: Should we consider a p3 for this? Probably depends on how disrupting this issue is.

**Comment by Qchristensen** [comment]
P3 is fine.  It's not overly disruption.  It's easy enough to ascertain which is the header for odd pages and which the header for even pages.  The information is there, it's just not announced as one might at first expect.

**Comment by bhavyashah** [comment]
@leonard (or others with requisite triaging privileges) Please add the P3 label as agreed upon by @leonardder and @Qchristensen in previous comments.

**Comment by Adriani90** [comment]
In mS Office 365 version 2505 with NVDA 2025.1.2 RC, these are not identified at all.

When navigating through header and footer with arrow keys, I get very often following errors:

```
ERROR - scriptHandler.executeScript (14:08:08.314) - MainThread (21012):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_WordDocumentNodeEditableTextWithAutoSelectDetectionUIA object at 0x05610BD0>> with gesture 'Pfeiltaste nach oben'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "editableText.pyc", line 268, in script_caret_moveByLine
  File "editableText.pyc", line 192, in _caretMovementScriptHelper
  File "NVDAObjects\behaviors.pyc", line 254, in _caretScriptPostMovedHelper
  File "editableText.pyc", line 178, in _caretScriptPostMovedHelper
  File "speech\speech.pyc", line 1483, in speakTextInfo
  File "speech\types.pyc", line 47, in __iter__
  File "speech\speech.pyc", line 1524, in getTextInfoSpeech
  File "NVDAObjects\UIA\wordDocument.pyc", line 351, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 1034, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 1022, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 685, in _getTextWithFields_text
  File "UIAHandler\utils.pyc", line 135, in iterUIARangeByUnit
_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))
DEBUG - comtypes._post_coinit.unknwn.__del__ (14:08:08.322) - MainThread (21012):
Release <POINTER(IUIAutomationTextRange) ptr=0x627d490 at 1419620>
DEBUG - comtypes._post_coinit.unknwn.__del__ (14:08:08.322) - MainThread (21012):
Release <POINTER(IUIAutomationElement) ptr=0x627d370 at 5654710>
DEBUG - comtypes._post_coinit.unknwn.__del__ (14:08:08.322) - MainThread (21012):
Release <POINTER(IUIAutomationTextRange) ptr=0x627cf80 at 557d3a0>
DEBUG - comtypes._post_coinit.unknwn.__del__ (14:08:08.322) - MainThread (21012):
Release <POINTER(IUIAutomationTextRange) ptr=0x627d298 at 557dcb0>
DEBUG - comtypes._post_coinit.unknwn.__del__ (14:08:08.322) - MainThread (21012):
Release <POINTER(IUIAutomationTextRange) ptr=0x627d400 at 5654620>
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
Hook received winEvent: EVENT_OBJECT_LOCATIONCHANGE, window 4784250 (_WwG), objectID OBJID_CARET, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
Adding winEvent to limiter: EVENT_OBJECT_LOCATIONCHANGE, window 4784250 (_WwG), objectID OBJID_CARET, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
Hook received winEvent: EVENT_OBJECT_FOCUS, window 4784250 (_WwG), objectID 361, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
Adding winEvent to limiter: EVENT_OBJECT_FOCUS, window 4784250 (_WwG), objectID 361, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
Hook received winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 4784250 (_WwG), objectID 362, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
Adding winEvent to limiter: IA2_EVENT_TEXT_CARET_MOVED, window 4784250 (_WwG), objectID 362, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
Hook received winEvent: EVENT_OBJECT_LOCATIONCHANGE, window 131294 (CursorVisualClass), objectID OBJID_WINDOW, childID 0, process 5008 (eoaexperiences), thread 5884
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (14:08:08.322) - MainThread (21012):
locationChange for something other than the caret. Dropping winEvent EVENT_OBJECT_LOCATIONCHANGE, window 131294 (CursorVisualClass), objectID OBJID_WINDOW, childID 0, process 5008 (eoaexperiences), thread 5884
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (14:08:08.322) - MainThread (21012):
Emitting winEvent EVENT_OBJECT_LOCATIONCHANGE, window 4784250 (_WwG), objectID OBJID_CARET, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (14:08:08.322) - MainThread (21012):
Emitting winEvent EVENT_OBJECT_FOCUS, window 4784250 (_WwG), objectID 361, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.orderedWinEventLimiter.OrderedWinEventLimiter.flushEvents (14:08:08.322) - MainThread (21012):
Emitting winEvent IA2_EVENT_TEXT_CARET_MOVED, window 4784250 (_WwG), objectID 362, childID 0, process 7668 (winword), thread 5656
DEBUG - IAccessibleHandler.processGenericWinEvent (14:08:08.322) - MainThread (21012):
Processing generic winEvent: EVENT_OBJECT_LOCATIONCHANGE, window 4784250 (_WwG), objectID OBJID_CARET, childID 0, process 7668 (winword)
DEBUG - IAccessibleHandler.processGenericWinEvent (14:08:08.322) - MainThread (21012):
handling winEvent as caret event on focus. winEvent window 4784250 (_WwG), objectID OBJID_CARET, childID 0, process 7668 (winword)
DEBUG - IAccessibleHandler.processFocusWinEvent (14:08:08.322) - MainThread (21012):
Processing focus winEvent: window 4784250 (_WwG), objectID 361, childID 0, process 7668 (winword), force False
DEBUG - IAccessibleHandler.winEventToNVDAEvent (14:08:08.322) - MainThread (21012):
Creating NVDA event from winEvent: EVENT_OBJECT_FOCUS, window 4784250 (_WwG), objectID 361, childID 0, process 7668 (winword), use cache False
DEBUG - IAccessibleHandler.winEventToNVDAEvent (14:08:08.322) - MainThread (21012):
winEvent mapped to NVDA event: gainFocus
DEBUG - UIAHandler.UIAHandler.isUIAWindow (14:08:08.322) - MainThread (21012):
Found cached is UIA window False for hwnd hwnd 0X49007A of class _WwG
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:08:08.330) - MainThread (21012):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 4784250 (_WwG), objectID 361, childID 0, process 7668 (winword)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (14:08:08.330) - MainThread (21012):
Could not instantiate an NVDAObject for winEvent: EVENT_OBJECT_FOCUS, window 4784250 (_WwG), objectID 361, childID 0, process 7668 (winword)
DEBUG - IAccessibleHandler.processGenericWinEvent (14:08:08.330) - MainThread (21012):
Processing generic winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 4784250 (_WwG), objectID 362, childID 0, process 7668 (winword)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (14:08:08.330) - MainThread (21012):
Creating NVDA event from winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 4784250 (_WwG), objectID 362, childID 0, process 7668 (winword), use cache True
DEBUG - IAccessibleHandler.winEventToNVDAEvent (14:08:08.330) - MainThread (21012):
winEvent mapped to NVDA event: caret
DEBUG - UIAHandler.UIAHandler.isUIAWindow (14:08:08.330) - MainThread (21012):
Found cached is UIA window False for hwnd hwnd 0X49007A of class _WwG
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (14:08:08.330) - MainThread (21012):
oleacc.AccessibleObjectFromEvent failed with [WinError -2147467259] Unbekannter Fehler. WinEvent: window 4784250 (_WwG), objectID 362, childID 0, process 7668 (winword)
DEBUG - IAccessibleHandler.winEventToNVDAEvent (14:08:08.330) - MainThread (21012):
Could not instantiate an NVDAObject for winEvent: IA2_EVENT_TEXT_CARET_MOVED, window 4784250 (_WwG), objectID 362, childID 0, process 7668 (winword)
```

cc: @michaelDCurran
