### ISSUE TITLE
"Enter formatting for number" label doesn't read in "define new multilevel list" in Word 2016

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6005]
In word 2016 at least, press alt+h the m to open the multi-level list options and press d to define new multi-level list.

Most of this dialog reads fine except the field after "click level to modify" which doesn't read anything when you get to it.  The label visually reads "Enter formatting for number:" with the "o" in formatting underlined.  The field itself is an edit field with, by default "1)" written in it (as the first number style.  You can arrow around this field and add your own extra text in (eg if you want numbers to always by "Chapter 1)" for instance).  The behaviour all works fine, just identifying the field as you get to it.

**Comment by michaelDCurran** [comment]
This is broken in Word 2016, but not in Word 2013.
Technical:
That particular MSAA object is not exposing the IAccessible focused state. The winEvent is being fired correctly.

**Comment by michaelDCurran** [comment]
Switching to p2 as This is a rather advanced usage of MS Word

**Comment by Adriani90** [comment]
Testing with NVDA alpha-16813,a0b991af

1. In Word 2010 I get following error when navigating to the field:
```
Input: kb(laptop):shift+tab
ERROR - baseObject.ScriptableObject.bindGestures (18:48:07.891):
Error binding script caret_changeSelection in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x051DEAB0>
ERROR - baseObject.ScriptableObject.bindGestures (18:48:07.928):
Error binding script caret_changeSelection in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x051DEAB0>
ERROR - baseObject.ScriptableObject.bindGestures (18:48:07.993):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x051DEAB0>
ERROR - baseObject.ScriptableObject.bindGestures (18:48:08.029):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x051DEAB0>
ERROR - baseObject.ScriptableObject.bindGestures (18:48:08.066):
Error binding script caret_changeSelection in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x051DEAB0>
ERROR - baseObject.ScriptableObject.bindGestures (18:48:08.108):
Error binding script caret_changeSelection in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x051DEAB0>
IO - inputCore.logTimeSinceInput (18:48:08.301):
0.471 sec since input
IO - speech.speak (18:48:08.301):
Speaking [u'Enter formatting for number:  Eingabefeld  *)']
```

and I cannot move with arrow keys through the field.


2. In Word 2016 / 365 with UIA enabled or disabled, the field is not recognized and while navigating with tab and shift + tab over the area where the field should be reported, I get following errors:
```
IO - inputCore.InputManager.executeGesture (18:53:22.344):
Input: kb(laptop):shift+tab
DEBUGWARNING - NVDAObjects.window.winword.WordDocument._get_WinwordWindowObject (18:53:22.433):
Could not get MS Word object model from window 919068 with class _WwN
Traceback (most recent call last):
  File "NVDAObjects\window\winword.pyc", line 1193, in _get_WinwordWindowObject
  File "oleacc.pyc", line 237, in AccessibleObjectFromWindow
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147467259] Unbekannter Fehler
ERROR - scriptHandler.executeScript (18:53:22.443):
error executing script: <bound method Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject.script_tab of <NVDAObjects.Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x05016610>> with gesture u'Umschalt+Tab'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "NVDAObjects\window\winword.pyc", line 1371, in script_tab
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 285, in __init__
NotImplementedError: UIAutomationTextRangeArray is empty
IO - inputCore.logTimeSinceInput (18:53:22.575):
0.231 sec since input
IO - speech.speak (18:53:22.575):
Speaking [u'Klicken Sie auf die Ebene, um sie zu \xe4ndern:  Liste']
```

I think something is really broken in this dialog which should be solved by Microsoft. It is similar to behaviors in edit fields in MS Excel I think.
cc: @lukaszgo1, @leonardder

**Comment by Qchristensen** [comment]
Microsoft might have changed this, but in Ofice 365 now, pressing ALT+H, M, D goes into define new multi-level list as desired, but the default list type is "Bullet, solid circle", and evidently with this type of bullet, you can't adjust the formatting using the edit box this issue is about.  If you press ALT+N to go to "Number style for this level" and press HOME to go to "None", the edit box becomes useable.  Press ALT+O to jump to it, or TAB to it, and NVDA now reads "Document, Page 1" then any text in the field.  It's still not "Enter formatting for number" which is what should be read, but at least it's not silent.

I noticed the same behaviour with or without UIA set in NVDA 2019.1.1  Using Office 365 version 16.0.11601.20174

**Comment by ivnc** [comment]
Are there any updates on this? A Spanish-speaking user has just complained about this or similar issues with that edit box, both in Word 2016 and 2010.
I have the full log if needed. The output is almost the same for both 2016 and 2010. I've reproduced it in Word for Office 365 build 13530.20316 and I couldn't even read the default format.
IO - speech.speak (17:57:04.213) - MainThread (11212):
Speaking [LangChangeCommand ('es_ES'), '1']
IO - inputCore.InputManager.executeGesture (17:57:05.594) - winInputHook (6472):
Input: kb(desktop):tab
ERROR - baseObject.ScriptableObject.bindGestures (17:57:05.663) - MainThread (11212):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x08A407B0>
ERROR - baseObject.ScriptableObject.bindGestures (17:57:05.663) - MainThread (11212):
Error binding script caret_moveByLine in <NVDAObjects.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x08A407B0>
IO - speech.speak (17:57:05.692) - MainThread (11212):
Speaking [LangChangeCommand ('es_ES'), 'Especifique formato para el número:', 'edición', '*)', 'Alt+o'] #Specify format for the number
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (17:57:05.693) - MainThread (11212):
Unsupported speech command: LangChangeCommand ('es_ES')
IO - inputCore.InputManager.executeGesture (17:57:09.864) - winInputHook (6472):
Input: kb(desktop):leftArrow
IO - inputCore.InputManager.executeGesture (17:57:10.822) - winInputHook (6472):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (17:57:11.705) - winInputHook (6472):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (17:57:12.544) - winInputHook (6472):
Input: kb(desktop):rightArrow
IO - inputCore.InputManager.executeGesture (17:57:17.004) - winInputHook (6472):
Input: kb(desktop):escape

Regards.

**Comment by Adriani90** [comment]
Yeah this dialog is quite buggy, actually it seems on some controls Microsoft uses contentEditable and it feels like some controls are a mix of plain text and edit field. So the object, when reviewing with NVDA review cursor, is half plain text or grafics and half edit field + content.

cc: @msftedad can you please open a ticket with your development team? Thanks.

**Comment by Adriani90** [comment]
I used NVDA 2025.1.2 rC and MS Office 365 version 2505 to test, and this is still reproducible.
