### ISSUE TITLE
MS-word will be crashed with this document when NVDA is running.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#6023]
Hi:
system version: windows 10 10586.318 x64
NVDA version: next-13343,73ee6b2a
Office version: office2016 professional plus
Except for the error at the title, I also catch the error log:
ERROR - scriptHandler.executeScript (10:42:16):
error executing script: <bound method Dynamic_IAccessibleWordDocumentWindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleWordDocumentWindowNVDAObject object at 0x052596D0>> with gesture u'\u4e0b\u5149\u6807'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "C:\Users\vgjh2005\AppData\Roaming\nvda\addons\TextHelper\globalPlugins\TextHelper\__init__.py", line 53, in mySpeakInfo
  File "speech.pyc", line 675, in speakTextInfo
  File "NVDAObjects\window\winword.pyc", line 570, in getTextWithFields
  File "NVDAObjects\window\winword.pyc", line 699, in _normalizeFormatField
  File "NVDAObjects\window\winword.pyc", line 1017, in winwordColorToNVDAColor
ValueError: Unknown color format 0 0 0 0
The document will be uploaded later.
Thanks!

**Comment by vgjh2005** [comment]
Please change the extention name from docx to doc.Thanks!
[document.docx](https://github.com/nvaccess/nvda/files/290272/document.docx)

**Comment by michaelDCurran** [comment]
@qchristensen: Does the text in this document show up visually as black? Also, by going to the font dialog and choosing the color,  Can you tell where the author got black from? I.e. was it one of the theme colors? For some reason this black is a very strange value that I can't reproduce in other documents.

**Comment by Qchristensen** [comment]
Visually, the text appears black and going into font colour / more colours gives an RGB value of 0,0,0, it isn't being highlighted as one of the colours in the default palette, though Word doesn't highlight when "automatic" is being used either.

**Comment by michaelDCurran** [comment]
This exception has been fixed in #5997 and will be available in the next Next snapshot. However, I do not see any actual crash. If you meant there was only an exception, then  I will close this issue as fixed.

**Comment by vgjh2005** [comment]
Hi Mic：
This issue has been fixed. Thanks a lot!
