### ISSUE TITLE
Inconsistent NVDA behavior with SVG images and various browsers

### ISSUE THREAD

**Issue by tgeczy** [nvaccess/nvda#6103]

**Comment by ehollig** [comment]
@tgeczy, have you noticed any changes in the way that browsers handle SVG's since filing this issue?

**Comment by Adriani90** [comment]
@tgeczy are you still on Github and available to test? Is this issue still reproducible?

**Comment by tgeczy** [comment]
@ehollig and @Adriani90 - it's definitely not as severe of an issue now, but I'm noticing on this page that with Edge you can only read aria-describedby tags if you focus the image with the G key. Object nav in FireFox will still let you enter an SVG with object nav and see empty graphics; But this is not high impact to users. The main thing with Edge reporting multiple SVG paths is at least solved.
 https://weboverhauls.github.io/demos/svg/

**Comment by Adriani90** [comment]
@jcsteh how do you see the impact of this issue in Firefox at least? At least for me, I am dealing often with diagrams in .svg format on financial websites. As of now we are still using IE at work but soon we will be changing to Firefox.

**Comment by Adriani90** [comment]
If you look at the first two svg images (rectangle grafic) they contain the description "rectangle a grid of 3x3 = 9 rectangles". This information is very important for many grafics, i.e. diagrams. In firefox, you get the description only when you use g in browse mode or when you use object navigation. I would prefer to get this information also when navigating by arrow keys in browse mode but I think the priority for this will not be very high due to possible workarounds.

**Comment by Adriani90** [comment]
When using IE, the description of the rectangle svg is being reported also while using arrow keys to navigate. But on the second and third svg image in IE I get following error in the log file:

```
IO - inputCore.InputManager.executeGesture (22:20:16.576):
Input: kb(laptop):downArrow
ERROR - scriptHandler.executeScript (22:20:16.710):
error executing script: <bound method MSHTML.script_moveByLine_forward of <virtualBuffers.MSHTML.MSHTML object at 0x05262C90>> with gesture u'Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 213, in script_moveByLine_forward
  File "cursorManager.pyc", line 143, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1239, in _set_selection
  File "browseMode.pyc", line 1254, in _shouldSetFocusToObj
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 944, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 226, in __call__
  File "comtypes\automation.pyc", line 729, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))
```
