### ISSUE TITLE
An error is appeared when installing Emodicon addon.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#6130]
Hi:
I find many addons that cannot be installed. Now I test with Emodicon:http://addons.nvda-project.org/files/get.php?file=emo
Error log is below:
ERROR - gui.addonGui.AddonsDialog.installAddon (16:41:43):
Error opening addon bundle from D:\软件\软件\NVDA插件\emoticons v4.5.nvda-addon
Traceback (most recent call last):
  File "gui\addonGui.pyc", line 106, in installAddon
  File "addonHandler.pyc", line 411, in __init__
  File "addonHandler.pyc", line 507, in __init__
  File "configobj.pyc", line 1219, in __init__
  File "configobj.pyc", line 1302, in _load
ConfigObjError: Parsing failed with several errors.
First error at line 1.

**Comment by jcsteh** [comment]
This is due to a problem in the manifest translation. You've translated the summary as two lines (including a line break), but it must only be one. Generally, your translation should have the same number of lines as the original.
