### ISSUE TITLE
Setting up smart art in Word

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6142]
When creating a "Smart art" diagram in Word (Press alt+n then m), after choosing the type of diagram you wish to create, it is inserted in the document and the focus is on a non-standard appearing dialog labelled "Type your text here".  This dialog has a number of bullet points - equal to the default number of items in the object - 5 for a basic block list, 3 for a basic process etc.

These are not always read out, sometimes when the focus is at the end of an item, when you press NVDA+up arrow, it reads the next item.

For many diagram types you need to press TAB to indent items - this makes them sub-items of the previous item.  The indent is not read out, even with report line / paragraph indentation checked in NVDA document settings.

Also, when you finish your diagram, if you come back and select it later, this "type your text here" dialog appears again, however there does not seem to be a way to move the focus to it (without clicking with the mouse).

**Comment by Adriani90** [comment]
While navigating through the smarart diagram, I get following error in the log:
```
IO - inputCore.InputManager.executeGesture (20:00:50.193) - winInputHook (8476):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (20:00:50.234) - MainThread (8360):
Caret move detected using event. Elapsed: 0 ms
ERROR - scriptHandler.executeScript (20:00:50.287) - MainThread (8360):
error executing script: <bound method EditableText.script_caret_moveByCharacter of <NVDAObjects.Dynamic_ListItemEditableTextWithAutoSelectDetectionUIA object at 0x00BD0410>> with gesture 'Pfeiltaste nach rechts'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "editableText.pyc", line 223, in script_caret_moveByCharacter
  File "editableText.pyc", line 164, in _caretMovementScriptHelper
  File "NVDAObjects\behaviors.pyc", line 175, in _caretScriptPostMovedHelper
  File "editableText.pyc", line 150, in _caretScriptPostMovedHelper
  File "speech\__init__.pyc", line 1076, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\__init__.pyc", line 1116, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 704, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 489, in _getTextWithFields_text
  File "NVDAObjects\UIA\__init__.pyc", line 455, in _getTextFromUIARange
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))
```
