### ISSUE TITLE
Latest nexxt snapshot generates an error when opening Windows 7's start menu.

### ISSUE THREAD

**Issue by kara-louise** [nvaccess/nvda#6411]
I am running next-13611,dcb35858.
On opening the start menu, an error message is generated in the log.
Note that I have edited the lines which point to my user folder. Also, I have tried disabling the addons mentioned, but the same occurs minus the addons.
The error message is below.
Note that I have edited the lines which point to my user folder. Also, I have tried disabling the addons mentioned, but the same occurs minus the addons.

ERROR - eventHandler.executeEvent (23:03:08):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x08CEB250> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\MyUsername\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 341, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\MyUsername\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 416, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "appModules\explorer.pyc", line 263, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 892, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 804, in reportFocus
  File "speech.pyc", line 369, in speakObject
  File "speech.pyc", line 691, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 428, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 312, in _getTextWithFieldsForUIARange
COMError: (-2147467263, 'Not implemented', (None, None, None, 0, None))
I'll provide more info if necessary.

**Comment by josephsl** [comment]
CC @MichaelDCurran – is this a regression introduced with #6271 incubation? Thanks.

**Comment by jcsteh** [comment]
Thanks for reporting.

Yes, this is related to #6271.

Technical: It seems GetenclosingElement isn't implemented for this control. There's nothing we can do about this; we just need to catch it and move on (probably logging a debugWarning). However, I'm not sure what to set if this occurs. I'll leave that to @MichaelDCurran. :)

**Comment by michaelDCurran** [comment]
6afc061 was merged into next.

**Comment by Brian1Gaff** [comment]
Yes the latest snap has cured this. I noticed somebody beat me to this 
creating a ticket.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
Oops!
 Its also very broken in windows xp when you install or update it.

INFO - __main__ (18:02:08):
Starting NVDA
INFO - core.main (18:02:16):
Config dir: C:\Documents and Settings\brian\Application Data\nvda
DEBUG - core.main (18:02:16):
setting language to Windows
INFO - core.main (18:02:16):
NVDA version next-13611,dcb35858
INFO - core.main (18:02:16):
Using Windows version 5.1.2600 service pack 3 workstation
INFO - core.main (18:02:16):
Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
INFO - core.main (18:02:16):
Using comtypes version 0.6.2
DEBUG - core.main (18:02:17):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Listing add-ons from C:\Documents and Settings\brian\Application Data\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\extendedWinamp
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Found add-on extendedWinamp
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\fakeClipboardAnouncement
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Found add-on fakeClipboardAnouncement
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\goldwave
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Found add-on goldwave
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Found add-on resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\Speech Hub
DEBUG - addonHandler._getAvailableAddonsFromPath (18:02:17):
Found add-on Speech Hub
DEBUG - core.main (18:02:18):
Initializing appModule Handler
DEBUG - addonHandler.Addon.addToPackagePath (18:02:18):
Addon extendedWinamp added to appModules package path
DEBUG - addonHandler.Addon.addToPackagePath (18:02:18):
Addon goldwave added to appModules package path
DEBUG - core.main (18:02:18):
Initializing NVDAHelper
DEBUG - core.main (18:02:18):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (18:02:18):
Loading speech dictionary 'C:\Documents and Settings\brian\Application Data\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (18:02:18):
16 loaded records.
DEBUG - speechDictHandler.SpeechDict.load (18:02:18):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (18:02:18):
3 loaded records.
DEBUG - core.main (18:02:18):
Initializing speech
DEBUG - addonHandler.Addon.addToPackagePath (18:02:18):
Addon Speech Hub added to synthDrivers package path
INFO - synthDrivers.espeak.SynthDriver.__init__ (18:02:18):
Using eSpeak version 1.48.15  16.Apr.15
DEBUG - speechDictHandler.SpeechDict.load (18:02:19):
Loading speech dictionary 'C:\Documents and Settings\brian\Application Data\nvda\speechDicts\espeak-english.dic'...
DEBUG - speechDictHandler.SpeechDict.load (18:02:19):
2 loaded records.
INFO - synthDriverHandler.setSynth (18:02:19):
Loaded synthDriver espeak
DEBUGWARNING - core.main (18:02:19):
Slow starting core (11.95 sec)
IO - speech.speak (18:02:19):
Speaking [LangChangeCommand ('en_GB'), u'Loading NVDA. Please wait...']
INFO - core.main (18:02:19):
Using wx version 3.0.2.0 msw (classic)
DEBUGWARNING - RPC process 964 (nvda_snapshot_next-13611,dcb35858(1).exe) (18:02:19):
Thread 1556, build\x86\remote\ia2Support.cpp, IA2Support_inProcess_terminate, 194:
WaitForMultipleObjects returned 258

DEBUG - core.main (18:02:19):
Initializing braille
INFO - braille.initialize (18:02:19):
Using liblouis version 3.0.0
INFO - braille.BrailleHandler.setDisplayByName (18:02:19):
Loaded braille display driver noBraille, current display has 0 cells.
DEBUG - core.main (18:02:19):
Initializing braille input
INFO - brailleInput.initialize (18:02:19):
Braille input initialized
DEBUG - core.main (18:02:19):
Initializing displayModel
DEBUG - core.main (18:02:19):
Initializing GUI
DEBUG - core.main (18:02:19):
initializing Java Access Bridge support
DEBUG - core.main (18:02:19):
Initializing winConsole support
DEBUG - core.main (18:02:19):
Initializing UIA support
WARNING - core.main (18:02:19):
UIA not available
DEBUG - core.main (18:02:19):
Initializing IAccessible support
DEBUG - core.main (18:02:19):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (18:02:19):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (18:02:19):
No user gesture map
DEBUG - core.main (18:02:19):
Initializing keyboard handler
DEBUG - core.main (18:02:19):
initializing mouse handler
ERROR - mouseHandler.initialize (18:02:19):
Error retrieving initial mouse object
Traceback (most recent call last):
  File "mouseHandler.pyc", line 124, in initialize
  File "NVDAObjects\__init__.pyc", line 249, in objectFromPoint
  File "NVDAObjects\__init__.pyc", line 189, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 189, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
DEBUG - core.main (18:02:19):
Initializing touchHandler
DEBUGWARNING - touchHandler.initialize (18:02:19):
Touch only supported on installed copies
DEBUG - core.main (18:02:19):
Initializing global plugin handler
DEBUG - addonHandler.Addon.addToPackagePath (18:02:19):
Addon fakeClipboardAnouncement added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (18:02:19):
Addon resourceMonitor added to globalPlugins package path
DEBUG - core.main (18:02:19):
Initializing core pump
DEBUG - core.main (18:02:19):
Initializing watchdog
DEBUG - core.main (18:02:19):
initializing updateCheck
INFO - core.main (18:02:19):
NVDA initialized
DEBUG - core.main (18:02:19):
entering wx application main loop
ERROR - core.CorePump.Notify (18:02:19):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 355, in Notify
  File "IAccessibleHandler.pyc", line 888, in pumpAll
  File "IAccessibleHandler.pyc", line 621, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 533, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 59, in __call__
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
ERROR - appModuleHandler.fetchAppModule (18:02:19):
error in appModule 'explorer'
Traceback (most recent call last):
  File "appModuleHandler.pyc", line 168, in fetchAppModule
  File "appModules\explorer.pyc", line 18, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
IO - speech.speak (18:02:19):
Speaking [LangChangeCommand ('en_GB'), u'Error in appModule explorer']
ERROR - core.CorePump.Notify (18:02:19):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 355, in Notify
  File "IAccessibleHandler.pyc", line 888, in pumpAll
  File "IAccessibleHandler.pyc", line 621, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 533, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 59, in __call__
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
ERROR - core.CorePump.Notify (18:02:20):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 355, in Notify
  File "IAccessibleHandler.pyc", line 888, in pumpAll
  File "IAccessibleHandler.pyc", line 621, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 533, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 59, in __call__
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
IO - inputCore.InputManager.executeGesture (18:02:39):
Input: kb(desktop):tab
ERROR - core.CorePump.Notify (18:02:39):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 355, in Notify
  File "IAccessibleHandler.pyc", line 888, in pumpAll
  File "IAccessibleHandler.pyc", line 621, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 533, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 59, in __call__
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
IO - inputCore.InputManager.executeGesture (18:02:39):
Input: kb(desktop):tab
ERROR - core.CorePump.Notify (18:02:39):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 355, in Notify
  File "IAccessibleHandler.pyc", line 876, in pumpAll
  File "IAccessibleHandler.pyc", line 658, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 533, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 59, in __call__
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
IO - inputCore.InputManager.executeGesture (18:02:42):
Input: kb(desktop):tab
ERROR - core.CorePump.Notify (18:02:42):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 355, in Notify
  File "IAccessibleHandler.pyc", line 888, in pumpAll
  File "IAccessibleHandler.pyc", line 621, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 533, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 59, in __call__
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
ERROR - core._setInitialFocus (18:02:45):
Error retrieving initial focus
Traceback (most recent call last):
  File "core.pyc", line 142, in _setInitialFocus
  File "NVDAObjects\__init__.pyc", line 259, in objectWithFocus
  File "NVDAObjects\__init__.pyc", line 189, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 189, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\IAccessible\__init__.pyc", line 331, in getPossibleAPIClasses
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 29, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'TextUnit_Format'
IO - inputCore.InputManager.executeGesture (18:02:46):
Input: kb(desktop):control+alt+r
INFO - core.main (18:02:46):
Exiting
DEBUG - core._terminate (18:02:46):
Terminating updateCheck
DEBUG - core._terminate (18:02:46):
Terminating watchdog
DEBUG - core._terminate (18:02:46):
Terminating global plugin handler
DEBUG - core._terminate (18:02:46):
Terminating gui
INFO - config.ConfigManager.save (18:02:46):
Base configuration saved
DEBUG - core._terminate (18:02:46):
Terminating treeInterceptorHandler
DEBUG - core._terminate (18:02:46):
Terminating IAccessible support
DEBUG - core._terminate (18:02:46):
Terminating UIA support
DEBUG - core._terminate (18:02:46):
Terminating winConsole support
DEBUG - core._terminate (18:02:46):
Terminating Java Access Bridge support
DEBUG - core._terminate (18:02:46):
Terminating app module handler
DEBUG - core._terminate (18:02:46):
Terminating NVDAHelper
DEBUG - core._terminate (18:02:46):
Terminating touchHandler
DEBUG - core._terminate (18:02:46):
Terminating keyboard handler
DEBUG - core._terminate (18:02:46):
Terminating mouseHandler
DEBUG - core._terminate (18:02:46):
Terminating inputCore
DEBUG - core._terminate (18:02:46):
Terminating brailleInput
DEBUG - core._terminate (18:02:46):
Terminating braille
DEBUG - core._terminate (18:02:46):
Terminating speech
DEBUG - core._terminate (18:02:46):
Terminating addonHandler
DEBUG - core.main (18:02:47):
core done
INFO - __main__ (18:02:47):
NVDA exit
Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
  ----- Original Message -----
