### ISSUE TITLE
No formatting information in edit mode in Excel

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6479]
In any cell, with or without text in it, press F2 to go into edit mode, then press NVDA+f to read formatting information.  NVDA reads "No formatting information" instead of advising the current font, etc.

Tested in Excel 2016.

In Excel 2007, if the cell is blank, NVDA reads "No formatting information".
If the cell has text, and the focus is at the end of the text, NVDA reads "space" when NVDA+f is pressed.
If the cell has text, and the focus is anywhere else in the text, NVDA reads "space" and then the formatting information.

Possibly connected to #6478 ?

**Comment by feerrenrut** [comment]
I tested this in Excel 2013 and got the same behaviour.

**Comment by feerrenrut** [comment]
We are unable to get access to the formatting information while in edit mode as it currently stands, we will need an update to excel for this.

**Comment by feerrenrut** [comment]
P3 since its perhaps less common to individually format words within cells than format the whole cell.

**Comment by Adriani90** [comment]
I agree here. Formating single parts of content in a cell is not common practice.

**Comment by Qchristensen** [comment]
Trying this now with NVDA 2020.3 and Office 365 (64-bit) Version: 16.0.13426.20270, I find:

- On a cell (not in edit mode), NVDA reads: "No caret".
- Press F2 to go into edit mode (the focus is after the last character in the cell).  NVDA reads "No formatting information".
- In edit mode, move to within the text in the cell: NVDA reads the correct formatting information.

The comment above that it is less common to format individual words within a cell is, I believe, still correct, but that only makes the lack of formatting information when not in edit mode more pronounced.

Meanwhile, the work around is, go into edit mode, and left arrow once into the text.

**Comment by Adriani90** [comment]
Did you try with nvda+shift+f?

cc: @lukaszgo1, @CyrilleB79

**Comment by CyrilleB79** [comment]
@Qchristensen wrote:
> * In edit mode, move to within the text in the cell: NVDA reads the correct formatting information.

On my side, it is somewhat different (Excel 2016, NVDA 2020.3).
In a cell in edit mode and after having moved the caret in the middle of the text, NVDA reports "baseline", which is correct, but not bold and italic, either with NVDA+F or with NVDA+shift+F.

If the cell is not in edit mode, NVDA+F indicates only "No caret", but NVDA+shift+F indicates the correct formatting information for the whole cell, assuming it is uniform.





> The comment above that it is less common to format individual words within a cell is, I believe, still correct, but that only makes the lack of formatting information when not in edit mode more pronounced.
> 
> Meanwhile, the work around is, go into edit mode, and left arrow once into the text.

**Comment by lukaszgo1** [comment]
@Qchristensen wrote:
> On a cell (not in edit mode), NVDA reads: "No caret".

 This indeed regressed with #10973 - I'll submit a pr for this later today or tomorrow

**Comment by Adriani90** [comment]
I guess the expected behavior here is to report formating infor in the cell on the carret position with nvda+f and report the formating of the whole cell when pressing nvda+shift+f while in editing mode. Right? Because the navigator can only move between cells but not between letters within a cell. Or am I wrong?

So basically in most cases the formating information should be almost similar for nvda+f and nvda+shift+f, but for the nvda+shift+f command it could be more detailed (i.e. including formating of cell borders, background color etc.

**Comment by lukaszgo1** [comment]
> 
> 
> I guess the expected behavior here is to report formating infor in the cell on the carret position with nvda+f and report the formating of the whole cell when pressing nvda+shift+f while in editing mode. Right? Because the navigator can only move between cells but not between letters within a cell. Or am I wrong?

Since NVDA+Shift+F reports at the position of the review cursor NVDA_+Shift+F reports formatting info for whatever character is under the review cursor when in edit mode.  When not in edit mode output of NVDA+F and NVDA+Shift+F  would be exactly the same i.e formatting for the entire cell after #11914 would be merged.

**Comment by Qchristensen** [comment]
In 2020.4 beta 3 this behaviour is only slightly changed but the end result is the same:
- On a cell (not in edit mode), NVDA now reads: "No formatting information" (Previously it would read "No caret").
- Press F2 to go into edit mode (the focus is after the last character in the cell). Now press NVDA+f and NVDA reads "No formatting information".
- In edit mode, move to within the text in the cell: NVDA reads the correct formatting information.

No difference between NVDA+f and NVDA+shift+f.  If you do notice a difference, make sure you know where the review cursor is - ie if you don't have "Caret moves review cursor" set, if you left the review cursor somewhere with formatting information, ie in the middle of a cell in edit mode), then NVDA+shift+f will continue to report the formatting information in that cell until you move the review cursor).

**Comment by lukaszgo1** [comment]
>     * On a cell (not in edit mode), NVDA now reads: "No formatting information" (Previously it would read "No caret").


Can't confirm with latest Alpha  and Excel 2010 NVDA reads 
style Normal
no border lines
Calibri
11.0
black on white
background pattern none
align default
vertical align default

even for an empty cell.

**Comment by CyrilleB79** [comment]
> > ```
> > * On a cell (not in edit mode), NVDA now reads: "No formatting information" (Previously it would read "No caret").
> > ```
> 
> Can't confirm with latest Alpha and Excel 2010 NVDA reads
> style Normal
> no border lines
> Calibri
> 11.0
> black on white
> background pattern none
> align default
> vertical align default
> 
> even for an empty cell.

Same result as @lukaszgo1 on my side with both NVDA last alpha or NVDA 2020.4beta3 and Excel 2016.
Excel version: 16.0.5095.1000; this is not the last version of Excel 2016.

**Comment by Qchristensen** [comment]
I should have clarified in my last comment, I'm using Office 365.  So testing just now with NVDA 2020.4 beta 4 on Windows 10 (64-bit) Version: 2009, Build: 19042 running Office 365 (64-bit) Version: 16.0.13530.20418 

- On a cell (not in edit mode), NVDA+f now reads the correct formatting
- With multiple cells selected, NVDA reads "No formatting information"
- In edit mode at the very end of the contents, NVDA reads "No formatting information"
- In edit mode anywhere else in the cell, NVDA reads the correct formatting.

On the same PC but running NVDA alpha-21668,e8f14f9a, I get exactly the same results.

**Comment by CyrilleB79** [comment]
Following last @Qchristensen tests, here are my results on the same tests with Excel 2016 (16.0.5110.1000):

> * On a cell (not in edit mode), NVDA+f now reads the correct formatting

Also correct on my side with Excel 2016.

> * With multiple cells selected, NVDA reads "No formatting information"

Same issue here with Excel 2016.

> * In edit mode at the very end of the contents, NVDA reads "No formatting information"

Same issue here with Excel 2016.

> * In edit mode anywhere else in the cell, NVDA reads the correct formatting.

Here with Excel 2016, NVDA reads only baseline (should disappear with #11897). But it does not read all other formating info such as font name, size, bold, italic, etc.
@Qchristensen can you confirm NVDA reads all formatting information in this case and not just baseline?

**Comment by Qchristensen** [comment]
@CyrilleB79 Sorry you are correct - I wasn't paying enough attention (also my test spreadsheet at the time was using the default font).

In edit mode anywhere in a cell except past the last character, NVDA+f reads the DEFAULT baseline formatting.  IE Calibre 11pt - even if I've changed the formatting for part of a cell, or the whole cell.  If I escape out of edit mode and press NVDA+f, it reads the correct formatting.  If I've changed something for part of a cell, eg the font size for one word, NVDA will NOT read the (in this case) font size, but will read everything else.

**Comment by Adriani90** [comment]
It seems the only case where NVDA reports "no formating information" is when you select more than one cell and press nvda+f or nvda+shift+f.

@Qchristensen when formating for small pieces of text within the cell is changed, I think it would be quite difficult to include all the formating details within the cell when exiting the cell and reporting formating information is pressed on the entire cell. Actually in this case, it would be good to have an additional  reporting like "contains different formating styles" and otherwise don't change the current behavior.

**Comment by CyrilleB79** [comment]
> It seems the only case where NVDA reports "no formating information" is when you select more than one cell and press nvda+f or nvda+shift+f.

No @Adriani90, that's not correct. As written in https://github.com/nvaccess/nvda/issues/6479#issuecomment-768172985, the case when you edit the cell and the cursor is not at the end of the text also reports "No formatting". I have tested again and this is still the case today with Excel 2016 version '16.0.5387.1000'. I may test tomorrow on a newer version of Excel on another machine if you want.

**Comment by Adriani90** [comment]
Ok, I cannot reproduce on Excel 365 at least.
Do you have direct editing in cells enabled or disabled in excel advanced options?

However, when changing formating for some pieces of text within a cell and exiting the cell, applying nvda+f or nvda+shift+f on the entire cell gives me following error:

```
IO - speech.speech.speak (00:27:45.566) - MainThread (12124):
Speaking ['NVDA users', 'A2', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (00:27:46.106) - winInputHook (24320):
Input: kb(laptop):NVDA+f
ERROR - scriptHandler.executeScript (00:27:46.136) - MainThread (12124):
error executing script: <bound method GlobalCommands.script_reportOrShowFormattingAtCaret of <globalCommands.GlobalCommands object at 0x08BA9350>> with gesture 'NVDA+f'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 289, in executeScript
  File "globalCommands.pyc", line 2282, in script_reportOrShowFormattingAtCaret
  File "globalCommands.pyc", line 2260, in script_reportFormattingAtCaret
  File "globalCommands.pyc", line 2161, in _reportFormattingHelper
  File "textInfos\offsets.pyc", line 571, in getTextWithFields
  File "NVDAObjects\window\excel.pyc", line 1029, in _getFormatFieldAndOffsets
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by CyrilleB79** [comment]
> Ok, I cannot reproduce on Excel 365 at least. Do you have direct editing in cells enabled or disabled in excel advanced options?

Are you saying that you can get formatting info with NVDA+F while editing a cell? Have you "Direct editing in cell" enabled or disabled?

On my side, it is confirmed also with more recent Excel 2016, i.e. Microsoft® Excel® 2016 MSO (Version 2303 Build 16.0.16227.20202) 32 bits.
That is:
* Press F2 to edit a cell containing bold and italic text
* Set the cursor not at the end
* Press NVDA+F
NVDA says "No formatting" whereas it should indicate bold and italic.
tested now with Excel 2016 
with a cell containing bold and italic, I cannot get any formatting info.

I use direct edition in cell.


> However, when changing formating for some pieces of text within a cell and exiting the cell, applying nvda+f or nvda+shift+f on the entire cell gives me following error:
> 
> ```
> IO - speech.speech.speak (00:27:45.566) - MainThread (12124):
> Speaking ['NVDA users', 'A2', CancellableSpeech (still valid)]
> IO - inputCore.InputManager.executeGesture (00:27:46.106) - winInputHook (24320):
> Input: kb(laptop):NVDA+f
> ERROR - scriptHandler.executeScript (00:27:46.136) - MainThread (12124):
> error executing script: <bound method GlobalCommands.script_reportOrShowFormattingAtCaret of <globalCommands.GlobalCommands object at 0x08BA9350>> with gesture 'NVDA+f'
> Traceback (most recent call last):
>   File "scriptHandler.pyc", line 289, in executeScript
>   File "globalCommands.pyc", line 2282, in script_reportOrShowFormattingAtCaret
>   File "globalCommands.pyc", line 2260, in script_reportFormattingAtCaret
>   File "globalCommands.pyc", line 2161, in _reportFormattingHelper
>   File "textInfos\offsets.pyc", line 571, in getTextWithFields
>   File "NVDAObjects\window\excel.pyc", line 1029, in _getFormatFieldAndOffsets
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> ```

This does not happen with cells containing mixed bold / italic. But it happens with cells containing mixed colors. This is however a different issue tracked in #7277:
* The current issue is about formatting info requested on the current character while editing a cell
* #7277 is about formatting info requested on a whole cell.

Thanks.

**Comment by Qchristensen** [comment]
Testing again, I found several things:

With Allow editing directly in cells enabled, When I press F2 to edit a cell then NVDA+f to read the formatting, it reads it correctly, however it tells me the font is: "Calibri 14.300000190734863 pt black on white align left"

... Which is a very specific font size....  certainly much more precise than I had specified!  Looking in the font size edit, it actually says 11pt.  Not even 14 point.

With allow editing directly in cells disabled, I get:

"Calibri 12.0 pt white on white align left"

Again, the font size SHOULD be 11pt.

The text is black on white (in fact, it is set to automatic / no colour). I think what it is doing here is getting the font colour from the formula bar, which IS white (and possibly 12 pt?) - although it's not on a white background.

NVDA 2023.1.0.27913 
 
Windows 11 (64-bit) Version: 22H2, Build: 22621.1555 
 
Office 365 (64-bit) Version: 16.0.16227.20244

**Comment by Adriani90** [comment]
Hmm, very strange. I think this needs an external fix, maybe the API delivers the wrong info? Or is NVDA retrieving the formating info based on wrong assumptions?

cc: @ABuffEr, @SaschaCowley any idea on this one?

**Comment by Qchristensen** [comment]
I've worked out what is happening with the weird font sizes.  NVDA seems to be calculating the size of the text on screen based on 100% zoom - but if the zoom level (in Excel) is different to 100%, NVDA reports the font size incorrectly.  For instance:
Actual font size: 16pt
At 100% zoom, NVDA reports size as 16pt


Since this has pivoted from the original issue, and the original issue seems to be resolved.  I am closing this issue, and have opened #18180 specifically for the incorrect font size reporting issue.
