### ISSUE TITLE
Wordpad problem with latest next versions

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#6611]
When opening Wordpad to create a new document, you can enter text but then, you can't reread it using NVDA.
The problem does not seem to occur when opening an already existing document.
Tested with Wordpad under Windows 10 Anniversary 64 bits

**Comment by Mary5958** [comment]
It also happens to me with some existing documents if it includes some copied text, for example Skype chat logs or some text copied from a site but this part is quite irregular and seems to depend on the site but it wouldn't happen before yesterday's update, and language doesn't matter. When opening this kind of file NVDA throws errors and it's impossible to read anything or sometimes you can read just a few lines but moving by character or word even on those particular lines is impossible. I'm sending my log and one of the affected files.

**Comment by Mary5958** [comment]
I tried sending attachments to this ticket via Github but I'm not really 
sure if they got through so I'm trying via email now; just the log and 
one of the affected texts.

INFO - __main__ (14:23:51):
Starting NVDA
INFO - core.main (14:23:51):
Config dir: C:\Users\Martina\AppData\Roaming\nvda
INFO - core.main (14:23:52):
NVDA version next-13737,94e66478
INFO - core.main (14:23:52):
Using Windows version 10.0.14393 workstation
INFO - core.main (14:23:52):
Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
INFO - core.main (14:23:52):
Using comtypes version 0.6.2
INFO - core.main (14:23:52):
Add-ons are disabled. Restart NVDA to enable them.
INFO - synthDrivers.espeak.SynthDriver.__init__ (14:23:52):
Using eSpeak version 1.48.15  16.Apr.15
INFO - synthDriverHandler.setSynth (14:23:52):
Loaded synthDriver espeak
INFO - core.main (14:23:52):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (14:23:52):
Braille input initialized
INFO - braille.initialize (14:23:52):
Using liblouis version 3.0.0
INFO - braille.BrailleHandler.setDisplayByName (14:23:52):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (14:23:52):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (14:23:52):
UIAutomation: IUIAutomation3
INFO - core.main (14:23:53):
NVDA initialized
ERROR - eventHandler.executeEvent (14:24:01):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04EE7E50> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\behaviors.pyc", line 167, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 893, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 805, in reportFocus
  File "speech.pyc", line 370, in speakObject
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:04):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04EE7E50>> with gesture u'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:04):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04EE7E50>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:12):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_newLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04EE7E50>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 128, in script_caret_newLine
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - queueHandler.pumpAll (14:24:19):
error in generator 1
Traceback (most recent call last):
  File "queueHandler.pyc", line 72, in pumpAll
  File "sayAllHandler.pyc", line 128, in readTextHelper_generator
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - eventHandler.executeEvent (14:24:26):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\behaviors.pyc", line 167, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 893, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 805, in reportFocus
  File "speech.pyc", line 370, in speakObject
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:27):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30>> with gesture u'ctrl+home'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:28):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:29):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:29):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:29):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:29):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - scriptHandler.executeScript (14:24:32):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x04F23E30>> with gesture u'ctrl+home'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5
ERROR - queueHandler.pumpAll (14:24:33):
error in generator 2
Traceback (most recent call last):
  File "queueHandler.pyc", line 72, in pumpAll
  File "sayAllHandler.pyc", line 128, in readTextHelper_generator
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 5

**Comment by josephsl** [comment]
Regression due to #6555 and PR #6564. CC @MichaelDCurran, @feerrenrut

**Comment by jcsteh** [comment]
We're going to need a sample document that can be loaded into Wordpad to
reproduce this. You'll need to add any attachments via the web interface.
Only certain file extensions are accepted, so try zipping the file if
you're not sure. Thanks.

**Comment by Mary5958** [comment]
The file is in .RTF; I've zipped it now so hopefully it will work.
Only a few lines from the copied text plus two at the end added by me are recognized correctly.
[Break Another Heart.zip](https://github.com/nvaccess/nvda/files/625712/Break.Another.Heart.zip)

**Comment by Brian1Gaff** [comment]
Here is my message from the dev list, I'll see if I can find the file later 
on today and go to the web site and upload it but git is a bit of a git when 
trying to upload files sometimes.

IO - speech.speak (09:45:16):
Speaking [LangChangeCommand ('en_GB'), u'Document - WordPad  icon  2 of 8']
IO - speech.speak (09:45:18):
Speaking [LangChangeCommand ('en_GB'), u'Document - WordPad']
IO - speech.speak (09:45:18):
Speaking [LangChangeCommand ('en_GB'), u'edit  multi line']
IO - speech.speak (09:45:18):
Speaking [LangChangeCommand ('en_GB'), u'Traffic and travel.\r This is
Monday and Tuesday night only, but it does not specify whether the road
closure will be all day.\rKingston Road, New Malden\r\xb7\tcarriageway
resurfacing\r\xb7\tSouth Lane West to Wellington Crescent\r\xb7\tnight
works\r\xb7\tmultiway temporary traffic signals\r\xb7\tclosure of South Lane
West\r\xb7\tMonday 5 December to 6 December 2016\r\r\r===\r\r']
IO - inputCore.InputManager.executeGesture (09:45:19):
Input: kb(desktop):control+home
IO - speech.speak (09:45:19):
Speaking [LangChangeCommand ('en_GB'), u'Traffic and travel.\r']
IO - inputCore.InputManager.executeGesture (09:45:22):
Input: kb(desktop):downArrow
IO - speech.speak (09:45:22):
Speaking [LangChangeCommand ('en_GB'), u' This is Monday and Tuesday night
only, but it does not specify whether the road closure will be all day.\r']
IO - inputCore.InputManager.executeGesture (09:45:23):
Input: kb(desktop):downArrow
ERROR - scriptHandler.executeScript (09:45:23):
error executing script: <bound method
Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of
<NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at
0x05AA23B0>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 9


No idea what this is about it was some text pasted into wordpad from a word
document which in itself has no errors when read.

Anything else you need to know before I raise a ticket. I think this is the
non ribbon version of wordpad which many use on 7 these days.

Its obvious that from the comments the version of Wordpad is not the issue 
here, but more the cut and pasted text or some of the characters used in it.
 Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
While I'm here let me point out that the issue is in fact far worse in jarte 
than in Wordpad, stopping any kind of access to most of the file that has 
issues as the log below shows, and as has been said points the finger toward 
the offending recent update.
IO - speech.speak (07:44:34):
Speaking [LangChangeCommand ('en_GB'), u'traffic.doc - Jarte   (screen 
reader mode)']
IO - speech.speak (07:44:34):
Speaking [LangChangeCommand ('en_GB'), u'edit  multi line']
IO - speech.speak (07:44:34):
Speaking [LangChangeCommand ('en_GB'), u'Traffic and travel 2 pages..\r']
IO - inputCore.InputManager.executeGesture (07:44:42):
Input: kb(desktop):NVDA+downArrow
DEBUG - queueHandler.registerGeneratorObject (07:44:42):
Adding generator 1
IO - speech.speak (07:44:42):
Speaking [IndexCommand(1), LangChangeCommand ('en_GB'), u'Traffic and travel 
2 pages..\r\r', IndexCommand(2), u'Park Road, Kingston\r\xb7\tSunday 04 
December 2016\r\xb7\tnight-time works on pedestrian island\r\xb7\tbetween 
the junctions with Kings Road and Wyndham Road\r\xb7\tmultiway traffic 
signals\rObviously to be avoided by pedestrians, then.\r']
IO - speech.speak (07:44:42):
Speaking [IndexCommand(3), LangChangeCommand ('en_GB'), u'====\r\r This is 
Monday and Tuesday night only, but it does not specify whether the road 
closure will be all day.\r']
ERROR - queueHandler.pumpAll (07:44:42):
error in generator 1
Traceback (most recent call last):
  File "queueHandler.pyc", line 72, in pumpAll
  File "sayAllHandler.pyc", line 128, in readTextHelper_generator
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 9

Brian


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
It seems you don't need any file at all as the error occurs on an empty 
wordpad in windows 7, and interestingly, in this log I left the add ons 
switched on so you can see them come in as well.

IO - speech.speak (08:20:20):
Speaking [LangChangeCommand ('en_GB'), u'WordPad']
IO - inputCore.InputManager.executeGesture (08:20:22):
Input: kb(desktop):enter
IO - speech.speak (08:20:22):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - speech.speak (08:20:22):
Speaking [LangChangeCommand ('en_GB'), u'Document - WordPad']
IO - speech.speak (08:20:22):
Speaking [LangChangeCommand ('en_GB'), u'Rich Text Window  edit  multi 
line']
ERROR - eventHandler.executeEvent (08:20:22):
error executing event: gainFocus on 
<NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 
0x05A4CFF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File 
"C:\Users\Brian\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", 
line 419, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File 
"C:\Users\Brian\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator.py", 
line 82, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\behaviors.pyc", line 167, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 893, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 805, in reportFocus
  File "speech.pyc", line 370, in speakObject
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 9
IO - inputCore.InputManager.executeGesture (08:20:28):
Input: kb(desktop):downArrow
ERROR - scriptHandler.executeScript (08:20:28):
error executing script: <bound method 
Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of 
<NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 
0x05A4CFF0>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 9
IO - inputCore.InputManager.executeGesture (08:20:29):
Input: kb(desktop):upArrow
ERROR - scriptHandler.executeScript (08:20:29):
error executing script: <bound method 
Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_moveByLine of 
<NVDAObjects.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 
0x05A4CFF0>> with gesture u'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 544, in _getFormatFieldAtRange
  File "languageHandler.pyc", line 47, in windowsLCIDToLocaleName
KeyError: 9
IO - inputCore.InputManager.executeGesture (08:20:38):
Input: kb(desktop):control+alt+r
DEBUGWARNING - RPC process 2736 (conhost.exe) (08:20:38):
Thread 2960, build\x86_64\remote\ia2Support.cpp, installIA2Support, 86:
Error registering class object, code -2147221008

IO - speech.speak (08:20:38):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - speech.speak (08:20:39):
Speaking [LangChangeCommand ('en_GB'), u'reboot nvda with log  terminal']
IO - speech.speak (08:20:39):
Speaking [LangChangeCommand ('en_GB'), u'blank']
INFO - core.main (08:20:39):
Exiting



This is the native wordpad for windows 7 with the ribbon menu
 Just for clarity. No real need to use a file. I suspect that something in 
some files  goes out of range, but if you get the error on an empty file 
then my guess is its counting characters which are only used for  language 
id and getting the position out of range due to that.

Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment]
incidentally the no file loaded  issue in wordpad/Jarte ony seems to occur 
if you use the  ribbon menu version of Wordpad, and you will need the test 
file for Jarte and older wordpad versions. However the file shows errors in 
all versions.
In the Ribbon version of Wordpad just typing into the file area and trying 
to edit it causes the error.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by feerrenrut** [comment]
The keys being complained about have the values `5` and `9`. The meaning of these values can be found by looking at the `CLID` table on [msdn](https://msdn.microsoft.com/en-us/library/cc233982.aspx). `5` is for Czech (`cs`) and `9` is for English (`en`). One thing to note about these is that they lack the culture code, it is just the language that is specified.

Looking at the python locale module (specifically `locale.windows_locale`) it doesn't seem to support language only locales.
When using MS Word this kind of error is caught, logged and ignored.
