### ISSUE TITLE
Excel autocomplete formula doesn't read

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6786]
When typing a formula in Excel, a drop down list appears with auto complete options for what has been typed so far.  If I type =cou for instance, a list will appear with COUNT, COUNTA, COUNTBLANK etc.  When you arrow through the list, a tooltip appears explaining each function ("Counts the number of cells in a range that contain numbers" for COUNT).

Pressing TAB inserts the currently selected function from the list ready to add arguments. Nothing is read when moving through the list or when TAB is pressed and the function is added to the current cell (the dropdown appears for nested functions as well).

**Comment by DGartmann** [comment]
Still not announcing the autocomplete suggestion in Excel 2016 running NVDA Next 14342.

**Comment by lukaszgo1** [comment]
Can this issue be prioritized? I'm not using Excel myself, but many users in the polish community are asking about this particular feature. As far as i know it didn't work in office 2013 and from my testing 2010 is also affected.

**Comment by Qchristensen** [comment]
No update, except to my original explanation - as well as the definition of the functions in the autocomplete list, once you have typed the function and are entering the arguments, the tooltip denotes the allowed arguments.  For COUNT for instance:
- When =cou has been typed and the count function is selected in the list, the tooltip explains "Counts the number of cells in a range that contain numbers"
- once the open parenthesis is added, the tooltip changes to "=count(value1, [value2], ...)"

Visually the current argument is highlighted, but if we leave this issue at simply reading the text, that would be a great improvement.

**Comment by seanbudd** [comment]
Closing this as fixed

**Comment by Adriani90** [comment]
This is not fixed, I can still reproduce. Reopening

**Comment by Adriani90** [comment]
Update with MS Office 365 version 2510 and NVDA alpha-53667,bc2647d0 (2026.1.0.53667):

When direct editing in cells is enabled in Excel advanced settings, the suggestions are properly announced and inserting them with tab announces the required and optional parameters.

**Comment by Adriani90** [comment]
However, when direct editing in cells is disabled, I get following error while suggestions appear or while pressing tab to add a suggestion to the cell. NVDA freezes everytime for approx. 2.5 seconds:


1. When typing and the suggestion appears:

```
IO - speech.speech.speak (23:26:12.439) - MainThread (26112):
Speaking ['Bearbeitungsleiste', 'Eingabefeld', CancellableSpeech (still valid), '=']
IO - inputCore.InputManager.executeGesture (23:26:13.257) - winInputHook (21396):
Input: kb(laptop):s
IO - inputCore.InputManager.executeGesture (23:26:13.383) - winInputHook (21396):
Input: kb(laptop):u
IO - inputCore.InputManager.executeGesture (23:26:13.606) - winInputHook (21396):
Input: kb(laptop):m
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (23:26:13.794) - watchdog (11764):
Potential freeze, waiting up to 10 seconds.
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:26:15.434) - Dummy-495 (24424):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1373, in getNearestWindowHandle
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (23:26:15.439) - MainThread (26112):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30060, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:26:15.448) - Dummy-500 (24424):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1373, in getNearestWindowHandle
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:26:15.454) - Dummy-503 (24424):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1373, in getNearestWindowHandle
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (23:26:15.440) - MainThread (26112):
error executing event: typedCharacter on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x000001CC80C469C0> with extra args of {'ch': 's'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 354, in executeEvent
  File "eventHandler.pyc", line 120, in __init__
  File "eventHandler.pyc", line 129, in next
  File "NVDAObjects\behaviors.pyc", line 312, in event_typedCharacter
  File "NVDAObjects\__init__.pyc", line 1257, in event_typedCharacter
  File "speech\speech.pyc", line 1386, in speakTypedCharacters
  File "api.pyc", line 362, in isTypingProtected
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1127, in _get_isProtected
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1916, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 1160, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (23:26:15.464) - MainThread (26112):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30060, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
ERROR - eventHandler.executeEvent (23:26:15.465) - MainThread (26112):
error executing event: typedCharacter on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x000001CC80C469C0> with extra args of {'ch': 'u'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 354, in executeEvent
  File "eventHandler.pyc", line 120, in __init__
  File "eventHandler.pyc", line 129, in next
  File "NVDAObjects\behaviors.pyc", line 312, in event_typedCharacter
  File "NVDAObjects\__init__.pyc", line 1257, in event_typedCharacter
  File "speech\speech.pyc", line 1386, in speakTypedCharacters
  File "api.pyc", line 362, in isTypingProtected
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1127, in _get_isProtected
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1916, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 1160, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (23:26:15.557) - MainThread (26112):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30060, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
ERROR - eventHandler.executeEvent (23:26:15.558) - MainThread (26112):
error executing event: descriptionChange on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x000001CC80C469C0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 354, in executeEvent
  File "eventHandler.pyc", line 120, in __init__
  File "eventHandler.pyc", line 129, in next
  File "NVDAObjects\__init__.pyc", line 1417, in event_descriptionChange
  File "speech\speech.pyc", line 643, in speakObjectProperties
  File "speech\speech.pyc", line 753, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1916, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 1160, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (23:26:15.798) - watchdog (11764):
Recovered from potential freeze after 2.503750400035642 seconds.
```

2. When pressing tab to add suggestion to the cell:

```
IO - inputCore.InputManager.executeGesture (23:26:17.668) - winInputHook (21396):
Input: kb(laptop):tab
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (23:26:18.189) - watchdog (11764):
Potential freeze, waiting up to 10 seconds.
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (23:26:19.899) - Dummy-510 (24424):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1373, in getNearestWindowHandle
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (23:26:19.904) - MainThread (26112):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30060, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
ERROR - eventHandler.executeEvent (23:26:19.905) - MainThread (26112):
error executing event: descriptionChange on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x000001CC80C469C0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 354, in executeEvent
  File "eventHandler.pyc", line 120, in __init__
  File "eventHandler.pyc", line 129, in next
  File "NVDAObjects\__init__.pyc", line 1417, in event_descriptionChange
  File "speech\speech.pyc", line 643, in speakObjectProperties
  File "speech\speech.pyc", line 753, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1916, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 1160, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (23:26:19.937) - MainThread (26112):
error executing event: UIA_controllerFor on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x000001CC80C469C0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 354, in executeEvent
  File "eventHandler.pyc", line 120, in __init__
  File "eventHandler.pyc", line 129, in next
  File "NVDAObjects\UIA\__init__.pyc", line 2410, in event_UIA_controllerFor
  File "NVDAObjects\behaviors.pyc", line 232, in event_controllerForChange
  File "baseObject.pyc", line 59, in __get__
  File "baseObject.pyc", line 167, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 2371, in _get_controllerFor
  File "NVDAObjects\UIA\__init__.pyc", line 1160, in _getUIACacheablePropertyValue
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (23:26:20.197) - watchdog (11764):
Recovered from potential freeze after 2.507883000012953 seconds.
```

@michaelDCurran do you think this needs to be fixed by Microsoft? Or can something be improved in NVDA?
It makes working in Excel very slow and inefficient due to these freezes.

Ofcourse there is always the possibility to turn off suggestions completely, but finding that setting in Excel is by far not trivial and beginners will struggle alot with the current issue.
