### ISSUE TITLE
Unicode Encode error in Microsoft Excel

### ISSUE THREAD

**Issue by michaelDCurran** [nvaccess/nvda#6848]
In Microsoft Excel when pressing NVDA+numpadDelete 
for report sheet name, exception UnicodeEncodeError arises Here.
```
ERROR - scriptHandler.executeScript (20:14:49):
error executing script: <bound method 
GlobalCommands.script_navigatorObject_currentDimensions of 
<globalCommands.GlobalCommands object at 0x05CB4090>> with gesture 
u'NVDA+delete \u043d\u0430 
\u0446\u0438\u0444\u0440\u043e\u0432\u043e\u043c 
\u0431\u043b\u043e\u043a\u0435'
Traceback (most recent call last):
   File "scriptHandler.py", line 187, in executeScript
     script(gesture)
   File "globalCommands.py", line 804, in 
script_navigatorObject_currentDimensions
     locationText=api.getReviewPosition().locationText if count==0 else None
   File "baseObject.py", line 21, in __get__
     return self.fget(instance)
   File "NVDAObjects\window\excel.py", line 991, in _get_locationText
     return self.obj.getCellPosition()
   File "NVDAObjects\window\excel.py", line 1136, in getCellPosition
     return "Sheet {0}, {1}".format(sheet, rowAndColumn)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 
0-3: ordinal not in range(128)
```

This string should be unicode, and translatable.

**Comment by michaelDCurran** [comment]
Introduced in #6736
