### ISSUE TITLE
Outlook 2016: Multiple reading issues with the account settings dialog

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6859]
Based on the log below, multiple repetitions of the announcement about the data file association as well as tabs. Note: the behavior is the same when I disable all add-ons. 
* Expected behavior: When the dialog is opened, NVDA announces "mail" tab.
* Actual behavior: multiple verbose announcements of Outlook data file association for the focused email account.

STR:
1. Open Outlook
2. press alt+f to enter the file tab
3. Press i to enter the info tab
4. Press s to get to the account settings item.
5. Press enter to enter the account settings dialog.
6. Press tab.

IO - inputCore.InputManager.executeGesture (10:33:00):
Input: kb(laptop):alt+f
IO - inputCore.InputManager.executeGesture (10:33:01):
Input: kb(laptop):i
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:01):
oleacc.AccessibleObjectFromEvent with window 25821826, objectID -4 and childID 0: [Error -2147024809] The parameter is incorrect
IO - speech.speak (10:33:02):
Speaking [LangChangeCommand ('en'), u'Info  tab  selected  Info  Alt, F, I']
IO - inputCore.InputManager.executeGesture (10:33:02):
Input: kb(laptop):s
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:02):
oleacc.AccessibleObjectFromEvent with window 725996, objectID 73036 and childID 0: [Error -2147467259] Unspecified error
IO - speech.speak (10:33:02):
Speaking [LangChangeCommand ('en'), u'menu']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:03):
oleacc.AccessibleObjectFromEvent with window 725996, objectID 73049 and childID 0: [Error -2147467259] Unspecified error
IO - speech.speak (10:33:03):
Speaking [LangChangeCommand ('en'), u'menu']
IO - inputCore.InputManager.executeGesture (10:33:04):
Input: kb(laptop):enter
DEBUGWARNING - watchdog._watcher (10:33:04):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 195, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 366, in Notify
  File "IAccessibleHandler.pyc", line 885, in pumpAll
  File "IAccessibleHandler.pyc", line 618, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 522, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 299, in isUIAWindow
  File "_UIAHandler.pyc", line 293, in _isUIAWindowHelper

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:05):
oleacc.AccessibleObjectFromEvent with window 26018434, objectID -4 and childID 0: [Error -2147024809] The parameter is incorrect
DEBUGWARNING - eventHandler.executeEvent (10:33:05):
error executing event: typedCharacter on <NVDAObjects.UIA.UIA object at 0x05581850> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\Pratik Patel\AppData\Roaming\nvda\addons\reportSymbols\globalPlugins\reportSymbols.py", line 58, in event_typedCharacter
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 840, in event_typedCharacter
  File "speech.pyc", line 627, in speakTypedCharacters
  File "api.pyc", line 239, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 814, in _get_states
  File "comtypes\__init__.pyc", line 266, in __getattr__
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
IO - speech.speak (10:33:05):
Speaking [LangChangeCommand ('en'), u'Account Settings  dialog  E-mail Accounts\nYou can add or remove an account. You can select an account and change its settings.\nSelected account delivers new messages to the following location:\nSelected account delivers new messages to the following location:\nppatel@ezfire.net\\Inbox\nSelected account delivers new messages to the following location:\nin data file C:\\Users\\Pratik Patel\\...\\Microsoft\\Outlook\\ppatel@ezfire.net.ost']
IO - speech.speak (10:33:05):
Speaking [LangChangeCommand ('en'), u'AcctMgr Tab  tab control']
IO - speech.speak (10:33:05):
Speaking [LangChangeCommand ('en'), u'E-mail  tab  selected']
IO - inputCore.InputManager.executeGesture (10:33:15):
Input: kb(laptop):tab
IO - speech.speak (10:33:16):
Speaking [LangChangeCommand ('en'), u'DAL=on  property page  Selected account delivers new messages to the following location:\nSelected account delivers new messages to the following location:\nppatel@ezfire.net\\Inbox\nSelected account delivers new messages to the following location:\nin data file C:\\Users\\Pratik Patel\\...\\Microsoft\\Outlook\\ppatel@ezfire.net.ost']
IO - speech.speak (10:33:16):
Speaking [LangChangeCommand ('en'), u'tool bar']
IO - speech.speak (10:33:16):
Speaking [LangChangeCommand ('en'), u'New...  button  Alt+n']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:16):
oleacc.AccessibleObjectFromEvent with window 128452410, objectID 73058 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:16):
oleacc.AccessibleObjectFromEvent with window 128452410, objectID 73059 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:16):
oleacc.AccessibleObjectFromEvent with window 4915824, objectID 73060 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:33:16):
oleacc.AccessibleObjectFromEvent with window 4915824, objectID 73061 and childID 0: [Error -2147467259] Unspecified error

**Comment by Adriani90** [comment]
This is still the case in NVDA 2019.1 and Outlook 2016 and 365.
