### ISSUE TITLE
ARIA List Box List items are announced in Browse mode in internet Explorer  when navigating wiht the ARROW keys. 

### ISSUE THREAD

**Issue by rnickelson** [nvaccess/nvda#6965]
In Internet Explorer, navigate to
https://labs.ssbbartgroup.com/index.php/ARIA_Listbox
Ensure browse mode is enabled.
Navigate to the Platform Label.
Press DOWN ARROW
Notice that NVDA announces the list items iOS, Android, Windows Phone.
According to bug #6934 which considers the same user actions while using Firefox, this should not be the case.

**Comment by feerrenrut** [comment]
I can reproduce this with NVDA `next-13911,3c8e30bd` on Internet Explorer `Version: 11.576.14393.0 Update Versions: 11.0.38 (KB3203621)` Using the same link with Firefox gives the behaviour described in #6934 (items are NOT announced)

**Comment by Adriani90** [comment]
I can reproduce this issue in IE11 with NVDA 2019.1. When using arrow key to navigate in browse mode, NVDA reports each item of the list box on a line instead of reporting "list box IOS selected".
I tried to see if I cann access the list by focus mode:
1. Pressing enter on the list does not work
2. Pressing NVDA+space works. When accessig the list with tab and shift+tab, following error in in the log file:

**Comment by Adriani90** [comment]
```
IO - inputCore.InputManager.executeGesture (16:33:37.460):
Input: kb(laptop):NVDA+space
IO - inputCore.InputManager.executeGesture (16:33:37.910):
Input: kb(laptop):tab
IO - inputCore.logTimeSinceInput (16:33:38.223):
0.314 sec since input
IO - speech.speak (16:33:38.223):
Speaking [u'Special:Categories  Link  Special:Categories']
IO - inputCore.InputManager.executeGesture (16:33:38.640):
Input: kb(laptop):shift+tab
IO - inputCore.logTimeSinceInput (16:33:38.907):
0.267 sec since input
IO - speech.speak (16:33:38.907):
Speaking [u'Nothing  Schalter']
IO - inputCore.InputManager.executeGesture (16:33:39.433):
Input: kb(laptop):shift+tab
IO - inputCore.logTimeSinceInput (16:33:39.684):
0.251 sec since input
IO - speech.speak (16:33:39.684):
Speaking [u'Platform:  Liste']
ERROR - eventHandler.executeEvent (16:33:39.711):
error executing event: gainFocus on <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x0551D0B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1475, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 966, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 854, in reportFocus
  File "speech.pyc", line 403, in speakObject
  File "speech.pyc", line 327, in speakObjectProperties
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1235, in _get_selectionContainer
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 957, in _get_table
NotImplementedError
IO - inputCore.InputManager.executeGesture (16:33:41.357):
Input: kb(laptop):downArrow
ERROR - eventHandler.executeEvent (16:33:41.572):
error executing event: gainFocus on <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x0543B030> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1475, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 966, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 854, in reportFocus
  File "speech.pyc", line 403, in speakObject
  File "speech.pyc", line 327, in speakObjectProperties
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1235, in _get_selectionContainer
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 957, in _get_table
NotImplementedError
```

**Comment by Adriani90** [comment]
cc: @feerrenrut, @leonardder

**Comment by Brian1Gaff** [comment]
Is this everywhere or in specific pages?

I suspect not a lot of people will be using IE11, but I think I still have 
it, so if I knew where to look
Not implemented makes it sound like its not going to be easy to fix perhaps?
 ....
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Adriani90** [comment]
IE support has ended completely in 2022 and the browser is being removed automatically from machines that still have it after an Edge update in February 2023. I am closing this issue as abandoned, since I don't expect any further accessibility updates to IE or to IE mode in Edge. If you are having this issue in other browsers, please open a new issue with updated steps to reproduce and a minimal test case.
