### ISSUE TITLE
edge: error while alt+tabig to edge window

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#6975]
ERROR - eventHandler.executeEvent (10:55:14):
error executing event: gainFocus on <NVDAObjects.UIA.edge.EdgeNode object at 0x052B5FF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 171, in doPreGainFocus
  File "browseMode.pyc", line 1070, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1126, in _set_selection
  File "cursorManager.pyc", line 107, in _set_selection
  File "cursorManager.pyc", line 410, in updateSelection
  File "treeInterceptorHandler.pyc", line 158, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 523, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 149, in __init__
  File "textInfos\__init__.pyc", line 238, in __init__
TypeError: cannot create weak reference to 'NoneType' object

**Comment by jcsteh** [comment]
CC @MichaelDCurran

**Comment by PratikP1** [comment]
I’m unable to replicate this in NVDA version next-13911,3c8e30bd and Windows 10 insider 15058.

**Comment by feerrenrut** [comment]
@beqabeqa473 Are you able to reproduce this?

**Comment by Adriani90** [comment]
No error in Edge Chromium 81. And we didn't get any updates from the initial author since years. Closing as works for me and abandoned.

**Comment by Adriani90** [comment]
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
