### ISSUE TITLE
NVDA gets an error when the webpage contains aria-label syntax problem.

### ISSUE THREAD

**Issue by oaron** [nvaccess/nvda#7173]
### Steps to reproduce:
When I open a webpage which contains aria-label syntax error, NVDA plays the error sound, and NVDA does not read the content. The syntax problem is the folloving:
&lt;section aria-label"almenük" role="region"&gt;
(= sign is missing after aria-label)
You can test it on the folloving page: https://alkosoft.hu/szolgaltatasok/tavszerviz
On the top, press d for four times, and press down arrow for three times. In this case the error sound playes, and NVDA does not read the content.

### Expected behavior:
Good solution would be that NVDA skips the aria-label, but content of the section can be navigate.

### Actual behavior:
NVDA playes an error sound, and it does not announce content of the region.

### System configuration:
NVDA version: next-14045,c75e7d19

NVDA Installed or portable: installed

Windows version: Windows 7 64 bits

Name and version of other software in use when reproducing the issue: Mozilla Firefox 53.0.2

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No

**Comment by Brian1Gaff** [comment]
Actually in Master at least it does not crash, it merely gets stuck in a 
loop so cursor movement cannot take place unless for example D or shift D is 
pressed to get it out of the hole, so to speak.
 In the release version I'd suspect it just gets stuck and  is silent. The 
log in master looks like this up to the end of the first loop.
IO - inputCore.InputManager.executeGesture (09:46:44):
Input: kb(desktop):downArrow
ERROR - XMLFormatting.XMLTextParser.parse (09:46:44):
XML: <control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-57" _startOfNode="0" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="13" _childcontrolcount="11" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_display="block" 
IAccessible2::attribute_explicit-name="true" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="body" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible::role="15" IAccessible::state_1048576="1" 
IAccessible::state_64="1" description="" keyboardShortcut="" name="Alko-Soft 
Távszerviz" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-64" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="2" _childcontrolcount="1" _indexInParent="6" 
_parentChildCount="13" IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_id="contentcontainer" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-166" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="2" _childcontrolcount="2" _indexInParent="0" 
_parentChildCount="2" IAccessible2::attribute_display="table" 
IAccessible2::attribute_id="menucontainer" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-167" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" 
_parentChildCount="2" IAccessible2::attribute_display="table-cell" 
IAccessible2::attribute_id="submenu" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-168" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_label"almenük"="" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" 
IAccessible2::attribute_tag="section" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" 
IAccessible2::attribute_xml-roles="region" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="20" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-169" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="14" _childcontrolcount="13" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_class="sub_ul" 
IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-170" _startOfNode="1" _endOfNode="1" isBlock="1" 
isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" 
_parentChildCount="14" IAccessible2::attribute_class="sub_li activeli" 
IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-171" _startOfNode="1" _endOfNode="1" isBlock="1" 
isHidden="0" _childcount="2" _childcontrolcount="0" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_display="block" 
IAccessible2::attribute_draggable="true" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="a" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="30" 
IAccessible::state_1048576="1" IAccessible::state_4194304="1" 
IAccessibleAction_jump="0" description="" keyboardShortcut="" ><text 
_startOfNode="1" _endOfNode="1" isBlock="0" isHidden="0" _childcount="0" 
_childcontrolcount="0" _indexInParent="1" _parentChildCount="2" 
background-color="rgb(146, 145, 145)" color="rgb(255, 255, 255)" 
font-family="Merriweather" font-size="15pt" font-style="normal" 
font-weight="700" language="hu" text-align="start" text-position="baseline" 
 >Távszerviz</text></control></control></control></control></control></control></control></control>
Traceback (most recent call last):
  File "XMLFormatting.pyc", line 60, in parse
ExpatError: not well-formed (invalid token): line 1, column 3239
IO - speech.speak (09:46:44):
Speaking [LangChangeCommand ('en_GB'), u'blank']
IO - speech.speak (09:46:44):
Speaking [LangChangeCommand ('en_GB'), u'Bel\xe9p\xe9s / 
Regisztr\xe1ci\xf3']
ERROR - XMLFormatting.XMLTextParser.parse (09:46:44):
XML: <control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-57" _startOfNode="0" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="13" _childcontrolcount="11" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_display="block" 
IAccessible2::attribute_explicit-name="true" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="body" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible::role="15" IAccessible::state_1048576="1" 
IAccessible::state_64="1" description="" keyboardShortcut="" name="Alko-Soft 
Távszerviz" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-64" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="2" _childcontrolcount="1" _indexInParent="6" 
_parentChildCount="13" IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_id="contentcontainer" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-166" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="2" _childcontrolcount="2" _indexInParent="0" 
_parentChildCount="2" IAccessible2::attribute_display="table" 
IAccessible2::attribute_id="menucontainer" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-167" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" 
_parentChildCount="2" IAccessible2::attribute_display="table-cell" 
IAccessible2::attribute_id="submenu" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-168" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_label"almenük"="" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" 
IAccessible2::attribute_tag="section" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" 
IAccessible2::attribute_xml-roles="region" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="20" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-169" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="14" _childcontrolcount="13" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_class="sub_ul" 
IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-170" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" 
_parentChildCount="14" IAccessible2::attribute_class="sub_li activeli" 
IAccessible2::attribute_display="block" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="1060" description="" 
keyboardShortcut="" ><control controlIdentifier_docHandle="1508396" 
controlIdentifier_ID="-171" _startOfNode="1" _endOfNode="0" isBlock="1" 
isHidden="0" _childcount="2" _childcontrolcount="0" _indexInParent="0" 
_parentChildCount="1" IAccessible2::attribute_display="block" 
IAccessible2::attribute_draggable="true" 
IAccessible2::attribute_formatting="block" 
IAccessible2::attribute_margin-bottom="0px" 
IAccessible2::attribute_margin-left="0px" 
IAccessible2::attribute_margin-right="0px" 
IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="a" 
IAccessible2::attribute_text-align="start" 
IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" 
IAccessible2::state_4096="1" IAccessible::role="30" 
IAccessible::state_1048576="1" IAccessible::state_4194304="1" 
IAccessibleAction_jump="0" description="" keyboardShortcut="" ><text 
_startOfNode="1" _endOfNode="0" isBlock="0" isHidden="0" _childcount="0" 
_childcontrolcount="0" _indexInParent="1" _parentChildCount="2" 
background-color="rgb(146, 145, 145)" color="rgb(255, 255, 255)" 
font-family="Merriweather" font-size="15pt" font-style="normal" 
font-weight="700" language="hu" text-align="start" text-position="baseline" 
 >T</text></control></control></control></control></control></control></control></control>
Traceback (most recent call last):
  File "XMLFormatting.pyc", line 60, in parse
ExpatError: not well-formed (invalid token): line 1, column 3239
IO - inputCore.InputManager.executeGesture (09:46:46):
Input: kb(desktop):downArrow

Where up or down arrow gives the same error.
 Brian

**Comment by derekriemer** [comment]
Hi:
This isn't a crash, just an error. The error triggered appears to be 

Speaking [u'Bel\xe9p\xe9s / Regisztr\xe1ci\xf3']
ERROR - XMLFormatting.XMLTextParser.parse (15:33:10):
XML: <control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332470" _startOfNode="0" _endOfNode="0" isBlock="1" isHidden="0" _childcount="13" _childcontrolcount="11" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_display="block" IAccessible2::attribute_explicit-name="true" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="body" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" IAccessible::role="15" IAccessible::state_1048576="1" IAccessible::state_64="1" description="" keyboardShortcut="" name="Alko-Soft Távszerviz" ><control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332479" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="2" _childcontrolcount="1" _indexInParent="6" _parentChildCount="13" IAccessible2::attribute_display="block" IAccessible2::attribute_formatting="block" IAccessible2::attribute_id="contentcontainer" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="1060" description="" keyboardShortcut="" ><control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332543" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="2" _childcontrolcount="2" _indexInParent="0" _parentChildCount="2" IAccessible2::attribute_display="table" IAccessible2::attribute_id="menucontainer" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="1060" description="" keyboardShortcut="" ><control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332544" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" _parentChildCount="2" IAccessible2::attribute_display="table-cell" IAccessible2::attribute_id="submenu" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="1060" description="" keyboardShortcut="" ><control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332545" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_display="block" IAccessible2::attribute_formatting="block" IAccessible2::attribute_label"almenük"="" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="section" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::attribute_xml-roles="region" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="20" description="" keyboardShortcut="" ><control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332546" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="14" _childcontrolcount="13" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_class="sub_ul" IAccessible2::attribute_display="block" IAccessible2::attribute_formatting="block" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="1060" description="" keyboardShortcut="" ><control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332547" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" _parentChildCount="14" IAccessible2::attribute_class="sub_li activeli" IAccessible2::attribute_display="block" IAccessible2::attribute_formatting="block" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="div" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="1060" description="" keyboardShortcut="" ><control controlIdentifier_docHandle="262898" controlIdentifier_ID="-332485" _startOfNode="1" _endOfNode="0" isBlock="1" isHidden="0" _childcount="2" _childcontrolcount="0" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_display="block" IAccessible2::attribute_draggable="true" IAccessible2::attribute_formatting="block" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="a" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="30" IAccessible::state_1048576="1" IAccessible::state_4194304="1" IAccessible::state_8388608="1" IAccessibleAction_jump="0" description="" keyboardShortcut="" ><text _startOfNode="1" _endOfNode="0" isBlock="0" isHidden="0" _childcount="0" _childcontrolcount="0" _indexInParent="1" _parentChildCount="2" background-color="rgb(146, 145, 145)" color="rgb(255, 255, 255)" font-family="Merriweather" font-size="15pt" font-style="normal" font-weight="700" language="hu" text-align="start" text-position="baseline" >T</text></control></control></control></control></control></control></control></control>
Traceback (most recent call last):
  File "XMLFormatting.pyc", line 60, in parse
ExpatError: not well-formed (invalid token): line 1, column 3251

**Comment by Brian1Gaff** [comment]
Which was why I posted that as a comment to the original. it affects master 
as well, so I suspect the effect is always been there.
 It would be nice if it allowed cursoring out of the black hole rather than 
to use tab or some other way though.
 Brian

**Comment by jcsteh** [comment]
Confirmed.

Technical: Our vbuf XML output code sanitises spaces (#6295, be357ce), but no other characters. It needs to sanitise quotes to fix this issue. I guess we may as well sanitise other invalid characters while we're at it.

P2 because while this is pretty nasty, it isn't a crash and should be pretty rare in the wild.

**Comment by Adriani90** [comment]
@oaron, @jcsteh  I cannot reproduce this issue in NVDA alpha-17077,7f274eca and Firefox 66.0.3. Can you still see this error?

**Comment by jcsteh** [comment]
I can still reproduce it here.

**Comment by jcsteh** [comment]
Simple test case: `data:text/html,<section aria-label"almenük" role="region">`

**Comment by Adriani90** [comment]
@jcsteh can you reproduce this also in Firefox 71 with NVDA alpha-19441,855bf207?
When I try your simple test case there is no error displayed in the log.

**Comment by jcsteh** [comment]
Yes, I can, but I had to tweak the test case slightly:
`data:text/html,<section aria-label"almen%C3%BCk" role="region">test`
Same underlying bug though.

**Comment by Adriani90** [comment]
Ok I can reproduce it now, thank Jamie for the modified simple test case.
I get slightly differen error than above as follows:

```
IO - inputCore.InputManager.executeGesture (00:11:12.926) - winInputHook (8800):
Input: kb(laptop):upArrow
ERROR - XMLFormatting.XMLTextParser.parse (00:11:12.950) - MainThread (1200):
XML: <control controlIdentifier_docHandle="263030" controlIdentifier_ID="-67108866" _startOfNode="1" _endOfNode="1" isBlock="1" isHidden="0" _childcount="1" _childcontrolcount="1" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_display="block" IAccessible2::attribute_explicit-name="true" IAccessible2::attribute_margin-bottom="8px" IAccessible2::attribute_margin-left="8px" IAccessible2::attribute_margin-right="8px" IAccessible2::attribute_margin-top="8px" IAccessible2::attribute_tag="body" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::state_1="1" IAccessible2::state_1024="1" IAccessible::role="15" IAccessible::state_1048576="1" IAccessible::state_4="1" IAccessible::state_64="1" alwaysReportName="true" description="" keyboardShortcut="" name="" ><control controlIdentifier_docHandle="263030" controlIdentifier_ID="-67108867" _startOfNode="1" _endOfNode="1" isBlock="1" isHidden="0" _childcount="1" _childcontrolcount="0" _indexInParent="0" _parentChildCount="1" IAccessible2::attribute_display="block" IAccessible2::attribute_formatting="block" IAccessible2::attribute_label"almenÃ¼k"="" IAccessible2::attribute_margin-bottom="0px" IAccessible2::attribute_margin-left="0px" IAccessible2::attribute_margin-right="0px" IAccessible2::attribute_margin-top="0px" IAccessible2::attribute_tag="section" IAccessible2::attribute_text-align="start" IAccessible2::attribute_text-indent="0px" IAccessible2::attribute_xml-roles="region" IAccessible2::state_1024="1" IAccessible2::state_4096="1" IAccessible::role="1060" description="" keyboardShortcut="" ><text _startOfNode="1" _endOfNode="1" isBlock="0" isHidden="0" _childcount="0" _childcontrolcount="0" _indexInParent="0" _parentChildCount="1" background-color="rgb(255, 255, 255)" color="rgb(0, 0, 0)" font-family="Times New Roman" font-size="12pt" font-style="normal" font-weight="400" ia2TextStartOffset="0" text-align="start" text-position="baseline" >test</text></control></control>
Traceback (most recent call last):
  File "XMLFormatting.pyc", line 69, in parse
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1147
```

I don't really know why the column is different in every error. Maybe it depends on screen resolution?

cc: @feerrenrut

**Comment by jcsteh** [comment]
The column number in the error will be different for each modified test
case, since the position of the problematic code changes. It should be the
same for the same test case on the same browser, though.

**Comment by Adriani90** [comment]
@SaschaCowley do you think it is suitable to label this as good for new dev?

**Comment by SaschaCowley** [comment]
I don't think so. This is probably going to require modifying the vbuf backends.
