### ISSUE TITLE
Reporting formatting on a cell with multiple colours fails in Excel 2013

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#7277]
Reporting formatting on a cell with multiple colours fails in Excel 2013. The cell contains black and red. Where the word 'red' is coloured red.

### Steps to reproduce:
- Using Excel 2013 open up [testCaseRedAndBlack.xlsx.txt](https://github.com/nvaccess/nvda/files/1070523/testCaseRedAndBlack.xlsx.txt) (after removing the .txt part of the filename)
- Move to cell A1 and press NVDA+F to report the formatting.
- Notice an error sound when enter is pressed.

### Expected behavior:
The formatting of the cell should be reported.

### Actual behavior:
An error sound, no formatting reported. The following log entry:

```
Input: kb(desktop):NVDA+f
ERROR - scriptHandler.executeScript (14:52:04.819):
error executing script: <bound method GlobalCommands.script_reportFormatting of <globalCommands.GlobalCommands object at 0x04D78B70>> with gesture u'NVDA+f'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 1295, in script_reportFormatting
  File "textInfos\offsets.pyc", line 392, in getTextWithFields
  File "NVDAObjects\window\excel.pyc", line 977, in _getFormatFieldAndOffsets
TypeError: int() argument must be a string or a number, not 'NoneType'
```

### System configuration:
NVDA version: next-14098,66f26bb2

NVDA Installed or portable: Installed

Windows version:
Windows 10 Version 1607 Build 14393.1198

Name and version of other software in use when reproducing the issue:
Microsoft office Excel 2013

**Comment by Adriani90** [comment]
This is also reproducible with NVDA 2019.1.1 and MS Excel 2016 / 365.

**Comment by Adriani90** [comment]
cc: @lukaszgo1
