### ISSUE TITLE
Split out global commands into distinct scripts

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7314]
For @dictationbridge, we want to support speech commands like "speak current line" and "spell current line"
This makes our code ugly, because we literally have to send "speakCurrentLine twice to spell it, and it is not as clean of code. I propose the following.

1. Split any script in globalCommands.GlobalCommands which looks at getScriptRepeatCount into multiple scripts as necesary, I.E. speakCurrentLine, spellCurrentLine, spellCurrentLinePhonetically.
2. Make an overarching script which dispatches behaviors based on the number of times its been called, I.e. reportCurrentLine would check and if the script has fired twice, would call into spellCurrentLine, etc.

**Comment by derekriemer** [comment]
For dictationbridge 1.0, this isn't happening. Marking as "goodForNewDev" for now in case anyone wants to stab at it.

**Comment by venkateshpotluri** [comment]
Hi,

I would like to start contributing to NVDA. As I am new to this project, wanted to start by trying to solve this issue.

Thanks, Venkatesh

**Comment by derekriemer** [comment]
let me know if you need any help.
Cheers

**Comment by venkateshpotluri** [comment]
Thanks a lot @derekriemer!

I am trying to compile by following the steps in the readme but I get this error when I run scons source

Traceback (most recent call last):
  File "scons.py", line 10, in <module>
    import SCons.Script
  File "C:\Users\<UserName>\code\NVDA\nvda\miscDeps\python\SCons\__init__.py", line 43, in <module>
    import SCons.compat
  File "C:\Users\<UserName>\code\NVDA\nvda\miscDeps\python\SCons\compat\__init__.py", line 90, in <module>
    import _scons_builtins
ModuleNotFoundError: No module named '_scons_builtins'

I did a git clone with the --recursive flag enabled and checked if the git submodules were present. Also, the module that the python interpreter says is missing is present.
I am on windows 10 enterprise and am using Python 3.6.0::Anakonda 4.3.0 (64-bit)

How do I fix this issue?
Thanks.

**Comment by derekriemer** [comment]
do you have python2 or python3, do you have scons installed as well?

**Comment by sudheesh001** [comment]
Hi @derekriemer We are using `python2` and ran into the following issue while setting this up. We installed `scons==2.4.1` from pip for this.

https://github.com/nvaccess/nvda/issues/7170#issuecomment-333460068

**Comment by derekriemer** [comment]
Try running `python scons.py source `
 from the nvda directory  NVDA includes its own scons (As noted in the readme).

**Comment by sudheesh001** [comment]
Hi @derekriemer This is the issue we face when running it via `python scons.py source`

```log
nvda>python scons.py source
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
MIDL.EXE /nologo /win32 /tlb build\x86\acrobatAccess.tlb /h build\x86\acrobatAccess.h /iid build\x86\acrobatAccess_i.c /proxy build\x86\acrobatAccess_p.c /dlldata build\x86\acrobatAccess_data.c build\x86\acrobatAccess.idl
Processing build\x86\acrobatAccess.idl
midl : command line error MIDL1005 : cannot find C preprocessor cl.exe
scons: *** [build\x86\acrobatAccess.tlb] Error 1005
scons: building terminated because of errors.
```

**Comment by derekriemer** [comment]
That suggests your visual studio is messed up.  Specifically, it cannot get at the actual c++ compiler. Do you have vs 2015? If not, @michaelDCurran is close to getting support for visual studio 2017 in, so it might just be worth waiting for it to hit master in a few weeks. If you do have vs2015, are you sure the c++ tools installed? The treeview on 2015 is weird. Hint: Look for a checkbox under each tree item with object navigation.

**Comment by bergmeister** [comment]
I have the same error as @sudheesh001  when trying to compile on a new VM with only VS 2017 on it although I even installed the additional C++ build tools to have `cl.exe` on the PATH. On my other dev box with VS2015 and VS2017 it compiles fine so there must still be some VS2015 dependency.

**Comment by derekriemer** [comment]
this now works for me actually

**Comment by derekriemer** [comment]
can you post your error?

**Comment by bergmeister** [comment]
@derekriemer Its exactly the same as your error. I am building on a fresh new Windows Server 2016 VM with VS 2017 only being installed. I ticked all C++ related options and even some backcompat options with VS2015.

**Comment by derekriemer** [comment]
@michaelDCurran

**Comment by bergmeister** [comment]
I tried today on a physical Windows 10 box and had no errors. Maybe it was a problem of the OS (Windows Server 2016) or it being a VM in Azure. I would normally think it could be the former but given that the AppVeyor image [Visual Studio 2017](https://www.appveyor.com/docs/build-environment/#operating-system) that you use is running on WinServer 2016 it might be the latter...

**Comment by lukaszgo1** [comment]
While it certainly can be useful in some situations I am wondering if instead of implementing it all at once wouldn't be better to do it incrementally when other changes to these scripts are made. @michaelDCurran  @feerrenrut, thoughts?
