### ISSUE TITLE
Unable to load the oneCore synthesizer

### ISSUE THREAD

**Issue by nikosdemetriou** [nvaccess/nvda#7553]
It is impossible to switch to the oneCore synthesizer from nvda's synthesizer settings dialogue.
When I choose oneCore synthesizer from the list and I press OK, a message comes up saying could not load the oneCore synthesizer and there is only an OK button to press in this dialogue.

I am using windows 10 with the latest updates and the latest nvda master snapshot.

All the information is included in the attached log.
Nikos
[nvda.txt](https://github.com/nvaccess/nvda/files/1270002/nvda.txt)

**Comment by josephsl** [comment]
Hi, oh great, newline problem… CC @MichaelDCurran

**Comment by zstanecic** [comment]
I cannot reproduce it on my system.

I have all voices wich i need.


W dniu 01.09.2017 o 18:16, Joseph Lee pisze:

**Comment by dannyakakong** [comment]
I also have the same issue on Windows 10 (build 17046), here is my log output:

```
WARNING - synthDriverHandler.SynthDriver.loadSettings (16:52:58.943):
Invalid voice: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_enGB_HazelM
ERROR - synthDriverHandler.setSynth (16:52:58.957):
setSynth
Traceback (most recent call last):
  File "synthDriverHandler.pyo", line 89, in setSynth
  File "synthDriverHandler.pyo", line 498, in loadSettings
  File "synthDriverHandler.pyo", line 36, in changeVoice
  File "speechDictHandler\__init__.pyo", line 128, in loadVoiceDict
KeyError: u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enGB_HazelM'
INFO - synthDriverHandler.setSynth (16:52:58.963):
Loaded synthDriver sapi5
```

**Comment by josephsl** [comment]
Hi, this is commonly caused by the fact that the voice you used before isn’t there anymore. Thanks.

**Comment by mohdshara** [comment]
@josephsl Other than re-installing the missing voice, is there anything that can be done to make the driver fall back to whatever voice currently installed?

**Comment by feerrenrut** [comment]
We could potentially check if the voice is available (see `def setSynth` of `source/synthDriverHandler.py`) and if not choose an arbitrary voice (eg the first available).

The ramifications of this is that from the users perspective, the voice will no longer be what they are familiar with, and they will not know why. Though, this does not seem worse than the synth changing with no explanation.

**Comment by feerrenrut** [comment]
Setting this as priority 2. It looks like it should be fairly quick to fix.

**Comment by michaelDCurran** [comment]
Anyone experiencing this issue: please test the following try build of NVDA, and switch to windows Onecore Speech to see if it works now:
https://ci.appveyor.com/api/buildjobs/63rtodmkp2xckm91/artifacts/output%2Fnvda_snapshot_try-i7553-14859%2Ca1e2a6d3.exe
