### ISSUE TITLE
next 14510,580365a5 build, installation fails

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#7654]
Hello,
I received the following error when I apply the latest next build:

```
DEBUGWARNING - RPC process 6076 (nvda_slave.exe) (12:03:27.555):
Python warning:
C:\Users\andre\AppData\Local\Temp\nslCE2F.tmp\app\library.zip\configobj.py:28: DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
ERROR - RPC process 6076 (nvda_slave.exe) (12:03:27.631):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 42, in main
  File "installer.pyc", line 416, in install
  File "installer.pyc", line 169, in removeOldProgramFiles
  File "installer.pyc", line 366, in tryRemoveFile
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 13: ordinal not in range(128)
ERROR - gui.installerGui.doInstall (12:03:27.663):
Installation failed: 1
```

**Comment by ehollig** [comment]
I am assuming this works for you now as you closed this issue?

**Comment by Andre9642** [comment]
> I am assuming this works for you now as you closed this issue?

Exactly, I tested with the build `next-14511,339707cd`. This problem is no longer present for me! :) Sorry, I should have said so.
