### ISSUE TITLE
slowness after closing outlook

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7796]
After viewing an appointment in the outlook calendar and closing the software, and opening the menu start nvda is locked for about 30 seconds before starting to read the start menu again.
In the log it would point out a locking of the nvda core.
### Steps to reproduce:

1. Open Outlook.
1. create an appointment.
1. Press ctrl + 2 to go to the calendar.
1. Walk with the right and left arrows until nvda announces the selected day and the appointment in the calendar.
1. Press ctrl + 1 to go back to the inbox.
1. Press alt + f4 to exit Outlook.
1. Immediately press the start menu.
1. Walk with the arrow keys.

### Expected behavior:
The nvda should read the start menu.

### Actual behavior:
The nvda is muted for about 30 seconds, and then returns to work properly.

### System configuration:
NVDA version: next-14660
NVDA Installed or portable: instaled

Other information:
If the problem does not occur in the first test, please try to reproduce for some time, the problem with me is repeated for several times, but it does not occur in 100% of the times.
Sometimes you just have to read an email and you do not have to see an appointment in the calendar.

Windows version: Windows 10 Version 1609 Build 16299.64 64bits
Name and version of other software in use when reproducing the issue:
outlook 2016 16.0.8625.2132 32bits

### Other questions:

Does the issue still occur after restarting your PC? yes

Have you tried any other versions of NVDA?
I've seen this problem in some builds next to nvda before, but I thought I could reproduce this more reliably now.

Follow the log:
```
Input: kb(laptop):alt+f4
DEBUGWARNING - watchdog._watcher (11:02:42.769):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 200, in <module>
  File "core.pyc", line 468, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 438, in Notify
  File "IAccessibleHandler.pyc", line 894, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 78, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 385, in findOverlayClasses
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 776, in _get_IAccessibleRole
  File "comtypes\__init__.pyc", line 795, in __call__

DEBUGWARNING - core.CorePump.Notify (11:02:42.831):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 438, in Notify
  File "IAccessibleHandler.pyc", line 894, in pumpAll
  File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 529, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 43, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 78, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 385, in findOverlayClasses
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
IO - inputCore.InputManager.executeGesture (11:02:48.404):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (11:03:05.806):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - speech.speak (11:03:06.315):
Speaking [u'Iniciar  janela']
IO - speech.speak (11:03:06.319):
Speaking [u'Todos os aplicativos  lista']
IO - speech.speak (11:03:06.325):
Speaking [u'Adicionados recentemente  grupo']
IO - inputCore.InputManager.executeGesture (11:03:12.349):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (11:03:12.690):
Developer info for navigator object:
name: u'Adicionados recentemente'
role: ROLE_GROUPING
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.UIA.UIA object at 0x078C4B10>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (60, 239, 307, 44)
value: None
appModule: <'shellexperiencehost' (appName u'shellexperiencehost', process ID 8984) at address 7876bb0>
appModule.productName: u'Microsoft\xae Windows\xae Operating System'
appModule.productVersion: u'10.0.16299.15'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 65960
windowClassName: u'Windows.UI.Core.CoreWindow'
windowControlID: 0
windowStyle: -1811939328
windowThreadID: 2024
windowText: u'Iniciar'
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x26f76c8 at 7835e90>
UIA automationID: RecentList
UIA frameworkID: XAML
UIA runtimeID: (42, 65960, 3, 19)
UIA providerDescription: [pid:8984,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:Windows.UI.Xaml.dll)]
UIA className: ListViewItem
```

**Comment by Adriani90** [comment]
@fernando-jose-silva we have closed several issues which showed this behavior in the past because users were not having this problem anymore. Can you still see this problem occuring?

**Comment by fernando-jose-silva** [comment]
I could not reproduce the problems any more.
All new:
nvda 17110
office 2019
windows 10 18362
Thank you.

**Comment by Adriani90** [comment]
Closing as works for me.
