### ISSUE TITLE
Errors in log when trying to update NVDA on Windows 7 machine.

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#7830]
Issue raised on behalf of @Brian1Gaff 

### Steps to reproduce:
The steps to reproduce are unknown. Description of what happened:

> I found this with my current master copy when I did some updates to add ons
then went to general settings and tried to hit the button to copy the
settings so they would be used at log in. it just bleeped for ever, on doing
an alt tab I found a retry and cancell error hidden behind the updating
page.
Cancel gets you out then it says it could not copy the settings. However It
could under some circumstances, presumably, need to do this process when
updating, and then the same problem would happen one assumes.

```
IO - inputCore.InputManager.executeGesture (07:28:38.868):
Input: kb(desktop):tab
IO - speech.speak (07:28:38.904):
Speaking [LangChangeCommand ('en_GB'), u'Cancel  button']
IO - inputCore.InputManager.executeGesture (07:28:40.625):
Input: kb(desktop):shift+tab
IO - speech.speak (07:28:40.663):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
IO - inputCore.InputManager.executeGesture (07:28:42.131):
Input: kb(desktop):space
IO - speech._speakSpellingGen (07:28:42.135):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (07:28:42.135):
Adding generator 3276
IO - speech.speak (07:28:42.137):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (07:28:42.154):
generator 3276 finished
DEBUGWARNING - gui.ExecAndPump.run (07:28:42.240):
task had errors
Traceback (most recent call last):
  File "gui\__init__.pyc", line 824, in run
  File "config\__init__.pyc", line 219, in setSystemConfigToCurrentConfig
  File "config\__init__.pyc", line 231, in _setSystemConfig
  File "installer.pyc", line 348, in tryRemoveFile
RetriableFailure: Failed to rename file C:\Program Files
(x86)\NVDA\systemConfig before  remove
DEBUGWARNING - gui.settingsDialogs.GeneralSettingsDialog.onCopySettings
(07:28:42.344):
Error when copying settings to system config
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 235, in onCopySettings
  File "gui\__init__.pyc", line 820, in __init__
RetriableFailure: Failed to rename file C:\Program Files
(x86)\NVDA\systemConfig before  remove
IO - speech.speak (07:28:42.387):
Speaking [LangChangeCommand ('en_GB'), u'Error Copying  dialog  Unable to
copy a file. Perhaps it is currently being used by another process or you
have run out of disc space on the drive you are copying to.']
IO - speech.speak (07:28:42.391):
Speaking [LangChangeCommand ('en_GB'), u'Retry  button  Alt+r']
```

**Comment by feerrenrut** [comment]
Further comment:
> I did exactly what the  reporter did, went off after the error and then came
back and tried it again and of course it worked this time.
 Could this be linked to the same issue we had on updates with the folder
deletes before, and Mick somehow made them not cause the hard error?

**Comment by feerrenrut** [comment]
A previous log while updating next versions:
```
Speaking [LangChangeCommand ('en_GB'), u'Desktop  list']
IO - speech.speak (19:56:27.913):
Speaking [LangChangeCommand ('en_GB'), u'Computer  2 of 63']
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:27.951):
Python warning:
C:\Users\Brian\AppData\Local\Temp\nsl993.tmp\app\library.zip\configobj.py:28:
DeprecationWarning: The compiler package is deprecated and removed in Python
3.x.
IO - speech.speak (19:56:28.025):
Speaking [LangChangeCommand ('en_GB'), u'Updating NVDA  dialog  Please wait
while your previous installation of NVDA is being updated.']
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:28.036):
installer.tryCopyFile:
Unable to copy
\\?\C:\Users\Brian\AppData\Local\Temp\nsl993.tmp\app\nvda_eoaProxy.exe,
error 32
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:28.040):
installer.tryCopyFile:
Unable to copy
\\?\C:\Users\Brian\AppData\Local\Temp\nsl993.tmp\app\python27.dll, error 32
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:28.367):
installer.tryCopyFile:
Unable to copy
\\?\C:\Users\Brian\AppData\Local\Temp\nsl993.tmp\app\_ctypes.pyd, error 32
IO - tones.beep (19:56:28.875):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
IO - speech.speak (19:56:28.877):
Speaking [LangChangeCommand ('en_GB'), u'Please wait']
IO - tones.beep (19:56:28.907):
Beep at pitch 110.0, for 40 ms, left volume 50, right volume 50
IO - speech.speak (19:56:28.911):
Speaking [LangChangeCommand ('en_GB'), u'0 percent']
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:29.517):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\IAccessible2proxy.dll'
IO - tones.beep (19:56:29.888):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:30.519):
installer.tryRemoveFile:
Failed to delete file C:\Program Files
(x86)\NVDA\lib\next-14675,14728b95\tmpgewxzy, marking for delete on reboot
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:30.523):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\ISimpleDOM.dll'
IO - tones.beep (19:56:30.904):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:31.526):
installer.tryRemoveFile:
Failed to delete file C:\Program Files
(x86)\NVDA\lib\next-14675,14728b95\tmpgttfnl, marking for delete on reboot
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:31.532):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\minHook.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:31.535):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\nvdaHelperLocal.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:31.538):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\nvdaHelperLocalWin10.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:31.540):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\nvdaHelperRemote.dll'
IO - inputCore.InputManager.executeGesture (19:56:31.740):
Input: kb(desktop):alt+tab
IO - tones.beep (19:56:31.920):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:32.543):
installer.tryRemoveFile:
Failed to delete file C:\Program Files
(x86)\NVDA\lib\next-14675,14728b95\tmpnr9hzx, marking for delete on reboot
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.546):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\VBufBackend_adobeAcrobat.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.549):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\VBufBackend_adobeFlash.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.552):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\VBufBackend_gecko_ia2.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.555):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\VBufBackend_lotusNotesRichText.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.559):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\VBufBackend_mshtml.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.563):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95\\VBufBackend_webKit.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.568):
installer.removeOldLibFiles:
Skipping current install lib path: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14685,bc898bdc'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.569):
installer.removeOldLibFiles:
Removing old lib directory: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14675,14728b95'
WARNING - RPC process 3596 (nvda_slave.exe) (19:56:32.572):
installer.removeOldLibFiles:
Failed to remove a directory no longer needed. This can be manually removed
after a reboot or the  installer will try removing it again next time.
Directory: u'C:\\Program Files (x86)\\NVDA\\lib\\next-14675,14728b95'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.575):
installer.removeOldLibFiles:
Removing old lib directory: u'C:\\Program Files
(x86)\\NVDA\\lib\\next-14685,bc898bdc'
WARNING - RPC process 3596 (nvda_slave.exe) (19:56:32.576):
installer.removeOldLibFiles:
Failed to remove a directory no longer needed. This can be manually removed
after a reboot or the  installer will try removing it again next time.
Directory: u'C:\\Program Files (x86)\\NVDA\\lib\\next-14685,bc898bdc'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:32.582):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\IAccessible2proxy.dll'
IO - tones.beep (19:56:32.930):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:33.585):
installer.tryRemoveFile:
Failed to delete file C:\Program Files
(x86)\NVDA\lib64\next-14675,14728b95\tmplofbt0, marking for delete on reboot
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:33.588):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\ISimpleDOM.dll'
IO - tones.beep (19:56:33.944):
Beep at pitch 440, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - RPC process 3596 (nvda_slave.exe) (19:56:34.591):
installer.tryRemoveFile:
Failed to delete file C:\Program Files
(x86)\NVDA\lib64\next-14675,14728b95\tmpvtyzzh, marking for delete on reboot
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.594):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\minHook.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.596):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\nvdaHelperRemote.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.599):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\nvdaHelperRemoteLoader.exe'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.604):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\VBufBackend_adobeAcrobat.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.608):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\VBufBackend_adobeFlash.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.611):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\VBufBackend_gecko_ia2.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.614):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\VBufBackend_lotusNotesRichText.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.617):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\VBufBackend_mshtml.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.619):
installer.removeOldLibFiles:
Removing old lib file: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95\\VBufBackend_webKit.dll'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.624):
installer.removeOldLibFiles:
Skipping current install lib path: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14685,bc898bdc'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.625):
installer.removeOldLibFiles:
Removing old lib directory: u'C:\\Program Files
(x86)\\NVDA\\lib64\\master-14676,f2bf8884'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.627):
installer.removeOldLibFiles:
Removing old lib directory: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14675,14728b95'
WARNING - RPC process 3596 (nvda_slave.exe) (19:56:34.628):
installer.removeOldLibFiles:
Failed to remove a directory no longer needed. This can be manually removed
after a reboot or the  installer will try removing it again next time.
Directory: u'C:\\Program Files (x86)\\NVDA\\lib64\\next-14675,14728b95'
DEBUG - RPC process 3596 (nvda_slave.exe) (19:56:34.628):
installer.removeOldLibFiles:
Removing old lib directory: u'C:\\Program Files
(x86)\\NVDA\\lib64\\next-14685,bc898bdc'
WARNING - RPC process 3596 (nvda_slave.exe) (19:56:34.631):
installer.removeOldLibFiles:
Failed to remove a directory no longer needed. This can be manually removed
after a reboot or the  installer will try removing it again next time.
Directory: u'C:\\Program Files (x86)\\NVDA\\lib64\\next-14685,bc898bdc'
IO - tones.beep (19:56:34.640):
Beep at pitch 1760, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole
(19:56:34.776):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None,
None, 0, None))
IO - speech.speak (19:56:34.802):
Speaking [LangChangeCommand ('en_GB'), u'Desktop  list']
IO - speech.speak (19:56:34.821):
Speaking [LangChangeCommand ('en_GB'), u'Computer  2 of 63']
IO - inputCore.InputManager.executeGesture (19:56:34.931):
Input: kb(desktop):alt+tab
DEBUGWARNING - RPC process 4836 (nvda_update_7wz51m.exe) (19:56:35.924):
Thread 5028, build\x86\remote\ia2Support.cpp,
IA2Support_inProcess_terminate, 152:
WaitForMultipleObjects returned 258
```

**Comment by Brian1Gaff** [comment]
The installed copy of Master just failed to restart in the usual  way here 
this morning, but cancelling the error and then manually rebooting made it 
work.
 Its weird but I suspect we will no know exactly how many fall prey to it 
till the release is installed by a lot of people.

Brian

**Comment by feerrenrut** [comment]
My guess is that there is some other software locking these files on your machine. I know you use several computers, does this behaviour happen across all of them?
If there is some anti-virus or other protective software on the computers where this occurs, could you try to disable the software?

Rather than guessing at the software that is accessing these files, here is a guide (for perforce, but the principles still apply to nvda) to tracking this down. 
http://answers.perforce.com/articles/KB/3035

We may have to look into programatically reporting what process has a handle on these files, we could use a tool such as [handle](https://docs.microsoft.com/en-gb/sysinternals/downloads/handle) for this.

**Comment by feerrenrut** [comment]
@Brian1Gaff Have you had any luck following up on this? Do you still get these errors? Could you manually inspect `C:\\Program Files
(x86)\\NVDA\\lib64\\` and let us know what is in there?

**Comment by Brian1Gaff** [comment]
Its been a while since it happened last, and as mentioned originally, since 
nobody but one other ever saw this, I'm struggling to figure out the 
conditions to make it happen. I was hoping it might have gone away, but will 
report back if it resurfaces.
 Brian

**Comment by Adriani90** [comment]
@Brian1Gaff did this still happen during last months? Or is this issue no occuring anymore?

**Comment by Adriani90** [comment]
@feerrenrut Have you seen this issue in the last versions of NVDA?
Maybe @hozosh or @lukaszgo1 are able to test if this still occurs in Windows 7?

**Comment by hozosch** [comment]
Sorry, I can't quite understand this description.

**Comment by lukaszgo1** [comment]
I haven't experienced anything like this on Windows 7. Given the fact that @Brian1Gaff isn't responding I vote for closing.

**Comment by Adriani90** [comment]
Closing as works for me.
