### ISSUE TITLE
Unable to read equations in braille

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#7878]
Since several next versions, I am not able read equations in braille anymore (speech is OK).
Take, for example, this page -> https://math.stackexchange.com/questions/2581244/show-that-a4b4c42a2b22b2c22a2c2
I receive the following error when I move on an equation:

```
ERROR - queueHandler.flushQueue (00:42:34.493):
Error in func _loadBufferDone from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 442, in _loadBufferDone
  File "browseMode.pyc", line 1128, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1433, in event_gainFocus
  File "browseMode.pyc", line 1191, in _set_selection
  File "cursorManager.pyc", line 109, in _set_selection
  File "braille.pyc", line 1753, in handleCaretMove
  File "braille.pyc", line 1718, in _doNewObject
  File "braille.pyc", line 1454, in getFocusRegions
  File "braille.pyc", line 920, in update
  File "braille.pyc", line 818, in _addTextWithFields
  File "browseMode.pyc", line 1074, in getControlFieldBraille
  File "textInfos\__init__.pyc", line 442, in getControlFieldBraille
  File "braille.pyc", line 665, in getControlFieldBraille
  File "mathPres\mathPlayer.pyc", line 142, in getBrailleForMathMl
COMError: (-2147467259, 'Erreur non sp\xe9cifi\xe9e', (None, None, None, 0, None))
```

Tested with Firefox and Chrome, all addons enabled and disabled.

Here a full log:

```
INFO - __main__ (00:42:23.770):
Starting NVDA
INFO - core.main (00:42:24.224):
Config dir: C:\Users\andre\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (00:42:24.226):
Loading config: C:\Users\andre\AppData\Roaming\nvda\nvda.ini
INFO - config.ConfigManager._loadConfig (00:42:24.256):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{u'schemaVersion': u'2', u'upgrade': {}, u'update': {u'autoCheck': u'True'}, u'general': {u'language': u'fr', u'saveConfigurationOnExit': u'True', u'askToExit': u'True', u'playStartAndExitSounds': u'True', u'loggingLevel': u'DEBUG', u'showWelcomeDialogAtStartup': u'False'}, u'speech': {u'synth': u'eloquence', u'outputDevice': u'Mappeur de sons Microsoft', u'symbolLevel': u'100', u'autoLanguageSwitching': u'False', u'autoDialectSwitching': u'False', u'espeak': {u'voice': u'fr', u'variant': u'max', u'rate': u'30', u'pitch': u'40', u'inflection': u'75', u'volume': u'100'}, u'eloquence': {u'voice': u'196608', u'variant': u'1', u'rate': u'69', u'pitch': u'64', u'inflection': u'35', u'volume': u'100', u'internalDicTags': u'True', u'capPitchChange': u'0', u'sayCapForCapitals': u'True'}, u'eloq47': {u'voice': u'65536', u'variant': u'1', u'pitch': u'65', u'inflection': u'30', u'volume': u'92', u'rgh': u'0', u'bth': u'0'}, u'speechPlayerInEspeak': {u'voice': u'fr', u'variant': u'edward', u'rate': u'30', u'pitch': u'40', u'inflection': u'75', u'volume': u'100'}, u'espeak_randomize_words': {u'voice': u'fr', u'variant': u'max', u'rate': u'30', u'pitch': u'40', u'inflection': u'75', u'volume': u'100'}, u'mbrolaInEspeak': {u'voice': u'mb-fr1', u'variant': u'none', u'rate': u'30', u'pitch': u'40', u'inflection': u'75', u'volume': u'100'}, u'espeak_piglattin': {u'voice': u'fr', u'variant': u'max', u'rate': u'30', u'pitch': u'40', u'inflection': u'75', u'volume': u'100'}, u'oneCore': {u'voice': u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_frFR_HortenseM', u'volume': u'100'}, u'silence': {}}, u'braille': {u'display': u'baum', u'translationTable': u'fr-bfu-comp8.utb', u'inputTable': u'fr-bfu-comp8.utb', u'tetherTo': u'focus', u'wordWrap': u'False', u'focusContextPresentation': u'fill', u'noMessageTimeout': u'False', u'messageTimeout': u'3', u'cursorBlink': u'True', u'showCursor': u'True', u'outputPass1Only': u'False', u'autoTether': u'True', u'readByParagraph': u'False', u'cursorShapeFocus': u'192', u'expandAtCursor': u'False', u'noBraille': {u'port': u''}, u'baum': {u'port': u'auto'}, u'erbnvda': {}, u'brailliantB': {u'port': u''}, u'brailliantbB': {u'port': u''}, u'brailliantb': {u'port': u''}, u'alvaBC6': {u'port': u''}, u'brailleNote': {u'port': u''}, u'papenmeier_serial': {u'port': u''}, u'ecoBraille': {u'port': u''}, u'16': {u'port': u''}, u'2': {u'port': u''}, u'eurobraille': {u'port': u'auto'}, u'auto': {}, u'handyTech': {u'port': u'COM3'}}, u'keyboard': {u'keyboardLayout': u'laptop', u'useCapsLockAsNVDAModifierKey': u'True', u'speakTypedCharacters': u'False', u'speakTypedWords': u'True', u'speakCommandKeys': u'False', u'speechInterruptForCharacters': u'True', u'speechInterruptForEnter': u'True'}, u'presentation': {u'reportDynamicContentChanges': u'True', u'reportObjectDescriptions': u'True', u'progressBarUpdates': {u'progressBarOutputMode': u'speak'}}, u'documentFormatting': {u'autoLanguageSwitching': u'False'}, u'reviewCursor': {u'followCaret': u'True', u'followMouse': u'True', u'simpleReviewMode': u'False', u'followFocus': u'True'}, u'audio': {u'audioDuckingMode': u'0'}, u'uwpOcr': {u'language': u'fr-FR'}, u'wintenApps': {u'updateCheckTime': u'1514908886'}, u'audioThemes': {u'speakRole': u'True'}, u'reportSymbols': {u'speakTypedSymbols': u'True', u'speakTypedSpaces': u'True'}, u'mouse': {u'enableMouseTracking': u'True'}}
DEBUG - core.main (00:42:24.292):
setting language to fr
INFO - core.main (00:42:24.303):
NVDA version next-14753,cae9ca42
INFO - core.main (00:42:24.303):
Using Windows version 10.0.16299 workstation
INFO - core.main (00:42:24.303):
Using Python version 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
INFO - core.main (00:42:24.303):
Using comtypes version 1.1.3
DEBUG - core.main (00:42:24.309):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.312):
Listing add-ons from C:\Users\andre\AppData\Roaming\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.312):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\audacity
DEBUG - addonHandler.Addon.__init__ (00:42:24.312):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\audacity\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.312):
Found add-on audacity
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.313):
Disabling add-on audacity
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.313):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\AudioThemes3D
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.315):
Found add-on AudioThemes3D
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.315):
Disabling add-on AudioThemes3D
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.315):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\BrailleDebug
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.316):
Found add-on BrailleDebug
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.316):
Disabling add-on BrailleDebug
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.316):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\BrailleExtender
DEBUG - addonHandler.Addon.__init__ (00:42:24.318):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\BrailleExtender\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.318):
Found add-on BrailleExtender
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.319):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\consoleTimer
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.321):
Found add-on consoleTimer
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.321):
Disabling add-on consoleTimer
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.321):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\dropbox
DEBUG - addonHandler.Addon.__init__ (00:42:24.322):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\dropbox\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.322):
Found add-on dropbox
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.322):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\Eloquence
DEBUG - addonHandler.Addon.__init__ (00:42:24.322):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\Eloquence\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.323):
Found add-on Eloquence
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.323):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\emoticons
DEBUG - addonHandler.Addon.__init__ (00:42:24.323):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\emoticons\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.325):
Found add-on emoticons
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.325):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\enhancedTouchGestures
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.325):
Found add-on enhancedTouchGestures
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.325):
Disabling add-on enhancedTouchGestures
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.325):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\eurobrailleDriver
DEBUG - addonHandler.Addon.__init__ (00:42:24.326):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\eurobrailleDriver\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.328):
Found add-on eurobrailleDriver
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.328):
Disabling add-on eurobrailleDriver
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.328):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\fast espeak
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.328):
Found add-on fast espeak
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.329):
Disabling add-on fast espeak
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.329):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\goldenCursor
DEBUG - addonHandler.Addon.__init__ (00:42:24.329):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\goldenCursor\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.331):
Found add-on goldenCursor
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.331):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\maxiCalc
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.332):
Found add-on maxiCalc
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.332):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\Mozilla
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.334):
Found add-on Mozilla
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.334):
Disabling add-on Mozilla
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.334):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\NotepadPlusPlus
DEBUG - addonHandler.Addon.__init__ (00:42:24.334):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\NotepadPlusPlus\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.335):
Found add-on NotepadPlusPlus
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.335):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\objInspector
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.335):
Found add-on objInspector
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.336):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\objPad
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.338):
Found add-on objPad
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.338):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\pcKbBrl
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.338):
Found add-on pcKbBrl
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.338):
Disabling add-on pcKbBrl
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.338):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\pingCheck
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.339):
Found add-on pingCheck
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.341):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\rapidSettings
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.342):
Found add-on rapidSettings
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.342):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\readFeeds
DEBUG - addonHandler.Addon.__init__ (00:42:24.342):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\readFeeds\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.342):
Found add-on readFeeds
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.344):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\remote
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.345):
Found add-on remote
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.345):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\reportSymbols
DEBUG - addonHandler.Addon.__init__ (00:42:24.345):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\reportSymbols\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.345):
Found add-on reportSymbols
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.346):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\resourceMonitor
DEBUG - addonHandler.Addon.__init__ (00:42:24.346):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\resourceMonitor\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.348):
Found add-on resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.348):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\speechHistory
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.348):
Found add-on speechHistory
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.348):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\speechPlayerInEspeak
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.349):
Found add-on speechPlayerInEspeak
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.349):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\TeamTalk
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.351):
Found add-on TeamTalk
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.351):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\virtualRevision
DEBUG - addonHandler.Addon.__init__ (00:42:24.351):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\virtualRevision\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.351):
Found add-on virtualRevision
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.355):
Loading add-on from C:\Users\andre\AppData\Roaming\nvda\addons\wintenApps
DEBUG - addonHandler.Addon.__init__ (00:42:24.355):
Using manifest translation from C:\Users\andre\AppData\Roaming\nvda\addons\wintenApps\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (00:42:24.355):
Found add-on wintenApps
INFO - core.main (00:42:24.355):
Add-ons are disabled. Restart NVDA to enable them.
DEBUG - core.main (00:42:24.532):
Initializing appModule Handler
DEBUG - core.main (00:42:24.532):
Initializing NVDAHelper
DEBUG - core.main (00:42:24.578):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (00:42:24.578):
Loading speech dictionary 'C:\Users\andre\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (00:42:24.584):
64 loaded records.
DEBUG - speechDictHandler.SpeechDict.load (00:42:24.584):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (00:42:24.585):
3 loaded records.
DEBUG - core.main (00:42:24.585):
Initializing speech
ERROR - synthDriverHandler.setSynth (00:42:24.585):
setSynth
Traceback (most recent call last):
  File "synthDriverHandler.pyc", line 87, in setSynth
  File "synthDriverHandler.pyc", line 39, in _getSynthDriver
ImportError: No module named eloquence
INFO - synthDrivers.espeak.SynthDriver.__init__ (00:42:24.631):
Using eSpeak NG version 1.49.1 dev
DEBUG - speechDictHandler.SpeechDict.load (00:42:24.684):
Loading speech dictionary 'C:\Users\andre\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-French (France).dic'...
DEBUG - speechDictHandler.SpeechDict.load (00:42:24.684):
file 'C:\Users\andre\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-French (France).dic' not found.
INFO - synthDriverHandler.setSynth (00:42:24.684):
Loaded synthDriver espeak
INFO - core.main (00:42:24.684):
Using wx version 3.0.2.0 msw (classic)
DEBUG - core.main (00:42:24.687):
Initializing braille input
INFO - brailleInput.initialize (00:42:24.687):
Braille input initialized
DEBUG - core.main (00:42:24.687):
Initializing braille
INFO - braille.initialize (00:42:24.687):
Using liblouis version 3.3.0
INFO - brailleDisplayDrivers.baum.BrailleDisplayDriver.__init__ (00:42:24.710):
Found VarioUltra40 connected via USB HID (\\?\hid#vid_0904&pid_6102&mi_00#7&40b644d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
INFO - braille.BrailleHandler.setDisplayByName (00:42:24.710):
Loaded braille display driver baum, current display has 40 cells.
DEBUG - core.main (00:42:24.710):
Initializing displayModel
DEBUG - core.main (00:42:24.711):
Initializing GUI
DEBUGWARNING - touchHandler.touchSupported (00:42:24.733):
No touch devices found
DEBUG - NVDAObjects.NVDAObject._get_placeholder (00:42:24.752):
Potential unimplemented child class: <NVDAObjects.window.Desktop object at 0x0708EED0>
IO - braille.BrailleBuffer.update (00:42:24.759):
Braille regions text: [u'Bureau fen']
IO - braille.BrailleHandler.update (00:42:24.759):
Braille window dots: 127 136 1235 15 1 136 - 124 15 1345
DEBUG - core.main (00:42:24.759):
initializing Java Access Bridge support
DEBUG - core.main (00:42:24.835):
Initializing winConsole support
DEBUG - core.main (00:42:24.835):
Initializing UIA support
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (00:42:24.838):
UIAutomation: IUIAutomation3
DEBUG - core.main (00:42:26.252):
Initializing IAccessible support
DEBUG - core.main (00:42:26.253):
Initializing input core
DEBUG - core.main (00:42:26.257):
Initializing keyboard handler
DEBUG - core.main (00:42:26.259):
initializing mouse handler
DEBUG - core.main (00:42:26.302):
Initializing touchHandler
DEBUGWARNING - touchHandler.touchSupported (00:42:26.302):
No touch devices found
DEBUG - core.main (00:42:26.302):
Initializing global plugin handler
IO - braille.BrailleBuffer.update (00:42:26.303):
Braille regions text: [u'NVDA d\xe9marr\xe9']
IO - braille.BrailleHandler.update (00:42:26.303):
Braille window dots: 13457 12367 1457 17 - 145 123456 134 1 1235 1235 123456
DEBUG - core.main (00:42:26.306):
Initializing core pump
DEBUG - core.main (00:42:26.306):
Initializing watchdog
DEBUG - core.main (00:42:26.308):
initializing updateCheck
INFO - core.main (00:42:26.308):
NVDA initialized
DEBUG - core.main (00:42:26.308):
entering wx application main loop
DEBUG - treeInterceptorHandler.update (00:42:26.463):
Adding new treeInterceptor to runningTable: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x07021EB0>
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.464):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.467):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.470):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.473):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.476):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.477):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.480):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:42:26.483):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
IO - speech.speak (00:42:26.490):
Speaking [u'algebra precalculus - Show that: $a^4+b^4+c^4<2a^2b^2+2b^2c^2+2a^2c^2$ - Mathematics Stack Exchange - Firefox Nightly']
IO - speech.speak (00:42:26.546):
Speaking [u'algebra precalculus - Show that: $a^4+b^4+c^4<2a^2b^2+2b^2c^2+2a^2c^2$ - Mathematics Stack Exchange  document']
IO - speech.speak (00:42:26.552):
Speaking [u'Show that: a4+b4+c4<2a2b2+2b2c2+2a2c2  titre']
IO - braille.BrailleHandler.update (00:42:29.305):
Braille window dots: 127 136 1235 15 1 136 - 124 15 1345
IO - inputCore.InputManager.executeGesture (00:42:31.039):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (00:42:32.411):
Input: kb(laptop):tab
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (00:42:32.490):
accRole failed: (-2147024809, 'Param\xe8tre incorrect.', (None, None, None, 0, None))
IO - speech.speak (00:42:33.509):
Speaking [u'Chargement du document...']
IO - braille.BrailleBuffer.update (00:42:33.510):
Braille regions text: [u'Chargement du document...']
IO - braille.BrailleHandler.update (00:42:33.510):
Braille window dots: 147 125 1 1235 1245 15 134 15 1345 2345 - 145 136 - 145 135 14 136 134 15 1345 2345 256 256 256
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (00:42:33.648):
Buffer load took 1.134 sec, 6292 chars
IO - speech.speak (00:42:34.269):
Speaking [u'cliquable', BreakCommand(time=94), u'a ', BreakCommand(time=75), u'\xe0 la puissance ', BreakCommand(time=75), u'fourth ', BreakCommand(time=141), u'pluce ', BreakCommand(time=141), u'b ', BreakCommand(time=75), u'\xe0 la puissance ', BreakCommand(time=75), u'fourth ', BreakCommand(time=141), u'pluce ', BreakCommand(time=141), u'c ', BreakCommand(time=75), u'\xe0 la puissance ', BreakCommand(time=75), u'fourth ', BreakCommand(time=565), u'inf\xe9rieur \xe0 ', BreakCommand(time=942), u'2 ', BreakCommand(time=141), u'a ', u'au carr\xe9 ', BreakCommand(time=226), u'b ', u'au carr\xe9 ', BreakCommand(time=367), u'pluce ', BreakCommand(time=367), u'2 ', BreakCommand(time=141), u'b ', u'au carr\xe9 ', BreakCommand(time=226), u'c ', u'au carr\xe9 ', BreakCommand(time=367), u'pluce ', BreakCommand(time=367), u'2 ', BreakCommand(time=141), u'a ', u'au carr\xe9 ', BreakCommand(time=226), u'c ', u'au carr\xe9 ', u'math\xe9matique', u'visit\xe9  lien', u'titre  niveau 1']
ERROR - queueHandler.flushQueue (00:42:34.493):
Error in func _loadBufferDone from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 442, in _loadBufferDone
  File "browseMode.pyc", line 1128, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1433, in event_gainFocus
  File "browseMode.pyc", line 1191, in _set_selection
  File "cursorManager.pyc", line 109, in _set_selection
  File "braille.pyc", line 1753, in handleCaretMove
  File "braille.pyc", line 1718, in _doNewObject
  File "braille.pyc", line 1454, in getFocusRegions
  File "braille.pyc", line 920, in update
  File "braille.pyc", line 818, in _addTextWithFields
  File "browseMode.pyc", line 1074, in getControlFieldBraille
  File "textInfos\__init__.pyc", line 442, in getControlFieldBraille
  File "braille.pyc", line 665, in getControlFieldBraille
  File "mathPres\mathPlayer.pyc", line 142, in getBrailleForMathMl
COMError: (-2147467259, 'Erreur non sp\xe9cifi\xe9e', (None, None, None, 0, None))
IO - braille.BrailleHandler.update (00:42:36.507):
Braille window dots: 
IO - inputCore.InputManager.executeGesture (00:42:37.443):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (00:42:37.621):
Developer info for navigator object:
name: None
role: ROLE_EQUATION
states: STATE_OFFSCREEN
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.Dynamic_MathMozillaIAccessible object at 0x072A00F0>
Python class mro: (<class 'NVDAObjects.Dynamic_MathMozillaIAccessible'>, <class 'NVDAObjects.IAccessible.ia2Web.Math'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (325, 369, 494, 31)
value: None
appModule: <'firefox' (appName u'firefox', process ID 16204) at address 71ac210>
appModule.productName: u'Firefox'
appModule.productVersion: u'59.0a1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 1051674L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 12936
windowText: u'algebra precalculus - Show that: $a^4+b^4+c^4<2a^2b^2+2b^2c^2+2a^2c^2$ - Mathematics Stack Exchange - Firefox Nightly'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xbca8afc at 71c5990>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1051674, objectID=-4, childID=-33597923
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_EQUATION
IAccessible accState: STATE_SYSTEM_OFFSCREEN, STATE_SYSTEM_VALID (65536)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 1051674
IAccessible2 uniqueID: -33597923
IAccessible2 role: ROLE_SYSTEM_EQUATION
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE (5120)
IAccessible2 attributes: u'margin-left:0px;text-align:left;text-indent:0px;margin-right:0px;tag:math;margin-top:0px;margin-bottom:0px;display:inline;'
```

**Comment by Andre9642** [comment]
Hello,
I found the reason for this bug. Actually, It's not really a bug.
On this machine, I have defined a environment variable LOUIS_TABLEPATH and MathPlayer seems to look first in this place.
Sorry for this noise. I close this ticket.
