### ISSUE TITLE
UIA in Word 2016: COM errors raised when creating a list below a table when braille is enabled

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7932]
### Steps to reproduce:
1. OPen Word 2016 with UIA enabled
2. Create a table in the document, a one by one table is enough to reproduce the issue
3. Press enter to move out of the table
4. Press control+shift+l to create a list, and start typing

### Expected behavior:
NVDA does not play the error sound.

### Actual behavior:
NVDA starts playing error sounds while typing. Errors look like this

```
ERROR - core.CorePump.Notify (08:19:36.177):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 446, in Notify
  File "braille.pyc", line 1967, in pumpAll
  File "braille.pyc", line 1760, in handlePendingCaretUpdate
  File "braille.pyc", line 1766, in _doCursorMove
  File "braille.pyc", line 916, in update
  File "braille.pyc", line 775, in _addTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 158, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 620, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 513, in _getTextWithFieldsForUIARange
COMError: (-2146233079, None, (None, None, None, 0, None))
```

### System configuration:
NVDA version: next-14799,5410e284
NVDA Installed
Windows version: Windows 10 fall creators update

**Comment by leonardder** [comment]
cc @michaeldcurran

**Comment by feerrenrut** [comment]
Given this a priority 2 to fix, assuming this stops a user from being able to continue to work in word. The severity of this should be verified.

**Comment by derekriemer** [comment]
is this with or without the new UIA in word incubation?

**Comment by michaelDCurran** [comment]
I can reproduce this, but cannot work around it. It is a bug in MS Word's UIA implementation. It looks like that whole apragraph  is continuously replaced and  previous ranges invalidated each time you type characters.
I can't detect a real user impact though. Even the braille display continues to show the correct content.
Decreasing priority and marking as  needsExternalFix

**Comment by leonardder** [comment]
@michaelDCurran: In https://github.com/nvaccess/nvda/issues/7932#issuecomment-364821405 you pointed out that this needs an external fix. Has this been fixed by Microsoft yet? I'm pretty sure I can still reproduce this once in a while. In fact, this and #9613 hold me back from using the UIA implementation more often.
