### ISSUE TITLE
IE11 there are com errors for state and focusable

### ISSUE THREAD

**Issue by dineshkaushal** [nvaccess/nvda#7973]
### Steps to reproduce:

In IE11, Open you tube and move to play / pause button in browse mode. then press down arrow and there should be an error tone.
for status error, open new issue in GitHub and tab after title box.

### Expected behavior:
There should not be any error.

### Actual behavior:
There is an error tone and focus may not move to that item.

### System configuration:
NVDA version: master-14831
I have started noticing this after 2017.4

NVDA Installed or portable: installed

Other information:

Windows version: windows 10

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA? 2017.4

It works fine.

**Comment by dineshkaushal** [comment]
NVDA log for Focusable error:
ERROR - scriptHandler.executeScript (11:26:40.780):
error executing script: <bound method MSHTML.script_moveByLine_back of <virtualBuffers.MSHTML.MSHTML object at 0x050F3630>> with gesture u'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 206, in script_moveByLine_back
  File "cursorManager.pyc", line 140, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1216, in _set_selection
  File "browseMode.pyc", line 1231, in _shouldSetFocusToObj
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 944, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 226, in __call__
  File "comtypes\automation.pyc", line 729, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))


NVDA log for Status error:
ERROR - core.CorePump.Notify (11:13:17.161):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 443, in Notify
  File "IAccessibleHandler.pyc", line 897, in pumpAll
  File "IAccessibleHandler.pyc", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 684, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 640, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 638, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 793, in _get_states
  File "comtypes\client\lazybind.pyc", line 226, in __call__
  File "comtypes\automation.pyc", line 729, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))

**Comment by dineshkaushal** [comment]
This issue is better explained in 
#7982 so it should be closed.
