### ISSUE TITLE
Several COM, UIA and Get Focus errors

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7982]
### Steps to reproduce:
See log file.

I have analyzed a logfile during a work day with NVDA and found out that there are quite many COM Errors and Get focus Errors in several applications (especially IE and Adobe reader, but also MS Excel and MS Word. There are some UIA Errors as well.

[nvda COMErrors, Get focus errors etc.txt](https://github.com/nvaccess/nvda/files/1712376/nvda.COMErrors.Get.focus.errors.etc.txt)
I cannot understand all errors in there. But I would be very happy to start a discussion among developers on why there are so many errors occuring. I hope it can contribute to solve some issues.

### System configuration:
NVDA version:
2017.4

NVDA Installed or portable:
Installed

Other information:
Windows running as local user

Windows version:
Windows 8.1

Name and version of other software in use when reproducing the issue:
Adobe Reader, MS Office 2010, IE11

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
no.

**Comment by Adriani90** [comment]
#7986

**Comment by dineshkaushal** [comment]
My earlier assumption was that this error started after comtypes 1.1.3 committed on 21 December 2017, but after testing previous versions till 2017.4 rc1, I figured that this error has been happening even before that. After going through comments in #8015, I realized that I should check NVDA 2017.4 release versions and yes, I found out that error was still there but it was not being reported. So these errors have been happening for a while and solution would be to handle com errors and returning appropriate values.

**Comment by Adriani90** [comment]
I think it could be related to this error in the log file above:
```
DEBUGWARNING - eventHandler.executeEvent (12:10:37.752):
error executing event: gainFocus on <NVDAObjects.UIA.UIA object at 0x05896AF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 143, in executeEvent
  File "eventHandler.pyo", line 91, in __init__
  File "eventHandler.pyo", line 98, in next
  File "\\pegasus\profil$\BOA\Daten\AppData\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 238, in event_gainFocus
  File "eventHandler.pyo", line 98, in next
  File "\\pegasus\profil$\BOA\Daten\AppData\nvda\addons\wintenApps\globalPlugins\wintenObjs.py", line 149, in event_gainFocus
  File "eventHandler.pyo", line 98, in next
  File "NVDAObjects\__init__.pyo", line 950, in event_gainFocus
  File "NVDAObjects\__init__.pyo", line 838, in reportFocus
  File "speech.pyo", line 376, in speakObject
  File "speech.pyo", line 270, in speakObjectProperties
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1180, in _get_columnHeaderText
  File "NVDAObjects\UIA\__init__.pyo", line 667, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))
``

**Comment by Adriani90** [comment]
I am closing this due to following reasons:
1. Testing was under an old environment with an old NVDA version, so results are outdated.
2. Many of the com errors are not occuring in newer NVDA versions. For certain com error issues, other issues are already open.
