### ISSUE TITLE
NVDA causes crash in MS Outlook 2016 on Windows 10

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7986]
### Steps to reproduce:
I am trying to open an e-mail with a screenshot in it and every time Outlook is crashing.

### Expected behavior:
Outlook should not crash.

### Actual behavior:
NVDA causes a crash in outlook. When opening that e-mail with jaws, outlook does not crash. I get following error after debugging with Visual Studio 2015:
Unhandled exception at 0x1A44F125 (WWLIB.DLL) in OUTLOOK.EXE: 0xC0000005: 

   AND AFTER KLICKING ON "Continue"
Exception thrown at 0x1A44F125 (WWLIB.DLL) in OUTLOOK.EXE: 0xC0000005: 

You can find attached the NVDA log file containing many COMErrors.

### System configuration:
NVDA version:
2017.4
[nvda Crash in Outlook 2016.txt](https://github.com/nvaccess/nvda/files/1714474/nvda.Crash.in.Outlook.2016.txt)

NVDA Installed or portable:
Both

Other information:

Windows version:
Windows 10 Build 16.299.64

Name and version of other software in use when reproducing the issue:
MS Outlook 2016

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No.

**Comment by leonardder** [comment]
[**@Adriani90**](https://github.com/Adriani90) commented on [11 feb. 2018 16:03 CET](https://github.com/nvaccess/nvda/issues/7986#issue-296196490 "2018-02-11T15:03:51Z - Replied by Github Reply Comments"):
> Name and version of other software in use when reproducing the issue:
> MS Outlook 2016

Could you please make sure that you have the most recent version of Outlook 2016, i.e. that Outlook itself reports it being the most recent version when trying to update?

**Comment by Adriani90** [comment]
Hello, after updating to last 2016 version, NVDA causes an automatic restart of MS Outlook instead of application crash. See log file. I have tested it with jaws and outlook is definitely not being restarted. I will test it tomorrow in MS Outlook 2010 as well.
[nvda causes restart of outlook.txt](https://github.com/nvaccess/nvda/files/1716580/nvda.causes.restart.of.outlook.txt)

**Comment by Brian1Gaff** [comment]
I've seen these effects reported on the users list. maybe some post over 
there might be of use here?

**Comment by Adriani90** [comment]
I have repaired MS Outlook 2016 on Windows 10 and made sure that it is updated to the very last version. Now it is not restarting automatically anymore, but it crashes when NVDA is running.

**Comment by Adriani90** [comment]
Here is the log fragment related to outlook action after pressing enter on the message. The whole file is attached. A dmp file has not been created, even when using python console.




[nvda_crash.txt](https://github.com/nvaccess/nvda/files/1808839/nvda_crash.txt)

```
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (23:06:06.678):
oleacc.AccessibleObjectFromEvent with window 1180212, objectID 244 and childID 0: [Error -2147467259] Unbekannter Fehler
IO - inputCore.InputManager.executeGesture (23:06:07.427):
Input: kb(laptop):downArrow
DEBUGWARNING - watchdog._watcher (23:06:09.967):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyo", line 473, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 444, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "scriptHandler.pyo", line 145, in _queueScriptCallback
  File "scriptHandler.pyo", line 187, in executeScript
  File "cursorManager.pyo", line 210, in script_moveByLine_forward
  File "cursorManager.pyo", line 140, in _caretMovementScriptHelper
  File "browseMode.pyo", line 1200, in _set_selection
  File "baseObject.pyo", line 21, in __get__
  File "treeInterceptorHandler.pyo", line 200, in _get_bookmark
  File "baseObject.pyo", line 21, in __get__
  File "NVDAObjects\window\winword.pyo", line 968, in _get_bookmark
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke

DEBUGWARNING - scriptHandler.executeScript (23:06:10.023):
error executing script: <bound method MailViewerTreeInterceptor.script_moveByLine_forward of <appModules.outlook.MailViewerTreeInterceptor object at 0x06E44DF0>> with gesture u'Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "cursorManager.pyo", line 210, in script_moveByLine_forward
  File "cursorManager.pyo", line 140, in _caretMovementScriptHelper
  File "browseMode.pyo", line 1200, in _set_selection
  File "baseObject.pyo", line 21, in __get__
  File "treeInterceptorHandler.pyo", line 200, in _get_bookmark
  File "baseObject.pyo", line 21, in __get__
  File "NVDAObjects\window\winword.pyo", line 968, in _get_bookmark
  File "watchdog.pyo", line 202, in _COMError_init
CallCancelled
IO - speech.speak (23:06:15.982):
Speaking [u'Microsoft Outlook  Dialogfeld  Microsoft Outlook wird neu gestartet...']
IO - speech.speak (23:06:15.986):
Speaking [u'Abbrechen  Schalter']
IO - tones.beep (23:06:15.987):
Beep at pitch 110.0, for 40 ms, left volume 50, right volume 50
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (23:06:16.194):
accRole failed: (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (23:06:16.206):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUG - appModuleHandler.cleanup (23:06:16.220):
application outlook closed
DEBUG - treeInterceptorHandler.killTreeInterceptor (23:06:16.230):
Killed treeInterceptor: <appModules.outlook.MailViewerTreeInterceptor object at 0x06E44DF0>
```
