### ISSUE TITLE
Word 2016 UIA with braille: error when returning to focus mode or when changing review mode to object

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#8041]
Thanks to @bramd for the initial report.

### Steps to reproduce:
1. Use braille, set it to tether automatically or to review
2. Open a plain Word 2016 document
3. Type a line of text
4. Below that line, create a heading
5. Move to the top of the document
6. Enable browse mode
7. Press "h" to go to the heading
8. Disable browse mode

### Expected behavior:
Browse mode disables properly, without an error.

### Actual behavior:
The following error is in de log

```
ERROR - scriptHandler.executeScript (08:20:39.121):
error executing script: <bound method GlobalCommands.script_toggleVirtualBufferPassThrough of <globalCommands.GlobalCommands object at 0x06EA8410>> with gesture u'NVDA+spatie'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 1245, in script_toggleVirtualBufferPassThrough
  File "treeInterceptorHandler.pyc", line 119, in _set_passThrough
  File "review.pyc", line 120, in setCurrentMode
  File "api.pyc", line 195, in setReviewPosition
  File "braille.pyc", line 1842, in handleReviewMove
  File "braille.pyc", line 1718, in _doNewObject
  File "braille.pyc", line 1454, in getFocusRegions
  File "braille.pyc", line 903, in update
  File "braille.pyc", line 775, in _addTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 161, in getTextWithFields
IndexError: list index out of range
```

After this, the error is re-triggered when you change review mode to document and back to object.

### System configuration:
NVDA version: 2018.1RC1
NVDA Installed
Windows 10 fall creators update with most recent Office 2016

**Comment by leonardder** [comment]
cc @michaeldcurran

**Comment by leonardder** [comment]
This looks like a more generic issue. It seems like browse mode and focus mode are not in sync. Whenever I have a bigger document and move to headings in browse mode, than back to focus mode, the focus mode cursor is in a completely different position.
