### ISSUE TITLE
NVDA version next-15023,fcbd1731 Problem with Explorer 

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#8161]
Hello.
1. Open this computer.
2. Start moving using the arrows.
Expected. Nvda reads the folder list. In fact, this does not happen NVDA gives an error and is silent.windows 10 1803 17133-73

NVDA version next-15023,fcbd1731

**Comment by gdata1** [comment]
INFO - __main__ (12:05:19.967):
Starting NVDA
INFO - core.main (12:05:20.121):
Config dir: C:\Users\nikit\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (12:05:20.121):
Loading config: C:\Users\nikit\AppData\Roaming\nvda\nvda.ini
INFO - core.main (12:05:21.118):
NVDA version next-15023,fcbd1731
INFO - core.main (12:05:21.118):
Using Windows version 10.0.17133 workstation
INFO - core.main (12:05:21.118):
Using Python version 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
INFO - core.main (12:05:21.118):
Using comtypes version 1.1.3
INFO - external:synthDrivers.RHVoice.SynthDriver.__init__ (12:05:21.361):
Using RHVoice version 0.5
INFO - synthDriverHandler.setSynth (12:05:21.361):
Loaded synthDriver RHVoice
INFO - core.main (12:05:21.361):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (12:05:21.368):
Braille input initialized
INFO - braille.initialize (12:05:21.368):
Using liblouis version 3.5.0
INFO - braille.BrailleHandler.setDisplayByName (12:05:21.368):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (12:05:21.418):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (12:05:21.424):
UIAutomation: IUIAutomation5
INFO - core.main (12:05:22.319):
NVDA initialized
ERROR - core.CorePump.Notify (12:05:26.460):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 443, in Notify
  File "IAccessibleHandler.pyc", line 880, in pumpAll
  File "IAccessibleHandler.pyc", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 684, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 643, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1564, in _get_parent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\window\__init__.pyc", line 263, in _get_parent
  File "NVDAObjects\__init__.pyc", line 87, in __call__
  File "appModules\explorer.pyc", line 236, in chooseNVDAObjectOverlayClasses
NameError: global name 'windowClassName' is not defined

**Comment by josephsl** [comment]
Hi, probable cause: #5751. CC @DKager as this is a critical showstopper. Thanks.

**Comment by PratikP1** [comment]
I can verify this behavior as well.

**Comment by gregjozk** [comment]
confirmed. It also occurs at shutdown dialog.

**Comment by gdata1** [comment]
Many thanks. Problem solved in version NVDA version next-15024,ac2d9f33
