### ISSUE TITLE
In firefox nightly with next, this error occurs on gmail

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#8330]
On the new gmail, in the latest nightly and with Next, this error occurs when table navigating in the emails table. Additionally, NVDA says 'cell" with no table info.

```
Input: kb(desktop):alt+control+downArrow
ERROR - scriptHandler.executeScript (13:11:08.611):
error executing script: <bound method Gecko_ia2.script_nextRow of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05A3B4D0>> with gesture u'alt+ctrl+down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "documentBase.pyc", line 174, in script_nextRow
  File "documentBase.pyc", line 161, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 321, in _getNearestTableCell
  File "documentBase.pyc", line 138, in _getNearestTableCell
  File "virtualBuffers\gecko_ia2.pyc", line 311, in _getTableCellAt
AttributeError: 'Mozilla' object has no attribute 'IAccessibleTableObject'
IO - inputCore.InputManager.executeGesture (13:11:09.426):
Input: kb(desktop):NVDA+f1
DEBUGWARNING - watchdog._watcher (13:11:10.930):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyc", line 475, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 446, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 1438, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1167, in info
  File "logHandler.pyc", line 140, in _log
  File "wx\_core.pyc", line 13263, in SetInsertionPointEnd

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (13:11:11.062):
Developer info for navigator object:
name: u"unread, Dickson .. James 4, [nvda-addons] Announcing Skype 0.1, 1:03 PM, Hi, For my first addon, I was inspired to port some features from Dug Lee's excellent jaws scripts for Skype for classic Skype. Its on GitHub, and this is the direct link to the .addon file for."
role: ROLE_CHECKBOX
states: STATE_FOCUSABLE, STATE_CHECKABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x05CE25D0>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: RectLTWH(left=94, top=444, width=20, height=20)
value: None
appModule: <'firefox' (appName u'firefox', process ID 11816) at address 5a256f0>
appModule.productName: u'Firefox Nightly'
appModule.productVersion: u'62.0a1'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 393740L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 382664704
windowThreadID: 12084
windowText: u'Inbox (2) - driemer.riemer@gmail.com - Gmail - Firefox Nightly'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x9166c14 at 5bbc9e0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=393740, objectID=-4, childID=-16783550
IAccessible accName: u"unread, Dickson .. James 4, [nvda-addons] Announcing Skype 0.1, 1:03 PM, Hi, For my first addon, I was inspired to port some features from Dug Lee's excellent jaws scripts for Skype for classic Skype. Its on GitHub, and this is the direct link to the" (truncated)
IAccessible accRole: ROLE_SYSTEM_CHECKBUTTON
IAccessible accState: STATE_SYSTEM_MARQUEED, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1056772)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 393740
IAccessible2 uniqueID: -16783550
IAccessible2 role: ROLE_SYSTEM_CHECKBUTTON
IAccessible2 states: IA2_STATE_OPAQUE (1024)
IAccessible2 attributes: u'margin-left:0px;checkable:true;text-align:left;text-indent:0px;id:\\:lz;tag:div;class:oZ-jc T-Jo J-J5-Ji ;xml-roles:checkbox;margin-top:0px;margin-bottom:0px;margin-right:0px;display:flex;explicit-name:true;'

```

**Comment by derekriemer** [comment]
cuteScript (23:32:24.934):
error executing script: <bound method Gecko_ia2.script_previousRow of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x06125910>> with gesture u'alt+ctrl+up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "documentBase.pyc", line 179, in script_previousRow
  File "documentBase.pyc", line 167, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 311, in _getTableCellAt
AttributeError: 'Mozilla' object has no attribute 'IAccessibleTableObject'
In firefox
62.0a1 (2018-06-03) (64-bit)

**Comment by Adriani90** [comment]
in Firefox 63.0.3 table navigation in message list and other tables is still broken.

**Comment by Adriani90** [comment]
I cannot reproduce this anymore in Firefox 66.0.2. @derekriemer can you confirm?

**Comment by ehollig** [comment]
@derekriemer can you still reproduce this?

**Comment by derekriemer** [comment]
no.
