### ISSUE TITLE
Chrome: Text input in an edit field keeps generating errors

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#8634]
### Steps To Reproduce: ###
1. Open your Wordpress site in Chrome and edit one of the published posts.
2. Navigate to and activate the Categories and Tags button.
3. Navigate to and enter the Tags edit field. Tabbing to it, pressing Enter or Spacebar on it, or activating focus mode on the edit field all are effective means of entering the edit field that do not affect the results.
4. Input any character, press Backspace to delete the same, and keep playing around in the edit field.
### Expected Result: ###
Text input should work normally and no error should be generated.
### Actual Result: ###
Text input occurs correctly but almost every other character inputted causes an error.
### Developer Info for Edit Field ###
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (08:02:29.368):
Developer info for navigator object:
name: u'Tags '
role: ROLE_EDITABLETEXT
states: STATE_OFFSCREEN, STATE_FOCUSABLE, STATE_FOCUSED, STATE_EDITABLE
isFocusable: True
hasFocus: True
Python object: <baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x04B3C8F0>
Python class mro: (<class 'baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.DocumentWithTableNavigation'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (1375, 469, 124, 24)
value: u'this is a test'
appModule: <'appModuleHandler' (appName u'chrome', process ID 2668) at address 46a7250>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'68.0.3440.106'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 2949978L
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: -767786672
windowStyle: 1445986304
windowThreadID: 348
windowText: u'Chrome Legacy Window'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x6b2d274 at 4b3ebc0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=2949978, objectID=-4, childID=-25697
IAccessible accName: u'Tags '
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_OFFSCREEN, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1114116)
IAccessible accDescription: None
IAccessible accValue: u'this is a test'
IAccessible2 windowHandle: 2949978
IAccessible2 uniqueID: -25697
IAccessible2 role: ROLE_SYSTEM_TEXT
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE, IA2_STATE_EDITABLE, IA2_STATE_SINGLE_LINE (13320)
IAccessible2 attributes: u'display:block;tag:input;explicit-name:true;class:token-field__input;text-model:a1;;text-input-type:text;'
### Log Snippet ###
ERROR - eventHandler.executeEvent (08:00:21.076):
error executing event: caret on <baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x049C7650> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 152, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "browseMode.pyo", line 1173, in event_caret
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\behaviors.pyo", line 173, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyo", line 1368, in event_caret
  File "NVDAObjects\__init__.pyo", line 1002, in event_caret
  File "review.pyo", line 174, in handleCaretMove
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 201, in _findContentDescendant
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (08:00:21.088):
error executing event: caret on <baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x049C7650> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 152, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "browseMode.pyo", line 1173, in event_caret
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\behaviors.pyo", line 173, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyo", line 1368, in event_caret
  File "NVDAObjects\__init__.pyo", line 1002, in event_caret
  File "review.pyo", line 174, in handleCaretMove
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 201, in _findContentDescendant
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - queueHandler.pumpAll (08:00:21.107):
generator 1437 finished
### System Version: ###
NVDA version: 2018.3 Beta 2
NVDA Installed or portable: Installed
Google Chrome Version: 68.0.3440.106
Windows version: Windows 8.1
### Notes ###
* This issue does not occur with Firefox.
* I may be imagining this, but pressing Backspace produces errors far more consistently than an alphabetic character, and typing at moderately fast speeds seems to produce more errors than at slow or excessively fast speeds.

**Comment by Adriani90** [comment]
@bhavyashah are you still having this problem in Chrome 79 with NVDA 2019.3 Beta 1?

**Comment by Adriani90** [comment]
STill reproducible from time to time in Chrome 83 with NVDA 2020.1.
Following error is written to the log:

```
Input: kb(laptop):rightArrow
ERROR - scriptHandler.executeScript (14:08:55.545) - MainThread (10000):
error executing script: <bound method EditableText.script_caret_moveByCharacter of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x03FB9A50>> with gesture 'Pfeiltaste nach rechts'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "editableText.pyc", line 223, in script_caret_moveByCharacter
  File "editableText.pyc", line 161, in _caretMovementScriptHelper
  File "editableText.pyc", line 94, in _hasCaretMoved
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 94, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 202, in _findContentDescendant
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
```

Is this overall an issue in comtypes? Or is it an NVDA issue?
cc: @JulienCochuyt, @aleventhal.

**Comment by Adriani90** [comment]
I cannot really reproduce this issue anymore. Some times NVDA plays sometimes an error sound but very very rare, it's actually negligible. @bhavyashah can you reproduce this in Chrome 117 with NVDA 2023.2?

**Comment by bhavyashah** [comment]
I no longer actively use Chrome or Wordpress. That said, I tried following my STR again just now and had no errors. I'll close this ticket. 
P.S. Thanks for following up on this, @Adriani90! I need to update my tickets, especially bugs I've reported in the past which no longer reproduce...
