### ISSUE TITLE
Core: Don't Refuse to Start properly if input braille table is invalid

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#8650]
### Steps to reproduce:
((Context: through an add-on, I'd like to implement the possibility to add his own braille tables. No problem with output tables.))

1. Open the NVDA console and type: `import config; config.conf["braille"]["inputTable"] = "afr-za-g1.ctb"`
Note: "afr-za-g1.ctb" is just for the example. Take just a table that's not in brailleTables.listTables(, but present in liblouis tables dir.
2. Save NVDA config and Restart NVDA.

### Actual behavior:
NVDA refuse to start properly and the following critical error are logged:
<details>
<summary>Errors from log</summary>
<pre>
ERROR - brailleInput.BrailleInputHandler.__init__ (14:09:09.019):
Invalid table: afr-za-g1.ctb
CRITICAL - __main__ (14:09:09.061):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 214, in <module>
  File "core.pyc", line 269, in main
  File "brailleInput.pyc", line 48, in initialize
  File "brailleInput.pyc", line 70, in __init__
  File "brailleTables.pyc", line 52, in getTable
KeyError: 'en-us-comp8.ctb'
ERROR - unhandled exception (14:10:03.992):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "NVDAHelper.pyc", line 379, in nvdaControllerInternal_typedCharacterNotify
AttributeError: 'NoneType' object has no attribute 'windowClassName'
ERROR - unhandled exception (14:10:14.335):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "NVDAHelper.pyc", line 379, in nvdaControllerInternal_typedCharacterNotify
AttributeError: 'NoneType' object has no attribute 'windowClassName'
ERROR - unhandled exception (14:10:14.516):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "NVDAHelper.pyc", line 379, in nvdaControllerInternal_typedCharacterNotify
AttributeError: 'NoneType' object has no attribute 'windowClassName'
ERROR - unhandled exception (14:10:15.084):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "NVDAHelper.pyc", line 379, in nvdaControllerInternal_typedCharacterNotify
AttributeError: 'NoneType' object has no attribute 'windowClassName'
[...]
</pre>
</details>

Besides, NVDA must be killed by task manager.

### Expected behavior:
NVDA should be start properly if the input or output braille table is invalid.

#### NVDA Installed/portable/running from source:
Any

#### NVDA version:
alpha-15878,fabb3cd4

#### Windows version:
Any

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by Andre9642** [comment]
I'm unable to reproduce the issue - closing.
