### ISSUE TITLE
Cannot create a valid method resolution order

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#8700]
### Steps to reproduce:
1. find a file and activate open with.
2. Choose "Choose another app." This is usally at the bottom of tthe list in the context menu.
3. Arrow through the list of programs.

### Actual behavior:

Errors occur
```

error executing event: gainFocus on <NVDAObjects.UIA.ListItem object at 0x05F0FF10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 147, in executeEvent
  File "eventHandler.pyc", line 160, in doPreGainFocus
  File "api.pyc", line 107, in setFocusObject
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 496, in _get_container
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1154, in _get_parent
  File "NVDAObjects\__init__.pyc", line 109, in __call__
  File "baseObject.pyc", line 135, in __new__
TypeError: Cannot create a consistent method resolution

```

### Expected behavior:

Programs are read out.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
NonVisual Desktop Access (NVDA)
Version: alpha-15933,b3aff97c

#### Windows version:
10, latest stable.

#### Other information about your system:

Tried running COM fixes.

**Comment by leonardder** [comment]
Is this occurring with NVDA 2018.3Beta and 2018.2.1?

**Comment by Brian1Gaff** [comment]
No sign on this in windows 7 open with by the way.

**Comment by derekriemer** [comment]
not with .2, but with .3 beta3

I'm going to attempt to bisect.

**Comment by derekriemer** [comment]
not with .2, but with .3 beta3

I'm going to attempt to bisect.I was using an out of date windows 10 app essentials.
