### ISSUE TITLE
Config profile triggers: a nonexistent key causes key error traceback when attempting to switch between profiles

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8778]
Hi,

Perhaps a regression from Emoji announcement work: one cannot switch to profiles without encountering key error exception traceback.

### Steps to reproduce:
1. Create one or more config profiles.
2. Open config profiles (Control+NVDA+P) and try to switch to a profile manually.
3. Alternatively, trigger a profile via say all, switching between apps and so on.

### Actual behavior:
ERROR - unhandled exception (21:28:27.158):
Traceback (most recent call last):
  File "gui\configProfiles.pyc", line 259, in onClose
  File "config\__init__.pyc", line 753, in disableProfileTriggers
  File "config\__init__.pyc", line 374, in _handleProfileSwitch
  File "config\__init__.pyc", line 943, in dict
  File "config\__init__.pyc", line 941, in dict
  File "config\__init__.pyc", line 864, in __getitem__
KeyError: u'x'

### Expected behavior:
Profile switching works normally.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
Alpha.16103

#### Windows version:
Windows 10 Version 1809 Preview

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

Thanks.

**Comment by josephsl** [comment]
P1, CC @LeonardDer

**Comment by leonardder** [comment]
Could you please test [this](https://ci.appveyor.com/api/buildjobs/ed54xb39higm5oef/artifacts/output%2Fnvda_snapshot_try-i8778-16108%2C65241863.exe) try build to see whether the issue is resolved?

**Comment by leonardder** [comment]
`KeyError: u'x'` is because the x value for the speech viewer has no default. Same applies to y, width, height and displays. This is exactly what #8780 is supposed to solve.
