### ISSUE TITLE
Windows 10 mail and favorites list

### ISSUE THREAD

**Issue by nidza07** [nvaccess/nvda#8816]
### Summary.
When you open windows 10 mail and press end on the list of favorite folders, the app  crashes.
### Steps to reproduce:
1. Open Windows 10 mail.
2. Tab until you reach the favorites list.
3. Press end to jump to the last folder in the list.

### Actual behavior:
The mail app crashes and closes.
### Expected behavior:
The mail app should work normally and you should be focused on the last folder in the list. This did work before, but not sure if it was a NVDA update or the mail app update which broke this.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
alpha-16123,142e542a
#### Windows version:
Windows 10 1809
#### Name and version of other software in use when reproducing the issue:
Windows 10 mail Version 16005.10827.20110.0
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No
### Log:
After this crash, the following error is generated in the log:
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem object at 0x03D720B0> with extra args of {'ch': u'\t'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 908, in event_typedCharacter
  File "speech.pyc", line 661, in speakTypedCharacters
  File "api.pyc", line 248, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 782, in _get_isProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1067, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 734, in _prefetchUIACacheForPropertyIDs
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

**Comment by Adriani90** [comment]
@nidza07 are you still having this issue in NVDA 2019.3 Beta 2?
I cannot reproduce it in Windows mail version 16005.12228.20410.0 on Windows 10 1909 Update.

**Comment by Adriani90** [comment]
We do not have updates from the initial author since more than one year, closing as abandoned and works for me. Cannot reproduce with NVDA 2020.1.
