### ISSUE TITLE
In VLC Media Player version 3.0.4, NVDA + pavNum5 pressed twice or three times raises an error

### ISSUE THREAD

**Issue by abdel792** [nvaccess/nvda#8854]
With VLC Media Player version 3.0.4, we notice the following bug that we were able to reproduce with the version 2018.3.2 and 2018.3.1, we have not tested with previous versions of NVDA

Steps to Reproduce:

Open VLC Media Player version 3.0.4.

Press NVDA + pavNum5 twice or 3 times.

Expected behavior:

The name of the object under the navigation cursor should be spelled or copied to the Clipboard.

Actual behavior:

NVDA remains silent and the log displays the following log:

error executing script: <bound method GlobalCommands.script_navigatorObject_current of <globalCommands.GlobalCommands object at 0x0493E8D0>> with gesture u'NVDA+pavNum 5'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "globalCommands.pyo", line 780, in script_navigatorObject_current
  File "documentBase.pyo", line 24, in makeTextInfo
  File "displayModel.pyo", line 263, in __init__
  File "textInfos\offsets.pyo", line 300, in __init__
  File "displayModel.pyo", line 253, in _getSelectionOffsets
LookupError

**Comment by seanbudd** [comment]
is this still an issue in the latest VLC and NVDA?
