### ISSUE TITLE
baum vario 40 no key input

### ISSUE THREAD

**Issue by erikpro** [nvaccess/nvda#8894]
### Steps to reproduce:
connect vario 40 vire com or usb to com converter. select baum driver in brl configuration.
press eni button on the desplay. 
### Actual behavior:
nvda dont doo anything.
### Expected behavior:
a gesture must be executed.
#### nvda log cat
ERROR - hwIo.IoBase._notifyReceive (18:27:46.773):
Traceback (most recent call last):
  File "hwIo.pyo", line 147, in _notifyReceive
  File "brailleDisplayDrivers\baum.pyo", line 162, in _onReceive
  File "brailleDisplayDrivers\baum.pyo", line 177, in _handleResponse
  File "brailleDisplayDrivers\baum.pyo", line 228, in __init__
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - hwIo.IoBase._notifyReceive (18:27:47.220):
Traceback (most recent call last):
  File "hwIo.pyo", line 147, in _notifyReceive
  File "brailleDisplayDrivers\baum.pyo", line 162, in _onReceive
  File "brailleDisplayDrivers\baum.pyo", line 177, in _handleResponse
  File "brailleDisplayDrivers\baum.pyo", line 228, in __init__
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - hwIo.IoBase._notifyReceive (18:27:47.368):
Traceback (most recent call last):
  File "hwIo.pyo", line 147, in _notifyReceive
  File "brailleDisplayDrivers\baum.pyo", line 162, in _onReceive
  File "brailleDisplayDrivers\baum.pyo", line 177, in _handleResponse
  File "brailleDisplayDrivers\baum.pyo", line 228, in __init__
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - hwIo.IoBase._notifyReceive (18:27:48.290):
Traceback (most recent call last):
  File "hwIo.pyo", line 147, in _notifyReceive
  File "brailleDisplayDrivers\baum.pyo", line 162, in _onReceive
  File "brailleDisplayDrivers\baum.pyo", line 177, in _handleResponse
  File "brailleDisplayDrivers\baum.pyo", line 228, in __init__
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - hwIo.IoBase._notifyReceive (18:27:48.739):
Traceback (most recent call last):
  File "hwIo.pyo", line 147, in _notifyReceive
  File "brailleDisplayDrivers\baum.pyo", line 162, in _onReceive
  File "brailleDisplayDrivers\baum.pyo", line 177, in _handleResponse
  File "brailleDisplayDrivers\baum.pyo", line 228, in __init__
AttributeError: 'NoneType' object has no attribute 'replace'

#### NVDA Installed/portable/running from source:
instaled 
#### NVDA version:
2018.3.2
#### Windows version:
windos 10 1809
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
yes

**Comment by leonardder** [comment]
This looks like a model identifier isn't set for this display. I will take this.

**Comment by leonardder** [comment]
Could you please test input with [this try build](https://ci.appveyor.com/api/buildjobs/4fb19x0qtl0fp97x/artifacts/output%2Fnvda_snapshot_try-i8894-16204%2Ce18554ec.exe)?

**Comment by erikpro** [comment]
yes that build works like a charm. thanks.
i think this fix wood be included to nvda 2018.4. however i ask you wood it be possible to provide me addon or python file with this solution.
thank you @leonardder for help.
