### ISSUE TITLE
when creating new account in office365/Outlook 2016, the password field behaves incorrectly

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#8904]
### Steps to reproduce:
1. open the acconnt creation dialog in office365/outlook
2. after entering the e-mail adress, enter the password
### Actual behavior:
when entering password, the following error was generated
see log below
INFO - __main__ (10:57:55.953):
Starting NVDA
INFO - core.main (10:57:56.086):
Config dir: C:\Users\ninos\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (10:57:56.086):
Loading config: C:\Users\ninos\AppData\Roaming\nvda\nvda.ini
INFO - core.main (10:57:57.538):
NVDA version alpha-16196,5fe34c52
INFO - core.main (10:57:57.538):
Using Windows version 10.0.17763 workstation
INFO - core.main (10:57:57.538):
Using Python version 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
INFO - core.main (10:57:57.538):
Using comtypes version 1.1.3
INFO - core.main (10:57:57.539):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (10:57:57.960):
Loaded synthDriver newfon
INFO - core.main (10:57:57.960):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5
INFO - brailleInput.initialize (10:57:57.963):
Braille input initialized
INFO - braille.initialize (10:57:57.963):
Using liblouis version 3.7.0
INFO - braille.BrailleHandler.setDisplayByName (10:57:57.966):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (10:57:58.007):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (10:57:58.019):
UIAutomation: IUIAutomation6
INFO - external:globalPlugins.brailleExtender.GlobalPlugin.__init__ (10:57:58.335):
BrailleExtender dev-18.10.28-224825 loaded
INFO - core.main (10:57:58.336):
NVDA initialized
INFO - brailleDisplayDrivers.eurobraille.BrailleDisplayDriver.__init__ (10:57:58.859):
Found Esys 24 connected via hid (\\?\hid#vid_c251&pid_1123&mi_00#7&28a90993&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
INFO - braille.BrailleHandler.setDisplayByName (10:57:58.859):
Loaded braille display driver eurobraille, current display has 24 cells.
WARNING - external:globalPlugins.brailleExtender.configBE.loadConf (10:58:00.726):
C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\eurobraille\default\profile.ini inaccessible
WARNING - external:globalPlugins.brailleExtender.configBE.initGestures (10:58:00.727):
No main gestures map (C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\eurobraille\default\gestures.ini; C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\eurobraille\default\gestures.ini) found
INFO - config.ConfigManager.save (10:59:53.479):
Base configuration saved
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:01:11.224):
Fatal error: 
ERROR - eventHandler.executeEvent (11:01:11.285):
error executing event: gainFocus on <NVDAObjects.IAccessible.ContentGenericClient object at 0x0566E370> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 233, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 962, in event_gainFocus
  File "braille.pyc", line 1834, in handleGainFocus
  File "braille.pyc", line 1854, in _doNewObject
  File "braille.pyc", line 1340, in focus
  File "braille.pyc", line 1222, in regionPosToBufferPos
LookupError: No such position
ERROR - RPC process 6348 (nvda_slave.exe) (11:01:16.065):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 94, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1247, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] 
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:35.446):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:35.645):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:35.821):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:36.552):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:36.822):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:37.002):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:37.411):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:37.651):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:38.032):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:38.292):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:39.042):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:39.502):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:39.921):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:40.502):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:41.101):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:41.641):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - external:globalPlugins.brailleExtender.TextInfoRegion.update (11:02:41.861):
Fatal error: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
INFO - synthDrivers.espeak.SynthDriver.__init__ (11:09:38.802):
Using eSpeak NG version 1.49.3 dev
INFO - synthDriverHandler.setSynth (11:09:38.905):
Loaded synthDriver espeak
INFO - config.ConfigManager.save (11:09:44.857):
Base configuration saved
INFO - synthDriverHandler.setSynth (11:11:20.015):
Loaded synthDriver newfon
ERROR - eventHandler.executeEvent (11:25:27.737):
error executing event: gainFocus on <appModules.outlook.UIAGridRow object at 0x057698B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 233, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 961, in event_gainFocus
  File "NVDAObjects\behaviors.pyc", line 471, in reportFocus
  File "NVDAObjects\__init__.pyc", line 849, in reportFocus
  File "speech.pyc", line 383, in speakObject
  File "speech.pyc", line 275, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1243, in _get_columnNumber
  File "NVDAObjects\UIA\__init__.pyc", line 714, in _getUIACacheablePropertyValue
COMError: (-2146233083, None, (None, None, None, 0, None))
ERROR - core.CorePump.run (11:25:27.851):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 485, in run
  File "IAccessibleHandler.pyc", line 883, in pumpAll
  File "IAccessibleHandler.pyc", line 671, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 687, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache

nvda alpha alpha-16196,5fe34c52 and latest was used,
windows 10.0.1wwwwwwindows 10 version 1800 and office
w

**Comment by zstanecic** [comment]
windows 10 version 1809 17763.latestkb from insider preview ring
outlook version Microsoft® Outlook® 2016 MSO (16.0.9126.2295
32 bit
installed NVDA

**Comment by zstanecic** [comment]
Hi andre
the result from your recomendation to disable the add-on is the following:
ERROR - core.CorePump.run (13:54:38.331):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 488, in run
  File "braille.pyc", line 2133, in pumpAll
  File "braille.pyc", line 1875, in handlePendingCaretUpdate
  File "braille.pyc", line 1881, in _doCursorMove
  File "braille.pyc", line 960, in update
  File "braille.pyc", line 832, in _addTextWithFields
  File "NVDAObjects\window\edit.pyc", line 652, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 598, in _getTextAtRange
  File "comtypes\__init__.pyc", line 279, in __getattr__
COMError: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (13:54:39.163):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_backspaceCharacter of <baseObject.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x057FEA30>> with gesture u'backspace'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 231, in script_caret_backspaceCharacter
  File "editableText.pyc", line 217, in _backspaceScriptHelper
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\window\edit.pyc", line 722, in _get_text
  File "NVDAObjects\window\edit.pyc", line 598, in _getTextAtRange
  File "comtypes\__init__.pyc", line 279, in __getattr__
COMError: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (13:54:39.930):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_backspaceCharacter of <baseObject.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x057FEA30>> with gesture u'backspace'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 231, in script_caret_backspaceCharacter
  File "editableText.pyc", line 217, in _backspaceScriptHelper
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\window\edit.pyc", line 722, in _get_text
  File "NVDAObjects\window\edit.pyc", line 598, in _getTextAtRange
  File "comtypes\__init__.pyc", line 279, in __getattr__
COMError: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (13:54:40.450):
error executing script: <bound method Dynamic_IAccessibleRichEdit50WindowNVDAObject.script_caret_backspaceCharacter of <baseObject.Dynamic_IAccessibleRichEdit50WindowNVDAObject object at 0x057FEA30>> with gesture u'backspace'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 231, in script_caret_backspaceCharacter
  File "editableText.pyc", line 217, in _backspaceScriptHelper
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\window\edit.pyc", line 722, in _get_text
  File "NVDAObjects\window\edit.pyc", line 598, in _getTextAtRange
  File "comtypes\__init__.pyc", line 279, in __getattr__
COMError: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
@michaelDCurran 
@leonardder 
@josephsl 
@Andre9642

**Comment by Andre9642** [comment]
Hmm, according to your reproduce steps, I can NOT reproduce this bug. The only error is when I validate a password (fake or not), I get the following error:

<blockquote><pre>
ERROR - eventHandler.executeEvent (20:30:12.964):
error executing event: typedCharacter on <baseObject.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x053F45D0> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 908, in event_typedCharacter
  File "speech.pyc", line 679, in speakTypedCharacters
  File "api.pyc", line 248, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 782, in _get_isProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1067, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 734, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, 'Param\xe8tre incorrect.', (None, None, None, 0, None))
</pre></blockquote>

I'm running on Microsoft Outlook 16.0.10827.20181 and Windows 10 Insider (64-bit) build 18252.1000.

**Comment by Adriani90** [comment]
@zstanecic are you still having this issue in NVDA 2023.1 or in the last alpha version?
