### ISSUE TITLE
Word: Error while modifying style

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#8910]
### Steps to reproduce:
1. Create a new document.
2. Press control shift s to open the Apply Styles page.
3. Press "Modify...".

If the error sound doesn't occur, try changing the font size and tabbing.
### Actual behavior:
The error sound plays
```
ERROR - baseObject.ScriptableObject.bindGestures (03:42:21.480):
Error binding script caret_changeSelection in <baseObject.Dynamic_WordDocument_WwNIAccessibleWindowNVDAObject object at 0x05D9B150>
```
### Expected behavior:
No error sound should be played
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-16220,87eb36f8
#### Windows version:
Version 1809 (OS Build 17763.55)
#### Name and version of other software in use when reproducing the issue:
Microsoft® Word for Office 365 MSO (16.0.11001.20064) 32-bit
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
I could also catch these errors while trying to close the styles dialog with escape:

```
IO - speech.speak (00:22:31.207) - MainThread (9800):
Speaking ['Formatvorlage ändern', 'Dialogfeld', 'Eigenschaften\nFormatierung']
IO - inputCore.InputManager.executeGesture (00:22:31.239) - winInputHook (9272):
Input: kb(laptop):escape
DEBUGWARNING - NVDAObjects.window.edit.RichEdit.makeTextInfo (00:22:31.267) - MainThread (9800):
Could not instanciate ITextDocumentTextInfo
Traceback (most recent call last):
  File "speech\__init__.pyc", line 512, in getObjectSpeech
  File "NVDAObjects\window\edit.pyc", line 841, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 653, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\window\edit.pyc", line 841, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 650, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418113, 'Schwerwiegender Fehler', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (00:22:31.269) - MainThread (9800):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x071569B0> with extra args of {}
Traceback (most recent call last):
  File "speech\__init__.pyc", line 512, in getObjectSpeech
  File "NVDAObjects\window\edit.pyc", line 841, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 653, in __init__
AttributeError: 'NoneType' object has no attribute 'duplicate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\window\edit.pyc", line 841, in makeTextInfo
  File "NVDAObjects\window\edit.pyc", line 650, in __init__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418113, 'Schwerwiegender Fehler', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 469, in speakObject
  File "speech\__init__.pyc", line 527, in getObjectSpeech
  File "NVDAObjects\window\edit.pyc", line 845, in makeTextInfo
  File "textInfos\offsets.pyc", line 458, in __init__
  File "NVDAObjects\window\edit.pyc", line 337, in _getStoryLength
  File "winKernel.pyc", line 212, in virtualAllocEx
OSError: [WinError 6] Das Handle ist ungültig.
ERROR - eventHandler.executeEvent (00:22:31.299) - MainThread (9800):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x071569B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1485, in event_caret
  File "NVDAObjects\window\edit.pyc", line 811, in event_caret
  File "NVDAObjects\window\edit.pyc", line 837, in makeTextInfo
  File "documentBase.pyc", line 24, in makeTextInfo
  File "textInfos\offsets.pyc", line 455, in __init__
  File "NVDAObjects\window\edit.pyc", line 287, in _getSelectionOffsets
  File "winKernel.pyc", line 212, in virtualAllocEx
OSError: [WinError 6] Das Handle ist ungültig.
ERROR - eventHandler.executeEvent (00:22:31.436) - MainThread (9800):
error executing event: caret on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x071569B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1485, in event_caret
  File "NVDAObjects\window\edit.pyc", line 811, in event_caret
  File "NVDAObjects\window\edit.pyc", line 837, in makeTextInfo
  File "documentBase.pyc", line 24, in makeTextInfo
  File "textInfos\offsets.pyc", line 455, in __init__
  File "NVDAObjects\window\edit.pyc", line 287, in _getSelectionOffsets
  File "winKernel.pyc", line 212, in virtualAllocEx
OSError: [WinError 6] Das Handle ist ungültig.
IO - inputCore.logTimeSinceInput (00:22:31.574) - MainThread (9800):
0.335 sec since input
IO - speech.speak (00:22:31.575) - MainThread (9800):
Speaking ['Werkzeugleiste']
IO - inputCore.logTimeSinceInput (00:22:31.613) - MainThread (9800):
0.374 sec since input
IO - speech.speak (00:22:31.613) - MainThread (9800):
Speaking ['Formatvorlagen übernehmen', 'Eigenschaftsseite']
IO - inputCore.logTimeSinceInput (00:22:31.617) - MainThread (9800):
0.378 sec since input
IO - speech.speak (00:22:31.617) - MainThread (9800):
Speaking ['Ändern...', 'Schalter']
IO - inputCore.InputManager.executeGesture (00:22:31.895) - winInputHook (9272):
Input: kb(laptop):escape
DEBUG - speech.manager.SpeechManager._handleIndex (00:22:31.992) - MainThread (9800):
Unknown index 2428, speech probably cancelled from main thread.
IO - inputCore.logTimeSinceInput (00:22:32.035) - MainThread (9800):
0.140 sec since input
IO - speech.speak (00:22:32.036) - MainThread (9800):
Speaking ['Dokument1 - Word']
```


If this is related to TextInfo, I think @leonardder has worked on a PR which might solve this but I am not sure which one it was.
