### ISSUE TITLE
Errors while typing in Chrome

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#8928]
### Steps to reproduce:
1. Open https://www.youtube.com
2. Move to the search field and start typing

### Actual behavior:
The edit box re-reads every character, and this error occurs while typing:
```
ERROR - eventHandler.executeEvent (11:10:52.844):
error executing event: caret on <baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x05AB1610> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1190, in event_caret
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 173, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1420, in event_caret
  File "NVDAObjects\__init__.pyc", line 1002, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 201, in _findContentDescendant
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

### Expected behavior:
No errors occur
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-16235,153b12df
#### Windows version:
Version 1809 (OS Build 17763.55)
#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment]
@tspivey I am on Version: alpha- I g-460, d722geff
I cannot reproduce this issue.
Are you still seeing this problem?

**Comment by Adriani90** [comment]
No updates since one and a half years from the initial author on this issue. I am closing as abandoned and I cannot reproduce.
