### ISSUE TITLE
Error when starting Microsoft Outlook 2010 with NVDA 2018.4 Beta 1

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8961]
### Steps to reproduce:
+ Just start Microsoft Outlook 2010.
### Actual behaviour:
Error when starting Microsoft Outlook 2010. [Here](https://github.com/nvaccess/nvda/files/2599668/NVDA.2018.4beta1_Outlook.2010.log) is the logfile.
### Expected behaviour:
No error when starting Microsoft Outlook 2010.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
NVDA 2018.4 Beta 1
#### Windows version:
Windows 7, SP1, 64-Bit
#### Name and version of other software in use when reproducing the issue:
Microsoft Outlook® 2010 (14.0.7224.5000) SP2 MSO (14.0.7224.5000)
#### Other information about your system:
+ Language: German (Austria)
+ KB4461529, KB2863821 and KB4461522 are installed.
#### Does the issue still occur after restarting your PC?
Not tried.
#### Have you tried any other versions of NVDA?
No error with NVDA 2018.1 (installed).

**Comment by leonardder** [comment]
Could you install NVDA 2018.4 beta1 and see whether this problem still persists?

**Comment by DrSooom** [comment]
@leonardder: Sorry, I accidentally overlooked your comment here. You might have read [my comment in issue #8967](https://github.com/nvaccess/nvda/issues/8967#issuecomment-441266967) in the meantime. It's the same here. I don't want to install Betas and RCs of NVDA on my productive systems (Stand-PC and NUC).

@Adriani90: Could you please test this with Microsoft Outlook 2016?

**Comment by lukaszgo1** [comment]
I am able to reproduce it with Outlook 2010 32-bit installed on Windows 7 Pro x64 with locale of both Outlook and Windows set to Polish using installed version of NVDA version alpha-16298,c651588e.
[nvda-old.log](https://github.com/nvaccess/nvda/files/2615585/nvda-old.log)

Log is  attached.

**Comment by DrSooom** [comment]
No error sounds with NVDA 2018.1 (installed and portable) and also no one with NVDA 2018.3.2 (portable). The issue of course also exists in NVDA 2018.4 Beta 2. Shall I try it with some Alpha builds – all portable of course?

@lukaszgo1: Your logfile doesn't contain "appModules\outlook.pyo" – it contains errors with "appModules\firefox.pyc". In my above logfile the errors start after line 136, on which I pressed WIN+4 to start Outlook 2010.

**Comment by lukaszgo1** [comment]
@DrSooom It is possibly caused by the fact, that Firefox was the next opened application, however this happened right after running Outlook.

**Comment by lukaszgo1** [comment]
I am unable to reproduce the freeze when starting Outlook for the second time, however NVDA freezes for me almost 100%  of the time when closing Outlook with the following log
[nvda-old.log](https://github.com/nvaccess/nvda/files/2616854/nvda-old.log)
.

**Comment by Adriani90** [comment]
Testing with NVDA 2018.4 Beta 2 on Windows 10 1809 Update and Outlook 2016 and also 365 as follows:
1. Opened start menu and typed out
2. Pressed enter on outlook

following error is announced by a sound and is visible in NVDA's log file:

```
IO - inputCore.InputManager.executeGesture (19:46:41.543):
Input: kb(laptop):enter
DEBUGWARNING - watchdog._watcher (19:46:44.661):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 217, in <module>
  File "core.pyo", line 515, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 485, in run
  File "IAccessibleHandler.pyo", line 883, in pumpAll
  File "IAccessibleHandler.pyo", line 757, in processForegroundWinEvent
  File "IAccessibleHandler.pyo", line 532, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyo", line 46, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyo", line 72, in __call__
  File "NVDAObjects\IAccessible\__init__.pyo", line 571, in __init__
  File "IAccessibleHandler.pyo", line 917, in getIAccIdentity
  File "comtypes\__init__.pyo", line 1160, in QueryInterface

DEBUGWARNING - core.CorePump.run (19:46:44.720):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 485, in run
  File "IAccessibleHandler.pyo", line 883, in pumpAll
  File "IAccessibleHandler.pyo", line 757, in processForegroundWinEvent
  File "IAccessibleHandler.pyo", line 532, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyo", line 46, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyo", line 87, in __call__
  File "appModules\outlook.pyo", line 174, in chooseNVDAObjectOverlayClasses
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 825, in _get_states
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "watchdog.pyo", line 202, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (19:46:45.280):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 217, in <module>
  File "core.pyo", line 515, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 485, in run
  File "IAccessibleHandler.pyo", line 883, in pumpAll
  File "IAccessibleHandler.pyo", line 657, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 524, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 378, in isUIAWindow
  File "_UIAHandler.pyo", line 366, in _isUIAWindowHelper

IO - speech.speak (19:46:45.653):
Speaking [u'Posteingang - adriani.botez@googlemail.com - Outlook']
IO - speech.speak (19:46:45.750):
Speaking [u'Tabellenansicht  Tabelle']
ERROR - RPC process 8380 (nvda_slave.exe) (19:46:47.529):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 94, in main
  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject
  File "comtypes\__init__.pyo", line 1247, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Vorgang nicht verfügbar
```

I attach my log file as well. I have also tested with all add-ons disabled and get the same result.
[nvda_Outlook.txt](https://github.com/nvaccess/nvda/files/2616950/nvda_Outlook.txt)

**Comment by ruifontes** [comment]
And also tested with Office 2013, Windows 10 1809 and last NVDA Alpha:

Input: kb(desktop):enter
DEBUG - NVDAObjects.UIA.edge.EdgeNode._get_isCurrent (19:01:25.976):
aria props = label=Outlook 2013, Aplicação de Ambiente de Trabalho, 
Premir à direita para mudar pré-visualização;role=listitem;selected=true;
IO - speech.speak (19:01:25.976):
Speaking [u'Outlook 2013, Aplica\xe7\xe3o de Ambiente de Trabalho, 
Premir \xe0 direita para mudar pr\xe9-visualiza\xe7\xe3o  1 de 6']
DEBUG - NVDAObjects.UIA.edge.EdgeNode._get_isCurrent (19:01:26.026):
aria props = label=Outlook 2013, Aplicação de Ambiente de Trabalho, 
Premir à direita para mudar pré-visualização;role=listitem;selected=true;
IO - braille.BrailleBuffer.update (19:01:26.026):
Braille regions text: [u'Outlook 2013, Aplica\xe7\xe3o de Ambiente de 
Trabalho, Premir \xe0 direita para mudar pr\xe9-visualiza\xe7\xe3o 1 de 6']
IO - braille.BrailleHandler.update (19:01:26.026):
Braille window dots: 1357 136 2345 123 135 135 13 - 128 2458 18 148 2 - 
17 1234 123 24 14 1
DEBUG - NVDAObjects.UIA.edge.EdgeNode._get_isCurrent (19:01:26.036):
aria props = label=Outlook 2013, Aplicação de Ambiente de Trabalho, 
Premir à direita para mudar pré-visualização;role=listitem;selected=true;
IO - speech.speak (19:01:26.036):
Speaking [u'Outlook 2013, Aplica\xe7\xe3o de Ambiente de Trabalho, 
Premir \xe0 direita para mudar pr\xe9-visualiza\xe7\xe3o  1 de 6']
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
full text: u
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
Fetching parents starting from enclosingElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
Hit root
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
Done fetching parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
Generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
Done generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
Yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.036):
Done yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.046):
Yielding balanced fields for textRange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.046):
no children
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.046):
Yielding text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (19:01:26.046):
_getTextWithFields_text start
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (19:01:26.046):
Walking by unit None
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (19:01:26.046):
With further units of: [1, 2, 0]
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (19:01:26.046):
Chunk has text. Fetching formatting
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (19:01:26.046):
Yielding formatting and text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (19:01:26.046):
Done _getTextWithFields_text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange 
(19:01:26.046):
_getTextWithFieldsForUIARange end
IO - speech.speak (19:01:26.301):
Speaking [u'desconhecido']
DEBUG - NVDAObjects.NVDAObject._get_placeholder (19:01:26.301):
Potential unimplemented child class: 
<baseObject.Dynamic_ClipboardCommandAnnouncementContentGenericClientIAccessibleWindowNVDAObject 
object at 0x05332C10>
IO - braille.BrailleBuffer.update (19:01:26.301):
Braille regions text: [u'desconhecido ', ' ']
IO - braille.BrailleHandler.update (19:01:26.305):
Braille window dots: -
IO - braille.BrailleHandler.update (19:01:26.305):
Braille window dots: -
DEBUGWARNING - watchdog._watcher (19:01:27.964):
Trying to recover from freeze, core stack:
   File "nvda.pyw", line 217, in <module>
   File "core.pyc", line 515, in main
   File "wx\core.pyc", line 2134, in MainLoop
   File "gui\__init__.pyc", line 963, in Notify
   File "core.pyc", line 485, in run
   File "IAccessibleHandler.pyc", line 900, in pumpAll
   File "IAccessibleHandler.pyc", line 757, in processForegroundWinEvent
   File "IAccessibleHandler.pyc", line 532, in winEventToNVDAEvent
   File "NVDAObjects\IAccessible\__init__.pyc", line 40, in 
getNVDAObjectFromEvent
   File "IAccessibleHandler.pyc", line 342, in accessibleObjectFromEvent
   File "oleacc.pyc", line 265, in AccessibleObjectFromEvent

DEBUGWARNING - core.CorePump.run (19:01:28.203):
errors in this core pump cycle
Traceback (most recent call last):
   File "core.pyc", line 485, in run
   File "IAccessibleHandler.pyc", line 900, in pumpAll
   File "IAccessibleHandler.pyc", line 757, in processForegroundWinEvent
   File "IAccessibleHandler.pyc", line 532, in winEventToNVDAEvent
   File "NVDAObjects\IAccessible\__init__.pyc", line 46, in 
getNVDAObjectFromEvent
   File "NVDAObjects\__init__.pyc", line 87, in __call__
   File "appModules\outlook.pyc", line 174, in 
chooseNVDAObjectOverlayClasses
   File "baseObject.pyc", line 34, in __get__
   File "baseObject.pyc", line 115, in _getPropertyViaCache
   File "NVDAObjects\IAccessible\__init__.pyc", line 825, in _get_states
   File "baseObject.pyc", line 34, in __get__
   File "baseObject.pyc", line 115, in _getPropertyViaCache
   File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (19:01:28.750):
Trying to recover from freeze, core stack:
   File "nvda.pyw", line 217, in <module>
   File "core.pyc", line 515, in main
   File "wx\core.pyc", line 2134, in MainLoop
   File "gui\__init__.pyc", line 963, in Notify
   File "core.pyc", line 485, in run
   File "IAccessibleHandler.pyc", line 883, in pumpAll
   File "IAccessibleHandler.pyc", line 657, in processFocusWinEvent
   File "IAccessibleHandler.pyc", line 524, in winEventToNVDAEvent
   File "_UIAHandler.pyc", line 378, in isUIAWindow
   File "_UIAHandler.pyc", line 366, in _isUIAWindowHelper

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.868):
oleacc.AccessibleObjectFromEvent with window 1443906, objectID 6 and 
childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.868):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728963 
and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.875):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728964 
and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.875):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728963 
and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.875):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728958 
and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.875):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728959 
and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.875):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728960 
and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.875):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728961 
and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (19:01:29.875):
oleacc.AccessibleObjectFromEvent with window 854542, objectID 100728962 
and childID 0: [Error -2147467259] Erro não especificado
INFO - config.ConfigManager._loadConfig (19:01:29.875):
Loading config: C:\Users\tiflo\AppData\Roaming\nvda\profiles\correio.ini

Rui Fontes



Às 18:59 de 26/11/2018, Adriani90 escreveu:

**Comment by DrSooom** [comment]
Could somebody please explain me why I'm not hearing the error sound on starting Microsoft Outlook 2010 with NVDA 2018.4 RC1 Portable anymore, even when errors are logged at the debug logging level? [Here](https://github.com/nvaccess/nvda/files/2665647/8961_NVDA.2018.4.RC1_Outlook.2010_No.error.sound.log) is a new logfile for this. See line 136 to 249.

And when I set the logging level to "INFO", I just get this error message in the logfile, but also with no error sound feedback with NVDA 2018.4 RC1 Portable:
> ERROR - RPC process 9840 (nvda_slave.exe) (02:07:53.061):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 94, in main
  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject
  File "comtypes\__init__.pyo", line 1247, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Vorgang nicht verfÃ¼gbar

And quite interesting: I never noticed that I also get the same error with NVDA 2018.1 (installed). At the INFO-level I'm getting the following message without any error sound feedback on starting Microsoft Outlook 2010:
> ERROR - RPC process 8924 (nvda_slave.exe) (02:31:41.153):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 91, in main
  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject
  File "comtypes\__init__.pyo", line 1245, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Vorgang nicht verfÃ¼gbar

So I changed the title of this issue a little bit, because it doesn't seem to be related to NVDA 2018.4 Beta 1/RC1 itself. I only listened to the error sound feedback, which could be a mistake here by myself.

**Comment by Adriani90** [comment]
The error is still there but it does not strongly impacts NVDA‘s functionality. Error sounds are always played only in Alpha and Beta.

Von meinem iPhone gesendet

**Comment by DrSooom** [comment]
Same behavior with NVDA alpha-17252,7e26d874.

**Comment by DrSooom** [comment]
This issue still exists with NVDA 2019.2 Beta-18176. [Here](https://github.com/nvaccess/nvda/files/3443012/8961_NVDA.2019.2.Beta-18176_Outlook.2010.txt) is the logfile.

**Comment by Qchristensen** [comment]
Just to confirm this is still present in Office 365 and NVDA 2019.3 beta 1 on Windows 10 Version 1903 build 18362.388
 
Office 365 Version: 
16.0.12228.20322 

Log snippet follows:

```
Input: kb(desktop):enter
IO - speech.speakTypedCharacters (09:20:07.874) - MainThread (16100):
typed word: out
DEBUGWARNING - watchdog._watcher (09:20:10.150) - watchdog (18332):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 150, in executeEvent
  File "eventHandler.pyc", line 165, in doPreGainFocus
  File "NVDAObjects\__init__.pyc", line 313, in objectInForeground
  File "NVDAObjects\__init__.pyc", line 225, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 220, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyc", line 104, in getPossibleAPIClasses
  File "_UIAHandler.pyc", line 551, in isUIAWindow
  File "_UIAHandler.pyc", line 529, in _isUIAWindowHelper

DEBUGWARNING - eventHandler.executeEvent (09:20:11.397) - MainThread (16100):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x038E66B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 485, in speakObject
  File "speech\__init__.pyc", line 318, in speakObjectProperties
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 761, in _get_name
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 34, in __call__
core.CallCancelled: COM call cancelled
DEBUGWARNING - watchdog._watcher (09:20:12.069) - watchdog (18332):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 912, in pumpAll
  File "IAccessibleHandler.pyc", line 635, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 531, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 551, in isUIAWindow
  File "_UIAHandler.pyc", line 529, in _isUIAWindowHelper

IO - speech.speak (09:20:13.025) - MainThread (16100):
Speaking [LangChangeCommand ('en'), 'Inbox - G Suite - quentin@nvaccess.org - Outlook']
IO - speech.speak (09:20:13.036) - MainThread (16100):
Speaking [LangChangeCommand ('en'), 'Table View', 'table']
IO - speech.speak (09:20:13.045) - MainThread (16100):
Speaking [LangChangeCommand ('en'), 'Group By: Expanded: Date: Today', 'grouping', 'expanded']
ERROR - RPC process 13484 (nvda_slave.exe) (09:20:13.266) - Dummy-1 (15596):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 99, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1245, in GetActiveObject
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147221021] Operation unavailable
DEBUGWARNING - Python warning (09:20:13.325) - MainThread (16100):
C:\Program Files (x86)\NVDA\library.zip\api.py:287: DeprecationWarning: Yield() is deprecated
IO - speech.speak (09:20:13.374) - MainThread (16100):
Speaking [LangChangeCommand ('en'), 'Waiting for Outlook...', 'dialog']
DEBUGWARNING - appModules.outlook.AppModule._registerCOMWithFocusJuggle (09:20:14.362) - MainThread (16100):
Error while pumping com events
Traceback (most recent call last):
  File "appModules\outlook.pyc", line 112, in _registerCOMWithFocusJuggle
  File "comtypes\client\_events.pyc", line 277, in PumpEvents
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147417835] OLE has sent a request and is waiting for a reply
IO - speech.speak (09:20:14.375) - MainThread (16100):
Speaking [LangChangeCommand ('en'), 'level 1', 'From Quentin Christensen via Groups.Io, Subject Re: [nvda-addons] 2019.3, Received Tue 2019/12/10 9:17 AM, Size 25 KB,', '2 of 27168']
IO - speech.speak (09:20:14.466) - MainThread (16100):
Speaking [LangChangeCommand ('en'), 'Inbox - G Suite - quentin@nvaccess.org - Outlook']

```

**Comment by Qchristensen** [comment]
Just updated the title as this isn't limited to Office 2010 or NVDA 2018.x

**Comment by Adriani90** [comment]
Still reproducible in NVDA 2024.4 RC.

**Comment by Adriani90** [comment]
This is still reproducible with NVDA alpha-53423,57f2e9dc (2026.1.0.53423)
and MS Outlook 365 version 2510.

I am not sure, but this RPC process error might affect performance in outlook in general.
I attach my log file, we can see lots of events added to the event limitter, different objectIDs.
Could it be possible that Outlook sends many events to accessibility API which are not relevant?
I think we should try to understand why there are so many events, because these might be one of the reason performance issues in Outlook are still valid since years.

cc: @michaelDCurran, @CyrilleB79 

Also @msftedad can you report this to the development team please?


[nvda_Outlook-error.txt](https://github.com/user-attachments/files/23548793/nvda_Outlook-error.txt)
