### ISSUE TITLE
Error in google Crome with NVDA 2018.4 Beta1

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8968]
### Steps to reproduce:
1. Open NVDA
2. Open Google Crome
3. Go too www.google.com
4. In browse mode, press e to go to the search field
5. Type something and press enter
6. Press nvda+page up
7. Press e to go to the search field and type something, then press enter.

### Actual behavior:
Following error comes almost everytime when pressing enter (log file is attached):
```
IO - inputCore.InputManager.executeGesture (20:49:42.720):
Input: kb(laptop):enter
ERROR - scriptHandler.executeScript (20:49:42.947):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible.script_caret_newLine of <baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x05FC6030>> with gesture u'Eingabe'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "editableText.pyo", line 154, in script_caret_newLine
  File "editableText.pyo", line 87, in _hasCaretMoved
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 201, in _findContentDescendant
COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
```

### Expected behavior:
No error should appear.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.4 Beta1

#### Windows version:
Windows 10 1809 Update

#### Name and version of other software in use when reproducing the issue:
Google Crome 70.0.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, 2018.3.1

[nvda_crome.txt](https://github.com/nvaccess/nvda/files/2605628/nvda_crome.txt)

**Comment by Adriani90** [comment]
@michaelDCurran is this something which is worthy to investigate? Actually it does not affect user experience at all but it might have other impacts. If not, then I am fine with it to close it.

**Comment by leonardder** [comment]
You're saying that you tested with 2018.3.2, but as far as I can see, you did not report whether the error also occurs there.

**Comment by Adriani90** [comment]
Yes also tested with NVDA 2018.3.2 and 2018.3.1 and the error is still there. However, it does not highly affect user experience. But it could be related to #9058.

**Comment by Adriani90** [comment]
The error does not occur anymore with NVDA alpha-20220,1c4519a6 and Chrome 83. Closing as works for me.

**Comment by Adriani90** [comment]
Reopening, itseems it is still occuring from time to time. The error is a bit more detailed now.

```

IO - inputCore.InputManager.executeGesture (01:20:24.086) - winInputHook (12852):
Input: kb(laptop):enter
ERROR - scriptHandler.executeScript (01:20:24.397) - MainThread (9008):
error executing script: <bound method EditableText.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x0091EF90>> with gesture 'Eingabe'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "editableText.pyc", line 188, in script_caret_newLine
  File "editableText.pyc", line 94, in _hasCaretMoved
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 94, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 202, in _findContentDescendant
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2States (01:20:24.421) - MainThread (9008):
could not get IAccessible2 states
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1632, in _get_IA2States
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (01:20:24.424) - MainThread (9008):
IAccessibleObject.attributes COMError (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (01:20:24.426) - MainThread (9008):
accRole failed: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (01:20:24.759) - MainThread (9008):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x007E02F0>
```

Using NVDA 2020.1 and Chrome 83.

**Comment by Adriani90** [comment]
I cannot reproduce anymore with Chrome Canary 125 and NVDA 2024.1 RC1. Closing as works for me.
