### ISSUE TITLE
Error when prompting for user account control

### ISSUE THREAD

**Issue by vincent-lg** [nvaccess/nvda#9016]
When an application requires for UAC, the window doesn't appear in focus.  When doing an Alt-Tab, then Alt+Y (to accept), this window closes and there's an error in the NVDA log.

### Steps to reproduce:

1. Open an application that requires user access control, like etcher.
2. When you're asked whether to continue and allow this as administrator, press Alt + Tab to get focus (focus isn't acquired by default).
3. Press the Yes or No button.

### Actual behavior:

In the NVDA log file can be found these lines (note: I'm not sure whether the first traceback relates to the same issue, the second definitely does):

```
error executing event: typedCharacter on <baseObject.Dynamic_UIItemListItemUIA object at 0x077E2570> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 908, in event_typedCharacter
  File "speech.pyo", line 679, in speakTypedCharacters
  File "api.pyo", line 248, in isTypingProtected
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 782, in _get_isProtected
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1067, in _get_states
  File "NVDAObjects\UIA\__init__.pyo", line 734, in _prefetchUIACacheForPropertyIDs
COMError: (-2147418094, 'The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call did not execute.', (None, None, None, 0, None))
ERROR - NVDAObjects.behaviors.LiveText._monitor (11:07:24.486):
Error getting initial lines
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyo", line 260, in _monitor
  File "NVDAObjects\window\winConsole.pyo", line 49, in _getTextLines
  File "winConsoleHandler.pyo", line 121, in getConsoleVisibleLines
  File "wincon.pyo", line 70, in GetConsoleScreenBufferInfo
WindowsError: [Error 6] The handle is invalid.
```

### Expected behavior:

I would think the UAC window should get focus in the first place.  But even if it doesn't, when closing it, NVDA shouldn't mind.

### System configuration:

* Installed NVDA 2018.4 (beta 2).
* Windows 10 64-bit.

#### Does the issue still occur after restarting your PC?

It unfortunately does.

#### Have you tried any other versions of NVDA?

No, it might have occurred during the shift from NVDA 2018.3 to 2018.4, though I'm not positive, since it doesn't cause a fatal error.

**Comment by josephsl** [comment]
Hi, does NVDA even read UAC dialog content when this happens? If not, you might want to check if UAC level is set to 34% (level 1). As for the second traceback, you’re not alone in experiencing this problem where NvDA appears to not fetch first few lines of terminal text. Thanks.

**Comment by Brian1Gaff** [comment]
This has been going on for ages in windows 7. I have now turned  it off 
completely so I never get asked. Its also interesting to note that Dropbox 
seems to now have an alert that opens behind the current window that asks 
delete from all machines when you attempt to delete a file in a windows 
folder managed by dropbox.
 Sadly I can only seem to choose yes and only after alt tabbing a lot to get 
it into focus.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
@vincent-lg are you still seeing this issue with NVDA 2020.1?
I guess this is also very related to #8389.

**Comment by Adriani90** [comment]
We didn't get and updates from the initial author since many years. I am closing this as abandoned. Please comment on this if you are still having this issue and we can reopen.
