### ISSUE TITLE
Language drop down not read when translating in Word 365

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9019]
### Steps to reproduce:
1. Select some text in Word
2. Open the context menu and press S to choose "Translate".
3. Press F6 to move to the trranslator task pane
4. Press TAB to the Edit just past the "From label".
5. Start typing a language.
6. Down arrow through the list of languages

### Actual behavior:

At step 4, NVDA reads only "Edit Blank"
At step 5, the letter typed is read.
At step 6, the text typed in the edit is read each time UP or DOWN ARROW is pressed.

### Expected behavior:

At Step 4, the edit box contains the last used language.  This should be read out.  When the focus moves to the edit box, the selected language is greyed out but still selected.

Also at Step 4, a drop-down list of languages opens.
At Step 5, the drop-down list of languages shrinks to only those which match the text typed.  This should be indicated.
At Step 6, the focus moves through the languages in the list.  The currently focused language should be reported.

#### NVDA Installed/portable/running from source:

Installed
#### NVDA version:
2018.4beta3
#### Windows version:
Windows 10 slow insider 18272.1000 
#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.11029.20079 
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
NVDA 2018.3.2
NVDA 2018.2.1

Also tried Narrator which reads the language better, but has trouble navigating through it.

**Comment by Adriani90** [comment]
@Qchristensen I cannot reproduce your issue exactly. The dialog is full of repetitive grouping reportings and some how NVDA switches the focus to a button when typing some letter of the language in the combobox.
Can you test with NVDA 2023.1 in Office 365 or 2016? Is this issue still occuring?

**Comment by Qchristensen** [comment]
Checking this again with:

NVDA 2023.1.0.27913 
 
Windows 11 (64-bit) Version: 22H2, Build: 22621.1555 
 
Office 365 (64-bit) Version: 16.0.16227.20244 

The behaviour is still the same.  Note that if you tab to the language and then use the arrows to move through, it DOES read the options.  The issue occurs if you start typing a letter to jump to a particular language.

I did also find when you tab to the language, to swap to, it reads out ALL the languages.

Log fragment from when I tabbed to the language to switch to:

IO - inputCore.InputManager.executeGesture (17:31:49.165) - winInputHook (17384):
Input: kb(desktop):tab
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (17:31:49.339) - MainThread (21896):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (17:31:49.339) - MainThread (21896):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (17:31:49.339) - MainThread (21896):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1590, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1505, in _get__IA2Relations
NotImplementedError
DEBUG - virtualBuffers.MSHTML.MSHTMLTextInfo._getTextPositionAttribute (17:31:49.459) - MainThread (21896):
textPositionValue=auto
IO - speech.speech.speak (17:31:49.488) - MainThread (21896):
Speaking [LangChangeCommand ('en_GB'), 'French\r\n\r\n\r\nAfrikaans\r\n\r\n, 'combo box', 'expanded', CancellableSpeech (still valid)]

NOTE: I cut out all the languages there except the first couple (they are all listed with a couple of carriage return / newline characters.  French is first in this case because I had previously arrowed to that language in my testing.  Continuing the log from the same point (Focus is on the language edit box and I'm about to press a letter to jump to the first language starting with that letter and try to arrow through the languages):


IO - speech.speech.speak (17:31:49.520) - MainThread (21896):
Speaking [LangChangeCommand ('en_GB'), 'edit', CancellableSpeech (still valid), 'blank']
IO - inputCore.InputManager.executeGesture (17:31:54.684) - winInputHook (17384):
Input: kb(desktop):b
IO - speech.speech.speak (17:31:54.765) - MainThread (21896):
Speaking [CharacterModeCommand(True), LangChangeCommand ('en_GB'), 'b', EndUtteranceCommand()]
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (17:31:54.816) - MainThread (21896):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (17:31:54.816) - MainThread (21896):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (17:31:54.816) - MainThread (21896):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1590, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1505, in _get__IA2Relations
NotImplementedError
IO - inputCore.InputManager.executeGesture (17:31:55.851) - winInputHook (17384):
Input: kb(desktop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (17:31:56.549) - MainThread (21896):
Caret didn't move before timeout. Elapsed: 100 ms
IO - speech.speech.speak (17:31:56.552) - MainThread (21896):
Speaking [LangChangeCommand ('en_GB'), 'b']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (17:31:56.582) - MainThread (21896):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (17:31:56.582) - MainThread (21896):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (17:31:56.582) - MainThread (21896):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1590, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1505, in _get__IA2Relations
NotImplementedError


Continuing to down arrow at this point produces similar errors.
