### ISSUE TITLE
virtualBuffers.gecko_ia2: Virtual cursor jumps to the searchfield when pressing enter on a heading on google search

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9058]
### Steps to reproduce:
1. Open google search in Firefox
2. search something
3. In browse mode, navigate with h to a result heading and press enter

### Actual behavior:
Virtual cursor jumps to the search field instead of opening the link. This does not occur everytime.

### Expected behavior:
NVDA should open the link.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2017.4 RC1

#### Windows version:
Windows 10 1809 Update

#### Name and version of other software in use when reproducing the issue:
Firefox 43.0.3.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment]
cc: @leonardder

**Comment by Adriani90** [comment]
I get following in the log file after pressing enter on the heading:


```
IO - inputCore.InputManager.executeGesture (17:38:17.634):
Input: kb(laptop):enter
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:17.694):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUG - editableText.EditableText._hasCaretMoved (17:38:17.848):
Caret move detected using bookmarks. Elapsed: 60 ms
DEBUGWARNING - scriptHandler.executeScript (17:38:17.855):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible.script_caret_newLine of <baseObject.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible object at 0x05B2B070>> with gesture u'Eingabe'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "editableText.pyo", line 159, in script_caret_newLine
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 201, in _findContentDescendant
COMError: (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (17:38:17.855):
IAccessibleObject.attributes COMError (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:17.855):
accRole failed: (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
IO - speech.speakTypedCharacters (17:38:17.855):
typed word: gutscheincodes
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:17.878):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:17.924):
accRole failed: (-2147417848, 'Das aufgerufene Objekt wurde von den Clients getrennt.', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (17:38:17.934):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x05B2FE10>
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:17.944):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:17.954):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.update (17:38:17.984):
Adding new treeInterceptor to runningTable: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x0598A170>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (17:38:18.005):
Buffer load took 0.018 sec, 188 chars
IO - speech.speak (17:38:18.065):
Speaking [u'rabatt codes f\xfcr leonidas, gutscheincodes - Google-Suche  Dokument  Besch\xe4ftigt']
IO - speech.speak (17:38:18.065):
Speaking [u'\xdcberschrift  Ebene 1', u'Links zur Barrierefreiheit']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:18.134):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:18.298):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:18.305):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:18.305):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:18.325):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:18.407):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:18.586):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:19.035):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:38:19.454):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (17:38:19.538):
Input: kb(laptop):h
IO - speech.speak (17:38:19.598):
Speaking [u'Suchmodi', u'\xdcberschrift  Ebene 1']
IO - inputCore.InputManager.executeGesture (17:38:19.829):
Input: kb(laptop):h
IO - speech.speak (17:38:19.885):
Speaking [u'Hinweise zum Datenschutz bei Google', u'\xdcberschrift  Ebene 3']
IO - inputCore.InputManager.executeGesture (17:38:20.055):
Input: kb(laptop):h
IO - speech.speak (17:38:20.134):
Speaking [u'Suchergebnisse', u'\xdcberschrift  Ebene 1']
IO - inputCore.InputManager.executeGesture (17:38:20.265):
Input: kb(laptop):h
IO - speech.speak (17:38:20.335):
Speaking [u'Webergebnisse', u'\xdcberschrift  Ebene 2']
IO - inputCore.InputManager.executeGesture (17:39:36.174):
Input: kb(laptop):enter
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (17:39:36.214):
doAction failed
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (17:39:36.214):
Clicking with mouse
IO - speech.speak (17:39:36.384):
Speaking [u'Suche  Kombinationsfeld  Reduziert  mit AutoVervollst\xe4ndigung  Eingabefeld', u'rabatt codes f\xfcr leonidas, gutscheincodes']
IO - inputCore.InputManager.executeGesture (17:39:39.056):
Input: kb(laptop):upArrow
IO - speech.speak (17:39:39.155):
Speaking [u'Link', u'Grafik', u'Google']
IO - inputCore.InputManager.executeGesture (17:39:39.437):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.525):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.535):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.535):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.545):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.556):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.563):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.563):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:39:39.575):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IO - speech.speak (17:39:39.585):
Speaking [u'Suche  Kombinationsfeld  Reduziert  mit AutoVervollst\xe4ndigung  Eingabefeld', u'rabatt codes f\xfcr leonidas, gutscheincodes']
```

**Comment by leonardder** [comment]
Can you reproduce this on NVDA 2018.3.2?

**Comment by Adriani90** [comment]
I have also found a way to reliably reproduce it:
1. After pressing enter to search something, press ctrl+end to go to the bottom of google webpage
2. Press shift+h multiple time until you land on a search result
3. Press enter.

I can reproduce this everytime when doing these steps.

**Comment by Adriani90** [comment]
Will test in 2018.3.2 soon.

**Comment by Adriani90** [comment]
@leonardder I can reproduce this back until NVDA 2017.3.
cc: @michaelDCurran

**Comment by Adriani90** [comment]
maybe it is also because of new design of the google page. Otherwise I cannot explain why this problem has not been identified until recently. Actually I have seen the first reportings yesterday on audiogames.net in the off-topic forum. There were more people who had this problem.

**Comment by Brian1Gaff** [comment]
Is that really the version of Firefox you are using?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment]
oh that‘s a typo. I am on Firefox 63.0.3. Thanks for the comment

**Comment by DrSooom** [comment]
If I'm remembering me correctly I guess I also recognised this strange behaviour with NVDA 2015.3 and Firefox 56.0.2 on win7x64 on my NUC. Google changed here something a few weeks ago. So I don't think that this is a new issue with NVDA 2018.4.

Recently I also sent Google via its feedback form a link to this issue here.

@Adriani90: Please update to Firefox 64.0. But I don't think that this will change something.

**Comment by Neurrone** [comment]
I'm also seeing something similar on Slack as well, where focus moves about unexpectedly when you try to read messages. Am unsure if its related.

**Comment by leonardder** [comment]
> 
> 
> I'm also seeing something similar on Slack as well, where focus moves about unexpectedly when you try to read messages. Am unsure if its related.

Confirmed.

**Comment by Elshara** [comment]
Just right click on the result on open in new tab. You'd want that anyways in case you need to exit that page in case your search for the same item isn't over.

**Comment by Adriani90** [comment]
This is not reproducible anymore with NVDA 2023.1 RC1 and Firefox 110. I am closing as works for me.
