### ISSUE TITLE
IE11+NVDA throws console errors when focus moves to an SVG

### ISSUE THREAD

**Issue by smhigley** [nvaccess/nvda#9060]
### Steps to reproduce:

Open the following html page in IE11, or use this link: http://jsfiddle.net/kbc9wgej/show, and then move browser focus to the SVG with NVDA running

```html
<!doctype html>
<html>
<head></head>
<body>
  <svg height="100" width="100">
    <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
  </svg>
</body>
</html>
```

### Actual behavior:
The page logs multiple script errors:`SCRIPT65535: Invalid calling object`, pointing to the first line of the document.

### Expected behavior:
No errors

#### NVDA Installed or portable:
installed

#### NVDA version:
2018.3.2

#### Windows version:
Windows 10 Enterprise, v1803

#### Name and version of other software in use when reproducing the issue:
IE 11.407

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
no

[nvda.log](https://github.com/nvaccess/nvda/files/2673275/nvda.log)

**Comment by Adriani90** [comment]
Following error is in the log, also with NVDA 2020.1:

```
ERROR - eventHandler.executeEvent (13:53:39.083) - MainThread (14252):
error executing event: mouseMove on <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x06D14C90> with extra args of {'x': 2005, 'y': 1082}
Traceback (most recent call last):
  File "eventHandler.pyc", line 213, in executeEvent
  File "eventHandler.pyc", line 94, in __init__
  File "eventHandler.pyc", line 102, in next
  File "NVDAObjects\__init__.pyc", line 1059, in event_mouseMove
  File "speech\__init__.pyc", line 338, in speakObjectProperties
  File "speech\__init__.pyc", line 413, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 825, in _get_states
  File "comtypes\client\lazybind.pyc", line 226, in __call__
  File "comtypes\automation.pyc", line 729, in _invoke
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147352319, None, (None, None, None, 0, None))
```

**Comment by Adriani90** [comment]
This is java script related, maybe the SVG is into an iFrame, the iFrame needs to be updated when putting the focus I guess. Here might be some good hints on this:
https://supportcenter.devexpress.com/ticket/details/q488306/script65535-invalid-calling-object-when-trying-to-print-from-ie10-on-example-e454

However, this error is only Internet explorer specific. IE support ended recently and so I am closing this issue. In fact it is not only related to NVDA.
