### ISSUE TITLE
firefox nightly v 66.0a1 (2018-12-17) 64-bit when trying to launch options firefox crashes

### ISSUE THREAD

**Issue by mhussaincov** [nvaccess/nvda#9084]
### Steps to reproduce:
launch firefox nightly the latest build.
have nvda 2018.4 running.
in firefox nightly, try to open the options menu via tools options.

### Actual behavior:

when the options menu item is pressed, firefox crashes.

### Expected behavior:
the options menu should launch with out Firefox crashing
#### NVDA installed/portable/running from source:

an installed copy of nvda 2018.4

#### NVDA version:
nvda 2018.4
#### Windows version:
v1809
#### Name and version of other software in use when reproducing the issue:
firefox nightly
#### Other information about your system:
this is a fresh install of windows 10
when I try to launch the options menu it works when nvda is not running and i'm running narrator

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by mhussaincov** [comment]
here is the log after firefox crashes.

INFO - __main__ (16:48:22.296):
Starting NVDA
INFO - core.main (16:48:22.459):
Config dir: C:\Users\majid\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (16:48:22.459):
Loading config: C:\Users\majid\AppData\Roaming\nvda\nvda.ini
INFO - core.main (16:48:22.561):
NVDA version 2018.4
INFO - core.main (16:48:22.561):
Using Windows version 10.0.17763 workstation
INFO - core.main (16:48:22.561):
Using Python version 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
INFO - core.main (16:48:22.561):
Using comtypes version 1.1.3
INFO - core.main (16:48:22.561):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDrivers.espeak.SynthDriver.__init__ (16:48:22.997):
Using eSpeak NG version 1.49.3 dev
INFO - synthDriverHandler.setSynth (16:48:23.109):
Loaded synthDriver espeak
INFO - core.main (16:48:23.109):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5
INFO - brailleInput.initialize (16:48:23.119):
Braille input initialized
INFO - braille.initialize (16:48:23.119):
Using liblouis version 3.7.0
INFO - braille.BrailleHandler.setDisplayByName (16:48:23.119):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (16:48:23.150):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (16:48:23.160):
UIAutomation: IUIAutomation6
INFO - core.main (16:48:23.424):
NVDA initialized
ERROR - eventHandler.executeEvent (16:49:31.446):
error executing event: alert on <baseObject.Dynamic_DialogMozillaIAccessible object at 0x055391D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\IAccessible\__init__.pyo", line 1410, in event_alert
  File "speech.pyo", line 416, in speakObject
  File "documentBase.pyo", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 87, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 204, in _findContentDescendant
LookupError: Object has no text descendants
ERROR - eventHandler.executeEvent (16:57:44.214):
error executing event: caret on <baseObject.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible object at 0x0574E270> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "browseMode.pyo", line 1190, in event_caret
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\behaviors.pyo", line 175, in event_caret
  File "editableText.pyo", line 299, in detectPossibleSelectionChange
  File "editableText.pyo", line 306, in _updateSelectionAnchor
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 625, in compareEndPoints
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 600, in _getAncestors
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 172, in _getEmbedding
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 168, in _makeRawTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyo", line 36, in _getRawTextInfo
AttributeError: 'NoneType' object has no attribute 'role'
ERROR - virtualBuffers.VirtualBuffer._loadBuffer (17:00:08.867):
Traceback (most recent call last):
  File "virtualBuffers\__init__.pyo", line 439, in _loadBuffer
WindowsError: [Error 1726] The remote procedure call failed

**Comment by lukaszgo1** [comment]
I am also experiencing this.
The link to the crash is https://crash-stats.mozilla.org/report/index/bp-048f7328-3382-4127-a7ee-255010181217
cc @jcsteh

**Comment by jcsteh** [comment]
There's a Mozilla bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1513332

A fix is already on the way.

**Comment by jcsteh** [comment]
I'm going to close this, as this is very clearly a trivial Firefox bug which should be fixed quickly and there's no need to track it here. If you want to track progress, please watch the Mozilla bug. Thanks.
