### ISSUE TITLE
Outlook 2016: COM error when moving through calendar

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#9087]
### Steps to reproduce:
Note, it seems that this does not always cause the issue. It is very elusive

1. Create a recurring event in the Outlook calendar.
2. Delete only the first instance of the recurring event.
3. With tab in the day view, focus the next occurrence of the event.

### Actual behavior:
The following error is raised

<details>
<summary>Log snippet</summary>
<pre>
ERROR - eventHandler.executeEvent (15:30:51.079):
error executing event: gainFocus on <appModules.outlook.CalendarView object at 0x052D1ED0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 966, in event_gainFocus
  File "appModules\outlook.pyc", line 384, in reportFocus
  File "comtypesMonkeyPatches.pyc", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 168, in __getattr__
  File "comtypes\automation.pyc", line 729, in _invoke
COMError: (-2147352567, 'Er is een uitzondering opgetreden.', (None, None, None, 0, None))
<?pre>
</details>

This error translates to unhandled exception.

### Expected behavior
The appointment reads as expected.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-16458

#### Windows version:
Windows 10 version 1809, non insider build

#### Name and version of other software in use when reproducing the issue:
Outlook 16.0.11029.20108

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, NVDA 2017.4

**Comment by leonardder** [comment]
See also #8029. I'm afraid that the object model is getting in the way of a smooth calendar experience more and more.

**Comment by Adriani90** [comment]
@leonardder did you see this issue during last months / years still with newer version of NVDA and newer updates in Outlook 2016?

**Comment by Adriani90** [comment]
@CyrilleB79 could you please test in Outlook 2016 whether this issue occurs for you with NVDA 2024.4 or alpha?

**Comment by Adriani90** [comment]
No updates upon request since many years, I am closing as abandoned. if you are still having this issue, please comment and we can reopen.
I cannot reproduce in MS office 365 at least.
