### ISSUE TITLE
Word 2016 UIA: Table Cells with Long Text Cause Python Recursion Error

### ISSUE THREAD

**Issue by jage9** [nvaccess/nvda#9090]
### Steps to reproduce:
Using Office 2016 with UIA enabled, load the attached file. Move to the table and then tab through the cells.

### Actual behavior:
NVDA hangs on the table cell for about 10 seconds, then fires a Python recursion error. Log output is below.

### Expected behavior:
NVDA should read the cell contents.

#### Have you tried any other versions of NVDA? N/A, UIA support not implemented

Here is the log output.

ERROR - scriptHandler.executeScript (15:06:19.713):
error executing script: <bound method Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject.script_tab of <abc.Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x058681F0>> with gesture u'shift+tab'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "NVDAObjects\window\winword.pyc", line 1376, in script_tab
  File "speech.pyc", line 774, in speakTextInfo
  File "NVDAObjects\UIA\wordDocument.pyc", line 185, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 638, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 614, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 614, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 614, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 614, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 614, in _getTextWithFieldsForUIARange
... repeats about 800 more times.
  File "NVDAObjects\UIA\__init__.pyc", line 614, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 614, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 548, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\wordDocument.pyc", line 121, in _getControlFieldForObject
  File "NVDAObjects\UIA\__init__.pyc", line 414, in _getControlFieldForObject
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1315, in _get_table
  File "NVDAObjects\__init__.pyc", line 85, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 765, in findOverlayClasses
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 976, in _get_TextInfo
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 961, in _get_UIATextPattern
  File "NVDAObjects\UIA\__init__.pyc", line 942, in _getUIAPattern
  File "comtypes\__init__.pyc", line 1160, in QueryInterface
[NVDA table recursion example.docx](https://github.com/nvaccess/nvda/files/2692150/NVDA.table.recursion.example.docx)
ArgumentError: argument 1: <type 'exceptions.RuntimeError'>: maximum recursion depth exceeded while calling a Python object

**Comment by leonardder** [comment]
@michaeldcurran: would you be able to address this as part of #8919, or is it already covered?

**Comment by michaelDCurran** [comment]
This is a rather serious bug in Microsoft Word. In short, for row 2 column 1 in the attached document, getting a UIA text range from the cell's UIA element, and then getting the UIA enclosing element from the text range does not result in the cell UIA element, rather it results in the root UIA element for the document.  
@jage9  apart from the content of the cells being fairly long, is there anything else special about  row 2 column 1? How exactly did you create it?

**Comment by jage9** [comment]
I believe the only things that may contribute to this occurrence are A. 
a cell with a lot of text and B. perhaps this cell having some of the 
text cropped, though I am not 100 percent on B. I did have a long text 
field that did not cause an error in one of the right most columns, thus 
my theory on cropped text.

**Comment by michaelDCurran** [comment]
According to my machine, that cell is set to wrap text, and that row has 
no set height. Therefore, the text should be completely contained within 
the cell and not cropped at all if I understand correctly.

Is this something you have only seen with this document, or are there 
other real-world documents that have shown this issue?

I'm trying to Gage the severity of this issue in regards to whether it 
should hold back UIA in MS Word by default. Currently I am still finding 
no workaround for this bug in MS Word and I'm not sure when it would get 
fixed.

**Comment by jage9** [comment]
Hello.

I encountered this bug originally with a table for a private client, so 
wasn't able to provide that specific table as an example. But the bug 
occurred frequently with large blocks of text within a cell, and it only 
took me about 2 minutes to put enough text into a cell on a test table 
to reproduce the bug. I took a line of text, and pasted it several times 
in the same cell to create the error condition.We could try increasing 
the cell height/width too see if it would effect anything. It may be 
good to get someone to look at this visually as well to see if anything 
is obvious.

**Comment by jage9** [comment]
Sorry I'm just replying to this now, but that seems much better than a full-on lockup. Thanks for looking into this. Does the spelling errors PR play into this one as well?

**Comment by lukaszgo1** [comment]
@jage9 If this is fixed for your shoudn't this issue be closed?

**Comment by Adriani90** [comment]
Is this fixed? I thought @jage9's comment above is just a reply to mick's comment. Is there a PR which solved this issue?

**Comment by Adriani90** [comment]
@jage9 is this still reproducible in NVDA 2020.1?
