### ISSUE TITLE
Adding a "Note" to Excel causes NVDA to stop speaking.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9194]
### Steps to reproduce:

(Tested in Excel 365 / Office version 16.0.11126.20200 )

1. Open Excel to a blank worksheet.
2. On any cell, press the APPLICATIONS KEY to open the context menu.
3. Select "New note".
4. NVDA stops talking. Type something.
5. Press ESCAPE to save the note.  NVDA does not report anything.
6. Press ESCAPE again to return to Excel.

### Actual behavior:

When activating the "New Note" command in the context menu, the following errors are generated:
IO - speech.speak (08:02:44.078):
Speaking [LangChangeCommand ('en_GB'), u'New Note  N']
IO - inputCore.InputManager.executeGesture (08:02:45.660):
Input: kb(desktop):enter
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:02:45.780):
oleacc.AccessibleObjectFromEvent with window 526786, objectID -4 and childID 0: [Error -2147024809] The parameter is incorrect
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (08:02:45.786):
accRole failed: (-2147417848, 'The object invoked has disconnected from its clients.', (None, None, None, 0, None))
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:02:45.821):
oleacc.AccessibleObjectFromEvent with window 1182460, objectID 27 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:02:45.822):
oleacc.AccessibleObjectFromEvent with window 1182460, objectID 33 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor._get_isAlive (08:02:45.948):
could not compare sheet names
Traceback (most recent call last):
  File "NVDAObjects\window\excel.pyo", line 452, in _get_isAlive
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke
COMError: (-2147418111, 'Call was rejected by callee.', (None, None, None, 0, None))
DEBUGWARNING - eventHandler.executeEvent (08:02:45.960):
error executing event: gainFocus on <baseObject.Dynamic_IAccessibleExcel7WindowWindowNVDAObject object at 0x052CDC50> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\window\excel.pyo", line 668, in event_gainFocus
  File "NVDAObjects\window\excel.pyo", line 628, in _getSelection
  File "comtypes\client\dynamic.pyo", line 110, in __getattr__
  File "comtypes\automation.pyo", line 708, in GetIDsOfNames
COMError: (-2147418111, 'Call was rejected by callee.', (None, None, None, 0, None))

After escape is pressed to close the note and return to the spreadsheet, the following is generated:
IO - inputCore.InputManager.executeGesture (08:05:47.048):
Input: kb(desktop):escape
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:05:47.144):
oleacc.AccessibleObjectFromEvent with window 1182460, objectID 2409 and childID 0: [Error -2147467259] Unspecified error
IO - inputCore.InputManager.executeGesture (08:06:02.434):
Input: kb(desktop):rightArrow
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:06:02.456):
oleacc.AccessibleObjectFromEvent with window 1182460, objectID 2461 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:06:02.457):
oleacc.AccessibleObjectFromEvent with window 1182460, objectID 2462 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (08:06:02.464):
oleacc.AccessibleObjectFromEvent with window 1182460, objectID 2464 and childID 0: [Error -2147467259] Unspecified error

NVDA stops speaking and sometimes recovers and sometimes you need to alt+tab away and back.  In this case, I pressed tab to move to a new cell and typed something and NVDA did come back, but then gave an error in the log (didn't cause any noticeable problem at this point):

IO - inputCore.InputManager.executeGesture (08:06:04.773):
Input: kb(desktop):2
DEBUGWARNING - eventHandler.executeEvent (08:06:04.792):
error executing event: typedCharacter on <NVDAObjects.window.excel.ExcelCell object at 0x052899F0> with extra args of {'ch': u'2'}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\window\excel.pyo", line 1222, in event_typedCharacter
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\window\excel.pyo", line 1195, in _get_states
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke
COMError: (-2147418111, 'Call was rejected by callee.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor._get_isAlive (08:06:04.828):
could not compare sheet names
Traceback (most recent call last):
  File "NVDAObjects\window\excel.pyo", line 452, in _get_isAlive
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke
COMError: (-2147418111, 'Call was rejected by callee.', (None, None, None, 0, None))
IO - speech.speak (08:06:04.834):
Speaking [LangChangeCommand ('en_GB'), u'Formula Bar  edit']
IO - speech.speak (08:06:04.838):
Speaking [LangChangeCommand ('en_GB'), u'baseline', u'2']

### Expected behavior:

This is Excel's native method for entering notes (previously called comments).  SHIFT+F2 is the recommended method for entering these, however with the change by Microsoft to add both notes and comments, it is not clear which is which (As per #9193) so I expect we will see more users encountering this again.  (I'm sure there are older, closed issues for this).

Ideally override this function when called from the context menu to work as per SHIFT+F2 if working with Excel's native notes is not possible.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2018.4.1
#### Windows version:
10, build 18272.1000 
#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.11126.20200 

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by dkager** [comment]
I can reproduce this. Something similar happens in Excel 2013, but I have yet to check if any errors are logged.

**Comment by Qchristensen** [comment]
Just a quick, er, note, on this:  It still happens with:

NVDA 2025.2
Office 365 (64-bit) Version: 16.0.19029.20156 
Windows 11 (64-bit) Version: 24H2, Build: 26100.4946 

The workaround is to create notes with SHIFT+F2 rather than via the context menu.  I wonder if the action for this issue could be to override when a user tries this and display NVDA's new note dialog in the same was as when shift+f2 is pressed?

(Note that for the same reason users are encouraged to use the elements list to find notes in Excel rather than the "next note" and "previous note" functions on the review ribbon - so if we can override functions they are two more which could be looked at).

**Comment by CyrilleB79** [comment]
@Qchristensen what about Excel with UIA? and what about Narrator?

If the issue also occurs with Narrator, it should be reported to Microsoft.

The problem with NVDA's shift+F2 specific workaround dialog is that it does not allow all what the native dialog does, e.g.:
* modify/delete the name of the person who has written the note
* display or modify text formatting
