### ISSUE TITLE
COM error when activating specific link in browse mode in MS excel help screen

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#9241]
### Steps to reproduce:
1. Open MS excel
2. Press esc key
3. Press F1
4. Enable browse mode
5. Press k to activate the first link
### Actual behavior:
The following error occurs:
ERROR - core.CorePump.run (08:48:12.631):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 487, in run
  File "IAccessibleHandler.pyo", line 900, in pumpAll
  File "IAccessibleHandler.pyo", line 671, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 687, in processFocusNVDAEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyo", line 1066, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyo", line 793, in _get_states
  File "comtypes\client\dynamic.pyo", line 110, in __getattr__
  File "comtypes\automation.pyo", line 708, in GetIDsOfNames
COMError: (-2147352570, '\xbe\xcb \xbc\xf6 \xbe\xf8\xb4\xc2 \xc0\xcc\xb8\xa7\xc0\xd4\xb4\xcf\xb4\xd9.', (None, None, None, 0, None))
### Expected behavior:
NVDA should not error
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-16691,10590c87, 2018.4.1 stable
#### Windows version:
Version:1809(OS 빌드 17763.253)
#### Name and version of other software in use when reproducing the issue:
Office 365 Excel®  (16.0.11126.20192) 64bit
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes. This issue can also be reproduced in 2018.4 stable.

**Comment by Adriani90** [comment]
this works as expected with NVDA alpha-20206,dba33431 and Excel 365. No error anymore. Closing as works for me.
