### ISSUE TITLE
MS Excel 2016 / 365: Error when pressing f2 to edit a cell

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#9317]
###Steps to reproduce:
1. Open a blank excel sheet in ms Excel 2016 / 365
2. In Excel's options enable "allow direct editing in cells" (works only in NVDA alpha-16813,a0b991af and later)
3. Press f2 while focusing a cell

### Actual behavior:
Following error is in the log:

```
Input: kb(laptop):f2
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (15:10:35.628):
oleacc.AccessibleObjectFromEvent with window 658010, objectID 1922 and childID 0: [Error -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (15:10:35.631):
oleacc.AccessibleObjectFromEvent with window 658010, objectID 1930 and childID 0: [Error -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (15:10:35.631):
oleacc.AccessibleObjectFromEvent with window 658010, objectID 1928 and childID 0: [Error -2147467259] Unbekannter Fehler
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (15:10:35.726):
oleacc.AccessibleObjectFromEvent with window 658010, objectID 1926 and childID 0: [Error -2147467259] Unbekannter Fehler
DEBUGWARNING - NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor._get_isAlive (15:10:35.799):
could not compare sheet names
Traceback (most recent call last):
  File "NVDAObjects\window\excel.pyc", line 457, in _get_isAlive
  File "comtypesMonkeyPatches.pyc", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 168, in __getattr__
  File "comtypes\automation.pyc", line 729, in _invoke
COMError: (-2147418111, 'Aufruf wurde durch Aufgerufenen abgelehnt.', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (15:10:35.799):
Killed treeInterceptor: <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x057BCE50>
```

### Expected behavior:
No error is raised

### NVDA installed/portable/running from source:
Installed

### NVDA version:
alpha-16813,a0b991 af

### Windows version:
Windows 10 1809 Update

### Name and version of other software in use when reproducing the issue:
MS Excel 2016, MS Excel 365

### Other questions

####Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
No, Alphas or official releases before this one does not work with editing in cells enabled.

**Comment by Adriani90** [comment]
It is important to notice that this has not an obvious user impact, as long as the cell does not contain a dropdown list. If a dropdown list is contained, then NVDA cannot locate the dropdown after expanding the list and choosing an item. I guess the com error is one of the reasons for that.

**Comment by Adriani90** [comment]
Closing in favor of #10612 which contains a more detailed log.
