### ISSUE TITLE
Firefox: table navigation commands caused "executing Script error"

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#9476]
This case occurs while using table navigation commands to move to columns or rows.

### Steps to reproduce:
1. Open [this link](http://pchome.megatime.com.tw/group/mkt5/cidE003/050_4.html).
2. Press t to move to table.
3. Press control+alt+rightArrow fifth times to move to column6.
#### Actual behavior:
The system cursor may stop at column3 or column 4. (With log message below.)
ERROR - scriptHandler.executeScript (10:34:03.625):
error executing script: <bound method Gecko_ia2.script_nextColumn of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x063C6C10>> with gesture u'control+alt+\u5411\u53f3\u9375'

#### Expected behavior:
The cursor moves to column6.

#### NVDA Installed/portable/running from source:
Installed.

#### NVDA version:
2019.1

#### Windows version:
6.1.7601 service pack 1

#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 66.0.2 (x64 zh-TW)

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
NO.
[nvda.log](https://github.com/nvaccess/nvda/files/3061811/nvda.log)

**Comment by DrSooom** [comment]
CC: @jcsteh and @MarcoZehe; It seems that there is some auto-updated content on this site.

**Comment by tapper82** [comment]
This is on win 7.
• Mainstream support ended on January 13, 2015
• Extended support ends on January 14, 2020

**Comment by tapper82** [comment]
Cant reproduce this on windows 10 ff 68.1

**Comment by Adriani90** [comment]
This is still reproducible in Firefox 76 with NVDA alpha-20220,1c4519a6.

I get following error in the log:

```
IO - inputCore.InputManager.executeGesture (00:22:59.615) - winInputHook (9708):
Input: kb(laptop):alt+control+downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (00:22:59.641) - MainThread (5764):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (00:22:59.643) - MainThread (5764):
error executing script: <bound method DocumentWithTableNavigation.script_nextRow of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x01463B70>> with gesture 'Alt+Strg+Pfeiltaste nach unten'
Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 429, in _getTableCellAt
AttributeError: 'IAccessible' object has no attribute 'IAccessibleTable2Object'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "documentBase.pyc", line 170, in script_nextRow
  File "documentBase.pyc", line 157, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 441, in _getNearestTableCell
  File "documentBase.pyc", line 134, in _getNearestTableCell
  File "virtualBuffers\gecko_ia2.pyc", line 431, in _getTableCellAt
AttributeError: 'IAccessible' object has no attribute 'IAccessibleTableObject'
```

**Comment by Adriani90** [comment]
it's strange, that this works correctly in Chrome but not in Firefox.
cc: @jcsteh

**Comment by jcsteh** [comment]
This page frequently toggles CSS visibility on its main content area. That is pretty strange (and I'd say rare), but I've filed a Firefox bug to try to deal with this better: https://bugzilla.mozilla.org/show_bug.cgi?id=1638713
That said, this is unlikely to be fixed quickly, since I've only ever seen this odd behaviour on this one site.
