### ISSUE TITLE
Problem exiting settings gui for synth in NVDA version beta-17453,305bb049

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#9684]
### Steps to reproduce:

Run the above version of nvda. I ran it as portable
Go into preferences/settings/synths and fiddle about a bit, then  go and look at the various settings and tab down them till you reach OK and  activate it.

### Actual behavior:
 it gives an error as in the log at the end of this report
### Expected behavior:
It should exit the gui as normal
### System configuration
Windows 7pro 64bit 
nvda running portably.

#### Other information about your system:
I5 running at 3.2ghz 8 gig ram 512 gig ssd
Synths installed. Espeak, thich was used for the test, Speech Platform, SSappi 5 and4.

#### Does the issue still occur after restarting your PC?

Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Alpha and Threshold have the error stable does not.

Log output at the error

snip

Input: kb(desktop):tab
IO - speech.speak (16:27:14.236):
Speaking [LangChangeCommand ('en_GB'), u'Use spelling functionality if supported  check box  checked  Alt+s']
IO - inputCore.InputManager.executeGesture (16:27:14.861):
Input: kb(desktop):tab
IO - speech.speak (16:27:14.903):
Speaking [LangChangeCommand ('en_GB'), u'OK  button']
IO - inputCore.InputManager.executeGesture (16:27:15.644):
Input: kb(desktop):enter
ERROR - unhandled exception (16:27:15.644):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 602, in onOk
  File "gui\settingsDialogs.pyc", line 596, in _doSave
  File "gui\settingsDialogs.pyc", line 781, in onSave
RuntimeError: wrapped C/C++ object of type Choice has been deleted
IO - inputCore.InputManager.executeGesture (16:27:18.259):
Input: kb(desktop):control+alt+r
IO - speech.speak (16:27:18.354):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - speech.speak (16:27:18.418):
Speaking [LangChangeCommand ('en_GB'), u'reboot nvda with log  terminal']
IO - speech.speak (16:27:18.421):
Speaking [LangChangeCommand ('en_GB'), u'80 space', u'blank']
INFO - core.main (16:27:18.502):
Exiting
DEBUG - core._terminate (16:27:18.502):
Terminating updateCheck
DEBUG - core._terminate (16:27:18.502):
Terminating watchdog
DEBUG - core._terminate (16:27:18.502):
Terminating global plugin handler
DEBUG - core._terminate (16:27:19.005):
Terminating gui
ERROR - gui.terminate (16:27:19.006):
Destroyed but not deleted instance of settings dialog exists: <gui.settingsDialogs.NVDASettingsDialog object at 0x055DED00>
DEBUG - gui.settingsDialogs.SettingsDialog._setInstanceDestroyedState (16:27:19.016):
Setting state to destroyed for instance: <gui.settingsDialogs.NVDASettingsDialog object at 0x055DED00>
Current _instances {<gui.settingsDialogs.NVDASettingsDialog object at 0x055DED00>: 1}
DEBUG - fileUtils.FaultTolerantFile (16:27:19.035):
C:\nvda release candidate\userConfig\nvda.ini7n0btf.tmp
INFO - config.ConfigManager.save (16:27:19.043):
Base configuration saved
DEBUG - core.main (16:27:19.043):
calling lose focus on object with focus

snip

I do hope this is of use. Sadly I do not have a windows 10 machine to test it on.
 This however has  a very recently installed Windows 7 on it after the death of my hard drive.
 Brian

**Comment by Brian1Gaff** [comment]
Today I completely reinstalled all the snapshots and the problem seems to be gone. So it could well be something that was not being removed from a previous snapshot causing these issues. Of course strange things still do occur in Thresold but I suppose that is to be expected.
 It would be interesting to see if anyone else has the issue and if they do, I'd suggest a clear out and reinstall and see if it fixes things.
Brian
