### ISSUE TITLE
Skype for Business 2016: Error each Time a new Message is Sent

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9696]
Tested on Windows 10 1803 X64 with the latest NVDA snapshot (alpha-17533,549a6aaa).

Upon updating to the latest build of Skype for Business 2016 (16.0.4861.1000), an error is output in NVDA's log - see below. This same error is also sometimes generated when navingating around the main window of an open conversation - this error did not occur with previous builds of the client.

error executing event: liveRegionChange on <appModules.lync.NetUIRicherLabel object at 0x065ACDF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "appModules\lync.pyc", line 26, in event_liveRegionChange
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by elliott94** [comment]
Happy for this to be closed - this isn't happening for me now. :)
