### ISSUE TITLE
Windows 10: Start menu's search field does not always get focus

### ISSUE THREAD

**Issue by DataTriny** [nvaccess/nvda#9775]
### Steps to reproduce:
1. Open NVDA,
2. Open another software such as Firefox,
3. Press the Windows key to open the Start Menu.

### Actual behavior:
When the Start Menu appears, sometimes the search box wont have the focus. When such thing occures, it is impossible to navigate to Cortana's search bar at all.

### Expected behavior:
Start Menu's search field should always be present, and it should always get focused by default.

#### NVDA installed/portable/running from source:
NVDA is installed.

#### NVDA version:
NVDA version 2019.1.1.

#### Windows version:
Windows 10 Education, version 1903.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I got the same result on a source copy of NVDA.

#### Additional context
This issue seemed to appear after updating to Windows 10 version 1903. However, I haven't yet found a way to reproduce it all the time. I have attached a part of the log, but I don't think that it contains interesting information.
[Log.txt](https://github.com/nvaccess/nvda/files/3306476/Log.txt)

**Comment by josephsl** [comment]
Hi, if you have add-ons, what happens when you restart NVDA with add-ons off? Thanks.

**Comment by Neurrone** [comment]
I can also reproduce this almost all the time on Windows 10 1809.

**Comment by DataTriny** [comment]
Hello @josephsl,
As I wrote I got the same results on a source copy of NVDA (on which I have no add-ons installed). Strange thing is that I don't remember having this issue on Windows 10 version 1809.

**Comment by XLTechie** [comment]
For what it's worth, I experience this as well, on 1809, NVDA 2019.1.1.

It is intermittent, however, and so I have not tried with addons disabled: 
there's no telling how long I might have to wait with addons disabled, before it 
happens again.

I will try to grab a log next time. I had assumed it was just a windows 
quirk--the start menu not appearing or some such.

**Comment by Brian1Gaff** [comment]
If you try this on a beta snap do you hear any actual error sound when you 
press to get the start box up. I found this on a friends machine and I 
wondered if handling the error sometimes results in it missing the focus 
event.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by XLTechie** [comment]
I had experienced this from time to time on 1809. However I have started experiencing it about once-twice per day on 1903.

Here is a partial log from 2019.1.1, which I have annotated:

#### At this point I left an MS settings dialog via alt-F4, and returned to desktop.

```
IO - speech.speak (12:36:25.450):
Speaking [LangChangeCommand ('en_GB'), u'Desktop  list']
IO - speech.speak (12:36:25.505):
Speaking [LangChangeCommand ('en_GB'), u'2018-08-05  check box  selected  checked']
DEBUG - appModuleHandler.cleanup (12:36:39.250):
application systemsettings closed
IO - speech.speak (12:36:39.269):
Speaking [LangChangeCommand ('en_GB'), u'2018-08-05  check box  selected  checked']
```

#### Somewhere in here I pressed the Windows key, but it doesn't seem to register.

```
IO - speech.speak (12:46:15.006):
Speaking [LangChangeCommand ('en_GB'), u'2018-08-05  check box  selected  checked']
```

#### Since I was going to do a search, and since there was no speech after pressing the Windows key, I tried just pressing a letter.

```
IO - inputCore.InputManager.executeGesture (12:46:18.773):
Input: kb(desktop):a
IO - speech._speakSpellingGen (12:46:18.823):
Speaking character u'a'
DEBUG - queueHandler.registerGeneratorObject (12:46:18.823):
Adding generator 549
IO - speech.speak (12:46:18.848):
Speaking [LangChangeCommand ('en_GB'), u'amendments-revised.doc  check box  selected  checked']
```

#### Obviously I was still on the desktop, so I tried again by hitting the windows key, which again is not logged.

```
DEBUG - queueHandler.pumpAll (12:46:18.854):
generator 549 finished
IO - speech.speak (12:46:21.115):
Speaking [LangChangeCommand ('en_GB'), u'Start  window']
IO - speech.speak (12:46:21.124):
Speaking [LangChangeCommand ('en_GB'), u'Cortana  window']
IO - speech.speak (12:46:21.132):
Speaking [LangChangeCommand ('en_GB'), u'Search box  edit']
DEBUG - NVDAObjects.NVDAObject._get_placeholder (12:46:21.134):
Potential unimplemented child class: <NVDAObjects.Dynamic_StartMenuSearchFieldSearchFieldEditableTextWithoutAutoSelectDetectionUIA object at 0x0560F4D0>
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.134):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.134):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Fetching parents starting from enclosingElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Hit root
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Done fetching parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Done generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Done yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Yielding balanced fields for textRange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
no children
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.138):
Yielding text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (12:46:21.138):
_getTextWithFields_text start
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (12:46:21.138):
Walking by unit None
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (12:46:21.138):
With further units of: [1, 2, 0]
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (12:46:21.142):
Done _getTextWithFields_text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (12:46:21.142):
_getTextWithFieldsForUIARange end
IO - speech.speak (12:46:21.144):
Speaking [LangChangeCommand ('en_GB'), u'blank']
IO - inputCore.InputManager.executeGesture (12:46:22.459):
Input: kb(desktop):a
IO - speech._speakSpellingGen (12:46:22.762):
Speaking character u'a'
DEBUG - queueHandler.registerGeneratorObject (12:46:22.763):
Adding generator 550
IO - inputCore.InputManager.executeGesture (12:46:22.793):
Input: kb(desktop):l
DEBUG - queueHandler.pumpAll (12:46:22.898):
generator 550 finished
IO - speech._speakSpellingGen (12:46:22.918):
Speaking character u'l'
DEBUG - queueHandler.registerGeneratorObject (12:46:22.918):
Adding generator 551
DEBUG - queueHandler.pumpAll (12:46:22.944):
generator 551 finished
IO - inputCore.InputManager.executeGesture (12:46:22.956):
Input: kb(desktop):l
IO - speech._speakSpellingGen (12:46:23.305):
Speaking character u'l'
DEBUG - queueHandler.registerGeneratorObject (12:46:23.305):
Adding generator 552
DEBUG - queueHandler.pumpAll (12:46:23.319):
generator 552 finished
IO - inputCore.InputManager.executeGesture (12:46:23.408):
Input: kb(desktop):o
IO - speech._speakSpellingGen (12:46:23.601):
Speaking character u'o'
DEBUG - queueHandler.registerGeneratorObject (12:46:23.601):
Adding generator 553
IO - inputCore.InputManager.executeGesture (12:46:23.674):
Input: kb(desktop):w
DEBUG - queueHandler.pumpAll (12:46:23.938):
generator 553 finished
IO - speech._speakSpellingGen (12:46:23.938):
Speaking character u'w'
DEBUG - queueHandler.registerGeneratorObject (12:46:23.938):
Adding generator 554
DEBUG - queueHandler.pumpAll (12:46:23.963):
generator 554 finished
DEBUG - NVDAObjects.UIA.edge.EdgeNode._get_isCurrent (12:46:24.401):
aria props = label=Allowed apps, System settings, Press right to switch preview;selected=true;
IO - speech.speak (12:46:24.401):
Speaking [LangChangeCommand ('en_GB'), u'Allowed apps, System settings, Press right to switch preview  1 of 4']
DEBUG - NVDAObjects.UIA.edge.EdgeNode._get_isCurrent (12:46:24.908):
aria props = label=Allowed apps, System settings, Press right to switch preview;selected=true;
IO - speech.speak (12:46:24.908):
Speaking [LangChangeCommand ('en_GB'), u'Allowed apps, System settings, Press right to switch preview  1 of 4']
DEBUG - NVDAObjects.UIA.edge.EdgeNode._get_isCurrent (12:46:25.315):
aria props = label=Allowed apps, System settings, Press right to switch preview;selected=true;
IO - speech.speak (12:46:25.315):
Speaking [LangChangeCommand ('en_GB'), u'Allowed apps, System settings, Press right to switch preview  1 of 4']
```

**Comment by Adriani90** [comment]
@DataTriny, @XLTechie can you still reproduce this in NVDA 2019.3.1 or 2020.1 Beta on Windows 10 1909?
I am using last Alpha version and am not able to reproduce. I remember that I could definitely reproduce it on Windows 1809 but this is long time ago.

**Comment by ruifontes** [comment]
Yes, still occurs intermitently...


Rui Fontes


Às 20:19 de 20/04/2020, Adriani90 escreveu:

**Comment by Adriani90** [comment]
@ruifontes how is it now under Windows 10 2004 update and NVDA 2020.3?

**Comment by XLTechie** [comment]
I still get this every once in a while.  Usually right after startup, or when 
invoking while the system is under heavy load.

Not often though, and I can't predict it. Might go many days between events.

**Comment by CyrilleB79** [comment]
I also have it regularly with Windows 10 1809. It seems that it occurs when I have been using Firefox (or maybe also Chrome) but I am not so sure. I will try to pay attention on context when it happens again.
I will also see if it happens on Windows 20 2004.

**Comment by josephsl** [comment]
Hi,

Any upodates in August 2021?

Thanks.

**Comment by DataTriny** [comment]
Hello all,

I didn't encounter the bug recently so I thought it was somewhat fixed. But it just happened again today.

Here is an annotated log.
[log.txt](https://github.com/nvaccess/nvda/files/7084022/log.txt)

Strangely the press to the Windows key does not appear, just like @XLTechie  already mentioned.

- Windows version: 21H1 build 19043.1165,
- NVDA 2021.1 installed,
- Unfortunately some add-ons were enabled,
- Other software: I had several things running, notably a Windows Command Prompt which had the focus at the time.

**Comment by CyrilleB79** [comment]
I have just had the issues and took two logs of the following STR:
* press NVDA+shift+control+F1 to start registering the log
* press Windowskey (left) to open start menu
  The start menu seems to open but the search field is not focused
* press Windows key (left) to close the start menu
* press NVDA+shift+control+F1 to copy the registered log in the clipboard

I have taken two logs of this STR, unfortunately with add-ons:
* [StartMenuIssue.txt](https://github.com/nvaccess/nvda/files/7096739/StartMenuIssue.txt): a log in debug mode
* 
[StartMenuIssue(hwIO, MSAA, UIA, timeSinceInput).txt](https://github.com/nvaccess/nvda/files/7096751/StartMenuIssue.hwIO.MSAA.UIA.timeSinceInput.txt): the same STR with additional log categories, in case it helps

As written in the previous comments, the pressed Windows key does not appear in the log.

**Comment by fernando-jose-silva** [comment]
I upgraded to windows 11 22000.176, and I can reproduce this problem easily, if I understand the problem well.
steps to reproduce
open start menu, press esc to close start menu.
so far so good.
open the start menu again:
what happens
nvda stay silent
expected
nvda should announce the opening of the start menu and the search field.
even with nvda mute if I type something and press enter to open windows opens, which shows that the search field was in focus, but nvda does not recognize this.
if i press tabe and shift + tabe nvda recognizes the search field and works normally.
attached log. 
[start.txt](https://github.com/nvaccess/nvda/files/7103412/start.txt)

**Comment by DataTriny** [comment]
Hi @fernando-jose-silva ,

One of my machines is also running a Windows 11 preview version and I have encountered the bug you describe several times. But I am convinced that these are two separated issues.

On Windows 10, when the bug occurs, the search bar seems to not even be part of the navigation tree. In fact, when the Start Menu opens, another element get the focus instead.

**Comment by fernando-jose-silva** [comment]
thank you very much, you have reason, i will open another one called for windows 11 error. Thank you very much.

**Comment by Adriani90** [comment]
See #12809.

**Comment by Adriani90** [comment]
I think I could isolate this issue with NVDA 2024.1 RC1 and all add-ons disabled on Windows 11 23 H2.
It is related to IA2 in process initialization, not installing IA2 support due to the process being suspendable. Following error is written to the log:

```
IO - inputCore.InputManager.executeGesture (21:31:23.039) - winInputHook (18580):
Input: kb(laptop):windows+m
IO - inputCore.InputManager.executeGesture (21:31:23.611) - winInputHook (18580):
Input: kb(laptop):downArrow
IO - speech.speech.speak (21:31:23.629) - MainThread (11456):
Speaking ['Google Chrome Canary', '4 von 8', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (21:31:23.629) - MainThread (11456):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (21:31:23.629) - MainThread (11456):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (21:31:23.629) - MainThread (11456):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1631, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1546, in _get__IA2Relations
NotImplementedError
IO - inputCore.InputManager.executeGesture (21:31:23.879) - winInputHook (18580):
Input: kb(laptop):upArrow
IO - speech.speech.speak (21:31:23.893) - MainThread (11456):
Speaking ['Firefox', '3 von 8', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (21:31:23.894) - MainThread (11456):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
DEBUG - NVDAObjects.IAccessible.IAccessible._get__IA2Relations (21:31:23.894) - MainThread (11456):
Not an IA2.IAccessible2
DEBUG - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (21:31:23.894) - MainThread (11456):
Unable to fetch _IA2Relations
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1631, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1546, in _get__IA2Relations
NotImplementedError
IO - inputCore.InputManager.executeGesture (21:31:24.666) - winInputHook (18580):
Input: kb(laptop):downArrow
DEBUGWARNING - RPC process 16632 (StartMenuExperienceHost.exe) (21:31:24.686) - Dummy-39 (18612):
Thread 4520, build\x86_64\remote\ia2Support.cpp, IA2Support_inProcess_initialize, 177:
Not installing IA2 support as  process is suspendable

IO - inputCore.InputManager.executeGesture (21:31:24.977) - winInputHook (18580):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:31:25.322) - winInputHook (18580):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:31:25.606) - winInputHook (18580):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:31:25.942) - winInputHook (18580):
Input: kb(laptop):escape
IO - inputCore.InputManager.executeGesture (21:31:27.419) - winInputHook (18580):
Input: kb(laptop):escape
IO - inputCore.InputManager.executeGesture (21:31:29.496) - winInputHook (18580):
Input: kb(laptop):NVDA+f1
```


Note: after speaking "Firefox" I pressed the Windows key to open the start menu, then the IA2 support not being installejd has been written to the log, and arrow keys or escape key resulted in NVDA being silent.
You cannot see the press of the windows key in the log because this key is not being logged at all for what ever reason.

I wonder if there is something invisible getting the focus before the start menu appears after pressing the Windows key? I have Asus hotPlug Controller installed, this program is a standard program on Asus machines and the focus is often redirected to an invisible object of Asus Hotplug Controler when closing different windows, also when pressing escape to close the start menu. But this does not happen when opening different windows. Not sure if it happens though in this case.

cc: @josephsl any idea on this one?

**Comment by Adriani90** [comment]
I cannot reproduce this anymore with NVDA alpha-53273,a6a536eb (2026.1.0.53273) on Windows 11 25 H2.
@DataTriny or anyone else, are you able to reproduce this on Windows 11 25 H2?

**Comment by DataTriny** [comment]
Hi @Adriani90, I cannot reproduce this on Windows 11 2025H2. I still have a Windows 10 machine where this bug happens quite frequently though. Given that Windows 10 has now reached its end of life, I'm not sure if this issue should be kept open.

**Comment by Adriani90** [comment]
There will no longer be accessibility on win10, so I am closing as works for me on Win11. If anyone can reproduce this on Win11, please comment and we can reopen.

**Comment by seanbudd** [comment]
Hi @Adriani90 - we are still supporting Windows 10. As per our [legacy issues](https://github.com/nvaccess/nvda/blob/master/projectDocs/issues/triage.md#legacy-issues) policy, we keep issues like this open in the case that the community can fix it on NVDA's side. Once NVDA no longer supports Windows 10, we can close this

**Comment by Adriani90** [comment]
Fair enough, I just think there is no way NVDA can fix it, to my understanding the startmenu opens, but the system focus needs to be redirected properly and so it needs an external fix. I doubt Microsoft will provide anything here given the fact that it works as expected in Windows 11.
