### ISSUE TITLE
NVD fails to list formulas in a particular Excel sheet

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9780]
### Steps to reproduce:
1. Open an Exce file in question I cannot share it here @michaelDCurran  would it be ok to send it to info(at)nvaccess.org?
2. Open elements list.
3. switch to Formulas.
### Actual behavior:
The list is empty even though the sheet contains formulas. In addition the following is written in the log
ERROR - RPC process 7388 (EXCEL.EXE) (12:21:41.757):
Thread 7428, build\x86\remote\excel.cpp, nvdaInProcUtils_excel_getCellInfos::<lambda_a3c86ee69f81a35a54e78746d987966c>::operator (), 478:
application.range failed. Code -2146827284, rangeAddress '[file_name.xlsx]A1'!$L$3:$M$24,$W$3:$Y$24

### Expected behavior:
The formulas should be listed.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-17697,1d50498c

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Microsoft Excel 32-bit in Polish
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes in 2018.4 it works ok but  fails in 2019.1 so it looks like a regression from Excel speedups.

**Comment by Qchristensen** [comment]
Which version of Excel are you using?  I'm using Office 365 Version: 
16.0.12430.20198.

It looks like the bug is that NVDA won't populate the elements list if cells are selected.  In the workbook you emailed me, A2:B24 were selected.  Leaving these selected, nothing appears in the formula list in the elements list.  If you unselect these, the list populates as expected.

It doesn't seem to be anything to do with that specific workbook, I could replicate it by opening a blank workbook, writing =A2 in A1, selecting A1:A2 and opening the elements list, then pressing ALT+R to jump to the formulas page.  Here is the log fragment from when I pressed ALT+R in the elements list:

IO - inputCore.InputManager.executeGesture (12:52:30.806) - winInputHook (4480):
Input: kb(desktop):alt+r
ERROR - queueHandler.flushQueue (12:52:30.828) - MainThread (20352):
Error in func initElementType from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "browseMode.pyc", line 960, in initElementType
  File "NVDAObjects\window\excel.pyc", line 552, in _iterNodesByType
  File "NVDAObjects\window\excel.pyc", line 1117, in __init__
AttributeError: 'ExcelSelection' object has no attribute 'excelCellInfo'
IO - speech.speak (12:52:30.839) - MainThread (20352):
Speaking [LangChangeCommand ('en_US'), 'Type:', 'grouping']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (12:52:30.853) - MainThread (20352):
Begin processing speech
IO - speech.speak (12:52:30.855) - MainThread (20352):
Speaking [LangChangeCommand ('en_US'), 'Formulas', 'radio button', 'checked', 'Alt+r']

I confirm that I could access the elements list in 2018.4.1 in this situation, but not in 2019.1.1 or newer (2019.3.1).

**Comment by lukaszgo1** [comment]
I am on Excel 2010. No matter if cells are selected or not I am getting the error from the issue description.
