### ISSUE TITLE
Python 3: comparison error in start menu

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9842]
### Steps to reproduce:
1. Open the Windows 10 1903 start menu from a threshold_py3_staging snapshot
2. Enter a term that doesn't lead to results in the stat menu
2. Press down arrow

### Actual behavior:
The following error is logged:

```
ERROR - scriptHandler.executeScript (14:23:03.058):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_StartMenuSearchFieldSearchFieldEditableTextWithoutAutoSelectDetectionUIA object at 0x043F3E90>> with gesture 'down arrow'
Traceback (most recent call last):
  File "scriptHandler.py", line 189, in executeScript
    script(gesture)
  File "editableText.py", line 187, in script_caret_moveByLine
    self._caretMovementScriptHelper(gesture, textInfos.UNIT_LINE)
  File "editableText.py", line 146, in _caretMovementScriptHelper
    self._caretScriptPostMovedHelper(unit,gesture,newInfo)
  File "editableText.py", line 130, in _caretScriptPostMovedHelper
    speech.speakTextInfo(info, unit=speakUnit, reason=controlTypes.REASON_CARET)
  File "speech\__init__.py", line 768, in speakTextInfo
    textWithFields=info.getTextWithFields(formatConfig)
  File "NVDAObjects\UIA\__init__.py", line 647, in getTextWithFields
    fields=list(self._getTextWithFieldsForUIARange(self.obj.UIAElement,self._rangeObj,formatConfig))
  File "NVDAObjects\UIA\__init__.py", line 637, in _getTextWithFieldsForUIARange
    for field in self._getTextWithFields_text(textRange,formatConfig):
  File "NVDAObjects\UIA\__init__.py", line 461, in _getTextWithFields_text
    field=self._getFormatFieldAtRange(tempRange,formatConfig,ignoreMixedValues=len(furtherUIAFormatUnits)==0)
  File "NVDAObjects\UIA\__init__.py", line 238, in _getFormatFieldAtRange
    if UIAHandler.StyleId_Heading1<=styleIDValue<=UIAHandler.StyleId_Heading9:
TypeError: '<=' not supported between instances of 'int' and 'POINTER(IUnknown)'
```

### Expected behavior:
No error

**Comment by feerrenrut** [comment]
Closed with  3e04309
