### ISSUE TITLE
Chromium-based browsers 76 and above: Error when focusing certain text fields with an active braille display

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#9872]
### Steps to reproduce:

1. Run latest NVDA alpha snapshot, or NVDA 2019.2beta, or NVDA 2019.1.1, have any braille display connected, and Chrome 76 beta, 77 Canary, or Microsoft Edge Dev or Canary builds. Anything that is chromium-based and has a version number 76 or higher, 75 does not seem to be affected.
2. Open [the Twitter PWA](https://mobile.twitter.com) and log in.
3. Turn off reading mode and press n to start a new tweet.
4. Press Tab to focus the Insert Emoji button.
5. Press Shift+Tab to go back to the text field.

### Actual behavior:

The alpha version produces a log like this:

IO - inputCore.InputManager.executeGesture (09:32:42.326):
Input: kb(laptop):shift+tab
IO - braille.BrailleBuffer.update (09:32:42.469):
Braille regions text: [u'sltr Emoji hinzuf\xfcgen ']
IO - braille.BrailleHandler.update (09:32:42.469):
Braille window dots: 234 123 2345 1235 - 157 134 135 245 24 -
ERROR - eventHandler.executeEvent (09:32:42.569):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x053D3DF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1501, in event_gainFocus
  File "treeInterceptorHandler.pyc", line 128, in _set_passThrough
  File "review.pyc", line 127, in setCurrentMode
  File "api.pyc", line 196, in setReviewPosition
  File "braille.pyc", line 1969, in handleReviewMove
  File "braille.pyc", line 1845, in _doNewObject
  File "braille.pyc", line 1519, in getFocusRegions
  File "braille.pyc", line 956, in update
  File "braille.pyc", line 811, in _addTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 342, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 305, in _getText
IndexError: pop from empty list
ERROR - eventHandler.executeEvent (09:32:42.631):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x053D3DF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1234, in event_caret
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 183, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1468, in event_caret
  File "NVDAObjects\__init__.pyc", line 1069, in event_caret
  File "braille.pyc", line 1880, in handleCaretMove
  File "braille.pyc", line 1845, in _doNewObject
  File "braille.pyc", line 1519, in getFocusRegions
  File "braille.pyc", line 956, in update
  File "braille.pyc", line 811, in _addTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 342, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 305, in _getText
IndexError: pop from empty list

And when then pressing NVDA+F1 to get the developer info for the focused control, this happens:

IO - inputCore.InputManager.executeGesture (09:32:44.503):
Input: kb(laptop):NVDA+f1
DEBUGWARNING - watchdog._watcher (09:32:49.023):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyc", line 519, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1003, in Notify
  File "core.pyc", line 490, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "scriptHandler.pyc", line 150, in _queueScriptCallback
  File "scriptHandler.pyc", line 192, in executeScript
  File "globalCommands.pyc", line 1544, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1174, in info
  File "logHandler.pyc", line 138, in _log
  File "gui\logViewer.pyc", line 113, in activate

In addition, the braille display no longer tracks the caret, speech does. And the braille display shows either the first line of the edit field, or the info for the last focused control. This is different each time.

### Expected behavior:

None of the above, the display should just follow the caret and input as usual.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

Latest alpha snapshot, which produces the error sound and also the log entries. 2019.2beta and 2019.1.1 also show this behavior, but without the error sound and no traceback log entries.

#### Windows version:

19h1.

#### Name and version of other software in use when reproducing the issue:

Chrome 76 beta, 77 Canary, Microsoft Edge dev or Canary, both chromium-77-based.

#### Other information about your system:

Reproduced with both a Handy Tech Actilino as well as a Freedom Scientific Focus 40 Blue 5th generation on two machines.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

See above.

**Comment by lukaszgo1** [comment]
@MarcoZehe Is this still occurring?

**Comment by MarcoZehe** [comment]
Can no longer reproduce with Edge 80 and NVDA 2019.3.1 or 2020.1Alpha.
