### ISSUE TITLE
Python 3: AttributeError: module 'NVDAObjects.UIA.edge' has no attribute 'EdgeHTMLRootContainer'

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9880]
### Steps to reproduce:
Nothing very reliable. Searching in the windows 10 start menu something shows this issue.

### Actual behavior:
The following traceback is in the log:

```
ERROR - eventHandler.executeEvent (18:41:16.639):
error executing event: UIA_controllerFor on <NVDAObjects.Dynamic_StartMenuSearchFieldSearchFieldEditableTextWithoutAutoSelectDetectionUIA object at 0x03FDD950> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1667, in event_UIA_controllerFor
  File "baseObject.pyc", line 46, in __get__
  File "baseObject.pyc", line 149, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1451, in _get_controllerFor
  File "NVDAObjects\__init__.pyc", line 83, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 799, in findOverlayClasses
AttributeError: module 'NVDAObjects.UIA.edge' has no attribute 'EdgeHTMLRootContainer'
```

Note that this is an existing class, it can be found just fine when working with the python console. Therefore this error is pretty odd.

### Expected behavior:
No error

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
threshold_py3_staging-17954

#### Windows version:
10.0.18922.1000

#### Other information about your system:
Insider build

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Ye,s haven't seen this issue on Alpha.

**Comment by josephsl** [comment]
Hi,

Is this resolved?

Thanks.

**Comment by leonardder** [comment]
No, though I've seen it only once in the last few weeks. Problem is that I really do not understand what's happening here.

**Comment by leonardder** [comment]
I haven't seen this lately. Closing as works for me, will reopen if I have something reliable to test with.
