### ISSUE TITLE
Python 3: Erorr on the Windows 10 lock screen

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9883]
### Steps to reproduce:
End up at the lock screen after an update with auto logon enabled.

### Actual behavior:
The following error is written to the log when starting to navigate:

```
ERROR - appModuleHandler.fetchAppModule (08:27:25.426):
error in appModule 'lockapp'
Traceback (most recent call last):
  File "appModuleHandler.pyc", line 173, in fetchAppModule
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "appModules\lockapp.pyc", line 25, in <module>
  File "appModules\lockapp.pyc", line 37, in AppModule
AttributeError: 'function' object has no attribute '__func__'
```

### Expected behavior:
No error

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
threshold_py3_staging-17954

#### Windows version:
Windows 10.0.18932.1000

#### Other information about your system:
Insider build

**Comment by feerrenrut** [comment]
Fixed with commit 200a7a6 in #9884
