### ISSUE TITLE
Microsoft Edge Dev (Chromium): errors raised when moving through menus when reporting table headers is enabled

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#9926]
Originally reported by @bramd

### Steps to reproduce:
1. Enable table row/column headers in NVDA's document formatting settings
2. Use Microsoft Edge Dev

### Actual behavior:
When moving through Edge's interface, the following error is logged:

```ERROR - eventHandler.executeEvent (08:22:17.802):
error executing event: gainFocus on <NVDAObjects.Dynamic_MenuItemIa2WebIAccessible object at 0x0500DBD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\Leonard de Ruijter\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 661, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1850, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1030, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 918, in reportFocus
  File "speech.pyc", line 416, in speakObject
  File "speech.pyc", line 289, in speakObjectProperties
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1092, in _get_rowNumber
COMError: (-2147467259, 'Niet nader omschreven fout', (None, None, None, 0, None))
```

The English translation of this error is "Unspecified error'"

### Expected behavior:
NO errors

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-17928

#### Windows version:
Windows 10 1903 build 18362.239
\
#### Name and version of other software in use when reproducing the issue:
Microsoft Edge Dev 77.0.211.3 (Official build) dev (64-bit)

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by leonardder** [comment]
I can no longer reproduce this.
